@ TRANSLATED

BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Hvad en TRÆNER har brug for…\p"
	.string "Viden…\n"
	.string "Strategi…\l"
	.string "Lyd…\l"
	.string "Tarmene…\l"
	.string "Ånd…\l"
	.string "Mod…\l"
	.string "Og evne…\p"
	.string "Nå, jeg er klar på alle måder!\n"
	.string "Jeg vil være ustoppelig på ethvert bygning!\p"
	.string "Hva'? POKéMON?\n"
	.string "Hvad er det?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Kender du til FRONTIER\n"
	.string "BRAINS?\p"
	.string "Det er hvad SCOTT kalder de syv\n"
	.string "særlige TRÆNERE, der styrer de syv\n"
	.string "faciliteter i BATTLE FRONTIER.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "Ved KAMPENS TÅRN fortalte en ældre pige\n"
	.string "mig, at jeg har masser af talent\l"
	.string "til at kæmpe!\p"
	.string "Jeg foretrækker POKéMON-KONKURRENCER!\p"
	.string "Men jeg er ikke god til KONKURRENCER!\p"
	.string "Jeg antager, at talent og at kunne\n"
	.string "lide noget ikke er det samme.$"



