@ TRANSLATED

SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Der ser ud til at være en forbindelse\n"
	.string "mellem SOOTOPOLIS og MT. PYRE.\p"
	.string "Mine venner og jeg lavede nogle\n"
	.string "undersøgelser på det laboratorium, hvor\l"
	.string "jeg plejede at arbejde.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
.string "Min storebror plejede at studere havet.$"



