@ TRANSLATED

BattleFrontier_Lounge4_MapScripts::
	.byte 0

BattleFrontier_Lounge4_EventScript_Woman::
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Cook::
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Man::
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring:
	.string "Jeg spekulerer på, om de vil vise interviews\n"
	.string "med TUFFE TRÆNERE i dag?$"

BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere:
	.string "Hvis jeg åbnede en restaurant her, ville den\n"
	.string "helt sikkert tjene penge.$"

BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles:
	.string "Puha…\p"
	.string "Jeg har brug for at trække vejret efter\n"
	.string "nogle intense kampe…\p"
	.string "Men selv nu tager jeg aldrig en pause fra at\n"
	.string "planlægge strategi og kombinationer.$"



