@ TRANSLATED

RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "TRÆNERENS SKOLE er fantastisk.\p"
	.string "Hvis du studerer der, kan du endda blive en\n"
	.string "GYM-LEDER.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "ROXANNE, GYM-lederen, ved virkelig meget\n"
	.string "om POKéMON.\p"
	.string "Hun er også virkelig stærk!$"



