@ TRANSLATED

PacifidlogTown_House1_MapScripts::
	.byte 0

PacifidlogTown_House1_EventScript_Man::
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
	end

PacifidlogTown_House1_EventScript_Woman::
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
	end

PacifidlogTown_House1_Text_RegiStory:
	.string "I HOENN-regionen er der tre POKéMON, som\n"
	.string "repræsenterer kraften af sten, is og stål.\p"
	.string "Det siges, at hver af dem gemmer sig dybt\n"
	.string "inde i huler.\p"
	.string "Det er historien, jeg hørte, da jeg var bare\n"
	.string "en lille unge.$"

PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
	.string "“Seks prikker åbner tre døre.”\p"
	.string "Bedstefar plejede at sige det, men jeg ved\n"
	.string "ikke, hvad han mente.$"



