gText_ApprenticeChallenge0::
	.string "Øhm, jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling.\n"
	.string "Snøft… Denne spænding er for meget for mig…$"

gText_ApprenticeChallenge1::
	.string "Jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling!\n"
	.string "Her kommer vi!$"

gText_ApprenticeChallenge2::
	.string "Jeg er nr. {STR_VAR_2} lærling for {STR_VAR_1}!\n"
	.string "Accepter min udfordring!$"

gText_ApprenticeChallenge3::
	.string "Øhm… Jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling…\n"
	.string "Tror du, at en som mig kan vinde?$"

gText_ApprenticeChallenge4::
	.string "Jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling!\n"
	.string "Jeg lader dig udfordre mig!$"

gText_ApprenticeChallenge5::
	.string "Jeg har frygteligt travlt, men jeg er også\n"
	.string "{STR_VAR_1}s nr. {STR_VAR_2} lærling.$"

gText_ApprenticeChallenge6::
	.string "Jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling.\n"
	.string "Glad for at møde dig!$"

gText_ApprenticeChallenge7::
	.string "Jeg tjener som {STR_VAR_1}s nr. {STR_VAR_2} lærling.\n"
	.string "Må jeg begynde?$"

gText_ApprenticeChallenge8::
	.string "Uuh! Jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling!\n"
	.string "Jeg vil gøre mit bedste!$"

gText_ApprenticeChallenge9::
	.string "Yeehaw! Jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling!\n"
	.string "Gør dig klar!$"

gText_ApprenticeChallenge10::
	.string "Jeg er {STR_VAR_1}s 1.000. lærling!\n"
	.string "Faktisk er jeg nr. {STR_VAR_2}! Nu går det løs!$"

gText_ApprenticeChallenge11::
	.string "Ja, jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling!\n"
	.string "Lad os rocke og rulle!$"

gText_ApprenticeChallenge12::
	.string "Yippee-yahoo! Jeg er, hvad du kalder\n"
	.string "{STR_VAR_1}s nr. {STR_VAR_2} lærling!$"

gText_ApprenticeChallenge13::
	.string "Host! Jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling.\n"
	.string "Godt at møde dig! Host!$"

gText_ApprenticeChallenge14::
	.string "Dette er nervepirrende…\n"
	.string "Jeg er nr. {STR_VAR_2} lærling for {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Jeg er {STR_VAR_1}s nr. {STR_VAR_2} lærling,\n"
	.string "og det er ingen løgn.$"

gText_ApprenticePleaseTeach0::
	.string "Er du… {PLAYER}?\n"
	.string "Åh! Sniff…snøft…\p"
	.string "Åh! Undskyld…\n"
	.string "Jeg er så nervøs, jeg kan ikke holde op med at græde…\p"
	.string "Jeg er {STR_VAR_1}, og jeg ser virkelig op\n"
	.string "til dig, {PLAYER}.\p"
	.string "Jeg… Jeg havde denne drøm om en dag at møde\n"
	.string "dig og spørge dig om POKéMON.\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Please teach me about POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Åh… M-men…\n"
	.string "Snøft… Waaah!\p"
	.string "Please!\n"
	.string "Jeg beder dig, please!$"

gText_ApprenticeWhichLevelMode0::
	.string "Åh, virkelig? Vil du?\n"
	.string "Fantastisk! Fedt! Awoooh!\p"
	.string "Åh… Undskyld…\n"
	.string "Jeg er så glad, jeg græder…\p"
	.string "Øhm… Så fortæl mig venligst!\n"
	.string "Det handler om BATTLE TOWER.\p"
	.string "Hvilket ville være bedre for mig: Level 50\n"
	.string "eller Open Level?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Åh! Jeg er så ked af det!\n"
	.string "Du har gjort mig glad ved at vælge\l"
	.string "niveauet for mig, og det har gjort mig rørt…\p"
	.string "Snøft…\n"
	.string "Mange tak!\l"
	.string "Please talk with me again!$"

gText_ApprenticePleaseTeach1::
	.string "Wowee! Du er {PLAYER}, ikke sandt?\n"
	.string "Du er utrolig stærk, ikke sandt?\p"
	.string "Jeg er {STR_VAR_1}!\n"
	.string "Jeg er lige blevet en TRAINER!\p"
	.string "Please, {PLAYER}!\n"
	.string "Kan du være min lærer og fortælle mig\l"
	.string "masser om at være TRAINER?$"

gText_ApprenticeRejectTeaching1::
	.string "Øv, hvorfor?\n"
	.string "Åh, please? Pretty please?\l"
	.string "Please be my teacher, please!$"

gText_ApprenticeWhichLevelMode1::
	.string "Yay! Fantastisk!\p"
	.string "Det første, jeg ville spørge dig om, er\n"
	.string "om BATTLE TOWER!\p"
	.string "Level 50 og Open Level Rooms…\n"
	.string "Hvilket ville være perfekt for mig?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, ikke sandt? Det er sandt!\n"
	.string "Jeg vil gøre mit bedste der!\p"
	.string "Hvis vi mødes her igen, please teach\n"
	.string "mig noget andet, lærer!$"

gText_ApprenticePleaseTeach2::
	.string "Øhm… Er du {PLAYER}?\n"
	.string "Mit navn er {STR_VAR_1}.\p"
	.string "Jeg vil gerne blive en POKéMON TRAINER,\n"
	.string "men jeg ved ikke, hvad jeg skal gøre…\p"
	.string "Så jeg tænkte måske, jeg kunne spørge dig om\n"
	.string "råd, fordi du er så berømt.\p"
	.string "{PLAYER}, kunne du give mig råd?$"

gText_ApprenticeRejectTeaching2::
	.string "Åh, men…\p"
	.string "Jeg vil virkelig gerne blive en POKéMON\n"
	.string "TRAINER!\p"
	.string "Please, kan du besvare mine spørgsmål?$"

gText_ApprenticeWhichLevelMode2::
	.string "Tak!\n"
	.string "Her er mit første spørgsmål med det samme!\p"
	.string "BATTLE TOWER har to niveauer,\n"
	.string "Level 50 og Open Level, ikke?\p"
	.string "Hvilket niveau tror du er mere\n"
	.string "passende for mig?$"

gText_ApprenticeLevelModeThanks2::
	.string "Åh, {STR_VAR_1} udfordring?\n"
	.string "Forstået!\p"
	.string "Hvis jeg har et andet spørgsmål, kommer jeg\n"
	.string "tilbage her for at få dit råd!$"

gText_ApprenticePleaseTeach3::
	.string "Åh? Hvad? Du er…\n"
	.string "Nej, det kan ikke passe.\p"
	.string "Der er ingen måde, at en som\n"
	.string "mig kunne møde {PLAYER}.\p"
	.string "…Er du virkelig {PLAYER}?\n"
	.string "Jeg kan ikke tro, jeg taler med dig!\p"
	.string "Når noget så godt sker,\n"
	.string "vil kun frygtelige ting ske for mig\l"
	.string "nu, jeg ved det bare…\p"
	.string "…Jeg er ked af det…\n"
	.string "Jeg er… {STR_VAR_1}…\p"
	.string "Der er intet specielt ved mig,\n"
	.string "som jeg kan være stolt af…\p"
	.string "Jeg burde ikke engang sige noget\n"
	.string "om mig selv, fordi du vil glemme det…\p"
	.string "Jeg havde en drøm om, at hvis jeg\n"
	.string "nogensinde mødte dig, {PLAYER}, så\l"
	.string "kunne jeg måske bede dig om råd som\l"
	.string "en TRÆNER.\p"
	.string "Men jeg tror ikke, du vil gå med\n"
	.string "til det.\p"
	.string "…Eller vil du være så venlig at\n"
	.string "give mig råd?$"

gText_ApprenticeRejectTeaching3::
	.string "Jeg vidste det…\p"
	.string "Det måtte ske, fordi jeg er sådan\n"
	.string "en virkelig kedelig person…\p"
	.string "Men jeg tænkte bare måske…\n"
	.string "Du vil ikke genoverveje, vil du?\p"
	.string "Men jeg kan ikke give op sådan.\n"
	.string "Jeg vil spørge dig, mens jeg stadig\n"
	.string "er heldig!\p"
	.string "Vil du være så venlig at give\n"
	.string "mig råd?$"
gText_ApprenticeWhichLevelMode3::
	.string "Virkelig? Jeg kan ikke tro det!\n"
	.string "Jeg kan ikke tro, du vil rådgive mig!\l"
	.string "Jeg… Jeg er så glad…\p"
	.string "Det, jeg vil spørge dig om, er virkelig\n"
	.string "banalt, men jeg kan ikke beslutte mig…\p"
	.string "Ved KAMP TÅRNET lader de dig vælge\n"
	.string "Level 50 eller Åben Level.\p"
	.string "Hvilket kursus tror du, jeg måske\n"
	.string "har en chance ved?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Okay!\n"
	.string "Men tror du virkelig, at en som\l"
	.string "mig ville have en chance?\p"
	.string "Jeg vil gøre mit bedste, selvom jeg\n"
	.string "ikke tror, det vil lykkes.\p"
	.string "Mange tak for at bruge tid med\n"
	.string "en som mig.$"

gText_ApprenticePleaseTeach4::
	.string "Åh! Du er {PLAYER}{KUN}, er du ikke?\p"
	.string "Jeg har hørt, at du er god til\n"
	.string "POKéMON!\p"
	.string "Jeg er {STR_VAR_1}!\n"
	.string "Jeg vil være din ven!\p"
	.string "Vidste du?\p"
	.string "Du kan ikke vinde ved BATTLE FRONTIER,\n"
	.string "hvis alt du ved, er hvad de lærer på\n"
	.string "TRÆNER SKOLEN.\p"
	.string "Jeg er villig til at lytte til dine råd.\n"
	.string "Du vil selvfølgelig være enig, ikke?$"

gText_ApprenticeRejectTeaching4::
	.string "Hvad? Hvorfor afviser du mig?\n"
	.string "Det er mig, der spørger dig!\l"
	.string "Du er nødt til at genoverveje!$"

gText_ApprenticeWhichLevelMode4::
	.string "Okay, så der er noget her.\n"
	.string "Jeg vil have, at du beslutter for mig.\p"
	.string "Du ved, at BATTLE TOWER har\n"
	.string "Level 50 og Åben Level Rum?\p"
	.string "Hvilket tror du ville være godt\n"
	.string "for mig, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Okay, {STR_VAR_1} er passende for mig?\n"
	.string "Tak!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så\n"
	.string "ked af det, hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticePleaseTeach5::
	.string "Åh, hej der! {PLAYER}{KUN}!\n"
	.string "Jeg kender dig, fordi du er berømt!\l"
	.string "Kald mig {STR_VAR_1}! Glad for at møde dig!\p"
	.string "Jeg er en TRIATHLET, så jeg holder mig\n"
	.string "i form, selv mens jeg træner POKéMON.\p"
	.string "Jeg er også involveret i andre ting\n"
	.string "som arbejde, lur, selskabsdans…\p"
	.string "Når jeg er så travl, er det ikke så nemt\n"
	.string "for mig at blive en ordentlig TRÆNER.\p"
	.string "Så jeg har et forslag!\p"
	.string "Der må være en grund til, at vi mødtes.\n"
	.string "Så, {PLAYER}{KUN}, hvad med at dele din\l"
	.string "visdom med mig en gang imellem?$"

gText_ApprenticeRejectTeaching5::
	.string "Åh, men, vær sød?\n"
	.string "En fyr som mig har brug for en som\l"
	.string "dig, {PLAYER}{KUN}!\p"
	.string "Ærligt talt, jeg har brug for dit råd!$"

gText_ApprenticeWhichLevelMode5::
	.string "Tak! Det er mere som det skal være!\n"
	.string "Så lad os starte med en nem en!\p"
	.string "Du kender til BATTLE TOWERs\n"
	.string "to baner, ikke?\l"
	.string "Du ved, Level 50 og Åben Level.\p"
	.string "Mig som en travl fyr, hvilken en skal\n"
	.string "jeg forberede mig til?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, huh? Okay, forstået.\n"
	.string "Jeg finder tid på en eller anden måde og prøver!\p"
	.string "…Ups, jeg må hellere komme på arbejde!\n"
	.string "Tak! Vi ses!$"

gText_ApprenticePleaseTeach6::
	.string "Det kan ikke være rigtigt!\n"
	.string "Er du måske den ægte {PLAYER}?\p"
	.string "A-hah! Fantastisk! Jeg er {STR_VAR_1},\n"
	.string "glæder mig til at møde dig!\p"
	.string "{PLAYER}, du er meget stærk,\n"
	.string "ikke?\p"
	.string "Alle taler om dig!\p"
	.string "Åh! Jeg fik lige en god idé!\n"
	.string "Jeg vil få råd fra dig, {PLAYER}!\l"
	.string "Jeg er sikker på, det vil gøre mig stærkere!\p"
	.string "Er det ikke en god idé?\n"
	.string "Vær sød, jeg vil have dit råd!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, du kan lade som om du er ond,\n"
	.string "men du kan ikke narre mig!\l"
	.string "Du mener virkelig okay, ikke?$"

gText_ApprenticeWhichLevelMode6::
	.string "Yay! Jeg vidste, du havde et stort hjerte,\n"
	.string "{PLAYER}!\p"
	.string "Hvad skal jeg spørge dig først om?\n"
	.string "…Åh, jeg kom i tanke om noget!\p"
	.string "Trommehvirvel, tak!\n"
	.string "Mit spørgsmål er…\p"
	.string "Hvis jeg skulle tage en BATTLE TOWER\n"
	.string "udfordring, hvilken vej skal jeg gå?\p"
	.string "Level 50 eller Åben Level?\n"
	.string "Hvad passer mig bedst?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, siger du!\l"
	.string "Tak for et super sejt svar!\p"
	.string "Jeg tror, det var alt, jeg ville\n"
	.string "spørge dig om i dag.\p"
	.string "Lad os mødes her igen, okay?\n"
	.string "Tak!$"

gText_ApprenticePleaseTeach7::
	.string "Undskyld mig, men…\n"
	.string "Er du {PLAYER}?\p"
	.string "Jeg er {STR_VAR_1}, og jeg er glad for\n"
	.string "at gøre din bekendtskab.\p"
	.string "Jeg har længe beundret dig…\p"
	.string "… … … … … …\p"
	.string "Øhm… Jeg håber ikke, at du finder\n"
	.string "denne anmodning for belastende, men…\p"
	.string "Må jeg blive din lærling,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Åh…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Jeg må være besvimet af chok.\n"
	.string "Jeg er ked af det, jeg må have hørt forkert.\p"
	.string "Vær sød! Sig, at du vil\n"
	.string "acceptere mig som din lærling!$"

gText_ApprenticeWhichLevelMode7::
	.string "Åh… Jeg er henrykt!\p"
	.string "Jeg vil ikke spilde din tid,\n"
	.string "så vær venlig at rådgive mig om dette.\p"
	.string "Jeg planlægger at tage en BATTLE TOWER\n"
	.string "udfordring snart.\p"
	.string "Men der er to niveauer…\p"
	.string "Hvilket vil være mest passende for mig?\n"
	.string "Level 50 eller Åben Level?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} er dit valg!\n"
	.string "Jeg forstår. Jeg vil gøre mit bedste!\p"
	.string "Tak, {PLAYER}.\n"
	.string "Jeg håber, jeg kan regne med dig igen.\l"
	.string "Pas godt på dig selv!$"

gText_ApprenticePleaseTeach8::
	.string "Eek! Eek! {PLAYER}!\n"
	.string "Du talte til mig!\l"
	.string "Jeg… Jeg er overvældet af glæde!\p"
	.string "Mig! Mit navn er {STR_VAR_1}!\n"
	.string "Jeg er lige blevet en TRÆNER!\p"
	.string "Jeg er glad for at have mødt dig, {PLAYER},\n"
	.string "den store navn i POKéMON kredse!\p"
	.string "Åh-åh-åh, jeg ved det!\n"
	.string "Må jeg bede om en stor tjeneste, {PLAYER}?\p"
	.string "Tag mig ind som din lærling!\n"
	.string "Jeg vil lære fra dig!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah!\n"
	.string "{PLAYER} afviste mig…\l"
	.string "Det… Det er en uvurderlig oplevelse!\p"
	.string "{PLAYER}, vær sød! Jeg vil høre\n"
	.string "et bekræftende svar denne gang!\p"
	.string "Jeg beder om din vejledning!$"

gText_ApprenticeWhichLevelMode8::
	.string "Hieeeeh! {PLAYER} sagde ja!\n"
	.string "{PLAYER} sagde ja!\p"
	.string "Jeg vil ikke kunne sove i nat…\n"
	.string "Tusind tak!\p"
	.string "Så, her er mit spørgsmål!\p"
	.string "Ved BATTLE TOWER, hvad er bedst\n"
	.string "for mig, Level 50 eller Åben Level?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Helt forstået!\n"
	.string "Jeg forstår perfekt!\l"
	.string "Jeg er helt vildt glad!\p"
	.string "Jeg håber, du vil være villig til at lære mig\n"
	.string "noget mere en anden gang.$"

gText_ApprenticePleaseTeach9::
	.string "Whoa! Kunne du være…\n"
	.string "Er du måske… {PLAYER}{KUN}?!\l"
	.string "Den stærke og berømte TRÆNER?\l"
	.string "Nå, hej, er jeg ikke bare den heldigste!\p"
	.string "Hej, navnet er {STR_VAR_1}!\p"
	.string "Jeg har været på udkig efter\n"
	.string "en POKéMON lærer.\p"
	.string "Og med upåklagelig timing,\n"
	.string "kom du, {PLAYER}{KUN}!\p"
	.string "Så der har du det, {PLAYER}{KUN}!\n"
	.string "Lad mig blive din lærling!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah!\n"
	.string "Du er ret cool og sej…\p"
	.string "Vær ikke sådan, vær sød.\n"
	.string "Jeg beder dig!$"

gText_ApprenticeWhichLevelMode9::
	.string "Åh, ja! Det er et solidt svar!\n"
	.string "Fremragende, må jeg tilføje!\p"
	.string "Så hvad med et første råd\n"
	.string "om BATTLE TOWER?\p"
	.string "Hvis jeg skulle tage derhen, hvad ville\n"
	.string "så være bedre? Level 50 eller Åben Level?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, {STR_VAR_1} er det!\n"
	.string "OK, A-OK!\l"
	.string "Jeg vil vise mit værd, som, straks!\p"
	.string "Okay, jeg vil se til dig som min mentor!\n"
	.string "Adios!$"

gText_ApprenticePleaseTeach10::
	.string "Åh, hej, {PLAYER}{KUN}, ikke?\n"
	.string "Politiet ledte efter dig!\p"
	.string "… … …\n"
	.string "Selvfølgelig lyver jeg!\p"
	.string "Mig, jeg er {STR_VAR_1}. Trods mit udseende\n"
	.string "er jeg POKéMON MESTER!\l"
	.string "…Det er også en løgn!\p"
	.string "Dette er dog ikke en løgn.\n"
	.string "Jeg er ikke særlig god til at kæmpe.\p"
	.string "Så hvad med at du bliver min mester\n"
	.string "i alt, hvad der angår POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "Hvis du vil være kold som is,\n"
	.string "skal jeg vise dig, hvad jeg gør!\p"
	.string "Waaah! Waaah! Waaah!\n"
	.string "Hik!\p"
	.string "Hahaha, det var mine FALSKE TÅRER!\p"
	.string "Kom nu, vil du ikke nok være\n"
	.string "min POKéMON mester?$"

gText_ApprenticeWhichLevelMode10::
	.string "Jubii!\n"
	.string "Jeg køber dig en båd for det!\p"
	.string "Selvfølgelig lyver jeg igen!\n"
	.string "Men… Tak, mester!\p"
	.string "Du ved, hvordan der er Level 50 og\n"
	.string "Åben Level ved BATTLE TOWER?\p"
	.string "Jeg har svært ved at beslutte, hvilket\n"
	.string "niveau jeg skal udfordre…\p"
	.string "Kan du beslutte for mig, mester?$"

gText_ApprenticeLevelModeThanks10::
	.string "Okay, så {STR_VAR_1} er bedre!\n"
	.string "Jeg går til det andet niveau, så!\p"
	.string "Bare for sjov!\n"
	.string "Jeg vil følge din lære, mester!\p"
	.string "Tak, mester!\n"
	.string "Jeg håber, du vil fortsætte med at lære mig!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y!\n"
	.string "Og det staver ahoy, og det betyder hej!\p"
	.string "Jeg er {STR_VAR_1}, den rappende SØMAND,\n"
	.string "det er mig!\p"
	.string "Din tur nu, fortæl mig lidt om\n"
	.string "dig selv, giv det et forsøg!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "{PLAYER}{KUN} er dit navn,\l"
	.string "og POKéMON er dit spil!\p"
	.string "Og du er i en sart alder,\n"
	.string "hvor hele verden er din scene!\p"
	.string "Alligevel vil jeg bare sige,\n"
	.string "at du er den tiende TRÆNER,\l"
	.string "jeg har talt med i dag.\p"
	.string "Lad os fejre det!\n"
	.string "Bliv min mentor for at markere det!$"

gText_ApprenticeRejectTeaching11::
	.string "Men!\n"
	.string "Du skal arbejde med mig!\p"
	.string "Vær ikke så drilsk!\n"
	.string "Bliv min mentor, vær sød!$"

gText_ApprenticeWhichLevelMode11::
	.string "Det er det!\n"
	.string "{PLAYER}, du har ånden!\p"
	.string "Så her er mit første spørgsmål\n"
	.string "der beder om dit forslag!\p"
	.string "Det handler om BATTLE TOWER,\n"
	.string "og det afhænger af min styrke!\p"
	.string "Level 50 og Åben Level er der,\n"
	.string "hvilket er det, der er godt for mig?$"

gText_ApprenticeLevelModeThanks11::
	.string "Okay, {STR_VAR_1} er det, du siger!\n"
	.string "Jeg vil tage det på min vej!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticePleaseTeach12::
	.string "Sig, hey, er du ikke {PLAYER}?\n"
	.string "Hvad skal jeg gøre? Tale til dig?\l"
	.string "Hvorfor ikke? Jeg taler allerede til dig!\p"
	.string "{PLAYER}, er du overrasket over mig?\n"
	.string "Jeg må hellere fortælle dig, hvem jeg er!\p"
	.string "{STR_VAR_1} er, hvad du kan kalde mig.\n"
	.string "Den lyseste stjerne i guitardom,\l"
	.string "det er mig!\p"
	.string "Modtager du mig?\n"
	.string "Du modtager mig!\p"
	.string "Min held er på sit højeste,\n"
	.string "jeg vil komme med en anmodning!\p"
	.string "{PLAYER}, lad mig være din lærling!\n"
	.string "Jeg vil have, at du lærer mig alt!$"

gText_ApprenticeRejectTeaching12::
	.string "Du afviser mig altså?\n"
	.string "Jeg må bare spørge dig igen!\p"
	.string "{PLAYER}, jeg beder om at blive din lærling!\n"
	.string "Jeg har brug for, at du lærer mig alt!$"

gText_ApprenticeWhichLevelMode12::
	.string "Heldigt, ja, woohoo!\n"
	.string "Skal jeg stille dig et spørgsmål?\p"
	.string "Da vi er nær BATTLE TOWER,\n"
	.string "hvad med et spørgsmål om dets styrke?\p"
	.string "Af de valg du ser,\n"
	.string "hvilket er det rigtige for mig?$"

gText_ApprenticeLevelModeThanks12::
	.string "Hvis {STR_VAR_1} er, hvad du foreslår,\n"
	.string "må det være det allerbedste!\p"
	.string "Nå, {PLAYER}, jeg skal vandre frit,\n"
	.string "men glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticePleaseTeach13::
	.string "Åh, hej! Du der!\n"
	.string "Kan jeg få dig til at massere min skulder?\p"
	.string "…Ja, der! Det er det!\n"
	.string "Av, av! Oooh, det føles godt!\p"
	.string "Mit navn er {STR_VAR_1}.\n"
	.string "Jeg træner karate, men min krop er\l"
	.string "ikke bygget til at tåle det…\p"
	.string "Jeg besluttede mig for at kæmpe med POKéMON\n"
	.string "og gøre mig stærkere.\p"
	.string "Du er {PLAYER}{KUN}, ikke?\n"
	.string "POKéMON LIGA MESTEREN?\p"
	.string "Hør, kan jeg få dig til at give mig\n"
	.string "råd?$"

gText_ApprenticeRejectTeaching13::
	.string "Åh, hvorfor?\p"
	.string "Jeg vil ikke være til stor gene, jeg lover!\n"
	.string "Vær sød?$"

gText_ApprenticeWhichLevelMode13::
	.string "Tak. Rigtig godt af dig!\n"
	.string "…Host! Host!\p"
	.string "Oogh, jeg skal hurtigt blive stærkere…\p"
	.string "Jeg tager direkte til BATTLE TOWER,\n"
	.string "men hvad ville være bedre for mig?\n"
	.string "Level 50 eller Åben Level?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, okay. Det er {STR_VAR_1}.\n"
	.string "Jeg går derhen med det samme.\p"
	.string "Jeg håber, jeg kan blive ved med\n"
	.string "at bede dig om hjælp - du er jo min mentor!$"

gText_ApprenticePleaseTeach14::
	.string "Er… Øhm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Vær venlig ikke at se på mig sådan.\n"
	.string "Du gør mig helt selvbevidst.\p"
	.string "Jeg… Jeg er {STR_VAR_1}.\p"
	.string "Jeg er virkelig flov over at sige dette,\n"
	.string "men jeg udforsker gamle ruiner og sådan.\p"
	.string "Jeg er endnu mere flov over at indrømme,\n"
	.string "at jeg er interesseret i BATTLE FRONTIER.\p"
	.string "{PLAYER}{KUN}, du har ry for\n"
	.string "at være en hård TRÆNER…\p"
	.string "Det er svært for mig at sige dette,\n"
	.string "men jeg vil gerne spørge om noget.\p"
	.string "Kunne du blive min lærer og\n"
	.string "give mig råd?$"

gText_ApprenticeRejectTeaching14::
	.string "Vær venlig ikke at afvise mig sådan!\n"
	.string "Jeg kan ikke leve med ydmygelsen.\p"
	.string "Vær venlig at blive min lærer!\n"
	.string "Jeg har brug for dit råd!$"

gText_ApprenticeWhichLevelMode14::
	.string "Th-thank you…\p"
	.string "Men vær venlig ikke at se på mig sådan.\n"
	.string "Det gør mig helt forfjamsket.\p"
	.string "Vær venlig at svare mig uden at se\n"
	.string "på mine øjne.\p"
	.string "Ved BATTLE TOWER…\n"
	.string "Hvilket niveau skal jeg forsøge?$"

gText_ApprenticeLevelModeThanks14::
	.string "Åh… Okay!\n"
	.string "Jeg vil prøve det.\p"
	.string "Jeg håber, jeg kan udfordre uden\n"
	.string "at blive helt forfjamsket…\p"
	.string "Tak, {PLAYER}{KUN}.\n"
	.string "Hvis vi mødes igen, håber jeg, du vil\l"
	.string "være lige så hjælpsom.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig ægte?\p"
	.string "Du kan kalde mig {STR_VAR_1}.\p"
	.string "Jeg har leget med tanken om at\n"
	.string "blive lærling under en stærk TRÆNER.\p"
	.string "Så jeg må sige, jeg er heldig, at du kom forbi!\n"
	.string "…Du er virkelig {PLAYER}{KUN}, ikke?\p"
	.string "Nej, nej, hvis du er ægte, er det fint.\n"
	.string "Jeg vil blot have dig til at anerkende mig\n"
	.string "som din lærling.$"

gText_ApprenticeRejectTeaching15::
	.string "Åh?\n"
	.string "Men hvad får dig til at afvise?\p"
	.string "Jeg undskylder for at være skeptisk\n"
	.string "om din identitet.\p"
	.string "Vær venlig at acceptere min undskyldning\n"
	.string "og acceptere mig som din lærling.$"

gText_ApprenticeWhichLevelMode15::
	.string "Du accepterer mig virkelig?\n"
	.string "Jeg ønsker ikke at fejre for tidligt.\p"
	.string "Hvis det er sandt, undskylder jeg.\n"
	.string "Men nu har jeg brug for dit råd.\p"
	.string "Hvis jeg skulle deltage i BATTLE TOWER,\n"
	.string "hvad ville så være værdigt for mig?\l"
	.string "Level 50 eller Åben Level?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Er du sikker?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er det fint.\n"
	.string "Jeg takker dig for din tid.\p"
	.string "Jeg er klar over, at jeg kan irritere,\n"
	.string "men det glæder mig, at du har accepteret mig.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeWhatHeldItem0::
	.string "Suk… Snøft…\n"
	.string "Åh, {PLAYER}!\p"
	.string "Jeg er helt fanget i et dilemma,\n"
	.string "som jeg ikke kan beslutte.\p"
	.string "Jeg kan ikke beslutte, hvad jeg skal lade\n"
	.string "min {STR_VAR_1} holde.\p"
	.string "Fortæl mig venligst, {PLAYER}.\n"
	.string "Hvilket item skal jeg lade den holde?$"

gText_ApprenticeHoldNothing0::
	.string "Åh, virkelig? Jeg skal ikke lade\n"
	.string "min {STR_VAR_1} holde noget?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Åh, okay! Jeg er glad for, at det er afgjort!\n"
	.string "Fantastisk! Vildt! Awoooh!\p"
	.string "Tusind tak!$"

gText_ApprenticeThanksHeldItem0::
	.string "Åh, jeg er så glad…\n"
	.string "Jeg tror også, jeg har den {STR_VAR_1}.\p"
	.string "Jeg er glad for, at det er afgjort!\n"
	.string "Fantastisk! Vildt! Awoooh!\p"
	.string "Tusind tak!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaaah! Vær venlig ikke at være ond!\p"
	.string "Det item {STR_VAR_1} blev allerede\n"
	.string "anbefalet til mig før, snøft…\p"
	.string "Eller mener du, at jeg ikke skal lade\n"
	.string "min {STR_VAR_2} holde noget?$"

gText_ApprenticeWhatHeldItem1::
	.string "Yay! Det er {PLAYER}!\n"
	.string "Fantastisk! Jeg ville spørge dig om noget!\p"
	.string "Lader du dine POKéMON holde items?\n"
	.string "Jeg vil gerne lade mine holde items, men…\p"
	.string "Hvilket item ville være godt for\n"
	.string "{STR_VAR_1} at holde?\p"
	.string "Hvad synes du?$"

gText_ApprenticeHoldNothing1::
	.string "Hva? Mener du, at min {STR_VAR_1}\n"
	.string "ikke behøver at holde noget?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Åh, jeg forstår! Jeg gør det!\n"
	.string "Tak for at lære mig det!$"

gText_ApprenticeThanksHeldItem1::
	.string "Åh, wow! En {STR_VAR_1}, huh?\n"
	.string "Okay, jeg gør det!\p"
	.string "Tak for at lære mig det!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Åh, øh, nej, det var ikke det, jeg mente.\n"
	.string "Jeg vil gerne vide om et andet item\n"
	.string "end dem, jeg allerede kender.\p"
	.string "Eller mener du, at min POKéMON\n"
	.string "ikke behøver at holde noget denne gang?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, hej!\n"
	.string "Det handler om min {STR_VAR_1}…\p"
	.string "Jeg vil gerne lade den holde et godt item.\n"
	.string "Hvad ville være godt for den?$"

gText_ApprenticeHoldNothing2::
	.string "Åh, så min {STR_VAR_1} behøver\n"
	.string "ikke at holde noget?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Okay, jeg har forstået!\n"
	.string "Vi ses igen!$"

gText_ApprenticeThanksHeldItem2::
	.string "Åh, item {STR_VAR_1}?\n"
	.string "Forstået!\p"
	.string "Jeg vil gøre mit bedste for at finde en!\n"
	.string "Vi ses igen!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Nogen har allerede fortalt mig\n"
	.string "om {STR_VAR_1}.\p"
	.string "Jeg vil gerne have min POKéMON til at holde\n"
	.string "en anden slags item.\p"
	.string "Eller mener du, at {STR_VAR_2}\n"
	.string "ikke behøver at holde noget?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hej, {PLAYER}…\n"
	.string "Undskyld, jeg forstyrrer, men jeg har\l"
	.string "noget andet, jeg gerne vil spørge dig om.\p"
	.string "Jeg tror ikke, jeg er god nok til at vinde\n"
	.string "kampe alene, så jeg overvejer at\n"
	.string "lade min {STR_VAR_1} holde et item.\p"
	.string "Men jeg ved ikke, hvad der ville være godt.\p"
	.string "{PLAYER}, vær venlig, kan du beslutte\n"
	.string "for mig?$"

gText_ApprenticeHoldNothing3::
	.string "En POKéMON, der tilhører en som mig,\n"
	.string "ville have det bedre uden et item?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Jeg forstår…\n"
	.string "Du siger, jeg ikke skal stole på items.\l"
	.string "Jeg vil gøre mit bedste for ikke at gøre det!\p"
	.string "Tusind tak!$"

gText_ApprenticeThanksHeldItem3::
	.string "Itemet {STR_VAR_1}, okay.\n"
	.string "Jeg er ikke sikker på, om jeg kan få en…\l"
	.string "Nej! Jeg vil gøre mit bedste for at få den.\p"
	.string "Tusind tak!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Åh, men…\n"
	.string "Jeg tror, jeg har hørt om det før…\p"
	.string "Er det måske, fordi jeg ikke har håndteret\n"
	.string "itemet {STR_VAR_1} særlig godt?\p"
	.string "Eller mener du, at jeg ikke skal lade\n"
	.string "min {STR_VAR_2} holde noget?$"

gText_ApprenticeWhatHeldItem4::
	.string "Åh, {PLAYER}{KUN}.\n"
	.string "Der er noget, jeg gerne vil spørge dig om.\p"
	.string "Du ved, hvordan du besluttede, hvilke\n"
	.string "POKéMON jeg skulle have for mig?\p"
	.string "Men jeg spurgte dig aldrig, hvilket item\n"
	.string "den skulle holde.\p"
	.string "Siden du allerede gav mig råd,\n"
	.string "hvordan med at følge det til ende?\p"
	.string "Hvad ville være godt? Jeg vil gerne lade\n"
	.string "min {STR_VAR_1} holde noget.$"

gText_ApprenticeHoldNothing4::
	.string "Åh! Så min {STR_VAR_1} skal klare sig\n"
	.string "så godt som muligt uden noget?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Hvis du mener, det er bedst, gør jeg det.\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af det,\n"
	.string "hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeThanksHeldItem4::
	.string "Itemet {STR_VAR_1}, huh?\n"
	.string "Ikke dårligt. Jeg vil bruge det!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af det,\n"
	.string "hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Hva? Hvad siger du?\n"
	.string "Du fortalte mig allerede om {STR_VAR_1}\l"
	.string "før.\p"
	.string "Eller mener du, at min {STR_VAR_2}\n"
	.string "skal klare sig så godt som muligt uden noget?$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}{KUN}!\p"
	.string "Vi er begge travle, men vi ser ud til\n"
	.string "at løbe ind i hinanden alligevel!\p"
	.string "I dag skal jeg gå en tur,\n"
	.string "rengøre og børste.\p"
	.string "Jeg har ikke engang haft tid til at købe\n"
	.string "noget til min dyrebare {STR_VAR_1}.\p"
	.string "Jeg har ikke tid, så hvad med\n"
	.string "at give mig råd om, hvad jeg skal lade\n"
	.string "min {STR_VAR_1} holde?$"

gText_ApprenticeHoldNothing5::
	.string "Åh, så mig som en travl fyr, siger du\n"
	.string "at min {STR_VAR_1} ikke behøver noget?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Okay, forstået.\n"
	.string "Jeg behøver ikke tid til det.\p"
	.string "Tak for i dag!\n"
	.string "Vi ses!$"

gText_ApprenticeThanksHeldItem5::
	.string "Okay, forstået.\n"
	.string "Jeg finder tid på en eller anden måde og finder\n"
	.string "den {STR_VAR_1}, du anbefalede.\p"
	.string "Jeg er glad for at have mødt en god mentor som dig.\n"
	.string "Tak! Vi ses!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Hva? Jeg ved allerede om\n"
	.string "den {STR_VAR_1}.\p"
	.string "Åh, rigtigt, jeg forstår.\n"
	.string "Så mig som en travl fyr, siger du\n"
	.string "at min {STR_VAR_2} ikke behøver noget?$"

gText_ApprenticeWhatHeldItem6::
	.string "Hej, {PLAYER}! Det er mig!\n"
	.string "Jeg har brug for din hjælp igen i dag.\l"
	.string "Venligst, jeg har brug for dit råd!\p"
	.string "Trommehvirvel, tak!\n"
	.string "Mit spørgsmål er…\p"
	.string "Hvis jeg vil lade min {STR_VAR_1} holde\n"
	.string "et item, hvad skal det så være?$"

gText_ApprenticeHoldNothing6::
	.string "Er det rigtigt? Min {STR_VAR_1}\n"
	.string "behøver ikke at holde et item, siger du.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Okay, det er, hvad jeg vil gøre!\p"
	.string "Jeg tror, det var alt, jeg ville\n"
	.string "spørge dig om i dag.\p"
	.string "Lad os mødes her igen, okay?\n"
	.string "Tak!$"

gText_ApprenticeThanksHeldItem6::
	.string "Uh-huh! En {STR_VAR_1}.\n"
	.string "Hvilket sejt valg!\l"
	.string "Jeg vil bestemt prøve det!\p"
	.string "Jeg tror, det var alt, jeg ville\n"
	.string "spørge dig om i dag.\p"
	.string "Lad os mødes her igen, okay?\n"
	.string "Tak!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah! Det er fjollet!\n"
	.string "Du har allerede fortalt mig om den\n"
	.string "{STR_VAR_1} før!\p"
	.string "Har du det okay, {PLAYER}?\p"
	.string "Åh, vent! Min {STR_VAR_2}\n"
	.string "behøver ikke at holde et item, siger du.$"

gText_ApprenticeWhatHeldItem7::
	.string "Hej, {PLAYER}. Jeg håber, du har det\n"
	.string "godt.\p"
	.string "Må jeg spørge dig til råds?\p"
	.string "I en nylig kamp så det ud til, at\n"
	.string "min modstander havde givet sin POKéMON\l"
	.string "et item at holde.\p"
	.string "Som resultat blev jeg besejret…\p"
	.string "Jeg ønsker ikke at blive efterladt.\n"
	.string "Jeg vil gerne lade min {STR_VAR_1}\l"
	.string "holde et item, også.\p"
	.string "Det ville glæde mig, hvis du kunne beslutte\n"
	.string "hvad der ville være godt for min POKéMON…$"

gText_ApprenticeHoldNothing7::
	.string "Med andre ord… Min POKéMON har\n"
	.string "ikke brug for at holde et item?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Jeg forstår det klart nu!\n"
	.string "Jeg vil fortsætte på denne måde.\p"
	.string "Tak, {PLAYER}.\n"
	.string "Jeg håber, jeg kan regne med dig igen.\l"
	.string "Pas godt på dig selv!$"

gText_ApprenticeThanksHeldItem7::
	.string "En {STR_VAR_1} er det!\n"
	.string "Jeg vil bestille den med det samme.\p"
	.string "Tak, {PLAYER}.\n"
	.string "Jeg håber, jeg kan regne med dig igen.\l"
	.string "Pas godt på dig selv!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Du har allerede fortalt mig om det,\n"
	.string "og jeg har det allerede.\p"
	.string "Eller siger du… Min POKéMON har\n"
	.string "ikke brug for at holde et item?$"

gText_ApprenticeWhatHeldItem8::
	.string "Eek! {PLAYER}!\n"
	.string "Jeg… Jeg er overvældet af glæde over at se dig igen!\p"
	.string "Åh-åh-åh! Der er noget, jeg bare\n"
	.string "må spørge dig om, {PLAYER}!\p"
	.string "Vær venlig at beslutte, hvad min {STR_VAR_1}\n"
	.string "skal holde!$"

gText_ApprenticeHoldNothing8::
	.string "Åh, wow! Det forventede jeg ikke!\n"
	.string "Så, et item er ikke nødvendigt?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Perfekt forstået!\n"
	.string "Jeg vil fortsætte uden et item!\p"
	.string "Jeg håber, du vil lære mig noget mere en anden gang.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Jeg vil bruge det!\p"
	.string "Øhm… Kunne det være, {PLAYER}, at du også\n"
	.string "lader din POKéMON holde det item?\p"
	.string "Jeg vil helt sikkert skaffe det!\n"
	.string "Jeg håber, du vil lære mig noget mere en anden gang.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Hva? Du anbefalede den\n"
	.string "{STR_VAR_1} før, også.\p"
	.string "Er det det bedste item at holde?\n"
	.string "Eller mener du, at min {STR_VAR_2}\l"
	.string "ikke behøver noget at holde?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola!\n"
	.string "Min maestro, {PLAYER}{KUN}!\p"
	.string "Jeg vil gerne have dit råd om\n"
	.string "POKéMON redskaber.\p"
	.string "Hvad tror du ville være godt for\n"
	.string "min {STR_VAR_1} at holde?\p"
	.string "Vær ikke genert nu.\n"
	.string "Lad os få det ud!$"

gText_ApprenticeHoldNothing9::
	.string "Åh? Så du siger, at min {STR_VAR_1}\n"
	.string "kan vinde uden at holde noget item?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Si, bueno!\n"
	.string "Jeg vil give det mit bedste forsøg, som, slam!\p"
	.string "Okay, tak som altid!\n"
	.string "Adios!$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, det er en {STR_VAR_1}?\n"
	.string "Si, bueno!\l"
	.string "Jeg vil finde en, som, bam!\p"
	.string "Okay, tak som altid!\n"
	.string "Adios!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Nej, nej! Du har allerede fortalt mig om\n"
	.string "det {STR_VAR_1} før.\p"
	.string "Åh, vent lige et øjeblik…\n"
	.string "Så du siger, at min {STR_VAR_2}\l"
	.string "kan vinde uden at holde noget item?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, noget utroligt\n"
	.string "er sket!\p"
	.string "Jeg vågnede i morges, og min POKéMON\n"
	.string "havde 10 NUGGETS!\p"
	.string "Selvfølgelig lyver jeg!\n"
	.string "Wahahaha!\p"
	.string "Dette er dog ikke en løgn.\n"
	.string "Jeg er ikke særlig god til at tænke på,\l"
	.string "hvilke items POKéMON skal holde.\p"
	.string "Så hvad med at beslutte, hvad\n"
	.string "min {STR_VAR_1} skal holde, mester?$"

gText_ApprenticeHoldNothing10::
	.string "Hvad betyder det?\n"
	.string "Skal den ikke holde noget?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Okay, så den skal ikke holde noget.\n"
	.string "Så må jeg hellere få noget til den!\p"
	.string "Bare for sjov!\n"
	.string "Jeg vil følge din lære, mester!\p"
	.string "Tak, mester!\n"
	.string "Jeg håber, du vil fortsætte med at lære mig!$"

gText_ApprenticeThanksHeldItem10::
	.string "Okay, så det er en {STR_VAR_1}!\n"
	.string "Jeg vil lade den holde alt andet end det!\p"
	.string "Bare for sjov!\n"
	.string "Jeg vil følge din lære, mester!\p"
	.string "Tak, mester!\n"
	.string "Jeg håber, du vil fortsætte med at lære mig!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Øhm, du har fortalt mig om det før,\n"
	.string "ikke sandt?\p"
	.string "Er der ikke noget andet?\p"
	.string "Eller mener du, at jeg ikke skal lade\n"
	.string "min {STR_VAR_2} holde noget?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y!\n"
	.string "Og det staver ahoy!\p"
	.string "Jeg er den rappende SØMAND!\n"
	.string "Jeg præsenterer dig et spørgsmål\l"
	.string "der er ret fedt!\p"
	.string "Det er et item spørgsmål\n"
	.string "der beder om dit forslag!\p"
	.string "Min {STR_VAR_1} har brug for et item at holde,\n"
	.string "Hvad skal det være, hvis jeg må være fræk?$"

gText_ApprenticeHoldNothing11::
	.string "Er det rigtigt?\n"
	.string "Min {STR_VAR_1} behøver ikke at holde\n"
	.string "noget stramt?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Okay, jeg hører dig, selvfølgelig gør jeg!\n"
	.string "Min POKéMON vil også gå tomhændet!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeThanksHeldItem11::
	.string "Okay, en {STR_VAR_1},\n"
	.string "det er, hvad jeg vil bruge.\l"
	.string "Jeg havde ret i at få dig til at vælge!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Okay, en {STR_VAR_1}, siger du?\n"
	.string "Du fortalte mig det den anden dag.\l"
	.string "Jeg har brug for en ny idé, en helt ny måde.\p"
	.string "Eller, hvad, er det rigtigt?\n"
	.string "Min POKéMON behøver ikke at holde\n"
	.string "noget stramt?$"

gText_ApprenticeWhatHeldItem12::
	.string "Sig, hey, {PLAYER}!\n"
	.string "Jeg fandt dig igen i dag!\p"
	.string "Hvad skal jeg gøre? Få dit råd?\n"
	.string "Hvorfor ikke? Jeg taler allerede med dig!\p"
	.string "{PLAYER}, er du ved at blive træt af mig?\n"
	.string "Nah, ingen måde, det kan ikke være.\p"
	.string "Vil du høre mig ud?\n"
	.string "Jeg leder efter råd--det er, hvad\l"
	.string "jeg taler om.\p"
	.string "Det handler om et item til\n"
	.string "min {STR_VAR_1} der ville være godt.\l"
	.string "Min ubeslutsomhed gør mig frustreret.$"

gText_ApprenticeHoldNothing12::
	.string "Min {STR_VAR_1} behøver ingenting?\n"
	.string "Behøver ikke at holde noget?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Hvis det bedste er at holde ingenting,\n"
	.string "vil jeg gøre, som du foreslår!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit,\n"
	.string "men glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeThanksHeldItem12::
	.string "Hvis det bedste er at holde den {STR_VAR_1},\n"
	.string "vil jeg gøre, som du foreslår!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit,\n"
	.string "men glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Har jeg ikke hørt om den\n"
	.string "{STR_VAR_1} før?\l"
	.string "Jeg er sikker på, jeg har, det er sikkert!\p"
	.string "Jeg har brug for noget nyt!\n"
	.string "Eller, min {STR_VAR_2} behøver ingenting?\l"
	.string "Behøver ikke at holde noget?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah! Av! {PLAYER}{KUN}, min arm er brækket!\n"
	.string "Rør den ikke, vær sød!\p"
	.string "Jeg må have brækket den, mens jeg prøvede\n"
	.string "forskellige hold items med min flok af\l"
	.string "POKéMON.\p"
	.string "Så, som tingene er,\n"
	.string "har jeg brug for, at du beslutter for mig.\p"
	.string "{PLAYER}{KUN}, hvad synes du ville være\n"
	.string "godt for min {STR_VAR_1} at holde?$"

gText_ApprenticeHoldNothing13::
	.string "Av…\p"
	.string "Så du foreslår, at min {STR_VAR_1}\n"
	.string "ikke behøver at holde noget?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, okay. Det ville være lettere\n"
	.string "for mig, som tingene er nu.\p"
	.string "Jeg håber, jeg kan blive ved med\n"
	.string "at bede dig om hjælp som dette.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, okay. Det er en {STR_VAR_1}.\n"
	.string "Min POKéMONs arm er i orden, så jeg vil\n"
	.string "lade den holde det item med det samme.\p"
	.string "Jeg håber, jeg kan blive ved med\n"
	.string "at bede dig om hjælp som dette.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Nej, nej, du fortalte mig om den\n"
	.string "{STR_VAR_1} før, husker du?\p"
	.string "Hvad med at fortælle mig noget\n"
	.string "endnu bedre?\p"
	.string "Åh, vent et øjeblik.\n"
	.string "Så du foreslår, at min {STR_VAR_2}\n"
	.string "ikke behøver at holde noget?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Øhm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Vær venlig ikke at se på mig sådan.\n"
	.string "Mine POKéMON har ikke noget.\p"
	.string "Jeg… Jeg er virkelig flov over dette,\n"
	.string "men jeg har virkelig brug for dit råd.\p"
	.string "Jeg kan ikke beslutte, hvilket item der ville\n"
	.string "gøre min {STR_VAR_1} stærk.\p"
	.string "{PLAYER}{KUN}, hvad synes du ville\n"
	.string "være godt?$"

gText_ApprenticeHoldNothing14::
	.string "Åh… Så du tror, det ville være bedre,\n"
	.string "hvis min {STR_VAR_1} ikke havde et item?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Åh… Okay!\n"
	.string "Jeg vil gå uden et item.\p"
	.string "Det er dog nervepirrende.\n"
	.string "Ville det ikke være for sejt?\p"
	.string "Tak, {PLAYER}{KUN}.\n"
	.string "Hvis vi mødes igen, håber jeg, du vil\l"
	.string "være lige så hjælpsom.$"

gText_ApprenticeThanksHeldItem14::
	.string "Åh… Okay!\n"
	.string "Jeg vil gå med den {STR_VAR_1}.\p"
	.string "Det er dog nervepirrende.\n"
	.string "Ville det ikke være for sejt?\p"
	.string "Tak, {PLAYER}{KUN}.\n"
	.string "Hvis vi mødes igen, håber jeg, du vil\l"
	.string "være lige så hjælpsom.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "M-men jeg har allerede hørt om det.\p"
	.string "Vær venlig ikke at afvise mig sådan!\n"
	.string "Jeg kan ikke leve med ydmygelsen.\p"
	.string "Åh… Springer jeg til konklusioner?\n"
	.string "Tror du, det ville være bedre, hvis\n"
	.string "min {STR_VAR_2} ikke havde et item?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig?\l"
	.string "Måske er du en tvilling?\p"
	.string "Åh, nej, nej, nej, bare rolig!\n"
	.string "Hvis du virkelig er {PLAYER}, så glem\n"
	.string "min uhøflighed.\p"
	.string "Hvad jeg gerne vil have, er noget mere af\n"
	.string "dit gode råd.\p"
	.string "Jeg har her min {STR_VAR_1}, som jeg gerne\n"
	.string "vil lade holde et praktisk item.\p"
	.string "Hvad ville være værdigt for den?$"

gText_ApprenticeHoldNothing15::
	.string "Det er bedre, hvis den ikke holder noget?\n"
	.string "Er du sikker?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Jeg forstår. Hvis det er tilfældet, er det fint.\n"
	.string "Jeg takker dig for din tid.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeThanksHeldItem15::
	.string "En {STR_VAR_1}?\n"
	.string "Er du sikker?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er det fint.\n"
	.string "Jeg takker dig for din tid.\p"
	.string "Jeg håber, min POKéMON vil kunne\n"
	.string "bruge det godt.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Nej, nej, vent et øjeblik.\n"
	.string "Jeg tror, du lærte mig det før.\p"
	.string "Jeg vil gerne have, at du anbefaler\n"
	.string "noget andet denne gang.\p"
	.string "Måske foreslår du, at\n"
	.string "min {STR_VAR_2} ikke skal holde noget?\l"
	.string "Er du sikker?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waah, {PLAYER}!\n"
	.string "Jeg har et dilemma, snøft…\p"
	.string "Jeg vil begynde at kæmpe mod andre,\n"
	.string "men jeg ved ikke, hvad jeg skal gøre.\p"
	.string "Hvordan skal jeg stille mine POKéMON op,\n"
	.string "så de er stærkest?\p"
	.string "Fortæl mig venligst, {PLAYER}.\n"
	.string "Hvis du var mig, hvilken af disse POKéMON\l"
	.string "ville du sende ud først?$"

gText_ApprenticeMonFirstThanks0::
	.string "Min {STR_VAR_1} skal gå først?\n"
	.string "Waaaaah!\p"
	.string "Åh! Jeg er så ked af det!\n"
	.string "Du har gjort mig glad ved at vælge\l"
	.string "min første POKéMON, og det har gjort mig rørt…\p"
	.string "Tusind tak!$"

gText_ApprenticeWhichMonFirst1::
	.string "Yay! Det er {PLAYER}!\n"
	.string "Fantastisk! Jeg ville spørge dig om noget!\p"
	.string "Øhm, af mine POKéMON, hvilken tror du\n"
	.string "skal gå ud først?$"

gText_ApprenticeMonFirstThanks1::
	.string "Min {STR_VAR_1}? Det er sandt.\n"
	.string "Okay, jeg gør det!\p"
	.string "Tak for at lære mig det!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, hej!\p"
	.string "Jeg tror, det er meget vigtigt i en kamp,\n"
	.string "hvilken POKéMON der kommer ud først.\p"
	.string "Ud af de POKéMON, jeg har,\n"
	.string "hvilken ville være god at sende ud først?$"

gText_ApprenticeMonFirstThanks2::
	.string "Min {STR_VAR_1} går først?\n"
	.string "Okay, jeg har forstået!\p"
	.string "Vi ses igen!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hej, {PLAYER}…\n"
	.string "Undskyld, jeg forstyrrer dig igen med\l"
	.string "endnu et spørgsmål.\p"
	.string "Jeg har så lidt selvtillid, jeg ved ikke,\n"
	.string "hvad jeg ville gøre uden dig, {PLAYER}.\p"
	.string "Det kan være spild af tid for mig\n"
	.string "overhovedet at bekymre mig om det, men jeg kan bare ikke\l"
	.string "beslutte mig…\p"
	.string "Hvilken af mine POKéMON skal jeg sende\n"
	.string "ud først i en kamp?$"

gText_ApprenticeMonFirstThanks3::
	.string "Min {STR_VAR_1}?\n"
	.string "Forstået!\p"
	.string "Jeg kan ikke tro, at du gider\n"
	.string "besvare mine spørgsmål så ofte!\p"
	.string "Jeg er så taknemmelig for, at du overhovedet\n"
	.string "vil tale med mig… Tak!$"

gText_ApprenticeWhichMonFirst4::
	.string "Åh, {PLAYER}{KUN}! Det er mig!\n"
	.string "Jeg er så glad for at se dig, fordi jeg har\l"
	.string "et lille problem.\p"
	.string "Jeg kan ikke beslutte, hvordan mine POKéMON skal\n"
	.string "stilles op. Kunne du beslutte for mig?\p"
	.string "Åh, du behøver ikke at beslutte hele\n"
	.string "holdet lige nu.\p"
	.string "Hvad med at beslutte kun den første\n"
	.string "POKéMON for mig?$"

gText_ApprenticeMonFirstThanks4::
	.string "Min {STR_VAR_1}? Det er fantastisk!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af det,\n"
	.string "hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hej, min lærer {PLAYER}{KUN}!\n"
	.string "Jeg har travlt igen i dag!\p"
	.string "Jeg skal cykle, handle ind,\n"
	.string "og nynne.\p"
	.string "Jeg har ikke engang haft tid til at beslutte,\n"
	.string "hvordan jeg skal stille mit POKéMON hold op.\p"
	.string "Så, hvad med at tjekke mit hold?\n"
	.string "Hvilken skal gå først?$"

gText_ApprenticeMonFirstThanks5::
	.string "Okay, forstået.\n"
	.string "Jeg har i det mindste tid nok til at sætte\n"
	.string "min {STR_VAR_1} først i rækken!\p"
	.string "Ups, min kæreste venter!\n"
	.string "Tak! Vi ses!$"

gText_ApprenticeWhichMonFirst6::
	.string "Yoohoo! Hej, {PLAYER}!\n"
	.string "Du går altid rundt og ser sej ud!\p"
	.string "Hør, jeg har brug for noget fra dig\n"
	.string "igen! Det er det sædvanlige!\p"
	.string "Trommehvirvel, tak!\n"
	.string "Mit spørgsmål handler om mit hold.\p"
	.string "Hvilken af mine POKéMON skal være den første\n"
	.string "til at gå ud i en kamp?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm!\n"
	.string "Min {STR_VAR_1}, siger du!\l"
	.string "Tak for et virkelig sejt svar!\p"
	.string "Jeg tror, det var alt, jeg ville\n"
	.string "spørge dig om i dag.\p"
	.string "Lad os mødes her igen, okay?\n"
	.string "Tak!$"

gText_ApprenticeWhichMonFirst7::
	.string "Tusind tak for at stoppe op\n"
	.string "og chatte med mig, {PLAYER}.\p"
	.string "Jeg ved, jeg udnytter din\n"
	.string "venlighed, men må jeg bede om råd?\p"
	.string "Jeg vil gerne have, at du beslutter rækkefølgen\n"
	.string "for mit POKéMON hold.\p"
	.string "Det ville glæde mig, hvis du kunne beslutte,\n"
	.string "hvilken POKéMON der skal komme først.$"

gText_ApprenticeMonFirstThanks7::
	.string "Min {STR_VAR_1} er det!\n"
	.string "Jeg vil sætte den først med det samme!\p"
	.string "Tak, {PLAYER}.\n"
	.string "Jeg håber, jeg kan regne med dig igen.\l"
	.string "Pas godt på dig selv!$"

gText_ApprenticeWhichMonFirst8::
	.string "Eek! {PLAYER}!\n"
	.string "Jeg… Jeg er overvældet af glæde over at se dig igen!\p"
	.string "Mine POKéMON er blevet meget\n"
	.string "stærkere!\p"
	.string "Men jeg vinder ikke altid. Det ser ud til\n"
	.string "at afhænge af, hvilken POKéMON der går først.\p"
	.string "{PLAYER}, vær venlig, jeg har brug for din hjælp!\p"
	.string "Vær venlig at beslutte, hvilken af mine POKéMON\n"
	.string "der skal gå ud først!$"

gText_ApprenticeMonFirstThanks8::
	.string "Suk… Jeg er overvældet af lykke…\p"
	.string "Det er som en drøm, at du beslutter\n"
	.string "for mig, {PLAYER}.\p"
	.string "Men perfekt forstået!\n"
	.string "Jeg vil sende min {STR_VAR_1} først ud!\p"
	.string "Jeg håber, du vil lære mig noget mere en anden gang.$"

gText_ApprenticeWhichMonFirst9::
	.string "Hej, hej!\n"
	.string "Min mentor, {PLAYER}{KUN}!\l"
	.string "Giv mig dit kloge råd i dag!\p"
	.string "Ser du, jeg har samlet et hold af\n"
	.string "tre POKéMON. Indtil videre så godt.\p"
	.string "Men holdets kamporden er endnu ikke\n"
	.string "afgjort.\p"
	.string "Det er her, du kommer ind, {PLAYER}{KUN}!\n"
	.string "Du bestemmer, hvilken POKéMON der fører an!\p"
	.string "Vær ikke genert nu.\n"
	.string "Lad os få det ud!$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, min {STR_VAR_1} fører an!\n"
	.string "OK, A-OK!\l"
	.string "Jeg vil omorganisere rækkefølgen, som, wham!\p"
	.string "Okay, tak som altid!\n"
	.string "Adios!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, hør!\n"
	.string "Det er en krise!\p"
	.string "Mine POKéMON, alle tre af dem, går ind i\n"
	.string "kamp på én gang!\p"
	.string "Selvfølgelig er det umuligt!\n"
	.string "Wahahaha!\p"
	.string "Dette er dog ingen løgn.\n"
	.string "Jeg er ikke særlig god til at tænke over\l"
	.string "hvordan jeg skal stille mine POKéMON op.\p"
	.string "Så, hvad med at beslutte for mig, hvilken\n"
	.string "POKéMON der skal gå først, mester?$"

gText_ApprenticeMonFirstThanks10::
	.string "Okay, så det er min {STR_VAR_1}, du valgte?\n"
	.string "Jeg vil lade enhver undtagen den gå først!\p"
	.string "Bare for sjov!\n"
	.string "Jeg vil følge din undervisning, mester!\p"
	.string "Tak, mester!\n"
	.string "Jeg håber, du vil fortsætte med at lære mig!$"

gText_ApprenticeWhichMonFirst11::
	.string "O-H-Ø-J!\n"
	.string "Sådan staves ohøj!\p"
	.string "Jeg er den rappende SØMAND!\n"
	.string "Jeg præsenterer dig et spørgsmål\l"
	.string "der er ret fedt!\p"
	.string "Det er et holdopstillingsspørgsmål\n"
	.string "der beder om dit forslag!\p"
	.string "Ud af dette hold, hvilken skal gå først\n"
	.string "som den første på stedet?$"

gText_ApprenticeMonFirstThanks11::
	.string "Okay, jeg hører dig, selvfølgelig gør jeg!\n"
	.string "Jeg bytter dem om, det gør jeg!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}!\n"
	.string "Hvordan går det?\p"
	.string "Hvad skal jeg gøre? Spørge om råd?\n"
	.string "Uh-huh, jeg har noget at spørge om!\l"
	.string "Modtager du mig?\l"
	.string "Du modtager mig!\p"
	.string "Du skal beslutte, hvilken af mine\n"
	.string "POKéMON der skal først!\l"
	.string "I kamp, mener jeg.$"

gText_ApprenticeMonFirstThanks12::
	.string "Min {STR_VAR_1}? Ja!\n"
	.string "Det er fint, ingen nød!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit,\n"
	.string "men glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Uff…av… {PLAYER}{KUN}…\n"
	.string "Min mave gør ondt pludselig…\p"
	.string "…Det bliver bedre nu…\p"
	.string "Jeg må have bekymret mig syg ved at tænke\n"
	.string "over, hvordan jeg skal stille mit hold af\l"
	.string "POKéMON op.\p"
	.string "Så, som tingene er,\n"
	.string "har jeg brug for, at du beslutter for mig.\p"
	.string "{PLAYER}{KUN}, hvilken af mine POKéMON skal\n"
	.string "gå først? Så jeg vinder, mener jeg.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, okay.\n"
	.string "Min {STR_VAR_1} går først.\p"
	.string "Jeg vil rette opstillingen sådan efter\n"
	.string "jeg har spist aftensmad.\p"
	.string "Jeg håber, jeg kan blive ved med\n"
	.string "at bede dig om hjælp som dette.$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Øhm…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Vær venlig ikke at se på mig sådan.\n"
	.string "Du gør mig helt forfjamsket.\p"
	.string "Øhm…\n"
	.string "Jeg har virkelig brug for dit råd.\p"
	.string "Det gør mig genert at sige dette,\n"
	.string "men jeg har valgt mit 3-POKéMON hold.\l"
	.string "Jeg kan dog ikke beslutte rækkefølgen.\p"
	.string "Hvilken POKéMON skal jeg sende ud først\n"
	.string "så jeg i det mindste ser dygtig ud?$"

gText_ApprenticeMonFirstThanks14::
	.string "Åh… Okay!\n"
	.string "Jeg vil starte med min {STR_VAR_1}.\p"
	.string "Jeg håber, jeg kan gøre mit bedste uden\n"
	.string "at blive helt forfjamsket.\p"
	.string "Tak, {PLAYER}{KUN}.\n"
	.string "Hvis vi mødes igen, håber jeg, du vil være\l"
	.string "lige så hjælpsom.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig?\l"
	.string "Måske er du en klog look-alike?\p"
	.string "Åh, nej, nej, nej, bare rolig!\n"
	.string "Hvis du virkelig er {PLAYER}, så glem\n"
	.string "min uhøflighed.\p"
	.string "Hvad jeg gerne vil have, er dit gode råd.\p"
	.string "Jeg har her mit POKéMON hold.\n"
	.string "Jeg vil gerne have, at du fortæller mig,\n"
	.string "hvilken der skal gå først i en kamp.$"

gText_ApprenticeMonFirstThanks15::
	.string "Min {STR_VAR_1}…\n"
	.string "Du trækker ikke benet på mig?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er det fint.\n"
	.string "Jeg takker dig for din tid.\p"
	.string "Jeg er, som du ser, men jeg skal gøre\n"
	.string "mit bedste.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeWhichMon0::
	.string "Snøft…\n"
	.string "Åh, {PLAYER}!\p"
	.string "Hvilken perfekt timing!\n"
	.string "Der er noget, jeg bare ikke kan beslutte…\p"
	.string "Jeg kan ikke beslutte, hvilken POKéMON jeg\n"
	.string "skal bruge.\p"
	.string "Jeg kan ikke beslutte mellem POKéMON\n"
	.string "{STR_VAR_1} og {STR_VAR_2}…\p"
	.string "{PLAYER}, hvilken tror du vil give\n"
	.string "selv mig en chance for at vinde?$"

gText_ApprenticeMonThanks0::
	.string "Snøft… Jeg… Jeg forstår!\n"
	.string "Åh! Jeg er så ked af det!\l"
	.string "Du har gjort mig så glad, jeg græder…\p"
	.string "Jeg vil gøre mit bedste for at fange\n"
	.string "en {STR_VAR_1}!\p"
	.string "Tusind tak!$"

gText_ApprenticeWhichMon1::
	.string "Yay! Det er {PLAYER}!\n"
	.string "Yay, du kom på det rigtige tidspunkt!\l"
	.string "Jeg har brug for dit råd igen!\p"
	.string "Øhm, jeg er helt forvirret--skal jeg bruge\n"
	.string "min {STR_VAR_1} eller {STR_VAR_2}…\p"
	.string "Hvilken tror du, jeg skal opdrage,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Åh, så min {STR_VAR_1} er bedre!\n"
	.string "Okay, jeg gør det!\p"
	.string "Tak for at lære mig det!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, hej!\n"
	.string "Jeg har et spørgsmål, jeg ville stille.\p"
	.string "Jeg er i et dilemma om, hvorvidt jeg skal\n"
	.string "opdrage en {STR_VAR_1} eller {STR_VAR_2}.\p"
	.string "Hvilken POKéMON tror du vil\n"
	.string "være stærkere?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} er dit valg?\n"
	.string "Okay, jeg har forstået!\p"
	.string "Jeg vil gå og fange en stærk {STR_VAR_1}\n"
	.string "med det samme!\p"
	.string "Vi ses igen!$"

gText_ApprenticeWhichMon3::
	.string "Hej, {PLAYER}…\p"
	.string "Øhm, du har sikkert allerede glemt\n"
	.string "en som mig…\p"
	.string "…Men det betyder ikke noget, hvis du\n"
	.string "kunne give mig råd…\p"
	.string "Jeg kan ikke beslutte, hvilken type\n"
	.string "POKéMON jeg skal opdrage…\p"
	.string "Jeg har begrænset feltet til POKéMON\n"
	.string "{STR_VAR_1} og {STR_VAR_2}, men det er\l"
	.string "der, hvor jeg blev fastlåst…\p"
	.string "{PLAYER}, du ønsker nok ikke at\n"
	.string "besvære dig, men vær venlig at beslutte for mig.$"

gText_ApprenticeMonThanks3::
	.string "Men vil en vild {STR_VAR_1} overhovedet\n"
	.string "lægge mærke til mig?\p"
	.string "Jeg vil prøve!\p"
	.string "Men vil jeg overhovedet kunne fange en…\n"
	.string "Nej! Jeg vil gøre mit bedste!\p"
	.string "Tak!$"

gText_ApprenticeWhichMon4::
	.string "Åh, {PLAYER}{KUN}! Jeg er så glad for at se dig!\n"
	.string "Jeg var lige ved at gå og lede efter dig!\p"
	.string "Kan du beslutte, hvilken type POKéMON\n"
	.string "jeg skal bruge?\p"
	.string "For eksempel…\n"
	.string "Hvad med POKéMON {STR_VAR_1}\l"
	.string "og {STR_VAR_2}?\p"
	.string "Hvilken tror du ville være\n"
	.string "bedre?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Det er fantastisk!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af det,\n"
	.string "hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeWhichMon5::
	.string "Er det ikke {PLAYER}{KUN}?! Hvordan går det?\n"
	.string "Jeg har travlt igen som altid!\p"
	.string "Jeg vil også gøre det godt med POKéMON,\n"
	.string "men jeg har ikke kunnet beslutte,\n"
	.string "hvilken POKéMON jeg skal bruge.\p"
	.string "Du ved, hvordan {STR_VAR_1} ser stærke ud?\n"
	.string "Men {STR_VAR_2} er svære at ignorere.\p"
	.string "{PLAYER}{KUN}, giv mig noget af dit gode\n"
	.string "råd! Hvilken ville være god for mig?$"

gText_ApprenticeMonThanks5::
	.string "Okay, forstået.\n"
	.string "Jeg vil finde tid på en eller anden måde og fange\n"
	.string "den {STR_VAR_1}, du anbefalede.\p"
	.string "Jeg er glad for at have mødt en god mentor som dig.\n"
	.string "Tak! Vi ses!$"

gText_ApprenticeWhichMon6::
	.string "Åh!\n"
	.string "Yay, det er {PLAYER}!\p"
	.string "Jeg spildte ingen tid med at prale for\n"
	.string "mine venner om at møde dig!\p"
	.string "Jeg har brug for din hjælp igen i dag.\n"
	.string "Det er nemt for dig!\p"
	.string "Trommehvirvel, tak!\n"
	.string "Mit spørgsmål er…\p"
	.string "Hvis jeg skulle opdrage en POKéMON,\n"
	.string "og valget stod mellem en {STR_VAR_1}\n"
	.string "eller {STR_VAR_2}, hvilken skulle det så være?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, siger du!\n"
	.string "Tak for et virkelig sejt svar!\p"
	.string "Jeg tror, det var alt, jeg ville\n"
	.string "spørge dig om i dag.\p"
	.string "Lad os mødes her igen, okay?\n"
	.string "Tak!$"

gText_ApprenticeWhichMon7::
	.string "Åh, er det dig, {PLAYER}?\n"
	.string "Jeg er glad for at se dig igen!\p"
	.string "Siden jeg blev din lærling,\n"
	.string "er min selvtillid vokset.\p"
	.string "Jeg tror, jeg er klar til at opdrage en POKéMON\n"
	.string "helt selv!\p"
	.string "{PLAYER}, må jeg bede dig om at vælge,\n"
	.string "hvilken POKéMON jeg skal opdrage?\p"
	.string "Valget står mellem POKéMON\n"
	.string "{STR_VAR_1} eller {STR_VAR_2}…\n"
	.string "Hvilken POKéMON er rigtig for mig?$"

gText_ApprenticeMonThanks7::
	.string "En {STR_VAR_1} er det!\n"
	.string "Jeg vil finde en med det samme!\p"
	.string "Tak, {PLAYER}.\n"
	.string "Jeg håber, jeg kan regne med dig igen.\n"
	.string "Pas godt på dig selv!$"

gText_ApprenticeWhichMon8::
	.string "Eek! {PLAYER}! Jeg mødte dig igen!\n"
	.string "Jeg… jeg er overvældet af glæde!\p"
	.string "Åh-åh-åh, jeg ved det!\n"
	.string "Jeg bør ikke gå glip af denne mulighed!\p"
	.string "Må jeg bede om en stor tjeneste, {PLAYER}?\n"
	.string "Vær venlig at vælge en POKéMON for mig!\p"
	.string "Vær venlig at beslutte, hvilken der er bedre,\n"
	.string "{STR_VAR_1} eller {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Wow! Du besluttede for mig!\n"
	.string "En {STR_VAR_1} er, hvad jeg vil opdrage\n"
	.string "til det bedste af min evne.\p"
	.string "Jeg håber, du vil lære mig noget mere en anden gang.$"

gText_ApprenticeWhichMon9::
	.string "Hej, hej!\n"
	.string "Min mentor, {PLAYER}{KUN}!\p"
	.string "Hej, jeg har ledt efter dig\n"
	.string "for at få mere af dit kloge råd!\p"
	.string "Hvilken slags POKéMON ville være god\n"
	.string "for mig, en {STR_VAR_1} eller {STR_VAR_2}?\p"
	.string "Vær ikke genert nu.\n"
	.string "Lad os få det ud!$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, en {STR_VAR_1} er det!\n"
	.string "OK, A-OK!\l"
	.string "Jeg fanger en i en BALL, som, cram!\p"
	.string "Okay, tak som altid!\n"
	.string "Adios!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, hør! Store nyheder!\n"
	.string "Jeg fangede en mirage POKéMON!\p"
	.string "Selvfølgelig lyver jeg!\n"
	.string "Wahahaha!\p"
	.string "Dette er dog ingen løgn.\n"
	.string "Jeg er ikke særlig god til at fange\n"
	.string "POKéMON.\p"
	.string "Så hvad med at beslutte for mig,\n"
	.string "hvilken slags POKéMON jeg skal fange,\n"
	.string "mester?\p"
	.string "Hvilken ville være bedre?\n"
	.string "{STR_VAR_1} eller {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Okay, så det er {STR_VAR_1}, du valgte?\n"
	.string "Jeg tager den anden slags så!\p"
	.string "Bare for sjov!\n"
	.string "Jeg vil følge din lære, mester!\p"
	.string "Tak, mester!\n"
	.string "Jeg håber, du vil fortsætte med at lære mig!$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y!\n"
	.string "Og det staver ahoy!\p"
	.string "Jeg er den rappende SØMAND!\n"
	.string "Du husker vel, hvem jeg er?\p"
	.string "I dag har jeg et POKéMON-spørgsmål,\n"
	.string "der beder om dit forslag!\p"
	.string "Jeg har valget mellem denne\n"
	.string "{STR_VAR_1} og {STR_VAR_2}, ser du.\l"
	.string "Hvilken er den rigtige for mig at fange?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, siger du, hey, hey!\n"
	.string "Jeg vil gå og fange en med det samme!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeWhichMon12::
	.string "Åh, wow, hvis det ikke er {PLAYER}!\p"
	.string "Hvad skal jeg gøre? Få dit råd?\n"
	.string "Hvorfor ikke? Jeg taler allerede med dig!\p"
	.string "Det er længe siden. Lad mig bryde\n"
	.string "isen. Jeg leder også efter råd!\l"
	.string "Modtager du mig?\l"
	.string "Du modtager mig!\p"
	.string "Min POKéMON--hvilken skal jeg bruge?\n"
	.string "Det er enten {STR_VAR_1} eller {STR_VAR_2}.\l"
	.string "Hvilken vælger du?$"

gText_ApprenticeMonThanks12::
	.string "Hvis den {STR_VAR_1} er den bedste,\n"
	.string "vil jeg gøre, som du foreslår!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit,\n"
	.string "men glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeWhichMon13::
	.string "Åh, hej, {PLAYER}{KUN}…\n"
	.string "Jeg har denne frygtelige hovedpine…\p"
	.string "Jeg må have bekymret mig for meget om,\n"
	.string "hvilken slags POKéMON jeg skal opdrage.\p"
	.string "Så, som tingene er,\n"
	.string "har jeg brug for, at du beslutter for mig.\p"
	.string "{PLAYER}{KUN}, hvis jeg skulle vælge mellem\n"
	.string "POKéMON {STR_VAR_1} og\n"
	.string "{STR_VAR_2}, hvilken skulle det være?$"

gText_ApprenticeMonThanks13::
	.string "Hm, en {STR_VAR_1}, okay.\n"
	.string "Jeg vil lede efter en, når jeg bliver bedre.\p"
	.string "Jeg håber, jeg kan blive ved med\n"
	.string "at bede dig om hjælp som dette.$"

gText_ApprenticeWhichMon14::
	.string "Er… Øhm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Vær venlig ikke at se på mig sådan.\n"
	.string "Jeg bliver helt forfjamsket…\l"
	.string "Jeg… jeg har brug for dit råd.\p"
	.string "Jeg… jeg er virkelig flov, men jeg kan ikke\n"
	.string "beslutte, hvilken POKéMON jeg skal bruge.\p"
	.string "Hvis valget stod mellem {STR_VAR_1} eller\n"
	.string "{STR_VAR_2}, hvilken ville være bedre?$"

gText_ApprenticeMonThanks14::
	.string "Åh… Okay!\n"
	.string "Jeg vil gøre mit bedste med en {STR_VAR_1}.\p"
	.string "Jeg håber, jeg kan gøre mit bedste uden\n"
	.string "at blive helt forfjamsket.\p"
	.string "Tak, {PLAYER}{KUN}.\n"
	.string "Hvis vi mødes igen, håber jeg, du vil være\l"
	.string "lige så hjælpsom.$"

gText_ApprenticeWhichMon15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig rigtig?\p"
	.string "Nej, nej, hvis du er rigtig, er det fint.\n"
	.string "Forresten, jeg vil gerne have\n"
	.string "dit råd.\p"
	.string "Det handler om den POKéMON, jeg skal bruge.\p"
	.string "Hvis valget står mellem POKéMON\n"
	.string "{STR_VAR_1} og {STR_VAR_2}, hvilken er\n"
	.string "mere værdig for mig?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Er du sikker?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er det fint.\n"
	.string "Jeg takker dig for din tid.\p"
	.string "Jeg håber, det er noget, jeg endda kan\n"
	.string "håndtere med lethed.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Åh, {PLAYER}!\n"
	.string "Snøft… Hiks…\p"
	.string "Jeg har et dilemma!\n"
	.string "Jeg kan ikke beslutte mig for et move til\l"
	.string "min {STR_VAR_1}…\p"
	.string "Vær venlig, vær venlig, {PLAYER}.\n"
	.string "Kan du beslutte for mig?\p"
	.string "For min {STR_VAR_1}, hvilket move ville\n"
	.string "være det bedste valg: {STR_VAR_2}\l"
	.string "eller {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Åh! Jeg er så ked af det, {PLAYER}!\n"
	.string "Du har gjort mig så glad ved at vælge\l"
	.string "movet, jeg græder…\p"
	.string "Snøft…\n"
	.string "Tusind tak!$"

gText_ApprenticeWhichMove1::
	.string "Yay! Hej, {PLAYER}!\n"
	.string "Jeg har brug for dit råd igen!\p"
	.string "Jeg vil lære min {STR_VAR_1}\n"
	.string "et sejt move.\p"
	.string "Jeg kan godt lide enten\n"
	.string "{STR_VAR_2} eller {STR_VAR_3}.\l"
	.string "Hvad er din anbefaling?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} er bedre? Det tror jeg også!\n"
	.string "Okay, jeg går med det!\p"
	.string "Hvis vi mødes her igen, vil du så\n"
	.string "lære mig noget andet, lærer?$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hej!\n"
	.string "Det handler om min {STR_VAR_1}, men jeg er\n"
	.string "bekymret over dens moves.\p"
	.string "Ser du, det er moves {STR_VAR_2}\n"
	.string "og {STR_VAR_3}.\p"
	.string "Hvilket er stærkere og bedre for\n"
	.string "min {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} er dit valg?\n"
	.string "Okay, jeg har forstået!\p"
	.string "Jeg vil straks lære {STR_VAR_1}\n"
	.string "til min POKéMON!\p"
	.string "Vi ses igen!$"

gText_ApprenticeWhichMove3::
	.string "Åhhh, {PLAYER}…\n"
	.string "Jeg er håbløs, nej, virkelig!\p"
	.string "Jeg har besluttet mig for at opdrage en POKéMON,\n"
	.string "men nu kan jeg ikke engang beslutte,\n"
	.string "hvilket move jeg skal lade den lære…\p"
	.string "Jeg ved, det ikke betyder noget\n"
	.string "for dig, {PLAYER}.\p"
	.string "Men det betyder meget for mig…\p"
	.string "Vær venlig, {PLAYER}, kunne du vælge\n"
	.string "et move til min {STR_VAR_1}?\p"
	.string "Hvis du kunne vælge mellem\n"
	.string "{STR_VAR_2} og {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Jeg forstår!\p"
	.string "Men vil den overhovedet være villig\n"
	.string "til at lære {STR_VAR_1} for mig…\l"
	.string "Nej! Jeg vil gøre mit bedste!\p"
	.string "Tak!$"

gText_ApprenticeWhichMove4::
	.string "Åh, {PLAYER}{KUN}!\n"
	.string "Jeg håbede lige at se dig!\p"
	.string "Jeg spekulerede på, hvilket move der\n"
	.string "ville være passende for min {STR_VAR_1}.\p"
	.string "Jeg kan ikke beslutte mig, så kan du\n"
	.string "beslutte for mig i stedet?\p"
	.string "For eksempel… Hvad med moves\n"
	.string "{STR_VAR_2} og {STR_VAR_3}?\l"
	.string "Hvilket ville være bedre?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Det er fantastisk!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af det,\n"
	.string "hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeWhichMove5::
	.string "Hvordan kan tingene være så travle?\n"
	.string "Hej, hvis det ikke er {PLAYER}{KUN}!\l"
	.string "Hvordan går det?\p"
	.string "Siden jeg stod op i morges, har jeg\n"
	.string "jogget, svømmet og lavet mad!\p"
	.string "Du vil ikke tro, hvor travlt jeg har det!\p"
	.string "Jeg kan ikke engang beslutte, hvilket move\n"
	.string "min {STR_VAR_1} skal lære!\p"
	.string "{STR_VAR_2} ser godt ud, ikke?\n"
	.string "Men {STR_VAR_3} er også okay.\p"
	.string "{PLAYER}{KUN}, giv mig noget af dit gode\n"
	.string "råd! Hvilket move ville være godt for mig?$"

gText_ApprenticeMoveThanks5::
	.string "Okay, forstået.\n"
	.string "Jeg vil finde tid i min tidsplan og\n"
	.string "lære det move.\p"
	.string "Jeg er glad for at have mødt en god mentor som dig.\n"
	.string "Tak! Vi ses!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Heldigt!\n"
	.string "Jeg mødte dig igen, {PLAYER}!\l"
	.string "Jeg har brug for din hjælp igen i dag.\p"
	.string "Trommehvirvel, tak!\n"
	.string "Mit spørgsmål er…\p"
	.string "For min {STR_VAR_1}, hvilket move er\n"
	.string "bedst egnet, {STR_VAR_2} eller\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, siger du!\l"
	.string "Tak for et virkelig sejt svar!\p"
	.string "Jeg tror, det var alt, jeg ville\n"
	.string "spørge dig om i dag.\p"
	.string "Lad os mødes her igen, okay?\n"
	.string "Tak!$"

gText_ApprenticeWhichMove7::
	.string "Åh, hej, {PLAYER}.\n"
	.string "Jeg håber, du har det godt?\p"
	.string "Jeg har brug for dit råd igen.\n"
	.string "Det handler om min kære {STR_VAR_1}.\p"
	.string "Hvilket ville være det ideelle move for\n"
	.string "min elskelige {STR_VAR_1}?\l"
	.string "{STR_VAR_2} eller {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} er det!\n"
	.string "Jeg vil lære det med det samme!\p"
	.string "Tak, {PLAYER}.\n"
	.string "Jeg håber, jeg kan regne med dig igen.\l"
	.string "Pas godt på dig selv!$"

gText_ApprenticeWhichMove8::
	.string "Eek! {PLAYER}! Jeg mødte dig igen!\n"
	.string "Jeg… jeg er overvældet af glæde!\p"
	.string "Når jeg har brug for hjælp, er du altid\n"
	.string "der for mig, {PLAYER}!\p"
	.string "I dag vil jeg have dig til at anbefale\n"
	.string "et move for mig!\p"
	.string "Vær venlig at vælge et move til\n"
	.string "min {STR_VAR_1}!\p"
	.string "Hvilket move ville være bedre,\n"
	.string "{STR_VAR_2} eller {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Åh-åh-åh! Tak!\n"
	.string "{STR_VAR_1} er det!\l"
	.string "Perfekt forstået!\p"
	.string "Jeg håber, du vil lære mig noget mere\n"
	.string "en anden gang.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno!\n"
	.string "Jeg håber på noget mere af\n"
	.string "dit kloge råd i dag!\p"
	.string "Hvad ville være det bedste move for\n"
	.string "min {STR_VAR_1}?\p"
	.string "Det skal være noget, der vil\n"
	.string "lade mig vinde med det samme!\p"
	.string "Ville det være {STR_VAR_2}?\n"
	.string "Eller {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1} er det!\n"
	.string "Si, bueno!\l"
	.string "Jeg vil lære det, som, ka-blam!\p"
	.string "Okay, tak som altid!\n"
	.string "Adios!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, det er helt vildt!\p"
	.string "Min POKéMON!\n"
	.string "Den har lært seks moves!\p"
	.string "Selvfølgelig lyver jeg!\n"
	.string "Wahahaha!\p"
	.string "Dette er dog ingen løgn.\n"
	.string "Jeg er ikke særlig god til at vælge moves\n"
	.string "til min POKéMON.\p"
	.string "Så hvad med at beslutte for mig, hvilket\n"
	.string "move jeg skal lære?\p"
	.string "{STR_VAR_2} eller {STR_VAR_3}--hvilket\n"
	.string "ville passe bedst til min {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "Okay, så det er {STR_VAR_1}, du valgte?\n"
	.string "Jeg vælger et andet move så!\p"
	.string "Bare for sjov!\n"
	.string "Jeg vil følge din lære, mester!\p"
	.string "Tak, mester!\n"
	.string "Jeg håber, du vil fortsætte med at lære mig!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y!\n"
	.string "Og det staver ahoy!\p"
	.string "Jeg er den rappende SØMAND!\n"
	.string "Jeg er altid med på det, spørg mig ikke hvorfor.\p"
	.string "I dag har jeg et move-spørgsmål,\n"
	.string "der beder om dit forslag!\p"
	.string "{STR_VAR_2} og {STR_VAR_3} er\n"
	.string "moves. Hvilket ville være bedst\l"
	.string "for min {STR_VAR_1}, så den groover?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, siger du, hey, hey!\n"
	.string "Jeg vil lære det med det samme!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeWhichMove12::
	.string "Åh, jaah, hvis det ikke er {PLAYER}!\p"
	.string "Hvad skal jeg gøre? Få dit råd?\n"
	.string "Hvorfor ikke? Jeg taler allerede med dig!\p"
	.string "{PLAYER}, er du overrasket over mig?\n"
	.string "Jeg vil have dit råd, kan du ikke se det?\p"
	.string "Modtager du mig?\n"
	.string "Du modtager mig!\p"
	.string "Min {STR_VAR_1}--hvad skal den bruge?\n"
	.string "Det er {STR_VAR_2} eller {STR_VAR_3},\l"
	.string "hvad vælger du?$"

gText_ApprenticeMoveThanks12::
	.string "Hvis den {STR_VAR_1} er den bedste,\n"
	.string "vil jeg gøre, som du foreslår!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit,\n"
	.string "men glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Åh, {PLAYER}{KUN}…\n"
	.string "Jeg har denne elendige forkølelse, det har jeg…\p"
	.string "Jeg vil vælge et move til min POKéMON,\n"
	.string "men jeg er ikke i stand til det…\p"
	.string "Så, som tingene er,\n"
	.string "har jeg brug for, at du beslutter for mig.\p"
	.string "{PLAYER}{KUN}, hvis jeg skulle vælge mellem\n"
	.string "{STR_VAR_2} og {STR_VAR_3} til\n"
	.string "min {STR_VAR_1}, hvilket skulle det være?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, okay. Host!\n"
	.string "Jeg vil lære det, når jeg bliver bedre.\p"
	.string "Jeg håber, jeg kan blive ved med\n"
	.string "at bede dig om hjælp som dette.$"

gText_ApprenticeWhichMove14::
	.string "Er… Øhm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Vær venlig ikke at se på mig sådan.\n"
	.string "Jeg bliver helt forfjamsket…\l"
	.string "Jeg… jeg har brug for dit råd.\p"
	.string "Jeg… jeg er virkelig flov, men jeg kan ikke\n"
	.string "beslutte, hvilket move jeg skal lære\n"
	.string "min POKéMON.\p"
	.string "Det er for min {STR_VAR_1}.\n"
	.string "Hvis valget stod mellem {STR_VAR_2} eller\n"
	.string "{STR_VAR_3}, hvilket ville være bedre?$"

gText_ApprenticeMoveThanks14::
	.string "Åh… Okay!\n"
	.string "Jeg vil prøve det {STR_VAR_1}.\p"
	.string "Jeg håber, jeg kan lære det move…\n"
	.string "Dette er så nervepirrende…\p"
	.string "Tak, {PLAYER}{KUN}.\n"
	.string "Hvis vi mødes igen, håber jeg, du vil være\l"
	.string "lige så hjælpsom.$"

gText_ApprenticeWhichMove15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig rigtig?\p"
	.string "Måske er du en af de populære\n"
	.string "mimics?\p"
	.string "Nej, nej, hvis du er rigtig, er det fint.\n"
	.string "Ingen grund til at blive ked af det, jeg forsikrer dig!\p"
	.string "Forresten, jeg vil gerne have\n"
	.string "dit råd.\p"
	.string "Det handler om min {STR_VAR_1}.\p"
	.string "Hvilket move ville være bedre for den at\n"
	.string "bruge, {STR_VAR_2} eller {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Der er ingen tvivl om det?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er det fint.\n"
	.string "Jeg takker dig for din tid.\p"
	.string "Jeg håber, det er noget, som selv\n"
	.string "min POKéMON kan lære.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticePickWinSpeech0::
	.string "Åh… {PLAYER}?\n"
	.string "Det er {PLAYER}!\l"
	.string "Åh! Snøft… Snuft… Vær venlig at lytte!\p"
	.string "Jeg… Når jeg kæmper, bliver jeg så nervøs,\n"
	.string "at jeg ikke kan lade være med at græde, selvom jeg vinder…\p"
	.string "Jeg ville ønske, jeg kunne sige noget sejt\n"
	.string "når jeg vinder…\p"
	.string "Vær venlig, vær venlig, {PLAYER}!\n"
	.string "Kan du måske lære mig noget sejt at sige,\l"
	.string "når jeg vinder, så jeg ikke græder?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Fantastisk! Cool! Awoooh!\n"
	.string "Det er virkelig sejt!\p"
	.string "Åh… Jeg er ked af det…\n"
	.string "Jeg er så glad, at jeg græder…\p"
	.string "Snøft… {PLAYER}!\n"
	.string "Tak for alt!\p"
	.string "Jeg vil kæmpe mit bedste for\n"
	.string "din skyld, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Næste gang… Skal vi kæmpe!$"

gText_ApprenticePickWinSpeech1::
	.string "Yay! Det er {PLAYER}! Hej!\n"
	.string "Jeg ville spørge dig om noget!\p"
	.string "Jeg vil sige noget sejt, når\n"
	.string "jeg vinder en kamp.\p"
	.string "Har du en sej sætning, som\n"
	.string "du kan anbefale?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Åh, wow! Det er så sejt!\n"
	.string "Okay, det vil jeg sige!\p"
	.string "Tak fordi du har lært mig alt dette!\n"
	.string "Jeg vil gøre mit bedste uanset hvor\l"
	.string "jeg går fra nu af!\p"
	.string "Når vi mødes igen, vil det være til\n"
	.string "en kamp!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, hej!\p"
	.string "Mine POKéMON og jeg er klar til\n"
	.string "alt, undtagen én ting.\p"
	.string "Jeg synes, det ville være godt, hvis jeg havde\n"
	.string "noget at råbe, når jeg vinder.\p"
	.string "Kan du finde på noget godt\n"
	.string "at sige?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Sejt!\n"
	.string "Det vil jeg bruge!\p"
	.string "Jeg vil ud og kæmpe overalt\n"
	.string "i verden.\p"
	.string "Hvem ved, måske får jeg endda\n"
	.string "lov til at kæmpe mod dig en dag, {PLAYER}.\p"
	.string "Næste gang, lad os mødes et sted\n"
	.string "for kamp!$"

gText_ApprenticePickWinSpeech3::
	.string "Hej, {PLAYER}…\n"
	.string "Jeg er ked af at forstyrre dig, men jeg er håbløs…\p"
	.string "Selv når…\n"
	.string "Selv når jeg vinder, har jeg ikke noget\l"
	.string "specielt at sige…\p"
	.string "Jeg ved, det ikke betyder noget\n"
	.string "for dig, {PLAYER}.\p"
	.string "Men det betyder meget for mig…\p"
	.string "Vær venlig, {PLAYER}, hvad skal jeg sige\n"
	.string "hvis jeg vinder en kamp?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Det er inspireret…\p"
	.string "Uh… Er det okay for en som mig\n"
	.string "at sige det?\p"
	.string "Nej! Jeg vil gøre mit bedste!\p"
	.string "{PLAYER}, tusind tak for\n"
	.string "at holde ud med mig så længe…\p"
	.string "Jeg lover at gøre mit bedste fremover.\p"
	.string "Jeg er sikker på, at du hurtigt vil glemme\n"
	.string "en som mig, men lad os mødes\l"
	.string "igen et sted!$"

gText_ApprenticePickWinSpeech4::
	.string "Åh, {PLAYER}{KUN}.\n"
	.string "Der er noget, jeg vil have dig til at høre.\p"
	.string "Jeg ved, at jeg ikke altid lyder\n"
	.string "venlig eller høflig…\p"
	.string "Når jeg vinder en kamp, tror jeg, at jeg\n"
	.string "kommer til at lyde arrogant.\p"
	.string "Jeg vil ikke have folk til at mislike mig,\n"
	.string "så jeg vil sige noget pænt til\l"
	.string "den jeg slår.\p"
	.string "Men jeg kan ikke finde på noget godt!\n"
	.string "Kan du finde på noget for mig?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Ikke dårligt!\n"
	.string "Ja, det vil jeg bruge!\p"
	.string "Jeg vil tage på vejen og gøre, hvad\n"
	.string "jeg kan med det, du har lært mig, i\l"
	.string "mit hoved og hjerte.\p"
	.string "Jeg er ked af, at jeg har været så påtrængende\n"
	.string "over for dig!\p"
	.string "Næste gang kæmper vi, okay?\n"
	.string "Vi ses!$"

gText_ApprenticePickWinSpeech5::
	.string "Åh, jeg kan ikke komme over, hvor travlt jeg har!\n"
	.string "Åh, hej, jeg ledte efter dig, {PLAYER}{KUN}.\p"
	.string "Har du det godt som altid?\n"
	.string "Tingene har ikke ændret sig for mig.\p"
	.string "Jeg skal løbe, kæmpe og kortlægge\n"
	.string "ting. Hvorfor har jeg så travlt?\p"
	.string "Men selvom jeg har travlt, ville det være uhøfligt\n"
	.string "bare at vende om og gå væk\l"
	.string "fra en sejr uden at sige et ord.\p"
	.string "Så hvad ville være en sej sætning til\n"
	.string "at understrege min coolness, når jeg er færdig\l"
	.string "og går væk? {PLAYER}{KUN}, hjælp mig!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Okay, forstået.\n"
	.string "Jeg kan finde tid til at sige det!\p"
	.string "Ærligt talt, jeg er glad for, at jeg mødte en god mentor\n"
	.string "som dig.\p"
	.string "Jeg vil finde tid på en eller anden måde, så\n"
	.string "jeg kan komme i kamp.\p"
	.string "Tak for alt, {PLAYER}{KUN}!\n"
	.string "Vi skal kæmpe, du og jeg, en dag!$"

gText_ApprenticePickWinSpeech6::
	.string "Jeg havde heldet med mig igen!\n"
	.string "{PLAYER}! Jeg er glad for at se dig!\l"
	.string "Som sædvanlig har jeg brug for dit råd!\p"
	.string "Trommehvirvel, tak!\n"
	.string "Mit sidste spørgsmål er…\p"
	.string "Hvis jeg vinder en kamp og vil afslutte\n"
	.string "den med et sejt træk, hvad\l"
	.string "skal jeg sige?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Det… Det er fantastisk!\n"
	.string "Det er værdigt og sejt! Det vil jeg bruge!\p"
	.string "…Hør, jeg tror, jeg bliver bedre til det her, huh?\p"
	.string "Så jeg tænker på at udfordre andre\n"
	.string "TRÆNERE fra nu af.\p"
	.string "{PLAYER}, dine råd har virkelig hjulpet mig.\p"
	.string "Måske en dag, vil der være en tid, hvor\n"
	.string "vi kæmper!\p"
	.string "Tak for alt!$"

// Danish translation
gText_ApprenticePickWinSpeech7::
	.string "Åh, {PLAYER}.\n"
	.string "Jeg er så glad for at møde dig!\p"
	.string "Jeg har ikke længere nogen bekymringer\n"
	.string "med hensyn til mine POKéMON.\p"
	.string "Det er mig selv, der bekymrer mig…\p"
	.string "Ved du hvordan en TRÆNER siger\n"
	.string "nogle få ting efter at have vundet en kamp?\p"
	.string "Det ville jeg virkelig også ønske, jeg kunne gøre!\n"
	.string "Vær venlig, hvad skal jeg sige, når\n"
	.string "jeg vinder en kamp?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Åh! Den sætning! Den opfrisker mig\n"
	.string "og får mig til at føle mig genfødt!\p"
	.string "Jeg må bruge den med det samme!\p"
	.string "Og nu må jeg tage afsted,\n"
	.string "{PLAYER}…\p"
	.string "Jeg vil gå ud og kæmpe mod mange andre,\n"
	.string "men jeg vil aldrig glemme dine læreråd.\p"
	.string "Måske en dag…\n"
	.string "Farvel!$"

gText_ApprenticePickWinSpeech8::
	.string "Eek! Jeg så {PLAYER}!\n"
	.string "Jeg… Jeg er overglad for at se dig!\p"
	.string "Åh-åh-åh! Der er noget, jeg bare\n"
	.string "må spørge dig om!\p"
	.string "For lidt tid siden vandt jeg en kamp.\n"
	.string "Den del var spændende!\p"
	.string "Men det gjorde mig så overglad, at\n"
	.string "jeg blev stum og kunne ikke sige noget!\p"
	.string "Så nu, {PLAYER}, vær venlig, jeg vil have dig til\n"
	.string "at finde en afslutningsreplik til mig, når jeg vinder!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "Jeg skal sige det?!\l"
	.string "Jeg… Jeg er overvældet af glæde!\p"
	.string "Th-th-thank you!\n"
	.string "Jeg har intet tilbage at fortryde nu!\p"
	.string "Jeg vil rejse nu og kæmpe\n"
	.string "mod alle slags mennesker.\p"
	.string "Alt dette skylder jeg dig, {PLAYER}.\n"
	.string "Virkelig, virkelig, tak!\p"
	.string "Jeg skal gå nu, men lad os mødes\n"
	.string "i kamp en dag!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Du ved, jeg får lyst til at strejfe\n"
	.string "rundt og kæmpe, hvor jeg kan.\p"
	.string "Men før jeg gør det, vil jeg gerne\n"
	.string "have dit råd igen, tak!\p"
	.string "Hvis jeg skulle vinde en kamp, hvad ville\n"
	.string "være en god pral, jeg kunne sige til min\l"
	.string "faldne TRÆNER modstander?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, det er sødt!\n"
	.string "Si, bueno!\l"
	.string "Jeg vil prøve at sige det, som, ham!\p"
	.string "Og nu er det tid til at sige farvel!\n"
	.string "Tak for alt muligt!\p"
	.string "Giv mig en kamp en dag, okay?\n"
	.string "Adios!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, der er store problemer!\p"
	.string "Når jeg vinder en kamp, praler jeg om det\n"
	.string "i mindst en time!\p"
	.string "Selvfølgelig lyver jeg!\n"
	.string "Wahahaha!\p"
	.string "Dette er ingen løgn, dog.\n"
	.string "Jeg er ikke særlig god til at snakke.\p"
	.string "Så, hvordan med at beslutte for mig, hvad\n"
	.string "jeg skal sige efter at have vundet en kamp,\l"
	.string "mester?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Det er det, jeg skal sige, huh?\n"
	.string "Så vil jeg undgå det!\p"
	.string "Bare for sjov!\n"
	.string "Jeg vil adlyde din undervisning, mester!\p"
	.string "Tak fordi du har lært mig alt dette,\n"
	.string "mester!\p"
	.string "Jeg begynder endelig at forstå, hvad det vil sige\n"
	.string "at være en TRÆNER.\p"
	.string "Jeg vil gå ud og vinde kampe\n"
	.string "mod enhver TRÆNER.\p"
	.string "Måske bliver det dig en dag, mester!\p"
	.string "Det var alt!\n"
	.string "Farvel, min mester!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y!\n"
	.string "Og det staver ahoy!\p"
	.string "Jeg er den rappende SØMAND!\n"
	.string "Dette vil være mit sidste spørgsmål,\l"
	.string "græd ikke!\p"
	.string "Det er et spørgsmål om at sige noget\n"
	.string "der kræver dit forslag!\p"
	.string "Hvis jeg vinder en kamp, hvad kan jeg sige\n"
	.string "på en rigtig sej måde?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfekt! Det vil jeg bruge.\n"
	.string "Jeg havde ret i at vælge dig!\p"
	.string "Og nu, synes jeg, det ville være bedst,\n"
	.string "hvis jeg forlod reden!\p"
	.string "Tak for alt, du har lært mig.\n"
	.string "Jeg vil tage på en kamp spree!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "Og det staver bon voyage,\l"
	.string "til dig er dette min hyldest!$"

gText_ApprenticePickWinSpeech12::
	.string "Åh, yeah, {PLAYER}!\n"
	.string "Jeg fandt dig igen i dag!\p"
	.string "Hvad skal jeg gøre? Spørge dig igen?\n"
	.string "Hvorfor ikke? Jeg spørger dig allerede!\p"
	.string "Alligevel, {PLAYER}…\n"
	.string "Modtager du mig?\l"
	.string "Du modtager mig!\l"
	.string "Jeg har brug for mere råd!\p"
	.string "Det handler om, hvad jeg skal råbe.\n"
	.string "Noget sejt at råbe, når\l"
	.string "en kamp ender godt.\p"
	.string "Kom nu, jeg vil høre dig sige det!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Okay, okay!\n"
	.string "Jeg vil bruge det, fordi det er så tight!\p"
	.string "Jeg har ikke flere spørgsmål til dig.\n"
	.string "At vinke farvel er alt, der er tilbage at gøre.\p"
	.string "Men måske en dag mødes vi, med en\n"
	.string "bestemt til at gå ned i nederlag.\p"
	.string "Men det er virkelig tid til at sige farvel.\p"
	.string "Nå, {PLAYER}, jeg skal være fri,\n"
	.string "men glem ikke mig!\p"
	.string "Pas godt på, {PLAYER}!\n"
	.string "Elsker dig!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, jeg er færdig…\n"
	.string "Min næse stopper ikke med at løbe…\p"
	.string "Jeg prøvede at finde på noget\n"
	.string "sejt at sige, når jeg vinder en kamp.\p"
	.string "Det inspirerede mig så meget, at jeg begyndte at græde,\n"
	.string "og nu stopper min næse ikke med at løbe…\p"
	.string "Så, tingene er som de er,\n"
	.string "jeg har brug for, at du beslutter for mig, {PLAYER}{KUN}.\p"
	.string "Når jeg vinder en kamp,\n"
	.string "hvad skal jeg sige?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Det er godt.\n"
	.string "Nej, det er inspirerende!\l"
	.string "Det bringer friske tårer til mine øjne!\p"
	.string "Men på trods af mine tårer og løbende\n"
	.string "næse, vil jeg bruge den sætning!\p"
	.string "Jeg har ikke flere spørgsmål til dig,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Fra nu af er vi rivaler!\n"
	.string "Tak for alt!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Øhm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Vær venlig, kig ikke sådan på mig.\n"
	.string "Du gør mig nervøs.\p"
	.string "Jeg… Jeg har brug for dit råd igen.\n"
	.string "Jeg lover, det er sidste gang…\p"
	.string "Det er virkelig pinligt at spørge,\n"
	.string "men hvad nu, hvis jeg vinder en kamp?\l"
	.string "Hvad skal jeg sige?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Åh… Okay!\n"
	.string "Jeg vil prøve at sige det!\l"
	.string "Jeg er måske for nervøs til at sige det…\p"
	.string "Tak, {PLAYER}{KUN}.\n"
	.string "Jeg må sige farvel nu.\p"
	.string "Jeg vil adlyde alt, hvad du har lært mig,\n"
	.string "{PLAYER}{KUN}, og gøre mit bedste.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig?\l"
	.string "Måske en smart {PLAYER} DUKKE?\p"
	.string "Åh, nej, nej, nej, vær ikke bekymret!\n"
	.string "Hvis du virkelig er ægte, så glem\l"
	.string "min uhøflighed.\p"
	.string "Ingen grund til at være så vred. Alt, jeg ønsker,\n"
	.string "er mere af dit fine råd.\p"
	.string "Det handler om en sætning.\p"
	.string "Mere præcist, hvad skal jeg sige,\n"
	.string "hvis jeg vinder en kamp?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Når jeg vinder en kamp…\p"
	.string "{STR_VAR_1}\p"
	.string "…Er du seriøs?\p"
	.string "Jeg ser. Hvis du er seriøs, er det fint.\n"
	.string "Jeg takker dig for din tid.\p"
	.string "Jeg håber, at selv jeg vil være i stand til\n"
	.string "at bruge den sætning godt.\p"
	.string "Jeg synes, jeg er løbet tør for råd\n"
	.string "jeg har brug for.\p"
	.string "Jeg tror, det er på tide at sige farvel\n"
	.string "og stå på egne ben.\p"
	.string "Tak, min mentor!\n"
	.string "Jeg undskylder for min skepsis!$"
