@ TRANSLATED

gText_ApprenticeChallenge0::
	.string "Øhm, jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling. Snøft… Denne\l"
	.string "spænding er for meget for mig…$"

gText_ApprenticeChallenge1::
	.string "Jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling! Her kommer vi!$"

gText_ApprenticeChallenge2::
	.string "Jeg er nr. {STR_VAR_2} lærling for\n"
	.string "{STR_VAR_1}! Accepter min\l"
	.string "udfordring!$"

gText_ApprenticeChallenge3::
	.string "Øhm… Jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling… Tror du, at en\l"
	.string "som mig kan vinde?$"

gText_ApprenticeChallenge4::
	.string "Jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling! Jeg lader dig\l"
	.string "udfordre mig!$"

gText_ApprenticeChallenge5::
	.string "Jeg har frygteligt travlt, men jeg er\n"
	.string "også {STR_VAR_1}s nr.\l"
	.string "{STR_VAR_2} lærling.$"

gText_ApprenticeChallenge6::
	.string "Jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling. Glad for at møde\l"
	.string "dig!$"

gText_ApprenticeChallenge7::
	.string "Jeg tjener som {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling. Må jeg begynde?$"

gText_ApprenticeChallenge8::
	.string "Uuh! Jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling! Jeg vil gøre mit\l"
	.string "bedste!$"

gText_ApprenticeChallenge9::
	.string "Yeehaw! Jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling! Gør dig klar!$"

gText_ApprenticeChallenge10::
	.string "Jeg er {STR_VAR_1}s 1.000. lærling!\n"
	.string "Faktisk er jeg nr. {STR_VAR_2}! Nu går\l"
	.string "det løs!$"

gText_ApprenticeChallenge11::
	.string "Ja, jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling! Lad os rocke og\l"
	.string "rulle!$"

gText_ApprenticeChallenge12::
	.string "Yippee-yahoo! Jeg er, hvad du kalder\n"
	.string "{STR_VAR_1}s nr. {STR_VAR_2}\l"
	.string "lærling!$"

gText_ApprenticeChallenge13::
	.string "Host! Jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling. Godt at møde\l"
	.string "dig! Host!$"

gText_ApprenticeChallenge14::
	.string "Dette er nervepirrende… Jeg er nr.\n"
	.string "{STR_VAR_2} lærling for\l"
	.string "{STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Jeg er {STR_VAR_1}s nr.\n"
	.string "{STR_VAR_2} lærling, og det er ingen\l"
	.string "løgn.$"

gText_ApprenticePleaseTeach0::
	.string "Er du… {PLAYER}? Åh! Sniff…snøft…\p"
	.string "Åh! Undskyld… Jeg er så nervøs, jeg kan\n"
	.string "ikke holde op med at græde…\p"
	.string "Jeg er {STR_VAR_1}, og jeg ser\n"
	.string "virkelig op til dig, {PLAYER}.\p"
	.string "Jeg… Jeg havde denne drøm om en dag at\n"
	.string "møde dig og spørge dig om POKéMON.\p"
	.string "Please, please, {PLAYER}! Please teach\n"
	.string "me about POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Åh… M-men… Snøft… Waaah!\p"
	.string "Please! Jeg beder dig, please!$"

gText_ApprenticeWhichLevelMode0::
	.string "Åh, virkelig? Vil du? Fantastisk! Fedt!\n"
	.string "Awoooh!\p"
	.string "Åh… Undskyld… Jeg er så glad, jeg\n"
	.string "græder…\p"
	.string "Øhm… Så fortæl mig venligst! Det handler\n"
	.string "om BATTLE TOWER.\p"
	.string "Hvilket ville være bedre for mig: Level\n"
	.string "50 eller Open Level?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}? Waaaaah!\p"
	.string "Åh! Jeg er så ked af det! Du har gjort\n"
	.string "mig glad ved at vælge niveauet for mig,\l"
	.string "og det har gjort mig rørt…\p"
	.string "Snøft… Mange tak! Please talk with me\n"
	.string "again!$"

gText_ApprenticePleaseTeach1::
	.string "Wowee! Du er {PLAYER}, ikke sandt? Du\n"
	.string "er utrolig stærk, ikke sandt?\p"
	.string "Jeg er {STR_VAR_1}! Jeg er lige\n"
	.string "blevet en TRAINER!\p"
	.string "Please, {PLAYER}! Kan du være min lærer\n"
	.string "og fortælle mig masser om at være\l"
	.string "TRAINER?$"

gText_ApprenticeRejectTeaching1::
	.string "Øv, hvorfor? Åh, please? Pretty please?\n"
	.string "Please be my teacher, please!$"

gText_ApprenticeWhichLevelMode1::
	.string "Yay! Fantastisk!\p"
	.string "Det første, jeg ville spørge dig om, er\n"
	.string "om BATTLE TOWER!\p"
	.string "Level 50 og Open Level Rooms… Hvilket\n"
	.string "ville være perfekt for mig?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, ikke sandt? Det er\n"
	.string "sandt! Jeg vil gøre mit bedste der!\p"
	.string "Hvis vi mødes her igen, please teach mig\n"
	.string "noget andet, lærer!$"

gText_ApprenticePleaseTeach2::
	.string "Øhm… Er du {PLAYER}? Mit navn er\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg vil gerne blive en POKéMON TRAINER,\n"
	.string "men jeg ved ikke, hvad jeg skal gøre…\p"
	.string "Så jeg tænkte måske, jeg kunne spørge\n"
	.string "dig om råd, fordi du er så berømt.\p"
	.string "{PLAYER}, kunne du give mig råd?$"

gText_ApprenticeRejectTeaching2::
	.string "Åh, men…\p"
	.string "Jeg vil virkelig gerne blive en POKéMON\n"
	.string "TRAINER!\p"
	.string "Please, kan du besvare mine spørgsmål?$"

gText_ApprenticeWhichLevelMode2::
	.string "Tak! Her er mit første spørgsmål med\n"
	.string "det samme!\p"
	.string "BATTLE TOWER har to niveauer, Level 50\n"
	.string "og Open Level, ikke?\p"
	.string "Hvilket niveau tror du er mere passende\n"
	.string "for mig?$"

gText_ApprenticeLevelModeThanks2::
	.string "Åh, {STR_VAR_1} udfordring?\n"
	.string "Forstået!\p"
	.string "Hvis jeg har et andet spørgsmål, kommer\n"
	.string "jeg tilbage her for at få dit råd!$"

gText_ApprenticePleaseTeach3::
	.string "Åh? Hvad? Du er… Nej, det kan ikke\n"
	.string "passe.\p"
	.string "Der er ingen måde, at en som mig kunne\n"
	.string "møde {PLAYER}.\p"
	.string "…Er du virkelig {PLAYER}? Jeg kan ikke\n"
	.string "tro, jeg taler med dig!\p"
	.string "Når noget så godt sker, vil kun\n"
	.string "frygtelige ting ske for mig nu, jeg ved\l"
	.string "det bare…\p"
	.string "…Jeg er ked af det… Jeg er…\n"
	.string "{STR_VAR_1}…\p"
	.string "Der er intet specielt ved mig, som jeg\n"
	.string "kan være stolt af…\p"
	.string "Jeg burde ikke engang sige noget om mig\n"
	.string "selv, fordi du vil glemme det…\p"
	.string "Jeg havde en drøm om, at hvis jeg\n"
	.string "nogensinde mødte dig, {PLAYER}, så\l"
	.string "kunne jeg måske bede dig om råd som en\l"
	.string "TRÆNER.\p"
	.string "Men jeg tror ikke, du vil gå med til det.\p"
	.string "…Eller vil du være så venlig at give mig\n"
	.string "råd?$"

gText_ApprenticeRejectTeaching3::
	.string "Jeg vidste det…\p"
	.string "Det måtte ske, fordi jeg er sådan en\n"
	.string "virkelig kedelig person…\p"
	.string "Men jeg tænkte bare måske… Du vil ikke\n"
	.string "genoverveje, vil du?\p"
	.string "Men jeg kan ikke give op sådan. Jeg vil\n"
	.string "spørge dig, mens jeg stadig er heldig!\p"
	.string "Vil du være så venlig at give mig råd?\p"
	.string "Virkelig? Jeg kan ikke tro det! Jeg kan\n"
	.string "ikke tro, du vil rådgive mig! Jeg… Jeg er\l"
	.string "så glad…\p"
	.string "Det, jeg vil spørge dig om, er virkelig\n"
	.string "banalt, men jeg kan ikke beslutte mig…\p"
	.string "Ved KAMP TÅRNET lader de dig vælge\n"
	.string "Level 50 eller Åben Level.\p"
	.string "Hvilket kursus tror du, jeg måske har en\n"
	.string "chance ved?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Okay! Men tror du\n"
	.string "virkelig, at en som mig ville have en\l"
	.string "chance?\p"
	.string "Jeg vil gøre mit bedste, selvom jeg ikke\n"
	.string "tror, det vil lykkes.\p"
	.string "Mange tak for at bruge tid med en som\n"
	.string "mig.$"

gText_ApprenticePleaseTeach4::
	.string "Åh! Du er {PLAYER}{KUN}, er du ikke?\p"
	.string "Jeg har hørt, at du er god til POKéMON!\p"
	.string "Jeg er {STR_VAR_1}! Jeg vil være din\n"
	.string "ven!\p"
	.string "Vidste du?\p"
	.string "Du kan ikke vinde ved BATTLE FRONTIER,\n"
	.string "hvis alt du ved, er hvad de lærer på\l"
	.string "TRÆNER SKOLEN.\p"
	.string "Jeg er villig til at lytte til dine råd. Du\n"
	.string "vil selvfølgelig være enig, ikke?$"

gText_ApprenticeRejectTeaching4::
	.string "Hvad? Hvorfor afviser du mig? Det er\n"
	.string "mig, der spørger dig! Du er nødt til at\l"
	.string "genoverveje!$"

gText_ApprenticeWhichLevelMode4::
	.string "Okay, så der er noget her. Jeg vil have,\n"
	.string "at du beslutter for mig.\p"
	.string "Du ved, at BATTLE TOWER har Level 50 og\n"
	.string "Åben Level Rum?\p"
	.string "Hvilket tror du ville være godt for mig,\n"
	.string "{PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Okay, {STR_VAR_1} er passende for\n"
	.string "mig? Tak!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af\l"
	.string "det, hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticePleaseTeach5::
	.string "Åh, hej der! {PLAYER}{KUN}! Jeg kender dig,\n"
	.string "fordi du er berømt! Kald mig\l"
	.string "{STR_VAR_1}! Glad for at møde dig!\p"
	.string "Jeg er en TRIATHLET, så jeg holder mig i\n"
	.string "form, selv mens jeg træner POKéMON.\p"
	.string "Jeg er også involveret i andre ting som\n"
	.string "arbejde, lur, selskabsdans…\p"
	.string "Når jeg er så travl, er det ikke så nemt\n"
	.string "for mig at blive en ordentlig TRÆNER.\p"
	.string "Så jeg har et forslag!\p"
	.string "Der må være en grund til, at vi mødtes.\n"
	.string "Så, {PLAYER}{KUN}, hvad med at dele din\l"
	.string "visdom med mig en gang imellem?$"

gText_ApprenticeRejectTeaching5::
	.string "Åh, men, vær sød? En fyr som mig har brug\n"
	.string "for en som dig, {PLAYER}{KUN}!\p"
	.string "Ærligt talt, jeg har brug for dit råd!$"

gText_ApprenticeWhichLevelMode5::
	.string "Tak! Det er mere som det skal være! Så\n"
	.string "lad os starte med en nem en!\p"
	.string "Du kender til BATTLE TOWERs to baner,\n"
	.string "ikke? Du ved, Level 50 og Åben Level.\p"
	.string "Mig som en travl fyr, hvilken en skal jeg\n"
	.string "forberede mig til?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, huh? Okay, forstået.\n"
	.string "Jeg finder tid på en eller anden måde og\l"
	.string "prøver!\p"
	.string "…Ups, jeg må hellere komme på arbejde!\n"
	.string "Tak! Vi ses!$"

gText_ApprenticePleaseTeach6::
	.string "Det kan ikke være rigtigt! Er du måske\n"
	.string "den ægte {PLAYER}?\p"
	.string "A-hah! Fantastisk! Jeg er\n"
	.string "{STR_VAR_1}, glæder mig til at møde\l"
	.string "dig!\p"
	.string "{PLAYER}, du er meget stærk, ikke?\p"
	.string "Alle taler om dig!\p"
	.string "Åh! Jeg fik lige en god idé! Jeg vil få\n"
	.string "råd fra dig, {PLAYER}! Jeg er sikker på,\l"
	.string "det vil gøre mig stærkere!\p"
	.string "Er det ikke en god idé? Vær sød, jeg vil\n"
	.string "have dit råd!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, du kan lade som om du er ond,\n"
	.string "men du kan ikke narre mig! Du mener\l"
	.string "virkelig okay, ikke?$"

gText_ApprenticeWhichLevelMode6::
	.string "Yay! Jeg vidste, du havde et stort\n"
	.string "hjerte, {PLAYER}!\p"
	.string "Hvad skal jeg spørge dig først om? …Åh,\n"
	.string "jeg kom i tanke om noget!\p"
	.string "Trommehvirvel, tak! Mit spørgsmål er…\p"
	.string "Hvis jeg skulle tage en BATTLE TOWER\n"
	.string "udfordring, hvilken vej skal jeg gå?\p"
	.string "Level 50 eller Åben Level? Hvad passer\n"
	.string "mig bedst?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh! {STR_VAR_1}, siger du! Tak\n"
	.string "for et super sejt svar!\p"
	.string "Jeg tror, det var alt, jeg ville spørge\n"
	.string "dig om i dag.\p"
	.string "Lad os mødes her igen, okay? Tak!$"

gText_ApprenticePleaseTeach7::
	.string "Undskyld mig, men… Er du {PLAYER}?\p"
	.string "Jeg er {STR_VAR_1}, og jeg er glad\n"
	.string "for at gøre din bekendtskab.\p"
	.string "Jeg har længe beundret dig…\p"
	.string "… … … … … …\p"
	.string "Øhm… Jeg håber ikke, at du finder denne\n"
	.string "anmodning for belastende, men…\p"
	.string "Må jeg blive din lærling, {PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Åh…!\p"
	.string "… … … … … … … … … … … …\p"
	.string "…Jeg må være besvimet af chok. Jeg er\n"
	.string "ked af det, jeg må have hørt forkert.\p"
	.string "Vær sød! Sig, at du vil acceptere mig som\n"
	.string "din lærling!$"

gText_ApprenticeWhichLevelMode7::
	.string "Åh… Jeg er henrykt!\p"
	.string "Jeg vil ikke spilde din tid, så vær venlig\n"
	.string "at rådgive mig om dette.\p"
	.string "Jeg planlægger at tage en BATTLE TOWER\n"
	.string "udfordring snart.\p"
	.string "Men der er to niveauer…\p"
	.string "Hvilket vil være mest passende for mig?\n"
	.string "Level 50 eller Åben Level?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} er dit valg! Jeg\n"
	.string "forstår. Jeg vil gøre mit bedste!\p"
	.string "Tak, {PLAYER}. Jeg håber, jeg kan\n"
	.string "regne med dig igen. Pas godt på dig selv!$"

gText_ApprenticePleaseTeach8::
	.string "Eek! Eek! {PLAYER}! Du talte til mig!\n"
	.string "Jeg… Jeg er overvældet af glæde!\p"
	.string "Mig! Mit navn er {STR_VAR_1}! Jeg er\n"
	.string "lige blevet en TRÆNER!\p"
	.string "Jeg er glad for at have mødt dig,\n"
	.string "{PLAYER}, den store navn i POKéMON\l"
	.string "kredse!\p"
	.string "Åh-åh-åh, jeg ved det! Må jeg bede om\n"
	.string "en stor tjeneste, {PLAYER}?\p"
	.string "Tag mig ind som din lærling! Jeg vil lære\n"
	.string "fra dig!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah! {PLAYER} afviste mig… Det…\n"
	.string "Det er en uvurderlig oplevelse!\p"
	.string "{PLAYER}, vær sød! Jeg vil høre et\n"
	.string "bekræftende svar denne gang!\p"
	.string "Jeg beder om din vejledning!$"

gText_ApprenticeWhichLevelMode8::
	.string "Hieeeeh! {PLAYER} sagde ja!\n"
	.string "{PLAYER} sagde ja!\p"
	.string "Jeg vil ikke kunne sove i nat… Tusind\n"
	.string "tak!\p"
	.string "Så, her er mit spørgsmål!\p"
	.string "Ved BATTLE TOWER, hvad er bedst for\n"
	.string "mig, Level 50 eller Åben Level?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Helt forstået! Jeg\n"
	.string "forstår perfekt! Jeg er helt vildt glad!\p"
	.string "Jeg håber, du vil være villig til at lære\n"
	.string "mig noget mere en anden gang.$"

gText_ApprenticePleaseTeach9::
	.string "Whoa! Kunne du være… Er du måske…\n"
	.string "{PLAYER}{KUN}?! Den stærke og berømte\l"
	.string "TRÆNER? Nå, hej, er jeg ikke bare den\l"
	.string "heldigste!\p"
	.string "Hej, navnet er {STR_VAR_1}!\p"
	.string "Jeg har været på udkig efter en POKéMON\n"
	.string "lærer.\p"
	.string "Og med upåklagelig timing, kom du,\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Så der har du det, {PLAYER}{KUN}! Lad mig\n"
	.string "blive din lærling!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah! Du er ret cool og sej…\p"
	.string "Vær ikke sådan, vær sød. Jeg beder dig!$"

gText_ApprenticeWhichLevelMode9::
	.string "Åh, ja! Det er et solidt svar!\n"
	.string "Fremragende, må jeg tilføje!\p"
	.string "Så hvad med et første råd om BATTLE\n"
	.string "TOWER?\p"
	.string "Hvis jeg skulle tage derhen, hvad ville\n"
	.string "så være bedre? Level 50 eller Åben\l"
	.string "Level?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, {STR_VAR_1} er det! OK,\n"
	.string "A-OK! Jeg vil vise mit værd, som, straks!\p"
	.string "Okay, jeg vil se til dig som min mentor!\n"
	.string "Adios!$"

gText_ApprenticePleaseTeach10::
	.string "Åh, hej, {PLAYER}{KUN}, ikke? Politiet ledte\n"
	.string "efter dig!\p"
	.string "… … … Selvfølgelig lyver jeg!\p"
	.string "Mig, jeg er {STR_VAR_1}. Trods mit\n"
	.string "udseende er jeg POKéMON MESTER! …Det er\l"
	.string "også en løgn!\p"
	.string "Dette er dog ikke en løgn. Jeg er ikke\n"
	.string "særlig god til at kæmpe.\p"
	.string "Så hvad med at du bliver min mester i\n"
	.string "alt, hvad der angår POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "Hvis du vil være kold som is, skal jeg\n"
	.string "vise dig, hvad jeg gør!\p"
	.string "Waaah! Waaah! Waaah! Hik!\p"
	.string "Hahaha, det var mine FALSKE TÅRER!\p"
	.string "Kom nu, vil du ikke nok være min POKéMON\n"
	.string "mester?$"

gText_ApprenticeWhichLevelMode10::
	.string "Jubii! Jeg køber dig en båd for det!\p"
	.string "Selvfølgelig lyver jeg igen! Men… Tak,\n"
	.string "mester!\p"
	.string "Du ved, hvordan der er Level 50 og Åben\n"
	.string "Level ved BATTLE TOWER?\p"
	.string "Jeg har svært ved at beslutte, hvilket\n"
	.string "niveau jeg skal udfordre…\p"
	.string "Kan du beslutte for mig, mester?$"

gText_ApprenticeLevelModeThanks10::
	.string "Okay, så {STR_VAR_1} er bedre! Jeg\n"
	.string "går til det andet niveau, så!\p"
	.string "Bare for sjov! Jeg vil følge din lære,\n"
	.string "mester!\p"
	.string "Tak, mester! Jeg håber, du vil fortsætte\n"
	.string "med at lære mig!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y! Og det staver ahoy, og det\n"
	.string "betyder hej!\p"
	.string "Jeg er {STR_VAR_1}, den rappende\n"
	.string "SØMAND, det er mig!\p"
	.string "Din tur nu, fortæl mig lidt om dig selv,\n"
	.string "giv det et forsøg!\p"
	.string "Uh-huh, uh-huh! {PLAYER}{KUN} er dit navn,\n"
	.string "og POKéMON er dit spil!\p"
	.string "Og du er i en sart alder, hvor hele\n"
	.string "verden er din scene!\p"
	.string "Alligevel vil jeg bare sige, at du er den\n"
	.string "tiende TRÆNER, jeg har talt med i dag.\p"
	.string "Lad os fejre det! Bliv min mentor for at\n"
	.string "markere det!$"

gText_ApprenticeRejectTeaching11::
	.string "Men! Du skal arbejde med mig!\p"
	.string "Vær ikke så drilsk! Bliv min mentor, vær\n"
	.string "sød!$"

gText_ApprenticeWhichLevelMode11::
	.string "Det er det! {PLAYER}, du har ånden!\p"
	.string "Så her er mit første spørgsmål der\n"
	.string "beder om dit forslag!\p"
	.string "Det handler om BATTLE TOWER, og det\n"
	.string "afhænger af min styrke!\p"
	.string "Level 50 og Åben Level er der, hvilket er\n"
	.string "det, der er godt for mig?$"

gText_ApprenticeLevelModeThanks11::
	.string "Okay, {STR_VAR_1} er det, du siger!\n"
	.string "Jeg vil tage det på min vej!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticePleaseTeach12::
	.string "Sig, hey, er du ikke {PLAYER}? Hvad\n"
	.string "skal jeg gøre? Tale til dig? Hvorfor\l"
	.string "ikke? Jeg taler allerede til dig!\p"
	.string "{PLAYER}, er du overrasket over mig?\n"
	.string "Jeg må hellere fortælle dig, hvem jeg er!\p"
	.string "{STR_VAR_1} er, hvad du kan kalde\n"
	.string "mig. Den lyseste stjerne i guitardom, det\l"
	.string "er mig!\p"
	.string "Modtager du mig? Du modtager mig!\p"
	.string "Min held er på sit højeste, jeg vil komme\n"
	.string "med en anmodning!\p"
	.string "{PLAYER}, lad mig være din lærling! Jeg\n"
	.string "vil have, at du lærer mig alt!$"

gText_ApprenticeRejectTeaching12::
	.string "Du afviser mig altså? Jeg må bare\n"
	.string "spørge dig igen!\p"
	.string "{PLAYER}, jeg beder om at blive din\n"
	.string "lærling! Jeg har brug for, at du lærer mig\l"
	.string "alt!$"

gText_ApprenticeWhichLevelMode12::
	.string "Heldigt, ja, woohoo! Skal jeg stille dig\n"
	.string "et spørgsmål?\p"
	.string "Da vi er nær BATTLE TOWER, hvad med et\n"
	.string "spørgsmål om dets styrke?\p"
	.string "Af de valg du ser, hvilket er det rigtige\n"
	.string "for mig?$"

gText_ApprenticeLevelModeThanks12::
	.string "Hvis {STR_VAR_1} er, hvad du\n"
	.string "foreslår, må det være det allerbedste!\p"
	.string "Nå, {PLAYER}, jeg skal vandre frit, men\n"
	.string "glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticePleaseTeach13::
	.string "Åh, hej! Du der! Kan jeg få dig til at\n"
	.string "massere min skulder?\p"
	.string "…Ja, der! Det er det! Av, av! Oooh, det\n"
	.string "føles godt!\p"
	.string "Mit navn er {STR_VAR_1}. Jeg træner\n"
	.string "karate, men min krop er ikke bygget til\l"
	.string "at tåle det…\p"
	.string "Jeg besluttede mig for at kæmpe med\n"
	.string "POKéMON og gøre mig stærkere.\p"
	.string "Du er {PLAYER}{KUN}, ikke? POKéMON LIGA\n"
	.string "MESTEREN?\p"
	.string "Hør, kan jeg få dig til at give mig råd?$"

gText_ApprenticeRejectTeaching13::
	.string "Åh, hvorfor?\p"
	.string "Jeg vil ikke være til stor gene, jeg\n"
	.string "lover! Vær sød?$"

gText_ApprenticeWhichLevelMode13::
	.string "Tak. Rigtig godt af dig! …Host! Host!\p"
	.string "Oogh, jeg skal hurtigt blive stærkere…\p"
	.string "Jeg tager direkte til BATTLE TOWER, men\n"
	.string "hvad ville være bedre for mig? Level 50\l"
	.string "eller Åben Level?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, okay. Det er {STR_VAR_1}. Jeg går\n"
	.string "derhen med det samme.\p"
	.string "Jeg håber, jeg kan blive ved med at bede\n"
	.string "dig om hjælp - du er jo min mentor!$"

gText_ApprenticePleaseTeach14::
	.string "Er… Øhm… {PLAYER}{KUN}…?\p"
	.string "Vær venlig ikke at se på mig sådan. Du\n"
	.string "gør mig helt selvbevidst.\p"
	.string "Jeg… Jeg er {STR_VAR_1}.\p"
	.string "Jeg er virkelig flov over at sige dette,\n"
	.string "men jeg udforsker gamle ruiner og sådan.\p"
	.string "Jeg er endnu mere flov over at indrømme,\n"
	.string "at jeg er interesseret i BATTLE\l"
	.string "FRONTIER.\p"
	.string "{PLAYER}{KUN}, du har ry for at være en\n"
	.string "hård TRÆNER…\p"
	.string "Det er svært for mig at sige dette, men\n"
	.string "jeg vil gerne spørge om noget.\p"
	.string "Kunne du blive min lærer og give mig råd?$"

gText_ApprenticeRejectTeaching14::
	.string "Vær venlig ikke at afvise mig sådan! Jeg\n"
	.string "kan ikke leve med ydmygelsen.\p"
	.string "Vær venlig at blive min lærer! Jeg har\n"
	.string "brug for dit råd!$"

gText_ApprenticeWhichLevelMode14::
	.string "Th-thank you…\p"
	.string "Men vær venlig ikke at se på mig sådan.\n"
	.string "Det gør mig helt forfjamsket.\p"
	.string "Vær venlig at svare mig uden at se på\n"
	.string "mine øjne.\p"
	.string "Ved BATTLE TOWER… Hvilket niveau skal\n"
	.string "jeg forsøge?$"

gText_ApprenticeLevelModeThanks14::
	.string "Åh… Okay! Jeg vil prøve det.\p"
	.string "Jeg håber, jeg kan udfordre uden at\n"
	.string "blive helt forfjamsket…\p"
	.string "Tak, {PLAYER}{KUN}. Hvis vi mødes igen,\n"
	.string "håber jeg, du vil være lige så hjælpsom.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig ægte?\p"
	.string "Du kan kalde mig {STR_VAR_1}.\p"
	.string "Jeg har leget med tanken om at blive\n"
	.string "lærling under en stærk TRÆNER.\p"
	.string "Så jeg må sige, jeg er heldig, at du kom\n"
	.string "forbi! …Du er virkelig {PLAYER}{KUN}, ikke?\p"
	.string "Nej, nej, hvis du er ægte, er det fint.\n"
	.string "Jeg vil blot have dig til at anerkende\l"
	.string "mig som din lærling.$"

gText_ApprenticeRejectTeaching15::
	.string "Åh? Men hvad får dig til at afvise?\p"
	.string "Jeg undskylder for at være skeptisk om\n"
	.string "din identitet.\p"
	.string "Vær venlig at acceptere min\n"
	.string "undskyldning og acceptere mig som din\l"
	.string "lærling.$"

gText_ApprenticeWhichLevelMode15::
	.string "Du accepterer mig virkelig? Jeg ønsker\n"
	.string "ikke at fejre for tidligt.\p"
	.string "Hvis det er sandt, undskylder jeg. Men\n"
	.string "nu har jeg brug for dit råd.\p"
	.string "Hvis jeg skulle deltage i BATTLE TOWER,\n"
	.string "hvad ville så være værdigt for mig? Level\l"
	.string "50 eller Åben Level?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}? Er du sikker?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er\n"
	.string "det fint. Jeg takker dig for din tid.\p"
	.string "Jeg er klar over, at jeg kan irritere,\n"
	.string "men det glæder mig, at du har accepteret\l"
	.string "mig.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeWhatHeldItem0::
	.string "Suk… Snøft… Åh, {PLAYER}!\p"
	.string "Jeg er helt fanget i et dilemma, som jeg\n"
	.string "ikke kan beslutte.\p"
	.string "Jeg kan ikke beslutte, hvad jeg skal\n"
	.string "lade min {STR_VAR_1} holde.\p"
	.string "Fortæl mig venligst, {PLAYER}. Hvilket\n"
	.string "item skal jeg lade den holde?$"

gText_ApprenticeHoldNothing0::
	.string "Åh, virkelig? Jeg skal ikke lade min\n"
	.string "{STR_VAR_1} holde noget?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Åh, okay! Jeg er glad for, at det er\n"
	.string "afgjort! Fantastisk! Vildt! Awoooh!\p"
	.string "Tusind tak!$"

gText_ApprenticeThanksHeldItem0::
	.string "Åh, jeg er så glad… Jeg tror også, jeg\n"
	.string "har den {STR_VAR_1}.\p"
	.string "Jeg er glad for, at det er afgjort!\n"
	.string "Fantastisk! Vildt! Awoooh!\p"
	.string "Tusind tak!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaaah! Vær venlig ikke at være ond!\p"
	.string "Det item {STR_VAR_1} blev allerede\n"
	.string "anbefalet til mig før, snøft…\p"
	.string "Eller mener du, at jeg ikke skal lade min\n"
	.string "{STR_VAR_2} holde noget?$"

gText_ApprenticeWhatHeldItem1::
	.string "Yay! Det er {PLAYER}! Fantastisk! Jeg\n"
	.string "ville spørge dig om noget!\p"
	.string "Lader du dine POKéMON holde items? Jeg\n"
	.string "vil gerne lade mine holde items, men…\p"
	.string "Hvilket item ville være godt for\n"
	.string "{STR_VAR_1} at holde?\p"
	.string "Hvad synes du?$"

gText_ApprenticeHoldNothing1::
	.string "Hva? Mener du, at min {STR_VAR_1}\n"
	.string "ikke behøver at holde noget?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Åh, jeg forstår! Jeg gør det! Tak for at\n"
	.string "lære mig det!$"

gText_ApprenticeThanksHeldItem1::
	.string "Åh, wow! En {STR_VAR_1}, huh? Okay,\n"
	.string "jeg gør det!\p"
	.string "Tak for at lære mig det!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Åh, øh, nej, det var ikke det, jeg mente.\n"
	.string "Jeg vil gerne vide om et andet item end\l"
	.string "dem, jeg allerede kender.\p"
	.string "Eller mener du, at min POKéMON ikke\n"
	.string "behøver at holde noget denne gang?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, hej! Det handler om min\n"
	.string "{STR_VAR_1}…\p"
	.string "Jeg vil gerne lade den holde et godt\n"
	.string "item. Hvad ville være godt for den?$"

gText_ApprenticeHoldNothing2::
	.string "Åh, så min {STR_VAR_1} behøver ikke\n"
	.string "at holde noget?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Okay, jeg har forstået! Vi ses igen!$"

gText_ApprenticeThanksHeldItem2::
	.string "Åh, item {STR_VAR_1}? Forstået!\p"
	.string "Jeg vil gøre mit bedste for at finde en!\n"
	.string "Vi ses igen!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Nogen har allerede fortalt mig om\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg vil gerne have min POKéMON til at\n"
	.string "holde en anden slags item.\p"
	.string "Eller mener du, at {STR_VAR_2} ikke\n"
	.string "behøver at holde noget?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hej, {PLAYER}… Undskyld, jeg\n"
	.string "forstyrrer, men jeg har noget andet, jeg\l"
	.string "gerne vil spørge dig om.\p"
	.string "Jeg tror ikke, jeg er god nok til at\n"
	.string "vinde kampe alene, så jeg overvejer at\l"
	.string "lade min {STR_VAR_1} holde et item.\p"
	.string "Men jeg ved ikke, hvad der ville være\n"
	.string "godt.\p"
	.string "{PLAYER}, vær venlig, kan du beslutte\n"
	.string "for mig?$"

gText_ApprenticeHoldNothing3::
	.string "En POKéMON, der tilhører en som mig,\n"
	.string "ville have det bedre uden et item?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Jeg forstår… Du siger, jeg ikke skal\n"
	.string "stole på items. Jeg vil gøre mit bedste\l"
	.string "for ikke at gøre det!\p"
	.string "Tusind tak!$"

gText_ApprenticeThanksHeldItem3::
	.string "Itemet {STR_VAR_1}, okay. Jeg er\n"
	.string "ikke sikker på, om jeg kan få en… Nej!\l"
	.string "Jeg vil gøre mit bedste for at få den.\p"
	.string "Tusind tak!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Åh, men… Jeg tror, jeg har hørt om det\n"
	.string "før…\p"
	.string "Er det måske, fordi jeg ikke har\n"
	.string "håndteret itemet {STR_VAR_1} særlig\l"
	.string "godt?\p"
	.string "Eller mener du, at jeg ikke skal lade min\n"
	.string "{STR_VAR_2} holde noget?$"

gText_ApprenticeWhatHeldItem4::
	.string "Åh, {PLAYER}{KUN}. Der er noget, jeg gerne\n"
	.string "vil spørge dig om.\p"
	.string "Du ved, hvordan du besluttede, hvilke\n"
	.string "POKéMON jeg skulle have for mig?\p"
	.string "Men jeg spurgte dig aldrig, hvilket item\n"
	.string "den skulle holde.\p"
	.string "Siden du allerede gav mig råd, hvordan\n"
	.string "med at følge det til ende?\p"
	.string "Hvad ville være godt? Jeg vil gerne lade\n"
	.string "min {STR_VAR_1} holde noget.$"

gText_ApprenticeHoldNothing4::
	.string "Åh! Så min {STR_VAR_1} skal klare sig\n"
	.string "så godt som muligt uden noget?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Hvis du mener, det er bedst, gør jeg det.\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af\l"
	.string "det, hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeThanksHeldItem4::
	.string "Itemet {STR_VAR_1}, huh? Ikke\n"
	.string "dårligt. Jeg vil bruge det!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af\l"
	.string "det, hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Hva? Hvad siger du? Du fortalte mig\n"
	.string "allerede om {STR_VAR_1} før.\p"
	.string "Eller mener du, at min {STR_VAR_2}\n"
	.string "skal klare sig så godt som muligt uden\l"
	.string "noget?$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}{KUN}!\p"
	.string "Vi er begge travle, men vi ser ud til at\n"
	.string "løbe ind i hinanden alligevel!\p"
	.string "I dag skal jeg gå en tur, rengøre og\n"
	.string "børste.\p"
	.string "Jeg har ikke engang haft tid til at købe\n"
	.string "noget til min dyrebare {STR_VAR_1}.\p"
	.string "Jeg har ikke tid, så hvad med at give mig\n"
	.string "råd om, hvad jeg skal lade min\l"
	.string "{STR_VAR_1} holde?$"

gText_ApprenticeHoldNothing5::
	.string "Åh, så mig som en travl fyr, siger du at\n"
	.string "min {STR_VAR_1} ikke behøver noget?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Okay, forstået. Jeg behøver ikke tid til\n"
	.string "det.\p"
	.string "Tak for i dag! Vi ses!$"

gText_ApprenticeThanksHeldItem5::
	.string "Okay, forstået. Jeg finder tid på en\n"
	.string "eller anden måde og finder den\l"
	.string "{STR_VAR_1}, du anbefalede.\p"
	.string "Jeg er glad for at have mødt en god\n"
	.string "mentor som dig. Tak! Vi ses!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Hva? Jeg ved allerede om den\n"
	.string "{STR_VAR_1}.\p"
	.string "Åh, rigtigt, jeg forstår. Så mig som en\n"
	.string "travl fyr, siger du at min\l"
	.string "{STR_VAR_2} ikke behøver noget?$"

gText_ApprenticeWhatHeldItem6::
	.string "Hej, {PLAYER}! Det er mig! Jeg har brug\n"
	.string "for din hjælp igen i dag. Venligst, jeg\l"
	.string "har brug for dit råd!\p"
	.string "Trommehvirvel, tak! Mit spørgsmål er…\p"
	.string "Hvis jeg vil lade min {STR_VAR_1}\n"
	.string "holde et item, hvad skal det så være?$"

gText_ApprenticeHoldNothing6::
	.string "Er det rigtigt? Min {STR_VAR_1}\n"
	.string "behøver ikke at holde et item, siger du.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Okay, det er, hvad jeg vil gøre!\p"
	.string "Jeg tror, det var alt, jeg ville spørge\n"
	.string "dig om i dag.\p"
	.string "Lad os mødes her igen, okay? Tak!$"

gText_ApprenticeThanksHeldItem6::
	.string "Uh-huh! En {STR_VAR_1}. Hvilket sejt\n"
	.string "valg! Jeg vil bestemt prøve det!\p"
	.string "Jeg tror, det var alt, jeg ville spørge\n"
	.string "dig om i dag.\p"
	.string "Lad os mødes her igen, okay? Tak!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah! Det er fjollet! Du har allerede\n"
	.string "fortalt mig om den {STR_VAR_1} før!\p"
	.string "Har du det okay, {PLAYER}?\p"
	.string "Åh, vent! Min {STR_VAR_2} behøver\n"
	.string "ikke at holde et item, siger du.$"

gText_ApprenticeWhatHeldItem7::
	.string "Hej, {PLAYER}. Jeg håber, du har det\n"
	.string "godt.\p"
	.string "Må jeg spørge dig til råds?\p"
	.string "I en nylig kamp så det ud til, at min\n"
	.string "modstander havde givet sin POKéMON et\l"
	.string "item at holde.\p"
	.string "Som resultat blev jeg besejret…\p"
	.string "Jeg ønsker ikke at blive efterladt. Jeg\n"
	.string "vil gerne lade min {STR_VAR_1} holde\l"
	.string "et item, også.\p"
	.string "Det ville glæde mig, hvis du kunne\n"
	.string "beslutte hvad der ville være godt for\l"
	.string "min POKéMON…$"

gText_ApprenticeHoldNothing7::
	.string "Med andre ord… Min POKéMON har ikke\n"
	.string "brug for at holde et item?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Jeg forstår det klart nu! Jeg vil\n"
	.string "fortsætte på denne måde.\p"
	.string "Tak, {PLAYER}. Jeg håber, jeg kan\n"
	.string "regne med dig igen. Pas godt på dig selv!$"

gText_ApprenticeThanksHeldItem7::
	.string "En {STR_VAR_1} er det! Jeg vil\n"
	.string "bestille den med det samme.\p"
	.string "Tak, {PLAYER}. Jeg håber, jeg kan\n"
	.string "regne med dig igen. Pas godt på dig selv!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Du har allerede fortalt mig om det, og\n"
	.string "jeg har det allerede.\p"
	.string "Eller siger du… Min POKéMON har ikke\n"
	.string "brug for at holde et item?$"

gText_ApprenticeWhatHeldItem8::
	.string "Eek! {PLAYER}! Jeg… Jeg er overvældet\n"
	.string "af glæde over at se dig igen!\p"
	.string "Åh-åh-åh! Der er noget, jeg bare må\n"
	.string "spørge dig om, {PLAYER}!\p"
	.string "Vær venlig at beslutte, hvad min\n"
	.string "{STR_VAR_1} skal holde!$"

gText_ApprenticeHoldNothing8::
	.string "Åh, wow! Det forventede jeg ikke! Så, et\n"
	.string "item er ikke nødvendigt?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Perfekt forstået! Jeg vil fortsætte\n"
	.string "uden et item!\p"
	.string "Jeg håber, du vil lære mig noget mere en\n"
	.string "anden gang.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Jeg vil bruge det!\p"
	.string "Øhm… Kunne det være, {PLAYER}, at du\n"
	.string "også lader din POKéMON holde det item?\p"
	.string "Jeg vil helt sikkert skaffe det! Jeg\n"
	.string "håber, du vil lære mig noget mere en\l"
	.string "anden gang.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Hva? Du anbefalede den {STR_VAR_1}\n"
	.string "før, også.\p"
	.string "Er det det bedste item at holde? Eller\n"
	.string "mener du, at min {STR_VAR_2} ikke\l"
	.string "behøver noget at holde?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola! Min maestro, {PLAYER}{KUN}!\p"
	.string "Jeg vil gerne have dit råd om POKéMON\n"
	.string "redskaber.\p"
	.string "Hvad tror du ville være godt for min\n"
	.string "{STR_VAR_1} at holde?\p"
	.string "Vær ikke genert nu. Lad os få det ud!$"

gText_ApprenticeHoldNothing9::
	.string "Åh? Så du siger, at min {STR_VAR_1}\n"
	.string "kan vinde uden at holde noget item?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Si, bueno! Jeg vil give det mit bedste\n"
	.string "forsøg, som, slam!\p"
	.string "Okay, tak som altid! Adios!$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, det er en {STR_VAR_1}? Si,\n"
	.string "bueno! Jeg vil finde en, som, bam!\p"
	.string "Okay, tak som altid! Adios!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Nej, nej! Du har allerede fortalt mig om\n"
	.string "det {STR_VAR_1} før.\p"
	.string "Åh, vent lige et øjeblik… Så du siger, at\n"
	.string "min {STR_VAR_2} kan vinde uden at\l"
	.string "holde noget item?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, noget utroligt er sket!\p"
	.string "Jeg vågnede i morges, og min POKéMON\n"
	.string "havde 10 NUGGETS!\p"
	.string "Selvfølgelig lyver jeg! Wahahaha!\p"
	.string "Dette er dog ikke en løgn. Jeg er ikke\n"
	.string "særlig god til at tænke på, hvilke items\l"
	.string "POKéMON skal holde.\p"
	.string "Så hvad med at beslutte, hvad min\n"
	.string "{STR_VAR_1} skal holde, mester?$"

gText_ApprenticeHoldNothing10::
	.string "Hvad betyder det? Skal den ikke holde\n"
	.string "noget?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Okay, så den skal ikke holde noget. Så\n"
	.string "må jeg hellere få noget til den!\p"
	.string "Bare for sjov! Jeg vil følge din lære,\n"
	.string "mester!\p"
	.string "Tak, mester! Jeg håber, du vil fortsætte\n"
	.string "med at lære mig!$"

gText_ApprenticeThanksHeldItem10::
	.string "Okay, så det er en {STR_VAR_1}! Jeg\n"
	.string "vil lade den holde alt andet end det!\p"
	.string "Bare for sjov! Jeg vil følge din lære,\n"
	.string "mester!\p"
	.string "Tak, mester! Jeg håber, du vil fortsætte\n"
	.string "med at lære mig!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Øhm, du har fortalt mig om det før, ikke\n"
	.string "sandt?\p"
	.string "Er der ikke noget andet?\p"
	.string "Eller mener du, at jeg ikke skal lade min\n"
	.string "{STR_VAR_2} holde noget?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y! Og det staver ahoy!\p"
	.string "Jeg er den rappende SØMAND! Jeg\n"
	.string "præsenterer dig et spørgsmål der er ret\l"
	.string "fedt!\p"
	.string "Det er et item spørgsmål der beder om\n"
	.string "dit forslag!\p"
	.string "Min {STR_VAR_1} har brug for et item\n"
	.string "at holde, Hvad skal det være, hvis jeg må\l"
	.string "være fræk?$"

gText_ApprenticeHoldNothing11::
	.string "Er det rigtigt? Min {STR_VAR_1}\n"
	.string "behøver ikke at holde noget stramt?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Okay, jeg hører dig, selvfølgelig gør\n"
	.string "jeg! Min POKéMON vil også gå tomhændet!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeThanksHeldItem11::
	.string "Okay, en {STR_VAR_1}, det er, hvad\n"
	.string "jeg vil bruge. Jeg havde ret i at få dig\l"
	.string "til at vælge!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Okay, en {STR_VAR_1}, siger du? Du\n"
	.string "fortalte mig det den anden dag. Jeg har\l"
	.string "brug for en ny idé, en helt ny måde.\p"
	.string "Eller, hvad, er det rigtigt? Min POKéMON\n"
	.string "behøver ikke at holde noget stramt?$"

gText_ApprenticeWhatHeldItem12::
	.string "Sig, hey, {PLAYER}! Jeg fandt dig igen i\n"
	.string "dag!\p"
	.string "Hvad skal jeg gøre? Få dit råd? Hvorfor\n"
	.string "ikke? Jeg taler allerede med dig!\p"
	.string "{PLAYER}, er du ved at blive træt af\n"
	.string "mig? Nah, ingen måde, det kan ikke være.\p"
	.string "Vil du høre mig ud? Jeg leder efter\n"
	.string "råd--det er, hvad jeg taler om.\p"
	.string "Det handler om et item til min\n"
	.string "{STR_VAR_1} der ville være godt. Min\l"
	.string "ubeslutsomhed gør mig frustreret.$"

gText_ApprenticeHoldNothing12::
	.string "Min {STR_VAR_1} behøver ingenting?\n"
	.string "Behøver ikke at holde noget?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Hvis det bedste er at holde ingenting,\n"
	.string "vil jeg gøre, som du foreslår!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit, men\n"
	.string "glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeThanksHeldItem12::
	.string "Hvis det bedste er at holde den\n"
	.string "{STR_VAR_1}, vil jeg gøre, som du\l"
	.string "foreslår!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit, men\n"
	.string "glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Har jeg ikke hørt om den {STR_VAR_1}\n"
	.string "før? Jeg er sikker på, jeg har, det er\l"
	.string "sikkert!\p"
	.string "Jeg har brug for noget nyt! Eller, min\n"
	.string "{STR_VAR_2} behøver ingenting?\l"
	.string "Behøver ikke at holde noget?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah! Av! {PLAYER}{KUN}, min arm er\n"
	.string "brækket! Rør den ikke, vær sød!\p"
	.string "Jeg må have brækket den, mens jeg\n"
	.string "prøvede forskellige hold items med min\l"
	.string "flok af POKéMON.\p"
	.string "Så, som tingene er, har jeg brug for, at\n"
	.string "du beslutter for mig.\p"
	.string "{PLAYER}{KUN}, hvad synes du ville være\n"
	.string "godt for min {STR_VAR_1} at holde?$"

gText_ApprenticeHoldNothing13::
	.string "Av…\p"
	.string "Så du foreslår, at min {STR_VAR_1}\n"
	.string "ikke behøver at holde noget?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, okay. Det ville være lettere for mig,\n"
	.string "som tingene er nu.\p"
	.string "Jeg håber, jeg kan blive ved med at bede\n"
	.string "dig om hjælp som dette.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, okay. Det er en {STR_VAR_1}. Min\n"
	.string "POKéMONs arm er i orden, så jeg vil lade\l"
	.string "den holde det item med det samme.\p"
	.string "Jeg håber, jeg kan blive ved med at bede\n"
	.string "dig om hjælp som dette.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Nej, nej, du fortalte mig om den\n"
	.string "{STR_VAR_1} før, husker du?\p"
	.string "Hvad med at fortælle mig noget endnu\n"
	.string "bedre?\p"
	.string "Åh, vent et øjeblik. Så du foreslår, at\n"
	.string "min {STR_VAR_2} ikke behøver at\l"
	.string "holde noget?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Øhm… {PLAYER}{KUN}…\p"
	.string "Vær venlig ikke at se på mig sådan. Mine\n"
	.string "POKéMON har ikke noget.\p"
	.string "Jeg… Jeg er virkelig flov over dette,\n"
	.string "men jeg har virkelig brug for dit råd.\p"
	.string "Jeg kan ikke beslutte, hvilket item der\n"
	.string "ville gøre min {STR_VAR_1} stærk.\p"
	.string "{PLAYER}{KUN}, hvad synes du ville være\n"
	.string "godt?$"

gText_ApprenticeHoldNothing14::
	.string "Åh… Så du tror, det ville være bedre,\n"
	.string "hvis min {STR_VAR_1} ikke havde et\l"
	.string "item?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Åh… Okay! Jeg vil gå uden et item.\p"
	.string "Det er dog nervepirrende. Ville det ikke\n"
	.string "være for sejt?\p"
	.string "Tak, {PLAYER}{KUN}. Hvis vi mødes igen,\n"
	.string "håber jeg, du vil være lige så hjælpsom.$"

gText_ApprenticeThanksHeldItem14::
	.string "Åh… Okay! Jeg vil gå med den\n"
	.string "{STR_VAR_1}.\p"
	.string "Det er dog nervepirrende. Ville det ikke\n"
	.string "være for sejt?\p"
	.string "Tak, {PLAYER}{KUN}. Hvis vi mødes igen,\n"
	.string "håber jeg, du vil være lige så hjælpsom.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "M-men jeg har allerede hørt om det.\p"
	.string "Vær venlig ikke at afvise mig sådan! Jeg\n"
	.string "kan ikke leve med ydmygelsen.\p"
	.string "Åh… Springer jeg til konklusioner? Tror\n"
	.string "du, det ville være bedre, hvis min\l"
	.string "{STR_VAR_2} ikke havde et item?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig? Måske er du en\l"
	.string "tvilling?\p"
	.string "Åh, nej, nej, nej, bare rolig! Hvis du\n"
	.string "virkelig er {PLAYER}, så glem min\l"
	.string "uhøflighed.\p"
	.string "Hvad jeg gerne vil have, er noget mere\n"
	.string "af dit gode råd.\p"
	.string "Jeg har her min {STR_VAR_1}, som jeg\n"
	.string "gerne vil lade holde et praktisk item.\p"
	.string "Hvad ville være værdigt for den?$"

gText_ApprenticeHoldNothing15::
	.string "Det er bedre, hvis den ikke holder\n"
	.string "noget? Er du sikker?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Jeg forstår. Hvis det er tilfældet, er\n"
	.string "det fint. Jeg takker dig for din tid.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeThanksHeldItem15::
	.string "En {STR_VAR_1}? Er du sikker?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er\n"
	.string "det fint. Jeg takker dig for din tid.\p"
	.string "Jeg håber, min POKéMON vil kunne bruge\n"
	.string "det godt.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Nej, nej, vent et øjeblik. Jeg tror, du\n"
	.string "lærte mig det før.\p"
	.string "Jeg vil gerne have, at du anbefaler\n"
	.string "noget andet denne gang.\p"
	.string "Måske foreslår du, at min\n"
	.string "{STR_VAR_2} ikke skal holde noget?\l"
	.string "Er du sikker?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waah, {PLAYER}! Jeg har et dilemma,\n"
	.string "snøft…\p"
	.string "Jeg vil begynde at kæmpe mod andre, men\n"
	.string "jeg ved ikke, hvad jeg skal gøre.\p"
	.string "Hvordan skal jeg stille mine POKéMON op,\n"
	.string "så de er stærkest?\p"
	.string "Fortæl mig venligst, {PLAYER}. Hvis du\n"
	.string "var mig, hvilken af disse POKéMON ville\l"
	.string "du sende ud først?$"

gText_ApprenticeMonFirstThanks0::
	.string "Min {STR_VAR_1} skal gå først?\n"
	.string "Waaaaah!\p"
	.string "Åh! Jeg er så ked af det! Du har gjort\n"
	.string "mig glad ved at vælge min første\l"
	.string "POKéMON, og det har gjort mig rørt…\p"
	.string "Tusind tak!$"

gText_ApprenticeWhichMonFirst1::
	.string "Yay! Det er {PLAYER}! Fantastisk! Jeg\n"
	.string "ville spørge dig om noget!\p"
	.string "Øhm, af mine POKéMON, hvilken tror du\n"
	.string "skal gå ud først?$"

gText_ApprenticeMonFirstThanks1::
	.string "Min {STR_VAR_1}? Det er sandt. Okay,\n"
	.string "jeg gør det!\p"
	.string "Tak for at lære mig det!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, hej!\p"
	.string "Jeg tror, det er meget vigtigt i en kamp,\n"
	.string "hvilken POKéMON der kommer ud først.\p"
	.string "Ud af de POKéMON, jeg har, hvilken ville\n"
	.string "være god at sende ud først?$"

gText_ApprenticeMonFirstThanks2::
	.string "Min {STR_VAR_1} går først? Okay, jeg\n"
	.string "har forstået!\p"
	.string "Vi ses igen!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hej, {PLAYER}… Undskyld, jeg\n"
	.string "forstyrrer dig igen med endnu et\l"
	.string "spørgsmål.\p"
	.string "Jeg har så lidt selvtillid, jeg ved ikke,\n"
	.string "hvad jeg ville gøre uden dig, {PLAYER}.\p"
	.string "Det kan være spild af tid for mig\n"
	.string "overhovedet at bekymre mig om det, men\l"
	.string "jeg kan bare ikke beslutte mig…\p"
	.string "Hvilken af mine POKéMON skal jeg sende\n"
	.string "ud først i en kamp?$"

gText_ApprenticeMonFirstThanks3::
	.string "Min {STR_VAR_1}? Forstået!\p"
	.string "Jeg kan ikke tro, at du gider besvare\n"
	.string "mine spørgsmål så ofte!\p"
	.string "Jeg er så taknemmelig for, at du\n"
	.string "overhovedet vil tale med mig… Tak!$"

gText_ApprenticeWhichMonFirst4::
	.string "Åh, {PLAYER}{KUN}! Det er mig! Jeg er så\n"
	.string "glad for at se dig, fordi jeg har et lille\l"
	.string "problem.\p"
	.string "Jeg kan ikke beslutte, hvordan mine\n"
	.string "POKéMON skal stilles op. Kunne du\l"
	.string "beslutte for mig?\p"
	.string "Åh, du behøver ikke at beslutte hele\n"
	.string "holdet lige nu.\p"
	.string "Hvad med at beslutte kun den første\n"
	.string "POKéMON for mig?$"

gText_ApprenticeMonFirstThanks4::
	.string "Min {STR_VAR_1}? Det er fantastisk!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af\l"
	.string "det, hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hej, min lærer {PLAYER}{KUN}! Jeg har travlt\n"
	.string "igen i dag!\p"
	.string "Jeg skal cykle, handle ind, og nynne.\p"
	.string "Jeg har ikke engang haft tid til at\n"
	.string "beslutte, hvordan jeg skal stille mit\l"
	.string "POKéMON hold op.\p"
	.string "Så, hvad med at tjekke mit hold? Hvilken\n"
	.string "skal gå først?$"

gText_ApprenticeMonFirstThanks5::
	.string "Okay, forstået. Jeg har i det mindste\n"
	.string "tid nok til at sætte min {STR_VAR_1}\l"
	.string "først i rækken!\p"
	.string "Ups, min kæreste venter! Tak! Vi ses!$"

gText_ApprenticeWhichMonFirst6::
	.string "Yoohoo! Hej, {PLAYER}! Du går altid\n"
	.string "rundt og ser sej ud!\p"
	.string "Hør, jeg har brug for noget fra dig igen!\n"
	.string "Det er det sædvanlige!\p"
	.string "Trommehvirvel, tak! Mit spørgsmål\n"
	.string "handler om mit hold.\p"
	.string "Hvilken af mine POKéMON skal være den\n"
	.string "første til at gå ud i en kamp?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm! Min {STR_VAR_1}, siger du! Tak\n"
	.string "for et virkelig sejt svar!\p"
	.string "Jeg tror, det var alt, jeg ville spørge\n"
	.string "dig om i dag.\p"
	.string "Lad os mødes her igen, okay? Tak!$"

gText_ApprenticeWhichMonFirst7::
	.string "Tusind tak for at stoppe op og chatte\n"
	.string "med mig, {PLAYER}.\p"
	.string "Jeg ved, jeg udnytter din venlighed, men\n"
	.string "må jeg bede om råd?\p"
	.string "Jeg vil gerne have, at du beslutter\n"
	.string "rækkefølgen for mit POKéMON hold.\p"
	.string "Det ville glæde mig, hvis du kunne\n"
	.string "beslutte, hvilken POKéMON der skal\l"
	.string "komme først.$"

gText_ApprenticeMonFirstThanks7::
	.string "Min {STR_VAR_1} er det! Jeg vil\n"
	.string "sætte den først med det samme!\p"
	.string "Tak, {PLAYER}. Jeg håber, jeg kan\n"
	.string "regne med dig igen. Pas godt på dig selv!$"

gText_ApprenticeWhichMonFirst8::
	.string "Eek! {PLAYER}! Jeg… Jeg er overvældet\n"
	.string "af glæde over at se dig igen!\p"
	.string "Mine POKéMON er blevet meget stærkere!\p"
	.string "Men jeg vinder ikke altid. Det ser ud til\n"
	.string "at afhænge af, hvilken POKéMON der går\l"
	.string "først.\p"
	.string "{PLAYER}, vær venlig, jeg har brug for\n"
	.string "din hjælp!\p"
	.string "Vær venlig at beslutte, hvilken af mine\n"
	.string "POKéMON der skal gå ud først!$"

gText_ApprenticeMonFirstThanks8::
	.string "Suk… Jeg er overvældet af lykke…\p"
	.string "Det er som en drøm, at du beslutter for\n"
	.string "mig, {PLAYER}.\p"
	.string "Men perfekt forstået! Jeg vil sende min\n"
	.string "{STR_VAR_1} først ud!\p"
	.string "Jeg håber, du vil lære mig noget mere en\n"
	.string "anden gang.$"

gText_ApprenticeWhichMonFirst9::
	.string "Hej, hej! Min mentor, {PLAYER}{KUN}! Giv mig\n"
	.string "dit kloge råd i dag!\p"
	.string "Ser du, jeg har samlet et hold af tre\n"
	.string "POKéMON. Indtil videre så godt.\p"
	.string "Men holdets kamporden er endnu ikke\n"
	.string "afgjort.\p"
	.string "Det er her, du kommer ind, {PLAYER}{KUN}! Du\n"
	.string "bestemmer, hvilken POKéMON der fører\l"
	.string "an!\p"
	.string "Vær ikke genert nu. Lad os få det ud!$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, min {STR_VAR_1} fører an!\n"
	.string "OK, A-OK! Jeg vil omorganisere\l"
	.string "rækkefølgen, som, wham!\p"
	.string "Okay, tak som altid! Adios!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, hør! Det er en krise!\p"
	.string "Mine POKéMON, alle tre af dem, går ind i\n"
	.string "kamp på én gang!\p"
	.string "Selvfølgelig er det umuligt! Wahahaha!\p"
	.string "Dette er dog ingen løgn. Jeg er ikke\n"
	.string "særlig god til at tænke over hvordan jeg\l"
	.string "skal stille mine POKéMON op.\p"
	.string "Så, hvad med at beslutte for mig,\n"
	.string "hvilken POKéMON der skal gå først,\l"
	.string "mester?$"

gText_ApprenticeMonFirstThanks10::
	.string "Okay, så det er min {STR_VAR_1}, du\n"
	.string "valgte? Jeg vil lade enhver undtagen\l"
	.string "den gå først!\p"
	.string "Bare for sjov! Jeg vil følge din\n"
	.string "undervisning, mester!\p"
	.string "Tak, mester! Jeg håber, du vil fortsætte\n"
	.string "med at lære mig!$"

gText_ApprenticeWhichMonFirst11::
	.string "O-H-Ø-J! Sådan staves ohøj!\p"
	.string "Jeg er den rappende SØMAND! Jeg\n"
	.string "præsenterer dig et spørgsmål der er ret\l"
	.string "fedt!\p"
	.string "Det er et holdopstillingsspørgsmål der\n"
	.string "beder om dit forslag!\p"
	.string "Ud af dette hold, hvilken skal gå først\n"
	.string "som den første på stedet?$"

gText_ApprenticeMonFirstThanks11::
	.string "Okay, jeg hører dig, selvfølgelig gør\n"
	.string "jeg! Jeg bytter dem om, det gør jeg!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}! Hvordan går det?\p"
	.string "Hvad skal jeg gøre? Spørge om råd?\n"
	.string "Uh-huh, jeg har noget at spørge om!\l"
	.string "Modtager du mig? Du modtager mig!\p"
	.string "Du skal beslutte, hvilken af mine\n"
	.string "POKéMON der skal først! I kamp, mener\l"
	.string "jeg.$"

gText_ApprenticeMonFirstThanks12::
	.string "Min {STR_VAR_1}? Ja! Det er fint,\n"
	.string "ingen nød!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit, men\n"
	.string "glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Uff…av… {PLAYER}{KUN}… Min mave gør ondt\n"
	.string "pludselig…\p"
	.string "…Det bliver bedre nu…\p"
	.string "Jeg må have bekymret mig syg ved at\n"
	.string "tænke over, hvordan jeg skal stille mit\l"
	.string "hold af POKéMON op.\p"
	.string "Så, som tingene er, har jeg brug for, at\n"
	.string "du beslutter for mig.\p"
	.string "{PLAYER}{KUN}, hvilken af mine POKéMON\n"
	.string "skal gå først? Så jeg vinder, mener jeg.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, okay. Min {STR_VAR_1} går først.\p"
	.string "Jeg vil rette opstillingen sådan efter\n"
	.string "jeg har spist aftensmad.\p"
	.string "Jeg håber, jeg kan blive ved med at bede\n"
	.string "dig om hjælp som dette.$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Øhm… {PLAYER}{KUN}?\p"
	.string "Vær venlig ikke at se på mig sådan. Du\n"
	.string "gør mig helt forfjamsket.\p"
	.string "Øhm… Jeg har virkelig brug for dit råd.\p"
	.string "Det gør mig genert at sige dette, men\n"
	.string "jeg har valgt mit 3-POKéMON hold. Jeg\l"
	.string "kan dog ikke beslutte rækkefølgen.\p"
	.string "Hvilken POKéMON skal jeg sende ud først\n"
	.string "så jeg i det mindste ser dygtig ud?$"

gText_ApprenticeMonFirstThanks14::
	.string "Åh… Okay! Jeg vil starte med min\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg håber, jeg kan gøre mit bedste uden\n"
	.string "at blive helt forfjamsket.\p"
	.string "Tak, {PLAYER}{KUN}. Hvis vi mødes igen,\n"
	.string "håber jeg, du vil være lige så hjælpsom.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig? Måske er du en klog\l"
	.string "look-alike?\p"
	.string "Åh, nej, nej, nej, bare rolig! Hvis du\n"
	.string "virkelig er {PLAYER}, så glem min\l"
	.string "uhøflighed.\p"
	.string "Hvad jeg gerne vil have, er dit gode råd.\p"
	.string "Jeg har her mit POKéMON hold. Jeg vil\n"
	.string "gerne have, at du fortæller mig, hvilken\l"
	.string "der skal gå først i en kamp.$"

gText_ApprenticeMonFirstThanks15::
	.string "Min {STR_VAR_1}… Du trækker ikke\n"
	.string "benet på mig?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er\n"
	.string "det fint. Jeg takker dig for din tid.\p"
	.string "Jeg er, som du ser, men jeg skal gøre mit\n"
	.string "bedste.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeWhichMon0::
	.string "Snøft… Åh, {PLAYER}!\p"
	.string "Hvilken perfekt timing! Der er noget,\n"
	.string "jeg bare ikke kan beslutte…\p"
	.string "Jeg kan ikke beslutte, hvilken POKéMON\n"
	.string "jeg skal bruge.\p"
	.string "Jeg kan ikke beslutte mellem POKéMON\n"
	.string "{STR_VAR_1} og {STR_VAR_2}…\p"
	.string "{PLAYER}, hvilken tror du vil give selv\n"
	.string "mig en chance for at vinde?$"

gText_ApprenticeMonThanks0::
	.string "Snøft… Jeg… Jeg forstår! Åh! Jeg er så\n"
	.string "ked af det! Du har gjort mig så glad, jeg\l"
	.string "græder…\p"
	.string "Jeg vil gøre mit bedste for at fange en\n"
	.string "{STR_VAR_1}!\p"
	.string "Tusind tak!$"

gText_ApprenticeWhichMon1::
	.string "Yay! Det er {PLAYER}! Yay, du kom på\n"
	.string "det rigtige tidspunkt! Jeg har brug for\l"
	.string "dit råd igen!\p"
	.string "Øhm, jeg er helt forvirret--skal jeg\n"
	.string "bruge min {STR_VAR_1} eller\l"
	.string "{STR_VAR_2}…\p"
	.string "Hvilken tror du, jeg skal opdrage,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Åh, så min {STR_VAR_1} er bedre!\n"
	.string "Okay, jeg gør det!\p"
	.string "Tak for at lære mig det!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, hej! Jeg har et spørgsmål,\n"
	.string "jeg ville stille.\p"
	.string "Jeg er i et dilemma om, hvorvidt jeg skal\n"
	.string "opdrage en {STR_VAR_1} eller\l"
	.string "{STR_VAR_2}.\p"
	.string "Hvilken POKéMON tror du vil være\n"
	.string "stærkere?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} er dit valg? Okay, jeg\n"
	.string "har forstået!\p"
	.string "Jeg vil gå og fange en stærk\n"
	.string "{STR_VAR_1} med det samme!\p"
	.string "Vi ses igen!$"

gText_ApprenticeWhichMon3::
	.string "Hej, {PLAYER}…\p"
	.string "Øhm, du har sikkert allerede glemt en\n"
	.string "som mig…\p"
	.string "…Men det betyder ikke noget, hvis du\n"
	.string "kunne give mig råd…\p"
	.string "Jeg kan ikke beslutte, hvilken type\n"
	.string "POKéMON jeg skal opdrage…\p"
	.string "Jeg har begrænset feltet til POKéMON\n"
	.string "{STR_VAR_1} og {STR_VAR_2}, men\l"
	.string "det er der, hvor jeg blev fastlåst…\p"
	.string "{PLAYER}, du ønsker nok ikke at\n"
	.string "besvære dig, men vær venlig at beslutte\l"
	.string "for mig.$"

gText_ApprenticeMonThanks3::
	.string "Men vil en vild {STR_VAR_1}\n"
	.string "overhovedet lægge mærke til mig?\p"
	.string "Jeg vil prøve!\p"
	.string "Men vil jeg overhovedet kunne fange\n"
	.string "en… Nej! Jeg vil gøre mit bedste!\p"
	.string "Tak!$"

gText_ApprenticeWhichMon4::
	.string "Åh, {PLAYER}{KUN}! Jeg er så glad for at se\n"
	.string "dig! Jeg var lige ved at gå og lede efter\l"
	.string "dig!\p"
	.string "Kan du beslutte, hvilken type POKéMON\n"
	.string "jeg skal bruge?\p"
	.string "For eksempel… Hvad med POKéMON\n"
	.string "{STR_VAR_1} og {STR_VAR_2}?\p"
	.string "Hvilken tror du ville være bedre?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Det er fantastisk!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af\l"
	.string "det, hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeWhichMon5::
	.string "Er det ikke {PLAYER}{KUN}?! Hvordan går\n"
	.string "det? Jeg har travlt igen som altid!\p"
	.string "Jeg vil også gøre det godt med POKéMON,\n"
	.string "men jeg har ikke kunnet beslutte,\l"
	.string "hvilken POKéMON jeg skal bruge.\p"
	.string "Du ved, hvordan {STR_VAR_1} ser\n"
	.string "stærke ud? Men {STR_VAR_2} er svære\l"
	.string "at ignorere.\p"
	.string "{PLAYER}{KUN}, giv mig noget af dit gode\n"
	.string "råd! Hvilken ville være god for mig?$"

gText_ApprenticeMonThanks5::
	.string "Okay, forstået. Jeg vil finde tid på en\n"
	.string "eller anden måde og fange den\l"
	.string "{STR_VAR_1}, du anbefalede.\p"
	.string "Jeg er glad for at have mødt en god\n"
	.string "mentor som dig. Tak! Vi ses!$"

gText_ApprenticeWhichMon6::
	.string "Åh! Yay, det er {PLAYER}!\p"
	.string "Jeg spildte ingen tid med at prale for\n"
	.string "mine venner om at møde dig!\p"
	.string "Jeg har brug for din hjælp igen i dag.\n"
	.string "Det er nemt for dig!\p"
	.string "Trommehvirvel, tak! Mit spørgsmål er…\p"
	.string "Hvis jeg skulle opdrage en POKéMON, og\n"
	.string "valget stod mellem en {STR_VAR_1}\l"
	.string "eller {STR_VAR_2}, hvilken skulle det\l"
	.string "så være?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh! {STR_VAR_1}, siger du! Tak for\n"
	.string "et virkelig sejt svar!\p"
	.string "Jeg tror, det var alt, jeg ville spørge\n"
	.string "dig om i dag.\p"
	.string "Lad os mødes her igen, okay? Tak!$"

gText_ApprenticeWhichMon7::
	.string "Åh, er det dig, {PLAYER}? Jeg er glad\n"
	.string "for at se dig igen!\p"
	.string "Siden jeg blev din lærling, er min\n"
	.string "selvtillid vokset.\p"
	.string "Jeg tror, jeg er klar til at opdrage en\n"
	.string "POKéMON helt selv!\p"
	.string "{PLAYER}, må jeg bede dig om at vælge,\n"
	.string "hvilken POKéMON jeg skal opdrage?\p"
	.string "Valget står mellem POKéMON\n"
	.string "{STR_VAR_1} eller {STR_VAR_2}…\l"
	.string "Hvilken POKéMON er rigtig for mig?$"

gText_ApprenticeMonThanks7::
	.string "En {STR_VAR_1} er det! Jeg vil finde\n"
	.string "en med det samme!\p"
	.string "Tak, {PLAYER}. Jeg håber, jeg kan\n"
	.string "regne med dig igen. Pas godt på dig selv!$"

gText_ApprenticeWhichMon8::
	.string "Eek! {PLAYER}! Jeg mødte dig igen!\n"
	.string "Jeg… jeg er overvældet af glæde!\p"
	.string "Åh-åh-åh, jeg ved det! Jeg bør ikke gå\n"
	.string "glip af denne mulighed!\p"
	.string "Må jeg bede om en stor tjeneste,\n"
	.string "{PLAYER}? Vær venlig at vælge en\l"
	.string "POKéMON for mig!\p"
	.string "Vær venlig at beslutte, hvilken der er\n"
	.string "bedre, {STR_VAR_1} eller\l"
	.string "{STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Wow! Du besluttede for mig! En\n"
	.string "{STR_VAR_1} er, hvad jeg vil opdrage\l"
	.string "til det bedste af min evne.\p"
	.string "Jeg håber, du vil lære mig noget mere en\n"
	.string "anden gang.$"

gText_ApprenticeWhichMon9::
	.string "Hej, hej! Min mentor, {PLAYER}{KUN}!\p"
	.string "Hej, jeg har ledt efter dig for at få\n"
	.string "mere af dit kloge råd!\p"
	.string "Hvilken slags POKéMON ville være god for\n"
	.string "mig, en {STR_VAR_1} eller\l"
	.string "{STR_VAR_2}?\p"
	.string "Vær ikke genert nu. Lad os få det ud!$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, en {STR_VAR_1} er det! OK,\n"
	.string "A-OK! Jeg fanger en i en BALL, som, cram!\p"
	.string "Okay, tak som altid! Adios!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, hør! Store nyheder! Jeg\n"
	.string "fangede en mirage POKéMON!\p"
	.string "Selvfølgelig lyver jeg! Wahahaha!\p"
	.string "Dette er dog ingen løgn. Jeg er ikke\n"
	.string "særlig god til at fange POKéMON.\p"
	.string "Så hvad med at beslutte for mig, hvilken\n"
	.string "slags POKéMON jeg skal fange, mester?\p"
	.string "Hvilken ville være bedre?\n"
	.string "{STR_VAR_1} eller {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Okay, så det er {STR_VAR_1}, du\n"
	.string "valgte? Jeg tager den anden slags så!\p"
	.string "Bare for sjov! Jeg vil følge din lære,\n"
	.string "mester!\p"
	.string "Tak, mester! Jeg håber, du vil fortsætte\n"
	.string "med at lære mig!$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y! Og det staver ahoy!\p"
	.string "Jeg er den rappende SØMAND! Du husker\n"
	.string "vel, hvem jeg er?\p"
	.string "I dag har jeg et POKéMON-spørgsmål, der\n"
	.string "beder om dit forslag!\p"
	.string "Jeg har valget mellem denne\n"
	.string "{STR_VAR_1} og {STR_VAR_2}, ser\l"
	.string "du. Hvilken er den rigtige for mig at\l"
	.string "fange?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, siger du, hey, hey! Jeg\n"
	.string "vil gå og fange en med det samme!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeWhichMon12::
	.string "Åh, wow, hvis det ikke er {PLAYER}!\p"
	.string "Hvad skal jeg gøre? Få dit råd? Hvorfor\n"
	.string "ikke? Jeg taler allerede med dig!\p"
	.string "Det er længe siden. Lad mig bryde isen.\n"
	.string "Jeg leder også efter råd! Modtager du\l"
	.string "mig? Du modtager mig!\p"
	.string "Min POKéMON--hvilken skal jeg bruge?\n"
	.string "Det er enten {STR_VAR_1} eller\l"
	.string "{STR_VAR_2}. Hvilken vælger du?$"

gText_ApprenticeMonThanks12::
	.string "Hvis den {STR_VAR_1} er den bedste,\n"
	.string "vil jeg gøre, som du foreslår!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit, men\n"
	.string "glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeWhichMon13::
	.string "Åh, hej, {PLAYER}{KUN}… Jeg har denne\n"
	.string "frygtelige hovedpine…\p"
	.string "Jeg må have bekymret mig for meget om,\n"
	.string "hvilken slags POKéMON jeg skal opdrage.\p"
	.string "Så, som tingene er, har jeg brug for, at\n"
	.string "du beslutter for mig.\p"
	.string "{PLAYER}{KUN}, hvis jeg skulle vælge mellem\n"
	.string "POKéMON {STR_VAR_1} og\l"
	.string "{STR_VAR_2}, hvilken skulle det\l"
	.string "være?$"

gText_ApprenticeMonThanks13::
	.string "Hm, en {STR_VAR_1}, okay. Jeg vil\n"
	.string "lede efter en, når jeg bliver bedre.\p"
	.string "Jeg håber, jeg kan blive ved med at bede\n"
	.string "dig om hjælp som dette.$"

gText_ApprenticeWhichMon14::
	.string "Er… Øhm… {PLAYER}{KUN}…?\p"
	.string "Vær venlig ikke at se på mig sådan. Jeg\n"
	.string "bliver helt forfjamsket… Jeg… jeg har\l"
	.string "brug for dit råd.\p"
	.string "Jeg… jeg er virkelig flov, men jeg kan\n"
	.string "ikke beslutte, hvilken POKéMON jeg skal\l"
	.string "bruge.\p"
	.string "Hvis valget stod mellem {STR_VAR_1}\n"
	.string "eller {STR_VAR_2}, hvilken ville være\l"
	.string "bedre?$"

gText_ApprenticeMonThanks14::
	.string "Åh… Okay! Jeg vil gøre mit bedste med en\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg håber, jeg kan gøre mit bedste uden\n"
	.string "at blive helt forfjamsket.\p"
	.string "Tak, {PLAYER}{KUN}. Hvis vi mødes igen,\n"
	.string "håber jeg, du vil være lige så hjælpsom.$"

gText_ApprenticeWhichMon15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig rigtig?\p"
	.string "Nej, nej, hvis du er rigtig, er det fint.\n"
	.string "Forresten, jeg vil gerne have dit råd.\p"
	.string "Det handler om den POKéMON, jeg skal\n"
	.string "bruge.\p"
	.string "Hvis valget står mellem POKéMON\n"
	.string "{STR_VAR_1} og {STR_VAR_2},\l"
	.string "hvilken er mere værdig for mig?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}? Er du sikker?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er\n"
	.string "det fint. Jeg takker dig for din tid.\p"
	.string "Jeg håber, det er noget, jeg endda kan\n"
	.string "håndtere med lethed.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Åh, {PLAYER}! Snøft… Hiks…\p"
	.string "Jeg har et dilemma! Jeg kan ikke\n"
	.string "beslutte mig for et move til min\l"
	.string "{STR_VAR_1}…\p"
	.string "Vær venlig, vær venlig, {PLAYER}. Kan\n"
	.string "du beslutte for mig?\p"
	.string "For min {STR_VAR_1}, hvilket move\n"
	.string "ville være det bedste valg:\l"
	.string "{STR_VAR_2} eller {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}? Waaaaah!\p"
	.string "Åh! Jeg er så ked af det, {PLAYER}! Du\n"
	.string "har gjort mig så glad ved at vælge movet,\l"
	.string "jeg græder…\p"
	.string "Snøft… Tusind tak!$"

gText_ApprenticeWhichMove1::
	.string "Yay! Hej, {PLAYER}! Jeg har brug for\n"
	.string "dit råd igen!\p"
	.string "Jeg vil lære min {STR_VAR_1} et sejt\n"
	.string "move.\p"
	.string "Jeg kan godt lide enten {STR_VAR_2}\n"
	.string "eller {STR_VAR_3}. Hvad er din\l"
	.string "anbefaling?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} er bedre? Det tror jeg\n"
	.string "også! Okay, jeg går med det!\p"
	.string "Hvis vi mødes her igen, vil du så lære mig\n"
	.string "noget andet, lærer?$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hej! Det handler om min\n"
	.string "{STR_VAR_1}, men jeg er bekymret\l"
	.string "over dens moves.\p"
	.string "Ser du, det er moves {STR_VAR_2} og\n"
	.string "{STR_VAR_3}.\p"
	.string "Hvilket er stærkere og bedre for min\n"
	.string "{STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} er dit valg? Okay, jeg\n"
	.string "har forstået!\p"
	.string "Jeg vil straks lære {STR_VAR_1} til\n"
	.string "min POKéMON!\p"
	.string "Vi ses igen!$"

gText_ApprenticeWhichMove3::
	.string "Åhhh, {PLAYER}… Jeg er håbløs, nej,\n"
	.string "virkelig!\p"
	.string "Jeg har besluttet mig for at opdrage en\n"
	.string "POKéMON, men nu kan jeg ikke engang\l"
	.string "beslutte, hvilket move jeg skal lade den\l"
	.string "lære…\p"
	.string "Jeg ved, det ikke betyder noget for dig,\n"
	.string "{PLAYER}.\p"
	.string "Men det betyder meget for mig…\p"
	.string "Vær venlig, {PLAYER}, kunne du vælge\n"
	.string "et move til min {STR_VAR_1}?\p"
	.string "Hvis du kunne vælge mellem\n"
	.string "{STR_VAR_2} og {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Jeg forstår!\p"
	.string "Men vil den overhovedet være villig til\n"
	.string "at lære {STR_VAR_1} for mig… Nej! Jeg\l"
	.string "vil gøre mit bedste!\p"
	.string "Tak!$"

gText_ApprenticeWhichMove4::
	.string "Åh, {PLAYER}{KUN}! Jeg håbede lige at se\n"
	.string "dig!\p"
	.string "Jeg spekulerede på, hvilket move der\n"
	.string "ville være passende for min\l"
	.string "{STR_VAR_1}.\p"
	.string "Jeg kan ikke beslutte mig, så kan du\n"
	.string "beslutte for mig i stedet?\p"
	.string "For eksempel… Hvad med moves\n"
	.string "{STR_VAR_2} og {STR_VAR_3}?\l"
	.string "Hvilket ville være bedre?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Det er fantastisk!\p"
	.string "Ved at du har taget beslutningen,\n"
	.string "{PLAYER}{KUN}, vil jeg ikke blive så ked af\l"
	.string "det, hvis jeg taber.\p"
	.string "Okay, jeg vil se til dig for råd igen.\n"
	.string "Farvel!$"

gText_ApprenticeWhichMove5::
	.string "Hvordan kan tingene være så travle?\n"
	.string "Hej, hvis det ikke er {PLAYER}{KUN}!\l"
	.string "Hvordan går det?\p"
	.string "Siden jeg stod op i morges, har jeg\n"
	.string "jogget, svømmet og lavet mad!\p"
	.string "Du vil ikke tro, hvor travlt jeg har det!\p"
	.string "Jeg kan ikke engang beslutte, hvilket\n"
	.string "move min {STR_VAR_1} skal lære!\p"
	.string "{STR_VAR_2} ser godt ud, ikke? Men\n"
	.string "{STR_VAR_3} er også okay.\p"
	.string "{PLAYER}{KUN}, giv mig noget af dit gode\n"
	.string "råd! Hvilket move ville være godt for\l"
	.string "mig?$"

gText_ApprenticeMoveThanks5::
	.string "Okay, forstået. Jeg vil finde tid i min\n"
	.string "tidsplan og lære det move.\p"
	.string "Jeg er glad for at have mødt en god\n"
	.string "mentor som dig. Tak! Vi ses!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Heldigt! Jeg mødte dig igen,\n"
	.string "{PLAYER}! Jeg har brug for din hjælp\l"
	.string "igen i dag.\p"
	.string "Trommehvirvel, tak! Mit spørgsmål er…\p"
	.string "For min {STR_VAR_1}, hvilket move er\n"
	.string "bedst egnet, {STR_VAR_2} eller\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh! {STR_VAR_1}, siger du! Tak for\n"
	.string "et virkelig sejt svar!\p"
	.string "Jeg tror, det var alt, jeg ville spørge\n"
	.string "dig om i dag.\p"
	.string "Lad os mødes her igen, okay? Tak!$"

gText_ApprenticeWhichMove7::
	.string "Åh, hej, {PLAYER}. Jeg håber, du har\n"
	.string "det godt?\p"
	.string "Jeg har brug for dit råd igen. Det\n"
	.string "handler om min kære {STR_VAR_1}.\p"
	.string "Hvilket ville være det ideelle move for\n"
	.string "min elskelige {STR_VAR_1}?\l"
	.string "{STR_VAR_2} eller {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} er det! Jeg vil lære det\n"
	.string "med det samme!\p"
	.string "Tak, {PLAYER}. Jeg håber, jeg kan\n"
	.string "regne med dig igen. Pas godt på dig selv!$"

gText_ApprenticeWhichMove8::
	.string "Eek! {PLAYER}! Jeg mødte dig igen!\n"
	.string "Jeg… jeg er overvældet af glæde!\p"
	.string "Når jeg har brug for hjælp, er du altid\n"
	.string "der for mig, {PLAYER}!\p"
	.string "I dag vil jeg have dig til at anbefale et\n"
	.string "move for mig!\p"
	.string "Vær venlig at vælge et move til min\n"
	.string "{STR_VAR_1}!\p"
	.string "Hvilket move ville være bedre,\n"
	.string "{STR_VAR_2} eller {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Åh-åh-åh! Tak! {STR_VAR_1} er det!\n"
	.string "Perfekt forstået!\p"
	.string "Jeg håber, du vil lære mig noget mere en\n"
	.string "anden gang.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno! Jeg håber på\n"
	.string "noget mere af dit kloge råd i dag!\p"
	.string "Hvad ville være det bedste move for min\n"
	.string "{STR_VAR_1}?\p"
	.string "Det skal være noget, der vil lade mig\n"
	.string "vinde med det samme!\p"
	.string "Ville det være {STR_VAR_2}? Eller\n"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1} er det! Si,\n"
	.string "bueno! Jeg vil lære det, som, ka-blam!\p"
	.string "Okay, tak som altid! Adios!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, det er helt vildt!\p"
	.string "Min POKéMON! Den har lært seks moves!\p"
	.string "Selvfølgelig lyver jeg! Wahahaha!\p"
	.string "Dette er dog ingen løgn. Jeg er ikke\n"
	.string "særlig god til at vælge moves til min\l"
	.string "POKéMON.\p"
	.string "Så hvad med at beslutte for mig, hvilket\n"
	.string "move jeg skal lære?\p"
	.string "{STR_VAR_2} eller\n"
	.string "{STR_VAR_3}--hvilket ville passe\l"
	.string "bedst til min {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "Okay, så det er {STR_VAR_1}, du\n"
	.string "valgte? Jeg vælger et andet move så!\p"
	.string "Bare for sjov! Jeg vil følge din lære,\n"
	.string "mester!\p"
	.string "Tak, mester! Jeg håber, du vil fortsætte\n"
	.string "med at lære mig!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y! Og det staver ahoy!\p"
	.string "Jeg er den rappende SØMAND! Jeg er\n"
	.string "altid med på det, spørg mig ikke hvorfor.\p"
	.string "I dag har jeg et move-spørgsmål, der\n"
	.string "beder om dit forslag!\p"
	.string "{STR_VAR_2} og {STR_VAR_3} er\n"
	.string "moves. Hvilket ville være bedst for min\l"
	.string "{STR_VAR_1}, så den groover?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, siger du, hey, hey! Jeg\n"
	.string "vil lære det med det samme!\p"
	.string "Hvis jeg nogensinde har brug for råd,\n"
	.string "{PLAYER}, vil jeg altid følge dit ord!$"

gText_ApprenticeWhichMove12::
	.string "Åh, jaah, hvis det ikke er {PLAYER}!\p"
	.string "Hvad skal jeg gøre? Få dit råd? Hvorfor\n"
	.string "ikke? Jeg taler allerede med dig!\p"
	.string "{PLAYER}, er du overrasket over mig?\n"
	.string "Jeg vil have dit råd, kan du ikke se det?\p"
	.string "Modtager du mig? Du modtager mig!\p"
	.string "Min {STR_VAR_1}--hvad skal den\n"
	.string "bruge? Det er {STR_VAR_2} eller\l"
	.string "{STR_VAR_3}, hvad vælger du?$"

gText_ApprenticeMoveThanks12::
	.string "Hvis den {STR_VAR_1} er den bedste,\n"
	.string "vil jeg gøre, som du foreslår!\p"
	.string "Nå, {PLAYER}, jeg må vandre frit, men\n"
	.string "glem ikke mig.\p"
	.string "Vi ses igen, min kloge ven!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Åh, {PLAYER}{KUN}… Jeg har\n"
	.string "denne elendige forkølelse, det har jeg…\p"
	.string "Jeg vil vælge et move til min POKéMON,\n"
	.string "men jeg er ikke i stand til det…\p"
	.string "Så, som tingene er, har jeg brug for, at\n"
	.string "du beslutter for mig.\p"
	.string "{PLAYER}{KUN}, hvis jeg skulle vælge mellem\n"
	.string "{STR_VAR_2} og {STR_VAR_3} til\l"
	.string "min {STR_VAR_1}, hvilket skulle det\l"
	.string "være?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, okay. Host! Jeg vil\n"
	.string "lære det, når jeg bliver bedre.\p"
	.string "Jeg håber, jeg kan blive ved med at bede\n"
	.string "dig om hjælp som dette.$"

gText_ApprenticeWhichMove14::
	.string "Er… Øhm… {PLAYER}{KUN}…?\p"
	.string "Vær venlig ikke at se på mig sådan. Jeg\n"
	.string "bliver helt forfjamsket… Jeg… jeg har\l"
	.string "brug for dit råd.\p"
	.string "Jeg… jeg er virkelig flov, men jeg kan\n"
	.string "ikke beslutte, hvilket move jeg skal lære\l"
	.string "min POKéMON.\p"
	.string "Det er for min {STR_VAR_1}. Hvis\n"
	.string "valget stod mellem {STR_VAR_2} eller\l"
	.string "{STR_VAR_3}, hvilket ville være\l"
	.string "bedre?$"

gText_ApprenticeMoveThanks14::
	.string "Åh… Okay! Jeg vil prøve det\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg håber, jeg kan lære det move… Dette\n"
	.string "er så nervepirrende…\p"
	.string "Tak, {PLAYER}{KUN}. Hvis vi mødes igen,\n"
	.string "håber jeg, du vil være lige så hjælpsom.$"

gText_ApprenticeWhichMove15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig rigtig?\p"
	.string "Måske er du en af de populære mimics?\p"
	.string "Nej, nej, hvis du er rigtig, er det fint.\n"
	.string "Ingen grund til at blive ked af det, jeg\l"
	.string "forsikrer dig!\p"
	.string "Forresten, jeg vil gerne have dit råd.\p"
	.string "Det handler om min {STR_VAR_1}.\p"
	.string "Hvilket move ville være bedre for den at\n"
	.string "bruge, {STR_VAR_2} eller\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}? Der er ingen tvivl om\n"
	.string "det?\p"
	.string "Jeg forstår. Hvis det er tilfældet, er\n"
	.string "det fint. Jeg takker dig for din tid.\p"
	.string "Jeg håber, det er noget, som selv min\n"
	.string "POKéMON kan lære.\p"
	.string "Lad os mødes igen!$"

gText_ApprenticePickWinSpeech0::
	.string "Åh… {PLAYER}? Det er {PLAYER}! Åh!\n"
	.string "Snøft… Snuft… Vær venlig at lytte!\p"
	.string "Jeg… Når jeg kæmper, bliver jeg så\n"
	.string "nervøs, at jeg ikke kan lade være med at\l"
	.string "græde, selvom jeg vinder…\p"
	.string "Jeg ville ønske, jeg kunne sige noget\n"
	.string "sejt når jeg vinder…\p"
	.string "Vær venlig, vær venlig, {PLAYER}! Kan du\n"
	.string "måske lære mig noget sejt at sige, når\l"
	.string "jeg vinder, så jeg ikke græder?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Fantastisk! Cool! Awoooh! Det er\n"
	.string "virkelig sejt!\p"
	.string "Åh… Jeg er ked af det… Jeg er så glad,\n"
	.string "at jeg græder…\p"
	.string "Snøft… {PLAYER}! Tak for alt!\p"
	.string "Jeg vil kæmpe mit bedste for din skyld,\n"
	.string "{PLAYER}!\p"
	.string "{PLAYER}… Næste gang… Skal vi kæmpe!$"

gText_ApprenticePickWinSpeech1::
	.string "Yay! Det er {PLAYER}! Hej! Jeg ville\n"
	.string "spørge dig om noget!\p"
	.string "Jeg vil sige noget sejt, når jeg vinder\n"
	.string "en kamp.\p"
	.string "Har du en sej sætning, som du kan\n"
	.string "anbefale?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Åh, wow! Det er så sejt! Okay, det vil jeg\n"
	.string "sige!\p"
	.string "Tak fordi du har lært mig alt dette! Jeg\n"
	.string "vil gøre mit bedste uanset hvor jeg går\l"
	.string "fra nu af!\p"
	.string "Når vi mødes igen, vil det være til en\n"
	.string "kamp!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, hej!\p"
	.string "Mine POKéMON og jeg er klar til alt,\n"
	.string "undtagen én ting.\p"
	.string "Jeg synes, det ville være godt, hvis jeg\n"
	.string "havde noget at råbe, når jeg vinder.\p"
	.string "Kan du finde på noget godt at sige?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Sejt! Det vil jeg bruge!\p"
	.string "Jeg vil ud og kæmpe overalt i verden.\p"
	.string "Hvem ved, måske får jeg endda lov til at\n"
	.string "kæmpe mod dig en dag, {PLAYER}.\p"
	.string "Næste gang, lad os mødes et sted for\n"
	.string "kamp!$"

gText_ApprenticePickWinSpeech3::
	.string "Hej, {PLAYER}… Jeg er ked af at\n"
	.string "forstyrre dig, men jeg er håbløs…\p"
	.string "Selv når… Selv når jeg vinder, har jeg\n"
	.string "ikke noget specielt at sige…\p"
	.string "Jeg ved, det ikke betyder noget for dig,\n"
	.string "{PLAYER}.\p"
	.string "Men det betyder meget for mig…\p"
	.string "Vær venlig, {PLAYER}, hvad skal jeg\n"
	.string "sige hvis jeg vinder en kamp?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Det er inspireret…\p"
	.string "Uh… Er det okay for en som mig at sige\n"
	.string "det?\p"
	.string "Nej! Jeg vil gøre mit bedste!\p"
	.string "{PLAYER}, tusind tak for at holde ud\n"
	.string "med mig så længe…\p"
	.string "Jeg lover at gøre mit bedste fremover.\p"
	.string "Jeg er sikker på, at du hurtigt vil\n"
	.string "glemme en som mig, men lad os mødes igen\l"
	.string "et sted!$"

gText_ApprenticePickWinSpeech4::
	.string "Åh, {PLAYER}{KUN}. Der er noget, jeg vil\n"
	.string "have dig til at høre.\p"
	.string "Jeg ved, at jeg ikke altid lyder venlig\n"
	.string "eller høflig…\p"
	.string "Når jeg vinder en kamp, tror jeg, at jeg\n"
	.string "kommer til at lyde arrogant.\p"
	.string "Jeg vil ikke have folk til at mislike mig,\n"
	.string "så jeg vil sige noget pænt til den jeg\l"
	.string "slår.\p"
	.string "Men jeg kan ikke finde på noget godt!\n"
	.string "Kan du finde på noget for mig?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Ikke dårligt! Ja, det vil jeg bruge!\p"
	.string "Jeg vil tage på vejen og gøre, hvad jeg\n"
	.string "kan med det, du har lært mig, i mit hoved\l"
	.string "og hjerte.\p"
	.string "Jeg er ked af, at jeg har været så\n"
	.string "påtrængende over for dig!\p"
	.string "Næste gang kæmper vi, okay? Vi ses!$"

gText_ApprenticePickWinSpeech5::
	.string "Åh, jeg kan ikke komme over, hvor travlt\n"
	.string "jeg har! Åh, hej, jeg ledte efter dig,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Har du det godt som altid? Tingene har\n"
	.string "ikke ændret sig for mig.\p"
	.string "Jeg skal løbe, kæmpe og kortlægge ting.\n"
	.string "Hvorfor har jeg så travlt?\p"
	.string "Men selvom jeg har travlt, ville det være\n"
	.string "uhøfligt bare at vende om og gå væk fra\l"
	.string "en sejr uden at sige et ord.\p"
	.string "Så hvad ville være en sej sætning til at\n"
	.string "understrege min coolness, når jeg er\l"
	.string "færdig og går væk? {PLAYER}{KUN}, hjælp mig!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Okay, forstået. Jeg kan finde tid til at\n"
	.string "sige det!\p"
	.string "Ærligt talt, jeg er glad for, at jeg\n"
	.string "mødte en god mentor som dig.\p"
	.string "Jeg vil finde tid på en eller anden måde,\n"
	.string "så jeg kan komme i kamp.\p"
	.string "Tak for alt, {PLAYER}{KUN}! Vi skal kæmpe,\n"
	.string "du og jeg, en dag!$"

gText_ApprenticePickWinSpeech6::
	.string "Jeg havde heldet med mig igen!\n"
	.string "{PLAYER}! Jeg er glad for at se dig! Som\l"
	.string "sædvanlig har jeg brug for dit råd!\p"
	.string "Trommehvirvel, tak! Mit sidste\n"
	.string "spørgsmål er…\p"
	.string "Hvis jeg vinder en kamp og vil afslutte\n"
	.string "den med et sejt træk, hvad skal jeg\l"
	.string "sige?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Det… Det er fantastisk! Det er værdigt\n"
	.string "og sejt! Det vil jeg bruge!\p"
	.string "…Hør, jeg tror, jeg bliver bedre til det\n"
	.string "her, huh?\p"
	.string "Så jeg tænker på at udfordre andre\n"
	.string "TRÆNERE fra nu af.\p"
	.string "{PLAYER}, dine råd har virkelig\n"
	.string "hjulpet mig.\p"
	.string "Måske en dag, vil der være en tid, hvor vi\n"
	.string "kæmper!\p"
	.string "Tak for alt!$"

// Danish translation
gText_ApprenticePickWinSpeech7::
	.string "Åh, {PLAYER}.\n"
	.string "Jeg er så glad for at møde dig!\p"
	.string "Jeg har ikke længere nogen bekymringer\n"
	.string "med hensyn til mine POKéMON.\p"
	.string "Det er mig selv, der bekymrer mig…\p"
	.string "Ved du hvordan en TRÆNER siger\n"
	.string "nogle få ting efter at have vundet en kamp?\p"
	.string "Det ville jeg virkelig også ønske, jeg kunne gøre!\n"
	.string "Vær venlig, hvad skal jeg sige, når\n"
	.string "jeg vinder en kamp?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Åh! Den sætning! Den opfrisker mig og\n"
	.string "får mig til at føle mig genfødt!\p"
	.string "Jeg må bruge den med det samme!\p"
	.string "Og nu må jeg tage afsted, {PLAYER}…\p"
	.string "Jeg vil gå ud og kæmpe mod mange andre,\n"
	.string "men jeg vil aldrig glemme dine læreråd.\p"
	.string "Måske en dag… Farvel!$"

gText_ApprenticePickWinSpeech8::
	.string "Eek! Jeg så {PLAYER}! Jeg… Jeg er\n"
	.string "overglad for at se dig!\p"
	.string "Åh-åh-åh! Der er noget, jeg bare må\n"
	.string "spørge dig om!\p"
	.string "For lidt tid siden vandt jeg en kamp.\n"
	.string "Den del var spændende!\p"
	.string "Men det gjorde mig så overglad, at jeg\n"
	.string "blev stum og kunne ikke sige noget!\p"
	.string "Så nu, {PLAYER}, vær venlig, jeg vil\n"
	.string "have dig til at finde en\l"
	.string "afslutningsreplik til mig, når jeg\l"
	.string "vinder!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah! Jeg skal sige det?! Jeg… Jeg\n"
	.string "er overvældet af glæde!\p"
	.string "Th-th-thank you! Jeg har intet tilbage\n"
	.string "at fortryde nu!\p"
	.string "Jeg vil rejse nu og kæmpe mod alle slags\n"
	.string "mennesker.\p"
	.string "Alt dette skylder jeg dig, {PLAYER}.\n"
	.string "Virkelig, virkelig, tak!\p"
	.string "Jeg skal gå nu, men lad os mødes i kamp\n"
	.string "en dag!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno! {PLAYER}{KUN}!\p"
	.string "Du ved, jeg får lyst til at strejfe rundt\n"
	.string "og kæmpe, hvor jeg kan.\p"
	.string "Men før jeg gør det, vil jeg gerne have\n"
	.string "dit råd igen, tak!\p"
	.string "Hvis jeg skulle vinde en kamp, hvad ville\n"
	.string "være en god pral, jeg kunne sige til min\l"
	.string "faldne TRÆNER modstander?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, det er sødt! Si, bueno! Jeg vil\n"
	.string "prøve at sige det, som, ham!\p"
	.string "Og nu er det tid til at sige farvel! Tak\n"
	.string "for alt muligt!\p"
	.string "Giv mig en kamp en dag, okay? Adios!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, der er store problemer!\p"
	.string "Når jeg vinder en kamp, praler jeg om\n"
	.string "det i mindst en time!\p"
	.string "Selvfølgelig lyver jeg! Wahahaha!\p"
	.string "Dette er ingen løgn, dog. Jeg er ikke\n"
	.string "særlig god til at snakke.\p"
	.string "Så, hvordan med at beslutte for mig,\n"
	.string "hvad jeg skal sige efter at have vundet\l"
	.string "en kamp, mester?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Det er det, jeg skal sige, huh? Så vil jeg\n"
	.string "undgå det!\p"
	.string "Bare for sjov! Jeg vil adlyde din\n"
	.string "undervisning, mester!\p"
	.string "Tak fordi du har lært mig alt dette,\n"
	.string "mester!\p"
	.string "Jeg begynder endelig at forstå, hvad\n"
	.string "det vil sige at være en TRÆNER.\p"
	.string "Jeg vil gå ud og vinde kampe mod enhver\n"
	.string "TRÆNER.\p"
	.string "Måske bliver det dig en dag, mester!\p"
	.string "Det var alt! Farvel, min mester!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y! Og det staver ahoy!\p"
	.string "Jeg er den rappende SØMAND! Dette vil\n"
	.string "være mit sidste spørgsmål, græd ikke!\p"
	.string "Det er et spørgsmål om at sige noget\n"
	.string "der kræver dit forslag!\p"
	.string "Hvis jeg vinder en kamp, hvad kan jeg\n"
	.string "sige på en rigtig sej måde?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfekt! Det vil jeg bruge. Jeg havde\n"
	.string "ret i at vælge dig!\p"
	.string "Og nu, synes jeg, det ville være bedst,\n"
	.string "hvis jeg forlod reden!\p"
	.string "Tak for alt, du har lært mig. Jeg vil tage\n"
	.string "på en kamp spree!\p"
	.string "B-O-N-V-O-Y-A-G-E! Og det staver bon\n"
	.string "voyage, til dig er dette min hyldest!$"

gText_ApprenticePickWinSpeech12::
	.string "Åh, yeah, {PLAYER}! Jeg fandt dig igen\n"
	.string "i dag!\p"
	.string "Hvad skal jeg gøre? Spørge dig igen?\n"
	.string "Hvorfor ikke? Jeg spørger dig allerede!\p"
	.string "Alligevel, {PLAYER}… Modtager du mig?\n"
	.string "Du modtager mig! Jeg har brug for mere\l"
	.string "råd!\p"
	.string "Det handler om, hvad jeg skal råbe.\n"
	.string "Noget sejt at råbe, når en kamp ender\l"
	.string "godt.\p"
	.string "Kom nu, jeg vil høre dig sige det!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Okay, okay! Jeg vil bruge det, fordi det\n"
	.string "er så tight!\p"
	.string "Jeg har ikke flere spørgsmål til dig. At\n"
	.string "vinke farvel er alt, der er tilbage at\l"
	.string "gøre.\p"
	.string "Men måske en dag mødes vi, med en\n"
	.string "bestemt til at gå ned i nederlag.\p"
	.string "Men det er virkelig tid til at sige\n"
	.string "farvel.\p"
	.string "Nå, {PLAYER}, jeg skal være fri, men\n"
	.string "glem ikke mig!\p"
	.string "Pas godt på, {PLAYER}! Elsker dig!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, jeg er færdig… Min næse\n"
	.string "stopper ikke med at løbe…\p"
	.string "Jeg prøvede at finde på noget sejt at\n"
	.string "sige, når jeg vinder en kamp.\p"
	.string "Det inspirerede mig så meget, at jeg\n"
	.string "begyndte at græde, og nu stopper min\l"
	.string "næse ikke med at løbe…\p"
	.string "Så, tingene er som de er, jeg har brug\n"
	.string "for, at du beslutter for mig, {PLAYER}{KUN}.\p"
	.string "Når jeg vinder en kamp, hvad skal jeg\n"
	.string "sige?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Det er godt. Nej, det er\n"
	.string "inspirerende! Det bringer friske tårer\l"
	.string "til mine øjne!\p"
	.string "Men på trods af mine tårer og løbende\n"
	.string "næse, vil jeg bruge den sætning!\p"
	.string "Jeg har ikke flere spørgsmål til dig,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Fra nu af er vi rivaler! Tak for alt!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Øhm… {PLAYER}{KUN}…?\p"
	.string "Vær venlig, kig ikke sådan på mig. Du gør\n"
	.string "mig nervøs.\p"
	.string "Jeg… Jeg har brug for dit råd igen. Jeg\n"
	.string "lover, det er sidste gang…\p"
	.string "Det er virkelig pinligt at spørge, men\n"
	.string "hvad nu, hvis jeg vinder en kamp? Hvad\l"
	.string "skal jeg sige?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Åh… Okay! Jeg vil prøve at sige det! Jeg\n"
	.string "er måske for nervøs til at sige det…\p"
	.string "Tak, {PLAYER}{KUN}. Jeg må sige farvel nu.\p"
	.string "Jeg vil adlyde alt, hvad du har lært mig,\n"
	.string "{PLAYER}{KUN}, og gøre mit bedste.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? Du ser ud til at være {PLAYER}{KUN}…\n"
	.string "Men er du virkelig? Måske en smart\l"
	.string "{PLAYER} DUKKE?\p"
	.string "Åh, nej, nej, nej, vær ikke bekymret! Hvis\n"
	.string "du virkelig er ægte, så glem min\l"
	.string "uhøflighed.\p"
	.string "Ingen grund til at være så vred. Alt, jeg\n"
	.string "ønsker, er mere af dit fine råd.\p"
	.string "Det handler om en sætning.\p"
	.string "Mere præcist, hvad skal jeg sige, hvis\n"
	.string "jeg vinder en kamp?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … … Når jeg vinder en kamp…\p"
	.string "{STR_VAR_1}\p"
	.string "…Er du seriøs?\p"
	.string "Jeg ser. Hvis du er seriøs, er det fint.\n"
	.string "Jeg takker dig for din tid.\p"
	.string "Jeg håber, at selv jeg vil være i stand\n"
	.string "til at bruge den sætning godt.\p"
	.string "Jeg synes, jeg er løbet tør for råd jeg\n"
	.string "har brug for.\p"
	.string "Jeg tror, det er på tide at sige farvel\n"
	.string "og stå på egne ben.\p"
	.string "Tak, min mentor! Jeg undskylder for min\n"
	.string "skepsis!$"



