FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Velkommen til BATTLE TENT\n"
	.string "FALLARBOR!\p"
	.string "Jeg er din guide til Set KO Turneringen!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Ønsker du at tage udfordringen\n"
	.string "i en Set KO Turnering?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Vi ser frem til din udfordring\n"
	.string "på et andet tidspunkt!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "I FALLARBOR BATTLE TENT\n"
	.string "afholder vi Set KO Turneringen.\p"
	.string "Alle deltagere går ind med et hold af\n"
	.string "tre POKéMON.\p"
	.string "De tre POKéMON skal opstilles i den\n"
	.string "rækkefølge, de skal optræde i.\p"
	.string "Under kampen vil POKéMON optræde\n"
	.string "én ad gangen i den forudbestemte rækkefølge.\p"
	.string "Når en POKéMON går ind i kampen, skal den\n"
	.string "forblive ude, indtil kampen er afgjort.\p"
	.string "Hvis en kamp ikke er afgjort på\n"
	.string "tre ture, går den til dommeren.\p"
	.string "Hvis du ønsker at afbryde din udfordring,\n"
	.string "skal du gemme spillet.\p"
	.string "Hvis du ikke gemmer, kan du ikke\n"
	.string "fortsætte med din udfordring.\p"
	.string "Hvis du trækker bedriften af at slå\n"
	.string "tre TRÆNERE i træk, vil vi præsentere\l"
	.string "dig for en fin præmie.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Før jeg viser dig til BATTLE\n"
	.string "TENT, skal jeg gemme. Er det okay?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Vi tilbyder to niveauer af udfordringer,\n"
	.string "Niveau 50 og Åbent Niveau.\l"
	.string "Hvilket er dit valg?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Fint, vælg nu venligst dine\n"
	.string "tre POKéMON.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Min kære udfordrer!\p"
	.string "Du har ikke de tre POKéMON,\n"
	.string "der kræves for at deltage.\p"
	.string "De må heller ikke holde de samme\n"
	.string "typer af genstande.\p"
	.string "ÆG er{STR_VAR_1} ugyldige.\p"
	.string "Når du har gjort dine forberedelser,\n"
	.string "venligst kom tilbage.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Min kære udfordrer!\p"
	.string "Du har ikke de tre POKéMON,\n"
	.string "der kræves for at deltage.\p"
	.string "For at kvalificere dig, skal du medbringe tre\n"
	.string "forskellige slags POKéMON.\p"
	.string "De må heller ikke holde de samme\n"
	.string "typer af genstande.\p"
	.string "ÆG er{STR_VAR_1} ugyldige.\p"
	.string "Når du har gjort dine forberedelser,\n"
	.string "venligst kom tilbage.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Jeg vil nu guide dig til\n"
	.string "BATTLE TENT.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Min kære udfordrer!\p"
	.string "Du gemte ikke spillet før du\n"
	.string "lukkede ned, gjorde du?\p"
	.string "Det er desværre sket, men det har\n"
	.string "resulteret i din diskvalifikation\l"
	.string "fra din udfordring.\p"
	.string "Du kan naturligvis starte med en ny\n"
	.string "udfordring.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Hvor fantastisk! Du har slået\n"
	.string "tre TRÆNERE i træk!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Vent venligst, mens jeg gemmer spillet.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Til minde om din 3-sejrs streak,\n"
	.string "præsenterer vi dig for denne præmie.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} modtog præmien\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Åh?\n"
	.string "Din TASKE ser ud til at være fuld.\p"
	.string "Jeg opfordrer dig til at rydde plads og\n"
	.string "komme tilbage for din præmie.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Mange tak for din deltagelse!\p"
	.string "Vent venligst, mens jeg gemmer spillet.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Vi ser frem til din udfordring\n"
	.string "på et andet tidspunkt!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Vi har set frem til din ankomst.\p"
	.string "Før jeg viser dig til BATTLE TENT,\n"
	.string "skal jeg gemme spillet. Vent venligst.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Velkommen til BATTLE TENT\n"
	.string "VERDANTURF!\p"
	.string "Her testes TRAINERENS tillid til\n"
	.string "POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Ønsker du at tage udfordringen i\n"
	.string "VERDANTURF BATTLE TENT?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "I VERDANTURF BATTLE TENT\n"
	.string "er der en vigtig regel, der skal\l"
	.string "overholdes.\p"
	.string "TRAINERE må kun skifte deres\n"
	.string "POKéMON ind og ud.\p"
	.string "TRAINERE er ellers forbudt at\n"
	.string "kommandere deres POKéMON.\p"
	.string "POKéMON skal opføre sig efter deres\n"
	.string "natur og kæmpe på egen hånd.\p"
	.string "Du skal stole på dine POKéMON og\n"
	.string "holde øje med dem.\p"
	.string "Hvis du opnår æren af at slå\n"
	.string "tre TRAINERE i træk, vil vi præsentere\l"
	.string "dig for en præmie.\p"
	.string "Hvis du vil afbryde din udfordring,\n"
	.string "skal du gemme spillet.\p"
	.string "Hvis du ikke gemmer før afbrydelse,\n"
	.string "bliver du diskvalificeret.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Når du har styrket dit hjerte\n"
	.string "og POKéMON, skal du vende tilbage.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Der er to niveauer af sværhedsgrad,\n"
	.string "Niveau 50 og Åbent Niveau.\l"
	.string "Hvilket niveau ønsker du at udfordre?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Suk…\p"
	.string "Du har ikke de tre POKéMON,\n"
	.string "der kræves til udfordringen.\p"
	.string "For at deltage, skal du medbringe tre\n"
	.string "forskellige slags POKéMON.\p"
	.string "De må heller ikke holde de samme\n"
	.string "typer af genstande.\p"
	.string "ÆG er{STR_VAR_1} ugyldige.\p"
	.string "Kom tilbage, når du har gjort\n"
	.string "dine forberedelser.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Suk…\p"
	.string "Du har ikke de tre POKéMON,\n"
	.string "der kræves til udfordringen.\p"
	.string "For at deltage, skal du medbringe tre\n"
	.string "forskellige slags POKéMON.\p"
	.string "De må heller ikke holde de samme\n"
	.string "typer af genstande.\p"
	.string "ÆG er{STR_VAR_1} ugyldige.\p"
	.string "Kom tilbage, når du har gjort\n"
	.string "dine forberedelser.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Godt. Nu skal du vælge dine\n"
	.string "tre POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Jeg skal gemme, før jeg viser dig til\n"
	.string "BATTLE TENT. Er det okay?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Godt.\n"
	.string "Følg mig nu.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Jeg føler mig privilegeret over at have set\n"
	.string "dine POKéMON's bedrifter.\p"
	.string "Resultaterne vil blive registreret.\n"
	.string "Jeg må bede dig vente kort.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "At opnå en 3-sejrs streak…\p"
	.string "Båndene, der binder dit hjerte med\n"
	.string "dine POKéMON, virker faste og sande.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Din bedrift vil blive registreret.\n"
	.string "Jeg må bede dig vente kort.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "For bedriften af din 3-sejrs streak,\n"
	.string "præsenterer vi dig for denne præmie.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Velkommen til BATTLE TENT\n"
	.string "SLATEPORT!\p"
	.string "Jeg er din guide til Battle Swap\n"
	.string "Turneringen.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Vil du tage Battle Swap udfordringen?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Her i SLATEPORT BATTLE TENT\n"
	.string "afholder vi Battle Swap events\l"
	.string "med leje-POKéMON.\p"
	.string "Først vil du få udlånt tre\n"
	.string "POKéMON specielt til denne event.\p"
	.string "Ved hjælp af de udlånte POKéMON\n"
	.string "skal du gennemføre en ENKELTKAMP.\p"
	.string "Hvis du vinder, må du bytte\n"
	.string "en af dine leje-POKéMON.\p"
	.string "Gentag denne cyklus af kampe og\n"
	.string "bytninger--hvis du vinder tre gange i\l"
	.string "træk, vil du få en fin præmie.\p"
	.string "Hvis du vil afbryde din\n"
	.string "udfordring, skal du gemme spillet.\p"
	.string "Hvis du ikke gemmer før afbrydelse,\n"
	.string "bliver du diskvalificeret.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Vi ser frem til dit næste besøg.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Hvilket niveau ønsker du at udfordre?\n"
	.string "Niveau 50 eller Niveau 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Før du begynder din udfordring,\n"
	.string "skal jeg gemme data. Er det okay?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Okay, jeg vil holde dine POKéMON i\n"
	.string "sikkerhed, mens du konkurrerer.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Træd venligst denne vej.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Tak for din deltagelse!\p"
	.string "Jeg vil returnere dine POKéMON i bytte\n"
	.string "for vores leje-POKéMON.\p"
	.string "Jeg skal også gemme dine resultater.\n"
	.string "Vent venligst.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Jeg vil returnere dine POKéMON i bytte\n"
	.string "for vores leje-POKéMON.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Tillykke!\n"
	.string "Du har vundet tre kampe i træk!\p"
	.string "Jeg vil returnere dine POKéMON i bytte\n"
	.string "for vores leje-POKéMON.\p"
	.string "Jeg skal også gemme dine resultater.\n"
	.string "Vent venligst.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Som anerkendelse for din 3-sejrs streak,\n"
	.string "tildeler vi dig denne præmie.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Åh?\n"
	.string "Du ser ud til at have ikke plads til dette.\p"
	.string "Venligst ryd plads i din TASKE og\n"
	.string "lad mig vide.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Vi har ventet på dig!\p"
	.string "Før vi genoptager din udfordring,\n"
	.string "skal jeg gemme spillet.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Jeg er ked af at sige det, men du gemte\n"
	.string "ikke før du stoppede sidste gang.\p"
	.string "Som følge heraf er du blevet diskvalificeret\n"
	.string "fra din udfordring.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Vi returnerer dine personlige POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} modtog præmien\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Battle Swap reglerne er opført.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Hvilken overskrift vil du læse?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "I en Battle Swap event må du kun bruge\n"
	.string "tre POKéMON.\p"
	.string "Uanset om du lejer eller bytter,\n"
	.string "må dit hold ikke have to eller flere\l"
	.string "af de samme POKéMON.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Du må kun bytte POKéMON med\n"
	.string "den TRÆNER, du lige har besejret.\p"
	.string "Du må kun bytte for de POKéMON,\n"
	.string "der blev brugt af den besejrede TRÆNER.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Efter hver kamp du vinder, må du\n"
	.string "bytte for en af dine besejrede\l"
	.string "modstanders POKéMON.\p"
	.string "Du vil ikke kunne bytte POKéMON\n"
	.string "med den tredje TRÆNER i eventen.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Der er to vigtige punkter at være opmærksom\n"
	.string "på ved bytning af POKéMON.\p"
	.string "For det første, når du bytter, kan du ikke\n"
	.string "tjekke statistikkerne for den POKéMON, du\l"
	.string "er ved at modtage.\p"
	.string "For det andet, POKéMON på dit hold\n"
	.string "er opstillet i rækkefølge afhængigt af\l"
	.string "den rækkefølge, de blev udlejet i.\p"
	.string "Denne rækkefølge forbliver uændret\n"
	.string "selv når der foretages bytte.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "POKéMON i SLATEPORT\n"
	.string "BATTLE TENT er alle lejede.\p"
	.string "Alle leje-POKéMON holdes på\n"
	.string "Niveau 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "VERDANTURF BATTLE TENT\n"
	.string "regler er opført.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Hvilken overskrift vil du læse?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Her i VERDANTURF BATTLE TENT\n"
	.string "skal POKéMON tænke og\l"
	.string "kæmpe på egen hånd.\p"
	.string "I modsætning til i naturen opfører POKéMON,\n"
	.string "der lever med mennesker, sig forskelligt\l"
	.string "afhængigt af deres natur.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Afhængigt af sin natur kan en POKéMON\n"
	.string "foretrække at angribe uanset hvad.\p"
	.string "En anden POKéMON kan foretrække at beskytte\n"
	.string "sig selv mod enhver skade.\p"
	.string "En tredje kan nyde at irritere eller\n"
	.string "forvirre sine modstandere.\p"
	.string "Afhængigt af sin natur vil en POKéMON\n"
	.string "have yndlingsbevægelser, den er god til\l"
	.string "at bruge.\p"
	.string "Den kan også ikke lide visse bevægelser,\n"
	.string "den har svært ved at bruge.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Der er offensive bevægelser, der påfører\n"
	.string "direkte skade på fjenden.\p"
	.string "Der er defensive bevægelser, der bruges\n"
	.string "til at forberede sig på fjendens angreb eller\l"
	.string "bruges til at helbrede HP og så videre.\p"
	.string "Der er også andre lidt mærkelige\n"
	.string "bevægelser, der kan svække fjenderne med\l"
	.string "stat problemer inklusive gift og lammelse.\p"
	.string "POKéMON vil overveje at bruge bevægelser\n"
	.string "i disse tre kategorier.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Når en POKéMON ikke kommanderes af sin TRÆNER,\n"
	.string "kan den være ude af stand til effektivt at\l"
	.string "bruge visse bevægelser.\p"
	.string "En POKéMON er ikke god til at bruge nogen\n"
	.string "bevægelse, den ikke kan lide.\p"
	.string "Hvis en POKéMON kun kender bevægelser, der\n"
	.string "ikke matcher dens natur, vil den ofte\l"
	.string "være ude af stand til at leve op til sit potentiale.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Afhængigt af sin natur kan en POKéMON begynde\n"
	.string "at bruge bevægelser, der ikke matcher dens\l"
	.string "natur, når den er i fare.\p"
	.string "Hvis en POKéMON begynder at opføre sig mærkeligt\n"
	.string "i en knibe, hold øje med den nøje.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "I denne BATTLE TENT vil niveauerne for\n"
	.string "dine modstandere blive justeret til at\l"
	.string "matche niveauerne for dine POKéMON.\p"
	.string "Ingen TRÆNER, du står over for, vil dog\n"
	.string "have nogen POKéMON under Niveau 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "VERDANTURF BATTLE TENT\n"
	.string "regler er opført.$"
