BattleDome_Text_Potential1::
	.string "Den bedste kandidat til at blive mester!$"

BattleDome_Text_Potential2::
	.string "Et hold, der helt sikkert når finalen.$"

BattleDome_Text_Potential3::
	.string "Et sandsynligt top-tre hold.$"

BattleDome_Text_Potential4::
	.string "En kandidat til at slutte på førstepladsen.$"

BattleDome_Text_Potential5::
	.string "Et hold med topklasse potentiale.$"

BattleDome_Text_Potential6::
	.string "Outsiderholdet i denne turnering.$"

BattleDome_Text_Potential7::
	.string "Et bedre end gennemsnitligt hold.$"

BattleDome_Text_Potential8::
	.string "Dette turnerings gennemsnitlige hold.$"

BattleDome_Text_Potential9::
	.string "Et hold med gennemsnitligt potentiale.$"

BattleDome_Text_Potential10::
	.string "Et svagere end gennemsnitligt hold.$"

BattleDome_Text_Potential11::
	.string "Et hold, der søger sin første sejr.$"

BattleDome_Text_Potential12::
	.string "En sejr vil gøre dette hold stolt.$"

BattleDome_Text_Potential13::
	.string "Generelt et svagt hold.$"

BattleDome_Text_Potential14::
	.string "Et hold med meget lavt potentiale.$"

BattleDome_Text_Potential15::
	.string "Et hold, der næppe vinder turneringen.$"

BattleDome_Text_Potential16::
	.string "Holdet mest usandsynligt til at vinde.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "Den perfekte, uovervindelige superstjerne!$"

BattleDome_Text_StyleRiskDisaster::
	.string "Villig til at risikere total katastrofe indimellem.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Dygtig til at udholde lange kampe.$"

BattleDome_Text_StyleVariesTactics::
	.string "Varierer taktikker efter modstanderen.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Har et hårdt vindermønster.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Bruger af og til et meget sjældent træk.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Bruger overraskende og forstyrrende træk.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Holder konstant øje med HP i kamp.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "God til at oplagre og frigive kraft.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Dygtig til at svække modstanderne.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Foretrækker taktikker, der afhænger af held.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Angriber med en majestætisk atmosfære.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Angriber med kraftfulde, lav-PP træk.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Dygtig til at svække og derefter angribe.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Kæmper mens de udholder alle angreb.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Dygtig til at forstyrre modstanderne følelsesmæssigt.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Bruger stærke og direkte træk.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Aggressivt bruger stærke træk.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Kæmper mens de snedigt undviger angreb.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Dygtig til at bruge forstyrrende angreb.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Bruger mange populære træk.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Har træk til kraftfulde kombinationer.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Bruger angreb med høj sandsynlighed.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Aggressivt bruger spektakulære træk.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Styrker angreb over forsvar.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Styrker forsvar over angreb.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Angriber hurtigt med stærke træk.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Bruger ofte træk med ekstra effekter.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Bruger en velafbalanceret blanding af træk.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Dette er prøvemeddelse 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Dette er prøvemeddelse 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Dette er prøvemeddelse 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Dette er prøvemeddelse 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Styrker HP og ANGREB.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Styrker HP og FORSVAR.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Styrker HP og FART.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Styrker HP og SP. ANGREB.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Styrker HP og SP. FORSVAR.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Styrker ANGREB og FORSVAR.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Styrker ANGREB og FART.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Styrker ANGREB og SP. ANGREB.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Styrker ANGREB og SP. FORSVAR.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Styrker FORSVAR og FART.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Styrker FORSVAR og SP. ANGREB.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Styrker FORSVAR og SP. FORSVAR.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Styrker FART og SP. ANGREB.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Styrker FART og SP. FORSVAR.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Styrker SP. ANGREB og SP. FORSVAR.$"

BattleDome_Text_EmphasizesHP::
	.string "Styrker HP.$"

BattleDome_Text_EmphasizesAtk::
	.string "Styrker ANGREB.$"

BattleDome_Text_EmphasizesDef::
	.string "Styrker FORSVAR.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Styrker FART.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Styrker SP. ANGREB.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Styrker SP. FORSVAR.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Svækker HP og ANGREB.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Svækker HP og FORSVAR.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Svækker HP og FART.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Svækker HP og SP. ANGREB.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Svækker HP og SP. FORSVAR.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Svækker ANGREB og FORSVAR.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Svækker ANGREB og FART.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Svækker ANGREB og SP. ANGREB.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Svækker ANGREB og SP. FORSVAR.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Svækker FORSVAR og FART.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Svækker FORSVAR og SP. ANGREB.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Svækker FORSVAR og SP. FORSVAR.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Svækker FART og SP. ANGREB.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Svækker FART og SP. FORSVAR.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Svækker SP. ANGREB og SP. FORSVAR.$"

BattleDome_Text_NeglectsHP::
	.string "Svækker HP.$"

BattleDome_Text_NeglectsAtk::
	.string "Svækker ANGREB.$"

BattleDome_Text_NeglectsDef::
	.string "Svækker FORSVAR.$"

BattleDome_Text_NeglectsSpeed::
	.string "Svækker FART.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Svækker SP. ANGREB.$"

BattleDome_Text_NeglectsSpDef::
	.string "Svækker SP. FORSVAR.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Opdrætter POKéMON på en velafbalanceret måde.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Lad kampen begynde!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} vandt ved at bruge {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} blev mesteren!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} vandt uden modstander!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} vandt uden modstander med det samme!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} vandt uden at bruge et træk!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} vandt uden træk med det samme!$"

BattleDome_Text_Round1Match1::
	.string "Runde 1, Kamp 1$"

BattleDome_Text_Round1Match2::
	.string "Runde 1, Kamp 2$"

BattleDome_Text_Round1Match3::
	.string "Runde 1, Kamp 3$"

BattleDome_Text_Round1Match4::
	.string "Runde 1, Kamp 4$"

BattleDome_Text_Round1Match5::
	.string "Runde 1, Kamp 5$"

BattleDome_Text_Round1Match6::
	.string "Runde 1, Kamp 6$"

BattleDome_Text_Round1Match7::
	.string "Runde 1, Kamp 7$"

BattleDome_Text_Round1Match8::
	.string "Runde 1, Kamp 8$"

BattleDome_Text_Round2Match1::
	.string "Runde 2, Kamp 1$"

BattleDome_Text_Round2Match2::
	.string "Runde 2, Kamp 2$"

BattleDome_Text_Round2Match3::
	.string "Runde 2, Kamp 3$"

BattleDome_Text_Round2Match4::
	.string "Runde 2, Kamp 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinale Kamp 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinale Kamp 2$"

BattleDome_Text_FinalMatch::
	.string "Finalekamp$"
