PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "DAD: Hej, {PLAYER}!\p"
	.string "Jeg har lige modtaget et meget sjældent BÆR.\n"
	.string "Jeg vil gerne give det til dig.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Hvis du ser BÆR vokse i løs jord,\n"
	.string "så tag dem endelig.\p"
	.string "Men sørg for at plante et BÆR\n"
	.string "på samme sted. Det er almindelig høflighed.\p"
	.string "Her, jeg vil dele dette med dig.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Ud fra dit udseende må du være en\n"
	.string "TRÆNER, ikke?\p"
	.string "TRÆNERE får ofte POKéMON til at holde\n"
	.string "BÆR.\p"
	.string "Det er op til dig, om du vil dyrke BÆR\n"
	.string "eller bruge dem.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Jeg vandede planterne hver dag.\n"
	.string "De fik mange blomster.\p"
	.string "Og de gav mig også mange BÆR.\p"
	.string "Her, værsgo!\n"
	.string "Du kan få det!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Jeg vil virkelig prøve at lave\n"
	.string "BÆR i forskellige farver.\p"
	.string "Jeg håber, du også prøver hårdt!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Jeg spekulerer på, hvilke farver BÆR\n"
	.string "jeg vil lede efter i dag?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Jeg elsker at bruge BERRY CRUSH maskinen,\n"
	.string "så jeg samler BÆR.\p"
	.string "Jeg deler gerne et med dig, hvis du vil?$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Du burde prøve BERRY CRUSH\n"
	.string "maskinen med dine venner.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Hvilket BÆR skal plantes?\n"
	.string "Skal du bruge eller gemme BÆR?\p"
	.string "Det er sjovt at tænke over.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BÆR vokser ved at suge sollys.\p"
	.string "Vi hjælper BÆR med at vokse ved at vande\n"
	.string "dem regelmæssigt.\p"
	.string "Det er en kærlighedserklæring, er det ikke?$"

Route120_Text_YesYouUnderstand:
	.string "Ja, ja.\n"
	.string "Du forstår, hvad jeg mener.\p"
	.string "Du bør tage denne.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Åh… Men det er vigtigt at danne sine\n"
	.string "egne indtryk, tror jeg…\p"
	.string "Du kan få denne.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Jeg tror, at det BÆR er sjældent.\n"
	.string "Jeg håber, du plejer det med kærlighed.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Jeg får flere BÆR fra\n"
	.string "BÆR-MESTEREN.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Når det kommer til stykket…\p"
	.string "Ligesom jakkesæt passer mig perfekt,\n"
	.string "passer en frisk brise perfekt til havet.\p"
	.string "Og du, et BÆR passer dig til en “T”…\p"
	.string "Hvorfor mon det er sådan?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Når det kommer til stykket…\p"
	.string "Det er fordi, du er en TRÆNER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Når det kommer til stykket…\p"
	.string "Ligesom værdig enkelhed passer mig,\n"
	.string "passer {POKEBLOCK}S perfekt til POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Du kan kalde mig BÆR-MESTEREN.\p"
	.string "Jeg drømmer om at fylde verden med\n"
	.string "smukke blomster, så jeg dyrker BÆR\l"
	.string "og deler dem ud til alle.\p"
	.string "Du fortjener en!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Hvorfor være nærig?\n"
	.string "Tag en til!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Sørg for at besøge PRETTY PETAL\n"
	.string "blomsterbutikken nær RUSTBORO.\p"
	.string "Lad blomster fylde verden!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Jeg er færdig for i dag.\n"
	.string "Kom igen en anden dag.\p"
	.string "Lad blomster fylde verden!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Den måde min mand dyrker BÆR,\n"
	.string "åh, han er den bedste i verden.\p"
	.string "Han gør mig stolt, det gør han.\p"
	.string "Forresten, barn, har du hørt\n"
	.string "et godt ordsprog for nylig?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Hvilket bemærkelsesværdigt ordsprog!\n"
	.string "Inspirerende, det er det!\p"
	.string "Jeg vil have, at du får dette.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Åh! Et godt ordsprog det er.\n"
	.string "Du er ret bemærkelsesværdig.\p"
	.string "Jeg vil have, at du får dette.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Vores fire børnebørn burde blive\n"
	.string "mere dygtige end min mand.\p"
	.string "Glæden går aldrig ud af mit liv!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Hej!\p"
	.string "Dette er PRETTY PETAL blomsterbutikken.\n"
	.string "Spreder blomster over hele verden!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, vil du lære om\n"
	.string "BÆR?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Dit navn er?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Det er et pænt navn.\p"
	.string "{PLAYER}{KUN}, vil du lære om\n"
	.string "BÆR?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BÆR vokser på træer, der kun trives\n"
	.string "i blød, løs jord.\p"
	.string "Hvis du tager nogle BÆR, skal du sørge for\n"
	.string "at plante et i den løse jord igen.\p"
	.string "Et plantet BÆR vil snart spire,\n"
	.string "vokse til en plante, blomstre smukt,\l"
	.string "og derefter vokse BÆR igen.\p"
	.string "Jeg vil se hele den vide verden\n"
	.string "fyldt med smukke blomster.\l"
	.string "Det er min drøm.\p"
	.string "Hjælp mig, {PLAYER}{KUN}. Plant BÆR\n"
	.string "og bring flere blomster til verden.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Blomster bringer så meget glæde til\n"
	.string "folk, ikke?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Hej!\p"
	.string "Jo mere opmærksomhed du giver blomster,\n"
	.string "jo smukkere blomstrer de.\p"
	.string "Du vil kunne lide at pleje blomster. Jeg er sikker\n"
	.string "på det. Du kan få dette.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Mens BÆR planter vokser,\n"
	.string "vand dem med WAILMER PAIL.\p"
	.string "Åh, en anden ting.\p"
	.string "Hvis du ikke plukker BÆR i et stykke tid,\n"
	.string "vil de falde til jorden.\l"
	.string "Men de vil spire igen.\p"
	.string "Er det ikke fantastisk?\n"
	.string "Det er som om, de har viljen til at leve.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Jeg prøver at være som mine store søstre.\n"
	.string "Jeg dyrker også blomster!\p"
	.string "Her, værsgo!\n"
	.string "Det er til dig!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Du kan plante et BÆR og få det til at vokse stort,\n"
	.string "eller du kan få en POKéMON til at holde det.\p"
	.string "Men nu har de en maskine, der blander\n"
	.string "forskellige BÆR og laver slik\l"
	.string "til POKéMON.\p"
	.string "Jeg vil også have noget slik.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hej, hvad er dit navn?\p"
	.string "… … …  … … …  … … …\n"
	.string "Okay. Det er godt!\p"
	.string "Mit navn er KIRI.\p"
	.string "Min mor og far navngav mig det, så\n"
	.string "jeg ville vokse op sund og varm.\l"
	.string "Det var deres ønske.\p"
	.string "Du kan få en af disse.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI vil også give dig dette BÆR!\n"
	.string "Jeg kan virkelig godt lide det!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Jeg spekulerer på, hvilken slags ønske\n"
	.string "der er inkluderet i dit navn.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Forår, sommer, efterår og vinter.\p"
	.string "Hvis du er født om foråret, kan du så lide\n"
	.string "foråret, og hvis du er født om sommeren,\l"
	.string "kan du så lide sommeren?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Så KIRI blev født om efteråret,\n"
	.string "så jeg elsker efteråret!\p"
	.string "Hvilken årstid kan du lide?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Åh…\n"
	.string "Det er lige meget…\p"
	.string "Der er så meget, jeg vil vide…$"
