@ TRANSLATED

PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "DAD: Hej, {PLAYER}!\p"
	.string "Jeg har lige modtaget et meget sjældent\n"
	.string "BÆR. Jeg vil gerne give det til dig.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Hvis du ser BÆR vokse i løs jord, så tag\n"
	.string "dem endelig.\p"
	.string "Men sørg for at plante et BÆR på samme\n"
	.string "sted. Det er almindelig høflighed.\p"
	.string "Her, jeg vil dele dette med dig.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Ud fra dit udseende må du være en\n"
	.string "TRÆNER, ikke?\p"
	.string "TRÆNERE får ofte POKéMON til at holde\n"
	.string "BÆR.\p"
	.string "Det er op til dig, om du vil dyrke BÆR\n"
	.string "eller bruge dem.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Jeg vandede planterne hver dag. De fik\n"
	.string "mange blomster.\p"
	.string "Og de gav mig også mange BÆR.\p"
	.string "Her, værsgo! Du kan få det!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Jeg vil virkelig prøve at lave BÆR i\n"
	.string "forskellige farver.\p"
	.string "Jeg håber, du også prøver hårdt!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Jeg spekulerer på, hvilke farver BÆR jeg\n"
	.string "vil lede efter i dag?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Jeg elsker at bruge BERRY CRUSH\n"
	.string "maskinen, så jeg samler BÆR.\p"
	.string "Jeg deler gerne et med dig, hvis du vil?$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Du burde prøve BERRY CRUSH maskinen\n"
	.string "med dine venner.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Hvilket BÆR skal plantes? Skal du bruge\n"
	.string "eller gemme BÆR?\p"
	.string "Det er sjovt at tænke over.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BÆR vokser ved at suge sollys.\p"
	.string "Vi hjælper BÆR med at vokse ved at\n"
	.string "vande dem regelmæssigt.\p"
	.string "Det er en kærlighedserklæring, er det\n"
	.string "ikke?$"

Route120_Text_YesYouUnderstand:
	.string "Ja, ja. Du forstår, hvad jeg mener.\p"
	.string "Du bør tage denne.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Åh… Men det er vigtigt at danne sine\n"
	.string "egne indtryk, tror jeg…\p"
	.string "Du kan få denne.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Jeg tror, at det BÆR er sjældent. Jeg\n"
	.string "håber, du plejer det med kærlighed.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Jeg får flere BÆR fra BÆR-MESTEREN.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Når det kommer til stykket…\p"
	.string "Ligesom jakkesæt passer mig perfekt,\n"
	.string "passer en frisk brise perfekt til havet.\p"
	.string "Og du, et BÆR passer dig til en “T”…\p"
	.string "Hvorfor mon det er sådan?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Når det kommer til stykket…\p"
	.string "Det er fordi, du er en TRÆNER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Når det kommer til stykket…\p"
	.string "Ligesom værdig enkelhed passer mig,\n"
	.string "passer {POKEBLOCK}S perfekt til POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Du kan kalde mig BÆR-MESTEREN.\p"
	.string "Jeg drømmer om at fylde verden med\n"
	.string "smukke blomster, så jeg dyrker BÆR og\l"
	.string "deler dem ud til alle.\p"
	.string "Du fortjener en!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Hvorfor være nærig? Tag en til!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Sørg for at besøge PRETTY PETAL\n"
	.string "blomsterbutikken nær RUSTBORO.\p"
	.string "Lad blomster fylde verden!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Jeg er færdig for i dag. Kom igen en\n"
	.string "anden dag.\p"
	.string "Lad blomster fylde verden!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Den måde min mand dyrker BÆR, åh, han er\n"
	.string "den bedste i verden.\p"
	.string "Han gør mig stolt, det gør han.\p"
	.string "Forresten, barn, har du hørt et godt\n"
	.string "ordsprog for nylig?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Hvilket bemærkelsesværdigt\n"
	.string "ordsprog! Inspirerende, det er det!\p"
	.string "Jeg vil have, at du får dette.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Åh! Et godt ordsprog det er. Du er ret\n"
	.string "bemærkelsesværdig.\p"
	.string "Jeg vil have, at du får dette.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Vores fire børnebørn burde blive mere\n"
	.string "dygtige end min mand.\p"
	.string "Glæden går aldrig ud af mit liv!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Hej!\p"
	.string "Dette er PRETTY PETAL\n"
	.string "blomsterbutikken. Spreder blomster over\l"
	.string "hele verden!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, vil du lære om BÆR?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Dit navn er?\p"
	.string "{PLAYER}{KUN}. Det er et pænt navn.\p"
	.string "{PLAYER}{KUN}, vil du lære om BÆR?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BÆR vokser på træer, der kun trives i\n"
	.string "blød, løs jord.\p"
	.string "Hvis du tager nogle BÆR, skal du sørge\n"
	.string "for at plante et i den løse jord igen.\p"
	.string "Et plantet BÆR vil snart spire, vokse til\n"
	.string "en plante, blomstre smukt, og derefter\l"
	.string "vokse BÆR igen.\p"
	.string "Jeg vil se hele den vide verden fyldt\n"
	.string "med smukke blomster. Det er min drøm.\p"
	.string "Hjælp mig, {PLAYER}{KUN}. Plant BÆR og bring\n"
	.string "flere blomster til verden.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Blomster bringer så meget glæde til\n"
	.string "folk, ikke?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Hej!\p"
	.string "Jo mere opmærksomhed du giver blomster,\n"
	.string "jo smukkere blomstrer de.\p"
	.string "Du vil kunne lide at pleje blomster. Jeg\n"
	.string "er sikker på det. Du kan få dette.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Mens BÆR planter vokser, vand dem med\n"
	.string "WAILMER PAIL.\p"
	.string "Åh, en anden ting.\p"
	.string "Hvis du ikke plukker BÆR i et stykke tid,\n"
	.string "vil de falde til jorden. Men de vil spire\l"
	.string "igen.\p"
	.string "Er det ikke fantastisk? Det er som om,\n"
	.string "de har viljen til at leve.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Jeg prøver at være som mine store\n"
	.string "søstre. Jeg dyrker også blomster!\p"
	.string "Her, værsgo! Det er til dig!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Du kan plante et BÆR og få det til at\n"
	.string "vokse stort, eller du kan få en POKéMON\l"
	.string "til at holde det.\p"
	.string "Men nu har de en maskine, der blander\n"
	.string "forskellige BÆR og laver slik til\l"
	.string "POKéMON.\p"
	.string "Jeg vil også have noget slik.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hej, hvad er dit navn?\p"
	.string "… … …  … … …  … … … Okay. Det er godt!\p"
	.string "Mit navn er KIRI.\p"
	.string "Min mor og far navngav mig det, så jeg\n"
	.string "ville vokse op sund og varm. Det var\l"
	.string "deres ønske.\p"
	.string "Du kan få en af disse.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI vil også give dig dette BÆR! Jeg\n"
	.string "kan virkelig godt lide det!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Jeg spekulerer på, hvilken slags ønske\n"
	.string "der er inkluderet i dit navn.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Forår, sommer, efterår og vinter.\p"
	.string "Hvis du er født om foråret, kan du så\n"
	.string "lide foråret, og hvis du er født om\l"
	.string "sommeren, kan du så lide sommeren?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Så KIRI blev født om efteråret, så jeg\n"
	.string "elsker efteråret!\p"
	.string "Hvilken årstid kan du lide?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Åh… Det er lige meget…\p"
	.string "Der er så meget, jeg vil vide…$"



