gText_Birch_Welcome::
    .string "Hej! Undskyld, at du måtte vente!\p"
    .string "Velkommen til POKéMON-verdenen!\p"
    .string "Mit navn er BIRCH.\p"
    .string "Men alle kalder mig POKéMON\n"
    .string "PROFESSOREN.\p"
    .string "$"

gText_Birch_Pokemon::
    .string "Dette er, hvad vi kalder en “POKéMON.”\p"
    .string "\n"
    .string "$"

gText_Birch_MainSpeech::
    .string "Denne verden er bredt beboet af\n"
    .string "skabninger kendt som POKéMON.\p"
    .string "Vi mennesker lever sammen med POKéMON,\n"
    .string "nogle gange som venlige legekammerater, og\l"
    .string "andre gange som samarbejdende arbejdskammerater.\p"
    .string "Og nogle gange slår vi os sammen\n"
    .string "og kæmper mod andre som os.\p"
    .string "Men på trods af vores nærhed, ved vi\n"
    .string "ikke alt om POKéMON.\p"
    .string "Faktisk er der mange, mange\n"
    .string "hemmeligheder omkring POKéMON.\p"
    .string "For at opklare POKéMON-mysterier,\n"
    .string "har jeg forsket i det.\l"
    .string "Det er, hvad jeg gør.\p"
    .string "$"

gText_Birch_AndYouAre::
    .string "Og du er?$"

gText_Birch_BoyOrGirl::
    .string "Er du en dreng?\n"
    .string "Eller er du en pige?$"

gText_Birch_WhatsYourName::
    .string "Okay.\n"
    .string "Hvad hedder du?$"

gText_Birch_SoItsPlayer::
    .string "Så det er {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
    .string "Ah, okay!\p"
    .string "Du er {PLAYER}{KUN}, der flytter til min\n"
    .string "hjemby LITTLEROOT.\l"
    .string "Jeg forstår det nu!\p"
    .string "$"

gText_Birch_AreYouReady::
    .string "Okay, er du klar?\p"
    .string "Dit helt eget eventyr er ved\n"
    .string "at begynde.\p"
    .string "Tag mod til dig, og spring ind i\n"
    .string "POKéMON-verdenen, hvor drømme,\l"
    .string "eventyr og venskaber venter!\p"
    .string "Jeg vil forvente dig senere.\n"
    .string "Kom og se mig i mit POKéMON-LAB.\p"
    .string "$"
