@ TRANSLATED

gText_Birch_Welcome::
    .string "Hej! Undskyld ventetiden!\p"
    .string "Velkommen til POKéMON'ernes verden!\p"
    .string "Jeg hedder egentlig BIRCH,\p"
    .string "men alle kalder mig POKéMON\n"
    .string "PROFESSOREN.\p"
    .string "$"

gText_Birch_Pokemon::
    .string "Det her kaldes en “POKéMON.”\p"
    .string "\n"
    .string "$"

gText_Birch_MainSpeech::
    .string "Denne verden er fuld af\n"
    .string "POKéMON-skabninger.\p"
    .string "Vi mennesker lever sammen med POKéMON,\n"
    .string "nogle gange som søde kæledyr, og\l"
    .string "andre gange som gode arbejdskammerater.\p"
    .string "Nogle gange slår vi os sammen\n"
    .string "og kæmper mod andre som os.\p"
    .string "Men selvom vi er tætte, ved vi\n"
    .string "endnu ikke alt om POKéMON.\p"
    .string "Faktisk er der mange, mange\n"
    .string "hemmeligheder omkring POKéMON.\p"
    .string "For at opklare POKéMON-mysterier,\n"
    .string "har jeg forsket i det.\l"
    .string "Det er mit arbejde!\p"
    .string "$"

gText_Birch_AndYouAre::
    .string "Og du er?$"

gText_Birch_BoyOrGirl::
    .string "Er du en dreng?\n"
    .string "Eller er du en pige?$"

gText_Birch_WhatsYourName::
    .string "Okay.\n"
    .string "Hvad hedder du?$"

gText_Birch_SoItsPlayer::
    .string "Så altså {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
    .string "Ah, okay!\p"
    .string "Du er {PLAYER}{KUN}, og du flytter\n"
    .string "til min hjemby LITTLEROOT.\l"
    .string "Nu forstår jeg!\p"
    .string "$"

gText_Birch_AreYouReady::
    .string "Okay, er du klar?\p"
    .string "Dit helt eget eventyr er ved\n"
    .string "at begynde.\p"
    .string "Tag mod til dig, og spring ind i\n"
    .string "POKéMON-verdenen, hvor drømme,\l"
    .string "eventyr og venskaber venter!\p"
    .string "Jeg venter dig senere.\n"
    .string "Kom og besøg mit POKéMON-LAB!\p"
    .string "$"
