BerryBlender_Text_BlendWithTheBlendMaster:
	.string "BLEND MESTER: Ja, det er mig!\n"
	.string "BLEND MESTEREN, det er jeg!\p"
	.string "Blend med mig, og du vil opleve\n"
	.string "mestrens færdigheder i blending!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "BLEND MESTER: Hmmm! Så du ønsker\n"
	.string "at se mine færdigheder i aktion?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm!\p"
	.string "Så du er for travlt nu, kan jeg se!\p"
	.string "Men frygt ej!\n"
	.string "Jeg vil være her hele dagen!\l"
	.string "Skynd dig tilbage fra dit ærinde!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm!\p"
	.string "Du har ikke en eneste BÆR!\p"
	.string "Jeg vil være her hele dagen!\n"
	.string "Skynd dig tilbage med nogle BÆR!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Selvfølgelig!\n"
	.string "Selvfølgelig!\p"
	.string "For øvrigt…\n"
	.string "Du ved, hvordan man blender {POKEBLOCK}S\l"
	.string "fra BÆR, ikke?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm!\p"
	.string "Ah, men det er en simpel proces!\p"
	.string "Når BLENDERENS pil kommer til\n"
	.string "dit mærke, skal du bare trykke på A-knappen.\p"
	.string "Det er alt, hvad du skal gøre.\p"
	.string "Når du ser, hvor præcist jeg trykker\n"
	.string "på A-knappen, vil du forstå.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Fint!\p"
	.string "Lad os komme i gang, så!\p"
	.string "Alle sammen med BLEND MESTEREN,\n"
	.string "lad os BERRY BLENDER!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm!\p"
	.string "Du ser ud til ikke at have fået\n"
	.string "{POKEBLOCK} KASSEN!\p"
	.string "Jeg vil være her hele dagen!\n"
	.string "Få fat i {POKEBLOCK} KASSEN og skynd dig tilbage!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm!\p"
	.string "Din {POKEBLOCK} KASSE ser ud til at være fuld!\p"
	.string "Jeg vil være her hele dagen!\n"
	.string "Brug nogle {POKEBLOCK}S og skynd dig tilbage!$"

BerryBlender_Text_WhoaAwesome:
	.string "Whoa!\n"
	.string "Fantastisk!$"

BerryBlender_Text_WickedlyFast:
	.string "Utrolig hurtig!$"

BerryBlender_Text_WhatAnExpert:
	.string "Sikke en ekspert!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Da jeg blended med MESTEREN,\n"
	.string "lavede vi fantastiske {POKEBLOCK}S!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Øjne, der sporer pilen med\n"
	.string "maskinlignende intensitet…\p"
	.string "En hånd, der trykker på A-knappen\n"
	.string "med urværkslignende præcision…\p"
	.string "At besidde disse kvaliteter gør\n"
	.string "BLEND MESTEREN virkelig stor.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "BLEND MESTEREN siges at arbejde\n"
	.string "på sine færdigheder dybt i bjergene.\p"
	.string "Nogle gange kommer han til LILYCOVE\n"
	.string "for at blende BÆR hele dagen lang.$"
