@ TRANSLATED

BerryBlender_Text_BlendWithTheBlendMaster:
	.string "BLEND MESTER: Ja, det er mig! BLEND\n"
	.string "MESTEREN, det er jeg!\p"
	.string "Blend med mig, og du vil opleve mestrens\n"
	.string "færdigheder i blending!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "BLEND MESTER: Hmmm! Så du ønsker at se\n"
	.string "mine færdigheder i aktion?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm!\p"
	.string "Så du er for travlt nu, kan jeg se!\p"
	.string "Men frygt ej! Jeg vil være her hele\n"
	.string "dagen! Skynd dig tilbage fra dit ærinde!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm!\p"
	.string "Du har ikke en eneste BÆR!\p"
	.string "Jeg vil være her hele dagen! Skynd dig\n"
	.string "tilbage med nogle BÆR!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Selvfølgelig! Selvfølgelig!\p"
	.string "For øvrigt… Du ved, hvordan man blender\n"
	.string "{POKEBLOCK}S fra BÆR, ikke?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm!\p"
	.string "Ah, men det er en simpel proces!\p"
	.string "Når BLENDERENS pil kommer til dit mærke,\n"
	.string "skal du bare trykke på A-knappen.\p"
	.string "Det er alt, hvad du skal gøre.\p"
	.string "Når du ser, hvor præcist jeg trykker på\n"
	.string "A-knappen, vil du forstå.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Fint!\p"
	.string "Lad os komme i gang, så!\p"
	.string "Alle sammen med BLEND MESTEREN, lad os\n"
	.string "BERRY BLENDER!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm!\p"
	.string "Du ser ud til ikke at have fået {POKEBLOCK}\n"
	.string "KASSEN!\p"
	.string "Jeg vil være her hele dagen! Få fat i\n"
	.string "{POKEBLOCK} KASSEN og skynd dig tilbage!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm!\p"
	.string "Din {POKEBLOCK} KASSE ser ud til at være\n"
	.string "fuld!\p"
	.string "Jeg vil være her hele dagen! Brug nogle\n"
	.string "{POKEBLOCK}S og skynd dig tilbage!$"

BerryBlender_Text_WhoaAwesome:
	.string "Whoa! Fantastisk!$"

BerryBlender_Text_WickedlyFast:
	.string "Utrolig hurtig!$"

BerryBlender_Text_WhatAnExpert:
	.string "Sikke en ekspert!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Da jeg blended med MESTEREN, lavede vi\n"
	.string "fantastiske {POKEBLOCK}S!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Øjne, der sporer pilen med\n"
	.string "maskinlignende intensitet…\p"
	.string "En hånd, der trykker på A-knappen med\n"
	.string "urværkslignende præcision…\p"
	.string "At besidde disse kvaliteter gør BLEND\n"
	.string "MESTEREN virkelig stor.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "BLEND MESTEREN siges at arbejde på\n"
	.string "sine færdigheder dybt i bjergene.\p"
	.string "Nogle gange kommer han til LILYCOVE for\n"
	.string "at blende BÆR hele dagen lang.$"



