@ TRANSLATED

CableClub_Text_WelcomeWhichCableClubService::
	.string "Velkommen til POKéMON KABEL\n"
	.string "KLUBBEN.\p"
	.string "Hvilken af vores tjenester ønsker\n"
	.string "du at bruge?$"

CableClub_Text_WhichService::
	.string "Hvilken af vores tjenester ønsker\n"
	.string "du at bruge?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Byt POKéMON med en anden spiller\n"
	.string "ved hjælp af et GBA Game Link kabel.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Du kan kæmpe mod en anden TRÆNER\n"
	.string "ved hjælp af et GBA Game Link kabel.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Du kan bruge RECORD CORNER med\n"
	.string "andre ved hjælp af et GBA Game Link kabel.$"

@ Unused
CableClub_Text_CloseThisMenu::
	.string "Luk denne menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle::
	.string "Til en DOBBELTKAMP skal du have\n"
	.string "mindst to POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade::
	.string "Til bytte skal du have\n"
	.string "mindst to POKéMON med dig.$"

CableClub_Text_CantTradeEnigmaBerry::
	.string "En POKéMON, der holder {STR_VAR_1}\n"
	.string "BERRY, kan ikke byttes.$"

gText_PleaseWaitForLink::
	.string "Vent venligst.\n"
	.string "… … B Knap:: Annuller$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Når alle spillere er klar…\n"
	.string "A Knap:: Bekræft\l"
	.string "B Knap:: Annuller$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Start link med {STR_VAR_1} spillere.\n"
	.string "A Knap:: Bekræft\l"
	.string "B Knap:: Annuller$"

gText_AwaitingLinkup::
	.string "Venter på linkopkobling…\n"
	.string "… … B Knap:: Annuller$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Din fremgang skal gemmes før\n"
	.string "linking. Er det okay at gemme?$"

CableClub_Text_PleaseEnter::
	.string "Venligst indtast.$"

CableClub_Text_DirectYouToYourRoom::
	.string "Jeg vil vise dig til dit rum nu.$"

Text_SomeoneIsNotReadyToLink::
	.string "Nogen er ikke klar til at linke.\p"
	.string "Kom tilbage, når alle har\n"
	.string "gjort sig klar.$"

Text_LinkErrorPleaseReset::
	.string "Beklager, vi har en linkfejl…\n"
	.string "Nulstil og prøv igen.$"

Text_PlayersMadeDifferentSelections::
	.string "Linkpartnere ser ud til at have\n"
	.string "lavet forskellige valg.$"

CableClub_Text_PleaseVisitAgain::
	.string "Besøg os igen.$"

CableClub_Text_IncorrectNumberOfParticipants::
	.string "Antallet af deltagere er\n"
	.string "forkert.$"

CableClub_Text_CantSingleBattleWithXPlayers::
	.string "SINGLE BATTLE Mode kan ikke spilles\n"
	.string "af {STR_VAR_1} spillere.$"

CableClub_Text_CantDoubleBattleWithXPlayers::
	.string "DOUBLE BATTLE Mode kan ikke spilles\n"
	.string "af {STR_VAR_1} spillere.$"

CableClub_Text_NeedFourPlayers::
	.string "Der skal være fire spillere for at spille\n"
	.string "denne kampmode.$"

CableClub_Text_PleaseConfirmNumberAndRestart::
	.string "Bekræft antallet af\n"
	.string "spillere og start igen.$"

Text_TerminateLinkConfirmation::
	.string "Linket afbrydes, hvis du forlader rummet.\n"
	.string "Er det i orden?$"

Text_TerminateLinkPleaseWait::
	.string "Afslutter link…\n"
	.string "Du vil blive eskorteret ud af rummet.\n"
	.string "Vent venligst.$"

CableClub_Text_TooBusyToNotice::
	.string "Denne TRÆNER er for travl til\n"
	.string "at bemærke…$"

CableClub_Text_GotToLookAtTrainerCard::
	.string "Sejt! Jeg fik set {STR_VAR_1}'s\n"
	.string "TRÆNERKORT!$"

CableClub_Text_GotToLookAtColoredTrainerCard::
	.string "Sejt! Jeg fik set {STR_VAR_1}'s\n"
	.string "TRÆNERKORT!\p"
	.string "Det er et {STR_VAR_2} kort!$"

BattleColosseum_2P_Text_TakePlaceStartBattle::
	.string "Tag din plads og start\n"
	.string "din kamp.$"

TradeCenter_Text_TakeSeatStartTrade::
	.string "Tag din plads og start\n"
	.string "din byttehandel.$"

RecordCorner_Text_ThanksForComing::
	.string "Tak fordi du kom.$"

CableClub_Text_TrainerCardDataOverwritten::
	.string "TRÆNERKORT data vil\n"
	.string "blive overskrevet.$"

CableClub_Text_HopeToSeeYouAgain::
	.string "Jeg håber at se dig igen!$"

CableClub_Text_NotSetUpForFarAwayRegion::
	.string "Jeg beklager meget.\p"
	.string "Vi er ikke indstillet til at gennemføre\n"
	.string "handler med TRÆNERE langt væk i en anden region endnu…$"

CableClub_Text_OtherTrainerNotReady::
	.string "Den anden TRÆNER er ikke klar.$"

CableClub_Text_YouHaveAMonThatCantBeTaken::
	.string "Du har mindst én POKéMON\n"
	.string "som ikke kan tages.$"

RecordCorner_Text_TakeSeatAndWait::
	.string "Tag din plads og vent.$"

RecordCorner_Text_PlayerSentOverOneX::
	.string "{STR_VAR_1} sendte en\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame::
	.string "Beklager, der er en transmissionsfejl.\p"
	.string "Du må ikke blande data med  \n"
	.string "japanske Ruby eller Sapphire spil.\p"
	.string "Også, du kan ikke blande data med\n"
	.string "japanske Emerald og udenlandske Ruby\l"
	.string "eller Sapphire spil samtidig.$"

CableClub_Text_AdapterNotConnected::
	.string "Wireless Adapteren er ikke\n"
	.string "tilsluttet korrekt.$"

CableClub_Text_ParticipantsStepUpToCounter::
	.string "Deltagere bedes træde op\n"
	.string "til receptionsdisken.$"

@ Unused
CableClub_Text_Hello::
	.string "Hej!$"

@ Unused
CableClub_Text_PleaseWait::
	.string "Vent venligst.$"

CableClub_Text_YouMayTradeHere::
	.string "Du kan bytte dine POKéMON her\n"
	.string "med en anden TRÆNER.$"

CableClub_Text_YouMayBattleHere::
	.string "Du kan kæmpe med dine venner\n"
	.string "her.$"

CableClub_Text_CanMakeBerryPowder::
	.string "To til fem TRÆNERE kan lave\n"
	.string "BERRY POWDER sammen.$"

CableClub_Text_CanMixRecords::
	.string "Optegnelserne for to til fire spillere\n"
	.string "kan blandes sammen.$"

@ Unused
CableClub_Text_GuideToVariousServices::
	.string "En guide til WIRELESS CLUB's\n"
	.string "forskellige tjenester.$"

CableClub_Text_CancelSelectedItem::
	.string "Annullerer det valgte MENU punkt.$"

@ Unused
CableClub_Text_WhichBattleMode::
	.string "Hvilken kampmode vil du spille?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep::
	.string "Tilbage til forrige trin.$"

CableClub_Text_NeedBerryForBerryCrush::
	.string "For at bruge BERRY CRUSH tjenesten,\n"
	.string "skal du have mindst en BERRY.$"

CableClub_Text_NeedTwoMonsForUnionRoom::
	.string "For at komme ind i UNION RUMMET,\n"
	.string "skal du have mindst to POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom::
	.string "Ingen POKéMON, der holder {STR_VAR_1}\n"
	.string "BERRY, må komme ind i UNION RUMMET.$"

CableClub_Text_UnionRoomAdapterNotConnected::
	.string "Dette er POKéMON WIRELESS CLUB\n"
	.string "UNION RUMMET.\p"
	.string "Desværre er din Wireless Adapter\n"
	.string "ikke tilsluttet korrekt.\p"
	.string "Kom venligst igen.$"

@ Unused
CableClub_Text_OhExcuseMe::
	.string "Åh…\n"
	.string "Undskyld!$"

CableClub_Text_PlayerIsWaiting::
	.string "Det ser ud som om {STR_VAR_1} spiller\n"
	.string "lige nu.\l"
	.string "Giv den gas!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame::
	.string "Jeg kan forklare spillereglerne for dig,\n"
	.string "hvis du vil.\p"
	.string "Hvilket spil skal jeg beskrive?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo::
	.string "“POKéMON JUMP”\p"
	.string "Få din POKéMON til at hoppe over\n"
	.string "VINE WHIP tovet med A Knap.\p"
	.string "Kun mini POKéMON omkring 28 tommer\n"
	.string "eller mindre kan deltage.\p"
	.string "POKéMON der kun svømmer, graver\n"
	.string "eller flyver er ikke gode til at hoppe.\p"
	.string "Som følge heraf kan disse POKéMON\n"
	.string "ikke deltage.\p"
	.string "Gode ting sker, hvis alle\n"
	.string "hopper i takt.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo::
	.string "“DODRIO BERRY-PICKING”\p"
	.string "Kontroller DODRIO's tre hoveder til\n"
	.string "at fange faldende BERRIES.\p"
	.string "Tryk højre, op eller venstre på\n"
	.string "{PLUS} Control Pad for at flytte hovederne.\p"
	.string "For at spille dette spil, skal du have\n"
	.string "en DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay::
	.string "Hvis du vil spille et spil,\n"
	.string "så fortæl det til den gamle mand ved siden af mig.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait::
	.string "Hej, velkommen!\n"
	.string "Er du her for at spille spil ved brug af\n"
	.string "Wireless Communication?\p"
	.string "Kan du vente lidt?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain::
	.string "Okay, kom igen!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected::
	.string "Wireless Adapteren er ikke tilsluttet.\n"
	.string "Kom tilbage, når den er tilsluttet!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame::
	.string "Okay, hvilket spil vil du spille?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon::
	.string "Hvilken POKéMON vil du\n"
	.string "tilmelde?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo::
	.string "Okay, du er klar.\n"
	.string "Lad de andre ikke slå dig!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain::
	.string "Går du nu?\n"
	.string "Kom igen!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon::
	.string "Det ser ikke ud til, at du har nogen\n"
	.string "POKéMON, der kan deltage…\p"
	.string "Vil du have mig til at forklare, hvilke\n"
	.string "slags POKéMON kan deltage?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed::
	.string "“POKéMON JUMP” er åbent for POKéMON\n"
	.string "omkring 28 tommer eller mindre.\p"
	.string "Hvad du ikke kan tilmelde er de\n"
	.string "POKéMON, der ikke kan hoppe.\p"
	.string "Du ved, ligesom POKéMON der kun\n"
	.string "svømmer, graver eller flyver.\p"
	.string "Det er alt, du behøver at vide.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed::
	.string "DODRIO BERRY-PICKING er et spil, som\n"
	.string "kun DODRIO kan deltage i.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease::
	.string "Kan du prøve igen fra starten\n"
	.string "igen, tak?$"

CableClub_Text_WelcomeWhichDirectCornerRoom::
	.string "Velkommen til POKéMON WIRELESS\n"
	.string "CLUB DIRECT CORNER.\p"
	.string "Du kan interagere direkte med\n"
	.string "dine venner her.\p"
	.string "Hvilket rum vil du gå ind i?$"

CableClub_Text_TradePokemon::
	.string "Vil du bytte POKéMON?$"

CableClub_Text_PlayWhichBattleMode::
	.string "Hvilken kampmode vil du spille?$"

CableClub_Text_AccessRecordCorner::
	.string "Vil du få adgang til RECORD CORNER?$"

CableClub_Text_UseBerryCrush::
	.string "Vil du bruge BERRY CRUSH System?$"

CableClub_Text_ExplainBattleModes::
	.string "Der er tre kampmodi.\p"
	.string "SINGLE BATTLE er for to TRÆNERE\n"
	.string "med en eller flere POKéMON hver.\p"
	.string "Hver TRÆNER kan have en POKéMON\n"
	.string "i kamp ad gangen.\p"
	.string "DOUBLE BATTLE er for to TRÆNERE\n"
	.string "med to eller flere POKéMON hver.\p"
	.string "Hver TRÆNER vil sende to POKéMON\n"
	.string "i kamp ad gangen.\p"
	.string "MULTI BATTLE er for fire TRÆNERE\n"
	.string "med en eller flere POKéMON hver.\p"
	.string "Hver TRÆNER kan have en POKéMON\n"
	.string "i kamp ad gangen.$"

CableClub_Text_ChooseGroupLeaderOfTwo::
	.string "Afgør venligst hvem af jer to\n"
	.string "der skal være LEDER.\p"
	.string "Den anden spiller skal derefter vælge\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour::
	.string "Afgør venligst hvem af jer fire\n"
	.string "der skal være GRUPPELEDER.\p"
	.string "De andre spillere skal derefter vælge\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeader::
	.string "Afgør venligst hvem af jer\n"
	.string "der skal være GRUPPELEDER.\p"
	.string "De andre spillere skal derefter vælge\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_WelcomeUnionRoomEnter::
	.string "Velkommen til POKéMON WIRELESS\n"
	.string "CLUB UNION ROOM.\p"
	.string "Du kan interagere direkte med\n"
	.string "andre TRÆNERE her, nogle af dem\n"
	.string "kender du måske ikke engang.\p"
	.string "Vil du gå ind i RUMMET?$"

CableClub_Text_UnionRoomInfo::
	.string "TRÆNERNE i UNION RUMMET\n"
	.string "vil være de spillere omkring dig\n"
	.string "som også har gået ind i RUMMET.\p"
	.string "Du kan lave alle mulige ting her,\n"
	.string "som at udveksle hilsner.\p"
	.string "Du kan tilmelde to POKéMON op til\n"
	.string "Lv. 30 for en en-mod-en kamp.\p"
	.string "Du kan deltage i en chat med\n"
	.string "to til fem personer.\p"
	.string "Eller, du kan registrere en POKéMON\n"
	.string "til bytte.\p"
	.string "Vil du gå ind i RUMMET?$"

CableClub_Text_EnjoyUnionRoom::
	.string "Jeg håber du nyder din tid i\n"
	.string "UNION RUMMET.$"

CableClub_Text_FirstTimeRightThisWay::
	.string "Hej!\n"
	.string "Mit navn er TEALA.\p"
	.string "Det må være din første gang\n"
	.string "heroppe.\p"
	.string "Jeg vil vise dig, hvordan Wireless\n"
	.string "Communication Systemet fungerer.\p"
	.string "Først skal jeg vise dig denne\n"
	.string "etage af vores POKéMON CENTER.\p"
	.string "Denne vej, tak.$"

CableClub_Text_ExplainWirelessClubFirstTime::
	.string "På øverste etage er der to\n"
	.string "rum.\p"
	.string "Først, rummet til venstre.\n"
	.string "Det er UNION RUMMET.\p"
	.string "Du kan linke op med TRÆNERE\n"
	.string "omkring dig, som også er gået ind i UNION RUMMET.\p"
	.string "Med dem kan du gøre ting som\n"
	.string "at chatte, kæmpe og bytte.\p"
	.string "Andet, rummet til højre er\n"
	.string "DIRECT CORNER.\p"
	.string "Du kan bytte eller kæmpe med\n"
	.string "dine venner i dette rum.\p"
	.string "Hvis Wireless Adapteren ikke er\n"
	.string "tilsluttet, kan du stadig linke op\n"
	.string "ved hjælp af et GBA Game Link kabel.\p"
	.string "Hvis det er tilfældet, skal du gå\n"
	.string "til DIRECT CORNER.\p"
	.string "Jeg håber, du nyder Wireless\n"
	.string "Communication Systemet.$"

CableClub_Text_AskAboutLinking::
	.string "Hej, {PLAYER}!\p"
	.string "Det er mig, TEALA, POKéMON\n"
	.string "CENTER 2F attendant.\p"
	.string "Er der noget, du vil spørge\n"
	.string "mig om linking?$"

CableClub_Text_ExplainWirelessClub::
	.string "Lad mig forklare, hvordan POKéMON\n"
	.string "WIRELESS CLUB fungerer.\p"
	.string "På denne øverste etage er der to\n"
	.string "rum.\p"
	.string "Først, rummet til venstre.\n"
	.string "Det er UNION RUMMET.\p"
	.string "Du kan linke op med TRÆNERE\n"
	.string "omkring dig, som også er gået ind i UNION RUMMET.\p"
	.string "Med dem kan du gøre ting som\n"
	.string "at chatte, kæmpe og bytte.\p"
	.string "Andet, rummet til højre er\n"
	.string "DIRECT CORNER.\p"
	.string "Du kan bytte eller kæmpe med\n"
	.string "dine venner i dette rum.\p"
	.string "Nogle gange kan du måske ikke\n"
	.string "finde dine venner i UNION RUMMET\n"
	.string "eller DIRECT CORNER.\p"
	.string "I så fald, venligst flyt tættere på\n"
	.string "dine venner.\p"
	.string "Hvis Wireless Adapteren ikke er\n"
	.string "tilsluttet, kan du stadig linke op\n"
	.string "ved hjælp af et GBA Game Link kabel.\p"
	.string "Hvis det er tilfældet, skal du gå\n"
	.string "til DIRECT CORNER.\p"
	.string "Jeg håber, du nyder Wireless\n"
	.string "Communication Systemet.$"

CableClub_Text_HopeYouEnjoyWirelessSystem::
	.string "Jeg håber, du nyder Wireless\n"
	.string "Communication Systemet.$"
