@ TRANSLATED

CableClub_Text_WelcomeWhichCableClubService::
	.string "Velkommen til POKéMON KABEL KLUBBEN.\p"
	.string "Hvilken af vores tjenester ønsker du at\n"
	.string "bruge?$"

CableClub_Text_WhichService::
	.string "Hvilken af vores tjenester ønsker du at\n"
	.string "bruge?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Byt POKéMON med en anden spiller ved\n"
	.string "hjælp af et GBA Game Link kabel.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Du kan kæmpe mod en anden TRÆNER ved\n"
	.string "hjælp af et GBA Game Link kabel.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Du kan bruge RECORD CORNER med andre\n"
	.string "ved hjælp af et GBA Game Link kabel.$"

@ Unused
CableClub_Text_CloseThisMenu::
	.string "Luk denne menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle::
	.string "Til en DOBBELTKAMP skal du have mindst\n"
	.string "to POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade::
	.string "Til bytte skal du have mindst to\n"
	.string "POKéMON med dig.$"

CableClub_Text_CantTradeEnigmaBerry::
	.string "En POKéMON, der holder {STR_VAR_1}\n"
	.string "BERRY, kan ikke byttes.$"

gText_PleaseWaitForLink::
	.string "Vent venligst. … … B Knap:: Annuller$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Når alle spillere er klar… A Knap::\n"
	.string "Bekræft B Knap:: Annuller$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Start link med {STR_VAR_1} spillere.\n"
	.string "A Knap:: Bekræft B Knap:: Annuller$"

gText_AwaitingLinkup::
	.string "Venter på linkopkobling… … … B Knap::\n"
	.string "Annuller$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Din fremgang skal gemmes før\n"
	.string "linking. Er det okay at gemme?$"

CableClub_Text_PleaseEnter::
	.string "Venligst indtast.$"

CableClub_Text_DirectYouToYourRoom::
	.string "Jeg vil vise dig til dit rum nu.$"

Text_SomeoneIsNotReadyToLink::
	.string "Nogen er ikke klar til at linke.\p"
	.string "Kom tilbage, når alle har gjort sig klar.$"

Text_LinkErrorPleaseReset::
	.string "Beklager, vi har en linkfejl… Nulstil og\n"
	.string "prøv igen.$"

Text_PlayersMadeDifferentSelections::
	.string "Linkpartnere ser ud til at have lavet\n"
	.string "forskellige valg.$"

CableClub_Text_PleaseVisitAgain::
	.string "Besøg os igen.$"

CableClub_Text_IncorrectNumberOfParticipants::
	.string "Antallet af deltagere er forkert.$"

CableClub_Text_CantSingleBattleWithXPlayers::
	.string "SINGLE BATTLE Mode kan ikke spilles af\n"
	.string "{STR_VAR_1} spillere.$"

CableClub_Text_CantDoubleBattleWithXPlayers::
	.string "DOUBLE BATTLE Mode kan ikke spilles af\n"
	.string "{STR_VAR_1} spillere.$"

CableClub_Text_NeedFourPlayers::
	.string "Der skal være fire spillere for at spille\n"
	.string "denne kampmode.$"

CableClub_Text_PleaseConfirmNumberAndRestart::
	.string "Bekræft antallet af spillere og start\n"
	.string "igen.$"

Text_TerminateLinkConfirmation::
	.string "Linket afbrydes, hvis du forlader\n"
	.string "rummet. Er det i orden?$"

Text_TerminateLinkPleaseWait::
	.string "Afslutter link… Du vil blive eskorteret\n"
	.string "ud af rummet. Vent venligst.$"

CableClub_Text_TooBusyToNotice::
	.string "Denne TRÆNER er for travl til at\n"
	.string "bemærke…$"

CableClub_Text_GotToLookAtTrainerCard::
	.string "Sejt! Jeg fik set {STR_VAR_1}'s\n"
	.string "TRÆNERKORT!$"

CableClub_Text_GotToLookAtColoredTrainerCard::
	.string "Sejt! Jeg fik set {STR_VAR_1}'s\n"
	.string "TRÆNERKORT!\p"
	.string "Det er et {STR_VAR_2} kort!$"

BattleColosseum_2P_Text_TakePlaceStartBattle::
	.string "Tag din plads og start din kamp.$"

TradeCenter_Text_TakeSeatStartTrade::
	.string "Tag din plads og start din byttehandel.$"

RecordCorner_Text_ThanksForComing::
	.string "Tak fordi du kom.$"

CableClub_Text_TrainerCardDataOverwritten::
	.string "TRÆNERKORT data vil blive overskrevet.$"

CableClub_Text_HopeToSeeYouAgain::
	.string "Jeg håber at se dig igen!$"

CableClub_Text_NotSetUpForFarAwayRegion::
	.string "Jeg beklager meget.\p"
	.string "Vi er ikke indstillet til at gennemføre\n"
	.string "handler med TRÆNERE langt væk i en\l"
	.string "anden region endnu…$"

CableClub_Text_OtherTrainerNotReady::
	.string "Den anden TRÆNER er ikke klar.$"

CableClub_Text_YouHaveAMonThatCantBeTaken::
	.string "Du har mindst én POKéMON som ikke kan\n"
	.string "tages.$"

RecordCorner_Text_TakeSeatAndWait::
	.string "Tag din plads og vent.$"

RecordCorner_Text_PlayerSentOverOneX::
	.string "{STR_VAR_1} sendte en\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame::
	.string "Beklager, der er en transmissionsfejl.\p"
	.string "Du må ikke blande data med   japanske\n"
	.string "Ruby eller Sapphire spil.\p"
	.string "Også, du kan ikke blande data med\n"
	.string "japanske Emerald og udenlandske Ruby\l"
	.string "eller Sapphire spil samtidig.$"

CableClub_Text_AdapterNotConnected::
	.string "Wireless Adapteren er ikke tilsluttet\n"
	.string "korrekt.$"

CableClub_Text_ParticipantsStepUpToCounter::
	.string "Deltagere bedes træde op til\n"
	.string "receptionsdisken.$"

@ Unused
CableClub_Text_Hello::
	.string "Hej!$"

@ Unused
CableClub_Text_PleaseWait::
	.string "Vent venligst.$"

CableClub_Text_YouMayTradeHere::
	.string "Du kan bytte dine POKéMON her med en\n"
	.string "anden TRÆNER.$"

CableClub_Text_YouMayBattleHere::
	.string "Du kan kæmpe med dine venner her.$"

CableClub_Text_CanMakeBerryPowder::
	.string "To til fem TRÆNERE kan lave BERRY\n"
	.string "POWDER sammen.$"

CableClub_Text_CanMixRecords::
	.string "Optegnelserne for to til fire spillere\n"
	.string "kan blandes sammen.$"

@ Unused
CableClub_Text_GuideToVariousServices::
	.string "En guide til WIRELESS CLUB's\n"
	.string "forskellige tjenester.$"

CableClub_Text_CancelSelectedItem::
	.string "Annullerer det valgte MENU punkt.$"

@ Unused
CableClub_Text_WhichBattleMode::
	.string "Hvilken kampmode vil du spille?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep::
	.string "Tilbage til forrige trin.$"

CableClub_Text_NeedBerryForBerryCrush::
	.string "For at bruge BERRY CRUSH tjenesten,\n"
	.string "skal du have mindst en BERRY.$"

CableClub_Text_NeedTwoMonsForUnionRoom::
	.string "For at komme ind i UNION RUMMET, skal du\n"
	.string "have mindst to POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom::
	.string "Ingen POKéMON, der holder\n"
	.string "{STR_VAR_1} BERRY, må komme ind i\l"
	.string "UNION RUMMET.$"

CableClub_Text_UnionRoomAdapterNotConnected::
	.string "Dette er POKéMON WIRELESS CLUB UNION\n"
	.string "RUMMET.\p"
	.string "Desværre er din Wireless Adapter ikke\n"
	.string "tilsluttet korrekt.\p"
	.string "Kom venligst igen.$"

@ Unused
CableClub_Text_OhExcuseMe::
	.string "Åh…\n"
	.string "Undskyld!$"

CableClub_Text_PlayerIsWaiting::
	.string "Det ser ud som om {STR_VAR_1}\n"
	.string "spiller lige nu. Giv den gas!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame::
	.string "Jeg kan forklare spillereglerne for dig,\n"
	.string "hvis du vil.\p"
	.string "Hvilket spil skal jeg beskrive?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo::
	.string "“POKéMON JUMP”\p"
	.string "Få din POKéMON til at hoppe over VINE\n"
	.string "WHIP tovet med A Knap.\p"
	.string "Kun mini POKéMON omkring 28 tommer\n"
	.string "eller mindre kan deltage.\p"
	.string "POKéMON der kun svømmer, graver eller\n"
	.string "flyver er ikke gode til at hoppe.\p"
	.string "Som følge heraf kan disse POKéMON ikke\n"
	.string "deltage.\p"
	.string "Gode ting sker, hvis alle hopper i takt.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo::
	.string "“DODRIO BERRY-PICKING”\p"
	.string "Kontroller DODRIO's tre hoveder til at\n"
	.string "fange faldende BERRIES.\p"
	.string "Tryk højre, op eller venstre på {PLUS}\n"
	.string "Control Pad for at flytte hovederne.\p"
	.string "For at spille dette spil, skal du have en\n"
	.string "DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay::
	.string "Hvis du vil spille et spil, så fortæl det\n"
	.string "til den gamle mand ved siden af mig.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait::
	.string "Hej, velkommen! Er du her for at spille\n"
	.string "spil ved brug af Wireless Communication?\p"
	.string "Kan du vente lidt?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain::
	.string "Okay, kom igen!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected::
	.string "Wireless Adapteren er ikke tilsluttet.\n"
	.string "Kom tilbage, når den er tilsluttet!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame::
	.string "Okay, hvilket spil vil du spille?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon::
	.string "Hvilken POKéMON vil du tilmelde?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo::
	.string "Okay, du er klar. Lad de andre ikke slå\n"
	.string "dig!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain::
	.string "Går du nu?\n"
	.string "Kom igen!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon::
	.string "Det ser ikke ud til, at du har nogen\n"
	.string "POKéMON, der kan deltage…\p"
	.string "Vil du have mig til at forklare, hvilke\n"
	.string "slags POKéMON kan deltage?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed::
	.string "“POKéMON JUMP” er åbent for POKéMON\n"
	.string "omkring 28 tommer eller mindre.\p"
	.string "Hvad du ikke kan tilmelde er de POKéMON,\n"
	.string "der ikke kan hoppe.\p"
	.string "Du ved, ligesom POKéMON der kun\n"
	.string "svømmer, graver eller flyver.\p"
	.string "Det er alt, du behøver at vide.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed::
	.string "DODRIO BERRY-PICKING er et spil, som\n"
	.string "kun DODRIO kan deltage i.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease::
	.string "Kan du prøve igen fra starten\n"
	.string "igen, tak?$"

CableClub_Text_WelcomeWhichDirectCornerRoom::
	.string "Velkommen til POKéMON WIRELESS CLUB\n"
	.string "DIRECT CORNER.\p"
	.string "Du kan interagere direkte med dine\n"
	.string "venner her.\p"
	.string "Hvilket rum vil du gå ind i?$"

CableClub_Text_TradePokemon::
	.string "Vil du bytte POKéMON?$"

CableClub_Text_PlayWhichBattleMode::
	.string "Hvilken kampmode vil du spille?$"

CableClub_Text_AccessRecordCorner::
	.string "Vil du få adgang til RECORD CORNER?$"

CableClub_Text_UseBerryCrush::
	.string "Vil du bruge BERRY CRUSH System?$"

CableClub_Text_ExplainBattleModes::
	.string "Der er tre kampmodi.\p"
	.string "SINGLE BATTLE er for to TRÆNERE med en\n"
	.string "eller flere POKéMON hver.\p"
	.string "Hver TRÆNER kan have en POKéMON i kamp\n"
	.string "ad gangen.\p"
	.string "DOUBLE BATTLE er for to TRÆNERE med to\n"
	.string "eller flere POKéMON hver.\p"
	.string "Hver TRÆNER vil sende to POKéMON i kamp\n"
	.string "ad gangen.\p"
	.string "MULTI BATTLE er for fire TRÆNERE med en\n"
	.string "eller flere POKéMON hver.\p"
	.string "Hver TRÆNER kan have en POKéMON i kamp\n"
	.string "ad gangen.$"

CableClub_Text_ChooseGroupLeaderOfTwo::
	.string "Afgør venligst hvem af jer to der skal\n"
	.string "være LEDER.\p"
	.string "Den anden spiller skal derefter vælge\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour::
	.string "Afgør venligst hvem af jer fire der skal\n"
	.string "være GRUPPELEDER.\p"
	.string "De andre spillere skal derefter vælge\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeader::
	.string "Afgør venligst hvem af jer der skal være\n"
	.string "GRUPPELEDER.\p"
	.string "De andre spillere skal derefter vælge\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_WelcomeUnionRoomEnter::
	.string "Velkommen til POKéMON WIRELESS CLUB\n"
	.string "UNION ROOM.\p"
	.string "Du kan interagere direkte med andre\n"
	.string "TRÆNERE her, nogle af dem kender du\l"
	.string "måske ikke engang.\p"
	.string "Vil du gå ind i RUMMET?$"

CableClub_Text_UnionRoomInfo::
	.string "TRÆNERNE i UNION RUMMET vil være de\n"
	.string "spillere omkring dig som også har gået\l"
	.string "ind i RUMMET.\p"
	.string "Du kan lave alle mulige ting her, som at\n"
	.string "udveksle hilsner.\p"
	.string "Du kan tilmelde to POKéMON op til Lv. 30\n"
	.string "for en en-mod-en kamp.\p"
	.string "Du kan deltage i en chat med to til fem\n"
	.string "personer.\p"
	.string "Eller, du kan registrere en POKéMON til\n"
	.string "bytte.\p"
	.string "Vil du gå ind i RUMMET?$"

CableClub_Text_EnjoyUnionRoom::
	.string "Jeg håber du nyder din tid i UNION\n"
	.string "RUMMET.$"

CableClub_Text_FirstTimeRightThisWay::
	.string "Hej! Mit navn er TEALA.\p"
	.string "Det må være din første gang heroppe.\p"
	.string "Jeg vil vise dig, hvordan Wireless\n"
	.string "Communication Systemet fungerer.\p"
	.string "Først skal jeg vise dig denne etage af\n"
	.string "vores POKéMON CENTER.\p"
	.string "Denne vej, tak.$"

CableClub_Text_ExplainWirelessClubFirstTime::
	.string "På øverste etage er der to rum.\p"
	.string "Først, rummet til venstre. Det er UNION\n"
	.string "RUMMET.\p"
	.string "Du kan linke op med TRÆNERE omkring dig,\n"
	.string "som også er gået ind i UNION RUMMET.\p"
	.string "Med dem kan du gøre ting som at chatte,\n"
	.string "kæmpe og bytte.\p"
	.string "Andet, rummet til højre er DIRECT\n"
	.string "CORNER.\p"
	.string "Du kan bytte eller kæmpe med dine\n"
	.string "venner i dette rum.\p"
	.string "Hvis Wireless Adapteren ikke er\n"
	.string "tilsluttet, kan du stadig linke op ved\l"
	.string "hjælp af et GBA Game Link kabel.\p"
	.string "Hvis det er tilfældet, skal du gå til\n"
	.string "DIRECT CORNER.\p"
	.string "Jeg håber, du nyder Wireless\n"
	.string "Communication Systemet.$"

CableClub_Text_AskAboutLinking::
	.string "Hej, {PLAYER}!\p"
	.string "Det er mig, TEALA, POKéMON CENTER 2F\n"
	.string "attendant.\p"
	.string "Er der noget, du vil spørge mig om\n"
	.string "linking?$"

CableClub_Text_ExplainWirelessClub::
	.string "Lad mig forklare, hvordan POKéMON\n"
	.string "WIRELESS CLUB fungerer.\p"
	.string "På denne øverste etage er der to rum.\p"
	.string "Først, rummet til venstre. Det er UNION\n"
	.string "RUMMET.\p"
	.string "Du kan linke op med TRÆNERE omkring dig,\n"
	.string "som også er gået ind i UNION RUMMET.\p"
	.string "Med dem kan du gøre ting som at chatte,\n"
	.string "kæmpe og bytte.\p"
	.string "Andet, rummet til højre er DIRECT\n"
	.string "CORNER.\p"
	.string "Du kan bytte eller kæmpe med dine\n"
	.string "venner i dette rum.\p"
	.string "Nogle gange kan du måske ikke finde\n"
	.string "dine venner i UNION RUMMET eller DIRECT\l"
	.string "CORNER.\p"
	.string "I så fald, venligst flyt tættere på dine\n"
	.string "venner.\p"
	.string "Hvis Wireless Adapteren ikke er\n"
	.string "tilsluttet, kan du stadig linke op ved\l"
	.string "hjælp af et GBA Game Link kabel.\p"
	.string "Hvis det er tilfældet, skal du gå til\n"
	.string "DIRECT CORNER.\p"
	.string "Jeg håber, du nyder Wireless\n"
	.string "Communication Systemet.$"

CableClub_Text_HopeYouEnjoyWirelessSystem::
	.string "Jeg håber, du nyder Wireless\n"
	.string "Communication Systemet.$"



