@ TRANSLATED

Text_PictureBookShelf:
	.string "Der er en samling af\n"
	.string "POKéMON-billedbøger.$"

Text_BookShelf:
	.string "Den er fyldt med alle slags bøger.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magasiner! POKéMON-vennen…\p"
	.string "POKéMON-håndbogen De sejeste\n"
	.string "POKéMON'er…$"

Text_Vase:
	.string "Denne vase ser dyr ud… Kiggede indeni…\p"
	.string "Men den var tom.$"

Text_EmptyTrashCan:
	.string "Den er tom.$"

Text_ShopShelf:
	.string "Hylderne er fyldt med alle slags\n"
	.string "POKéMON merchandise.$"

Text_Blueprint:
	.string "En slags plantegning? Det er for\n"
	.string "kompliceret!$"



