@ TRANSLATED

Text_PictureBookShelf:
	.string "Der er en samling af POKéMON-billedbøger.$"

Text_BookShelf:
	.string "Den er fyldt med alle slags bøger.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magasiner!\n"
	.string "POKéMON-vennen…\p"
	.string "POKéMON-håndbogen\n"
	.string "De sejeste POKéMON'er…$"

Text_Vase:
	.string "Denne vase ser dyr ud…\n"
	.string "Kiggede indeni…\p"
	.string "Men den var tom.$"

Text_EmptyTrashCan:
	.string "Den er tom.$"

Text_ShopShelf:
	.string "Hylderne er fyldt med alle slags\n"
	.string "POKéMON merchandise.$"

Text_Blueprint:
	.string "En slags plantegning?\n"
	.string "Det er for kompliceret!$"
