@ TRANSLATED

gContestHallPaintingCaption::
	.string "{STR_VAR_1} {STR_VAR_2}'s\n"
	.string "{STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "KONKURRENCE$"

gContestRankNormal::
	.string "NORMAL RANG$"

gContestRankSuper::
	.string "SUPER RANG$"

gContestRankHyper::
	.string "HYPER RANG$"

gContestRankMaster::
	.string "MESTER RANG$"

gContestLink::
	.string "LINK$"

gContestCoolness::
	.string "KØLIGHED$"

gContestBeauty::
	.string "SKØNHED$"

gContestCuteness::
	.string "SØDHED$"

gContestSmartness::
	.string "KLOKHED$"

gContestToughness::
	.string "SEJHED$"

gContestPaintingCool1::
	.string "Nonstop supercool-- den uovertrufne\n"
	.string "{STR_VAR_1}$"

gContestPaintingCool2::
	.string "Hey, der! Den flotte POKéMON\n"
	.string "{STR_VAR_1}$"

gContestPaintingCool3::
	.string "Den fantastiske, vidunderlige og meget\n"
	.string "store {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "Dette århundredes sidste Venus-- den\n"
	.string "smukke {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "{STR_VAR_1}'s strålende, glitrende\n"
	.string "smil$"

gContestPaintingBeauty3::
	.string "POKéMON CENTER's super idol-- den\n"
	.string "uforlignelige {STR_VAR_1}$"

gContestPaintingCute1::
	.string "Den dejlige og søde {STR_VAR_1}$"

gContestPaintingCute2::
	.string "Den yndige {STR_VAR_1}'s vindende\n"
	.string "portræt$"

gContestPaintingCute3::
	.string "Giv os et blink! Den søde POKéMON\n"
	.string "{STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Klokhedens mester-- den vise POKéMON\n"
	.string "{STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--den ene udvalgte over\n"
	.string "alle POKéMON$"

gContestPaintingSmart3::
	.string "Den fremragende {STR_VAR_1}'s\n"
	.string "øjeblik af elegance$"

gContestPaintingTough1::
	.string "Den kraftfulde muskuløse hurtigløber\n"
	.string "{STR_VAR_1}$"

gContestPaintingTough2::
	.string "Den stærke, stærkere og stærkeste\n"
	.string "{STR_VAR_1}$"

gContestPaintingTough3::
	.string "Den mægtige seje hyper POKéMON\n"
	.string "{STR_VAR_1}$"



