gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_2}'s {STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "KONKURRENCE$"

gContestRankNormal::
	.string "NORMAL RANG$"

gContestRankSuper::
	.string "SUPER RANG$"

gContestRankHyper::
	.string "HYPER RANG$"

gContestRankMaster::
	.string "MESTER RANG$"

gContestLink::
	.string "LINK$"

gContestCoolness::
	.string "KØLIGHED$"

gContestBeauty::
	.string "SKØNHED$"

gContestCuteness::
	.string "SØDHED$"

gContestSmartness::
	.string "KLOKHED$"

gContestToughness::
	.string "SEJHED$"

gContestPaintingCool1::
	.string "Nonstop supercool--\n"
	.string "den uovertrufne {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Hey, der!\n"
	.string "Den flotte POKéMON {STR_VAR_1}$"

gContestPaintingCool3::
	.string "Den fantastiske, vidunderlige og\n"
	.string "meget store {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "Dette århundredes sidste Venus--\n"
	.string "den smukke {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "{STR_VAR_1}'s strålende,\n"
	.string "glitrende smil$"

gContestPaintingBeauty3::
	.string "POKéMON CENTER's super idol--\n"
	.string "den uforlignelige {STR_VAR_1}$"

gContestPaintingCute1::
	.string "Den dejlige og søde {STR_VAR_1}$"

gContestPaintingCute2::
	.string "Den yndige {STR_VAR_1}'s\n"
	.string "vindende portræt$"

gContestPaintingCute3::
	.string "Giv os et blink!\n"
	.string "Den søde POKéMON {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Klokhedens mester--\n"
	.string "den vise POKéMON {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--den ene udvalgte\n"
	.string "over alle POKéMON$"

gContestPaintingSmart3::
	.string "Den fremragende {STR_VAR_1}'s\n"
	.string "øjeblik af elegance$"

gContestPaintingTough1::
	.string "Den kraftfulde muskuløse\n"
	.string "hurtigløber {STR_VAR_1}$"

gContestPaintingTough2::
	.string "Den stærke, stærkere og\n"
	.string "stærkeste {STR_VAR_1}$"

gContestPaintingTough3::
	.string "Den mægtige seje\n"
	.string "hyper POKéMON {STR_VAR_1}$"
