@ TRANSLATED

gText_HighlyAppealingMove::
	.string "En meget tiltalende handling.$"

gText_UserMoreEasilyStartled::
	.string "Efter denne handling bliver brugeren\n"
	.string "lettere forskrækket.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Gør en stor appel, men\n"
	.string "kan ikke lave flere til slutningen.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Kan bruges gentagne gange\n"
	.string "uden at kede dommeren.$"

gText_AvoidStartledByOthersOnce::
	.string "Kan undgå at blive forskrækket\n"
	.string "af andre én gang.$"

gText_AvoidStartledByOthers::
	.string "Kan undgå at blive forskrækket\n"
	.string "af andre.$"

gText_AvoidStartledByOthersLittle::
	.string "Kan undgå at blive forskrækket\n"
	.string "af andre en smule.$"

gText_UserLessLikelyStartled::
	.string "Efter denne handling bliver brugeren\n"
	.string "mindre tilbøjelig til at blive forskrækket.$"

gText_SlightlyStartleFrontMon::
	.string "Forskrækker let\n"
	.string "POKéMON i fronten.$"

gText_SlightlyStartleAppealed::
	.string "Forskrækker let dem,\n"
	.string "der har lavet appel.$"

gText_StartleAppealedBeforeUser::
	.string "Forskrækker POKéMON, der\n"
	.string "appellerede før brugeren.$"

gText_StartleAllAppealed::
	.string "Forskrækker alle POKéMON, der\n"
	.string "har lavet appel.$"

gText_BadlyStartleFrontMon::
	.string "Forskrækker kraftigt\n"
	.string "POKéMON i fronten.$"

gText_BadlyStartleAppealed::
	.string "Forskrækker kraftigt dem, der\n"
	.string "har lavet appel.$"

gText_StartleAppealedBeforeUser2::
	.string "Forskrækker POKéMON, der\n"
	.string "appellerede før brugeren.$"

gText_StartleAllAppealed2::
	.string "Forskrækker alle POKéMON, der\n"
	.string "har lavet appel.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Flytter dommerens\n"
	.string "opmærksomhed fra andre.$"

gText_StartleMonHasJudgesAttention::
	.string "Forskrækker POKéMON, der\n"
	.string "har dommerens opmærksomhed.$"

gText_JamOthersMissesTurn::
	.string "Forstyrrer andre, og mister\n"
	.string "en tur af appeller.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Forskrækker POKéMON, der\n"
	.string "lavede en samme-type appel.$"

gText_BadlyStartleCoolAppeals::
	.string "Forskrækker kraftigt POKéMON,\n"
	.string "der lavede KØLIGHED appeller.$"

gText_BadlyStartleBeautyAppeals::
	.string "Forskrækker kraftigt POKéMON,\n"
	.string "der lavede SKØNHED appeller.$"

gText_BadlyStartleCuteAppeals::
	.string "Forskrækker kraftigt POKéMON,\n"
	.string "der lavede SØDHED appeller.$"

gText_BadlyStartleSmartAppeals::
	.string "Forskrækker kraftigt POKéMON,\n"
	.string "der lavede KLOKHED appeller.$"

gText_BadlyStartleToughAppeals::
	.string "Forskrækker kraftigt POKéMON,\n"
	.string "der lavede SEJHED appeller.$"

gText_MakeMonAfterUserNervous::
	.string "Gør en POKéMON efter\n"
	.string "brugeren nervøs.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Gør alle POKéMON efter\n"
	.string "brugeren nervøse.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Forværrer tilstanden for\n"
	.string "dem, der har lavet appel.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Forskrækker kraftigt POKéMON i\n"
	.string "god tilstand.$"

gText_AppealGreatIfPerformedFirst::
	.string "Appellen fungerer godt, hvis\n"
	.string "den udføres først.$"

gText_AppealGreatIfPerformedLast::
	.string "Appellen fungerer godt, hvis\n"
	.string "den udføres sidst.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Gør appellen lige så god\n"
	.string "som dem før den.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Gør appellen lige så god\n"
	.string "som den før den.$"

gText_AppealBetterLaterItsPerformed::
	.string "Appellen fungerer bedre,\n"
	.string "jo senere den udføres.$"

gText_AppealVariesDependingOnTiming::
	.string "Appellens kvalitet varierer\n"
	.string "afhængigt af dens timing.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Fungerer godt, hvis det er samme\n"
	.string "type som den før.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Fungerer godt, hvis det er en\n"
	.string "anden type end den før.$"

gText_AffectedByAppealInFront::
	.string "Påvirkes af, hvor godt\n"
	.string "appellen foran går.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Forbedrer brugerens tilstand.\n"
	.string "Hjælper med at forhindre nervøsitet.$"

gText_AppealWorksWellIfConditionGood::
	.string "Appellen fungerer godt, hvis\n"
	.string "brugerens tilstand er god.$"

gText_NextAppealMadeEarlier::
	.string "Den næste appel kan\n"
	.string "laves tidligere næste tur.$"

gText_NextAppealMadeLater::
	.string "Den næste appel kan\n"
	.string "laves senere næste tur.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Gør næste turs rækkefølge\n"
	.string "nemmere at blande.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Blander rækkefølgen af\n"
	.string "appeller i næste tur.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "En appel, der begejstrer\n"
	.string "publikum i enhver konkurrence.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Forskrækker kraftigt alle POKéMON,\n"
	.string "der lavede gode appeller.$"

gText_AppealBestMoreCrowdExcited::
	.string "Appellen fungerer bedst,\n"
	.string "jo mere publikum er begejstret.$"

gText_TemporarilyStopCrowdExcited::
	.string "Stopper midlertidigt\n"
	.string "publikum fra at blive begejstret.$"

@ Unused move names

gText_RainDance::
	.string "REGNDANS$"

gText_Rage::
	.string "RASN$"

gText_FocusEnergy::
	.string "FOKUS ENERGI$"

gText_Hypnosis::
	.string "HYPNOSE$"

gText_Softboiled::
	.string "BLØDKOGT$"

gText_HornAttack::
	.string "HORNANGREB$"

gText_SwordsDance::
	.string "Sværddans$"

gText_Conversion::
	.string "KONVERTERING$"

gText_SunnyDay::
	.string "SOLRIG DAG$"

gText_Rest2::
	.string "HVILE$"

gText_Vicegrip::
	.string "NÆBETAG$"

gText_DefenseCurl::
	.string "FORSVAR KRØL$"

gText_LockOn::
	.string "LÅS PÅ$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "KØLIGHED$"

gContestMoveTypeBeautyText::
	.string "SKØNHED$"

gContestMoveTypeCuteText::
	.string "SØDHED$"

gContestMoveTypeSmartText::
	.string "KLOGHED$"

gContestMoveTypeToughText::
	.string "SEJHED$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Appel nr. {STR_VAR_1}!\n"
	.string "Hvilken handling vil blive brugt?$"

gText_AppealNumButItCantParticipate::
	.string "Appel nr. {STR_VAR_1}!\n"
	.string "Men den kan ikke deltage!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} appellerede med\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} kiggede på\n"
	.string "de andre.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "Vi er løbet tør for\n"
	.string "appeltid!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Men appellen blev\n"
	.string "forstyrret.$"

gText_FollowedAnotherMonsLead::
	.string "Den fulgte en anden\n"
	.string "POKéMON's føring.$"

gText_ButItMessedUp::
	.string "Men det gik galt.$"

gText_WentBetterThanUsual::
	.string "Det gik bedre end\n"
	.string "sædvanligt.$"

gText_JudgeLookedAwayForSomeReason::
	.string "Dommeren kiggede væk\n"
	.string "af en eller anden grund.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "Den arbejdede hårdt for at bygge\n"
	.string "på tidligere fejl.$"

gText_CantMakeAnyMoreMoves::
	.string "Den kan ikke lave flere\n"
	.string "handlinger.$"

gText_WorkedFrighteninglyWell::
	.string "Det fungerede skræmmende\n"
	.string "godt.$"

gText_WorkedHardAsStandoutMon::
	.string "Den arbejdede så hårdt som den\n"
	.string "fremstående POKéMON.$"

gText_JudgedLookedOnExpectantly::
	.string "Dommeren kiggede på\n"
	.string "med forventning.$"

gText_WorkedRatherWell::
	.string "Det fungerede ret godt.$"

gText_WorkedLittleBetterThanUsual::
	.string "Det fungerede lidt bedre\n"
	.string "end sædvanligt.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} skilte sig ikke\n"
	.string "ud overhovedet…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} skilte sig ikke\n"
	.string "meget ud…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} fangede\n"
	.string "en smule opmærksomhed.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} tiltrak en\n"
	.string "masse opmærksomhed.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} kommanderede\n"
	.string "total opmærksomhed.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} har ikke lavet\n"
	.string "sin appel.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Forventningen steg til\n"
	.string "{STR_VAR_1}'s appel næste.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "Dommerens syn på\n"
	.string "{STR_VAR_1} holdt fast.$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "ændrede opfattelser.$"

gText_MonsAppealEffectWoreOff::
	.string "{STR_VAR_1}'s appel\n"
	.string "effekt gik væk.$"

gText_SpecialAppealsEffectWoreOff::
	.string "Den specielle appels\n"
	.string "effekt gik væk.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Alles appeller blev\n"
	.string "gjort ens.$"

gText_CheapenedMonsAppeal::
	.string "Det forringede\n"
	.string "{STR_VAR_2}'s appel.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Det forringede appellen\n"
	.string "af dem foran.$"

gText_StoleAttentionAwayFromMon::
	.string "Det stjal opmærksomheden\n"
	.string "fra {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "Det forringede\n"
	.string "{STR_VAR_2}'s appel.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "Det forringede alvorligt\n"
	.string "andre appeller.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Forventningen steg til\n"
	.string "{STR_VAR_1}'s appel næste.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Det forringede appellen\n"
	.string "af dem foran.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "Det forringede dommerens\n"
	.string "yndlingsappel.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "De andres appeller\n"
	.string "blev halveret.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Det skilte sig ud for at kompensere\n"
	.string "for at blive forstyrret.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Det kan ikke deltage i\n"
	.string "appeller længere.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "Det rørte dommeren for\n"
	.string "en fantastisk appel.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Forventningen steg til\n"
	.string "kommende appeller.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Det skilte sig ud lige så meget som\n"
	.string "specielle appeller.$"

gText_StoodOutAsMuchAsMon::
	.string "Det skilte sig ud lige så meget som\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Forstyrrede appeller blev gjort\n"
	.string "endnu mindre synlige.$"

gText_EveryonesAppealsMadeSame::
	.string "Alles appeller blev\n"
	.string "gjort ens.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Det blev mere bevidst\n"
	.string "om de andre POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} kan ikke lave\n"
	.string "en appel efter dette.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Det faldt lidt til ro.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Det blev ligeglad med\n"
	.string "de andre POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Det blev mindre opmærksom\n"
	.string "på de andre POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Det holdt op med at bekymre sig\n"
	.string "om de andre POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Det forsøgte at forskrække\n"
	.string "de andre POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Det forsøgte at blænde\n"
	.string "de andre.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "Dommeren kiggede væk\n"
	.string "fra {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Det forsøgte at gøre\n"
	.string "den næste POKéMON nervøs.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} blev\n"
	.string "nervøs.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Appellen forsøgte at\n"
	.string "gøre ventende POKéMON nervøse.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Det hånede POKéMON,\n"
	.string "der klarede sig godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} genvandt\n"
	.string "sin form.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Det forsøgte at forstyrre POKéMON,\n"
	.string "der klarede sig godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "Den fremstående {STR_VAR_1}\n"
	.string "arbejdede endnu hårdere.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Den stort set ubemærkede\n"
	.string "{STR_VAR_1} arbejdede hårdt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Den arbejdede lige så meget\n"
	.string "som POKéMON før den.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{STR_VAR_1}'s appel gik\n"
	.string "ikke godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Den arbejdede lige så meget\n"
	.string "som den forrige POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{STR_VAR_1}'s appel gik\n"
	.string "ikke godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{STR_VAR_1}'s appel gik\n"
	.string "ikke godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{STR_VAR_1}'s appel\n"
	.string "gik en smule godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{STR_VAR_1}'s appel\n"
	.string "gik ret godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1}'s appel\n"
	.string "gik fremragende.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{STR_VAR_1}'s appel var\n"
	.string "en fiasko.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{STR_VAR_1}'s appel\n"
	.string "virkede ikke særlig godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{STR_VAR_1}'s appel\n"
	.string "gik en smule godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{STR_VAR_1}'s appel\n"
	.string "gik ret godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{STR_VAR_1}'s appel\n"
	.string "gik meget godt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1}'s appel\n"
	.string "gik fremragende.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Det er samme type som\n"
	.string "den før--godt!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Det er ikke samme type som\n"
	.string "den før--godt!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Det skilte sig meget mere ud\n"
	.string "end POKéMON før den.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Det gik ikke lige så godt som\n"
	.string "POKéMON før den.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1}'s tilstand\n"
	.string "steg over det sædvanlige.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{STR_VAR_1}'s varme status\n"
	.string "gjorde det til en stor appel!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Den rykkede op i rækken for\n"
	.string "den næste appel.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Den rykkede tilbage i rækken én gang\n"
	.string "for den næste appel.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Den blandede rækkefølgen for\n"
	.string "næste tur.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "Dommeren kiggede på\n"
	.string "{STR_VAR_1} forventningsfuldt.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "Appel-kombinationen gik\n"
	.string "godt.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "Appel-kombinationen gik\n"
	.string "meget godt.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "Appel-kombinationen gik\n"
	.string "fremragende.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} formåede at\n"
	.string "undgå blikket.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} formåede at\n"
	.string "undgå at se det.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} er ikke påvirket\n"
	.string "af den slags ting.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} blev en\n"
	.string "smule distraheret.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Det forsøgte at forskrække\n"
	.string "de andre POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} kiggede ned\n"
	.string "ud af distraktion.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} vendte sig om\n"
	.string "ud af distraktion.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} kunne ikke lade være\n"
	.string "med at udstøde et skrig.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} kunne ikke lade være\n"
	.string "med at springe op.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} snublede\n"
	.string "ud af distraktion.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} var for\n"
	.string "nervøs til at bevæge sig.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Men det gik galt.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Men det mislykkedes at\n"
	.string "gøre målet nervøs.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Men det mislykkedes at\n"
	.string "gøre nogen nervøs.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Men det blev ignoreret…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Men det kunne ikke forbedre\n"
	.string "sin tilstand…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Den dårlige tilstand\n"
	.string "resulterede i en svag appel.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} blev\n"
	.string "upåvirket.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} skuffede\n"
	.string "ved at gentage en appel.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "gik godt.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "gik ikke godt her…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "fik publikum til at gå amok.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} kan ikke lave\n"
	.string "en appel næste tur…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Det tiltrak publikums\n"
	.string "opmærksomhed.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "Publikum fortsætter med at\n"
	.string "kigge på {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}'s\n"
	.string "{STR_VAR_2} ignoreres.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "skyhed$"

gText_Contest_Anxiety::
	.string "ængstelse$"

gText_Contest_Laziness::
	.string "dovenskab$"

gText_Contest_Hesitancy::
	.string "tøven$"

gText_Contest_Fear::
	.string "frygt$"

gText_Contest_Coolness::
	.string "kølighed$"

gText_Contest_Beauty::
	.string "skønhed$"

gText_Contest_Cuteness::
	.string "sødhed$"

gText_Contest_Smartness::
	.string "kloghed$"

gText_Contest_Toughness::
	.string "sejhed$"

@ Unused
gText_Tension::
	.string "SPÆNDING$"

gText_CoolMove::
	.string "KØLIG Handling$"

gText_BeautyMove::
	.string "SKØN Handling$"

gText_CuteMove::
	.string "SØD Handling$"

gText_SmartMove::
	.string "KLOG Handling$"

gText_ToughMove::
	.string "SEJ Handling$"

gText_3QuestionMarks::
	.string "???$"
