@ TRANSLATED

EventTicket_Text_OldSeaMapTooFar:
	.string "Hva' så, unge?\p"
	.string "Hva', er det dig, der har et gammelt,\n"
	.string "laset kort?\p"
	.string "Lad os se. … … … … … …\p"
	.string "Manner, det er langt væk. Jeg er bange\n"
	.string "for, at jeg ikke kan hjælpe dig…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Vent lige et øjeblik!\p"
	.string "Hva' med at afvise nogen, som jeg\n"
	.string "skylder så meget?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, jeg er meget ked af det.\p"
	.string "Du kom til mig for at få hjælp, og vi var\n"
	.string "ved at afvise dig.\p"
	.string "Lad mig gøre det godt igen.\p"
	.string "Vi sejler straks, selvfølgelig!\p"
	.string "Lad os finde denne ø på dette GAMLE\n"
	.string "SØKORT!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Er det dig, der har det mærkelige billet?\p"
	.string "Hvor du prøver at komme hen er en ø\n"
	.string "langt, langt væk.\p"
	.string "Ingen ved, hvad der venter der…\p"
	.string "Tanken alene ophidser mit blod som\n"
	.string "sømand!\p"
	.string "Kom ombord, unge!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "KAPT. BRINEY kan være så irriterende\n"
	.string "omskiftelig…\p"
	.string "Vil du tilbage til LILYCOVE?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Sikke en mærkelig formet ø, hva? Vil du\n"
	.string "tilbage til LILYCOVE?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Er det dig, der har de mærkelige\n"
	.string "billetter?\p"
	.string "… … …Hm.\p"
	.string "Disse billetter vil bringe dig til øer\n"
	.string "langt, langt væk.\p"
	.string "Ingen ved, hvad der venter der, eller\n"
	.string "hvad der kan ske der.\p"
	.string "Tanken alene ophidser mit blod som\n"
	.string "sømand!\p"
	.string "Kom ombord, unge! Hvor skal vi sejle\n"
	.string "først?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Hørte du det? Den lave knurren derinde\n"
	.string "fra.\p"
	.string "Er du sikker på, det er sikkert? Synes\n"
	.string "du, vi skal tage af sted?$"

FarawayIsland_Entrance_Text_Sign:
	.string "Skriften falmer som om den var skrevet\n"
	.string "for længe siden…\p"
	.string "“…ber, 6. dag Hvis noget\n"
	.string "menneske…sætter fod her… igen…lad det\l"
	.string "være en venlig sjæl… …med dette håb,\l"
	.string "tager jeg afst…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"



