@ TRANSLATED

EventTicket_Text_OldSeaMapTooFar:
	.string "Hva' så, unge?\p"
	.string "Hva', er det dig, der har\n"
	.string "et gammelt, laset kort?\p"
	.string "Lad os se.\n"
	.string "… … … … … …\p"
	.string "Manner, det er langt væk.\n"
	.string "Jeg er bange for, at jeg ikke kan hjælpe dig…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Vent lige et øjeblik!\p"
	.string "Hva' med at afvise\n"
	.string "nogen, som jeg skylder så meget?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, jeg er meget ked af det.\p"
	.string "Du kom til mig for at få hjælp,\n"
	.string "og vi var ved at afvise dig.\p"
	.string "Lad mig gøre det godt igen.\p"
	.string "Vi sejler straks, selvfølgelig!\p"
	.string "Lad os finde denne ø på\n"
	.string "dette GAMLE SØKORT!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Er det dig, der har det mærkelige\n"
	.string "billet?\p"
	.string "Hvor du prøver at komme hen er en ø\n"
	.string "langt, langt væk.\p"
	.string "Ingen ved, hvad der venter der…\p"
	.string "Tanken alene ophidser mit blod\n"
	.string "som sømand!\p"
	.string "Kom ombord, unge!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "KAPT. BRINEY kan være så\n"
	.string "irriterende omskiftelig…\p"
	.string "Vil du tilbage til LILYCOVE?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Sikke en mærkelig formet ø, hva?\n"
	.string "Vil du tilbage til LILYCOVE?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Er det dig, der har de\n"
	.string "mærkelige billetter?\p"
	.string "… … …Hm.\p"
	.string "Disse billetter vil bringe dig til øer\n"
	.string "langt, langt væk.\p"
	.string "Ingen ved, hvad der venter der,\n"
	.string "eller hvad der kan ske der.\p"
	.string "Tanken alene ophidser mit blod\n"
	.string "som sømand!\p"
	.string "Kom ombord, unge!\n"
	.string "Hvor skal vi sejle først?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Hørte du det?\n"
	.string "Den lave knurren derinde fra.\p"
	.string "Er du sikker på, det er sikkert?\n"
	.string "Synes du, vi skal tage af sted?$"

FarawayIsland_Entrance_Text_Sign:
	.string "Skriften falmer som om den var\n"
	.string "skrevet for længe siden…\p"
	.string "“…ber, 6. dag\n"
	.string "Hvis noget menneske…sætter fod her…\l"
	.string "igen…lad det være en venlig sjæl…\l"
	.string "…med dette håb, tager jeg afst…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
