EventTicket_Text_ShowOldSeaMap:
	.string "Færgen til SLATEPORT er…\p"
	.string "Undskyld mig?\n"
	.string "Kan vi sejle til dette sted på kortet?\p"
	.string "Jeg kender nogen, der vil kunne hjælpe dig bedre.\n"
	.string "Vent venligst.$"

EventTicket_Text_ThatPass:
	.string "Færgen til SLATEPORT er…\p"
	.string "Åh?\n"
	.string "Det PASS…$"

EventTicket_Text_ShowEonTicket:
	.string "Hej, makker, er du den, der bragte\n"
	.string "det mærkelige PASS?\p"
	.string "Jeg skal sige dig, du prøver at nå\n"
	.string "en lille ø langt mod syd.\p"
	.string "Der er ingen garanti for, hvad vi møder\n"
	.string "når vi når dertil, åh.\l"
	.string "Det giver mig kuldegysninger!\p"
	.string "Alle ombord!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Hej, makker, der er intet her at\n"
	.string "se eller gøre på denne kedelige ø.\p"
	.string "Hvad siger du til, at vi sejler tilbage til LILYCOVE?$"

EventTicket_Text_SailHome:
	.string "Aye, lige præcis!\n"
	.string "Vi sejler hjem!$"

EventTicket_Text_AsYouLike:
	.string "Aye, lige præcis, som du ønsker.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Alle drømme er blot en anden virkelighed.\n"
	.string "Glem det aldrig…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“De, hvis minder falmer, søger at\n"
	.string "indgravere dem i deres hjerter…”$"
