@ TRANSLATED

@ Battle Tower
gText_AnabelWonSilver::
	.string "Det er meget skuffende…$"

gText_AnabelDefeatSilver::
	.string "Okay, jeg forstår…$"

gText_AnabelWonGold::
	.string "Jeg er frygtelig ked af det…$"

gText_AnabelDefeatGold::
	.string "Tak…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Ahahaha! Er du ikke flov?\n"
	.string "Alle kigger!$"

gText_TuckerDefeatSilver::
	.string "Grr… Hvad i…$"

gText_TuckerWonGold::
	.string "Min DOME ACE titel er ikke kun til show!$"

gText_TuckerDefeatGold::
	.string "Ahahaha! Du er inspirerende!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Godt arbejde!\n"
	.string "Det var en god lektion, hva'? $"

gText_NolandDefeatSilver::
	.string "Godt klaret! Du ved, hvad du laver!$"

gText_NolandWonGold::
	.string "Hey, hey, hey! Er du færdig allerede?$"

gText_NolandDefeatGold::
	.string "Hvad skete der her?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Hm…$"

gText_LucyDefeatSilver::
	.string "Åh…$"

gText_LucyWonGold::
	.string "Hah!$"

gText_LucyDefeatGold::
	.string "Forbandet!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Åh, kom nu!\n"
	.string "Du må prøve hårdere end det!$"

gText_GretaDefeatSilver::
	.string "Nej, det kan ikke passe! Godt klaret!$"

gText_GretaWonGold::
	.string "Heheh! Hvad havde du forventet?$"

gText_GretaDefeatGold::
	.string "Huh? Er du seriøs?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Dine POKéMON er svage fordi\n"
	.string "du er en svag TRÆNER!$"

gText_SpenserDefeatSilver::
	.string "Ah… Nu er dette noget andet…$"

gText_SpenserWonGold::
	.string "Gwahahaha! Mine brødre, vi har intet at\n"
	.string "frygte!$"

gText_SpenserDefeatGold::
	.string "Gwah! Hahahaha!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Hey! Hvad er der galt med dig!\n"
	.string "Vis lidt indsats! Kom op!$"

gText_BrandonDefeatSilver::
	.string "Det er det! Du har gjort det godt! Du\n"
	.string "har arbejdet hårdt for dette!$"

gText_BrandonWonGold::
	.string "Hey! Giv ikke op nu! Kom op! Mist ikke\n"
	.string "troen på dig selv!$"

gText_BrandonDefeatGold::
	.string "Det er det! Du har gjort det! Du holdt\n"
	.string "ved og arbejdede for dette!$"



