@ TRANSLATED

@ Battle Tower
gText_AnabelWonSilver::
	.string "Det er meget skuffende…$"

gText_AnabelDefeatSilver::
	.string "Okay, jeg forstår…$"

gText_AnabelWonGold::
	.string "Jeg er frygtelig ked af det…$"

gText_AnabelDefeatGold::
	.string "Tak…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Ahahaha! Er du ikke flov?\n"
	.string "Alle kigger!$"

gText_TuckerDefeatSilver::
	.string "Grr…\n"
	.string "Hvad i…$"

gText_TuckerWonGold::
	.string "Min DOME ACE titel er ikke kun til show!$"

gText_TuckerDefeatGold::
	.string "Ahahaha!\n"
	.string "Du er inspirerende!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Godt arbejde!\n"
	.string "Det var en god lektion, hva'? $"

gText_NolandDefeatSilver::
	.string "Godt klaret!\n"
	.string "Du ved, hvad du laver!$"

gText_NolandWonGold::
	.string "Hey, hey, hey!\n"
	.string "Er du færdig allerede?$"

gText_NolandDefeatGold::
	.string "Hvad skete der her?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Hm…$"

gText_LucyDefeatSilver::
	.string "Åh…$"

gText_LucyWonGold::
	.string "Hah!$"

gText_LucyDefeatGold::
	.string "Forbandet!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Åh, kom nu!\n"
	.string "Du må prøve hårdere end det!$"

gText_GretaDefeatSilver::
	.string "Nej, det kan ikke passe!\n"
	.string "Godt klaret!$"

gText_GretaWonGold::
	.string "Heheh!\n"
	.string "Hvad havde du forventet?$"

gText_GretaDefeatGold::
	.string "Huh?\n"
	.string "Er du seriøs?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Dine POKéMON er svage fordi\n"
	.string "du er en svag TRÆNER!$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Nu er dette noget andet…$"

gText_SpenserWonGold::
	.string "Gwahahaha!\n"
	.string "Mine brødre, vi har intet at frygte!$"

gText_SpenserDefeatGold::
	.string "Gwah!\n"
	.string "Hahahaha!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Hey! Hvad er der galt med dig!\n"
	.string "Vis lidt indsats! Kom op!$"

gText_BrandonDefeatSilver::
	.string "Det er det! Du har gjort det godt!\n"
	.string "Du har arbejdet hårdt for dette!$"

gText_BrandonWonGold::
	.string "Hey! Giv ikke op nu!\n"
	.string "Kom op! Mist ikke troen på dig selv!$"

gText_BrandonDefeatGold::
	.string "Det er det! Du har gjort det!\n"
	.string "Du holdt ved og arbejdede for dette!$"
