LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Dette er POKéMON LOTTERIHJØRNET.\p"
	.string "Alle kunder i vores STORMAGASIN\n"
	.string "får lov til at trække en POKéMON LOTTO BILLET.\p"
	.string "Hvis LOTTO BILLETTENS nummer matcher\n"
	.string "ID-nummeret på en af dine POKéMON,\l"
	.string "vil du modtage en fantastisk gave.\p"
	.string "Vil du trække en POKéMON\n"
	.string "LOTTO BILLET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Kom venligst tilbage i morgen.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Kom endelig igen.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Vælg venligst en LOTTO BILLET.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "LOTTO BILLETTENS nummer er {STR_VAR_1}.\p"
	.string "Jeg skal køre en kontrol på dette nummer\n"
	.string "for at se, om det matcher nogen af dine\l"
	.string "POKéMON's ID-numre. Vent venligst.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Tillykke!\p"
	.string "ID-nummeret på dit holds\n"
	.string "{STR_VAR_1} matcher din\l"
	.string "LOTTO BILLETS nummer!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Tillykke!\p"
	.string "ID-nummeret på din PC-boks\n"
	.string "{STR_VAR_1} matcher din\l"
	.string "LOTTO BILLETS nummer!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Jeg er ked af det.\n"
	.string "Ingen af numrene matchede.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "To cifre matchede, så du vinder\n"
	.string "tredjepræmien!\l"
	.string "Du har vundet {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Tre cifre matchede, så du vinder\n"
	.string "andenpræmien!\l"
	.string "Du har vundet {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Fire cifre matchede, så du vinder\n"
	.string "førstepræmien!\l"
	.string "Du har vundet {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Åh, min godhed, alle fem cifre\n"
	.string "matchede!\p"
	.string "Du har vundet hovedpræmien!\n"
	.string "Du har vundet {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Åh?\n"
	.string "Du ser ud til at have ikke plads til dette.\p"
	.string "Lav venligst plads i din TASKE og\n"
	.string "lad mig vide det.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Ja, jeg har ventet dig.\p"
	.string "Dette er præmien, vi har holdt\n"
	.string "for dig.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Kom endelig igen.$"
