@ TRANSLATED

LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Dette er POKéMON LOTTERIHJØRNET.\p"
	.string "Alle kunder i vores STORMAGASIN får lov\n"
	.string "til at trække en POKéMON LOTTO BILLET.\p"
	.string "Hvis LOTTO BILLETTENS nummer matcher\n"
	.string "ID-nummeret på en af dine POKéMON, vil\l"
	.string "du modtage en fantastisk gave.\p"
	.string "Vil du trække en POKéMON LOTTO BILLET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Kom venligst tilbage i morgen.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Kom endelig igen.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Vælg venligst en LOTTO BILLET.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "LOTTO BILLETTENS nummer er\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg skal køre en kontrol på dette\n"
	.string "nummer for at se, om det matcher nogen\l"
	.string "af dine POKéMON's ID-numre. Vent\l"
	.string "venligst.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Tillykke!\p"
	.string "ID-nummeret på dit holds\n"
	.string "{STR_VAR_1} matcher din LOTTO\l"
	.string "BILLETS nummer!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Tillykke!\p"
	.string "ID-nummeret på din PC-boks\n"
	.string "{STR_VAR_1} matcher din LOTTO\l"
	.string "BILLETS nummer!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Jeg er ked af det. Ingen af numrene\n"
	.string "matchede.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "To cifre matchede, så du vinder\n"
	.string "tredjepræmien! Du har vundet\l"
	.string "{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Tre cifre matchede, så du vinder\n"
	.string "andenpræmien! Du har vundet\l"
	.string "{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Fire cifre matchede, så du vinder\n"
	.string "førstepræmien! Du har vundet\l"
	.string "{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Åh, min godhed, alle fem cifre matchede!\p"
	.string "Du har vundet hovedpræmien! Du har\n"
	.string "vundet {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Åh? Du ser ud til at have ikke plads til\n"
	.string "dette.\p"
	.string "Gør venligst plads i din RYGSÆK og kom\n"
	.string "tilbage.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}? Ja, jeg har ventet dig.\p"
	.string "Dette er præmien, vi har holdt for dig.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Kom endelig igen.$"



