MatchCall_WildBattleText1::
	.string "Hej! {PLAYER}{KUN}, hej!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg så denne {STR_VAR_2} for et stykke tid siden\n"
	.string "men jeg kunne ikke fange den.\p"
	.string "Den var så tæt på, også!\n"
	.string "Nå, vi ses igen!$"

MatchCall_WildBattleText2::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg prøvede at fange en fin {STR_VAR_2}\n"
	.string "for lidt siden.\p"
	.string "Men den slap væk.\n"
	.string "Jeg var virkelig skuffet!\p"
	.string "Okay, farvel!$"

MatchCall_WildBattleText3::
	.string "Hej {PLAYER}!\n"
	.string "Det er mig, {STR_VAR_1}.\p"
	.string "Jeg forsøgte lige at fange denne\n"
	.string "{STR_VAR_2}, men den løb sin vej.\p"
	.string "Jeg var så tæt på, også!\p"
	.string "Den ødelagde min dag…\n"
	.string "Nå, vi ses!$"

MatchCall_WildBattleText4::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Kender du POKéMON {STR_VAR_2}?\n"
	.string "Jeg kom tæt på at fange en.\p"
	.string "Det var for lidt siden.\n"
	.string "Jeg troede, jeg havde den, men den\n"
	.string "undslap.\p"
	.string "Hvis jeg ser den igen, får jeg den\n"
	.string "sikkert.\p"
	.string "Okay, vi snakkes senere.$"

MatchCall_WildBattleText5::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}.\l"
	.string "Har du fanget nogle POKÉMON på det\n"
	.string "sidste? Hørte du det?\p"
	.string "For et øjeblik siden var jeg tæt på at\n"
	.string "fange en, men den slap løs.\p"
	.string "Okay, pas på!$"

MatchCall_WildBattleText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\l" 
	.string "Har du fanget nogle POKéMON på det seneste?\p" 
	.string "Jeg prøvede næsten at fange en forleden dag.\n" 
	.string "Men den undslap mig på en eller anden måde.\p" 
	.string "Pas på dig selv.$"

MatchCall_WildBattleText7::
	.string "…Øh, {PLAYER}{KUN}?\n"
	.string "Det er mig, {STR_VAR_1}.\p"
	.string "Vent lidt! Vent!\n"
	.string "Jeg kan fange denne {STR_VAR_2}…\p"
	.string "Aaarrrgh! Den undslap!\n"
	.string "Det var lige ved og næsten!$"

MatchCall_WildBattleText8::
	.string "Åh, {PLAYER}{KUN}, hvordan går det?\n"
	.string "Det er {STR_VAR_1}, der taler.\p"
	.string "Har du haft succes med at fange\n"
	.string "POKéMON på det sidste?\p"
	.string "Jeg kom meget tæt på for nylig,\n"
	.string "men mit mål slap væk.\p"
	.string "Jeg bliver nødt til at prøve\n"
	.string "hårdere! Vi ses igen!$"

MatchCall_WildBattleText9::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Nå? Samler du flere POKéMON\n"
	.string "sammen?\p"
	.string "Jeg har en elendig tid med det!\n"
	.string "De slipper alle væk fra mig!\p"
	.string "Vi ses!$"

MatchCall_WildBattleText10::
	.string "Åh, {PLAYER}{KUN}, hej…\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Hør, jeg var så tæt på at fange denne\n"
	.string "{STR_VAR_2}…\p"
	.string "Men den slap væk…\p"
	.string "Jeg bliver nødt til at prøve hårdere.\n"
	.string "Vi ses.$"

MatchCall_WildBattleText11::
	.string "Åh, {PLAYER}{KUN}.\n"
	.string "Dette er {STR_VAR_1}.\l"
	.string "Hvordan går det med dig?\p"
	.string "Jeg prøvede at fange en vild {STR_VAR_2}\n"
	.string "tidligere, men den formåede at flygte.\p"
	.string "Jeg føler mig slået…$"

MatchCall_WildBattleText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Fanger du stadig POKéMON?\p"
	.string "Jeg har også prøvet at fange dem\n"
	.string "selv, men det er ikke så nemt.\p"
	.string "POKéMONs verden er dyb!$"

MatchCall_WildBattleText13::
	.string "Åh, hej, {PLAYER}{KUN}!\n"
	.string "Det her er {STR_VAR_1}!\l"
	.string "Har du fanget POKéMON?\p"
	.string "Jeg har også prøvet at fange\n"
	.string "dem, men med ringe succes.\p"
	.string "POKéMONs vej er dyb!$"

MatchCall_WildBattleText14::
	.string "Hej, {PLAYER}{KUN}, hvordan går det?\n"
	.string "Det her er {STR_VAR_1}.\p"
	.string "Lige nu prøvede jeg at fange en sød\n"
	.string "{STR_VAR_2}.\p"
	.string "Det slap dog væk!\n"
	.string "Åh, jeg var skuffet!\p"
	.string "Farvel!$"

MatchCall_WildBattleText15::
	.string "Hej, {PLAYER}!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg har tænkt på at prøve\n"
	.string "at fange nogle POKéMON.\p"
	.string "Men jeg kan ikke finde nogen.\n"
	.string "Det er en rigtig gåde for mig!\p"
	.string "Jeg er i bunden af min visdom!\n"
	.string "Vi ses!$"

MatchCall_NegativeBattleText1::
	.string "Hej! {PLAYER}{KUN}, hej!\n"
	.string "Det her er {STR_VAR_1}.\p"
	.string "Jeg prøvede at kæmpe mod en anden TRÆNER,\n"
	.string "men jeg tabte.\p"
	.string "Det var virkelig skuffende.\n"
	.string "Nå, vi ses igen!$"

MatchCall_NegativeBattleText2::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg udfordrede en anden efter vi\n"
	.string "kæmpede.\p"
	.string "Jeg kom tæt på, men endte med at\n"
	.string "tabe. Nå, pyt!$"

MatchCall_NegativeBattleText3::
	.string "Hej {PLAYER}!\n"
	.string "Det er mig, {STR_VAR_1}.\p"
	.string "Jeg blev lige ryddet af i en kamp.\p"
	.string "Jeg skal nok forbedre mit hold lidt mere!$"

MatchCall_NegativeBattleText4::
	.string "Hej, {PLAYER}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Jeg prøvede en anden kamp i går,\n"
	.string "men jeg kunne ikke vinde.\p"
	.string "Mit hold har brug for mere træning.\n"
	.string "Okay, vi ses senere.$"

MatchCall_NegativeBattleText5::
	.string "Hej, {PLAYER}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Hvordan går det med dig?\p"
	.string "Jeg har kæmpet, men\n"
	.string "jeg har ikke vundet særlig tit.\p"
	.string "Jeg kan ikke få det til at\n"
	.string "fungere. Nå, pas på!$"

MatchCall_NegativeBattleText6::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Hvordan går det for dig?\p"
	.string "Jeg har kæmpet hårdt på det\n"
	.string "seneste, men til ingen succes.\p"
	.string "Jeg kan ikke komme i flow.\n"
	.string "Pas på dig selv.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} her.\n"
	.string "Hvordan går det for tiden?\p"
	.string "Jeg tabte en kamp i går,\n"
	.string "og det fylder mine tanker.\p"
	.string "Jeg må tænke en plan ud…\n"
	.string "Vi ses.$"

MatchCall_NegativeBattleText8::
	.string "Åh, {PLAYER}{KUN}, hvordan har du det?\n"
	.string "Det er {STR_VAR_1} der taler.\p"
	.string "Hvordan har dine POKéMON det?\n"
	.string "Jeg tabte en kamp forleden dag.\p"
	.string "Jeg skal prøve hårdere!\n"
	.string "Vi ses igen!$"

MatchCall_NegativeBattleText9::
	.string "Åh, {PLAYER}{KUN}, hej der!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Hør nu her, du skal høre\n"
	.string "dette!\p"
	.string "Jeg havde en POKéMON-kamp tidligere,\n"
	.string "men jeg tabte i sidste sekund.\p"
	.string "Åh, det gør mig vred!$"

MatchCall_NegativeBattleText10::
	.string "Åh, {PLAYER}{KUN}, hej…\n"
	.string "Det her er {STR_VAR_1}.\p"
	.string "For lidt tid siden var jeg i kamp.\n"
	.string "Jeg tabte dog.\p"
	.string "Jeg skal træne mine POKéMON mere.\n"
	.string "Vi ses rundt omkring.$"

MatchCall_NegativeBattleText11::
	.string "Åh, {PLAYER}{KUN}.\n"
	.string "Det her er {STR_VAR_1}.\l"
	.string "Hvordan har dine POKéMON det?\p"
	.string "Jeg tabte lige endnu en kamp.\p"
	.string "Nå, vi ses!$"

 MatchCall_NegativeBattleText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Kæmper du stadig hårdt?\p"
	.string "Hvad mig angår, tabte jeg\n"
	.string "for nylig, så jeg har trænet mit\n"
	.string "hold overalt.\p"
	.string "Lad os mødes igen.$"

MatchCall_NegativeBattleText13::
	.string "Åh, hej, {PLAYER}{KUN}!\n"
	.string "Det her er {STR_VAR_1}!\p"
	.string "Jeg håber, du har det godt.\p"
	.string "Jeg var i kamp lige før\n"
	.string "dette.\p"
	.string "{PLAYER}{KUN}, prøv at være aktiv som mig.\n"
	.string "Vi ses igen!$"

MatchCall_NegativeBattleText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det her er {STR_VAR_1}.\p"
	.string "Har du det godt?\p"
	.string "Du bør tage hjem en gang imellem,\n"
	.string "dog.\p"
	.string "Farvel!$"

MatchCall_PositiveBattleText1::
	.string "Hej! {PLAYER}{KUN}, hej!\n"
	.string "Det her er {STR_VAR_1}!\p"
	.string "Jeg kæmpede mod en anden TRÆNER tidligere.\n"
	.string "Jeg vandt! Jeg vandt!\p"
	.string "Min {STR_VAR_2} arbejdede virkelig hårdt\n"
	.string "for mig. Det her er så godt!$"

MatchCall_PositiveBattleText2::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg havde en kamp i går og\n"
	.string "jeg vandt! Det er fantastisk!$"

MatchCall_PositiveBattleText3:: 
	.string "Hej {PLAYER}!\n"
	.string "Det er mig, {STR_VAR_1}!\l"
	.string "Hvordan går det med dine kampe?\p"
	.string "Jeg havde en kamp den anden dag,\n"
	.string "og min {STR_VAR_2} gjorde det stort!\p"
	.string "Næste gang vi kamper,\n"
	.string "{PLAYER}, det bliver ikke mig, der taber!$"

MatchCall_PositiveBattleText4::
	.string "Hej, {PLAYER}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Jeg havde en kamp tidligere.\n"
	.string "Jeg formåede at vinde, men det \n"
	.string "var tæt.\p"
	.string "Min {STR_VAR_2} gav en\n"
	.string "inspirerende præstation.$"

MatchCall_PositiveBattleText5::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Hvordan går det med dig?\n"
	.string "Kæmper du meget?\p"
	.string "Jeg vandt lige for nylig!\n"
	.string "Min {STR_VAR_2} var genial!\p"
	.string "Du venter bare. Jeg vil slå dig\n"
	.string "næste gang! Okay, pas på!$"

MatchCall_PositiveBattleText6::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Hvordan går det for dig?\p"
	.string "Jeg har været på en vinderstribe.\n"
	.string "Jeg vandt lige en kamp.\p"
	.string "Når vi har vores næste kamp,\n"
	.string "er jeg sikker på, at jeg ikke\n"
	.string "vil tabe!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} her.\p"
	.string "Min {STR_VAR_2} er en kraft!\n"
	.string "Den vandt mig en anden kamp lige nu!\p"
	.string "Jeg kan ikke vente med at få en revanche\n"
	.string "med dig.$"

MatchCall_PositiveBattleText8::
	.string "Hej, {PLAYER}{KUN}, hvordan har du det?\n"
	.string "Det er {STR_VAR_1} der taler.\p"
	.string "Jeg håber, du har det godt.\n"
	.string "Jeg ville bare fortælle dig, at jeg lige vandt.\p"
	.string "Min {STR_VAR_2} arbejdede især\n"
	.string "hårdt for at få sejren.\p"
	.string "Vi ses igen!$"

MatchCall_PositiveBattleText9::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Her er {STR_VAR_1}!\p"
	.string "Hvordan har dine POKéMON det?\n"
	.string "Mine har lige vundet en kamp!\p"
	.string "Min {STR_VAR_2} var fantastisk,\n"
	.string "må jeg sige!\p"
	.string "Jeg ønsker, jeg kunne have vist dig!\n"
	.string "Vi ses igen!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}ærme, hej…\n"
	.string "Det her er {STR_VAR_1}.\p"
	.string "Hvordan har livet behandlet dig?\p"
	.string "Mine POKéMON ser ud til at være fyldt\n"
	.string "med energi.\p"
	.string "Jeg vandt lige en kamp med dem.\n"
	.string "Vi ses.$"

MatchCall_PositiveBattleText11::
	.string "Hovsa, {PLAYER}{KUN}.\n"
	.string "Dette er {STR_VAR_1}.\p"
	.string "Har du kæmpet for nylig?\n"
	.string "Jeg vandt lige endnu en kamp i dag!\p"
	.string "Jeg er i topform! Gahahaha!\n"
	.string "Nå, vi ses!$"

MatchCall_PositiveBattleText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\p"
	.string "Jeg håber, alt er godt?\n"
	.string "Jeg sprudler stadig af liv!\p"
	.string "Jeg vandt endda lige igen.\n"
	.string "Jeg giver ikke plads til jer\n"
	.string "ungdommelige endnu!\p$"

MatchCall_PositiveBattleText13::
	.string "Åh, hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg håber, at du har det godt.\n"
	.string "Jeg har stadig schwung i skridtet!\p"
	.string "Ja, jeg har lige vundet endnu en\n"
	.string "kamp.\n"
	.string "Åh, jeg vil ikke tabe til unge\n"
	.string "mennesker endnu!\p"
	.string "Vi ses igen!$"

MatchCall_PositiveBattleText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg var i kamp for nylig, og min\n"
	.string "{STR_VAR_2} var exceptionel!\p"
	.string "Jeg ville ønske, at du kunne have set det,\n"
	.string "{PLAYER}{KUN}. Hej-hej!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hej! {PLAYER}, hej!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Hvad? Vent, er du tæt på\n"
	.string "{STR_VAR_2}?\p"
	.string "Wow, så må vi kæmpe!\n"
	.string "Jeg venter! Vi ses!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Hej, {PLAYER}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Åh? Er du tilfældigvis i\n"
	.string "{STR_VAR_2} lige nu?\p"
	.string "Skal vi kæmpe nu?\n"
	.string "Jeg venter på dig! Vi ses!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Hej der, {PLAYER}!\n"
	.string "Det er mig, {STR_VAR_1}.\p"
	.string "Åh, hej, er du tæt på\n"
	.string "{STR_VAR_2} lige nu?\p"
	.string "Vil du kæmpe med mig\n"
	.string "lige nu?\p"
	.string "Jeg taber ikke igen!\n"
	.string "Jeg venter! Vi ses snart!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Hvor befinder du dig nu?\n"
	.string "Hva' så? {STR_VAR_2}?\p"
	.string "Skal vi kæmpe nu?\n"
	.string "Jeg vil vente på dig. Vi ses!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}.\l"
	.string "Hvordan går det med dig?\p"
	.string "Er du hvor nu?\n"
	.string "{STR_VAR_2}?\p"
	.string "Hvad siger du til en hurtig\n"
	.string "omkamp lige nu?\p"
	.string "Jeg holder øje med dig.\n"
	.string "Vi ses snart!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\l"
	.string "Hvordan har dine POKéMON det?\p"
	.string "Åh, er det rigtigt? Du er i nærheden\n"
	.string "af {STR_VAR_2}?\p"
	.string "Nå, så må vi hellere få\n"
	.string "en omkamp.\p"
	.string "Jeg kan vente, selvfølgelig.\n"
	.string "Vi ses!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Øh, {PLAYER}igen?\n"
	.string "{STR_VAR_1} her…\p"
	.string "Åh, er du tilfældigvis i\n"
	.string "{STR_VAR_2}?\p"
	.string "Så lad os kæmpe.\n"
	.string "Med det samme, mener jeg.\p"
	.string "Jeg vil vise dig mine POKéMON.\n"
	.string "Jeg venter på dig.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Hej, {PLAYER}{KUN}, hvordan går det?\n"
	.string "Det er {STR_VAR_1}, der taler.\p"
	.string "Jeg håber, du har det godt.\n"
	.string "Åh, du er nær {STR_VAR_2}.\p"
	.string "Har du lyst til at kæmpe\n"
	.string "med mig så?\p"
	.string "Jeg venter på dig.\n"
	.string "Vi ses snart!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Hej, {PLAYER}{KUN}, hej!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Er du med?\n"
	.string "Er du nær {STR_VAR_2}?\p"
	.string "Nå, så synes du ikke, vi\n"
	.string "skal kæmpe?\p"
	.string "Hold mig ikke vente for længe!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Hej, {PLAYER}{KUN}…\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Hvordan går det med dig?\n"
	.string "Oh, du er tæt på {STR_VAR_2}.\p"
	.string "Vi burde kæmpe nu.\p"
	.string "Jeg er klar og venter.\n"
	.string "Skynd dig!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Åh, {PLAYER}{KUN}.\n"
	.string "Det her er {STR_VAR_1}.\p"
	.string "Åh, så hvor du er lige nu er\n"
	.string "{STR_VAR_2}?\p"
	.string "Nå, så bliver vi nødt til at\n"
	.string "have en kamp, ikke sandt?\p"
	.string "Jeg venter på dig!\n"
	.string "Vi ses snart!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Hvor befinder du dig nu?\p"
	.string "{STR_VAR_2}?\n"
	.string "Det er ret tæt på!\p"
	.string "Hvad siger du til at have en kamp\n"
	.string "nu?\p"
	.string "Jeg kan vente.\n"
	.string "Vi ses!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Åh, hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg håber, du har det godt.\n"
	.string "Åh, du er tæt på {STR_VAR_2}?\p"
	.string "Da det ikke er så langt væk,\n"
	.string "kom og se mig til en kamp.\p"
	.string "Jeg venter på dig.\n"
	.string "Hej for nu.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Hvad siger du? ...{STR_VAR_2}?\n"
	.string "Det er meget tæt på.\p"
	.string "Synes du ikke vi burde\n"
	.string "have en kamp?\p"
	.string "Jeg vil lede efter dig!\n"
	.string "Farvel!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hej! {PLAYER}, hej!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Vil du kæmpe imod mig?\p"
	.string "Jeg venter på dig omkring\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Hej, {PLAYER}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Vil du kæmpe\n"
	.string "mod mig igen?\p"
	.string "Du kan finde mig omkring\n"
	.string "{STR_VAR_2}. Jeg venter!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Hej {PLAYER}!\n"
	.string "Det' mig, {STR_VAR_1}.\p"
	.string "Mine POKéMON er blevet meget\n"
	.string "stærkere siden sidst.\p"
	.string "Jeg vil gerne se hvor stærke\n"
	.string "de er blevet i forhold til dine\n"
	.string "POKéMON, {PLAYER}.\p"
	.string "Så lad os kæmpe!\p"
	.string "Jeg venter på dig ved\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\l"
	.string "Hvordan går det med dig?\p"
	.string "Mine POKéMON er blevet ret\n"
	.string "seje på det sidste.\p"
	.string "Hey, kunne du tænke dig at tage\n"
	.string "en kamp til med mig?\p"
	.string "Vi kan mødes omkring\n"
	.string "{STR_VAR_2}, okay?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Mine POKéMON vokser op på\n"
	.string "fine måder.\p"
	.string "Jeg vil virkelig gerne have et\n"
	.string "anden kamp med dig.\p"
	.string "Jeg vil holde øje med dig omkring\n"
	.string "{STR_VAR_2}. Vi ses snart!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\l"
	.string "Jeg håber, du har styr på tingene.\p"
	.string "Jeg tænkte, at jeg gerne vil udfordre\n"
	.string "dig til endnu et slag. Hvad siger du?\p"
	.string "Hvis du har lyst til kamp,\n"
	.string "så kom til {STR_VAR_2}.\p"
	.string "Vi ses!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Øh, er det dig, {PLAYER}{KUN}? \n"
	.string "{STR_VAR_1} her…\l"
	.string "Nå? Gror dine POKéMON? \p"
	.string "Mine er helt sikkert blevet stærkere.\n"
	.string "Jeg vil gerne vise dig det. \p"
	.string "Jeg vil være i nærheden af {STR_VAR_2}. \n"
	.string "Kom og find mig til en kamp. \p"
	.string "Vi ses.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Hej, {PLAYER}{KUN}, hvordan går det?\n"
	.string "Det er {STR_VAR_1}, der taler.\p"
	.string "Jeg håber, du har det godt.\n"
	.string "Mine POKéMON er meget livlige.\p"
	.string "Hvis du nogensinde er i området, så\n"
	.string "giv mig en revanche.\p"
	.string "Jeg vil være omkring {STR_VAR_2}.\n"
	.string "Indtil da, farvel!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\l"
	.string "Hvordan har dine POKéMON det?\p"
	.string "Mine POKéMON bliver ved med at blive bedre.\n"
	.string "Jeg vil gerne vise dig, {PLAYER}{KUN}.\p"
	.string "Jeg er omkring {STR_VAR_2} nu,\n"
	.string "så lad os kæmpe, hvis du er i nærheden.\p"
	.string "Håber jeg ser dig snart!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Hej, {PLAYER}{KUN}…\n"
	.string "Det er {STR_VAR_1}.\l"
	.string "Nå, hvordan går det med dig?\p"
	.string "Mine POKéMON er blevet\nganske meget stærkere.\p"
	.string "Jeg vil meget gerne kæmpe\n"
	.string "med dig igen, {PLAYER}{KUN}.\p"
	.string "Jeg er i nærheden af {STR_VAR_2}.\n"
	.string "Kom og besøg mig, hvis du er tæt på.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Dette er {STR_VAR_1}.\l"
	.string "Hvor mon du befinder dig nu?\p"
	.string "Mine POKéMON er fulde af liv.\n"
	.string "De ser ud til at glæde sig til\l"
	.string "at se dine POKéMON, {PLAYER}{KUN}.\p"
	.string "Jeg er omkring {STR_VAR_2} nu.\n"
	.string "Jeg håber, du vil opsøge os.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\p"
	.string "Jeg bør fortælle dig, at mine POKéMON er\n"
	.string "vokset sig ret robuste på det seneste.\p"
	.string "Jeg vil gerne se dem i kamp med dig,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Vi vil være omkring {STR_VAR_2}.\n"
	.string "Kom og besøg os når som helst!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Åh, hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\l"
	.string "Har dine POKéMON det godt?\p"
	.string "Mine POKéMON har været så sunde,\n"
	.string "at de ikke ser ud til at kunne tabe!\p"
	.string "Jeg ville helt sikkert elske at\n"
	.string "kæmpe mod dig igen.\p"
	.string "Hvis du er i nærheden af {STR_VAR_2},\n"
	.string "skal du endelig komme forbi hos os.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er {STR_VAR_1}.\l"
	.string "Alt godt, håber jeg.\p"
	.string "åh, ja! Mine POKéMON er\n"
	.string "meget stærkere end før.\p"
	.string "Synes du ikke, vi burde tage\n"
	.string "en kamp, {PLAYER}{KUN}?\p"
	.string "Vi venter på dig omkring\n"
	.string "{STR_VAR_2}.\p"
	.string "Kom og besøg os når som helst, okay?$"

MatchCall_PersonalizedText1::
	.string "Det' mig, bjerg-elskeren!\n"
	.string "{STR_VAR_1}!\p"
	.string "Har du lært at værdsætte\n"
	.string "bjergene mere, siden vi sidst mødtes?\p"
	.string "Jeg ser dig sjældent i bjergene…\p"
	.string "Næste gang mødes vi et sted\n"
	.string "omkring {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "Det her er {STR_VAR_1}.\n"
	.string "Hej.\p"
	.string "Jeg var lige ved at fortælle en ny TRÆNER\n"
	.string "om dig.\p"
	.string "Jeg fortalte hende om en stærk TRÆNER\n"
	.string "som opdrætter POKéMON med omhu.\p"
	.string "Jeg håber, du bliver en TRÆNER\n"
	.string "som alle vil beundre.\p"
	.string "Jeg håber, vi mødes igen!$"

MatchCall_PersonalizedText3::
	.string "Hej! Det er {STR_VAR_1}.\p"
	.string "Jeg elsker hvor jeg er lige nu.\n"
	.string "Det er dejligt med søde aromaer!\p"
	.string "Jeg tror nogen plantede BÆR,\n"
	.string "og de sprang i blomst.\p"
	.string "Vi ses igen en anden gang!$"

MatchCall_PersonalizedText4::
	.string "Hej! Tredive års udforskning,\n"
	.string "{STR_VAR_1} til din tjeneste!\p"
	.string "Det ser ud til, at du energisk\n"
	.string "rejser frem og tilbage.\p"
	.string "Har du opdaget nogle nye ruiner?\n"
	.string "Fortæl mig venligst, hvis du har!\p"
	.string "Nu vil jeg tage videre til\n"
	.string "at udforske ruiner.$"

MatchCall_PersonalizedText5::
	.string "Det er {STR_VAR_1}!\p"
	.string "Ved du, hvad jeg laver i dag?\n"
	.string "Kigger på bølger fra stranden!\p"
	.string "Suk… Bølgerne er så skinnende.\n"
	.string "Havet er smukkest herfra.\l"
	.string "Jeg bliver sulten, så hej-hej!$"

MatchCall_PersonalizedText6::
	.string "Smask-tyg…\n"
	.string "Hej--det er {STR_VAR_1}.\l"
	.string "Jeg elsker at spise på stranden.\p"
	.string "Mine POKéMON og jeg har det\n"
	.string "fantastisk. Vi er helt tanket op!\l"
	.string "Jeg skal en tur i vandet. Hej!$"

MatchCall_PersonalizedText7::
	.string "Hej, det er {STR_VAR_1}…\p"
	.string "Jeg er blevet lidt træt af det her\n"
	.string "med hele SEJTRÆNER-titlen…\p"
	.string "Alle tror, at jeg er en perfekt\n"
	.string "TRÆNER, og det får mig til at\l"
	.string "stræbe efter at leve op til den\n"
	.string "forventning.\p"
	.string "Men det må jeg jo affinde mig\n"
	.string "med, når jeg er en SEJTRÆNER.\p"
	.string "Jeg bliver nødt til at tage mig\n"
	.string "sammen… og bide tænderne sammen.\p"
	.string "Du er den eneste, jeg kan\n"
	.string "betror mig til på den måde.\p"
	.string "Men når jeg ser dig næste gang,\n"
	.string "bare rolig, jeg vil ikke brokke mig!$"

MatchCall_PersonalizedText8::
	.string "Juhu, det er {STR_VAR_1}!\n"
	.string "Hvordan har du det?\p"
	.string "Jeg har opdraget mine POKéMON med\n"
	.string "dig som målet.\p"
	.string "Jeg har ikke tænkt mig at tabe,\n"
	.string "når vi kæmper igen.\p"
	.string "Er det ikke skønt at have TRÆNER-\n"
	.string "venner? Lad os mødes igen!$"

MatchCall_PersonalizedText9::
	.string "Det er {STR_VAR_1}…\n"
	.string "Lige nu, bag dig…\l"
	.string "Var der ikke noget…?\p"
	.string "Kraften fra POKéMON'erne,\n"
	.string "som sover her på MT. PYRE…\p"
	.string "De fortæller mig om dig…\p"
	.string "Du burde gå hurtigt væk og\n"
	.string "aldrig kigge tilbage…\p"
	.string "Hihi…\n"
	.string "Farvel…$"

MatchCall_PersonalizedText10::
	.string "Det her er {STR_VAR_1}.\n"
	.string "Hvordan har du det?\p"
	.string "Er det ikke praktisk, at vi kan\n"
	.string "snakke sådan her på afstand?\p"
	.string "Førhen, hvis jeg ville tale med\n"
	.string "nogen, måtte jeg have min far\l"
	.string "køre mig…\p"
	.string "Jeg burde nok smutte nu.\n"
	.string "Jeg er glad for, at vi snakkede.$"

MatchCall_PersonalizedText11::
	.string "Det er {STR_VAR_1}!\n"
	.string "Vil du høre dette?\p"
	.string "Jeg kan rigtig godt lide SAFARI ZONEN,\n"
	.string "men hver gang jeg besøger den, farer jeg vild!\p"
	.string "Al det høje græs!\n"
	.string "Og det er alt for uoverskueligt!\p"
	.string "Jeg føler mig bedre, efter jeg har\n"
	.string "løftet det fra hjertet!\p"
	.string "Jeg tager til SAFARI ZONEN igen!\n"
	.string "Vi ses!$"

MatchCall_PersonalizedText12::
	.string "Hej, her er {STR_VAR_1}.\n"
	.string "Ja, korrekt, jeg er rig, ja.\p"
	.string "Jeg bør fortælle dig, at min\n"
	.string "formue er vokset, siden sidst vi mødtes.\p"
	.string "Hvad mere er, mine POKéMON er også\n"
	.string "blevet stærkere.\p"
	.string "Jeg kan ikke slippe følelsen af,\n"
	.string "at denne verden eksisterer for mig!\p"
	.string "Åh, der er ingen grund til at sige\n"
	.string "et ord!\nAlle ved, det er sandt!\p"
	.string "Åh, du må undskylde mig, jeg har dette\n"
	.string "formelle middagsselskab at deltage i.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "Det er mig, {STR_VAR_1}…\p"
	.string "Kan du gætte, hvad jeg ser?\n"
	.string "Et par {STR_VAR_2} i kamp.\p"
	.string "Måske vil jeg prøve at fange vinderen…\n"
	.string "Ufufufufufu…\p"
	.string "Jeg… Jeg er lidt optaget lige nu.\n"
	.string "Jeg er nødt til at gå.$"

MatchCall_PersonalizedText14::
	.string "Åh, det er {STR_VAR_1}!\p"
	.string "Jeg sad lige og tænkte på, at jeg\n"
	.string "er ved at blive træt af DEN FORLADTE\n"
	.string "SKIB.\p"
	.string "Men da jeg allerede er her, og jeg\n"
	.string "gerne vil slå dig én gang,\l"
	.string "så bliver jeg lidt længere.\p"
	.string "Hvis du føler dig fristet, hvorfor\n"
	.string "kommer du ikke og besøger mig?\p"
	.string "Jeg tror, at i dag bliver dagen,\n"
	.string "hvor jeg endelig udfordrer ham\n"
	.string "næste dør til en kamp.\p"
	.string "Vi ses!$"

MatchCall_PersonalizedText15::
	.string "Jeg er {STR_VAR_1}!\n"
	.string "Manden fra havet!\p"
	.string "Ved du hvad jeg tænker?\p"
	.string "De TRÆNERE derude på havet\n"
	.string "er de sejeste af de seje!\p"
	.string "Du burde lære af mig og træne\n"
	.string "på havet…\p"
	.string "Ups, kæmpe bølge på vej!\p"
	.string "Det er en fantastisk træningsmulighed!\n"
	.string "Beklager, men jeg bliver nødt til at gå!$"

MatchCall_PersonalizedText16::
	.string "Det er {STR_VAR_1}! Lyt, jeg har\n"
	.string "undervist i karate til mine POKéMON.\p"
	.string "Men nu er de bedre end mig!\n"
	.string "Jeg har kun tabt til dem!\p"
	.string "Men selvom jeg taber til\n"
	.string "POKéMON, vil jeg ikke tabe til en\l"
	.string "ANDEN TRÆNER, nej, hr.!\p"
	.string "Vi er nødt til at kæmpe igen!\n"
	.string "Ugwaah!$"

MatchCall_PersonalizedText17::
    .string "Det' mig, {STR_VAR_1}.\n"
    .string "Hvordan går det med dine rejser?\p"
    .string "…Wow, er det rigtigt?\n"
    .string "Det lyder enormt spændende!\p"
    .string "Jeg tror, jeg kunne skrive en sang\n"
    .string "om en af dine oplevelser.\p"
    .string "…Nå, hey, jeg føler det.\n"
    .string "Jeg hører riffs i mit hoved.\p"
    .string "Jeg må nok få skrevet denne melodi\n"
    .string "ordentligt ned, så jeg bliver nødt til\n"
    .string "at flyve! Vi ses!$"

MatchCall_PersonalizedText18::
	.string "Dette er {STR_VAR_1}…\n"
	.string "Hør min nye sang.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Hvorfor er du så {STR_VAR_2}?\l"
	.string "Hvorfor kan jeg ikke være dig, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} og {STR_VAR_1},\l"
	.string "{STR_VAR_1} og {STR_VAR_2}…\p"
	.string "Gentag omkvædet, fade…$"

MatchCall_PersonalizedText19::
	.string "Jeg er {STR_VAR_1}, ved du nok,\n"
	.string "eksperten i camping!\p"
	.string "Da vi kæmpede, kunne jeg ikke\n"
	.string "undgå at tabe til dig.\p"
	.string "Trods alt, min ekspertise ligger\n"
	.string "inden for camping.\p"
	.string "Men uanset om jeg vinder eller\n"
	.string "taber, så kan jeg godt lide at\n"
	.string "kæmpe, når jeg camperer.\p"
	.string "Kom og kæmp med os igen, okay?\n"
	.string "Åh, og lad os også tage på\n"
	.string "camping sammen!$"

 MatchCall_PersonalizedText20::
	.string "Det' mig, mig, {STR_VAR_1}!\p"
	.string "Jeg vil gerne bestige andre bjerge\n"
	.string "end dette, for at være ærlig.\p"
	.string "Men jeg er ikke sikker på, om der er\n"
	.string "damer som på MT. CHIMNEY.\p"
	.string "Hvis du kender nogle andre bjerge\n"
	.string "med damer omkring, så lad mig vide!\p"
	.string "Høhøhø, vi ses!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Det er {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Det var alt for i dag…$"

MatchCall_PersonalizedText22::
	.string "Dette er {STR_VAR_1}. I dag fik jeg\n"
	.string "lysten til at chatte med dig.\p"
	.string "Min lyst til at besejre dig vokser\n"
	.string "dag for dag og nat for nat.\p"
	.string "Har du en rival ligesom det, ja?\n"
	.string "Jeg ville ønske, det var mig…\p"
	.string "Jeg er glad for, at du lyttede til mig.\n"
	.string "Vi ses!$"

MatchCall_PersonalizedText23::
	.string "Det er {STR_VAR_1}.\p"
	.string "Når der er en stærk TRÆNER\n"
	.string "i nærheden, kan jeg nogle gange mærke det\n"
	.string "på en eller anden måde.\p"
	.string "Kom du tæt forbi, {PLAYER}{KUN}?\n"
	.string "Måske var det dig.\p"
	.string "Jeg venter på dit besøg.\n"
	.string "Hej hej!$"

MatchCall_PersonalizedText24::
	.string "Hej, det er {STR_VAR_1}.\n"
	.string "Du lyder godt, {PLAYER}{KUN}.\p"
	.string "Jeg har rejst rundt om i verden,\n"
	.string "men jeg må sige, at jeg har taget\n"
	.string "en stor forkærlighed for dette\n"
	.string "område.\p"
	.string "Jeg planlægger at blive her et\n"
	.string "stykke tid.\n"
	.string "Måske kan vi mødes igen?\p"
	.string "Jeg har ikke glemt dine\n"
	.string "dazzlende teknikker.\p"
	.string "Jeg håber på en revanche.$"

MatchCall_PersonalizedText25::
	.string "Hulk... Det er... {STR_VAR_1}...\n"
	.string "...Græd...\p"
	.string "ROXANNE gav mig skæld ud i\n"
	.string "dag i skolen.\p"
	.string "Men jeg kan godt lide hende.\p"
	.string "ROXANNE fortæller mig præcist,\n"
	.string "hvad jeg gjorde forkert, så jeg\n"
	.string "kan lære af det.\p"
	.string "Jeg vil helt sikkert tage til\n"
	.string "TRÆNER-SKOLEN i morgen!\p"
	.string "Vi ses senere!$"

MatchCall_PersonalizedText26::
	.string "Det er {STR_VAR_1}!\p"
	.string "ROXANNE lod mig kæmpe mod hende\n"
	.string "i går.\p"
	.string "Resultaterne…\n"
	.string "Forfærdelige, som om du\n"
	.string "havde brug for at spørge.\p"
	.string "Men jeg var henrykt over,\n"
	.string "at ROXANNE ville lade mig udfordre\n"
	.string "hende!\p"
	.string "Du ville ikke tro, hvor meget\n"
	.string "mere jeg beundrer hende!\p"
	.string "Jeg vil virkelig fokusere og arbejde!\n"
	.string "Nu må jeg hellere smutte!$"

MatchCall_PersonalizedText27::
	.string "Hej, det' ANNA! Jeg er sammen med\n"
	.string "min junior-partner MEG igen i dag.\p"
	.string "Jeg elsker virkelig at passe på MEG\n"
	.string "og POKéMON. De er så søde!\p"
	.string "Jeg ville ønske, jeg kunne passe\n"
	.string "på dem, som om de var mine søskende!\p"
	.string "Åh, hej, MEG!\n"
	.string "Fik du bollerne?\p"
	.string "Hvad? Nej, nej, jeg behandler dig\n"
	.string "ikke som min personlige slave!\p"
	.string "Du tabte kampen, så du skal gå og\n"
	.string "købe brødet som straf!\p"
	.string "Jeg ville aldrig behandle dig som en\n"
	.string "slave, MEG! Du er for speciel for mig!\p"
	.string "Jeg er nødt til at gå nu.\n"
	.string "Det er tid til vores snack!$"

MatchCall_PersonalizedText28::
	.string "Jeg elsker POKéMON!\n"
	.string "Det er {STR_VAR_1} fra FANKLUBBEN!\p"
	.string "Du bliver nødt til at høre dette!\n"
	.string "Min søde POKéMON…\p"
	.string "Snøft! Wahaha!\n"
	.string "Jeg kan ikke sige mere! Det er en hemmelighed!\l"
	.string "Det er bare alt for sødt for ord!\p"
	.string "Åh, min søde {STR_VAR_2} beder om\n"
	.string "en {POKEBLOCK}!\p"
	.string "Det er billedet af cuteness!\p"
	.string "Beklager, men jeg kan ikke snakke nu!\n"
	.string "Du må høre dette næste gang!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "Det her er {STR_VAR_1}! Jeg kan\n"
	.string "slet ikke vente med at fortælle dig\n"
	.string "om min elskede POKéMON!\p"
	.string "Vent, du bliver nødt til at høre\n"
	.string "om min elskede {STR_VAR_2}.\p"
	.string "Når nogen rører ved den,\n"
	.string "springer den straks ind i mine arme!\p"
	.string "Åh… Åh… Kan der være noget mere\n"
	.string "saligt?\p"
	.string "Åh, det føles så himmelsk!\p"
	.string "Jeg er så glad for, at jeg kunne\n"
	.string "dele lidt af min glæde med dig.\p"
	.string "Nå, jeg må videre.\n"
	.string "Hej, så!$"

  MatchCall_PersonalizedText30::
	.string "Jeg er… {STR_VAR_1}.\n"
	.string "Folk kalder mig en EKSPERT.\p"
	.string "Men der er en ting, jeg ved.\n"
	.string "Jeg kunne ikke være en EKSPERT\n"
	.string "alene med min egen kraft.\p"
	.string "Kun med hjælp fra POKéMON kan\n"
	.string "en TRÆNER blive en EKSPERT.\p"
	.string "Hov! Jeg tror, jeg lige sagde noget\n"
	.string "dybt og profondt!\p"
	.string "Jeg vil efterlade dig i godt humør!$"

MatchCall_PersonalizedText31::
	.string "Det er {STR_VAR_1}.\n"
	.string "Jeg er glad for at snakke med dig!\p"
	.string "Jeg føler mig i live og fornyet\n"
	.string "mens jeg slapper af i denne varme\n"
	.string "kilde.\p"
	.string "Jeg har kæmpet mod unge\n"
	.string "TRÆNERE siden vi mødtes, men du er\n"
	.string "stadig den bedste i flokken.\p"
	.string "Jeg forestiller mig, at du vil blive\n"
	.string "en EKSPERT i din alderdom! Ha-ha-ha…$"

MatchCall_PersonalizedText32::
	.string "Jubii! Det er {STR_VAR_1}!\n"
	.string "Hvad så? \p"
	.string "Måske er det bare mig, men når jeg\n"
	.string "vinder kampe, virker mine shorts\n"
	.string "lidt, ja, bedre. Fysisk.\p"
	.string "Hvad mener jeg med det?\n"
	.string "Det er lidt svært at forklare, men…\l"
	.string "Hvordan skulle jeg sige det nu…\l"
	.string "Mine shorts føles silkebløde!\p"
	.string "Og da jeg kæmpede mod dig, {PLAYER}{KUN},\n"
	.string "føltes mine shorts ulækre og grove.\p"
	.string "… … … … … …\n"
	.string "Troede du virkelig på det?\l"
	.string "Haha, det var det hele! Hej så!$"

MatchCall_PersonalizedText33::
	.string "Hej!\n"
	.string "{STR_VAR_1} her!\p"
	.string "Som altid fisker jeg med vild\n"
	.string "hengivenhed!\p"
	.string "Er der andre steder, hvor jeg kan\n"
	.string "fiske end havet og floderne?\p"
	.string "Jeg får disse kraftige trang til at\n"
	.string "fiske nærmest overalt!\p"
	.string "Åh, søren!\n"
	.string "Mit snøre er filtreret ind!\p"
	.string "Skal lige afsted!\n"
	.string "Find mig nogle nye fiskesteder!$"

MatchCall_PersonalizedText34::
	.string "Hej, du der! Det er {STR_VAR_1}.\n"
	.string "Tager du det roligt?\p"
	.string "Lige siden jeg var barn, du ved,\n"
	.string "har jeg altid været afslappet, hva'?\p"
	.string "Jeg har aldrig været til at stresse\n"
	.string "eller skynde på tingene.\p"
	.string "Men kan du tro det,\n"
	.string "jeg er nu en TRIATLET.\p"
	.string "Man kan aldrig vide, hvor livet\n"
	.string "fører en hen, hvis du forstår mig.\p"
	.string "Du er en TRÆNER nu, men hvem ved,\n"
	.string "hvad fremtiden bringer, hva'?\p"
	.string "Forestil dig som en lærer,\n"
	.string "eller måske en kunstner. Fedt, hva'?\p"
	.string "Men, hey, hold det chill. Tag det\n"
	.string "roligt. Vi ses.$"

MatchCall_PersonalizedText35::
	.string "Dette er {STR_VAR_1}!\n"
	.string "Jeg cykler lige nu.\p"
	.string "Jeg elsker at svømme og løbe,\n"
	.string "men cykling er min første kærlighed!\p"
	.string "Det får hele min krop til at føles,\n"
	.string "som om jeg er ét med vinden.\p"
	.string "Det opløfter mig, som om jeg fløj!\p"
	.string "Okay! I dag vil jeg sætte en ny\n"
	.string "CYKELVEJS rekord!\p"
	.string "Du bør også tage udfordringen op!\n"
	.string "Vi ses!$"

MatchCall_PersonalizedText36::
	.string "Hej, det er {STR_VAR_1}! Jeg er lige\n"
	.string "midt i en triatlon!\p"
	.string "Men hey, jeg har altid tid til at\n"
	.string "sludre lidt!\p"
	.string "At træne med POKéMON føles\n"
	.string "rigtig godt!\p"
	.string "Uden at udveksle ord, synkroniserer\n"
	.string "vi næsten som om vi delte et hjerte.\p"
	.string "Det er inspirerende!\p"
	.string "Puh... At snakke mens jeg løber...\n"
	.string "Jeg mister pusten…\l"
	.string "Puh... Skal...afsted...$"

MatchCall_PersonalizedText37::
	.string "Hej, det er {STR_VAR_1}.\n"
	.string "Hvis du vil forbedre udholdenheden,\l"
	.string "er højde-træning vejen frem!\p"
	.string "Prøv at løbe på et bjergtop.\n"
	.string "Du vil være forpustet på ingen tid!\p"
	.string "Jeg mangler også ilt!\n"
	.string "Vi ses!$"

MatchCall_PersonalizedText38::
	.string "Åh, det er {STR_VAR_1}, hej.\p"
	.string "Jeg har svømmet en masse, men jeg\n"
	.string "kan stadig ikke nå til EVERGRANDE.\p"
	.string "Måske svømmer jeg bare rundt i\n"
	.string "cirkler.\p"
	.string "Nej, nej, det kan ikke være muligt.\n"
	.string "Hahaha.\l"
	.string "Pas på!$"

MatchCall_PersonalizedText39::
	.string "Hej, det er {STR_VAR_1}…\n"
	.string "Ups!\p"
	.string "Plask!\p"
	.string "Blup-blup-blup-blup…\p"
	.string "Plumps!\p"
	.string "Vift-vift! Vift-vift!\p"
	.string "Hej! Undskyld det!\n"
	.string "Jeg smurte lige lidt solcreme på.\p"
	.string "Så forsvandt min POKéNAV lige\n"
	.string "ud af min hånd og ned i vandet!\p"
	.string "Men, puha, DEVONs POKéNAV er bygget\n"
	.string "robust. Det overlevede den dukkert!\p"
	.string "Nå, jeg er optaget af at solbade,\n"
	.string "så lad os snakke en anden gang.$"

MatchCall_PersonalizedText40::
	.string "Hej, det er {STR_VAR_1}.\p"
	.string "Af de tre triathlon-events,\n"
	.string "kan jeg bedst lide at svømme.\p"
	.string "Men hvis jeg bliver i havet for længe,\n"
	.string "bliver jeg ikke helt rynket?\p"
	.string "Åh, triathlon er så krævende\n"
	.string "en test af menneskelig udholdenhed! Hej!$"

MatchCall_PersonalizedText41::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Hvordan har dine POKéMON det?\p"
	.string "Mine DRAGE POKéMON ser ud til at være\n"
	.string "i topform. Vi ses senere.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} her.\p"
	.string "Min {STR_VAR_2} er blevet endnu\n"
	.string "sejere end sidste gang.\p"
	.string "Jeg vil ikke tabe til dig igen.\n"
	.string "Du venter bare til næste gang!\p"
	.string "Vi ses!$"

MatchCall_PersonalizedText43::
	.string "Det er {STR_VAR_1} her.\p"
	.string "Jeg har fortsat med mine studier\n"
	.string "i kunsten at skjule mig.\p"
	.string "Men jeg har været for succesfuld.\n"
	.string "Ingen har været i stand til at finde mig.\l"
	.string "Min succes gør mig ensom…\p"
	.string "Som røg forsvinder jeg!\n"
	.string "Farvel!$"

MatchCall_PersonalizedText44::
	.string "Det her er {STR_VAR_1}.\n" 
	.string "Jeg har holdt mig i træning siden vi mødtes.\p" 
	.string "Min {STR_VAR_2} bliver ret sej.\p" 
	.string "Træning på en strand er effektiv,\n" 
	.string "præcis som jeg troede. Hej hej!$"

MatchCall_PersonalizedText45::
	.string "Hvordan har du det?\n"
	.string "Her er {STR_VAR_1}.\p"
	.string "Jeg spekulerer på, hvornår denne \n"
	.string "klamme vulkanske aske holder op med at\n"
	.string "falde ned?\p"
	.string "Hvis det bliver for dybt, vil det \n"
	.string "dække mønsteret på min parasol…\p"
	.string "Lad os love at mødes igen!$"

MatchCall_PersonalizedText46::
	.string "Hej, {STR_VAR_1} her.\p"
	.string "Vidste du, at det er lettere at\n"
	.string "flyde i havet end i en pool?\p"
	.string "Bare ved at ligge stille vil din\n"
	.string "krop flyde af sig selv.\p"
	.string "Men hvis du flyder for længe,\n"
	.string "så pas på ikke at blive båret for\n"
	.string "langt ud.\p"
	.string "…Hvor er jeg egentlig?\n"
	.string "Jeg må hellere smutte!$"

MatchCall_PersonalizedText47::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det her er {STR_VAR_1}.\l"
	.string "Jeg er oppe i bjergene lige nu.\p"
	.string "Men jorden er alt for ujævn.\n"
	.string "Jeg kan ikke slå mit telt op her…\p"
	.string "Åh, jeg fik en genial idé!\p"
	.string "Måske kan jeg få mine POKéMON til at\n"
	.string "banke jorden flad her!\p"
	.string "Det vil jeg prøve!\n"
	.string "Farvel!$"

MatchCall_PersonalizedText48::
	.string "Hej, hej, det er {STR_VAR_1}!\p"
	.string "Jeg opdrætter POKéMON med LIV!\n"
	.string "Vi arbejder meget hårdt!\p"
	.string "Kan vi blive nummer et hvis vi \n"
	.string "prøver endnu hårdere? Hej hej!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} her!\p"
	.string "Jeg er en SØMAND, men jeg er ikke\n"
	.string "på en båd nu.\p"
	.string "Det får mig til at tænke--hvad\n"
	.string "skal en SØMAND på land kaldes?\p"
	.string "Det har jeg tænkt på\n"
	.string "mens jeg stirrede ud over bølgerne.\p"
	.string "Helt rigtigt, næste gang!$"

MatchCall_PersonalizedText50::
	.string "Det er {STR_VAR_1}.\n"
	.string "Nå? Fangede du flere POKéMON?\p"
	.string "Hvis du fanger en ny POKéMON,\n"
	.string "skal du komme og vise mig.\p"
	.string "Jeg vil ikke tigge om den, ærligt.\n"
	.string "Jeg venter. Vi ses.$"

MatchCall_PersonalizedText51::
	.string "Dette er {STR_VAR_1}.\p"
	.string "Opdrætter du dine POKéMON\n"
	.string "på den optimale måde?\p"
	.string "Luften er ren, hvor jeg er.\n"
	.string "Det er det perfekte miljø for at\l"
	.string "opdrætte POKéMON.\p"
	.string "Hvis du vil fokusere på at opdrætte\n"
	.string "POKéMON, så skulle du tage til\l"
	.string "{STR_VAR_2}. Pas nu godt på.$"

MatchCall_PersonalizedText52::
	.string "Hej, det er {STR_VAR_1}.\p"
	.string "Jeg gav en {POKEBLOCK} til min {STR_VAR_2}.\n"
	.string "Den nød det meget.\p"
	.string "Det ser ud til, at POKéMON har deres\n"
	.string "præferencer med {POKEBLOCK}S.\p"
	.string "Synes du også det er spændende.\n"
	.string "Pas nu godt på.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} her.\p"
	.string "Hvis du samarbejder med POKéMON,\n"
	.string "kan man være tryg i det vilde.\p"
	.string "Alle burde indse det og\n"
	.string "samarbejde mere med POKéMON.\p"
	.string "Det ville være ideelt.\n"
	.string "Det synes jeg virkelig.\p"
	.string "Jeg synes, du er på rette spor!\n"
	.string "Vi ses senere!$"

MatchCall_PersonalizedText54::
	.string "Hej, det er {STR_VAR_1}. Du ved jo,\n"
	.string "TRÆNEREN der altid er forberedt!\p"
	.string "{PLAYER}{KUN}, har du nok genstande?\n"
	.string "Er dine POKéMON klar til kamp?\p"
	.string "At holde alt perfekt omkring dig\n"
	.string "hele tiden er hemmeligheden til\l"
	.string "at fortsætte din rejse.\p"
	.string "Jeg må hellere tjekke mine egne\n"
	.string "forråd! Vær opmærksom!$"

MatchCall_PersonalizedText55::
	.string "Det er {STR_VAR_1}!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "{STR_VAR_2} er en meget travl\n"
	.string "gennemgangsvej, så jeg bliver udfordret\l"
	.string "af alle slags TRÆNERE hver dag.\p"
	.string "I dag vandt jeg fem kampe og tabte\n"
	.string "kun tre!\p"
	.string "Hvordan gik det for dig i dag?\n"
	.string "Fortæl mig om det næste gang, okay?$"

MatchCall_PersonalizedText56::
	.string "Det' mig, {STR_VAR_1}.\p"
	.string "Jeg er populær, fordi jeg har\n"
	.string "en masse BÆST POKéMON, ikke?\p"
	.string "Nå, jeg tog en flok af mine\n"
	.string "yndlingsbæster med i skole i dag.\p"
	.string "Pigen, jeg kan lide, begyndte\n"
	.string "at græde!\p"
	.string "Grin du bare, hvis du vil.\p"
	.string "Jeg bliver nødt til at prøve at\n"
	.string "lære hende, hvad der gør BÆST POKéMON\n"
	.string "så tiltrækkende.\p"
	.string "Snøft…\n"
	.string "Vi ses!$"

MatchCall_PersonalizedText57::
	.string "Hovsa! Hovsa! Hovsa! Hovsa!\p"
	.string "Hej! Det er {STR_VAR_1}! Hovsa! Hovsa!\p"
	.string "Prøver at snakke…\n"
	.string "Mens jeg klatrer…\l"
	.string "Er barsk motion… Hovsa! Hovsa!\p"
	.string "Åh! Av…\n"
	.string "Det er stejlere nu…\l"
	.string "Vi snakker…en anden gang…\l"
	.string "Hovsa! Hovsa! Hovsa!$"

MatchCall_PersonalizedText58::
	.string "Åh, hej!\p"
	.string "Jeg leder stadig efter skatte\n"
	.string "sammen med KIRA!\p"
	.string "Måske er der slet ingen skat\n"
	.string "her…\p"
	.string "Men det vigtigste er, at jeg\n"
	.string "leder sammen med KIRA.\p"
	.string "Åh, hey, KIRA!\n"
	.string "H-hvorfor er du sur?\p"
	.string "Jeg ignorerer dig ikke, skat!\n"
	.string "Du er min eneste ene!\p"
	.string "…{PLAYER}, jeg er nødt til at\n"
	.string "gå, hej!$"

MatchCall_PersonalizedText59::
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg var i DEWFORDs GYM igen\n"
	.string "til træning.\p"
	.string "BRAWLY, GYM LEADEREN, virker\n"
	.string "hårdere nu.\p"
	.string "Noget med at være hærdet\n"
	.string "af de vilde bølger…\p"
	.string "Men han er stadig lige sej.\n"
	.string "Damerne tilbeder ham!\l"
	.string "Det gør mig faktisk misundelig.\p"
	.string "Mon… Er hans ven BRUNO\n"
	.string "på samme måde som BRAWLY?\p"
	.string "Du ved, svedig og lugtende,\n"
	.string "og tilbøjelig til at kalde folk\n"
	.string "“stor bølge,” den slags.\p"
	.string "Men hør her, denne jalousi er\n"
	.string "ikke særlig anstændig, er den?\p"
	.string "Lad os glemme denne snak nogensinde fandt sted,\n"
	.string "hvad siger du? Farvel!$"

MatchCall_PersonalizedText60::
	.string "Det er en fornøjelse at chatte med\n"
	.string "en ung TRÆNER som dig.\p"
	.string "Jeg forestiller mig, at du vil\n"
	.string "fortsætte med at nyde POKéMON\n"
	.string "uanset din alder.\p"
	.string "Ville det ikke være godt, hvis du\n"
	.string "havde et partnerskab ligesom vores?\p"
	.string "Selvfølgelig, {PLAYER}{KUN}, du nyder\n"
	.string "allerede tilliden og selskabet\l"
	.string "af dine POKéMON nu.\p"
	.string "Du besidder allerede\n"
	.string "evnen til langvarige og nære\n"
	.string "forhold!\p"
	.string "Hahaha!\n"
	.string "Vær aldrig modløs!$"

MatchCall_PersonalizedText61::
	.string "Hej, det er {STR_VAR_1}!\n"
	.string "Vi har lige vundet en kamp!\p"
	.string "Vi vinder ikke så tit, men det\n"
	.string "var den seje SVØMMER fyr.\p"
	.string "Min søster var helt vild!\p"
	.string "Hun ville gerne late som om hun\n"
	.string "var svag for at gøre indtryk!\p"
	.string "Hun skælder altid ud på mig\n"
	.string "uanset om vi vinder eller taber!\p"
	.string "{PLAYER}{KUN}, kan du sige noget til\n"
	.string "hende næste gang?\p"
	.string "Okay, vi ses!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} her, ja.\n"
	.string "Jeg sejlede ud på havet i går.\p"
	.string "Jeg havde håbet at finde et\n"
	.string "nyt ruinhjørne at udforske.\p"
	.string "Men strømmene syntes på en\n"
	.string "eller anden måde at bringe mig\n"
	.string "tilbage til udgangspunktet.\p"
	.string "Jeg er stadig svag i kampene...\n"
	.string "Må I endelig grine ad mig…\l"
	.string "Men jeg giver ikke op.\p"
	.string "Min dag vil komme, når jeg\n"
	.string "opdager en ny ruin!\p"
	.string "Det er alt, jeg har at sige!\n"
	.string "Farvel for nu!$"

MatchCall_PersonalizedText63::
	.string "Hej med dig!\n"
	.string "Det er mig, {STR_VAR_1}!\l"
	.string "Jeg er på RUTE 108 nu!\l"
	.string "Med andre ord, hvor jeg altid er!\p"
	.string "I dag svømmede en fantastisk\n"
	.string "SVØMMER forbi mig!\p"
	.string "Så jeg forskrækkede hende med et råb!\p"
	.string "Og hun gav mig et trættende blik!\p"
	.string "Det er alt fra RUTE 108!\n"
	.string "Præsenteret af {STR_VAR_1}!$"

MatchCall_PersonalizedText64::  
	.string "Det er {STR_VAR_1}!\p"  
	.string "Jeg er lidt optaget, men jeg\n"  
	.string "tænkte, at jeg burde fortælle dig,\l"  
	.string "at jeg har slået fem TRÆNERE igen i dag.\p"  
	.string "Hvis jeg holder dette tempo, kan jeg\n"  
	.string "sandsynligvis slå dig næste gang.\p"  
	.string "Jeg tror, vi bliver gode rivaler,\n"  
	.string "du og jeg. Farvel for nu!$"

  MatchCall_BattleFrontierStreakText1::
	.string "Hej! Det er {STR_VAR_1}.\n"
	.string "Jeg har hørt nyhederne!\p"
	.string "De siger, at du gjorde det\n"
	.string "fremragende ved {STR_VAR_2}.\p"
	.string "Det er fantastisk, {STR_VAR_3} lige\n"
	.string "sejre? Vi ses!$"

MatchCall_BattleFrontierStreakText2::
	.string "Hej, det er {STR_VAR_1}!\n"
	.string "Jeg har hørt om dig!\p"
	.string "De sagde, at du vandt {STR_VAR_3}\n"
	.string "på stribe kampe ved {STR_VAR_2}.\p"
	.string "Det er specielt! Jeg burde også\n"
	.string "prøve hårdere! Vi ses!$"

MatchCall_BattleFrontierStreakText3::
	.string "Hej der, {PLAYER}!\n"
	.string "Det er mig, {STR_VAR_1}.\p"
	.string "Jeg hørte, at du har været en stjerne\n"
	.string "i {STR_VAR_2}!\p"
	.string "En stor {STR_VAR_3}-vindende\nstreak…\n"
	.string "Det er da en imponerende rekord, ikk'?\p"
	.string "Jeg bliver nødt til at skærpe mig!\n"
	.string "Vi ses snart!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her. Hvad så?\p"
	.string "Der går et rygte om, at du har\n"
	.string "hevet {STR_VAR_3} sejre i træk hjem\n"
	.string "på {STR_VAR_2}.\p"
	.string "Jeg bliver nok nødt til også at\n"
	.string "skærpe mig. Vi ses!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hej med dig, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Du var ved {STR_VAR_2}\n"
	.string "og vandt {STR_VAR_3} kampe i træk?\l"
	.string "Er det ikke noget!\p"
	.string "Jeg bliver nødt til at arbejde mere med mine POKéMON.\n"
	.string "Vi ses snart!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her. Hvordan har du det?\p"
	.string "Forresten, jeg hørte, at du\n"
	.string "opnåede {STR_VAR_3} lige sejre på\n"
	.string "{STR_VAR_2}.\p"
	.string "Det inspirerer mig til at fokusere\n"
	.string "på at opgradere mit hold.$"

MatchCall_BattleFrontierStreakText7::
    .string "…Øh, {PLAYER}{KUN}?\n"
    .string "{STR_VAR_1} her…\p"
    .string "Åh ja, du var henne ved\n"
    .string "{STR_VAR_2}, ikke sandt?\p"
    .string "Og du vandt {STR_VAR_3} kampe i træk.\p"
    .string "Åh, der går en sjælden POKéMON!\n"
    .string "Jeg er nødt til at gå!$"

MatchCall_BattleFrontierStreakText8::
	.string "Åh, {PLAYER}{KUN}, hvordan har du det?\n"
	.string "Det er {STR_VAR_1} der taler.\l"
	.string "Jeg håber, du har det godt.\p"
	.string "Åh, men det har du. Jeg har hørt\n"
	.string "at du har vundet {STR_VAR_3} kampe i træk på\l"
	.string "{STR_VAR_2}.\p"
	.string "Det er meget imponerende!\n"
	.string "Jeg håber, du forbliver succesfuld.$"

MatchCall_BattleFrontierStreakText9::
	.string "Åh, {PLAYER}{KUN}, hej!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg hørte det! Din {STR_VAR_3}-vind-stime på\n"
	.string "{STR_VAR_2}!\p"
	.string "Det er så sejt!\n"
	.string "Jeg bliver nødt til at anstrenge mig mere også!$"

MatchCall_BattleFrontierStreakText10::
	.string "Hej, {PLAYER}{KUN}…\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Du vandt {STR_VAR_3} kampe i træk på\n"
	.string "{STR_VAR_2}?\p"
	.string "Det er virkelig en præstation.\n"
	.string "Jeg bliver nødt til at arbejde hårdere.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Dette er {STR_VAR_1}.\p"
	.string "Jeg har hørt, at du er skrækken\n"
	.string "fra {STR_VAR_2}?\p"
	.string "Du vandt, hvad, {STR_VAR_3} kampe i\n"
	.string "træk?\p"
	.string "Du er god, dig.\n"
	.string "Jeg spekulerer på, hvor mange jeg\n"
	.string "kan vinde?$"

MatchCall_BattleFrontierStreakText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Har du det godt?\p"
	.string "Nogen har fortalt mig om dig.\n"
	.string "Hvordan du vandt {STR_VAR_3} på stribe\l"
	.string "i et sted kaldet {STR_VAR_2}?\p"
	.string "Det er en historie værd at høre.\n"
	.string "Vi ses!$"

MatchCall_BattleFrontierStreakText13::
	.string "Nå, hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\l"
	.string "Jeg håber, du har det godt.\p"
	.string "De siger, du har vundet {STR_VAR_3}\n"
	.string "rette kampe ved {STR_VAR_2}.\p"
	.string "Jeg beundrer dit energiniveau!\n"
	.string "Hej så.$"

  MatchCall_BattleFrontierStreakText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg har hørt om dig!\n"
	.string "Vandt du ikke lige {STR_VAR_3} kampe i\n"
	.string "{STR_VAR_2} i træk?\p"
	.string "Du er en inspiration!\n"
	.string "Hej-hej!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hej! Det er {STR_VAR_1}.\n"
	.string "Jeg hørte nyheden!\p"
	.string "De siger, at du gjorde fremragende\n"
	.string "på {STR_VAR_2}.\p"
	.string "Det er fantastisk - {STR_VAR_3} lige sejre?\n"
	.string "Vi ses!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hej, det er {STR_VAR_1}!\n"
	.string "Jeg har hørt om dig!\p"
	.string "De sagde, at du vandt {STR_VAR_3} på række\n"
	.string "kampe ved {STR_VAR_2}.\p"
	.string "Det er særligt! Jeg bør også\n"
	.string "prøve hårdere! Vi ses!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hej med dig, {PLAYER}!\n"
	.string "Det er mig, {STR_VAR_1}.\p"
	.string "Jeg hørte, at du har været\n"
	.string "ret vild på {STR_VAR_2}-banen!\p"
	.string "En stor {STR_VAR_3}-sejr-stime…\n"
	.string "Det er et stort rekord, ikk' det?\p"
	.string "Jeg må hellere få styr på mit spil!\n"
	.string "Vi ses snart!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hey, {PLAYER}!\n"
	.string "{STR_VAR_1} here. Hvad så?\p"
	.string "Der går et rygte om, at du har\n"
	.string "vundet {STR_VAR_3} kampe i træk på\n"
	.string "{STR_VAR_2}.\p"
	.string "Nu må jeg også skærpe mig.\n"
	.string "Vi ses!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Var du på {STR_VAR_2}\n"
	.string "og vandt {STR_VAR_3} kampe i træk?\l"
	.string "Er det ikke noget!\p"
	.string "Mig? Jeg vil sige, at jeg er på vej frem.\n"
	.string "Vi ses snart!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hej {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her. Hvordan har du det?\p"
	.string "Forresten hørte jeg, at du formåede\n"
	.string "at vinde {STR_VAR_3} gange i træk hos\l"
	.string "{STR_VAR_2}.\p"
	.string "Jeg bliver nødt til at anstrenge mig mere!\n"
	.string "Vi ses snart!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Øh, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} her…\p"
	.string "Nå ja, du var ovre på\n"
	.string "{STR_VAR_2}, ikke?\p"
	.string "Og du vandt {STR_VAR_3} kampe i træk.\p"
	.string "Åh, der går en sjælden POKéMON!\n"
	.string "Jeg bliver nødt til at gå!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Åh, {PLAYER}{KUN}, hvordan har du det?\n"
	.string "Det er {STR_VAR_1}, der taler.\l"
	.string "Jeg håber, du har det godt.\p"
	.string "Åh, men det har du. Jeg har hørt, at\n"
	.string "du har vundet {STR_VAR_3} kampe i træk på\l"
	.string "{STR_VAR_2}.\p"
	.string "Det er meget imponerende!\n"
	.string "Jeg bliver nødt til at arbejde på mine POKéMON også!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg hørte, din {STR_VAR_3}-sejr-række på\n"
	.string "{STR_VAR_2}!\p"
	.string "Det er så sejt!\n"
	.string "Jeg må hellere prøve hårdere også!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Åh, {PLAYER}{KUN}, hej…\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Du har vundet {STR_VAR_3} på stribe\n"
	.string "ved {STR_VAR_2}?\p"
	.string "Det er virkelig en præstation.\n"
	.string "Jeg bliver nødt til at arbejde hårdere.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Åh, {PLAYER}{KUN}.\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg har hørt, at du er skrækken\n"
	.string "fra {STR_VAR_2}.\p"
	.string "Du har vundet, hvad, {STR_VAR_3} kampe\n"
	.string "i træk?\p"
	.string "Du er god, dig.\n"
	.string "Jeg undrer mig på, hvor mange jeg\n"
	.string "kan vinde?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Har du det godt?\p"
	.string "Nogen sendte besked om dig.\n"
	.string "Hvordan du vandt {STR_VAR_3} på stribe\l"
	.string "ved et sted kaldet {STR_VAR_2}?\p"
	.string "Det er en ganske historie.\n"
	.string "Vi ses!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\l"
	.string "Jeg håber, du har det godt.\p"
	.string "De siger, at du har vundet\n"
	.string "{STR_VAR_3} kampe i træk på\n"
	.string "{STR_VAR_2}.\p"
	.string "Jeg beundrer dit energiniveau!\n"
	.string "Hej da.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det her er {STR_VAR_1}.\l"
	.string "Jeg har hørt om dig!\p"
	.string "Vandt du ikke lige {STR_VAR_3} kampe i\n"
	.string "træk på {STR_VAR_2}?\p"
	.string "Du er en inspiration!\n"
	.string "Hej-hej!$"

MatchCall_BattleDomeText1::
	.string "Hej! {PLAYER}?\n"
	.string "Hej, det er {STR_VAR_1}!\l"
	.string "Jeg hørte nyhederne!\p"
	.string "Du blev mester hos\n"
	.string "{STR_VAR_2} {STR_VAR_3} gange?\p"
	.string "Det er fantastisk! Jeg bliver nødt til\n"
	.string "at gøre det bedre!\n"
	.string "Vi ses!$"

MatchCall_BattleDomeText2::
	.string "Hej, det er {STR_VAR_1}!\n"
	.string "Jeg har hørt om dig!\p"
	.string "De sagde, at du har vundet {STR_VAR_3}\n"
	.string "titler på {STR_VAR_2}.\p"
	.string "Det er super! Jeg spekulerer på, om\n"
	.string "jeg kan blive en mester?$"

MatchCall_BattleDomeText3::
	.string "Hej {PLAYER}!\n"
	.string "Det' mig, {STR_VAR_1}.\l"
	.string "Skærer det sig?\p"
	.string "Jeg har hørt, du vandt events {STR_VAR_3} gange\n"
	.string "på {STR_VAR_2}!\p"
	.string "Gør det en mere næste gang!\n"
	.string "Vi ses snart!$"

MatchCall_BattleDomeText4::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Jeg hørte, at du blev mesteren\n"
	.string "ved {STR_VAR_2} {STR_VAR_3} gange.\p"
	.string "Det lyder som om, at du arbejder\n"
	.string "hårdt. Jeg vil prøve at følge med!$"

MatchCall_BattleDomeText5::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg hørte, du har vundet {STR_VAR_3} gange\n"
	.string "i træk i {STR_VAR_2}.\p"
	.string "Jeg må hellere komme op at snuse!\n"
	.string "Vi ses snart!$"

MatchCall_BattleDomeText6::
	.string "Hej, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} her. Hvordan har du det?\p"
	.string "Forresten, jeg hørte, at du blev\n"
	.string "mester {STR_VAR_3} gange på\l"
	.string "{STR_VAR_2}.\p"
	.string "Jeg må nok træne mine POKéMON lidt\n"
	.string "mere, før du kommer foran.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} her.\p"
	.string "Var du på {STR_VAR_2}\n"
	.string "og blev mester {STR_VAR_3} gange?\p"
	.string "Det er smart. Forresten, har du\n"
	.string "fanget nogle sjældne POKéMON for nylig?\p"
	.string "Åh, er det rigtigt.\n"
	.string "Okay, hej.$"

MatchCall_BattleDomeText8::
	.string "Åh, {PLAYER}{KUN}, hvordan går det?\n"
	.string "Det er {STR_VAR_1}, der taler.\l"
	.string "Håber, du har det godt.\l"
	.string "Åh, men det har du.\p"
	.string "Jeg har hørt, at du har vundet {STR_VAR_3} titler\n"
	.string "på {STR_VAR_2}.\p"
	.string "Jeg bliver nødt til at opdrage\n"
	.string "mine POKéMON som dig.\n"
	.string "Vi ses igen.$"

MatchCall_BattleDomeText9::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg hørte, at du har vundet titlen\n"
	.string "{STR_VAR_3} gange ved {STR_VAR_2}!\p"
	.string "Hvor sejt!\n"
	.string "Jeg bliver nødt til at prøve hårdere også!$"

MatchCall_BattleDomeText10::
	.string "Hej, {PLAYER}{KUN}, hej.\n"
	.string "Det her er {STR_VAR_1}.\p"
	.string "Du har vundet {STR_VAR_3} gange i\n"
	.string "{STR_VAR_2}?\p"
	.string "Det er en imponerende præstation.\n"
	.string "Jeg skal arbejde hårdere.$"

MatchCall_BattleDomeText11::
	.string "Åh, {PLAYER}{KUN}.\n"
	.string "Dette er {STR_VAR_1}.\p"
	.string "Jeg hører, du er skrækken\n"
	.string "af {STR_VAR_2}?\p"
	.string "Du har vundet, hvad, {STR_VAR_3}\n"
	.string "gange i træk nu?\p"
	.string "Jeg undrer mig over, om jeg nogensinde\n"
	.string "kan blive mester?\p"
	.string "…Ret umuligt, ikke?\n"
	.string "Nå, vi ses!$"

MatchCall_BattleDomeText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Har du det godt?\p"
	.string "Du har vundet {STR_VAR_3} begivenheder\n"
	.string "på et sted ved navn {STR_VAR_2}?\p"
	.string "Det er helt vildt.\n"
	.string "Vi ses!$"

MatchCall_BattleDomeText13::
	.string "Åh, hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\l"
	.string "Jeg håber, du har det godt.\p"
	.string "De siger, du har vundet {STR_VAR_3}\n"
	.string "begivenheder på {STR_VAR_2}?\p"
	.string "Jeg beundrer din energi!\n"
	.string "Hej hej.$"

MatchCall_BattleDomeText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Dette er {STR_VAR_1}.\l"
	.string "Jeg har hørt om dig!\p"
	.string "Vandt du ikke {STR_VAR_3} titler\n"
	.string "på {STR_VAR_2}?\p"
	.string "Du er en inspiration!\n"
	.string "Vi ses igen!$"

MatchCall_BattlePikeText1::
	.string "Hej! {PLAYER}?\n"
	.string "Hej, det er {STR_VAR_1}!\l"
	.string "Jeg hørte nyhederne!\p"
	.string "Du kom igennem {STR_VAR_3} rum\n"
	.string "på {STR_VAR_2}!\p"
	.string "Det er imponerende!\n"
	.string "Vi ses!$"

MatchCall_BattlePikeText2::
	.string "Hej, det er {STR_VAR_1}!\n"
	.string "Jeg har hørt om dig!\p"
	.string "De sagde, at du vandt dig vej gennem\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}.\p"
	.string "Jeg bliver nødt til at gøre en større indsats!\n"
	.string "Hej-hej!$"

MatchCall_BattlePikeText3::
	.string "Hej med dig, {PLAYER}!\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Hvordan går det?\p"
	.string "Jeg hørte, at du vandt gennem {STR_VAR_3} rum\n"
	.string "på {STR_VAR_2}!\p"
	.string "Prøv at gøre det endnu bedre næste gang!\n"
	.string "Vi ses snart!$"

MatchCall_BattlePikeText4::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Jeg hørte, at du har klaret dig igennem {STR_VAR_3} rum\n"
	.string "på {STR_VAR_2}.\p"
	.string "Jeg vil nok hellere træne mine POKéMON og\n"
	.string "prøve at følge med!$"

MatchCall_BattlePikeText5::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg hørte, at du kom forbi {STR_VAR_3} rum\n"
	.string "på {STR_VAR_2}.\p"
	.string "Jeg burde også komme i gang!\n"
	.string "Vi ses snart!$"

MatchCall_BattlePikeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} her. Hvordan har du det?\p"
	.string "Forresten, jeg hørte, at du klarede\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}.\p"
	.string "Jeg må nok træne mine POKéMON\n"
	.string "lidt, før du trækker for langt fra.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} her.\p"
	.string "Var du ved {STR_VAR_2}\n"
	.string "og vandt dig vej forbi {STR_VAR_3} rum?\p"
	.string "Det er vildt.\p"
	.string "Åh, der går en sjælden POKéMON!\n"
	.string "Okay, hej.$"

MatchCall_BattlePikeText8::
	.string "Hej, {PLAYER}{KUN}, hvordan har du det?\n"
	.string "Det er {STR_VAR_1}, der taler.\l"
	.string "Jeg håber, at du har det godt.\l"
	.string "Det har du jo.\p"
	.string "Jeg har hørt, at du klarede\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}.\p"
	.string "Det er ret imponerende!\n"
	.string "Jeg bliver nødt til at træne\n"
	.string "mine POKéMON som dig.\l"
	.string "Vi ses igen.$"

MatchCall_BattlePikeText9::
	.string "Hej, {PLAYER}{KUN}, hej!\n"
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg hørte! Du vandt dig vej gennem\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}!\p"
	.string "Det er så sejt!\n"
	.string "Jeg må hellere prøve hårdere selv!$"

MatchCall_BattlePikeText10::
	.string "Hej {PLAYER}{KUN}.\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Du vandt dig vej forbi {STR_VAR_3} rum\n"
	.string "på {STR_VAR_2}?\p"
	.string "Det er en stor præstation.\n"
	.string "Jeg bliver nødt til at arbejde hårdere.$"

MatchCall_BattlePikeText11::
	.string "Nå, {PLAYER}{KUN}.\n"
	.string "Jeg er {STR_VAR_1}.\p"
	.string "Hører jeg, at du er skrækken\n"
	.string "i {STR_VAR_2}?\p"
	.string "Du klarede hvad, {STR_VAR_3} rum?\n"
	.string "Det må da tælle for noget.\p"
	.string "Mon jeg nogensinde kan blive\n"
	.string "mester?\p"
	.string "…Temmelig umuligt?\n"
	.string "Nå, ses!$"

MatchCall_BattlePikeText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Har du det godt?\p"
	.string "Du har vundet igennem {STR_VAR_3} rum på\n"
	.string "et sted ved navn {STR_VAR_2}?\p"
	.string "Det er en temmelig vild historie.\n"
	.string "Vi ses!$"

MatchCall_BattlePikeText13:: 
	.string "Åh, hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\l"
	.string "Jeg håber, du har det godt.\p"
	.string "De siger, du har vundet i {STR_VAR_3}\n"
	.string "rum på {STR_VAR_2}?\p"
	.string "Jeg beundrer din energi!\n"
	.string "Hej så.$"

MatchCall_BattlePikeText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det her er {STR_VAR_1}.\l"
	.string "Jeg har hørt om dig!\p"
	.string "Kom du ikke igennem {STR_VAR_3} rum\n"
	.string "i {STR_VAR_2}?\p"
	.string "Du er en inspiration!\n"
	.string "Vi ses igen!$"

MatchCall_BattlePyramidText1::
	.string "Hej! {PLAYER}?\n"
	.string "Hej, det er {STR_VAR_1}!\l"
	.string "Jeg har hørt nyheden!\p"
	.string "Du har besteget {STR_VAR_3} etager\n"
	.string "i {STR_VAR_2}, ikke sandt?\p"
	.string "Det er fantastisk!\n"
	.string "Jeg burde prøve den udfordring.$"

MatchCall_BattlePyramidText2::
	.string "Hej, det er {STR_VAR_1}!\n"
	.string "Jeg har hørt om dig!\p"
	.string "De sagde, at du vandt dig gennem\n"
	.string "{STR_VAR_3} etager i {STR_VAR_2}.\p"
	.string "Wow, det er fantastisk!\n"
	.string "Jeg må hellere træne mine POKéMON også!$"

MatchCall_BattlePyramidText3::
	.string "Hej {PLAYER}!\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Hvordan går det?\p"
	.string "Jeg hørte, at du nåede {STR_VAR_3} etager\n"
	.string "i {STR_VAR_2}!\p"
	.string "Prøv at gøre det endnu bedre næste gang!\n"
	.string "Vi ses snart!$"

MatchCall_BattlePyramidText4::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} her.\p"
	.string "Jeg hørte, at du besteg {STR_VAR_3}\n"
	.string "etager i {STR_VAR_2}.\p"
	.string "Jeg burde nok arbejde hårdt og prøve\n"
	.string "at følge med!$"

MatchCall_BattlePyramidText5::
	.string "Hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg hørte, at du klatrede {STR_VAR_3} etager\n"
	.string "i {STR_VAR_2}.\p"
	.string "Jeg må nok også i gang!\n"
	.string "Vi ses snart!$"

MatchCall_BattlePyramidText6::
	.string "Hej, {PLAYER}! \n"
	.string "{STR_VAR_1} her. Hvordan har du det?\p"
	.string "Forresten, jeg hørte, at du kom\n"
	.string "igennem {STR_VAR_3} etager i {STR_VAR_2}.\p"
	.string "Jeg burde nok træne mine POKéMON\n"
	.string "lidt, inden du løber fra mig.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} her.\p"
	.string "Var du ved {STR_VAR_2}\n"
	.string "og vandt dig op {STR_VAR_3} etager?\p"
	.string "Fedt. Var der nogen sjældne POKéMON\n"
	.string "der?\p"
	.string "Nej, hva?\n"
	.string "Okay, hej.$"

MatchCall_BattlePyramidText8::
	.string "Åh, {PLAYER}{KUN}, hvordan går det?\n"
	.string "Her er det {STR_VAR_1}, der taler.\l"
	.string "Jeg håber, at du har det godt.\l"
	.string "Åh, men det har du.\p"
	.string "Jeg har hørt, at du klarede\n"
	.string "{STR_VAR_3} etager i {STR_VAR_2}.\p"
	.string "Det er ret imponerende!\n"
	.string "Jeg må hæve mine POKéMON som dig.\l"
	.string "Vi ses igen.$"

MatchCall_BattlePyramidText9::
	.string "Åh, {PLAYER}{KUN}, hej der!\n"
	.string "Det her er {STR_VAR_1}!\p"
	.string "Jeg hørte det! Du vandt dig vej gennem\n"
	.string "{STR_VAR_3} gulve i {STR_VAR_2}!\p"
	.string "Det er så sejt!\n"
	.string "Jeg må nok også prøve hårdere!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hej.\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Du klatrede {STR_VAR_3} etager inde\n"
	.string "i {STR_VAR_2}?\p"
	.string "Det er en imponerende præstation.\n"
	.string "Jeg bliver nødt til at arbejde hårdere.$"

MatchCall_BattlePyramidText11::
	.string "Åh, {PLAYER}{KUN}.\n"
	.string "Dette er {STR_VAR_1}.\p"
	.string "Jeg hører, at du er skrækken\n"
	.string "fra {STR_VAR_2}?\p"
	.string "Du steg gennem, hvad, {STR_VAR_3} gulve?\n"
	.string "Det må tælle for noget.\p"
	.string "Jeg spekulerer på, om jeg nogensinde\n"
	.string "kan blive en mester?\p"
	.string "…Ret umuligt?\n"
	.string "Nå, vi ses!$"

MatchCall_BattlePyramidText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Har du det godt?\p"
	.string "Du har vundet igennem {STR_VAR_3}\n"
	.string "etager i et sted kaldet {STR_VAR_2}?\p"
	.string "Det er da en historie.\n"
	.string "Vi ses!$"

MatchCall_BattlePyramidText13::
	.string "Nå, hej, {PLAYER}{KUN}!\n"
	.string "Det her er {STR_VAR_1}!\l"
	.string "Håber du har haft det godt.\p"
	.string "Sig mig, har du besteget {STR_VAR_3} etager\n"
	.string "i {STR_VAR_2}?\p"
	.string "Jeg beundrer din energi!\n"
	.string "Hej for nu.$"

MatchCall_BattlePyramidText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Jeg er {STR_VAR_1}.\l"
	.string "Jeg har hørt om dig!\p"
	.string "Kommer du ikke igennem {STR_VAR_3} etager\n"
	.string "i {STR_VAR_2}?\p"
	.string "Du er en inspiration!\n"
	.string "Vi ses igen!$"

MatchCall_Text_Mom1::
	.string "MOR: Din far og dig…\n"
	.string "Alle er betaget af POKéMON.\p"
	.string "Hvad er charmen ved POKéMON?\p"
	.string "Mig?\n"
	.string "Jeg forguder POKéMON, der hjælper\n"
	.string "mig med mine daglige pligter.$"

MatchCall_Text_Mom2::
	.string "MOR: Hej, {PLAYER}!\n"
	.string "Din far holder sig låst inde\n"
	.string "i PETALBURG GYM.\p"
	.string "Han kommer hjem en gang imellem.\n"
	.string "Men han går tilbage til GYMet,\n"
	.string "når han har spist alt, han kan.\p"
	.string "Jeg gætter på, at det at tabe til dig\n"
	.string "var et stort slag mod hans stolthed!$"

MatchCall_Text_Mom3::
	.string "MOR: {PLAYER}…\n"
	.string "Bare rolig med mig eller huset.\p"
	.string "Brug de LØBESKO indtil\n"
	.string "de falder fra hinanden, skat!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Åh hej, {PLAYER}!\p"
	.string "Jeg har knoklet hårdt med træningen\n"
	.string "siden vi mødtes.\p"
	.string "Jeg har stadig brug for lidt\n"
	.string "mere tid, før jeg kan genåbne GYMen.\p"
	.string "Men når jeg gør det, så kom og besøg\n"
	.string "min GYM for en revanche!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Er det dig, {PLAYER}?\n"
	.string "Tillykke!\l"
	.string "Jeg har hørt om dig!\p"
	.string "Hvad mig angår, har jeg brug for\n"
	.string "lidt mere tid, før jeg kan åbne GYM'et.\p"
	.string "Men når jeg gør, så besøg min GYM\n"
	.string "for en revanche!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "Min GYM er klar!\p"
	.string "Besøg RUSTBORO,\n"
	.string "når du kan!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: På RUSTBORO GYM,\n"
	.string "det faktum, at vi kæmpede, {PLAYER},\l"
	.string "er en sag om stolthed.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hej {PLAYER}{KUN}!\p"
	.string "Jeg lærte en masse af kampen, vi\n"
	.string "havde sammen.\p"
	.string "Jeg har tænkt mig at træne lidt\n"
	.string "mere og derefter genåbne GYMMET.\p"
	.string "Der går lidt tid, før jeg er klar til\n"
	.string "at drive GYMMET igen.\p"
	.string "Men hvis jeg genåbner GYMMET,\n"
	.string "vil jeg have dig til at udfordre os igen.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hej, {PLAYER}{KUN}!\n"
	.string "Tillykke!\p"
	.string "Ordet om dine bedrifter nåede\n"
	.string "mig på tidevindsstrømme!\p"
	.string "Det ser ud til, at jeg skal arbejde\n"
	.string "mere på min træning.\p"
	.string "Det vil tage lidt tid, før jeg er\n"
	.string "klar til at drive GYMMET igen.\p"
	.string "Men hvis jeg kan genåbne GYMMET,\n"
	.string "vil jeg have dig til at udfordre os igen.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Min GYM er klar til aktion!\p"
	.string "Kom tilbage til DEWFORD når som\n"
	.string "helst for endnu en udfordring!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}, jeg tror ikke\n"
	.string "jeg nogensinde bliver træt af\n"
	.string "at kæmpe mod dig!\p$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Åh, det er dig!\p"
	.string "Efter du gik, har jeg genstartet\n"
	.string "min træning fra bunden.\p"
	.string "Jeg vil sige, jeg kunne bruge lidt\n"
	.string "mere tid til at genåbne min GYM.\p"
	.string "Du bliver nødt til at vente til da!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "Du har virkelig gjort det, har du ikke?\n"
	.string "Jeg har hørt om dig!\p"
	.string "Det virker til, at jeg skal træne\n"
	.string "endnu mere.\p"
	.string "Jeg vil sige, at jeg skal bruge lidt\n"
	.string "mere tid til at genåbne mit GYM.\p"
	.string "Du må vente indtil da!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Åh, det er dig!\n"
	.string "Mit GYM er klar!\p"
	.string "Besøg MAUVILLE når som helst!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "Et slag med dig er altid fyldt med\n"
	.string "elektrisk kraft!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "Da vi kæmpede, lærte jeg præcist\n"
	.string "hvor umoden jeg var.\p"
	.string "Men jeg er ikke færdig endnu!\p"
	.string "Jeg vil genoptage min træning og\n"
	.string "genåbne GYMMEN.\p"
	.string "Når tiden kommer, {PLAYER},\n"
	.string "udfordre os gerne igen.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Hej, {PLAYER}?\n"
	.string "Tillykke!\p"
	.string "Ordet om din succes har nået\n"
	.string "os som varmen fra en vulkan!\p"
	.string "Vores træning går rigtig godt her.\p"
	.string "Når GYM'et er klar, vil der\n"
	.string "komme et mærke ved siden af mit\n"
	.string "navn på MATCH CALL-listen.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Åh, {PLAYER}?\n"
	.string "Vores GYM er klar!\p"
	.string "Kom til LAVARIDGE og få en\n"
	.string "tur i varme kilder samt en udfordring!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "Jeg er sikker på, at du bliver\l"
	.string "bedre til træning hver gang.$"

MatchCall_Text_Winona1::
	.string "WINONA: Hej, {PLAYER}!\p"
	.string "Takket være vores kamp, er jeg blevet\n"
	.string "opmærksom på mine svage punkter!\p"
	.string "Når jeg genåbner GYMen, vil jeg ikke\n"
	.string "lade mig slå ud igen!$"

MatchCall_Text_Winona2::
	.string "WINONA: Du gjorde det, {PLAYER}!\p"
	.string "Nyheder om den nye MESTER\n"
	.string "har nået os i FORTREE!\p"
	.string "Men... Næste gang vi kæmper,\n"
	.string "kommer det ikke til at ende på\n"
	.string "samme måde.$"

MatchCall_Text_Winona3::
	.string "WINONA: Er det her {PLAYER}?\n"
	.string "Vores GYM er tilbage i drift!\p"
	.string "Vi venter på dig i FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Selvom jeg har tabt, vil mine vinger\n"
	.string "aldrig brække.\p"
	.string "Ja, præcis på samme måde som du\n"
	.string "aldrig mistede synet af din drøm.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Åh! Du er...\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Vi træner igen...\n"
	.string "LIZA: Så vi kan genåbne vores GYM!\p"
	.string "TATE: Når vores GYM er klar...\n"
	.string "LIZA: Når vores GYM er klar...\p"
	.string "TATE: En markering vil dukke op ved vores navn...\n"
	.string "LIZA: På MATCH CALL-listen.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, tillykke!\n"
	.string "LIZA: {PLAYER}, tillykke!\p"
	.string "TATE: Vi to er...\n"
	.string "LIZA: stadig i træning!\p"
	.string "TATE: Vi skal bruge lidt mere tid, men...\n"
	.string "LIZA: Når vores GYM er klar...\p"
	.string "TATE: Der vil komme et mærke ved vores navn...\n"
	.string "LIZA: På MATCH CALL-listen.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Vores GYM er klar!\n"
	.string "LIZA: Vores GYM er klar!\p"
	.string "TATE: Kom og besøg os...\n"
	.string "LIZA: I MOSSDEEP når du vil!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, kampen vi havde... \n"
	.string "LIZA: Er en uvurderlig oplevelse.\p"
	.string "TATE: Det ville være dejligt hvis... \n"
	.string "LIZA: Vi alle kunne kæmpe igen!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}, was det ikke?\p"
	.string "Vores kamp sammen--den bragte\n"
	.string "minder frem hos mig om dengang\n"
	.string "jeg først mødte WALLACE.\p"
	.string "Måske er du et geni, der kan\n"
	.string "overgå WALLACE endnu!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu... {PLAYER}{KUN}...\n"
	.string "Du har endelig nået dit mål.\p"
	.string "Mit øje for at vurdere talent var\n"
	.string "ikke fejlagtigt...\p"
	.string "Jeg ønsker for en anden chance for\n"
	.string "at møde dig, for du har besteget\n"
	.string "toppen af magt og prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho... {PLAYER}gerne...\p"
	.string "Vores SOOTOPOLIS GYM har endelig\n"
	.string "åbnet igen.\p"
	.string "Hvis du ønsker at besøge mig,\n"
	.string "er du velkommen når som helst.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Som den fineste musik, de kampe\n"
	.string "vi udkæmper sammen, slår toner\n"
	.string "af inspiration i mit hjerte…\p"
	.string "Når jeg lukker mine øjne, ser jeg\n"
	.string "visioner af dig svævende med melodien…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Hej, {PLAYER}!\p"
	.string "Hvis du vil kæmpe mod mig igen,\n"
	.string "så kom bare tilbage når som\n"
	.string "helst til POKéMON-LIGAEN.\p"
	.string "Jeg vil altid være her!\n"
	.string "Jeg venter på dig!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Hej, {PLAYER}!\p"
	.string "Hvad med at komme tilbage hertil på\n"
	.string "et tidspunkt?\p"
	.string "Jeg vil gerne se, hvor meget\l"
	.string "dit bånd er vokset med dine\n"
	.string "POKéMON.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Hej, {PLAYER}.\p"
	.string "Jeg håber, at du ikke er blevet\n"
	.string "selvtilfreds med din styrke?\p"
	.string "Hvis du føler behov for at\n"
	.string "køle lidt af på dine varme\n"
	.string "følelser, så kom endelig\l"
	.string "til POKéMON LIGAEN…$"

MatchCall_Text_Drake::
    .string "DRAKE: Den stemme… {PLAYER}, er det dig?\n"
    .string "Du lyder godt…\p"
    .string "Jeg har hørt, at der nu findes\n"
    .string "en facilitet kaldet BATTLE\l"
    .string "FRONTIER, der tester TRÆNERNES\l"
    .string "færdigheder.\p"
    .string "Men hvis du vil have rigtige\n"
    .string "kampe, er der intet der kan\l"
    .string "erstatte POKéMON LIGAEN!\p"
    .string "Er du ikke enig, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Hej, {PLAYER}{KUN}.\n"
	.string "Har du mødt Steven?\p"
	.string "Han er...\n"
	.string "Faktisk utroligt dygtig.\p"
	.string "Men han er en mærkelig sjæl, der\n"
	.string "sjældent kæmper.\p"
	.string "I stedet vil han hellere lede efter\n"
	.string "sjældne sten.\p"
	.string "Jeg er sikker på, at han graver i\n"
	.string "en hule eller et stejlt bjerg et\n"
	.string "eller andet sted.\p"
	.string "Men hvad er en sjælden sten\n"
	.string "egentlig?\n"
	.string "Alt hvad jeg kan tænke på er en\n"
	.string "meteorit...$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Jeg var lige i PACIFIDLOGBYT\n"
	.string "for lidt siden.\p"
	.string "Jeg så en kæmpestor grøn\n"
	.string "POKéMON flyve højt oppe i\n"
	.string "himlen.\p"
	.string "Jeg...\n"
	.string "Jeg har aldrig set noget lignende.\p"
	.string "Jeg undrer mig over, hvad det var.\n"
	.string "Er det måske en stor opdagelse?\p"
	.string "… … … … … …\n"
	.string "… … … … … Klik!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip!\p"
	.string "BRENDAN: Hej, {PLAYER}!\n"
	.string "Jeg var lige i PACIFIDLOG.\p"
	.string "Jeg så denne kæmpestore grønne\n"
	.string "POKéMON flyve over himlen.\p"
	.string "Jeg har aldrig set noget så\n"
	.string "fantastisk før.\p"
	.string "Jeg ville ønske, du kunne have\n"
	.string "set det, {PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Klik!$"

MatchCall_Text_May1::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY gik på pension som\n"
	.string "SØMAND, men jeg ser ham stadig ude\n"
	.string "på havet med hans kæledyr PEEKO\n"
	.string "engang imellem.\p"
	.string "Han må stadig elske havet.$"

MatchCall_Text_May2::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Ved du, hvordan små byer som\n"
	.string "PETALBURG og DEWFORD har GYMS?\p"
	.string "Af en eller anden grund har den store\n"
	.string "havn i SLATEPORT ikke et GYM.\p"
	.string "Når de endelig bygger et GYM der,\n"
	.string "skal jeg søge om at være LEDEREN.$"

MatchCall_Text_May3::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Husker du en fyr ved navn\n"
	.string "CUTTER i RUSTBORO?\l"
	.string "Han havde et hus der, husker du?\p"
	.string "Nå, jeg fandt ud af, at hans yngre\n"
	.string "bror bor i MAUVILLE.\p"
	.string "Kan du gætte hans navn?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "ROCK SMASH FYREN!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "RUSTURF-TUNNELEN…\n"
	.string "Det hedder den, fordi den\l"
	.string "forbinder RUSTBORO og VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}, hvordan har du det?\p"
	.string "Jeg er ude på RUTE 111 nu.\p"
	.string "Jeg vil hvile mig hos en gammel\n"
	.string "dame.\p"
	.string "Hun bor lige nord for ørkenen.$"

MatchCall_Text_May6::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Vidste du om MIRAGE\n"
	.string "TOWER i ørkenen?\p"
	.string "De siger, at ligesom en\n"
	.string "mirage, kommer og går den\n"
	.string "mysteriøst.\p"
	.string "Jeg ønsker, jeg kunne se den.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}, hej!\n"
	.string "Jeg er på RUTE 119 nu.\p"
	.string "Der er en stor flod her, og\n"
	.string "det regner ofte.\p"
	.string "Jeg blev gennemblødt!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}, hej.\p"
	.string "MT. PYRE er et minde for POKéMON,\n"
	.string "som har afsluttet deres liv.\p"
	.string "Måske som følge heraf er det\n"
	.string "inficeret med mange GHOST-type POKéMON!$"

 MatchCall_Text_May9::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Jeg tænkte på at tage til de varme\n"
	.string "kilder i LAVARIDGE.\p"
	.string "Men på vejen, omkring JAGGED\n"
	.string "PASS, stødte jeg på nogle\l"
	.string "skumle typer. Stemningen var sur!$"

MatchCall_Text_May10::
	.string "MAY: Hej, {PLAYER}!\n"
	.string "Har du set nyhederne?\p"
	.string "De siger, at KAPT. STERN opdagede\n"
	.string "HAVBUNDSKAVERNEN, mens han var på\l"
	.string "sin ubådsekspedition.$"

MatchCall_Text_May11::
	.string "MAY: Hej, {PLAYER}{KUN}!\n"
	.string "Synes du ikke, det er sejt?\p"
	.string "Selv hvis du ikke har en båd,\n"
	.string "kan du krydse havet ved at\l"
	.string "bruge en POKéMONs move.\p"
	.string "Vidste du, at der er mere?\p"
	.string "Der er en POKéMON move, der\l"
	.string "lader dig gå til bunden af havet.$"

MatchCall_Text_May12::
	.string "MAY: Hej, {PLAYER}{KUN}!\n"
	.string "Håber alt er ok!\p"
	.string "Har du været på havet og\n"
	.string "fundet din vej til den anden\l"
	.string "side blokeret?\p"
	.string "Prøv at dykke dybt ned under\n"
	.string "vandet og følg renderne.\p"
	.string "Når du kommer til den anden\n"
	.string "side, så kom op til overfladen.\p"
	.string "Let!$"

MatchCall_Text_May13::
    .string "MAY: Hej, {PLAYER}{KUN}!\p"
    .string "Hvordan går det?\n"
    .string "Er du ved at fylde din POKéDEX?\p"
    .string "Jeg hørte et rygte om, at der findes\n"
    .string "superældgamle POKéMON derude.\l"
    .string "Og der er tre af dem!\p"
    .string "Jeg ville elske at se bare en…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "Jeg har hørt rygterne!\p"
	.string "Du slog SOOTOPOLIS GYM-\n"
	.string "LEDEREN?\p"
	.string "Det betyder, at du ikke har\n"
	.string "langt igen, gør det?$"

MatchCall_Text_May15::
	.string "MAY: Der er ikke en eneste TRÆNER\n"
	.string "tilbage i HOENN, der ikke kender\l"
	.string "dig, {PLAYER}{KUN}!\p"
	.string "Når jeg fortæller folk, at jeg er\n"
	.string "venner med dig, {PLAYER}{KUN},\l"
	.string "bliver de alle overraskede!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Hej, {PLAYER}!\p"
	.string "MR. BRINEY gik på pension som en SØMAND,\n"
	.string "men jeg ser ham stadig ude på havet\n"
	.string "med sin pet PEEKO engang imellem.\p"
	.string "Jeg tror, han må stadig elske\n"
	.string "havet.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Hej, {PLAYER}!\p"
	.string "Jeg forstår ikke, hvordan små byer\n"
	.string "som PETALBURG og DEWFORD har GYMS.\p"
	.string "Jeg mener, ikke når den store havn i\n"
	.string "SLATEPORT ikke har et GYM.\p"
	.string "Når de endelig bygger et GYM der,\n"
	.string "bør jeg søge om at blive LEDER.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Hej, {PLAYER}!\p"
	.string "Husker du en fyr ved navn\n"
	.string "CUTTER i RUSTBORO?\l"
	.string "Han havde et hus der, ikke?\p"
	.string "Det viser sig, at hans lille\n"
	.string "bror bor i MAUVILLE.\p"
	.string "Kan du gætte hans navn?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "HAMMERBRO\p$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: Den her stemme... {PLAYER}?\p"
	.string "De kaldte RUSTURF-TUNNELEN for\n"
	.string "det, fordi den forbinder RUSTBORO\n"
	.string "og VERDANTURF.\p"
	.string "Vidste du det?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, hvad så?\p"
	.string "Hej, jeg er ude på RUTE 111 nu.\p"
	.string "Jeg vil hvile mig i et gammelt\n"
	.string "damers hus nord for ørkenen.\p"
	.string "Hvis du er i området, så burde\n"
	.string "du også besøge hende.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Hej, {PLAYER}!\p"
	.string "Vidste du om MIRAGE\n"
	.string "TÅRNET i ørkenen?\p"
	.string "De siger, ligesom et mirage, kan det\n"
	.string "kun ses til tider.\p"
	.string "Det vil jeg gerne se!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Hvem er det? Oh, {PLAYER}?\n"
	.string "Gæt hvad? Jeg er på RUTE 119 nu.\p"
	.string "Der er en stor flod her, og\n"
	.string "det regner hele tiden.\p"
	.string "Jeg blev gennemvåd til skindet!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE er et mindesmærke for POKéMON,\n"
	.string "deres liv er endt.\p"
	.string "Det er nok derfor det vrimler med\n"
	.string "mange GHOST-type POKéMON!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Hej med dig, {PLAYER}.\p"
	.string "Jeg var på vej tilbage til den varme\n"
	.string "kilde i LAVARIDGE.\p"
	.string "Men omkring JAGGED PASS rendte jeg\n"
	.string "ind i nogle ubehagelige typer.\p"
	.string "De skumle typer…\n"
	.string "Jeg tror, de var TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Hej, {PLAYER}!\n"
	.string "Har du hørt nyhederne?\p"
	.string "De siger, at KAPT. STERN opdagede\n"
	.string "HAVBUNDENSKAVEN under sin\l"
	.string "ubådsekspedition.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Hej der, {PLAYER}!\n"
	.string "Synes du ikke, det er fantastisk?\p"
	.string "Selv hvis du ikke har en båd,\n"
	.string "kan du krydse havet\n"
	.string "ved hjælp af en POKéMONs bevægelse.\p"
	.string "Og så er der en bevægelse, der lader dig\n"
	.string "rejse til bunden af havet.\p"
	.string "Pokémon kan virkelig alt muligt!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Hej, {PLAYER}!\n"
	.string "Hvordan har du det?\p"
	.string "Har du nogensinde oplevet, at vejen\n"
	.string "blev blokeret, mens du var på havet?\p"
	.string "Prøv at dykke dybt under vandet og\n"
	.string "følg renden på bunden.\p"
	.string "Når du når den anden side,\n"
	.string "kommer du op til overfladen. Simpelt!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Hej der, {PLAYER}!\p"
	.string "Hvordan går det? Har du fået fyldt\n"
	.string "din POKéDEX op med succes?\p"
	.string "Jeg har hørt et rygte om, at der\n"
	.string "findes super-ældgamle POKéMON derude.\l"
	.string "Og ikke bare en--tre!\p"
	.string "Jeg ville elske at fange bare én…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}!\n"
	.string "Jeg har hørt rygterne!\p"
	.string "Du slog SOOTOPOLIS GYM\n"
	.string "LEADER? Fantastisk!\p"
	.string "Du er virkelig tæt på nu!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: Der er ikke en TRÆNER i\n"
	.string "hele HOENN, der ikke ved, hvem du\l"
	.string "er, {PLAYER}!\p"
	.string "Når jeg fortæller folk, at jeg er\n"
	.string "venner med dig, {PLAYER}, bliver de\l"
	.string "ret misundelige!$"

MatchCall_Text_Wally1::
	.string "WALLY: Åh, {PLAYER}!\p"
	.string "Jeg har fået det bedre og er blevet\n"
	.string "mere fysisk fit.\p"
	.string "Jeg håber, at jeg snart kan blive en\n"
	.string "TRÆNER ligesom dig, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, hej!\p"
	.string "Efter RUSTURF-TUNNELEN\n"
	.string "har hun været meget glad!$"

MatchCall_Text_Wally3::
	.string "WALLY: Åh, {PLAYER}!\p"
	.string "Jeg... Jeg forlod min onkels hjem i\n"
	.string "VERDANTURF uden at fortælle nogen.\p"
	.string "Jeg spekulerer på, om han er rasende på mig...\p"
	.string "{PLAYER}, du forstår vel, hvordan\n"
	.string "jeg har det, ikke sandt?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}?\n"
	.string "Det er mig, WALLY!\p"
	.string "Trænernes verden er fantastisk!\p"
	.string "Når jeg har mine POKéMON med mig,\n"
	.string "siger alle mulige mennesker hej!\p"
	.string "Det er som om, at alle bliver\n"
	.string "forbundet gennem POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? Det er fantastisk!\n"
	.string "Den RALTS vi fangede sammen?\l"
	.string "Den udviklede sig, {PLAYER}!\p"
	.string "Måske er jeg talentfuld…\p"
	.string "Åh, men jeg bør ikke blive hovmodig\n"
	.string "som sådan!\p"
	.string "Det er jo POKéMON'en, der skal\n"
	.string "roses!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Det virker som om WALLY er ude\n"
	.string "af POKéNAVs dækningsområde…$"

MatchCall_Text_Wally7::
	.string "WALLY: Åh, {PLAYER}!\p"
	.string "Før jeg mødte dig, forlod jeg\n"
	.string "så sjældent mit hus…\p"
	.string "Men nu er jeg på et eventyr med\n"
	.string "min helt egen POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Tak…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Hej, {PLAYER}{KUN}!\p"
	.string "Ved du, hvordan man kan finde\n"
	.string "POKéMON overalt?\p"
	.string "Som i bjergene, i havet,\n"
	.string "i højt græs overalt?\p"
	.string "Ligesom POKéMON, kan du finde\n"
	.string "TRÆNERE overalt også.\p"
	.string "Som følge heraf skal jeg skynde\n"
	.string "mig overalt. Travlt, travlt!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Jeg er på RUTE 119 lige nu.\n"
	.string "Der er fyldt med TRÆNERE!\p"
	.string "Der er også højt græs overalt,\n"
	.string "det virker det til.\p"
	.string "At gå rundt i shorts her\n"
	.string "får mig til at krible over det hele!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Hej, hej, {PLAYER}{KUN}!\p"
	.string "Har du haft mulighed for at klatre\n"
	.string "op ad MT. PYRE?\p"
	.string "Stedet er et mindesmærke for POKéMON,\n"
	.string "der er gået bort.\p"
	.string "Det er et sted, som enhver TRÆNER\n"
	.string "bør klatre til toppen af mindst én gang.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Hej, {PLAYER}{KUN}!\p"
	.string "Jeg har hørt om disse mærkelige\n"
	.string "bander, der er til gene.\p"
	.string "Hold MAGMA og Hold AQUA,\n"
	.string "tror jeg, de hedder.\p"
	.string "Jeg vil tro, der er nogle dygtige\n"
	.string "TRÆNERE iblandt dem.\p"
	.string "…Men hvis de er bøller…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Åh, hej, {PLAYER}{KUN}.\p"
	.string "Mon der er nogle seje TRÆNERE\n"
	.string "nederst i havet?\p"
	.string "Det kan jeg ikke selv tjekke.\n"
	.string "Jeg kan ikke svømme, for det\n"
	.string "første.\l"
	.string "Og jeg opdrætter ikke POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Hej, hej, {PLAYER}{KUN}!\p"
	.string "Ved du, at du kan udfordre\n"
	.string "POKéMON-LIGAEN, når du har\n"
	.string "samlet alle GYM-BADGES?\p"
	.string "Med dit talent er det\n"
	.string "at blive MESTER ikke urealistisk.\p"
	.string "Men vidste du det?\n"
	.string "Der er et sted, der er endnu\n"
	.string "bedre.\p"
	.string "Men det er alt, jeg er villig til at\n"
	.string "sige for nu.\p"
	.string "Det er noget at se frem til.\p"
	.string "Når du har kæmpet dig vej gennem\n"
	.string "POKéMON-LIGAEN ind i HALL\n"
	.string "OF FAME!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Norman1::
	.string "FAR: I RUSTBORO bor der en mand,\n"
	.string "som går under det mærkelige\n"
	.string "navn SKÆREREN.\p"
	.string "Hvis du er i området, bør du\n"
	.string "besøge ham.$"

MatchCall_Text_Norman2::
	.string "FAR: Hmm… Lidt efter lidt, men også\n"
	.string "meget sikkert, bliver du\l"
	.string "stærkere, {PLAYER}.\p"
	.string "Jo stærkere du bliver, jo længere\n"
	.string "og højere svæver du fra Mor\l"
	.string "og mig…\p"
	.string "Denne følelse er svær at forklare.$"

MatchCall_Text_Norman3::
	.string "FAR: Jeg ser...\n"
	.string "Du har samlet fire GYM BADGES...\p"
	.string "Der er ingen vej udenom nu.\n"
	.string "Vi vil kæmpe, som jeg lovede.\p"
	.string "Kom når som helst.\n"
	.string "Vi venter alle på dig!$"

MatchCall_Text_Norman4::
	.string "FAR: {PLAYER}! Du bør besøge\n"
	.string "Mor en gang imellem.\p"
	.string "Jeg bliver her og fordobler\n"
	.string "min træning.\p"
	.string "Kampens vej er dyb og\n"
	.string "ubarmhjertig!$"

MatchCall_Text_Norman5::
	.string "FAR: Hej, {PLAYER}!\p"
	.string "Hvad er det? MAGMA-EMBLEM?\n"
	.string "Jeg ved ikke, hvad det handler om.\p"
	.string "Men med et navn som det kan det\n"
	.string "måske være på en eller anden måde\n"
	.string "relateret til en vulkan!$"

MatchCall_Text_Norman6::
	.string "FAR: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "Du fangede mig lige midt i\n"
	.string "en POKéMON-træningssession!$"

MatchCall_Text_Norman7::
	.string "FAR: {PLAYER}!\p"
	.string "Hvem havde troet, at du ville\n"
	.string "blive POKéMON LIGA-MESTER…\p"
	.string "Okay!\n"
	.string "Jeg bliver ikke efterladt!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}?\n"
	.string "Hvad er du heldig!\p"
	.string "Denne gang udfordrer jeg dig til\n"
	.string "kamp.\p"
	.string "Jeg venter i PETALBURG GYM.\n"
	.string "Accepter min udfordring når som helst!$"

MatchCall_Text_Norman9::
	.string "FAR: …Du forbavser mig, {PLAYER}.\n"
	.string "Hvor meget højere vil du flyve?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Hej, {PLAYER}en!\p"
	.string "Har du været i MAUVILLE\n"
	.string "allerede?\p"
	.string "Du bør besøge CYKELBUTIKKEN\n"
	.string "og få en MACH-CYKEL.\p"
	.string "Prøv derefter at udforske\n"
	.string "GRANITHULEN grundigt.\p"
	.string "Du kunne måske gøre en ny\n"
	.string "opdagelse der.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Hej, {PLAYER}!{KUN}\p"
	.string "Jeg har mødt mange forskellige\n"
	.string "TRÆNERE indtil videre.\p"
	.string "Men du er helt speciel.\n"
	.string "Du ligner ikke nogen andre.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Hej, {PLAYER}{KUN}!\p"
	.string "Når du er på eventyr med dine\n"
	.string "POKéMON, hvad tænker du?\p"
	.string "Ser du dem som stærke partnere?\p"
	.string "Ser du dem som sjove kammerater?\p"
	.string "Afhængigt af din tankegang,\n"
	.string "ændres eventyrets betydning.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Hej?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Jeg er havnet i lidt problemer\n"
	.string "på RUMCENTRET.\p"
	.string "Undskyld, men jeg kan ikke tale nu.\n"
	.string "Hej!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Oh!\n"
	.string "{PLAYER}!\p"
	.string "Der er ingen grund til at snakke.\n"
	.string "Det er forbi med at snakke.\p"
	.string "Du skal tro på dig selv\n"
	.string "og gøre det rigtige.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "STEVEN ser ud til ikke at få\n"
	.string "opkaldet…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}… Tillykke\n"
	.string "for at komme ind i FAME-HALLEN.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Jeg håber vi kan mødes\n"
	.string "igen et sted!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Åh, {PLAYER}{KUN}!\n"
	.string "Jeg har allerede hørt om dig!\p"
	.string "Det ser ud til, at din POKéNAV\n"
	.string "er blevet opgraderet med MATCH CALL.\p"
	.string "Nå, jeg burde også registrere mig!\p"
	.string "På den måde kunne jeg undersøge\n"
	.string "din POKéDEX selv mens du er ude\l"
	.string "på marken.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Registreret PROF. BIRCH\n"
	.string "i POKéNAV'en.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: Når man har både\n"
	.string "POKéDEX og POKéNAV, bliver studiet\n"
	.string "af POKéMON mere sjovt, hva?$"

MatchCall_Text_MrStone1::
	.string "MR. STEN: Åh? {PLAYER}{KUN}!\p"
	.string "Siden du ringede til mig, så\n"
	.string "virker POKéNAV'en som den skal!\p"
	.string "Andre personer bliver registreret,\n"
	.string "så prøv også at ringe til dem!\p"
	.string "Godt! Godt!\n"
	.string "Du virker ret glad!\p"
	.string "Hm...\n"
	.string "Hvordan kunne jeg vide det?\p"
	.string "Det er fordi, jeg kigger ned på\n"
	.string "dig fra mit kontorvindue!\p"
	.string "Wahahaha!\n"
	.string "Vi ses igen!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Åh? {PLAYER} {KUN}!\p"
	.string "Hvad er galt? Har du glemt\n"
	.string "om den lille opgave, jeg gav dig?\p"
	.string "Jeg har brug for dig til at\n"
	.string "levere mit brev til STEVEN i DEWFORD.\p"
	.string "Efter det, lever vores pakke til\n"
	.string "KAPT. STERN i SLATEPORT.\p"
	.string "Du husker det, ikke sandt?\p"
	.string "Nu, da jeg er en travl PRESIDENT,\n"
	.string "bliver jeg nødt til at gå! Hej-hej!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: Oh! {PLAYER}kun!\p"
	.string "Ah, så du har mødt STEVEN!\n"
	.string "Jeg burde belønne dig, så!\p"
	.string "Når du besøger RUSTBORO igen,\n"
	.string "kom og besøg mig på mit kontor.\p"
	.string "Jeg venter på dig!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Åh! {PLAYER}{KUN}!\p"
	.string "Vidste du, at DEVON var ved\n"
	.string "at grave RUSTURF-TUNNELEN?\p"
	.string "Men vi lukkede operationen ned for\n"
	.string "at beskytte POKéMON'erne i området.\p"
	.string "Det er egentlig meget simpelt.\p"
	.string "Det er vigtigere at lade POKéMON'erne\n"
	.string "leve i fred end at bekymre os om\l"
	.string "vores egen bekvemmelighed.$"

MatchCall_Text_MrStone5::
	.string "HR. STEN: Hej, hej, {PLAYER}{KUN}!\p"
	.string "Jeg hørte fra nogen i PETALBORG\n"
	.string "at du er NORMANs barn!\p"
	.string "Ikke underligt, du er så dygtig\n"
	.string "et individ!$"

MatchCall_Text_MrStone6::
	.string "HR. STEN: Hvad er det?\p"
	.string "Du kæmpede mod din egen far og\n"
	.string "besejrede ham?\p"
	.string "Det er fantastisk!\p"
	.string "Jeg havde ingen anelse om, at jeg\n"
	.string "havde gjort venner med nogen så\n"
	.string "særlig! Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Hej!\n"
	.string "Dette er DEVON KONCERNEN…\l"
	.string "Åh, hej, {PLAYER}!\p"
	.string "Vores DIREKTØR var her for lidt\n"
	.string "siden, men han er gået ud.\p"
	.string "Vores DIREKTØR er travl, men du\n"
	.string "ser ud til at være lige så travlt beskæftiget, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Hvad? …Hvad er det?\p"
	.string "GROU… Ja? …DON?\p"
	.string "Du er ved at falde ud…\n"
	.string "…kan ikke høre…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Huh? …Hvad er det?\p"
	.string "Seaflo… Ja? …Grotte…?\p"
	.string "Du er ved at miste signalet…\n"
	.string "…kan ikke høre…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "HR. STEN: {PLAYER}{KUN}! Det er mig!\p"
	.string "Du var åbenbart involveret i alle\n"
	.string "mulige ting, men jeg, der er travl,\l"
	.string "aner ikke præcist hvad!\p"
	.string "Dog opfordrer jeg dig til at vælge\n"
	.string "den vej, du tror på, og gå ad den.\p"
	.string "Jeg vil altid støtte dig!\n"
	.string "Pas på dig selv!$"

MatchCall_Text_MrStone11::
	.string "HR. STONE: … … … … … …\n"
	.string "Er det måske {PLAYER}{KUN}?\p"
	.string "Din stemme er så fuld af selvtillid,\n"
	.string "at jeg ikke genkendte dig med det\n"
	.string "samme!\p"
	.string "Hmm! Du må besøge os hos DEVON\n"
	.string "engang!$"
