@ TRANSLATED

MatchCall_WildBattleText1::
	.string "Hej! {PLAYER}{KUN}, hej! Det er\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg så denne {STR_VAR_2} for et\n"
	.string "stykke tid siden men jeg kunne ikke\l"
	.string "fange den.\p"
	.string "Den var så tæt på, også! Nå, vi ses igen!$"

MatchCall_WildBattleText2::
	.string "Hej, {PLAYER}{KUN}. Det er {STR_VAR_1}.\p"
	.string "Jeg prøvede at fange en fin\n"
	.string "{STR_VAR_2} for lidt siden.\p"
	.string "Men den slap væk. Jeg var virkelig\n"
	.string "skuffet!\p"
	.string "Okay, farvel!$"

MatchCall_WildBattleText3::
	.string "Hej {PLAYER}! Det er mig,\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg forsøgte lige at fange denne\n"
	.string "{STR_VAR_2}, men den løb sin vej.\p"
	.string "Jeg var så tæt på, også!\p"
	.string "Den ødelagde min dag… Nå, vi ses!$"

MatchCall_WildBattleText4::
	.string "Hej, {PLAYER}{KUN}. {STR_VAR_1} her.\p"
	.string "Kender du POKéMON {STR_VAR_2}? Jeg\n"
	.string "kom tæt på at fange en.\p"
	.string "Det var for lidt siden. Jeg troede, jeg\n"
	.string "havde den, men den undslap.\p"
	.string "Hvis jeg ser den igen, får jeg den\n"
	.string "sikkert.\p"
	.string "Okay, vi snakkes senere.$"

MatchCall_WildBattleText5::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}.\n"
	.string "Har du fanget nogle POKÉMON på det\l"
	.string "sidste? Hørte du det?\p"
	.string "For et øjeblik siden var jeg tæt på at\n"
	.string "fange en, men den slap løs.\p"
	.string "Okay, pas på!$"

MatchCall_WildBattleText6::
	.string "Hey, {PLAYER}{KUN}. {STR_VAR_1} her.\n"
	.string "Har du fanget nogle POKéMON på det\l"
	.string "seneste?\p"
	.string "Jeg prøvede næsten at fange en\n"
	.string "forleden dag. Men den undslap mig på en\l"
	.string "eller anden måde.\p"
	.string "Pas på dig selv.$"

MatchCall_WildBattleText7::
	.string "…Øh, {PLAYER}{KUN}? Det er mig,\n"
	.string "{STR_VAR_1}.\p"
	.string "Vent lidt! Vent! Jeg kan fange denne\n"
	.string "{STR_VAR_2}…\p"
	.string "Aaarrrgh! Den undslap! Det var lige ved\n"
	.string "og næsten!$"

MatchCall_WildBattleText8::
	.string "Åh, {PLAYER}{KUN}, hvordan går det? Det er\n"
	.string "{STR_VAR_1}, der taler.\p"
	.string "Har du haft succes med at fange\n"
	.string "POKéMON på det sidste?\p"
	.string "Jeg kom meget tæt på for nylig, men mit\n"
	.string "mål slap væk.\p"
	.string "Jeg bliver nødt til at prøve hårdere! Vi\n"
	.string "ses igen!$"

MatchCall_WildBattleText9::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}!\p"
	.string "Nå? Samler du flere POKéMON sammen?\p"
	.string "Jeg har en elendig tid med det! De\n"
	.string "slipper alle væk fra mig!\p"
	.string "Vi ses!$"

MatchCall_WildBattleText10::
	.string "Åh, {PLAYER}{KUN}, hej… Det er\n"
	.string "{STR_VAR_1}.\p"
	.string "Hør, jeg var så tæt på at fange denne\n"
	.string "{STR_VAR_2}…\p"
	.string "Men den slap væk…\p"
	.string "Jeg bliver nødt til at prøve hårdere. Vi\n"
	.string "ses.$"

MatchCall_WildBattleText11::
	.string "Åh, {PLAYER}{KUN}. Dette er\n"
	.string "{STR_VAR_1}. Hvordan går det med\l"
	.string "dig?\p"
	.string "Jeg prøvede at fange en vild\n"
	.string "{STR_VAR_2} tidligere, men den\l"
	.string "formåede at flygte.\p"
	.string "Jeg føler mig slået…$"

MatchCall_WildBattleText12::
	.string "Hej, {PLAYER}{KUN}. Det er mig,\n"
	.string "{STR_VAR_1}. Fanger du stadig\l"
	.string "POKéMON?\p"
	.string "Jeg har også prøvet at fange dem selv,\n"
	.string "men det er ikke så nemt.\p"
	.string "POKéMONs verden er dyb!$"

MatchCall_WildBattleText13::
	.string "Åh, hej, {PLAYER}{KUN}! Det her er\n"
	.string "{STR_VAR_1}! Har du fanget POKéMON?\p"
	.string "Jeg har også prøvet at fange dem, men\n"
	.string "med ringe succes.\p"
	.string "POKéMONs vej er dyb!$"

MatchCall_WildBattleText14::
	.string "Hej, {PLAYER}{KUN}, hvordan går det? Det\n"
	.string "her er {STR_VAR_1}.\p"
	.string "Lige nu prøvede jeg at fange en sød\n"
	.string "{STR_VAR_2}.\p"
	.string "Det slap dog væk! Åh, jeg var skuffet!\p"
	.string "Farvel!$"

MatchCall_WildBattleText15::
	.string "Hej, {PLAYER}! Det er {STR_VAR_1}!\p"
	.string "Jeg har tænkt på at prøve at fange\n"
	.string "nogle POKéMON.\p"
	.string "Men jeg kan ikke finde nogen. Det er en\n"
	.string "rigtig gåde for mig!\p"
	.string "Jeg er i bunden af min visdom! Vi ses!$"

MatchCall_NegativeBattleText1::
	.string "Hej! {PLAYER}{KUN}, hej! Det her er\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg prøvede at kæmpe mod en anden\n"
	.string "TRÆNER, men jeg tabte.\p"
	.string "Det var virkelig skuffende. Nå, vi ses\n"
	.string "igen!$"

MatchCall_NegativeBattleText2::
	.string "Hej, {PLAYER}{KUN}. Det er {STR_VAR_1}.\p"
	.string "Jeg udfordrede en anden efter vi\n"
	.string "kæmpede.\p"
	.string "Jeg kom tæt på, men endte med at tabe.\n"
	.string "Nå, pyt!$"

MatchCall_NegativeBattleText3::
	.string "Hej {PLAYER}! Det er mig,\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg blev lige ryddet af i en kamp.\p"
	.string "Jeg skal nok forbedre mit hold lidt\n"
	.string "mere!$"

MatchCall_NegativeBattleText4::
	.string "Hej, {PLAYER}. {STR_VAR_1} her.\p"
	.string "Jeg prøvede en anden kamp i går, men jeg\n"
	.string "kunne ikke vinde.\p"
	.string "Mit hold har brug for mere træning. Okay,\n"
	.string "vi ses senere.$"

MatchCall_NegativeBattleText5::
	.string "Hej, {PLAYER}! Det er {STR_VAR_1}.\p"
	.string "Hvordan går det med dig?\p"
	.string "Jeg har kæmpet, men jeg har ikke vundet\n"
	.string "særlig tit.\p"
	.string "Jeg kan ikke få det til at fungere. Nå,\n"
	.string "pas på!$"

MatchCall_NegativeBattleText6::
	.string "Hey, {PLAYER}. {STR_VAR_1} her.\p"
	.string "Hvordan går det for dig?\p"
	.string "Jeg har kæmpet hårdt på det seneste,\n"
	.string "men til ingen succes.\p"
	.string "Jeg kan ikke komme i flow. Pas på dig\n"
	.string "selv.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} her. Hvordan går det for\n"
	.string "tiden?\p"
	.string "Jeg tabte en kamp i går, og det fylder\n"
	.string "mine tanker.\p"
	.string "Jeg må tænke en plan ud… Vi ses.$"

MatchCall_NegativeBattleText8::
	.string "Åh, {PLAYER}{KUN}, hvordan har du det? Det\n"
	.string "er {STR_VAR_1} der taler.\p"
	.string "Hvordan har dine POKéMON det? Jeg\n"
	.string "tabte en kamp forleden dag.\p"
	.string "Jeg skal prøve hårdere! Vi ses igen!$"

MatchCall_NegativeBattleText9::
	.string "Åh, {PLAYER}{KUN}, hej der! Det er\n"
	.string "{STR_VAR_1}!\p"
	.string "Hør nu her, du skal høre dette!\p"
	.string "Jeg havde en POKéMON-kamp tidligere,\n"
	.string "men jeg tabte i sidste sekund.\p"
	.string "Åh, det gør mig vred!$"

MatchCall_NegativeBattleText10::
	.string "Åh, {PLAYER}{KUN}, hej… Det her er\n"
	.string "{STR_VAR_1}.\p"
	.string "For lidt tid siden var jeg i kamp. Jeg\n"
	.string "tabte dog.\p"
	.string "Jeg skal træne mine POKéMON mere. Vi ses\n"
	.string "rundt omkring.$"

MatchCall_NegativeBattleText11::
	.string "Åh, {PLAYER}{KUN}. Det her er\n"
	.string "{STR_VAR_1}. Hvordan har dine\l"
	.string "POKéMON det?\p"
	.string "Jeg tabte lige endnu en kamp.\p"
	.string "Nå, vi ses!$"

 MatchCall_NegativeBattleText12::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er mig, {STR_VAR_1}.\l"
	.string "Kæmper du stadig hårdt?\p"
	.string "Hvad mig angår, tabte jeg\n"
	.string "for nylig, så jeg har trænet mit\n"
	.string "hold overalt.\p"
	.string "Lad os mødes igen.$"

MatchCall_NegativeBattleText13::
	.string "Åh, hej, {PLAYER}{KUN}! Det her er\n"
	.string "{STR_VAR_1}!\p"
	.string "Jeg håber, du har det godt.\p"
	.string "Jeg var i kamp lige før dette.\p"
	.string "{PLAYER}{KUN}, prøv at være aktiv som mig.\n"
	.string "Vi ses igen!$"

MatchCall_NegativeBattleText14::
	.string "Hej, {PLAYER}{KUN}. Det her er\n"
	.string "{STR_VAR_1}.\p"
	.string "Har du det godt?\p"
	.string "Du bør tage hjem en gang imellem, dog.\p"
	.string "Farvel!$"

MatchCall_PositiveBattleText1::
	.string "Hej! {PLAYER}{KUN}, hej! Det her er\n"
	.string "{STR_VAR_1}!\p"
	.string "Jeg kæmpede mod en anden TRÆNER\n"
	.string "tidligere. Jeg vandt! Jeg vandt!\p"
	.string "Min {STR_VAR_2} arbejdede virkelig\n"
	.string "hårdt for mig. Det her er så godt!$"

MatchCall_PositiveBattleText2::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}!\p"
	.string "Jeg havde en kamp i går og jeg vandt!\n"
	.string "Det er fantastisk!$"

MatchCall_PositiveBattleText3:: 
	.string "Hej {PLAYER}!\n"
	.string "Det er mig, {STR_VAR_1}!\l"
	.string "Hvordan går det med dine kampe?\p"
	.string "Jeg havde en kamp den anden dag,\n"
	.string "og min {STR_VAR_2} gjorde det stort!\p"
	.string "Næste gang vi kamper,\n"
	.string "{PLAYER}, det bliver ikke mig, der taber!$"

MatchCall_PositiveBattleText4::
	.string "Hej, {PLAYER}. {STR_VAR_1} her.\p"
	.string "Jeg havde en kamp tidligere. Jeg\n"
	.string "formåede at vinde, men det  var tæt.\p"
	.string "Min {STR_VAR_2} gav en inspirerende\n"
	.string "præstation.$"

MatchCall_PositiveBattleText5::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}.\p"
	.string "Hvordan går det med dig? Kæmper du\n"
	.string "meget?\p"
	.string "Jeg vandt lige for nylig! Min\n"
	.string "{STR_VAR_2} var genial!\p"
	.string "Du venter bare. Jeg vil slå dig næste\n"
	.string "gang! Okay, pas på!$"

MatchCall_PositiveBattleText6::
	.string "Hej, {PLAYER}{KUN}. {STR_VAR_1} her.\p"
	.string "Hvordan går det for dig?\p"
	.string "Jeg har været på en vinderstribe. Jeg\n"
	.string "vandt lige en kamp.\p"
	.string "Når vi har vores næste kamp, er jeg\n"
	.string "sikker på, at jeg ikke vil tabe!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}? {STR_VAR_1} her.\p"
	.string "Min {STR_VAR_2} er en kraft! Den\n"
	.string "vandt mig en anden kamp lige nu!\p"
	.string "Jeg kan ikke vente med at få en\n"
	.string "revanche med dig.$"

MatchCall_PositiveBattleText8::
	.string "Hej, {PLAYER}{KUN}, hvordan har du det?\n"
	.string "Det er {STR_VAR_1} der taler.\p"
	.string "Jeg håber, du har det godt. Jeg ville\n"
	.string "bare fortælle dig, at jeg lige vandt.\p"
	.string "Min {STR_VAR_2} arbejdede især\n"
	.string "hårdt for at få sejren.\p"
	.string "Vi ses igen!$"

MatchCall_PositiveBattleText9::
	.string "Hej, {PLAYER}{KUN}! Her er {STR_VAR_1}!\p"
	.string "Hvordan har dine POKéMON det? Mine har\n"
	.string "lige vundet en kamp!\p"
	.string "Min {STR_VAR_2} var fantastisk, må\n"
	.string "jeg sige!\p"
	.string "Jeg ønsker, jeg kunne have vist dig! Vi\n"
	.string "ses igen!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}ærme, hej… Det her er\n"
	.string "{STR_VAR_1}.\p"
	.string "Hvordan har livet behandlet dig?\p"
	.string "Mine POKéMON ser ud til at være fyldt\n"
	.string "med energi.\p"
	.string "Jeg vandt lige en kamp med dem. Vi ses.$"

MatchCall_PositiveBattleText11::
	.string "Hovsa, {PLAYER}{KUN}. Dette er\n"
	.string "{STR_VAR_1}.\p"
	.string "Har du kæmpet for nylig? Jeg vandt lige\n"
	.string "endnu en kamp i dag!\p"
	.string "Jeg er i topform! Gahahaha! Nå, vi ses!$"

MatchCall_PositiveBattleText12::
	.string "Hej, {PLAYER}{KUN}. Det er mig,\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg håber, alt er godt? Jeg sprudler\n"
	.string "stadig af liv!\p"
	.string "Jeg vandt endda lige igen. Jeg giver\n"
	.string "ikke plads til jer ungdommelige endnu!$"

MatchCall_PositiveBattleText13::
	.string "Åh, hej, {PLAYER}{KUN}! Det er\n"
	.string "{STR_VAR_1}!\p"
	.string "Jeg håber, at du har det godt. Jeg har\n"
	.string "stadig schwung i skridtet!\p"
	.string "Ja, jeg har lige vundet endnu en kamp.\n"
	.string "Åh, jeg vil ikke tabe til unge mennesker\l"
	.string "endnu!\p"
	.string "Vi ses igen!$"

MatchCall_PositiveBattleText14::
	.string "Hej, {PLAYER}{KUN}. Det er {STR_VAR_1}.\p"
	.string "Jeg var i kamp for nylig, og min\n"
	.string "{STR_VAR_2} var exceptionel!\p"
	.string "Jeg ville ønske, at du kunne have set\n"
	.string "det, {PLAYER}{KUN}. Hej-hej!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hej! {PLAYER}, hej! Det er\n"
	.string "{STR_VAR_1}.\p"
	.string "Hvad? Vent, er du tæt på\n"
	.string "{STR_VAR_2}?\p"
	.string "Wow, så må vi kæmpe! Jeg venter! Vi ses!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Hej, {PLAYER}! Det er {STR_VAR_1}.\p"
	.string "Åh? Er du tilfældigvis i {STR_VAR_2}\n"
	.string "lige nu?\p"
	.string "Skal vi kæmpe nu? Jeg venter på dig! Vi\n"
	.string "ses!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Hej der, {PLAYER}! Det er mig,\n"
	.string "{STR_VAR_1}.\p"
	.string "Åh, hej, er du tæt på {STR_VAR_2}\n"
	.string "lige nu?\p"
	.string "Vil du kæmpe med mig lige nu?\p"
	.string "Jeg taber ikke igen! Jeg venter! Vi ses\n"
	.string "snart!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hej, {PLAYER}{KUN}. {STR_VAR_1} her.\p"
	.string "Hvor befinder du dig nu? Hva' så?\n"
	.string "{STR_VAR_2}?\p"
	.string "Skal vi kæmpe nu? Jeg vil vente på dig.\n"
	.string "Vi ses!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}.\n"
	.string "Hvordan går det med dig?\p"
	.string "Er du hvor nu? {STR_VAR_2}?\p"
	.string "Hvad siger du til en hurtig omkamp lige\n"
	.string "nu?\p"
	.string "Jeg holder øje med dig. Vi ses snart!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}. {STR_VAR_1} her.\n"
	.string "Hvordan har dine POKéMON det?\p"
	.string "Åh, er det rigtigt? Du er i nærheden af\n"
	.string "{STR_VAR_2}?\p"
	.string "Nå, så må vi hellere få en omkamp.\p"
	.string "Jeg kan vente, selvfølgelig. Vi ses!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Øh, {PLAYER}igen? {STR_VAR_1}\n"
	.string "her…\p"
	.string "Åh, er du tilfældigvis i {STR_VAR_2}?\p"
	.string "Så lad os kæmpe. Med det samme, mener\n"
	.string "jeg.\p"
	.string "Jeg vil vise dig mine POKéMON. Jeg\n"
	.string "venter på dig.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Hej, {PLAYER}{KUN}, hvordan går det? Det er\n"
	.string "{STR_VAR_1}, der taler.\p"
	.string "Jeg håber, du har det godt. Åh, du er nær\n"
	.string "{STR_VAR_2}.\p"
	.string "Har du lyst til at kæmpe med mig så?\p"
	.string "Jeg venter på dig. Vi ses snart!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Hej, {PLAYER}{KUN}, hej! Det er\n"
	.string "{STR_VAR_1}!\p"
	.string "Er du med? Er du nær {STR_VAR_2}?\p"
	.string "Nå, så synes du ikke, vi skal kæmpe?\p"
	.string "Hold mig ikke vente for længe!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Hej, {PLAYER}{KUN}… Det er {STR_VAR_1}.\p"
	.string "Hvordan går det med dig? Oh, du er tæt\n"
	.string "på {STR_VAR_2}.\p"
	.string "Vi burde kæmpe nu.\p"
	.string "Jeg er klar og venter. Skynd dig!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Åh, {PLAYER}{KUN}. Det her er\n"
	.string "{STR_VAR_1}.\p"
	.string "Åh, så hvor du er lige nu er\n"
	.string "{STR_VAR_2}?\p"
	.string "Nå, så bliver vi nødt til at have en kamp,\n"
	.string "ikke sandt?\p"
	.string "Jeg venter på dig! Vi ses snart!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Hej, {PLAYER}{KUN}. Det er mig,\n"
	.string "{STR_VAR_1}. Hvor befinder du dig\l"
	.string "nu?\p"
	.string "{STR_VAR_2}? Det er ret tæt på!\p"
	.string "Hvad siger du til at have en kamp nu?\p"
	.string "Jeg kan vente. Vi ses!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Åh, hej, {PLAYER}{KUN}! Det er\n"
	.string "{STR_VAR_1}!\p"
	.string "Jeg håber, du har det godt. Åh, du er tæt\n"
	.string "på {STR_VAR_2}?\p"
	.string "Da det ikke er så langt væk, kom og se\n"
	.string "mig til en kamp.\p"
	.string "Jeg venter på dig. Hej for nu.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Hej, {PLAYER}{KUN}. Det er {STR_VAR_1}.\p"
	.string "Hvad siger du? ...{STR_VAR_2}? Det er\n"
	.string "meget tæt på.\p"
	.string "Synes du ikke vi burde have en kamp?\p"
	.string "Jeg vil lede efter dig! Farvel!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hej! {PLAYER}, hej! Det er\n"
	.string "{STR_VAR_1}.\p"
	.string "Vil du kæmpe imod mig?\p"
	.string "Jeg venter på dig omkring\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Hej, {PLAYER}! Det er {STR_VAR_1}.\p"
	.string "Vil du kæmpe mod mig igen?\p"
	.string "Du kan finde mig omkring\n"
	.string "{STR_VAR_2}. Jeg venter!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Hej {PLAYER}! Det' mig, {STR_VAR_1}.\p"
	.string "Mine POKéMON er blevet meget stærkere\n"
	.string "siden sidst.\p"
	.string "Jeg vil gerne se hvor stærke de er\n"
	.string "blevet i forhold til dine POKéMON,\l"
	.string "{PLAYER}.\p"
	.string "Så lad os kæmpe!\p"
	.string "Jeg venter på dig ved {STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hej, {PLAYER}{KUN}. {STR_VAR_1} her.\n"
	.string "Hvordan går det med dig?\p"
	.string "Mine POKéMON er blevet ret seje på det\n"
	.string "sidste.\p"
	.string "Hey, kunne du tænke dig at tage en kamp\n"
	.string "til med mig?\p"
	.string "Vi kan mødes omkring {STR_VAR_2},\n"
	.string "okay?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}.\p"
	.string "Mine POKéMON vokser op på fine måder.\p"
	.string "Jeg vil virkelig gerne have et anden\n"
	.string "kamp med dig.\p"
	.string "Jeg vil holde øje med dig omkring\n"
	.string "{STR_VAR_2}. Vi ses snart!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hej, {PLAYER}{KUN}. {STR_VAR_1} her.\n"
	.string "Jeg håber, du har styr på tingene.\p"
	.string "Jeg tænkte, at jeg gerne vil udfordre\n"
	.string "dig til endnu et slag. Hvad siger du?\p"
	.string "Hvis du har lyst til kamp, så kom til\n"
	.string "{STR_VAR_2}.\p"
	.string "Vi ses!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Øh, er det dig, {PLAYER}{KUN}? \n"
	.string "{STR_VAR_1} her… Nå? Gror dine\l"
	.string "POKéMON? \p"
	.string "Mine er helt sikkert blevet stærkere.\n"
	.string "Jeg vil gerne vise dig det. \p"
	.string "Jeg vil være i nærheden af\n"
	.string "{STR_VAR_2}.  Kom og find mig til en\l"
	.string "kamp. \p"
	.string "Vi ses.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Hej, {PLAYER}{KUN}, hvordan går det? Det er\n"
	.string "{STR_VAR_1}, der taler.\p"
	.string "Jeg håber, du har det godt. Mine\n"
	.string "POKéMON er meget livlige.\p"
	.string "Hvis du nogensinde er i området, så giv\n"
	.string "mig en revanche.\p"
	.string "Jeg vil være omkring {STR_VAR_2}.\n"
	.string "Indtil da, farvel!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}!\n"
	.string "Hvordan har dine POKéMON det?\p"
	.string "Mine POKéMON bliver ved med at blive\n"
	.string "bedre. Jeg vil gerne vise dig, {PLAYER}{KUN}.\p"
	.string "Jeg er omkring {STR_VAR_2} nu, så\n"
	.string "lad os kæmpe, hvis du er i nærheden.\p"
	.string "Håber jeg ser dig snart!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Hej, {PLAYER}{KUN}… Det er {STR_VAR_1}.\n"
	.string "Nå, hvordan går det med dig?\p"
	.string "Mine POKéMON er blevetganske meget\n"
	.string "stærkere.\p"
	.string "Jeg vil meget gerne kæmpe med dig igen,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Jeg er i nærheden af {STR_VAR_2}.\n"
	.string "Kom og besøg mig, hvis du er tæt på.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}. Dette er\n"
	.string "{STR_VAR_1}. Hvor mon du befinder\l"
	.string "dig nu?\p"
	.string "Mine POKéMON er fulde af liv. De ser ud\n"
	.string "til at glæde sig til at se dine POKéMON,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Jeg er omkring {STR_VAR_2} nu. Jeg\n"
	.string "håber, du vil opsøge os.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Hej, {PLAYER}{KUN}. Det er mig,\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg bør fortælle dig, at mine POKéMON er\n"
	.string "vokset sig ret robuste på det seneste.\p"
	.string "Jeg vil gerne se dem i kamp med dig,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Vi vil være omkring {STR_VAR_2}. Kom\n"
	.string "og besøg os når som helst!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Åh, hej, {PLAYER}{KUN}! Det er\n"
	.string "{STR_VAR_1}! Har dine POKéMON det\l"
	.string "godt?\p"
	.string "Mine POKéMON har været så sunde, at de\n"
	.string "ikke ser ud til at kunne tabe!\p"
	.string "Jeg ville helt sikkert elske at kæmpe\n"
	.string "mod dig igen.\p"
	.string "Hvis du er i nærheden af\n"
	.string "{STR_VAR_2}, skal du endelig komme\l"
	.string "forbi hos os.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Hej, {PLAYER}{KUN}. Det er {STR_VAR_1}.\n"
	.string "Alt godt, håber jeg.\p"
	.string "åh, ja! Mine POKéMON er meget stærkere\n"
	.string "end før.\p"
	.string "Synes du ikke, vi burde tage en kamp,\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Vi venter på dig omkring\n"
	.string "{STR_VAR_2}.\p"
	.string "Kom og besøg os når som helst, okay?$"

MatchCall_PersonalizedText1::
	.string "Det' mig, bjerg-elskeren!\n"
	.string "{STR_VAR_1}!\p"
	.string "Har du lært at værdsætte bjergene mere,\n"
	.string "siden vi sidst mødtes?\p"
	.string "Jeg ser dig sjældent i bjergene…\p"
	.string "Næste gang mødes vi et sted omkring\n"
	.string "{STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "Det her er {STR_VAR_1}. Hej.\p"
	.string "Jeg var lige ved at fortælle en ny\n"
	.string "TRÆNER om dig.\p"
	.string "Jeg fortalte hende om en stærk TRÆNER\n"
	.string "som opdrætter POKéMON med omhu.\p"
	.string "Jeg håber, du bliver en TRÆNER som alle\n"
	.string "vil beundre.\p"
	.string "Jeg håber, vi mødes igen!$"

MatchCall_PersonalizedText3::
	.string "Hej! Det er {STR_VAR_1}.\p"
	.string "Jeg elsker hvor jeg er lige nu. Det er\n"
	.string "dejligt med søde aromaer!\p"
	.string "Jeg tror nogen plantede BÆR, og de\n"
	.string "sprang i blomst.\p"
	.string "Vi ses igen en anden gang!$"

MatchCall_PersonalizedText4::
	.string "Hej! Tredive års udforskning,\n"
	.string "{STR_VAR_1} til din tjeneste!\p"
	.string "Det ser ud til, at du energisk rejser\n"
	.string "frem og tilbage.\p"
	.string "Har du opdaget nogle nye ruiner? Fortæl\n"
	.string "mig venligst, hvis du har!\p"
	.string "Nu vil jeg tage videre til at udforske\n"
	.string "ruiner.$"

MatchCall_PersonalizedText5::
	.string "Det er {STR_VAR_1}!\p"
	.string "Ved du, hvad jeg laver i dag? Kigger på\n"
	.string "bølger fra stranden!\p"
	.string "Suk… Bølgerne er så skinnende. Havet er\n"
	.string "smukkest herfra. Jeg bliver sulten, så\l"
	.string "hej-hej!$"

MatchCall_PersonalizedText6::
	.string "Smask-tyg… Hej--det er\n"
	.string "{STR_VAR_1}. Jeg elsker at spise på\l"
	.string "stranden.\p"
	.string "Mine POKéMON og jeg har det fantastisk.\n"
	.string "Vi er helt tanket op! Jeg skal en tur i\l"
	.string "vandet. Hej!$"

MatchCall_PersonalizedText7::
	.string "Hej, det er {STR_VAR_1}…\p"
	.string "Jeg er blevet lidt træt af det her med\n"
	.string "hele SEJTRÆNER-titlen…\p"
	.string "Alle tror, at jeg er en perfekt TRÆNER,\n"
	.string "og det får mig til at stræbe efter at\l"
	.string "leve op til den forventning.\p"
	.string "Men det må jeg jo affinde mig med, når\n"
	.string "jeg er en SEJTRÆNER.\p"
	.string "Jeg bliver nødt til at tage mig sammen…\n"
	.string "og bide tænderne sammen.\p"
	.string "Du er den eneste, jeg kan betror mig til\n"
	.string "på den måde.\p"
	.string "Men når jeg ser dig næste gang, bare\n"
	.string "rolig, jeg vil ikke brokke mig!$"

MatchCall_PersonalizedText8::
	.string "Juhu, det er {STR_VAR_1}! Hvordan\n"
	.string "har du det?\p"
	.string "Jeg har opdraget mine POKéMON med dig\n"
	.string "som målet.\p"
	.string "Jeg har ikke tænkt mig at tabe, når vi\n"
	.string "kæmper igen.\p"
	.string "Er det ikke skønt at have TRÆNER-\n"
	.string "venner? Lad os mødes igen!$"

MatchCall_PersonalizedText9::
	.string "Det er {STR_VAR_1}… Lige nu, bag\n"
	.string "dig… Var der ikke noget…?\p"
	.string "Kraften fra POKéMON'erne, som sover her\n"
	.string "på MT. PYRE…\p"
	.string "De fortæller mig om dig…\p"
	.string "Du burde gå hurtigt væk og aldrig kigge\n"
	.string "tilbage…\p"
	.string "Hihi… Farvel…$"

MatchCall_PersonalizedText10::
	.string "Det her er {STR_VAR_1}. Hvordan har\n"
	.string "du det?\p"
	.string "Er det ikke praktisk, at vi kan snakke\n"
	.string "sådan her på afstand?\p"
	.string "Førhen, hvis jeg ville tale med nogen,\n"
	.string "måtte jeg have min far køre mig…\p"
	.string "Jeg burde nok smutte nu. Jeg er glad\n"
	.string "for, at vi snakkede.$"

MatchCall_PersonalizedText11::
	.string "Det er {STR_VAR_1}! Vil du høre\n"
	.string "dette?\p"
	.string "Jeg kan rigtig godt lide SAFARI ZONEN,\n"
	.string "men hver gang jeg besøger den, farer jeg\l"
	.string "vild!\p"
	.string "Al det høje græs! Og det er alt for\n"
	.string "uoverskueligt!\p"
	.string "Jeg føler mig bedre, efter jeg har\n"
	.string "løftet det fra hjertet!\p"
	.string "Jeg tager til SAFARI ZONEN igen! Vi ses!$"

MatchCall_PersonalizedText12::
	.string "Hej, her er {STR_VAR_1}. Ja, korrekt,\n"
	.string "jeg er rig, ja.\p"
	.string "Jeg bør fortælle dig, at min formue er\n"
	.string "vokset, siden sidst vi mødtes.\p"
	.string "Hvad mere er, mine POKéMON er også\n"
	.string "blevet stærkere.\p"
	.string "Jeg kan ikke slippe følelsen af, at\n"
	.string "denne verden eksisterer for mig!\p"
	.string "Åh, der er ingen grund til at sige et\n"
	.string "ord!Alle ved, det er sandt!\p"
	.string "Åh, du må undskylde mig, jeg har dette\n"
	.string "formelle middagsselskab at deltage i.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu… Det er mig, {STR_VAR_1}…\p"
	.string "Kan du gætte, hvad jeg ser? Et par\n"
	.string "{STR_VAR_2} i kamp.\p"
	.string "Måske vil jeg prøve at fange vinderen…\n"
	.string "Ufufufufufu…\p"
	.string "Jeg… Jeg er lidt optaget lige nu. Jeg er\n"
	.string "nødt til at gå.$"

MatchCall_PersonalizedText14::
	.string "Åh, det er {STR_VAR_1}!\p"
	.string "Jeg sad lige og tænkte på, at jeg er ved\n"
	.string "at blive træt af DEN FORLADTE SKIB.\p"
	.string "Men da jeg allerede er her, og jeg gerne\n"
	.string "vil slå dig én gang, så bliver jeg lidt\l"
	.string "længere.\p"
	.string "Hvis du føler dig fristet, hvorfor\n"
	.string "kommer du ikke og besøger mig?\p"
	.string "Jeg tror, at i dag bliver dagen, hvor jeg\n"
	.string "endelig udfordrer ham næste dør til en\l"
	.string "kamp.\p"
	.string "Vi ses!$"

MatchCall_PersonalizedText15::
	.string "Jeg er {STR_VAR_1}! Manden fra\n"
	.string "havet!\p"
	.string "Ved du hvad jeg tænker?\p"
	.string "De TRÆNERE derude på havet er de\n"
	.string "sejeste af de seje!\p"
	.string "Du burde lære af mig og træne på havet…\p"
	.string "Ups, kæmpe bølge på vej!\p"
	.string "Det er en fantastisk træningsmulighed!\n"
	.string "Beklager, men jeg bliver nødt til at gå!$"

MatchCall_PersonalizedText16::
	.string "Det er {STR_VAR_1}! Lyt, jeg har\n"
	.string "undervist i karate til mine POKéMON.\p"
	.string "Men nu er de bedre end mig! Jeg har kun\n"
	.string "tabt til dem!\p"
	.string "Men selvom jeg taber til POKéMON, vil\n"
	.string "jeg ikke tabe til en ANDEN TRÆNER, nej,\l"
	.string "hr.!\p"
	.string "Vi er nødt til at kæmpe igen! Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "Det' mig, {STR_VAR_1}. Hvordan går\n"
	.string "det med dine rejser?\p"
	.string "…Wow, er det rigtigt? Det lyder enormt\n"
	.string "spændende!\p"
	.string "Jeg tror, jeg kunne skrive en sang om en\n"
	.string "af dine oplevelser.\p"
	.string "…Nå, hey, jeg føler det. Jeg hører riffs i\n"
	.string "mit hoved.\p"
	.string "Jeg må nok få skrevet denne melodi\n"
	.string "ordentligt ned, så jeg bliver nødt til at\l"
	.string "flyve! Vi ses!$"

MatchCall_PersonalizedText18::
	.string "Dette er {STR_VAR_1}… Hør min nye\n"
	.string "sang.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Hvorfor er du så {STR_VAR_2}?\l"
	.string "Hvorfor kan jeg ikke være dig,\l"
	.string "{STR_VAR_2}? Lala, {STR_VAR_2}\l"
	.string "og {STR_VAR_1}, {STR_VAR_1} og\l"
	.string "{STR_VAR_2}…\p"
	.string "Gentag omkvædet, fade…$"

MatchCall_PersonalizedText19::
	.string "Jeg er {STR_VAR_1}, ved du nok,\n"
	.string "eksperten i camping!\p"
	.string "Da vi kæmpede, kunne jeg ikke undgå at\n"
	.string "tabe til dig.\p"
	.string "Trods alt, min ekspertise ligger inden\n"
	.string "for camping.\p"
	.string "Men uanset om jeg vinder eller taber, så\n"
	.string "kan jeg godt lide at kæmpe, når jeg\l"
	.string "camperer.\p"
	.string "Kom og kæmp med os igen, okay? Åh, og\n"
	.string "lad os også tage på camping sammen!$"

 MatchCall_PersonalizedText20::
	.string "Det' mig, mig, {STR_VAR_1}!\p"
	.string "Jeg vil gerne bestige andre bjerge\n"
	.string "end dette, for at være ærlig.\p"
	.string "Men jeg er ikke sikker på, om der er\n"
	.string "damer som på MT. CHIMNEY.\p"
	.string "Hvis du kender nogle andre bjerge\n"
	.string "med damer omkring, så lad mig vide!\p"
	.string "Høhøhø, vi ses!$"

MatchCall_PersonalizedText21::
	.string "… … … … … … … … … … … … Det er\n"
	.string "{STR_VAR_1}…\p"
	.string "… … … … … … … … … … … … Det var alt for i\n"
	.string "dag…$"

MatchCall_PersonalizedText22::
	.string "Dette er {STR_VAR_1}. I dag fik jeg\n"
	.string "lysten til at chatte med dig.\p"
	.string "Min lyst til at besejre dig vokser dag\n"
	.string "for dag og nat for nat.\p"
	.string "Har du en rival ligesom det, ja? Jeg ville\n"
	.string "ønske, det var mig…\p"
	.string "Jeg er glad for, at du lyttede til mig. Vi\n"
	.string "ses!$"

MatchCall_PersonalizedText23::
	.string "Det er {STR_VAR_1}.\p"
	.string "Når der er en stærk TRÆNER i nærheden,\n"
	.string "kan jeg nogle gange mærke det på en\l"
	.string "eller anden måde.\p"
	.string "Kom du tæt forbi, {PLAYER}{KUN}? Måske var\n"
	.string "det dig.\p"
	.string "Jeg venter på dit besøg. Hej hej!$"

MatchCall_PersonalizedText24::
	.string "Hej, det er {STR_VAR_1}. Du lyder\n"
	.string "godt, {PLAYER}{KUN}.\p"
	.string "Jeg har rejst rundt om i verden, men jeg\n"
	.string "må sige, at jeg har taget en stor\l"
	.string "forkærlighed for dette område.\p"
	.string "Jeg planlægger at blive her et stykke\n"
	.string "tid. Måske kan vi mødes igen?\p"
	.string "Jeg har ikke glemt dine dazzlende\n"
	.string "teknikker.\p"
	.string "Jeg håber på en revanche.$"

MatchCall_PersonalizedText25::
	.string "Hulk... Det er... {STR_VAR_1}...\n"
	.string "...Græd...\p"
	.string "ROXANNE gav mig skæld ud i dag i skolen.\p"
	.string "Men jeg kan godt lide hende.\p"
	.string "ROXANNE fortæller mig præcist, hvad jeg\n"
	.string "gjorde forkert, så jeg kan lære af det.\p"
	.string "Jeg vil helt sikkert tage til\n"
	.string "TRÆNER-SKOLEN i morgen!\p"
	.string "Vi ses senere!$"

MatchCall_PersonalizedText26::
	.string "Det er {STR_VAR_1}!\p"
	.string "ROXANNE lod mig kæmpe mod hende i går.\p"
	.string "Resultaterne… Forfærdelige, som om du\n"
	.string "havde brug for at spørge.\p"
	.string "Men jeg var henrykt over, at ROXANNE\n"
	.string "ville lade mig udfordre hende!\p"
	.string "Du ville ikke tro, hvor meget mere jeg\n"
	.string "beundrer hende!\p"
	.string "Jeg vil virkelig fokusere og arbejde! Nu\n"
	.string "må jeg hellere smutte!$"

MatchCall_PersonalizedText27::
	.string "Hej, det' ANNA! Jeg er sammen med min\n"
	.string "junior-partner MEG igen i dag.\p"
	.string "Jeg elsker virkelig at passe på MEG og\n"
	.string "POKéMON. De er så søde!\p"
	.string "Jeg ville ønske, jeg kunne passe på dem,\n"
	.string "som om de var mine søskende!\p"
	.string "Åh, hej, MEG! Fik du bollerne?\p"
	.string "Hvad? Nej, nej, jeg behandler dig ikke\n"
	.string "som min personlige slave!\p"
	.string "Du tabte kampen, så du skal gå og købe\n"
	.string "brødet som straf!\p"
	.string "Jeg ville aldrig behandle dig som en\n"
	.string "slave, MEG! Du er for speciel for mig!\p"
	.string "Jeg er nødt til at gå nu. Det er tid til\n"
	.string "vores snack!$"

MatchCall_PersonalizedText28::
	.string "Jeg elsker POKéMON! Det er\n"
	.string "{STR_VAR_1} fra FANKLUBBEN!\p"
	.string "Du bliver nødt til at høre dette! Min\n"
	.string "søde POKéMON…\p"
	.string "Snøft! Wahaha! Jeg kan ikke sige mere!\n"
	.string "Det er en hemmelighed! Det er bare alt\l"
	.string "for sødt for ord!\p"
	.string "Åh, min søde {STR_VAR_2} beder om en\n"
	.string "{POKEBLOCK}!\p"
	.string "Det er billedet af cuteness!\p"
	.string "Beklager, men jeg kan ikke snakke nu! Du\n"
	.string "må høre dette næste gang!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "Det her er {STR_VAR_1}! Jeg kan slet\n"
	.string "ikke vente med at fortælle dig om min\l"
	.string "elskede POKéMON!\p"
	.string "Vent, du bliver nødt til at høre om min\n"
	.string "elskede {STR_VAR_2}.\p"
	.string "Når nogen rører ved den, springer den\n"
	.string "straks ind i mine arme!\p"
	.string "Åh… Åh… Kan der være noget mere saligt?\p"
	.string "Åh, det føles så himmelsk!\p"
	.string "Jeg er så glad for, at jeg kunne dele\n"
	.string "lidt af min glæde med dig.\p"
	.string "Nå, jeg må videre. Hej, så!$"

  MatchCall_PersonalizedText30::
	.string "Jeg er… {STR_VAR_1}.\n"
	.string "Folk kalder mig en EKSPERT.\p"
	.string "Men der er en ting, jeg ved.\n"
	.string "Jeg kunne ikke være en EKSPERT\n"
	.string "alene med min egen kraft.\p"
	.string "Kun med hjælp fra POKéMON kan\n"
	.string "en TRÆNER blive en EKSPERT.\p"
	.string "Hov! Jeg tror, jeg lige sagde noget\n"
	.string "dybt og profondt!\p"
	.string "Jeg vil efterlade dig i godt humør!$"

MatchCall_PersonalizedText31::
	.string "Det er {STR_VAR_1}. Jeg er glad for\n"
	.string "at snakke med dig!\p"
	.string "Jeg føler mig i live og fornyet mens jeg\n"
	.string "slapper af i denne varme kilde.\p"
	.string "Jeg har kæmpet mod unge TRÆNERE siden\n"
	.string "vi mødtes, men du er stadig den bedste i\l"
	.string "flokken.\p"
	.string "Jeg forestiller mig, at du vil blive en\n"
	.string "EKSPERT i din alderdom! Ha-ha-ha…$"

MatchCall_PersonalizedText32::
	.string "Jubii! Det er {STR_VAR_1}! Hvad så? \p"
	.string "Måske er det bare mig, men når jeg\n"
	.string "vinder kampe, virker mine shorts lidt, ja,\l"
	.string "bedre. Fysisk.\p"
	.string "Hvad mener jeg med det? Det er lidt\n"
	.string "svært at forklare, men… Hvordan skulle\l"
	.string "jeg sige det nu… Mine shorts føles\l"
	.string "silkebløde!\p"
	.string "Og da jeg kæmpede mod dig, {PLAYER}{KUN},\n"
	.string "føltes mine shorts ulækre og grove.\p"
	.string "… … … … … … Troede du virkelig på det?\n"
	.string "Haha, det var det hele! Hej så!$"

MatchCall_PersonalizedText33::
	.string "Hej! {STR_VAR_1} her!\p"
	.string "Som altid fisker jeg med vild\n"
	.string "hengivenhed!\p"
	.string "Er der andre steder, hvor jeg kan fiske\n"
	.string "end havet og floderne?\p"
	.string "Jeg får disse kraftige trang til at\n"
	.string "fiske nærmest overalt!\p"
	.string "Åh, søren! Mit snøre er filtreret ind!\p"
	.string "Skal lige afsted! Find mig nogle nye\n"
	.string "fiskesteder!$"

MatchCall_PersonalizedText34::
	.string "Hej, du der! Det er {STR_VAR_1}.\n"
	.string "Tager du det roligt?\p"
	.string "Lige siden jeg var barn, du ved, har jeg\n"
	.string "altid været afslappet, hva'?\p"
	.string "Jeg har aldrig været til at stresse eller\n"
	.string "skynde på tingene.\p"
	.string "Men kan du tro det, jeg er nu en\n"
	.string "TRIATLET.\p"
	.string "Man kan aldrig vide, hvor livet fører en\n"
	.string "hen, hvis du forstår mig.\p"
	.string "Du er en TRÆNER nu, men hvem ved, hvad\n"
	.string "fremtiden bringer, hva'?\p"
	.string "Forestil dig som en lærer, eller måske en\n"
	.string "kunstner. Fedt, hva'?\p"
	.string "Men, hey, hold det chill. Tag det roligt.\n"
	.string "Vi ses.$"

MatchCall_PersonalizedText35::
	.string "Dette er {STR_VAR_1}! Jeg cykler lige\n"
	.string "nu.\p"
	.string "Jeg elsker at svømme og løbe, men\n"
	.string "cykling er min første kærlighed!\p"
	.string "Det får hele min krop til at føles, som\n"
	.string "om jeg er ét med vinden.\p"
	.string "Det opløfter mig, som om jeg fløj!\p"
	.string "Okay! I dag vil jeg sætte en ny\n"
	.string "CYKELVEJS rekord!\p"
	.string "Du bør også tage udfordringen op! Vi\n"
	.string "ses!$"

MatchCall_PersonalizedText36::
	.string "Hej, det er {STR_VAR_1}! Jeg er lige\n"
	.string "midt i en triatlon!\p"
	.string "Men hey, jeg har altid tid til at sludre\n"
	.string "lidt!\p"
	.string "At træne med POKéMON føles rigtig godt!\p"
	.string "Uden at udveksle ord, synkroniserer vi\n"
	.string "næsten som om vi delte et hjerte.\p"
	.string "Det er inspirerende!\p"
	.string "Puh... At snakke mens jeg løber... Jeg\n"
	.string "mister pusten… Puh... Skal...afsted...$"

MatchCall_PersonalizedText37::
	.string "Hej, det er {STR_VAR_1}. Hvis du vil\n"
	.string "forbedre udholdenheden, er\l"
	.string "højde-træning vejen frem!\p"
	.string "Prøv at løbe på et bjergtop. Du vil være\n"
	.string "forpustet på ingen tid!\p"
	.string "Jeg mangler også ilt! Vi ses!$"

MatchCall_PersonalizedText38::
	.string "Åh, det er {STR_VAR_1}, hej.\p"
	.string "Jeg har svømmet en masse, men jeg kan\n"
	.string "stadig ikke nå til EVERGRANDE.\p"
	.string "Måske svømmer jeg bare rundt i cirkler.\p"
	.string "Nej, nej, det kan ikke være muligt.\n"
	.string "Hahaha. Pas på!$"

MatchCall_PersonalizedText39::
	.string "Hej, det er {STR_VAR_1}… Ups!\p"
	.string "Plask!\p"
	.string "Blup-blup-blup-blup…\p"
	.string "Plumps!\p"
	.string "Vift-vift! Vift-vift!\p"
	.string "Hej! Undskyld det! Jeg smurte lige lidt\n"
	.string "solcreme på.\p"
	.string "Så forsvandt min POKéNAV lige ud af min\n"
	.string "hånd og ned i vandet!\p"
	.string "Men, puha, DEVONs POKéNAV er bygget\n"
	.string "robust. Det overlevede den dukkert!\p"
	.string "Nå, jeg er optaget af at solbade, så lad\n"
	.string "os snakke en anden gang.$"

MatchCall_PersonalizedText40::
	.string "Hej, det er {STR_VAR_1}.\p"
	.string "Af de tre triathlon-events, kan jeg\n"
	.string "bedst lide at svømme.\p"
	.string "Men hvis jeg bliver i havet for længe,\n"
	.string "bliver jeg ikke helt rynket?\p"
	.string "Åh, triathlon er så krævende en test af\n"
	.string "menneskelig udholdenhed! Hej!$"

MatchCall_PersonalizedText41::
	.string "Hej, {PLAYER}{KUN}. {STR_VAR_1} her.\p"
	.string "Hvordan har dine POKéMON det?\p"
	.string "Mine DRAGE POKéMON ser ud til at være i\n"
	.string "topform. Vi ses senere.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} her.\p"
	.string "Min {STR_VAR_2} er blevet endnu\n"
	.string "sejere end sidste gang.\p"
	.string "Jeg vil ikke tabe til dig igen. Du venter\n"
	.string "bare til næste gang!\p"
	.string "Vi ses!$"

MatchCall_PersonalizedText43::
	.string "Det er {STR_VAR_1} her.\p"
	.string "Jeg har fortsat med mine studier i\n"
	.string "kunsten at skjule mig.\p"
	.string "Men jeg har været for succesfuld. Ingen\n"
	.string "har været i stand til at finde mig. Min\l"
	.string "succes gør mig ensom…\p"
	.string "Som røg forsvinder jeg! Farvel!$"

MatchCall_PersonalizedText44::
	.string "Det her er {STR_VAR_1}. Jeg har\n"
	.string "holdt mig i træning siden vi mødtes.\p"
	.string "Min {STR_VAR_2} bliver ret sej.\p"
	.string "Træning på en strand er effektiv,\n"
	.string "præcis som jeg troede. Hej hej!$"

MatchCall_PersonalizedText45::
	.string "Hvordan har du det? Her er\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg spekulerer på, hvornår denne \n"
	.string "klamme vulkanske aske holder op med at\l"
	.string "falde ned?\p"
	.string "Hvis det bliver for dybt, vil det  dække\n"
	.string "mønsteret på min parasol…\p"
	.string "Lad os love at mødes igen!$"

MatchCall_PersonalizedText46::
	.string "Hej, {STR_VAR_1} her.\p"
	.string "Vidste du, at det er lettere at flyde i\n"
	.string "havet end i en pool?\p"
	.string "Bare ved at ligge stille vil din krop\n"
	.string "flyde af sig selv.\p"
	.string "Men hvis du flyder for længe, så pas på\n"
	.string "ikke at blive båret for langt ud.\p"
	.string "…Hvor er jeg egentlig? Jeg må hellere\n"
	.string "smutte!$"

MatchCall_PersonalizedText47::
	.string "Hej, {PLAYER}{KUN}! Det her er\n"
	.string "{STR_VAR_1}. Jeg er oppe i bjergene\l"
	.string "lige nu.\p"
	.string "Men jorden er alt for ujævn. Jeg kan\n"
	.string "ikke slå mit telt op her…\p"
	.string "Åh, jeg fik en genial idé!\p"
	.string "Måske kan jeg få mine POKéMON til at\n"
	.string "banke jorden flad her!\p"
	.string "Det vil jeg prøve! Farvel!$"

MatchCall_PersonalizedText48::
	.string "Hej, hej, det er {STR_VAR_1}!\p"
	.string "Jeg opdrætter POKéMON med LIV! Vi\n"
	.string "arbejder meget hårdt!\p"
	.string "Kan vi blive nummer et hvis vi  prøver\n"
	.string "endnu hårdere? Hej hej!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} her!\p"
	.string "Jeg er en SØMAND, men jeg er ikke på en\n"
	.string "båd nu.\p"
	.string "Det får mig til at tænke--hvad skal en\n"
	.string "SØMAND på land kaldes?\p"
	.string "Det har jeg tænkt på mens jeg stirrede\n"
	.string "ud over bølgerne.\p"
	.string "Helt rigtigt, næste gang!$"

MatchCall_PersonalizedText50::
	.string "Det er {STR_VAR_1}. Nå? Fangede du\n"
	.string "flere POKéMON?\p"
	.string "Hvis du fanger en ny POKéMON, skal du\n"
	.string "komme og vise mig.\p"
	.string "Jeg vil ikke tigge om den, ærligt. Jeg\n"
	.string "venter. Vi ses.$"

MatchCall_PersonalizedText51::
	.string "Dette er {STR_VAR_1}.\p"
	.string "Opdrætter du dine POKéMON på den\n"
	.string "optimale måde?\p"
	.string "Luften er ren, hvor jeg er. Det er det\n"
	.string "perfekte miljø for at opdrætte POKéMON.\p"
	.string "Hvis du vil fokusere på at opdrætte\n"
	.string "POKéMON, så skulle du tage til\l"
	.string "{STR_VAR_2}. Pas nu godt på.$"

MatchCall_PersonalizedText52::
	.string "Hej, det er {STR_VAR_1}.\p"
	.string "Jeg gav en {POKEBLOCK} til min\n"
	.string "{STR_VAR_2}. Den nød det meget.\p"
	.string "Det ser ud til, at POKéMON har deres\n"
	.string "præferencer med {POKEBLOCK}S.\p"
	.string "Synes du også det er spændende. Pas nu\n"
	.string "godt på.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} her.\p"
	.string "Hvis du samarbejder med POKéMON, kan\n"
	.string "man være tryg i det vilde.\p"
	.string "Alle burde indse det og samarbejde mere\n"
	.string "med POKéMON.\p"
	.string "Det ville være ideelt. Det synes jeg\n"
	.string "virkelig.\p"
	.string "Jeg synes, du er på rette spor! Vi ses\n"
	.string "senere!$"

MatchCall_PersonalizedText54::
	.string "Hej, det er {STR_VAR_1}. Du ved jo,\n"
	.string "TRÆNEREN der altid er forberedt!\p"
	.string "{PLAYER}{KUN}, har du nok genstande? Er\n"
	.string "dine POKéMON klar til kamp?\p"
	.string "At holde alt perfekt omkring dig hele\n"
	.string "tiden er hemmeligheden til at fortsætte\l"
	.string "din rejse.\p"
	.string "Jeg må hellere tjekke mine egne forråd!\n"
	.string "Vær opmærksom!$"

MatchCall_PersonalizedText55::
	.string "Det er {STR_VAR_1}! Det er\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_2} er en meget travl\n"
	.string "gennemgangsvej, så jeg bliver udfordret\l"
	.string "af alle slags TRÆNERE hver dag.\p"
	.string "I dag vandt jeg fem kampe og tabte kun\n"
	.string "tre!\p"
	.string "Hvordan gik det for dig i dag? Fortæl\n"
	.string "mig om det næste gang, okay?$"

MatchCall_PersonalizedText56::
	.string "Det' mig, {STR_VAR_1}.\p"
	.string "Jeg er populær, fordi jeg har en masse\n"
	.string "BÆST POKéMON, ikke?\p"
	.string "Nå, jeg tog en flok af mine\n"
	.string "yndlingsbæster med i skole i dag.\p"
	.string "Pigen, jeg kan lide, begyndte at græde!\p"
	.string "Grin du bare, hvis du vil.\p"
	.string "Jeg bliver nødt til at prøve at lære\n"
	.string "hende, hvad der gør BÆST POKéMON så\l"
	.string "tiltrækkende.\p"
	.string "Snøft… Vi ses!$"

MatchCall_PersonalizedText57::
	.string "Hovsa! Hovsa! Hovsa! Hovsa!\p"
	.string "Hej! Det er {STR_VAR_1}! Hovsa!\n"
	.string "Hovsa!\p"
	.string "Prøver at snakke… Mens jeg klatrer… Er\n"
	.string "barsk motion… Hovsa! Hovsa!\p"
	.string "Åh! Av… Det er stejlere nu… Vi\n"
	.string "snakker…en anden gang… Hovsa! Hovsa!\l"
	.string "Hovsa!$"

MatchCall_PersonalizedText58::
	.string "Åh, hej!\p"
	.string "Jeg leder stadig efter skatte sammen\n"
	.string "med KIRA!\p"
	.string "Måske er der slet ingen skat her…\p"
	.string "Men det vigtigste er, at jeg leder\n"
	.string "sammen med KIRA.\p"
	.string "Åh, hey, KIRA! H-hvorfor er du sur?\p"
	.string "Jeg ignorerer dig ikke, skat! Du er min\n"
	.string "eneste ene!\p"
	.string "…{PLAYER}, jeg er nødt til at gå, hej!$"

MatchCall_PersonalizedText59::
	.string "Det er {STR_VAR_1}!\p"
	.string "Jeg var i DEWFORDs GYM igen til træning.\p"
	.string "BRAWLY, GYM LEADEREN, virker hårdere\n"
	.string "nu.\p"
	.string "Noget med at være hærdet af de vilde\n"
	.string "bølger…\p"
	.string "Men han er stadig lige sej. Damerne\n"
	.string "tilbeder ham! Det gør mig faktisk\l"
	.string "misundelig.\p"
	.string "Mon… Er hans ven BRUNO på samme måde\n"
	.string "som BRAWLY?\p"
	.string "Du ved, svedig og lugtende, og\n"
	.string "tilbøjelig til at kalde folk “stor bølge,”\l"
	.string "den slags.\p"
	.string "Men hør her, denne jalousi er ikke særlig\n"
	.string "anstændig, er den?\p"
	.string "Lad os glemme denne snak nogensinde\n"
	.string "fandt sted, hvad siger du? Farvel!$"

MatchCall_PersonalizedText60::
	.string "Det er en fornøjelse at chatte med en\n"
	.string "ung TRÆNER som dig.\p"
	.string "Jeg forestiller mig, at du vil fortsætte\n"
	.string "med at nyde POKéMON uanset din alder.\p"
	.string "Ville det ikke være godt, hvis du havde\n"
	.string "et partnerskab ligesom vores?\p"
	.string "Selvfølgelig, {PLAYER}{KUN}, du nyder\n"
	.string "allerede tilliden og selskabet af dine\l"
	.string "POKéMON nu.\p"
	.string "Du besidder allerede evnen til\n"
	.string "langvarige og nære forhold!\p"
	.string "Hahaha! Vær aldrig modløs!$"

MatchCall_PersonalizedText61::
	.string "Hej, det er {STR_VAR_1}! Vi har lige\n"
	.string "vundet en kamp!\p"
	.string "Vi vinder ikke så tit, men det var den\n"
	.string "seje SVØMMER fyr.\p"
	.string "Min søster var helt vild!\p"
	.string "Hun ville gerne late som om hun var svag\n"
	.string "for at gøre indtryk!\p"
	.string "Hun skælder altid ud på mig uanset om vi\n"
	.string "vinder eller taber!\p"
	.string "{PLAYER}{KUN}, kan du sige noget til hende\n"
	.string "næste gang?\p"
	.string "Okay, vi ses!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} her, ja. Jeg sejlede ud\n"
	.string "på havet i går.\p"
	.string "Jeg havde håbet at finde et nyt\n"
	.string "ruinhjørne at udforske.\p"
	.string "Men strømmene syntes på en eller anden\n"
	.string "måde at bringe mig tilbage til\l"
	.string "udgangspunktet.\p"
	.string "Jeg er stadig svag i kampene... Må I\n"
	.string "endelig grine ad mig… Men jeg giver ikke\l"
	.string "op.\p"
	.string "Min dag vil komme, når jeg opdager en ny\n"
	.string "ruin!\p"
	.string "Det er alt, jeg har at sige! Farvel for\n"
	.string "nu!$"

MatchCall_PersonalizedText63::
	.string "Hej med dig! Det er mig, {STR_VAR_1}!\n"
	.string "Jeg er på RUTE 108 nu! Med andre ord,\l"
	.string "hvor jeg altid er!\p"
	.string "I dag svømmede en fantastisk SVØMMER\n"
	.string "forbi mig!\p"
	.string "Så jeg forskrækkede hende med et råb!\p"
	.string "Og hun gav mig et trættende blik!\p"
	.string "Det er alt fra RUTE 108! Præsenteret af\n"
	.string "{STR_VAR_1}!$"

MatchCall_PersonalizedText64::  
	.string "Det er {STR_VAR_1}!\p"  
	.string "Jeg er lidt optaget, men jeg\n"  
	.string "tænkte, at jeg burde fortælle dig,\l"  
	.string "at jeg har slået fem TRÆNERE igen i dag.\p"  
	.string "Hvis jeg holder dette tempo, kan jeg\n"  
	.string "sandsynligvis slå dig næste gang.\p"  
	.string "Jeg tror, vi bliver gode rivaler,\n"  
	.string "du og jeg. Farvel for nu!$"

  MatchCall_BattleFrontierStreakText1::
	.string "Hej! Det er {STR_VAR_1}.\n"
	.string "Jeg har hørt nyhederne!\p"
	.string "De siger, at du gjorde det\n"
	.string "fremragende ved {STR_VAR_2}.\p"
	.string "Det er fantastisk, {STR_VAR_3} lige\n"
	.string "sejre? Vi ses!$"

MatchCall_BattleFrontierStreakText2::
	.string "Hej, det er {STR_VAR_1}! Jeg har hørt\n"
	.string "om dig!\p"
	.string "De sagde, at du vandt {STR_VAR_3}\n"
	.string "på stribe kampe ved {STR_VAR_2}.\p"
	.string "Det er specielt! Jeg burde også prøve\n"
	.string "hårdere! Vi ses!$"

MatchCall_BattleFrontierStreakText3::
	.string "Hej der, {PLAYER}! Det er mig,\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg hørte, at du har været en stjerne i\n"
	.string "{STR_VAR_2}!\p"
	.string "En stor\n"
	.string "{STR_VAR_3}-vindendestreak… Det er\l"
	.string "da en imponerende rekord, ikk'?\p"
	.string "Jeg bliver nødt til at skærpe mig! Vi ses\n"
	.string "snart!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hey, {PLAYER}{KUN}. {STR_VAR_1} her.\n"
	.string "Hvad så?\p"
	.string "Der går et rygte om, at du har hevet\n"
	.string "{STR_VAR_3} sejre i træk hjem på\l"
	.string "{STR_VAR_2}.\p"
	.string "Jeg bliver nok nødt til også at skærpe\n"
	.string "mig. Vi ses!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hej med dig, {PLAYER}{KUN}! Det er\n"
	.string "{STR_VAR_1}.\p"
	.string "Du var ved {STR_VAR_2} og vandt\n"
	.string "{STR_VAR_3} kampe i træk? Er det\l"
	.string "ikke noget!\p"
	.string "Jeg bliver nødt til at arbejde mere med\n"
	.string "mine POKéMON. Vi ses snart!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hey, {PLAYER}{KUN}. {STR_VAR_1} her.\n"
	.string "Hvordan har du det?\p"
	.string "Forresten, jeg hørte, at du opnåede\n"
	.string "{STR_VAR_3} lige sejre på\l"
	.string "{STR_VAR_2}.\p"
	.string "Det inspirerer mig til at fokusere på at\n"
	.string "opgradere mit hold.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Øh, {PLAYER}{KUN}? {STR_VAR_1} her…\p"
	.string "Åh ja, du var henne ved {STR_VAR_2},\n"
	.string "ikke sandt?\p"
	.string "Og du vandt {STR_VAR_3} kampe i\n"
	.string "træk.\p"
	.string "Åh, der går en sjælden POKéMON! Jeg er\n"
	.string "nødt til at gå!$"

MatchCall_BattleFrontierStreakText8::
	.string "Åh, {PLAYER}{KUN}, hvordan har du det? Det\n"
	.string "er {STR_VAR_1} der taler. Jeg håber,\l"
	.string "du har det godt.\p"
	.string "Åh, men det har du. Jeg har hørt at du\n"
	.string "har vundet {STR_VAR_3} kampe i træk\l"
	.string "på {STR_VAR_2}.\p"
	.string "Det er meget imponerende! Jeg håber, du\n"
	.string "forbliver succesfuld.$"

MatchCall_BattleFrontierStreakText9::
	.string "Åh, {PLAYER}{KUN}, hej! Det er\n"
	.string "{STR_VAR_1}!\p"
	.string "Jeg hørte det! Din\n"
	.string "{STR_VAR_3}-vind-stime på\l"
	.string "{STR_VAR_2}!\p"
	.string "Det er så sejt! Jeg bliver nødt til at\n"
	.string "anstrenge mig mere også!$"

MatchCall_BattleFrontierStreakText10::
	.string "Hej, {PLAYER}{KUN}… Det er {STR_VAR_1}.\p"
	.string "Du vandt {STR_VAR_3} kampe i træk\n"
	.string "på {STR_VAR_2}?\p"
	.string "Det er virkelig en præstation. Jeg\n"
	.string "bliver nødt til at arbejde hårdere.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}. Dette er\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg har hørt, at du er skrækken fra\n"
	.string "{STR_VAR_2}?\p"
	.string "Du vandt, hvad, {STR_VAR_3} kampe i\n"
	.string "træk?\p"
	.string "Du er god, dig. Jeg spekulerer på, hvor\n"
	.string "mange jeg kan vinde?$"

MatchCall_BattleFrontierStreakText12::
	.string "Hej, {PLAYER}{KUN}. Det er mig,\n"
	.string "{STR_VAR_1}. Har du det godt?\p"
	.string "Nogen har fortalt mig om dig. Hvordan du\n"
	.string "vandt {STR_VAR_3} på stribe i et\l"
	.string "sted kaldet {STR_VAR_2}?\p"
	.string "Det er en historie værd at høre. Vi ses!$"

MatchCall_BattleFrontierStreakText13::
	.string "Nå, hej, {PLAYER}{KUN}! Det er\n"
	.string "{STR_VAR_1}! Jeg håber, du har det\l"
	.string "godt.\p"
	.string "De siger, du har vundet {STR_VAR_3}\n"
	.string "rette kampe ved {STR_VAR_2}.\p"
	.string "Jeg beundrer dit energiniveau! Hej så.$"

  MatchCall_BattleFrontierStreakText14::
	.string "Hej, {PLAYER}{KUN}.\n"
	.string "Det er {STR_VAR_1}.\p"
	.string "Jeg har hørt om dig!\n"
	.string "Vandt du ikke lige {STR_VAR_3} kampe i\n"
	.string "{STR_VAR_2} i træk?\p"
	.string "Du er en inspiration!\n"
	.string "Hej-hej!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hej! Det er {STR_VAR_1}. Jeg hørte\n"
	.string "nyheden!\p"
	.string "De siger, at du gjorde fremragende på\n"
	.string "{STR_VAR_2}.\p"
	.string "Det er fantastisk - {STR_VAR_3} lige\n"
	.string "sejre? Vi ses!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hej, det er {STR_VAR_1}! Jeg har hørt\n"
	.string "om dig!\p"
	.string "De sagde, at du vandt {STR_VAR_3}\n"
	.string "på række kampe ved {STR_VAR_2}.\p"
	.string "Det er særligt! Jeg bør også prøve\n"
	.string "hårdere! Vi ses!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hej med dig, {PLAYER}! Det er mig,\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg hørte, at du har været ret vild på\n"
	.string "{STR_VAR_2}-banen!\p"
	.string "En stor {STR_VAR_3}-sejr-stime…\n"
	.string "Det er et stort rekord, ikk' det?\p"
	.string "Jeg må hellere få styr på mit spil! Vi\n"
	.string "ses snart!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hey, {PLAYER}! {STR_VAR_1} here.\n"
	.string "Hvad så?\p"
	.string "Der går et rygte om, at du har vundet\n"
	.string "{STR_VAR_3} kampe i træk på\l"
	.string "{STR_VAR_2}.\p"
	.string "Nu må jeg også skærpe mig. Vi ses!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}.\p"
	.string "Var du på {STR_VAR_2} og vandt\n"
	.string "{STR_VAR_3} kampe i træk? Er det\l"
	.string "ikke noget!\p"
	.string "Mig? Jeg vil sige, at jeg er på vej frem.\n"
	.string "Vi ses snart!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hej {PLAYER}{KUN}. {STR_VAR_1} her.\n"
	.string "Hvordan har du det?\p"
	.string "Forresten hørte jeg, at du formåede at\n"
	.string "vinde {STR_VAR_3} gange i træk hos\l"
	.string "{STR_VAR_2}.\p"
	.string "Jeg bliver nødt til at anstrenge mig\n"
	.string "mere! Vi ses snart!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Øh, {PLAYER}{KUN}? {STR_VAR_1} her…\p"
	.string "Nå ja, du var ovre på {STR_VAR_2},\n"
	.string "ikke?\p"
	.string "Og du vandt {STR_VAR_3} kampe i\n"
	.string "træk.\p"
	.string "Åh, der går en sjælden POKéMON! Jeg\n"
	.string "bliver nødt til at gå!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Åh, {PLAYER}{KUN}, hvordan har du det? Det\n"
	.string "er {STR_VAR_1}, der taler. Jeg håber,\l"
	.string "du har det godt.\p"
	.string "Åh, men det har du. Jeg har hørt, at du\n"
	.string "har vundet {STR_VAR_3} kampe i træk\l"
	.string "på {STR_VAR_2}.\p"
	.string "Det er meget imponerende! Jeg bliver\n"
	.string "nødt til at arbejde på mine POKéMON\l"
	.string "også!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}!\p"
	.string "Jeg hørte, din\n"
	.string "{STR_VAR_3}-sejr-række på\l"
	.string "{STR_VAR_2}!\p"
	.string "Det er så sejt! Jeg må hellere prøve\n"
	.string "hårdere også!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Åh, {PLAYER}{KUN}, hej… Det er\n"
	.string "{STR_VAR_1}.\p"
	.string "Du har vundet {STR_VAR_3} på stribe\n"
	.string "ved {STR_VAR_2}?\p"
	.string "Det er virkelig en præstation. Jeg\n"
	.string "bliver nødt til at arbejde hårdere.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Åh, {PLAYER}{KUN}. Det er {STR_VAR_1}.\p"
	.string "Jeg har hørt, at du er skrækken fra\n"
	.string "{STR_VAR_2}.\p"
	.string "Du har vundet, hvad, {STR_VAR_3}\n"
	.string "kampe i træk?\p"
	.string "Du er god, dig. Jeg undrer mig på, hvor\n"
	.string "mange jeg kan vinde?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hej, {PLAYER}{KUN}. Det er mig,\n"
	.string "{STR_VAR_1}. Har du det godt?\p"
	.string "Nogen sendte besked om dig. Hvordan du\n"
	.string "vandt {STR_VAR_3} på stribe ved et\l"
	.string "sted kaldet {STR_VAR_2}?\p"
	.string "Det er en ganske historie. Vi ses!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}!\n"
	.string "Jeg håber, du har det godt.\p"
	.string "De siger, at du har vundet\n"
	.string "{STR_VAR_3} kampe i træk på\l"
	.string "{STR_VAR_2}.\p"
	.string "Jeg beundrer dit energiniveau! Hej da.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Hej, {PLAYER}{KUN}. Det her er\n"
	.string "{STR_VAR_1}. Jeg har hørt om dig!\p"
	.string "Vandt du ikke lige {STR_VAR_3}\n"
	.string "kampe i træk på {STR_VAR_2}?\p"
	.string "Du er en inspiration! Hej-hej!$"

MatchCall_BattleDomeText1::
	.string "Hej! {PLAYER}? Hej, det er\n"
	.string "{STR_VAR_1}! Jeg hørte nyhederne!\p"
	.string "Du blev mester hos {STR_VAR_2}\n"
	.string "{STR_VAR_3} gange?\p"
	.string "Det er fantastisk! Jeg bliver nødt til\n"
	.string "at gøre det bedre! Vi ses!$"

MatchCall_BattleDomeText2::
	.string "Hej, det er {STR_VAR_1}! Jeg har hørt\n"
	.string "om dig!\p"
	.string "De sagde, at du har vundet\n"
	.string "{STR_VAR_3} titler på\l"
	.string "{STR_VAR_2}.\p"
	.string "Det er super! Jeg spekulerer på, om jeg\n"
	.string "kan blive en mester?$"

MatchCall_BattleDomeText3::
	.string "Hej {PLAYER}! Det' mig, {STR_VAR_1}.\n"
	.string "Skærer det sig?\p"
	.string "Jeg har hørt, du vandt events\n"
	.string "{STR_VAR_3} gange på {STR_VAR_2}!\p"
	.string "Gør det en mere næste gang! Vi ses\n"
	.string "snart!$"

MatchCall_BattleDomeText4::
	.string "Hej, {PLAYER}{KUN}. {STR_VAR_1} her.\p"
	.string "Jeg hørte, at du blev mesteren ved\n"
	.string "{STR_VAR_2} {STR_VAR_3} gange.\p"
	.string "Det lyder som om, at du arbejder hårdt.\n"
	.string "Jeg vil prøve at følge med!$"

MatchCall_BattleDomeText5::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}.\p"
	.string "Jeg hørte, du har vundet\n"
	.string "{STR_VAR_3} gange i træk i\l"
	.string "{STR_VAR_2}.\p"
	.string "Jeg må hellere komme op at snuse! Vi ses\n"
	.string "snart!$"

MatchCall_BattleDomeText6::
	.string "Hej, {PLAYER}{KUN}? {STR_VAR_1} her.\n"
	.string "Hvordan har du det?\p"
	.string "Forresten, jeg hørte, at du blev mester\n"
	.string "{STR_VAR_3} gange på\l"
	.string "{STR_VAR_2}.\p"
	.string "Jeg må nok træne mine POKéMON lidt mere,\n"
	.string "før du kommer foran.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}? {STR_VAR_1} her.\p"
	.string "Var du på {STR_VAR_2} og blev mester\n"
	.string "{STR_VAR_3} gange?\p"
	.string "Det er smart. Forresten, har du fanget\n"
	.string "nogle sjældne POKéMON for nylig?\p"
	.string "Åh, er det rigtigt. Okay, hej.$"

MatchCall_BattleDomeText8::
	.string "Åh, {PLAYER}{KUN}, hvordan går det? Det er\n"
	.string "{STR_VAR_1}, der taler. Håber, du har\l"
	.string "det godt. Åh, men det har du.\p"
	.string "Jeg har hørt, at du har vundet\n"
	.string "{STR_VAR_3} titler på\l"
	.string "{STR_VAR_2}.\p"
	.string "Jeg bliver nødt til at opdrage mine\n"
	.string "POKéMON som dig. Vi ses igen.$"

MatchCall_BattleDomeText9::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}!\p"
	.string "Jeg hørte, at du har vundet titlen\n"
	.string "{STR_VAR_3} gange ved\l"
	.string "{STR_VAR_2}!\p"
	.string "Hvor sejt! Jeg bliver nødt til at prøve\n"
	.string "hårdere også!$"

MatchCall_BattleDomeText10::
	.string "Hej, {PLAYER}{KUN}, hej. Det her er\n"
	.string "{STR_VAR_1}.\p"
	.string "Du har vundet {STR_VAR_3} gange i\n"
	.string "{STR_VAR_2}?\p"
	.string "Det er en imponerende præstation. Jeg\n"
	.string "skal arbejde hårdere.$"

MatchCall_BattleDomeText11::
	.string "Åh, {PLAYER}{KUN}. Dette er\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg hører, du er skrækken af\n"
	.string "{STR_VAR_2}?\p"
	.string "Du har vundet, hvad, {STR_VAR_3}\n"
	.string "gange i træk nu?\p"
	.string "Jeg undrer mig over, om jeg nogensinde\n"
	.string "kan blive mester?\p"
	.string "…Ret umuligt, ikke? Nå, vi ses!$"

MatchCall_BattleDomeText12::
	.string "Hej, {PLAYER}{KUN}. Det er mig,\n"
	.string "{STR_VAR_1}. Har du det godt?\p"
	.string "Du har vundet {STR_VAR_3}\n"
	.string "begivenheder på et sted ved navn\l"
	.string "{STR_VAR_2}?\p"
	.string "Det er helt vildt. Vi ses!$"

MatchCall_BattleDomeText13::
	.string "Åh, hej, {PLAYER}{KUN}! Det er\n"
	.string "{STR_VAR_1}! Jeg håber, du har det\l"
	.string "godt.\p"
	.string "De siger, du har vundet {STR_VAR_3}\n"
	.string "begivenheder på {STR_VAR_2}?\p"
	.string "Jeg beundrer din energi! Hej hej.$"

MatchCall_BattleDomeText14::
	.string "Hej, {PLAYER}{KUN}. Dette er\n"
	.string "{STR_VAR_1}. Jeg har hørt om dig!\p"
	.string "Vandt du ikke {STR_VAR_3} titler på\n"
	.string "{STR_VAR_2}?\p"
	.string "Du er en inspiration! Vi ses igen!$"

MatchCall_BattlePikeText1::
	.string "Hej! {PLAYER}? Hej, det er\n"
	.string "{STR_VAR_1}! Jeg hørte nyhederne!\p"
	.string "Du kom igennem {STR_VAR_3} rum på\n"
	.string "{STR_VAR_2}!\p"
	.string "Det er imponerende! Vi ses!$"

MatchCall_BattlePikeText2::
	.string "Hej, det er {STR_VAR_1}! Jeg har hørt\n"
	.string "om dig!\p"
	.string "De sagde, at du vandt dig vej gennem\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}.\p"
	.string "Jeg bliver nødt til at gøre en større\n"
	.string "indsats! Hej-hej!$"

MatchCall_BattlePikeText3::
	.string "Hej med dig, {PLAYER}! Det er mig,\n"
	.string "{STR_VAR_1}. Hvordan går det?\p"
	.string "Jeg hørte, at du vandt gennem\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}!\p"
	.string "Prøv at gøre det endnu bedre næste\n"
	.string "gang! Vi ses snart!$"

MatchCall_BattlePikeText4::
	.string "Hej, {PLAYER}{KUN}. {STR_VAR_1} her.\p"
	.string "Jeg hørte, at du har klaret dig igennem\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}.\p"
	.string "Jeg vil nok hellere træne mine POKéMON\n"
	.string "og prøve at følge med!$"

MatchCall_BattlePikeText5::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}.\p"
	.string "Jeg hørte, at du kom forbi\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}.\p"
	.string "Jeg burde også komme i gang! Vi ses\n"
	.string "snart!$"

MatchCall_BattlePikeText6::
	.string "Hey, {PLAYER}{KUN}? {STR_VAR_1} her.\n"
	.string "Hvordan har du det?\p"
	.string "Forresten, jeg hørte, at du klarede\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}.\p"
	.string "Jeg må nok træne mine POKéMON lidt, før\n"
	.string "du trækker for langt fra.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}? {STR_VAR_1} her.\p"
	.string "Var du ved {STR_VAR_2} og vandt dig\n"
	.string "vej forbi {STR_VAR_3} rum?\p"
	.string "Det er vildt.\p"
	.string "Åh, der går en sjælden POKéMON! Okay,\n"
	.string "hej.$"

MatchCall_BattlePikeText8::
	.string "Hej, {PLAYER}{KUN}, hvordan har du det?\n"
	.string "Det er {STR_VAR_1}, der taler. Jeg\l"
	.string "håber, at du har det godt. Det har du jo.\p"
	.string "Jeg har hørt, at du klarede\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}.\p"
	.string "Det er ret imponerende! Jeg bliver nødt\n"
	.string "til at træne mine POKéMON som dig. Vi ses\l"
	.string "igen.$"

MatchCall_BattlePikeText9::
	.string "Hej, {PLAYER}{KUN}, hej! Det er\n"
	.string "{STR_VAR_1}!\p"
	.string "Jeg hørte! Du vandt dig vej gennem\n"
	.string "{STR_VAR_3} rum på {STR_VAR_2}!\p"
	.string "Det er så sejt! Jeg må hellere prøve\n"
	.string "hårdere selv!$"

MatchCall_BattlePikeText10::
	.string "Hej {PLAYER}{KUN}. Det er {STR_VAR_1}.\p"
	.string "Du vandt dig vej forbi {STR_VAR_3}\n"
	.string "rum på {STR_VAR_2}?\p"
	.string "Det er en stor præstation. Jeg bliver\n"
	.string "nødt til at arbejde hårdere.$"

MatchCall_BattlePikeText11::
	.string "Nå, {PLAYER}{KUN}. Jeg er {STR_VAR_1}.\p"
	.string "Hører jeg, at du er skrækken i\n"
	.string "{STR_VAR_2}?\p"
	.string "Du klarede hvad, {STR_VAR_3} rum?\n"
	.string "Det må da tælle for noget.\p"
	.string "Mon jeg nogensinde kan blive mester?\p"
	.string "…Temmelig umuligt? Nå, ses!$"

MatchCall_BattlePikeText12::
	.string "Hej, {PLAYER}{KUN}. Det er mig,\n"
	.string "{STR_VAR_1}. Har du det godt?\p"
	.string "Du har vundet igennem {STR_VAR_3}\n"
	.string "rum på et sted ved navn {STR_VAR_2}?\p"
	.string "Det er en temmelig vild historie. Vi ses!$"

MatchCall_BattlePikeText13:: 
	.string "Åh, hej, {PLAYER}{KUN}!\n"
	.string "Det er {STR_VAR_1}!\l"
	.string "Jeg håber, du har det godt.\p"
	.string "De siger, du har vundet i {STR_VAR_3}\n"
	.string "rum på {STR_VAR_2}?\p"
	.string "Jeg beundrer din energi!\n"
	.string "Hej så.$"

MatchCall_BattlePikeText14::
	.string "Hej, {PLAYER}{KUN}. Det her er\n"
	.string "{STR_VAR_1}. Jeg har hørt om dig!\p"
	.string "Kom du ikke igennem {STR_VAR_3} rum\n"
	.string "i {STR_VAR_2}?\p"
	.string "Du er en inspiration! Vi ses igen!$"

MatchCall_BattlePyramidText1::
	.string "Hej! {PLAYER}? Hej, det er\n"
	.string "{STR_VAR_1}! Jeg har hørt nyheden!\p"
	.string "Du har besteget {STR_VAR_3} etager\n"
	.string "i {STR_VAR_2}, ikke sandt?\p"
	.string "Det er fantastisk! Jeg burde prøve den\n"
	.string "udfordring.$"

MatchCall_BattlePyramidText2::
	.string "Hej, det er {STR_VAR_1}! Jeg har hørt\n"
	.string "om dig!\p"
	.string "De sagde, at du vandt dig gennem\n"
	.string "{STR_VAR_3} etager i {STR_VAR_2}.\p"
	.string "Wow, det er fantastisk! Jeg må hellere\n"
	.string "træne mine POKéMON også!$"

MatchCall_BattlePyramidText3::
	.string "Hej {PLAYER}! Det er mig,\n"
	.string "{STR_VAR_1}. Hvordan går det?\p"
	.string "Jeg hørte, at du nåede {STR_VAR_3}\n"
	.string "etager i {STR_VAR_2}!\p"
	.string "Prøv at gøre det endnu bedre næste\n"
	.string "gang! Vi ses snart!$"

MatchCall_BattlePyramidText4::
	.string "Hej, {PLAYER}{KUN}. {STR_VAR_1} her.\p"
	.string "Jeg hørte, at du besteg {STR_VAR_3}\n"
	.string "etager i {STR_VAR_2}.\p"
	.string "Jeg burde nok arbejde hårdt og prøve at\n"
	.string "følge med!$"

MatchCall_BattlePyramidText5::
	.string "Hej, {PLAYER}{KUN}! Det er {STR_VAR_1}.\p"
	.string "Jeg hørte, at du klatrede\n"
	.string "{STR_VAR_3} etager i {STR_VAR_2}.\p"
	.string "Jeg må nok også i gang! Vi ses snart!$"

MatchCall_BattlePyramidText6::
	.string "Hej, {PLAYER}!  {STR_VAR_1} her.\n"
	.string "Hvordan har du det?\p"
	.string "Forresten, jeg hørte, at du kom igennem\n"
	.string "{STR_VAR_3} etager i {STR_VAR_2}.\p"
	.string "Jeg burde nok træne mine POKéMON lidt,\n"
	.string "inden du løber fra mig.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}? {STR_VAR_1} her.\p"
	.string "Var du ved {STR_VAR_2} og vandt dig\n"
	.string "op {STR_VAR_3} etager?\p"
	.string "Fedt. Var der nogen sjældne POKéMON\n"
	.string "der?\p"
	.string "Nej, hva? Okay, hej.$"

MatchCall_BattlePyramidText8::
	.string "Åh, {PLAYER}{KUN}, hvordan går det? Her er\n"
	.string "det {STR_VAR_1}, der taler. Jeg\l"
	.string "håber, at du har det godt. Åh, men det\l"
	.string "har du.\p"
	.string "Jeg har hørt, at du klarede\n"
	.string "{STR_VAR_3} etager i {STR_VAR_2}.\p"
	.string "Det er ret imponerende! Jeg må hæve\n"
	.string "mine POKéMON som dig. Vi ses igen.$"

MatchCall_BattlePyramidText9::
	.string "Åh, {PLAYER}{KUN}, hej der! Det her er\n"
	.string "{STR_VAR_1}!\p"
	.string "Jeg hørte det! Du vandt dig vej gennem\n"
	.string "{STR_VAR_3} gulve i {STR_VAR_2}!\p"
	.string "Det er så sejt! Jeg må nok også prøve\n"
	.string "hårdere!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hej. Det er\n"
	.string "{STR_VAR_1}.\p"
	.string "Du klatrede {STR_VAR_3} etager inde\n"
	.string "i {STR_VAR_2}?\p"
	.string "Det er en imponerende præstation. Jeg\n"
	.string "bliver nødt til at arbejde hårdere.$"

MatchCall_BattlePyramidText11::
	.string "Åh, {PLAYER}{KUN}. Dette er\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeg hører, at du er skrækken fra\n"
	.string "{STR_VAR_2}?\p"
	.string "Du steg gennem, hvad, {STR_VAR_3}\n"
	.string "gulve? Det må tælle for noget.\p"
	.string "Jeg spekulerer på, om jeg nogensinde\n"
	.string "kan blive en mester?\p"
	.string "…Ret umuligt? Nå, vi ses!$"

MatchCall_BattlePyramidText12::
	.string "Hej, {PLAYER}{KUN}. Det er mig,\n"
	.string "{STR_VAR_1}. Har du det godt?\p"
	.string "Du har vundet igennem {STR_VAR_3}\n"
	.string "etager i et sted kaldet {STR_VAR_2}?\p"
	.string "Det er da en historie. Vi ses!$"

MatchCall_BattlePyramidText13::
	.string "Nå, hej, {PLAYER}{KUN}! Det her er\n"
	.string "{STR_VAR_1}! Håber du har haft det\l"
	.string "godt.\p"
	.string "Sig mig, har du besteget {STR_VAR_3}\n"
	.string "etager i {STR_VAR_2}?\p"
	.string "Jeg beundrer din energi! Hej for nu.$"

MatchCall_BattlePyramidText14::
	.string "Hej, {PLAYER}{KUN}. Jeg er {STR_VAR_1}.\n"
	.string "Jeg har hørt om dig!\p"
	.string "Kommer du ikke igennem {STR_VAR_3}\n"
	.string "etager i {STR_VAR_2}?\p"
	.string "Du er en inspiration! Vi ses igen!$"

MatchCall_Text_Mom1::
	.string "MOR: Din far og dig… Alle er betaget af\n"
	.string "POKéMON.\p"
	.string "Hvad er charmen ved POKéMON?\p"
	.string "Mig? Jeg forguder POKéMON, der hjælper\n"
	.string "mig med mine daglige pligter.$"

MatchCall_Text_Mom2::
	.string "MOR: Hej, {PLAYER}! Din far holder sig\n"
	.string "låst inde i PETALBURG GYM.\p"
	.string "Han kommer hjem en gang imellem. Men han\n"
	.string "går tilbage til GYMet, når han har spist\l"
	.string "alt, han kan.\p"
	.string "Jeg gætter på, at det at tabe til dig var\n"
	.string "et stort slag mod hans stolthed!$"

MatchCall_Text_Mom3::
	.string "MOR: {PLAYER}… Bare rolig med mig\n"
	.string "eller huset.\p"
	.string "Brug de LØBESKO indtil de falder fra\n"
	.string "hinanden, skat!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Åh hej, {PLAYER}!\p"
	.string "Jeg har knoklet hårdt med træningen\n"
	.string "siden vi mødtes.\p"
	.string "Jeg har stadig brug for lidt mere tid,\n"
	.string "før jeg kan genåbne GYMen.\p"
	.string "Men når jeg gør det, så kom og besøg min\n"
	.string "GYM for en revanche!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Er det dig, {PLAYER}?\n"
	.string "Tillykke! Jeg har hørt om dig!\p"
	.string "Hvad mig angår, har jeg brug for lidt\n"
	.string "mere tid, før jeg kan åbne GYM'et.\p"
	.string "Men når jeg gør, så besøg min GYM for en\n"
	.string "revanche!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}! Min GYM er klar!\p"
	.string "Besøg RUSTBORO, når du kan!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: På RUSTBORO GYM, det faktum,\n"
	.string "at vi kæmpede, {PLAYER}, er en sag om\l"
	.string "stolthed.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hej {PLAYER}{KUN}!\p"
	.string "Jeg lærte en masse af kampen, vi havde\n"
	.string "sammen.\p"
	.string "Jeg har tænkt mig at træne lidt mere og\n"
	.string "derefter genåbne GYMMET.\p"
	.string "Der går lidt tid, før jeg er klar til at\n"
	.string "drive GYMMET igen.\p"
	.string "Men hvis jeg genåbner GYMMET, vil jeg\n"
	.string "have dig til at udfordre os igen.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hej, {PLAYER}{KUN}! Tillykke!\p"
	.string "Ordet om dine bedrifter nåede mig på\n"
	.string "tidevindsstrømme!\p"
	.string "Det ser ud til, at jeg skal arbejde mere\n"
	.string "på min træning.\p"
	.string "Det vil tage lidt tid, før jeg er klar til\n"
	.string "at drive GYMMET igen.\p"
	.string "Men hvis jeg kan genåbne GYMMET, vil jeg\n"
	.string "have dig til at udfordre os igen.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Hey, {PLAYER}{KUN}! Min GYM er klar\n"
	.string "til aktion!\p"
	.string "Kom tilbage til DEWFORD når som helst\n"
	.string "for endnu en udfordring!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}, jeg tror ikke jeg\n"
	.string "nogensinde bliver træt af at kæmpe mod\l"
	.string "dig!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Åh, det er dig!\p"
	.string "Efter du gik, har jeg genstartet min\n"
	.string "træning fra bunden.\p"
	.string "Jeg vil sige, jeg kunne bruge lidt mere\n"
	.string "tid til at genåbne min GYM.\p"
	.string "Du bliver nødt til at vente til da!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "Du har virkelig gjort det, har du ikke?\n"
	.string "Jeg har hørt om dig!\p"
	.string "Det virker til, at jeg skal træne endnu\n"
	.string "mere.\p"
	.string "Jeg vil sige, at jeg skal bruge lidt mere\n"
	.string "tid til at genåbne mit GYM.\p"
	.string "Du må vente indtil da! Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Åh, det er dig! Mit GYM er klar!\p"
	.string "Besøg MAUVILLE når som helst!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "Et slag med dig er altid fyldt med\n"
	.string "elektrisk kraft!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "Da vi kæmpede, lærte jeg præcist hvor\n"
	.string "umoden jeg var.\p"
	.string "Men jeg er ikke færdig endnu!\p"
	.string "Jeg vil genoptage min træning og\n"
	.string "genåbne GYMMEN.\p"
	.string "Når tiden kommer, {PLAYER}, udfordre\n"
	.string "os gerne igen.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Hej, {PLAYER}? Tillykke!\p"
	.string "Ordet om din succes har nået os som\n"
	.string "varmen fra en vulkan!\p"
	.string "Vores træning går rigtig godt her.\p"
	.string "Når GYM'et er klar, vil der komme et\n"
	.string "mærke ved siden af mit navn på MATCH\l"
	.string "CALL-listen.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Åh, {PLAYER}? Vores GYM er\n"
	.string "klar!\p"
	.string "Kom til LAVARIDGE og få en tur i varme\n"
	.string "kilder samt en udfordring!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}… Jeg er sikker på,\n"
	.string "at du bliver bedre til træning hver gang.$"

MatchCall_Text_Winona1::
	.string "WINONA: Hej, {PLAYER}!\p"
	.string "Takket være vores kamp, er jeg blevet\n"
	.string "opmærksom på mine svage punkter!\p"
	.string "Når jeg genåbner GYMen, vil jeg ikke\n"
	.string "lade mig slå ud igen!$"

MatchCall_Text_Winona2::
	.string "WINONA: Du gjorde det, {PLAYER}!\p"
	.string "Nyheder om den nye MESTER har nået os i\n"
	.string "FORTREE!\p"
	.string "Men... Næste gang vi kæmper, kommer det\n"
	.string "ikke til at ende på samme måde.$"

MatchCall_Text_Winona3::
	.string "WINONA: Er det her {PLAYER}? Vores\n"
	.string "GYM er tilbage i drift!\p"
	.string "Vi venter på dig i FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}… Selvom jeg har\n"
	.string "tabt, vil mine vinger aldrig brække.\p"
	.string "Ja, præcis på samme måde som du aldrig\n"
	.string "mistede synet af din drøm.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Åh! Du er... LIZA: {PLAYER}!\p"
	.string "TATE: Vi træner igen... LIZA: Så vi kan\n"
	.string "genåbne vores GYM!\p"
	.string "TATE: Når vores GYM er klar... LIZA: Når\n"
	.string "vores GYM er klar...\p"
	.string "TATE: En markering vil dukke op ved\n"
	.string "vores navn... LIZA: På MATCH\l"
	.string "CALL-listen.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, tillykke! LIZA:\n"
	.string "{PLAYER}, tillykke!\p"
	.string "TATE: Vi to er... LIZA: stadig i træning!\p"
	.string "TATE: Vi skal bruge lidt mere tid, men...\n"
	.string "LIZA: Når vores GYM er klar...\p"
	.string "TATE: Der vil komme et mærke ved vores\n"
	.string "navn... LIZA: På MATCH CALL-listen.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}! LIZA: {PLAYER}!\p"
	.string "TATE: Vores GYM er klar! LIZA: Vores\n"
	.string "GYM er klar!\p"
	.string "TATE: Kom og besøg os... LIZA: I\n"
	.string "MOSSDEEP når du vil!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, kampen vi havde... \n"
	.string "LIZA: Er en uvurderlig oplevelse.\p"
	.string "TATE: Det ville være dejligt hvis... \n"
	.string "LIZA: Vi alle kunne kæmpe igen!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm… {PLAYER}, was det ikke?\p"
	.string "Vores kamp sammen--den bragte minder\n"
	.string "frem hos mig om dengang jeg først mødte\l"
	.string "WALLACE.\p"
	.string "Måske er du et geni, der kan overgå\n"
	.string "WALLACE endnu!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu... {PLAYER}{KUN}... Du har\n"
	.string "endelig nået dit mål.\p"
	.string "Mit øje for at vurdere talent var ikke\n"
	.string "fejlagtigt...\p"
	.string "Jeg ønsker for en anden chance for at\n"
	.string "møde dig, for du har besteget toppen af\l"
	.string "magt og prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho... {PLAYER}gerne...\p"
	.string "Vores SOOTOPOLIS GYM har endelig åbnet\n"
	.string "igen.\p"
	.string "Hvis du ønsker at besøge mig, er du\n"
	.string "velkommen når som helst.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Som den fineste musik, de kampe vi\n"
	.string "udkæmper sammen, slår toner af\l"
	.string "inspiration i mit hjerte…\p"
	.string "Når jeg lukker mine øjne, ser jeg\n"
	.string "visioner af dig svævende med melodien…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Hej, {PLAYER}!\p"
	.string "Hvis du vil kæmpe mod mig igen, så kom\n"
	.string "bare tilbage når som helst til\l"
	.string "POKéMON-LIGAEN.\p"
	.string "Jeg vil altid være her! Jeg venter på\n"
	.string "dig!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Hej, {PLAYER}!\p"
	.string "Hvad med at komme tilbage hertil på et\n"
	.string "tidspunkt?\p"
	.string "Jeg vil gerne se, hvor meget dit bånd er\n"
	.string "vokset med dine POKéMON.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Hej, {PLAYER}.\p"
	.string "Jeg håber, at du ikke er blevet\n"
	.string "selvtilfreds med din styrke?\p"
	.string "Hvis du føler behov for at køle lidt af\n"
	.string "på dine varme følelser, så kom endelig\l"
	.string "til POKéMON LIGAEN…$"

MatchCall_Text_Drake::
	.string "DRAKE: Den stemme… {PLAYER}, er det\n"
	.string "dig? Du lyder godt…\p"
	.string "Jeg har hørt, at der nu findes en\n"
	.string "facilitet kaldet BATTLE FRONTIER, der\l"
	.string "tester TRÆNERNES færdigheder.\p"
	.string "Men hvis du vil have rigtige kampe, er\n"
	.string "der intet der kan erstatte POKéMON\l"
	.string "LIGAEN!\p"
	.string "Er du ikke enig, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Hej, {PLAYER}{KUN}. Har du mødt\n"
	.string "Steven?\p"
	.string "Han er... Faktisk utroligt dygtig.\p"
	.string "Men han er en mærkelig sjæl, der\n"
	.string "sjældent kæmper.\p"
	.string "I stedet vil han hellere lede efter\n"
	.string "sjældne sten.\p"
	.string "Jeg er sikker på, at han graver i en hule\n"
	.string "eller et stejlt bjerg et eller andet\l"
	.string "sted.\p"
	.string "Men hvad er en sjælden sten egentlig?\n"
	.string "Alt hvad jeg kan tænke på er en\l"
	.string "meteorit...$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … … … … … … … Beep!\p"
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Jeg var lige i PACIFIDLOGBYT for lidt\n"
	.string "siden.\p"
	.string "Jeg så en kæmpestor grøn POKéMON flyve\n"
	.string "højt oppe i himlen.\p"
	.string "Jeg... Jeg har aldrig set noget lignende.\p"
	.string "Jeg undrer mig over, hvad det var. Er\n"
	.string "det måske en stor opdagelse?\p"
	.string "… … … … … … … … … … … Klik!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … … … … … … … Bip!\p"
	.string "BRENDAN: Hej, {PLAYER}! Jeg var lige i\n"
	.string "PACIFIDLOG.\p"
	.string "Jeg så denne kæmpestore grønne\n"
	.string "POKéMON flyve over himlen.\p"
	.string "Jeg har aldrig set noget så fantastisk\n"
	.string "før.\p"
	.string "Jeg ville ønske, du kunne have set det,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … … … … … … … Klik!$"

MatchCall_Text_May1::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY gik på pension som SØMAND,\n"
	.string "men jeg ser ham stadig ude på havet med\l"
	.string "hans kæledyr PEEKO engang imellem.\p"
	.string "Han må stadig elske havet.$"

MatchCall_Text_May2::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Ved du, hvordan små byer som PETALBURG\n"
	.string "og DEWFORD har GYMS?\p"
	.string "Af en eller anden grund har den store\n"
	.string "havn i SLATEPORT ikke et GYM.\p"
	.string "Når de endelig bygger et GYM der, skal\n"
	.string "jeg søge om at være LEDEREN.$"

MatchCall_Text_May3::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Husker du en fyr ved navn CUTTER i\n"
	.string "RUSTBORO? Han havde et hus der, husker\l"
	.string "du?\p"
	.string "Nå, jeg fandt ud af, at hans yngre bror\n"
	.string "bor i MAUVILLE.\p"
	.string "Kan du gætte hans navn?\p"
	.string "… … … … … … … … … … … …\p"
	.string "ROCK SMASH FYREN!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "RUSTURF-TUNNELEN… Det hedder den,\n"
	.string "fordi den forbinder RUSTBORO og\l"
	.string "VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}, hvordan har du det?\p"
	.string "Jeg er ude på RUTE 111 nu.\p"
	.string "Jeg vil hvile mig hos en gammel dame.\p"
	.string "Hun bor lige nord for ørkenen.$"

MatchCall_Text_May6::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Vidste du om MIRAGE TOWER i ørkenen?\p"
	.string "De siger, at ligesom en mirage, kommer og\n"
	.string "går den mysteriøst.\p"
	.string "Jeg ønsker, jeg kunne se den.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}, hej! Jeg er på RUTE 119\n"
	.string "nu.\p"
	.string "Der er en stor flod her, og det regner\n"
	.string "ofte.\p"
	.string "Jeg blev gennemblødt!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}, hej.\p"
	.string "MT. PYRE er et minde for POKéMON, som\n"
	.string "har afsluttet deres liv.\p"
	.string "Måske som følge heraf er det inficeret\n"
	.string "med mange GHOST-type POKéMON!$"

 MatchCall_Text_May9::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Jeg tænkte på at tage til de varme\n"
	.string "kilder i LAVARIDGE.\p"
	.string "Men på vejen, omkring JAGGED\n"
	.string "PASS, stødte jeg på nogle\l"
	.string "skumle typer. Stemningen var sur!$"

MatchCall_Text_May10::
	.string "MAY: Hej, {PLAYER}! Har du set\n"
	.string "nyhederne?\p"
	.string "De siger, at KAPT. STERN opdagede\n"
	.string "HAVBUNDSKAVERNEN, mens han var på sin\l"
	.string "ubådsekspedition.$"

MatchCall_Text_May11::
	.string "MAY: Hej, {PLAYER}{KUN}! Synes du ikke, det\n"
	.string "er sejt?\p"
	.string "Selv hvis du ikke har en båd, kan du\n"
	.string "krydse havet ved at bruge en POKéMONs\l"
	.string "move.\p"
	.string "Vidste du, at der er mere?\p"
	.string "Der er en POKéMON move, der lader dig gå\n"
	.string "til bunden af havet.$"

MatchCall_Text_May12::
	.string "MAY: Hej, {PLAYER}{KUN}! Håber alt er ok!\p"
	.string "Har du været på havet og fundet din vej\n"
	.string "til den anden side blokeret?\p"
	.string "Prøv at dykke dybt ned under vandet og\n"
	.string "følg renderne.\p"
	.string "Når du kommer til den anden side, så kom\n"
	.string "op til overfladen.\p"
	.string "Let!$"

MatchCall_Text_May13::
	.string "MAY: Hej, {PLAYER}{KUN}!\p"
	.string "Hvordan går det? Er du ved at fylde din\n"
	.string "POKéDEX?\p"
	.string "Jeg hørte et rygte om, at der findes\n"
	.string "superældgamle POKéMON derude. Og der er\l"
	.string "tre af dem!\p"
	.string "Jeg ville elske at se bare en…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}{KUN}! Jeg har hørt rygterne!\p"
	.string "Du slog SOOTOPOLIS GYM- LEDEREN?\p"
	.string "Det betyder, at du ikke har langt igen,\n"
	.string "gør det?$"

MatchCall_Text_May15::
	.string "MAY: Der er ikke en eneste TRÆNER\n"
	.string "tilbage i HOENN, der ikke kender dig,\l"
	.string "{PLAYER}{KUN}!\p"
	.string "Når jeg fortæller folk, at jeg er venner\n"
	.string "med dig, {PLAYER}{KUN}, bliver de alle\l"
	.string "overraskede!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Hej, {PLAYER}!\p"
	.string "MR. BRINEY gik på pension som en\n"
	.string "SØMAND, men jeg ser ham stadig ude på\l"
	.string "havet med sin pet PEEKO engang imellem.\p"
	.string "Jeg tror, han må stadig elske havet.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Hej, {PLAYER}!\p"
	.string "Jeg forstår ikke, hvordan små byer som\n"
	.string "PETALBURG og DEWFORD har GYMS.\p"
	.string "Jeg mener, ikke når den store havn i\n"
	.string "SLATEPORT ikke har et GYM.\p"
	.string "Når de endelig bygger et GYM der, bør\n"
	.string "jeg søge om at blive LEDER.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Hej, {PLAYER}!\p"
	.string "Husker du en fyr ved navn CUTTER i\n"
	.string "RUSTBORO? Han havde et hus der, ikke?\p"
	.string "Det viser sig, at hans lille bror bor i\n"
	.string "MAUVILLE.\p"
	.string "Kan du gætte hans navn?\p"
	.string "… … … … … … … … … … … …\p"
	.string "HAMMERBRO$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: Den her stemme... {PLAYER}?\p"
	.string "De kaldte RUSTURF-TUNNELEN for det,\n"
	.string "fordi den forbinder RUSTBORO og\l"
	.string "VERDANTURF.\p"
	.string "Vidste du det?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, hvad så?\p"
	.string "Hej, jeg er ude på RUTE 111 nu.\p"
	.string "Jeg vil hvile mig i et gammelt damers hus\n"
	.string "nord for ørkenen.\p"
	.string "Hvis du er i området, så burde du også\n"
	.string "besøge hende.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Hej, {PLAYER}!\p"
	.string "Vidste du om MIRAGE TÅRNET i ørkenen?\p"
	.string "De siger, ligesom et mirage, kan det kun\n"
	.string "ses til tider.\p"
	.string "Det vil jeg gerne se!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Hvem er det? Oh, {PLAYER}?\n"
	.string "Gæt hvad? Jeg er på RUTE 119 nu.\p"
	.string "Der er en stor flod her, og det regner\n"
	.string "hele tiden.\p"
	.string "Jeg blev gennemvåd til skindet!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE er et mindesmærke for POKéMON,\n"
	.string "deres liv er endt.\p"
	.string "Det er nok derfor det vrimler med mange\n"
	.string "GHOST-type POKéMON!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Hej med dig, {PLAYER}.\p"
	.string "Jeg var på vej tilbage til den varme\n"
	.string "kilde i LAVARIDGE.\p"
	.string "Men omkring JAGGED PASS rendte jeg ind\n"
	.string "i nogle ubehagelige typer.\p"
	.string "De skumle typer… Jeg tror, de var TEAM\n"
	.string "MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Hej, {PLAYER}! Har du hørt\n"
	.string "nyhederne?\p"
	.string "De siger, at KAPT. STERN opdagede\n"
	.string "HAVBUNDENSKAVEN under sin\l"
	.string "ubådsekspedition.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Hej der, {PLAYER}! Synes du\n"
	.string "ikke, det er fantastisk?\p"
	.string "Selv hvis du ikke har en båd, kan du\n"
	.string "krydse havet ved hjælp af en POKéMONs\l"
	.string "bevægelse.\p"
	.string "Og så er der en bevægelse, der lader dig\n"
	.string "rejse til bunden af havet.\p"
	.string "Pokémon kan virkelig alt muligt!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Hej, {PLAYER}! Hvordan har du\n"
	.string "det?\p"
	.string "Har du nogensinde oplevet, at vejen\n"
	.string "blev blokeret, mens du var på havet?\p"
	.string "Prøv at dykke dybt under vandet og\n"
	.string "følg renden på bunden.\p"
	.string "Når du når den anden side, kommer du op\n"
	.string "til overfladen. Simpelt!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Hej der, {PLAYER}!\p"
	.string "Hvordan går det? Har du fået fyldt din\n"
	.string "POKéDEX op med succes?\p"
	.string "Jeg har hørt et rygte om, at der findes\n"
	.string "super-ældgamle POKéMON derude. Og ikke\l"
	.string "bare en--tre!\p"
	.string "Jeg ville elske at fange bare én…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}! Jeg har hørt\n"
	.string "rygterne!\p"
	.string "Du slog SOOTOPOLIS GYM LEADER?\n"
	.string "Fantastisk!\p"
	.string "Du er virkelig tæt på nu!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: Der er ikke en TRÆNER i hele\n"
	.string "HOENN, der ikke ved, hvem du er,\l"
	.string "{PLAYER}!\p"
	.string "Når jeg fortæller folk, at jeg er venner\n"
	.string "med dig, {PLAYER}, bliver de ret\l"
	.string "misundelige!$"

MatchCall_Text_Wally1::
	.string "WALLY: Åh, {PLAYER}!\p"
	.string "Jeg har fået det bedre og er blevet\n"
	.string "mere fysisk fit.\p"
	.string "Jeg håber, at jeg snart kan blive en\n"
	.string "TRÆNER ligesom dig, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, hej!\p"
	.string "Efter RUSTURF-TUNNELEN har hun været\n"
	.string "meget glad!$"

MatchCall_Text_Wally3::
	.string "WALLY: Åh, {PLAYER}!\p"
	.string "Jeg... Jeg forlod min onkels hjem i\n"
	.string "VERDANTURF uden at fortælle nogen.\p"
	.string "Jeg spekulerer på, om han er rasende på\n"
	.string "mig...\p"
	.string "{PLAYER}, du forstår vel, hvordan jeg\n"
	.string "har det, ikke sandt?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}? Det er mig, WALLY!\p"
	.string "Trænernes verden er fantastisk!\p"
	.string "Når jeg har mine POKéMON med mig, siger\n"
	.string "alle mulige mennesker hej!\p"
	.string "Det er som om, at alle bliver forbundet\n"
	.string "gennem POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? Det er fantastisk!\n"
	.string "Den RALTS vi fangede sammen? Den\l"
	.string "udviklede sig, {PLAYER}!\p"
	.string "Måske er jeg talentfuld…\p"
	.string "Åh, men jeg bør ikke blive hovmodig som\n"
	.string "sådan!\p"
	.string "Det er jo POKéMON'en, der skal roses!$"

MatchCall_Text_Wally6::
	.string "… … … … … … … … … … … …\p"
	.string "Det virker som om WALLY er ude af\n"
	.string "POKéNAVs dækningsområde…$"

MatchCall_Text_Wally7::
	.string "WALLY: Åh, {PLAYER}!\p"
	.string "Før jeg mødte dig, forlod jeg så\n"
	.string "sjældent mit hus…\p"
	.string "Men nu er jeg på et eventyr med min helt\n"
	.string "egen POKéMON…\p"
	.string "{PLAYER}… Tak…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Hej, {PLAYER}{KUN}!\p"
	.string "Ved du, hvordan man kan finde POKéMON\n"
	.string "overalt?\p"
	.string "Som i bjergene, i havet, i højt græs\n"
	.string "overalt?\p"
	.string "Ligesom POKéMON, kan du finde TRÆNERE\n"
	.string "overalt også.\p"
	.string "Som følge heraf skal jeg skynde mig\n"
	.string "overalt. Travlt, travlt!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Jeg er på RUTE 119 lige nu. Der er\n"
	.string "fyldt med TRÆNERE!\p"
	.string "Der er også højt græs overalt, det\n"
	.string "virker det til.\p"
	.string "At gå rundt i shorts her får mig til at\n"
	.string "krible over det hele!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Hej, hej, {PLAYER}{KUN}!\p"
	.string "Har du haft mulighed for at klatre op ad\n"
	.string "MT. PYRE?\p"
	.string "Stedet er et mindesmærke for POKéMON,\n"
	.string "der er gået bort.\p"
	.string "Det er et sted, som enhver TRÆNER bør\n"
	.string "klatre til toppen af mindst én gang.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Hej, {PLAYER}{KUN}!\p"
	.string "Jeg har hørt om disse mærkelige bander,\n"
	.string "der er til gene.\p"
	.string "Hold MAGMA og Hold AQUA, tror jeg, de\n"
	.string "hedder.\p"
	.string "Jeg vil tro, der er nogle dygtige\n"
	.string "TRÆNERE iblandt dem.\p"
	.string "…Men hvis de er bøller…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Åh, hej, {PLAYER}{KUN}.\p"
	.string "Mon der er nogle seje TRÆNERE nederst i\n"
	.string "havet?\p"
	.string "Det kan jeg ikke selv tjekke. Jeg kan\n"
	.string "ikke svømme, for det første. Og jeg\l"
	.string "opdrætter ikke POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Hej, hej, {PLAYER}{KUN}!\p"
	.string "Ved du, at du kan udfordre\n"
	.string "POKéMON-LIGAEN, når du har samlet alle\l"
	.string "GYM-BADGES?\p"
	.string "Med dit talent er det at blive MESTER\n"
	.string "ikke urealistisk.\p"
	.string "Men vidste du det? Der er et sted, der\n"
	.string "er endnu bedre.\p"
	.string "Men det er alt, jeg er villig til at sige\n"
	.string "for nu.\p"
	.string "Det er noget at se frem til.\p"
	.string "Når du har kæmpet dig vej gennem\n"
	.string "POKéMON-LIGAEN ind i HALL OF FAME!$"

MatchCall_Text_Scott7::
	.string "… … … … … … … … … … … …\p"
	.string "SCOTT appears to be out of the\n"
	.string "POKéNAV's service area…$"

MatchCall_Text_Norman1::
	.string "FAR: I RUSTBORO bor der en mand, som\n"
	.string "går under det mærkelige navn SKÆREREN.\p"
	.string "Hvis du er i området, bør du besøge ham.$"

MatchCall_Text_Norman2::
	.string "FAR: Hmm… Lidt efter lidt, men også\n"
	.string "meget sikkert, bliver du stærkere,\l"
	.string "{PLAYER}.\p"
	.string "Jo stærkere du bliver, jo længere og\n"
	.string "højere svæver du fra Mor og mig…\p"
	.string "Denne følelse er svær at forklare.$"

MatchCall_Text_Norman3::
	.string "FAR: Jeg ser... Du har samlet fire GYM\n"
	.string "BADGES...\p"
	.string "Der er ingen vej udenom nu. Vi vil kæmpe,\n"
	.string "som jeg lovede.\p"
	.string "Kom når som helst. Vi venter alle på dig!$"

MatchCall_Text_Norman4::
	.string "FAR: {PLAYER}! Du bør besøge Mor en\n"
	.string "gang imellem.\p"
	.string "Jeg bliver her og fordobler min træning.\p"
	.string "Kampens vej er dyb og ubarmhjertig!$"

MatchCall_Text_Norman5::
	.string "FAR: Hej, {PLAYER}!\p"
	.string "Hvad er det? MAGMA-EMBLEM? Jeg ved\n"
	.string "ikke, hvad det handler om.\p"
	.string "Men med et navn som det kan det måske\n"
	.string "være på en eller anden måde relateret til\l"
	.string "en vulkan!$"

MatchCall_Text_Norman6::
	.string "FAR: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "Du fangede mig lige midt i en\n"
	.string "POKéMON-træningssession!$"

MatchCall_Text_Norman7::
	.string "FAR: {PLAYER}!\p"
	.string "Hvem havde troet, at du ville blive\n"
	.string "POKéMON LIGA-MESTER…\p"
	.string "Okay! Jeg bliver ikke efterladt!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}? Hvad er du heldig!\p"
	.string "Denne gang udfordrer jeg dig til kamp.\p"
	.string "Jeg venter i PETALBURG GYM. Accepter\n"
	.string "min udfordring når som helst!$"

MatchCall_Text_Norman9::
	.string "FAR: …Du forbavser mig, {PLAYER}.\n"
	.string "Hvor meget højere vil du flyve?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Hej, {PLAYER}en!\p"
	.string "Har du været i MAUVILLE allerede?\p"
	.string "Du bør besøge CYKELBUTIKKEN og få en\n"
	.string "MACH-CYKEL.\p"
	.string "Prøv derefter at udforske GRANITHULEN\n"
	.string "grundigt.\p"
	.string "Du kunne måske gøre en ny opdagelse\n"
	.string "der.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Hej, {PLAYER}!{KUN}\p"
	.string "Jeg har mødt mange forskellige TRÆNERE\n"
	.string "indtil videre.\p"
	.string "Men du er helt speciel. Du ligner ikke\n"
	.string "nogen andre.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Hej, {PLAYER}{KUN}!\p"
	.string "Når du er på eventyr med dine POKéMON,\n"
	.string "hvad tænker du?\p"
	.string "Ser du dem som stærke partnere?\p"
	.string "Ser du dem som sjove kammerater?\p"
	.string "Afhængigt af din tankegang, ændres\n"
	.string "eventyrets betydning.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Hej? {PLAYER}{KUN}?\p"
	.string "Jeg er havnet i lidt problemer på\n"
	.string "RUMCENTRET.\p"
	.string "Undskyld, men jeg kan ikke tale nu. Hej!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Oh! {PLAYER}!\p"
	.string "Der er ingen grund til at snakke. Det er\n"
	.string "forbi med at snakke.\p"
	.string "Du skal tro på dig selv og gøre det\n"
	.string "rigtige.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "STEVEN ser ud til ikke at få opkaldet…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}… Tillykke for at\n"
	.string "komme ind i FAME-HALLEN.\p"
	.string "… … … … … … … … … … … …\p"
	.string "Jeg håber vi kan mødes igen et sted!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Åh, {PLAYER}{KUN}! Jeg har\n"
	.string "allerede hørt om dig!\p"
	.string "Det ser ud til, at din POKéNAV er blevet\n"
	.string "opgraderet med MATCH CALL.\p"
	.string "Nå, jeg burde også registrere mig!\p"
	.string "På den måde kunne jeg undersøge din\n"
	.string "POKéDEX selv mens du er ude på marken.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Registreret PROF. BIRCH i POKéNAV'en.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: Når man har både POKéDEX\n"
	.string "og POKéNAV, bliver studiet af POKéMON\l"
	.string "mere sjovt, hva?$"

MatchCall_Text_MrStone1::
	.string "MR. STEN: Åh? {PLAYER}{KUN}!\p"
	.string "Siden du ringede til mig, så virker\n"
	.string "POKéNAV'en som den skal!\p"
	.string "Andre personer bliver registreret, så\n"
	.string "prøv også at ringe til dem!\p"
	.string "Godt! Godt! Du virker ret glad!\p"
	.string "Hm... Hvordan kunne jeg vide det?\p"
	.string "Det er fordi, jeg kigger ned på dig fra\n"
	.string "mit kontorvindue!\p"
	.string "Wahahaha! Vi ses igen!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Åh? {PLAYER} {KUN}!\p"
	.string "Hvad er galt? Har du glemt om den lille\n"
	.string "opgave, jeg gav dig?\p"
	.string "Jeg har brug for dig til at levere mit\n"
	.string "brev til STEVEN i DEWFORD.\p"
	.string "Efter det, lever vores pakke til KAPT.\n"
	.string "STERN i SLATEPORT.\p"
	.string "Du husker det, ikke sandt?\p"
	.string "Nu, da jeg er en travl PRESIDENT, bliver\n"
	.string "jeg nødt til at gå! Hej-hej!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: Oh! {PLAYER}kun!\p"
	.string "Ah, så du har mødt STEVEN! Jeg burde\n"
	.string "belønne dig, så!\p"
	.string "Når du besøger RUSTBORO igen, kom og\n"
	.string "besøg mig på mit kontor.\p"
	.string "Jeg venter på dig!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Åh! {PLAYER}{KUN}!\p"
	.string "Vidste du, at DEVON var ved at grave\n"
	.string "RUSTURF-TUNNELEN?\p"
	.string "Men vi lukkede operationen ned for at\n"
	.string "beskytte POKéMON'erne i området.\p"
	.string "Det er egentlig meget simpelt.\p"
	.string "Det er vigtigere at lade POKéMON'erne\n"
	.string "leve i fred end at bekymre os om vores\l"
	.string "egen bekvemmelighed.$"

MatchCall_Text_MrStone5::
	.string "HR. STEN: Hej, hej, {PLAYER}{KUN}!\p"
	.string "Jeg hørte fra nogen i PETALBORG at du\n"
	.string "er NORMANs barn!\p"
	.string "Ikke underligt, du er så dygtig et\n"
	.string "individ!$"

MatchCall_Text_MrStone6::
	.string "HR. STEN: Hvad er det?\p"
	.string "Du kæmpede mod din egen far og\n"
	.string "besejrede ham?\p"
	.string "Det er fantastisk!\p"
	.string "Jeg havde ingen anelse om, at jeg havde\n"
	.string "gjort venner med nogen så særlig!\l"
	.string "Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Hej! Dette er DEVON KONCERNEN… Åh, hej,\n"
	.string "{PLAYER}!\p"
	.string "Vores DIREKTØR var her for lidt siden,\n"
	.string "men han er gået ud.\p"
	.string "Vores DIREKTØR er travl, men du ser ud\n"
	.string "til at være lige så travlt beskæftiget,\l"
	.string "{PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Hvad? …Hvad er det?\p"
	.string "GROU… Ja? …DON?\p"
	.string "Du er ved at falde ud… …kan ikke høre…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Huh? …Hvad er det?\p"
	.string "Seaflo… Ja? …Grotte…?\p"
	.string "Du er ved at miste signalet… …kan ikke\n"
	.string "høre…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "HR. STEN: {PLAYER}{KUN}! Det er mig!\p"
	.string "Du var åbenbart involveret i alle mulige\n"
	.string "ting, men jeg, der er travl, aner ikke\l"
	.string "præcist hvad!\p"
	.string "Dog opfordrer jeg dig til at vælge den\n"
	.string "vej, du tror på, og gå ad den.\p"
	.string "Jeg vil altid støtte dig! Pas på dig\n"
	.string "selv!$"

MatchCall_Text_MrStone11::
	.string "HR. STONE: … … … … … … Er det måske\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Din stemme er så fuld af selvtillid, at\n"
	.string "jeg ikke genkendte dig med det samme!\p"
	.string "Hmm! Du må besøge os hos DEVON engang!$"



