@ TRANSLATED

@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " så smukt!$"

GiddyText_SoDarling::
	.string " så kær!$"

GiddyText_SoRelaxed::
	.string " så afslappende!$"

GiddyText_SoSunny::
	.string " så solrigt!$"

GiddyText_SoDesirable::
	.string " så ønskværdigt!$"

GiddyText_SoExciting::
	.string " så spændende!$"

GiddyText_SoAmusing::
	.string " så underholdende!$"

GiddyText_SoMagical::
	.string " så magisk!$"

GiddyText_Is::
	.string " er$"

GiddyText_DontYouAgree::
	.string " Er du ikke enig?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Jeg vil så gerne på ferie. Kender du et\n"
	.string "dejligt sted?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Jeg købte farvekridt med 120 farver! Er\n"
	.string "det ikke fantastisk?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Ville det ikke være dejligt, hvis vi\n"
	.string "kunne svæve væk på en sky af bobler?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Når du skriver på en sandstrand, bliver\n"
	.string "det skyllet væk. Det gør mig trist.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Hvordan er bunden af havet? Bare en\n"
	.string "gang vil jeg så gerne dykke ned!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Når du ser solen gå ned, får det dig så\n"
	.string "til at ville tage hjem?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Liggende tilbage i det grønne græs… Åh,\n"
	.string "det er så, så dejligt!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "HEMMELIGE BASER er så vidunderlige!\n"
	.string "Kan du ikke mærke spændingen?$"



