@ TRANSLATED

MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Denne bevægelse kan kun læres én gang.\n"
	.string "Er det i orden?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! Min POKéMON regerer totalt! Den er\n"
	.string "sejere end nogen POKéMON!\p"
	.string "Jeg vraltede rundt med et selvsikkert\n"
	.string "træd, indtil FORMANDEN skældte mig ud.\p"
	.string "Det tog selvsikkerheden ud af mit\n"
	.string "skridt.\p"
	.string "Hvis du vil, kan jeg lære en af dine\n"
	.string "POKéMON bevægelsen SWAGGER.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Hvad, nej? Kan du ikke komme ind i\n"
	.string "stemningen?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Okay, hvilken POKéMON vil lære hvordan\n"
	.string "man SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "Jeg vil bare rose min POKéMON fremover\n"
	.string "uden at blære mig.$"

MoveTutor_Text_RolloutTeach:
	.string "Vidste du, at du kan gå langt herfra i\n"
	.string "den retning uden at ændre retning?\p"
	.string "Jeg kunne måske endda rulle den vej.\p"
	.string "Tror du, din POKéMON vil rulle, også?\p"
	.string "Jeg kan lære en af dine POKéMON\n"
	.string "bevægelsen ROLLOUT, hvis du vil.$"

MoveTutor_Text_RolloutDeclined:
	.string "Du behøver ikke være genert. Lad os\n"
	.string "rulle!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sikkert! Det ville være\n"
	.string "fantastisk, hvis POKéMON lignede mig.$"

MoveTutor_Text_RolloutTaught:
	.string "At rulle rundt i græsset gør mig glad.\n"
	.string "Kom nu, lad os rulle!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Der er en bevægelse, der bliver\n"
	.string "stærkere, når du bruger den flere gange\l"
	.string "i træk.\p"
	.string "Det er en BUG-type bevægelse, og den er\n"
	.string "vildt sej.\p"
	.string "Den hedder FURY CUTTER. Vil du have, jeg\n"
	.string "lærer den til en POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Vi er ikke på samme bølgelængde.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay! Vis mig, hvilken POKéMON jeg skal\n"
	.string "lære den til.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Jeg får et kick ud af at se, om\n"
	.string "bevægelsen bliver ved med at ramme i\l"
	.string "træk!$"

MoveTutor_MimicTeach:
	.string "Ah, unge én!\p"
	.string "Jeg er også ung, men jeg efterligner de\n"
	.string "ældre folks stil og tale i denne by.\p"
	.string "Hvad siger du, unge én? Vil du sige ja,\n"
	.string "hvis jeg tilbyder at lære bevægelsen\l"
	.string "MIMIC?$"

MoveTutor_MimicDeclined:
	.string "Åh, øv! Jeg ville så gerne lære din\n"
	.string "POKéMON MIMIC!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! Og så vil jeg! Lad mig se den\n"
	.string "POKéMON, du ønsker, jeg skal lære.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC er en bevægelse med stor dybde.\p"
	.string "Kunne du udføre den til perfektion\n"
	.string "ligeså godt som mig…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Jeg vil have alle slags ting! Men jeg har\n"
	.string "brugt min lommepenge…\p"
	.string "Ville det ikke være dejligt, hvis der var\n"
	.string "en besværgelse, der fik penge til at\l"
	.string "dukke op, når du viftede med en finger?\p"
	.string "Hvis du vil, kan jeg lære din POKéMON\n"
	.string "bevægelsen METRONOME.\p"
	.string "Penge vil ikke dukke op, men din POKéMON\n"
	.string "vil vifte med en finger. Ja?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. Jeg er her, hvis du ændrer mening.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! Jeg vil lære den! Hvilken POKéMON\n"
	.string "skal jeg lære den til?$"

MoveTutor_Text_MetronomeTaught:
	.string "Når en POKéMON vifter med sin finger\n"
	.string "som en METRONOME, sker der alle mulige\l"
	.string "dejlige ting.\p"
	.string "Ville det ikke være dejligt, hvis vi også\n"
	.string "kunne bruge det?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! Min kone bruger HIDDEN POWER\n"
	.string "for at holde sig vågen.\p"
	.string "Hun burde bare tage en lur som mig, og\n"
	.string "SLEEP TALK.\p"
	.string "Jeg kan lære din POKéMON, hvordan man\n"
	.string "SLEEP TALK i stedet. Interesseret?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Åh, fint, fint. Du vil også holde dig\n"
	.string "vågen med HIDDEN POWER…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, et taknemmeligt barn! Hvilken\n"
	.string "POKéMON skal jeg lære?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Jeg har aldrig en gang fået min kones\n"
	.string "mønttrick rigtigt.\p"
	.string "Jeg ville være glad, hvis jeg fik det\n"
	.string "rigtigt, selv mens jeg SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach:
	.string "Når jeg ser den brede verden herfra\n"
	.string "oppe fra taget…\p"
	.string "Tænker jeg på, hvor dejligt det ville\n"
	.string "være, hvis der var mere end én af mig, så\l"
	.string "jeg kunne nyde alle slags liv.\p"
	.string "Selvfølgelig er det ikke muligt. Fnise…\p"
	.string "Jeg ved det! Ville du være interesseret\n"
	.string "i at få en POKéMON til at lære\l"
	.string "SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Åh, nej?\p"
	.string "En POKéMON kan lave en kopi af sig selv\n"
	.string "ved at bruge det, ved du.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Fnise… Hvilken POKéMON vil du have mig\n"
	.string "til at lære SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "Vi mennesker bør nyde vores egne liv til\n"
	.string "det yderste!\p"
	.string "Jeg håber, du også vil blive sådan!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Jeg kan ikke klare det mere!\p"
	.string "Det er fuldstændig håbløst!\p"
	.string "Jeg er en FIGHTING-type TRAINER, så\n"
	.string "jeg kan ikke vinde i MOSSDEEP GYM,\l"
	.string "uanset hvor hårdt jeg prøver!\p"
	.string "Argh! Slag! Slag! Slag! Slag! Slag! Slag!\p"
	.string "Hvad, ser du på mig sådan! Jeg slår kun\n"
	.string "jorden!\p"
	.string "Eller vil du have, jeg lærer din POKéMON\n"
	.string "DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! Gør du også grin med mig? Slag!\n"
	.string "Slag! Slag!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Hvad? Vil du det? Du er en god person!\n"
	.string "Hvilken POKéMON skal jeg lære?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Jeg vil have, at du skal vinde i\n"
	.string "MOSSDEEP GYM ved at bruge\l"
	.string "DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Suk…\p"
	.string "SOOTOPOLIS's GYM LEADER er virkelig\n"
	.string "beundringsværdig og elskelig.\p"
	.string "Men det betyder også, at jeg har mange\n"
	.string "rivaler om hans opmærksomhed.\p"
	.string "Han har en tiltrækning med en\n"
	.string "DOUBLE-EDGE. Jeg kunne ikke engang\l"
	.string "fange hans blik.\p"
	.string "Lad mig venligst lære din POKéMON\n"
	.string "bevægelsen DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Åh… Selv du afviste mig…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, hvilken POKéMON skal jeg lære\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Jeg vil ikke leve for kærlighed mere! Jeg\n"
	.string "vil blive stærk!$"

MoveTutor_Text_ExplosionTeach:
	.string "Jeg har ikke tænkt mig at blive her i\n"
	.string "provinsen for evigt.\p"
	.string "Se på mig, jeg skal til byen og blive et\n"
	.string "stort hit.\p"
	.string "Seriøst, jeg vil forårsage en enorm\n"
	.string "EXPLOSION af popularitet!\p"
	.string "Hvis du hørte det, vil jeg med glæde lære\n"
	.string "EXPLOSION til din POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! Du afviser mig, fordi jeg bor på\n"
	.string "landet?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fint! En EXPLOSION bliver det! Hvilken\n"
	.string "POKéMON vil eksplodere?$"

MoveTutor_Text_ExplosionTaught:
	.string "I lang tid har jeg lært POKéMON, hvordan\n"
	.string "man bruger EXPLOSION, men jeg har endnu\l"
	.string "ikke udløst min egen EXPLOSION…\p"
	.string "Måske er det, fordi jeg inderst inde\n"
	.string "hellere vil blive her…$"



