MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Denne bevægelse kan kun\n"
	.string "læres én gang. Er det i orden?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! Min POKéMON regerer totalt!\n"
	.string "Den er sejere end nogen POKéMON!\p"
	.string "Jeg vraltede rundt med et selvsikkert\n"
	.string "træd, indtil FORMANDEN skældte mig ud.\p"
	.string "Det tog selvsikkerheden ud af mit skridt.\p"
	.string "Hvis du vil, kan jeg lære en af dine\n"
	.string "POKéMON bevægelsen SWAGGER.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Hvad, nej? Kan du ikke komme\n"
	.string "ind i stemningen?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Okay, hvilken POKéMON vil lære\n"
	.string "hvordan man SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "Jeg vil bare rose min POKéMON fremover\n"
	.string "uden at blære mig.$"

MoveTutor_Text_RolloutTeach:
	.string "Vidste du, at du kan gå langt\n"
	.string "herfra i den retning uden at\n"
	.string "ændre retning?\p"
	.string "Jeg kunne måske endda rulle den vej.\p"
	.string "Tror du, din POKéMON vil rulle, også?\p"
	.string "Jeg kan lære en af dine POKéMON\n"
	.string "bevægelsen ROLLOUT, hvis du vil.$"

MoveTutor_Text_RolloutDeclined:
	.string "Du behøver ikke være genert.\n"
	.string "Lad os rulle!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sikkert! Det ville være fantastisk,\n"
	.string "hvis POKéMON lignede mig.$"

MoveTutor_Text_RolloutTaught:
	.string "At rulle rundt i græsset gør mig glad.\n"
	.string "Kom nu, lad os rulle!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Der er en bevægelse, der bliver stærkere,\n"
	.string "når du bruger den flere gange i træk.\p"
	.string "Det er en BUG-type bevægelse,\n"
	.string "og den er vildt sej.\p"
	.string "Den hedder FURY CUTTER.\n"
	.string "Vil du have, jeg lærer den til en POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Vi er ikke på samme bølgelængde.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Vis mig, hvilken POKéMON jeg skal lære den til.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Jeg får et kick ud af at se,\n"
	.string "om bevægelsen bliver ved med at ramme i træk!$"

MoveTutor_MimicTeach:
	.string "Ah, unge én!\p"
	.string "Jeg er også ung, men jeg efterligner\n"
	.string "de ældre folks stil og tale i denne by.\p"
	.string "Hvad siger du, unge én?\n"
	.string "Vil du sige ja, hvis jeg tilbyder at\n"
	.string "lære bevægelsen MIMIC?$"

MoveTutor_MimicDeclined:
	.string "Åh, øv! Jeg ville så gerne lære din\n"
	.string "POKéMON MIMIC!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! Og så vil jeg!\n"
	.string "Lad mig se den POKéMON, du ønsker, jeg skal lære.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC er en bevægelse med stor dybde.\p"
	.string "Kunne du udføre den til perfektion\n"
	.string "ligeså godt som mig…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Jeg vil have alle slags ting!\n"
	.string "Men jeg har brugt min lommepenge…\p"
	.string "Ville det ikke være dejligt, hvis der var\n"
	.string "en besværgelse, der fik penge til at dukke op,\n"
	.string "når du viftede med en finger?\p"
	.string "Hvis du vil, kan jeg lære din POKéMON\n"
	.string "bevægelsen METRONOME.\p"
	.string "Penge vil ikke dukke op, men din POKéMON\n"
	.string "vil vifte med en finger. Ja?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. Jeg er her, hvis du ændrer mening.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! Jeg vil lære den!\n"
	.string "Hvilken POKéMON skal jeg lære den til?$"

MoveTutor_Text_MetronomeTaught:
	.string "Når en POKéMON vifter med sin finger\n"
	.string "som en METRONOME, sker der alle mulige\n"
	.string "dejlige ting.\p"
	.string "Ville det ikke være dejligt, hvis vi\n"
	.string "også kunne bruge det?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! Min kone bruger HIDDEN\n"
	.string "POWER for at holde sig vågen.\p"
	.string "Hun burde bare tage en lur som mig,\n"
	.string "og SLEEP TALK.\p"
	.string "Jeg kan lære din POKéMON, hvordan man\n"
	.string "SLEEP TALK i stedet. Interesseret?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Åh, fint, fint. Du vil også holde dig vågen\n"
	.string "med HIDDEN POWER…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, et taknemmeligt barn!\n"
	.string "Hvilken POKéMON skal jeg lære?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Jeg har aldrig en gang fået min kones\n"
	.string "mønttrick rigtigt.\p"
	.string "Jeg ville være glad, hvis jeg fik det rigtigt,\n"
	.string "selv mens jeg SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach:
	.string "Når jeg ser den brede verden herfra\n"
	.string "oppe fra taget…\p"
	.string "Tænker jeg på, hvor dejligt det ville være,\n"
	.string "hvis der var mere end én af mig,\n"
	.string "så jeg kunne nyde alle slags liv.\p"
	.string "Selvfølgelig er det ikke muligt.\n"
	.string "Fnise…\p"
	.string "Jeg ved det! Ville du være interesseret\n"
	.string "i at få en POKéMON til at lære SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Åh, nej?\p"
	.string "En POKéMON kan lave en kopi af\n"
	.string "sig selv ved at bruge det, ved du.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Fnise…\n"
	.string "Hvilken POKéMON vil du have mig til at\n"
	.string "lære SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "Vi mennesker bør nyde vores\n"
	.string "egne liv til det yderste!\p"
	.string "Jeg håber, du også vil blive sådan!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Jeg kan ikke klare det mere!\p"
	.string "Det er fuldstændig håbløst!\p"
	.string "Jeg er en FIGHTING-type TRAINER,\n"
	.string "så jeg kan ikke vinde i MOSSDEEP GYM,\n"
	.string "uanset hvor hårdt jeg prøver!\p"
	.string "Argh! Slag! Slag! Slag!\n"
	.string "Slag! Slag! Slag!\p"
	.string "Hvad, ser du på mig sådan!\n"
	.string "Jeg slår kun jorden!\p"
	.string "Eller vil du have, jeg lærer din\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! Gør du også grin med mig?\n"
	.string "Slag! Slag! Slag!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Hvad? Vil du det? Du er en god person!\n"
	.string "Hvilken POKéMON skal jeg lære?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Jeg vil have, at du skal vinde i MOSSDEEP GYM\n"
	.string "ved at bruge DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Suk…\p"
	.string "SOOTOPOLIS's GYM LEADER er virkelig\n"
	.string "beundringsværdig og elskelig.\p"
	.string "Men det betyder også, at jeg har mange\n"
	.string "rivaler om hans opmærksomhed.\p"
	.string "Han har en tiltrækning med en DOUBLE-EDGE.\n"
	.string "Jeg kunne ikke engang fange hans blik.\p"
	.string "Lad mig venligst lære din POKéMON\n"
	.string "bevægelsen DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Åh…\n"
	.string "Selv du afviste mig…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, hvilken POKéMON skal jeg lære\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Jeg vil ikke leve for kærlighed mere!\n"
	.string "Jeg vil blive stærk!$"

MoveTutor_Text_ExplosionTeach:
	.string "Jeg har ikke tænkt mig at blive\n"
	.string "her i provinsen for evigt.\p"
	.string "Se på mig, jeg skal til byen\n"
	.string "og blive et stort hit.\p"
	.string "Seriøst, jeg vil forårsage\n"
	.string "en enorm EXPLOSION af popularitet!\p"
	.string "Hvis du hørte det, vil jeg med glæde\n"
	.string "lære EXPLOSION til din POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! Du afviser mig, fordi\n"
	.string "jeg bor på landet?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fint! En EXPLOSION bliver det!\n"
	.string "Hvilken POKéMON vil eksplodere?$"

MoveTutor_Text_ExplosionTaught:
	.string "I lang tid har jeg lært POKéMON,\n"
	.string "hvordan man bruger EXPLOSION, men jeg har\n"
	.string "endnu ikke udløst min egen EXPLOSION…\p"
	.string "Måske er det, fordi jeg inderst inde\n"
	.string "hellere vil blive her…$"
