@ TRANSLATED

gText_ObtainedTheItem::
	.string "Modtog {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Rygsækken er fuld…$"

gText_PutItemInPocket::
	.string "{PLAYER} lagde {STR_VAR_2} i\n"
	.string "{STR_VAR_3} LOMMEN.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} fandt en {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Øv! Rygsækken er fuld…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} lagde {STR_VAR_2} i\n"
	.string "RYGSÆKKEN.$"

gText_ObtainedTheDecor::
	.string "Modtog {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Øv! Der er ikke plads til endnu en\n"
	.string "{STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} blev overført til PC'en.$"



