@ TRANSLATED

gText_ObtainedTheItem::
	.string "Modtog {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Rygsækken er fuld…$"

gText_PutItemInPocket::
	.string "{PLAYER} lagde {STR_VAR_2}\n"
	.string "i {STR_VAR_3} LOMMEN.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} fandt en {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Øv!\n"
	.string "Rygsækken er fuld…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} lagde {STR_VAR_2}\n"
	.string "i RYGSÆKKEN.$"

gText_ObtainedTheDecor::
	.string "Modtog {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Øv! Der er ikke plads til\n"
	.string "endnu en {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} blev overført\n"
	.string "til PC'en.$"
