@ TRANSLATED

gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} blev overført til\n"
	.string "NOGENS PC.\p"
	.string "Den blev placeret i  BOKS\n"
	.string "“{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} blev overført til\n"
	.string "LANETTES PC.\p"
	.string "Den blev placeret i  BOKS\n"
	.string "“{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "BOKS “{STR_VAR_3}” på NOGENS PC var\n"
	.string "fuld.\p"
	.string "{STR_VAR_2} blev overført til BOKS\n"
	.string "“{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "BOKS “{STR_VAR_3}” på LANETTES PC\n"
	.string "var fuld.\p"
	.string "{STR_VAR_2} blev overført til BOKS\n"
	.string "“{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "Der er ikke mere plads til POKéMON!\p"
	.string "POKéMON BOKSENE er fulde og kan ikke\n"
	.string "tage imod flere!$"

gText_NicknameThisPokemon::
	.string "Vil du give denne {STR_VAR_1} et\n"
	.string "kælenavn?$"



