@ TRANSLATED

gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} blev overført til\n"
	.string "NOGENS PC.\p"
	.string "Den blev placeret i \n"
	.string "BOKS “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} blev overført til\n"
	.string "LANETTES PC.\p"
	.string "Den blev placeret i \n"
	.string "BOKS “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "BOKS “{STR_VAR_3}” på\n"
	.string "NOGENS PC var fuld.\p"
	.string "{STR_VAR_2} blev overført til\n"
	.string "BOKS “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "BOKS “{STR_VAR_3}” på\n"
	.string "LANETTES PC var fuld.\p"
	.string "{STR_VAR_2} blev overført til\n"
	.string "BOKS “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "Der er ikke mere plads til POKéMON!\p"
	.string "POKéMON BOKSENE er fulde og\n"
	.string "kan ikke tage imod flere!$"

gText_NicknameThisPokemon::
	.string "Vil du give denne {STR_VAR_1} et kælenavn?$"
