@ TRANSLATED

gText_WouldYouLikeToRestYourPkmn::
	.string "Hej, og velkommen til\n"
	.string "POKéMON CENTERET.\p"
	.string "Vi genskaber dine trætte POKéMON\n"
	.string "til fuld sundhed.\p"
	.string "Vil du hvile dine POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, jeg tager dine POKéMON\n"
	.string "i et par sekunder.$"

gText_RestoredPkmnToFullHealth::
	.string "Tak fordi du ventede.\p"
	.string "Vi har genskabt dine POKéMON\n"
	.string "til fuld sundhed.$"

gText_WeHopeToSeeYouAgain::
	.string "Vi håber at se dig igen!$"

gText_WelcomeCutShort::
	.string "Hej, og velkommen til\n"
	.string "POKéMON CENTERET.\p"
	.string "Vi genskaber dine trætte POKéMON\n"
	.string "til fuld sundhed.\p"
	.string "Vil du gerne…$"

gText_NoticesGoldCard::
	.string "D-dét kort…\n"
	.string "Kunne det være… GULD KORTET?!\p"
	.string "Åh, guldfarven er strålende!\n"
	.string "De fire stjerner synes at funkler!\p"
	.string "Jeg har set flere TRÆNERE med\n"
	.string "et SØLVKORT før, men, {PLAYER},\l"
	.string "du er den første TRÆNER jeg nogensinde\l"
	.string "har set med et GULD KORT!\p"
	.string "Okay, {PLAYER}, tillad mig\n"
	.string "ære at hvile dine POKéMON!$"

gText_YouWantTheUsual::
	.string "Jeg er henrykt over at se dig, {PLAYER}!\n"
	.string "Du vil have det sædvanlige, ikke?$"

gText_IllTakeYourPkmn2::
	.string "Okay, jeg tager dine POKéMON\n"
	.string "i et par sekunder.$"

gText_ThankYouForWaiting::
	.string "Tak fordi du ventede.$"

gText_WeHopeToSeeYouAgain2::
	.string "Vi håber at se dig igen!$"
