@ TRANSLATED

gText_WouldYouLikeToRestYourPkmn::
	.string "Hej, og velkommen til POKéMON CENTERET.\p"
	.string "Vi genskaber dine trætte POKéMON til\n"
	.string "fuld sundhed.\p"
	.string "Vil du hvile dine POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, jeg tager dine POKéMON i et par\n"
	.string "sekunder.$"

gText_RestoredPkmnToFullHealth::
	.string "Tak fordi du ventede.\p"
	.string "Vi har genskabt dine POKéMON til fuld\n"
	.string "sundhed.$"

gText_WeHopeToSeeYouAgain::
	.string "Vi håber at se dig igen!$"

gText_WelcomeCutShort::
	.string "Hej, og velkommen til POKéMON CENTERET.\p"
	.string "Vi genskaber dine trætte POKéMON til\n"
	.string "fuld sundhed.\p"
	.string "Vil du gerne…$"

gText_NoticesGoldCard::
	.string "D-dét kort… Kunne det være… GULD\n"
	.string "KORTET?!\p"
	.string "Åh, guldfarven er strålende! De fire\n"
	.string "stjerner synes at funkler!\p"
	.string "Jeg har set flere TRÆNERE med et\n"
	.string "SØLVKORT før, men, {PLAYER}, du er den\l"
	.string "første TRÆNER jeg nogensinde har set\l"
	.string "med et GULD KORT!\p"
	.string "Okay, {PLAYER}, tillad mig ære at hvile\n"
	.string "dine POKéMON!$"

gText_YouWantTheUsual::
	.string "Jeg er henrykt over at se dig,\n"
	.string "{PLAYER}! Du vil have det sædvanlige,\l"
	.string "ikke?$"

gText_IllTakeYourPkmn2::
	.string "Okay, jeg tager dine POKéMON i et par\n"
	.string "sekunder.$"

gText_ThankYouForWaiting::
	.string "Tak fordi du ventede.$"

gText_WeHopeToSeeYouAgain2::
	.string "Vi håber at se dig igen!$"



