@ TRANSLATED

gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Er du nysgerrig på, hvordan din\n"
	.string "POKéDEX klarer sig?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Åh, du har ikke fanget nok\n"
	.string "POKéMON til at gøre det værd.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Så du har set {STR_VAR_1} POKéMON\n"
	.string "og fanget {STR_VAR_2} POKéMON…$"

gBirchDexRatingText_LessThan10::
	.string "Gå mere rundt i græsområderne\n"
	.string "og kig mere omhyggeligt efter POKéMON.$"

gBirchDexRatingText_LessThan20::
	.string "Jeg antager, at du er ved at få\n"
	.string "det ind. Men det bliver sværere herfra.$"

gBirchDexRatingText_LessThan30::
	.string "Nogle POKéMON vises kun i\n"
	.string "bestemte områder.\l"
	.string "Du skal være vedholdende.$"

gBirchDexRatingText_LessThan40::
	.string "Nå, der kunne bruges flere af dem,\n"
	.string "men det ligner mere en POKéDEX nu.$"

gBirchDexRatingText_LessThan50::
	.string "Dette går ret godt.\n"
	.string "Fortsæt det gode arbejde.$"

gBirchDexRatingText_LessThan60::
	.string "Bruger du nogen STÆNGER?\n"
	.string "Der er mange POKéMON i havet.$"

gBirchDexRatingText_LessThan70::
	.string "I stedet for bare at fange POKéMON,\n"
	.string "hvorfor ikke også lade dem udvikle sig?$"

gBirchDexRatingText_LessThan80::
	.string "Dette kommer til at blive en fantastisk\n"
	.string "POKéDEX.\l"
	.string "Det er følelsen, jeg får.$"

gBirchDexRatingText_LessThan90::
	.string "Du har samlet så mange…\n"
	.string "Dit talent er bemærkelsesværdigt!$"

gBirchDexRatingText_LessThan100::
	.string "Har du besøgt SAFARI ZONE?\p"
	.string "Jeg hører, at der er nogle POKéMON,\n"
	.string "der kun kan fanges der.$"

gBirchDexRatingText_LessThan110::
	.string "Du har endelig nået\n"
	.string "mærket på 100 slags.\p"
	.string "Det er en imponerende POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "Der kunne være POKéMON, der kan findes\n"
	.string "ved at bruge ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "Du burde få nogle flere POKéMON\n"
	.string "ved at handle med andre.$"

gBirchDexRatingText_LessThan140::
	.string "Jeg har hørt om POKéMON, der udvikler sig,\n"
	.string "når de kommer til at elske deres TRÆNERE.$"

gBirchDexRatingText_LessThan150::
	.string "Jeg havde ingen idé om, at der var så\n"
	.string "mange POKéMON-arter i HOENN-regionen.$"

gBirchDexRatingText_LessThan160::
	.string "Fra tid til anden vises nogle POKéMON\n"
	.string "i store mængder som udbrud.\p"
	.string "Gå ikke glip af sådanne muligheder.$"

gBirchDexRatingText_LessThan170::
	.string "Man kan få en rigtig god idé om\n"
	.string "POKéMON i HOENN-regionen\n"
	.string "ved at se igennem din POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Jeg ville sige, at du allerede kvalificerer\n"
	.string "dig som en POKéMON-PROFESSOR, og en god\l"
	.string "en af slagsen også!$"

gBirchDexRatingText_LessThan190::
	.string "Med en så komplet POKéDEX er du\n"
	.string "en rigtig professionel til dette!$"

gBirchDexRatingText_LessThan200::
	.string "Du er meget tæt på at fuldføre\n"
	.string "denne POKéDEX.\l"
	.string "Jeg kan mærke det i mine knogler!$"

gBirchDexRatingText_DexCompleted::
	.string "Tillykke!\n"
	.string "Din POKéDEX er fuldendt!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "På landsbasis…\p"
	.string "Du har set {STR_VAR_1} POKéMON\n"
	.string "og fanget {STR_VAR_2} POKéMON…$"
