@ TRANSLATED

gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Er du nysgerrig på, hvordan din POKéDEX\n"
	.string "klarer sig?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Åh, du har ikke fanget nok POKéMON\n"
	.string "til at gøre det værd.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Så du har set {STR_VAR_1} POKéMON\n"
	.string "og fanget {STR_VAR_2} POKéMON…$"

gBirchDexRatingText_LessThan10::
	.string "Gå mere rundt i græsområderne og kig\n"
	.string "mere omhyggeligt efter POKéMON.$"

gBirchDexRatingText_LessThan20::
	.string "Jeg antager, at du er ved at få det ind.\n"
	.string "Men det bliver sværere herfra.$"

gBirchDexRatingText_LessThan30::
	.string "Nogle POKéMON vises kun i bestemte\n"
	.string "områder. Du skal være vedholdende.$"

gBirchDexRatingText_LessThan40::
	.string "Nå, der kunne bruges flere af dem, men\n"
	.string "det ligner mere en POKéDEX nu.$"

gBirchDexRatingText_LessThan50::
	.string "Dette går ret godt. Fortsæt det gode\n"
	.string "arbejde.$"

gBirchDexRatingText_LessThan60::
	.string "Bruger du nogen STÆNGER? Der er mange\n"
	.string "POKéMON i havet.$"

gBirchDexRatingText_LessThan70::
	.string "I stedet for bare at fange POKéMON,\n"
	.string "hvorfor ikke også lade dem udvikle sig?$"

gBirchDexRatingText_LessThan80::
	.string "Dette kommer til at blive en fantastisk\n"
	.string "POKéDEX. Det er følelsen, jeg får.$"

gBirchDexRatingText_LessThan90::
	.string "Du har samlet så mange… Dit talent er\n"
	.string "bemærkelsesværdigt!$"

gBirchDexRatingText_LessThan100::
	.string "Har du besøgt SAFARI ZONE?\p"
	.string "Jeg hører, at der er nogle POKéMON, der\n"
	.string "kun kan fanges der.$"

gBirchDexRatingText_LessThan110::
	.string "Du har endelig nået mærket på 100 slags.\p"
	.string "Det er en imponerende POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "Der kunne være POKéMON, der kan findes\n"
	.string "ved at bruge ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "Du burde få nogle flere POKéMON ved at\n"
	.string "handle med andre.$"

gBirchDexRatingText_LessThan140::
	.string "Jeg har hørt om POKéMON, der udvikler\n"
	.string "sig, når de kommer til at elske deres\l"
	.string "TRÆNERE.$"

gBirchDexRatingText_LessThan150::
	.string "Jeg havde ingen idé om, at der var så\n"
	.string "mange POKéMON-arter i HOENN-regionen.$"

gBirchDexRatingText_LessThan160::
	.string "Fra tid til anden vises nogle POKéMON i\n"
	.string "store mængder som udbrud.\p"
	.string "Gå ikke glip af sådanne muligheder.$"

gBirchDexRatingText_LessThan170::
	.string "Man kan få en rigtig god idé om POKéMON\n"
	.string "i HOENN-regionen ved at se igennem din\l"
	.string "POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Jeg ville sige, at du allerede\n"
	.string "kvalificerer dig som en\l"
	.string "POKéMON-PROFESSOR, og en god en af\l"
	.string "slagsen også!$"

gBirchDexRatingText_LessThan190::
	.string "Med en så komplet POKéDEX er du en\n"
	.string "rigtig professionel til dette!$"

gBirchDexRatingText_LessThan200::
	.string "Du er meget tæt på at fuldføre denne\n"
	.string "POKéDEX. Jeg kan mærke det i mine\l"
	.string "knogler!$"

gBirchDexRatingText_DexCompleted::
	.string "Tillykke! Din POKéDEX er fuldendt!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm… På landsbasis…\p"
	.string "Du har set {STR_VAR_1} POKéMON og\n"
	.string "fanget {STR_VAR_2} POKéMON…$"



