@ TRANSLATED

Questionnaire_Text_FillOut::
	.string "Der er en spørgeskema. Ønsker du at\n"
	.string "udfylde det?$"

Questionnaire_Text_ThankYou::
	.string "Tak fordi du tog dig tid til at udfylde\n"
	.string "vores spørgeskema.\p"
	.string "Din feedback vil blive brugt til\n"
	.string "fremtidig reference.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Åh, hej! Kender du de ord?\p"
	.string "Det betyder, at du må kende til Mystery\n"
	.string "Gift.\p"
	.string "Fra nu af burde du modtage Mystery\n"
	.string "Gifts!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Når du har gemt dit spil, kan du få\n"
	.string "adgang til Mystery Gift.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Åh, hej! Kender du de ord?\p"
	.string "Det betyder, at du må kende til Mystery\n"
	.string "Event.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Når du har gemt dit spil, kan du få\n"
	.string "adgang til Mystery Event.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Tak fordi du bruger Mystery Event\n"
	.string "Systemet.\p"
	.string "Du må være {PLAYER}. Der er en billet\n"
	.string "her til dig.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Den ser ud til at være til brug ved\n"
	.string "Lilycove City havn.\p"
	.string "Hvorfor ikke prøve det og se, hvad det\n"
	.string "handler om?$"



