@ TRANSLATED

Questionnaire_Text_FillOut::
	.string "Der er en spørgeskema.\n"
	.string "Ønsker du at udfylde det?$"

Questionnaire_Text_ThankYou::
	.string "Tak fordi du tog dig tid til\n"
	.string "at udfylde vores spørgeskema.\p"
	.string "Din feedback vil blive brugt til\n"
	.string "fremtidig reference.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Åh, hej!\n"
	.string "Kender du de ord?\p"
	.string "Det betyder, at du må kende til\n"
	.string "Mystery Gift.\p"
	.string "Fra nu af burde du modtage\n"
	.string "Mystery Gifts!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Når du har gemt dit spil, kan du\n"
	.string "få adgang til Mystery Gift.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Åh, hej!\n"
	.string "Kender du de ord?\p"
	.string "Det betyder, at du må kende til\n"
	.string "Mystery Event.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Når du har gemt dit spil, kan du\n"
	.string "få adgang til Mystery Event.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Tak fordi du bruger Mystery\n"
	.string "Event Systemet.\p"
	.string "Du må være {PLAYER}.\n"
	.string "Der er en billet her til dig.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Den ser ud til at være til brug ved\n"
	.string "Lilycove City havn.\p"
	.string "Hvorfor ikke prøve det og se, hvad\n"
	.string "det handler om?$"
