@ TRANSLATED

.align 2
gText_ConfirmSave::
	.string "Ønsker du at gemme?$"

gText_AlreadySavedFile::
	.string "Der er allerede en gemt fil.\n"
	.string "Er det okay at overskrive den?$"

gText_SavingDontTurnOff::
	.string "GEMMER…\n"
	.string "SLUK IKKE FOR STRØMMEN.$"

gText_PlayerSavedGame::
	.string "{PLAYER} har gemt spillet.$"

gText_DifferentSaveFile::
	.string "ADVARSEL!\p"
	.string "Der er allerede en anden gemt fil.\p"
	.string "Hvis du gemmer nu, vil den anden\n"
	.string "fil's eventyr, herunder genstande og\l"
	.string "POKéMON, være helt tabt.\p"
	.string "Er du sikker på, at du vil gemme nu\n"
	.string "og overskrive den anden gemte fil?$"

gText_SaveError::
	.string "Fejl ved gemning.\p"
	.string "Udskift venligst\n"
	.string "backup-hukommelsen.$"

gText_SavingDontTurnOffPower::
	.string "GEMMER…\n"
	.string "SLUK IKKE FOR STRØMMEN.$"
