@ TRANSLATED

SecretBase_Text_Trainer0Intro:
	.string "Har du allerede lavet en HEMMELIG BASE?\p"
	.string "Jeg gik her, der og alle vegne, før jeg\n"
	.string "valgte dette sted.\p"
	.string "Da du allerede er her, hvordan kunne du\n"
	.string "tænke dig at kæmpe?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Okay! Her kommer vi!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Hunh? Oh, du kan ikke lige nu…$"

SecretBase_Text_Trainer0Defeated::
	.string "Waaargh! Du er for stærk! Om mig at\n"
	.string "tabe… Hold det venligst hemmeligt!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Hvad synes du om min HEMMELIGE BASE?\n"
	.string "Kom og besøg mig igen i morgen.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Har du allerede lavet en HEMMELIG BASE?\p"
	.string "Jeg gik her, der og alle vegne, før jeg\n"
	.string "valgte dette sted.\p"
	.string "Føl dig fri til at hænge ud!$"

SecretBase_Text_Trainer5Intro:
	.string "Der er masser af steder, hvor du kan\n"
	.string "lave en HEMMELIG BASE.\p"
	.string "Men jeg kan bedst lide dette sted.\n"
	.string "Synes du ikke, det er dejligt?\p"
	.string "Åh, vil du have en kamp?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Okay, her går det løs!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Åh… Du kan ikke lige nu, okay.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmm… Det er vores tab… Men fortæl det\n"
	.string "ikke til nogen! Det er en fortrolig\l"
	.string "hemmelighed!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Hvis du er i dette område igen, håber\n"
	.string "jeg, du vil besøge mig.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Der er masser af steder, hvor du kan\n"
	.string "lave en HEMMELIG BASE.\p"
	.string "Men jeg kan bedst lide dette sted.\n"
	.string "Synes du ikke, det er dejligt?$"

SecretBase_Text_Trainer1Intro:
	.string "Dette er et populært sted. Det er altid\n"
	.string "optaget.\p"
	.string "Åh! Overvejede du også at tage dette\n"
	.string "sted?\p"
	.string "Jeg skal fortælle dig hvad, du kan få\n"
	.string "dette sted, hvis du kan slå mig.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Okay! Jeg vil forsvare min HEMMELIGE\n"
	.string "BASE!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Hunh? Er det rigtigt? Er du ikke\n"
	.string "interesseret i dette sted?$"

SecretBase_Text_Trainer1Defeated::
	.string "Jeg kan ikke fortsætte! Jeg overgiver\n"
	.string "mig!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Okay, når jeg flytter en dag, bliver\n"
	.string "dette sted dit!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Dette er et populært sted. Det er altid\n"
	.string "optaget.\p"
	.string "Jeg ventede længe på, at det skulle\n"
	.string "åbne. Jeg fik endelig lov til at bruge\l"
	.string "det!$"

SecretBase_Text_Trainer6Intro:
	.string "Velkommen til mit POKéMON\n"
	.string "LABORATORIUM.\p"
	.string "Jeg udfører forskning i\n"
	.string "hemmelighedskampe.\p"
	.string "Vil du gerne se, hvor stærk jeg er?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Jeg vil give det hele!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Åh. En anden gang, så!$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm… Jeg har stadig meget at lære. Jeg\n"
	.string "skal studere lidt mere.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Tak for kampen. Kom venligst tilbage\n"
	.string "igen i morgen.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Velkommen til mit POKéMON\n"
	.string "LABORATORIUM.\p"
	.string "Jeg udfører forskning i\n"
	.string "hemmelighedskampe.$"

SecretBase_Text_Trainer2Intro:
	.string "En stor herregård er fin, men jeg kan\n"
	.string "bedre lide denne slags sted.\p"
	.string "Jeg kan lide det, fordi alle mulige\n"
	.string "mennesker kommer og besøger mig.\p"
	.string "Så, hvordan vil du have en kamp?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Sådan!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Når du er klar, råb til mig!$"

SecretBase_Text_Trainer2Defeated::
	.string "Aww! Færdig! Men det er stadig sjovt at\n"
	.string "kæmpe!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Nå, uanset hvad, jeg skal købe lidt\n"
	.string "dekorationer og møbler.\p"
	.string "Jeg vil have min HEMMELIGE BASE til at\n"
	.string "være et sted, andre mennesker kan nyde.$"

SecretBase_Text_Trainer2PreChampion:
	.string "En stor herregård er fin, men jeg kan\n"
	.string "bedre lide denne slags sted.\p"
	.string "Jeg kan lide det, fordi alle mulige\n"
	.string "mennesker kommer og besøger mig.$"

SecretBase_Text_Trainer7Intro:
	.string "Jeg elsker simpelthen at shoppe efter\n"
	.string "dekorationer og møbler.\p"
	.string "Jeg elsker også at opdrætte POKéMON\n"
	.string "lige så meget.\p"
	.string "Hvis du vil være så venlig, vil du så\n"
	.string "kæmpe med mine POKéMON?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Tak. Skal vi begynde?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Åh. Hvor skuffende…$"

SecretBase_Text_Trainer7Defeated::
	.string "Jeg overgiver mig…$"

SecretBase_Text_Trainer7PostBattle:
	.string "Det var alt sammen sjovt! Jeg skal ud og\n"
	.string "nyde shoppingen nu.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Jeg elsker simpelthen at shoppe efter\n"
	.string "dekorationer og møbler.\p"
	.string "Jeg elsker også at opdrætte POKéMON\n"
	.string "lige så meget.$"

SecretBase_Text_Trainer3Intro:
	.string "Nogle mennesker laver deres HEMMELIGE\n"
	.string "BASER på svært tilgængelige steder. Vil\l"
	.string "de bare ligge lavt?\p"
	.string "Men siden du fandt mig, hvad med vi får\n"
	.string "en kamp?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Jeg giver ikke op let!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Åh… Er du måske træt af at lede efter\n"
	.string "dette sted?$"

SecretBase_Text_Trainer3Defeated::
	.string "Jeg tabte…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Hvor er din HEMMELIGE BASE? Jeg skal\n"
	.string "besøge dig der.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Nogle mennesker laver deres HEMMELIGE\n"
	.string "BASER på svært tilgængelige steder. Vil\l"
	.string "de bare ligge lavt?$"

SecretBase_Text_Trainer8Intro:
	.string "Folk har fortalt mig, at du kan få\n"
	.string "dekorationer på flere måder.\p"
	.string "Vi skulle have et løb for at se, hvem der\n"
	.string "kan få flottere dekorationer og møbler!\p"
	.string "I mellemtiden, vil du så kæmpe?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Dette er min HEMMELIGE BASE. Jeg kan\n"
	.string "ikke tabe!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Jeg vil kæmpe med dig når som helst.$"

SecretBase_Text_Trainer8Defeated::
	.string "Huh? Tabte jeg lige?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Jeg taber ikke ved at samle\n"
	.string "dekorationer. Kom og besøg igen!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Folk har fortalt mig, at du kan få\n"
	.string "dekorationer på flere måder.\p"
	.string "Vi skulle have et løb for at se, hvem der\n"
	.string "kan få flottere dekorationer og møbler!$"

SecretBase_Text_Trainer4Intro:
	.string "Jeg fandt et sted, jeg kunne lide, og\n"
	.string "jeg pyntede det op med mine\l"
	.string "yndlingsdekorationer.\p"
	.string "Jeg opdrætter min yndlingsPOKéMON og\n"
	.string "bliver stærkere med den.\p"
	.string "Det er hvad jeg gør. Vil du kæmpe med\n"
	.string "mig?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Vis mig hvad du er lavet af!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Jeg antager, at der er tidspunkter,\n"
	.string "hvor du ikke er interesseret.$"

SecretBase_Text_Trainer4Defeated::
	.string "Jeg ved præcis hvad du er lavet af nu.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Vi kan begge blive stærkere. Lad os\n"
	.string "fortsætte!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Jeg fandt et sted, jeg kunne lide, og\n"
	.string "jeg pyntede det op med mine\l"
	.string "yndlingsdekorationer.\p"
	.string "Jeg opdrætter min yndlingsPOKéMON og\n"
	.string "bliver stærkere med den.\p"
	.string "Hver dag er en god dag.$"

SecretBase_Text_Trainer9Intro:
	.string "Du kan lære meget om smag og sans hos\n"
	.string "mennesker ud fra de slags dekorationer,\l"
	.string "de har, og hvordan de viser dem frem.\p"
	.string "Hvad synes du om min smag? Er du\n"
	.string "målløs?\p"
	.string "Vil du se min stil i kamp?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Der er ingen tilbageholdenhed!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Jeg vil med glæde demonstrere min stil\n"
	.string "når som helst.$"

SecretBase_Text_Trainer9Defeated::
	.string "Du er suverænt talentfuld! Din styrke\n"
	.string "synes at være uendelig…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Hvad synes du om min stil? Jeg vil blive\n"
	.string "ved med at polere den!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Du kan lære meget om smag og sans hos\n"
	.string "mennesker ud fra de slags dekorationer,\l"
	.string "de har, og hvordan de viser dem frem.\p"
	.string "Hvad synes du om min smag? Er du\n"
	.string "målløs?$"



