SecretBase_Text_Trainer0Intro:
	.string "Har du allerede lavet en HEMMELIG BASE?\p"
	.string "Jeg gik her, der og alle vegne, før jeg\n"
	.string "valgte dette sted.\p"
	.string "Da du allerede er her, hvordan kunne\n"
	.string "du tænke dig at kæmpe?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Okay!\n"
	.string "Her kommer vi!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Hunh?\n"
	.string "Oh, du kan ikke lige nu…$"

SecretBase_Text_Trainer0Defeated::
	.string "Waaargh! Du er for stærk!\n"
	.string "Om mig at tabe… Hold det venligst hemmeligt!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Hvad synes du om min HEMMELIGE BASE?\n"
	.string "Kom og besøg mig igen i morgen.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Har du allerede lavet en HEMMELIG BASE?\p"
	.string "Jeg gik her, der og alle vegne, før jeg\n"
	.string "valgte dette sted.\p"
	.string "Føl dig fri til at hænge ud!$"

SecretBase_Text_Trainer5Intro:
	.string "Der er masser af steder, hvor du kan\n"
	.string "lave en HEMMELIG BASE.\p"
	.string "Men jeg kan bedst lide dette sted.\n"
	.string "Synes du ikke, det er dejligt?\p"
	.string "Åh, vil du have en kamp?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Okay, her går det løs!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Åh…\n"
	.string "Du kan ikke lige nu, okay.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmm… Det er vores tab…\n"
	.string "Men fortæl det ikke til nogen!\l"
	.string "Det er en fortrolig hemmelighed!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Hvis du er i dette område igen,\n"
	.string "håber jeg, du vil besøge mig.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Der er masser af steder, hvor du kan\n"
	.string "lave en HEMMELIG BASE.\p"
	.string "Men jeg kan bedst lide dette sted.\n"
	.string "Synes du ikke, det er dejligt?$"

SecretBase_Text_Trainer1Intro:
	.string "Dette er et populært sted.\n"
	.string "Det er altid optaget.\p"
	.string "Åh! Overvejede du også at\n"
	.string "tage dette sted?\p"
	.string "Jeg skal fortælle dig hvad, du kan få\n"
	.string "dette sted, hvis du kan slå mig.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Okay!\n"
	.string "Jeg vil forsvare min HEMMELIGE BASE!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Hunh? Er det rigtigt?\n"
	.string "Er du ikke interesseret i dette sted?$"

SecretBase_Text_Trainer1Defeated::
	.string "Jeg kan ikke fortsætte!\n"
	.string "Jeg overgiver mig!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Okay, når jeg flytter en dag,\n"
	.string "bliver dette sted dit!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Dette er et populært sted.\n"
	.string "Det er altid optaget.\p"
	.string "Jeg ventede længe på, at det skulle åbne.\n"
	.string "Jeg fik endelig lov til at bruge det!$"

SecretBase_Text_Trainer6Intro:
	.string "Velkommen til mit POKéMON LABORATORIUM.\p"
	.string "Jeg udfører forskning i hemmelighedskampe.\p"
	.string "Vil du gerne se, hvor stærk jeg er?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Jeg vil give det hele!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Åh.\n"
	.string "En anden gang, så!$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm… Jeg har stadig meget at lære.\n"
	.string "Jeg skal studere lidt mere.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Tak for kampen.\n"
	.string "Kom venligst tilbage igen i morgen.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Velkommen til mit POKéMON LABORATORIUM.\p"
	.string "Jeg udfører forskning i hemmelighedskampe.$"

SecretBase_Text_Trainer2Intro:
	.string "En stor herregård er fin, men jeg kan\n"
	.string "bedre lide denne slags sted.\p"
	.string "Jeg kan lide det, fordi alle mulige\n"
	.string "mennesker kommer og besøger mig.\p"
	.string "Så, hvordan vil du have en kamp?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Sådan!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Når du er klar, råb til mig!$"

SecretBase_Text_Trainer2Defeated::
	.string "Aww! Færdig!\n"
	.string "Men det er stadig sjovt at kæmpe!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Nå, uanset hvad, jeg skal købe lidt\n"
	.string "dekorationer og møbler.\p"
	.string "Jeg vil have min HEMMELIGE BASE til at være\n"
	.string "et sted, andre mennesker kan nyde.$"

SecretBase_Text_Trainer2PreChampion:
	.string "En stor herregård er fin, men jeg kan\n"
	.string "bedre lide denne slags sted.\p"
	.string "Jeg kan lide det, fordi alle mulige\n"
	.string "mennesker kommer og besøger mig.$"

SecretBase_Text_Trainer7Intro:
	.string "Jeg elsker simpelthen at shoppe efter\n"
	.string "dekorationer og møbler.\p"
	.string "Jeg elsker også at opdrætte POKéMON\n"
	.string "lige så meget.\p"
	.string "Hvis du vil være så venlig, vil du så\n"
	.string "kæmpe med mine POKéMON?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Tak.\n"
	.string "Skal vi begynde?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Åh.\n"
	.string "Hvor skuffende…$"

SecretBase_Text_Trainer7Defeated::
	.string "Jeg overgiver mig…$"

SecretBase_Text_Trainer7PostBattle:
	.string "Det var alt sammen sjovt!\n"
	.string "Jeg skal ud og nyde shoppingen nu.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Jeg elsker simpelthen at shoppe efter\n"
	.string "dekorationer og møbler.\p"
	.string "Jeg elsker også at opdrætte POKéMON\n"
	.string "lige så meget.$"

SecretBase_Text_Trainer3Intro:
	.string "Nogle mennesker laver deres HEMMELIGE\n"
	.string "BASER på svært tilgængelige steder.\l"
	.string "Vil de bare ligge lavt?\p"
	.string "Men siden du fandt mig, hvad med vi\n"
	.string "får en kamp?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Jeg giver ikke op let!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Åh… Er du måske træt af at lede\n"
	.string "efter dette sted?$"

SecretBase_Text_Trainer3Defeated::
	.string "Jeg tabte…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Hvor er din HEMMELIGE BASE?\n"
	.string "Jeg skal besøge dig der.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Nogle mennesker laver deres HEMMELIGE\n"
	.string "BASER på svært tilgængelige steder.\l"
	.string "Vil de bare ligge lavt?$"

SecretBase_Text_Trainer8Intro:
	.string "Folk har fortalt mig, at du kan få\n"
	.string "dekorationer på flere måder.\p"
	.string "Vi skulle have et løb for at se,\n"
	.string "hvem der kan få flottere dekorationer\n"
	.string "og møbler!\p"
	.string "I mellemtiden, vil du så kæmpe?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Dette er min HEMMELIGE BASE.\n"
	.string "Jeg kan ikke tabe!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Jeg vil kæmpe med dig når som helst.$"

SecretBase_Text_Trainer8Defeated::
	.string "Huh?\n"
	.string "Tabte jeg lige?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Jeg taber ikke ved at samle dekorationer.\n"
	.string "Kom og besøg igen!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Folk har fortalt mig, at du kan få\n"
	.string "dekorationer på flere måder.\p"
	.string "Vi skulle have et løb for at se,\n"
	.string "hvem der kan få flottere dekorationer\n"
	.string "og møbler!$"

SecretBase_Text_Trainer4Intro:
	.string "Jeg fandt et sted, jeg kunne lide, og\n"
	.string "jeg pyntede det op med mine yndlingsdekorationer.\p"
	.string "Jeg opdrætter min yndlingsPOKéMON og bliver\n"
	.string "stærkere med den.\p"
	.string "Det er hvad jeg gør.\n"
	.string "Vil du kæmpe med mig?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Vis mig hvad du er lavet af!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Jeg antager, at der er tidspunkter,\n"
	.string "hvor du ikke er interesseret.$"

SecretBase_Text_Trainer4Defeated::
	.string "Jeg ved præcis hvad du er lavet af nu.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Vi kan begge blive stærkere.\n"
	.string "Lad os fortsætte!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Jeg fandt et sted, jeg kunne lide, og\n"
	.string "jeg pyntede det op med mine yndlingsdekorationer.\p"
	.string "Jeg opdrætter min yndlingsPOKéMON og bliver\n"
	.string "stærkere med den.\p"
	.string "Hver dag er en god dag.$"

SecretBase_Text_Trainer9Intro:
	.string "Du kan lære meget om smag og sans hos\n"
	.string "mennesker ud fra de slags dekorationer,\n"
	.string "de har, og hvordan de viser dem frem.\p"
	.string "Hvad synes du om min smag?\n"
	.string "Er du målløs?\p"
	.string "Vil du se min stil i kamp?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Der er ingen tilbageholdenhed!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Jeg vil med glæde demonstrere min stil\n"
	.string "når som helst.$"

SecretBase_Text_Trainer9Defeated::
	.string "Du er suverænt talentfuld!\n"
	.string "Din styrke synes at være uendelig…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Hvad synes du om min stil?\n"
	.string "Jeg vil blive ved med at polere den!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Du kan lære meget om smag og sans hos\n"
	.string "mennesker ud fra de slags dekorationer,\n"
	.string "de har, og hvordan de viser dem frem.\p"
	.string "Hvad synes du om min smag?\n"
	.string "Er du målløs?$"
