ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Har du planer om at gå dybt ind\n"
	.string "derinde?\p"
	.string "Hvad med at bringe mig noget\n"
	.string "SHOAL SALT og SHOAL SHELLS med?\p"
	.string "Jeg kan lave noget godt til dig,\n"
	.string "hvis du bringer ingredienserne.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Hvis du bringer mig fire af både\n"
	.string "SHOAL SALT og SHOAL SHELLS,\l"
	.string "kan jeg lave en SHELL BELL til dig…\p"
	.string "Du kan få de ingredienser\n"
	.string "hver dag.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Åh, hey! SHOAL SALT og SHOAL SHELLS!\n"
	.string "Og nok af dem også!\p"
	.string "Vil du have mig til at lave en\n"
	.string "SHELL BELL med dem?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Godt så! Jeg laver en SHELL BELL\n"
	.string "med det samme.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Færdig!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Lad en POKéMON holde den.\n"
	.string "Den vil elske den, det er sikkert.\p"
	.string "Hvorfor, SHELL BELL's klang…\n"
	.string "Den er simpelthen sublim!\p"
	.string "Du kan få ingredienserne til den hver dag,\n"
	.string "så jeg kan lave flere til dig.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Åh… Er det sådan…\n"
	.string "Jeg ville gerne have lavet en SHELL BELL…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Du har ikke plads i din TASKE,\n"
	.string "hvis jeg skulle lave den til dig.\p"
	.string "Du bør lave plads og komme tilbage\n"
	.string "efter en SHELL BELL.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Der var noget SHOAL SALT her.\n"
	.string "Men der er ikke noget her nu.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Der var en SHOAL SHELL her.\n"
	.string "Men der er ikke noget her nu.$"
