Route102_Text_CalvinIntro:
	.string "Hvis du har POKéMON med dig, så er\n"
	.string "du en officiel POKéMON TRÆNER!\l"
	.string "Du kan ikke sige nej til min udfordring!$"  

Route102_Text_CalvinDefeated:
	.string "Åh nej, jeg tabte…\n"
	.string "Jeg burde have trænet mine mere…$"

Route102_Text_CalvinPostBattle:
	.string "Hør her, du. Hvis du er stærk,\n"
	.string "skulle du have fortalt mig det før!$"

Route102_Text_CalvinRegister:
	.string "Jeg har knoklet hårdt med dette siden\n"
	.string "jeg så dig sidst.\p"
	.string "Jeg vil gerne kæmpe mod dig igen, så\n"
	.string "kan du registrere mig i din POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "Jeg vil gerne kæmpe mod dig igen,\n"
	.string "så kan du registrere mig i din POKéNAV?\p$"

Route102_Text_CalvinRematchIntro:
	.string "Siden jeg tabte til dig, har jeg desperat\n"
	.string "trænet mine POKéMON.\l"
	.string "Du kan ikke sige nej til min udfordring!$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, jeg tabte!\n"
	.string "Træner jeg helt forkert?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Hvis du vil blive stærkere,\n"
	.string "så vil jeg også blive stærkere.$"

Route102_Text_AllenIntro:
	.string "Er du lige blevet en TRÆNER?\n"
	.string "Vi er begge nybegyndere!$"

Route102_Text_AllenDefeated:
	.string "Jeg ringede til dig, fordi jeg\n"
	.string "tænkte, at jeg kunne slå dig…$"

Route102_Text_AllenPostBattle:
	.string "Jeg har ikke vundet en eneste gang endnu…\n"
	.string "Jeg håber, at jeg snart vinder…$"

Route102_Text_RickIntro:
	.string "Haha! Vores øjne mødtes!\n"
	.string "Jeg vil udfordre dig med min BUG POKéMON!$"

Route102_Text_RickDefeated:
	.string "Åh! Ned og ude!$"

Route102_Text_RickPostBattle:
	.string "Hvis du møder øjnene med en TRÆNER,\n"
	.string "skal du udfordre vedkommende! Det er en regel!$"

Route102_Text_TianaIntro:
	.string "Jeg vil blive ved med at vinde og\n"
	.string "stræbe efter at være den bedste \nTRÆNER.\p"
	.string "Hjælp mig med at udvikle min karriere!$"

Route102_Text_TianaDefeated:
	.string "Jeg endte med at fremme din karriere…$"

Route102_Text_TianaPostBattle:
	.string "For at blive ved med at vinde, ser jeg,\n"
	.string "at jeg er nødt til at fange flere POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Kan du mærke trækket fra vores\n"
	.string "sjæleberoligende duft?\p$"

Route103_Text_DaisyDefeated:
	.string "Du blev ikke narret af vores duft…$"

Route103_Text_DaisyPostBattle:
	.string "Aromaterapi er en form for mental\n"
	.string "helbredelse, der arbejder med dufte.$"

Route103_Text_AmyIntro:
	.string "AMY: Jeg er AMY.\n"
	.string "Og det her er min lillesøster LIV.\l"
	.string "Vi kæmper sammen!$"

Route103_Text_AmyDefeated:
	.string "AMY: Øh, vi tabte.$"

Route103_Text_AmyPostBattle:
	.string "AMY: Du skal tænke på alle slags\n"
	.string "ting, når du kæmper mod to\n"
	.string "TRÆNERE.\p$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Ups, du har kun en\n"
	.string "POKéMON med dig.\l"
	.string "Du kan ikke kæmpe mod os på den måde.$"

Route103_Text_LivIntro:
	.string "LIV: Vi kæmper sammen som ét\n"
	.string "hold.$"

Route103_Text_LivDefeated:
	.string "LIV: Øv, vi tabte, storesøster…$"

Route103_Text_LivPostBattle:
	.string "LIV: Vi arbejder perfekt sammen,\n"
	.string "min storesøster og jeg…\p"
	.string "Men vi tabte stadig…$"

Route103_Text_AmyLivRegister:
	.string "LIV: Virkelig, vi er meget bedre…\n"
	.string "Det er sandt! Vi viser dig næste gang!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: Hvis du vil kæmpe mod os,\n"
	.string "skal du have to POKéMON med!\l"
	.string "Det er ikke fair hvis du ikke har!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: Jeg er AMY.\n"
	.string "Og dette er min lillesøster LIV.\l"
	.string "Vi kæmper sammen!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Åh, buhuhu!\n"
	.string "Vi kunne ikke vinde igen…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Du skal tænke på alle\n"
	.string "slags ting, når du kæmper mod\n"
	.string "to TRÆNERE.\p$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Ups! Du har kun een\n"
	.string "POKéMON med dig.\l"
	.string "Du kan ikke kæmpe mod os på den måde.$"

Route103_Text_LivRematchIntro:
	.string "LIV: Vi kæmper sammen som ét\n"
	.string "hold.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Øv, vi tabte igen…\n"
	.string "Storesøster…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: Vi arbejder perfekt sammen,\n"
	.string "min store søster og jeg…\p"
	.string "Men hvorfor tabte vi igen?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: Hvis du vil kæmpe mod os, skal du\n"
	.string "have to POKéMON!\n"
	.string "Det er ikke fair, hvis du ikke har to!$"

Route103_Text_AndrewIntro:
	.string "Åh nej! Mit fiskegarn er helt snørklet!\n"
	.string "Jeg bliver frustreret og sur!\p"
	.string "Det er nok! Udfordr mig!$"

Route103_Text_AndrewDefeated:
	.string "Åh! Tabte den!\n"
	.string "Nu er jeg endnu mere irriteret!$"

Route103_Text_AndrewPostBattle:
	.string "Åh, jeg er stadig kogende rasende…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "Mine POKéMON er dejligt bedårende!\n"
	.string "Vær ikke genert--jeg vil vise dig!$"

Route103_Text_MiguelDefeated:
	.string "Åh, min gosh!\n"
	.string "Min kære POKéMON!$"

Route103_Text_MiguelPostBattle:
	.string "Min dejlige POKéMON ser skøn ud,\n"
	.string "selv når den er faldet om!$"

Route103_Text_MiguelRegister:
	.string "Jeg skal nok få dig til at kigge på\n"
	.string "mine skønne POKéMON igen!$"

Route103_Text_MiguelRematchIntro:
	.string "Hej, dig! Min dejligt bedårende\n"
	.string "POKéMON er blevet endnu mere kær!$"

Route103_Text_MiguelRematchDefeated:
	.string "Åh!\n"
	.string "Mine kære POKéMON!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Jo mere tid jeg tilbringer med det,\n"
	.string "jo mere bedårende bliver mit POKéMON.$"

Route103_Text_PeteIntro:
	.string "Den slags afstand…\n"
	.string "Du burde bare svømme det!$"

Route103_Text_PeteDefeated:
	.string "Åh, det er godt gået!$"

Route103_Text_PetePostBattle:
	.string "Åh, nu forstår jeg, hvor du kommer\n"
	.string "fra.\p"
	.string "Hvis jeg havde en POKéMON så pålidelig,\n"
	.string "ville jeg også ønske at SURFE på den!$" 

Route103_Text_IsabelleIntro:
	.string "Se hvor du går!\n"
	.string "Vi kommer til at krasje!$"

Route103_Text_IsabelleDefeated:
	.string "Støn…$"

Route103_Text_IsabellePostBattle:
	.string "Jeg er en dårlig svømmer, så jeg øvede mig…\n"
	.string "Undskyld for næsten at støde ind i dig.$"

Route103_Text_RhettIntro:
	.string "Wow!\n"
	.string "Hvordan kom du ind på så lidt plads?$"

Route103_Text_RhettDefeated:
	.string "Whoa!\n"
	.string "Den knægt kan feste!$"

Route103_Text_RhettPostBattle:
	.string "Kan du lide trange rum\n"
	.string "som dette?$"

Route103_Text_MarcosIntro:
	.string "Trak min guitars jamren dig ind?$"

Route103_Text_MarcosDefeated:
	.string "Min enmandsforestilling er ødelagt…$"

Route103_Text_MarcosPostBattle:
	.string "Jeg spillede guitar, hvor der var få\n"
	.string "mennesker omkring, men en masse fans\n"
	.string "var samlet.\p"
	.string "Heh, måske skulle jeg blive professionel.$"

Route104_Text_GinaIntro:
	.string "GINA: Okay, lad os kæmpe med vores\n"
	.string "POKéMON!\p$"

Route104_Text_GinaDefeat:
	.string "GINA: Tab at tabe oprører mig!$"

Route104_Text_GinaPostBattle:
	.string "GINA: Du er stærk!\n"
	.string "Vi skal træne meget mere!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Åh? Kun én POKéMON?\n"
	.string "Så skal vi ikke kæmpe med dig.\p"
	.string "Hvis der kun er én POKéMON, vil den\n"
	.string "føle sig ensom. Det er ikke rart.$"

Route104_Text_MiaIntro:
	.string "MIA: Vi er tvillinger, så vi kæmper\n"
	.string "POKéMON sammen.$"

Route104_Text_MiaDefeat:
	.string "MIA: Vi kæmpede sammen, men vi\n"
	.string "begge tabte…$"

Route104_Text_MiaPostBattle:
	.string "MIA: Vi vil træne vores POKéMON \n"
	.string "mere og være stærke som dig.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Vil du kæmpe med os?\p"
	.string "Det er et stort NEJ, hvis du ikke har\n"
	.string "to POKéMON med dig.\l"
	.string "Vi er for stærke for dig!$"

Route104_Text_IvanIntro:
	.string "Hvorfor holde det som en hemmelighed?\n"
	.string "Jeg er eksperten i VANDE POKéMON!\p"
	.string "Hva'?\n"
	.string "Kender du mig ikke?$"

Route104_Text_IvanDefeat:
	.string "Jeg troede faktisk, at jeg ikke var så\n"
	.string "dårlig, hvis jeg selv skal sige det, men\n"
	.string "jeg gætter ikke… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "Jeg kom for meget i fiske\n"
	.string "humøret. Jeg glemte at træne\n"
	.string "mine POKéMON…$"

Route104_Text_BillyIntro:
	.string "At efterlade fodspor i sandet\n"
	.string "er så sjovt!$"

Route104_Text_BillyDefeat:
	.string "Åh nej! Jeg har fået sand i mine løbesko!\n"
	.string "De er helt sandete!$"

Route104_Text_BillyPostBattle:
	.string "Jeg vil efterlade mine fodspor\n"
	.string "overalt i sandet,\n"
	.string "men de forsvinder hurtigt…$"

Route104_Text_HaleyIntro:
	.string "Skal jeg…\n"
	.string "Eller skal jeg ikke?\p"
	.string "Okay, helt sikkert, jeg vil kæmpe!$"

Route104_Text_HaleyDefeat:
	.string "Jeg burde ikke have kæmpet…$"

Route104_Text_HaleyPostBattle:
	.string "Hvis du står over for en beslutning\n"
	.string "og du lader en anden vælge for dig,\n"
	.string "vil du fortryde det, uanset hvordan\n"
	.string "tingene går.$"

Route104_Text_HaleyRegister1:
	.string "Du er stærk, men skal jeg registrere\n"
	.string "dig i min POKéNAV?\l"
	.string "Måske skal jeg ikke…\p"
	.string "Godt, selvfølgelig vil jeg registrere dig!$"

Route104_Text_HaleyRegister2:
	.string "Du er stærk, men skal jeg registrere\n"
	.string "dig i min POKéNAViser?\l"
	.string "Måske skulle jeg ikke…\p"
	.string "Okay, selvfølgelig, jeg vil registrere dig!$"

Route104_Text_HaleyRematchIntro:
	.string "Kom så, kæmp mod mig!$"

Route104_Text_HaleyRematchDefeat:
	.string "Åhh…\n"
	.string "Jeg troede, jeg kunne vinde…$"

Route104_Text_HaleyPostRematch:
	.string "Jeg besluttede mig for at kæmpe, så\n"
	.string "jeg kan acceptere dette nederlag med nåde.\p"
	.string "Jeg er stadig ked af at tabe!$"  

Route104_Text_WinstonIntro:
	.string "Åh, selvfølgelig, jeg accepterer din udfordring.\n"
	.string "Jeg har masser af penge.$"

Route104_Text_WinstonDefeat:
	.string "Hvorfor kunne jeg ikke vinde?$"

Route104_Text_WinstonPostBattle:
	.string "Der er visse ting, penge ikke kan købe.\n"
	.string "Det er POKéMON…\p$"

Route104_Text_WinstonRegister1:
	.string "Hm?\n"
	.string "Nåh, du har fået en POKéNAV.\p"
	.string "Jeg vil med glæde registrere dig.\n"
	.string "Jeg har trods alt masser af penge.$"

Route104_Text_WinstonRegister2:
	.string "Hm?\n"
	.string "Åh, du har fået en POKéNAV.\p"
	.string "Jeg vil med glæde registrere dig.\n"
	.string "Jeg har trods alt masser af penge.$"

Route104_Text_WinstonRematchIntro:
	.string "Efter jeg tabte til dig, lærte jeg en\n"
	.string "masse ting om POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "Jeg tabte igen?\n"
	.string "Hvorfor kunne jeg ikke vinde?$"

Route104_Text_WinstonPostRematch:
	.string "Jeg er fantastisk rig, men jeg kan ikke\n"
	.string "synes at vinde i POKéMON…\p"
	.string "Det er så dybt, POKéMONs verden…$"

Route104_Text_CindyIntro:
	.string "Vi må have været skæbnebestemt til at mødes.\n"
	.string "Må jeg bede dig om en kamp?$"

Route104_Text_CindyDefeat:
	.string "Åh nej!$"

Route104_Text_CindyPostBattle:
	.string "“Hej” er begyndelsen på “farvel.”\n"
	.string "Jeg håber, vi mødes igen.$"

Route104_Text_CindyRegister1:
	.string "Hej, vi mødes igen.\p"
	.string "Det virker som om, vi bliver trukket\n"
	.string "sammen. Lad os registrere hinanden i\n"
	.string "vores POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "Vi burde mindes, hvordan vi synes\n"
	.string "at blive draget mod hinanden.\p"
	.string "Lad os registrere hinanden i vores\n"
	.string "POKéMONAVis.$"

Route104_Text_CindyRematchIntro:
	.string "Hej, vi mødes igen.\n"
	.string "Må jeg bede om en kamp?$"

Route104_Text_CindyRematchDefeat:
	.string "Åh, nej…\n"
	.string "Jeg gjorde det bedste, jeg kunne…$"

Route104_Text_CindyPostRematch:
	.string "“Hej” er starten på “farvel.”\n"
	.string "Jeg håber vi mødes igen.$"

Route104_Text_DarianIntro:
	.string "Jeg har fanget en sej udseende POKéMON!\p"
	.string "Den har en magisk kvalitet ved sig!\n"
	.string "Den ser helt klart sej ud, ja det gør den!$"

Route104_Text_DarianDefeat:
	.string "Hvad i…$"

Route104_Text_DarianPostBattle:
	.string "Hey, MAGIKARP, du lever virkelig\n"
	.string "ikke op til dit navn, gør du?$"

Route105_Text_FosterIntro:
    .string "Der skulle være en mystisk\n"
    .string "sten omkring her.\l"
    .string "Ved du noget om det?$"

Route105_Text_FosterDefeated:
	.string "Jeg tænkte for meget på den\n"
	.string "sten, mens mine POKéMON forblev svage…$"

Route105_Text_FosterPostBattle:
	.string "Jeg kan tilbringe timer og timer med"
	.string "at stirre på en flot sten uden at blive$"


Route105_Text_LuisIntro:
	.string "Puha! Jeg var bekymret for, at et barn\n"
	.string "drukner, når jeg så dig.\p"
	.string "Du ser ud til at have det fint, så hvad\n"
	.string "siger du til en kamp?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "Hvis du drukner, er signalet at vinke\n"
	.string "med en arm mod stranden.$"

Route105_Text_DominikIntro:
	.string "At svømme i det dybe blå…\n"
	.string "Det føles fantastisk!$"

Route105_Text_DominikDefeated:
	.string "Jeg tabte…\n"
	.string "Nu føler jeg mig blå…$"

Route105_Text_DominikPostBattle:
	.string "Hvorfor er havet blåt?\p"
	.string "Det lærte jeg om på MUSEET i\n"
	.string "SLATEPORT, men jeg har glemt.$"

Route105_Text_BeverlyIntro:
	.string "Min krop føles lettere i vandet.\n" 
	.string "Det er, som om jeg er blevet slankere!$"

Route105_Text_BeverlyDefeated:
	.string "Jeg svæver…$"

Route105_Text_PostBattle:
	.string "Din kropsvægt reduceres til kun\n"
	.string "en tiendedel i vandet.\p"
	.string "Det ville gøre mig…\n"
	.string "Ups! Jeg fortæller ikke min vægt!$"

Route105_Text_ImaniIntro:
    .string "Den blå, blå himmel…\n"
	.string "Den uendelige hav…\l"
	.string "Det er så fredeligt…$"

Route105_Text_ImaniDefeated:
	.string "Jeg tabte mens jeg slappede af!$"


Route105_Text_ImaniPostBattle:
	.string "Jeg vil gerne have at vide, at jeg er\n"
	.string "afslappende at være sammen med. Griner.$"

Route105_Text_AndresIntro:
	.string "Jeg er overbevist om, at havet\n"
	.string "gemmer hemmeligheder fra os.$"

Route105_Text_AndresDefeated:
	.string "Ja…\n"
	.string "Jeg er ikke god til at kæmpe…$"

Route105_Text_AndresPostBattle:
	.string "Jeg er sikker på, at der er mange hemmeligheder\n"
	.string "at opdage i verdens have.\p"
	.string "Jeg har tænkt mig at finde dem alle!$"

Route105_Text_AndresRegister:
	.string "Hov? Jeg er så svag, men du er\n"
	.string "villig til at registrere mig på din POKéNAV?$"

Route105_Text_AndresRematchIntro:
	.string "Jeg har fortalt dig, at jeg er svag…\n"
	.string "Er du sikker på, at du vil gøre dette?$"

Route105_Text_AndresRematchDefeated:
	.string "Ja…\n"
	.string "Jeg troede ikke, jeg kunne vinde.$"

Route105_Text_AndresRematchPostBattle:
	.string "Jeg er måske svag til kamp, men min\n"
	.string "trang til at udforske kan ikke slås.\p"
	.string "Jeg vil sejle alle have rundt om\n"
	.string "verdenen!$"

Route105_Text_JosueIntro:
    .string "Jeg er udmattet af at svømme.\n"
    .string "Jeg er bare ikke vant til det.\p"
    .string "Jeg har brug for en kamp for at få lidt variation!$"

Route105_Text_JosueDefeated:
	.string "Jeg tabte, fordi jeg kæmpede til søs.$"

Route105_Text_JosuePostBattle:
	.string "Yeah, for me, the sky is a much better\n"
	.string "match than the sea.$"

Route106_Text_ElliotIntro:
	.string "Hvad foretrækker du, fiskeri i havet\n"
	.string "eller en bæk? \p$"

Route106_Text_ElliotDefeated:
	.string "Som med dybhavsfiskeri, tabte jeg\n" 
	.string "spektakulært!$"

Route106_Text_ElliotPostBattle:
	.string "At fiske er det bedste, uanset om det\n"
	.string "er i havet eller en å.\l"
	.string "Er du enig med mig, ikke$?"

Route106_Text_ElliotRegister:
	.string "At fiske er skønt, men at kæmpe er også sjovt.\n"
	.string "Hvis det er okay med dig, kan vi så mødes igen?$"

Route106_Text_ElliotRematchIntro:
	.string "Jeg har fanget en masse POKéMON ved at fiske.\n"
	.string "Jeg vil vise dig en imponerende kamp!$"

Route106_Text_ElliotRematchDefeated:
	.string "Jeg tabte igen spektakulært!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Uanset om man vinder eller taber, POKéMON er de bedste!\n"
	.string "Du er enig med mig, ikke sandt?$"

Route106_Text_NedIntro:
	.string "Hvad gør folk, hvis de skal på\p"
	.string "WC?\n"
	.string "Hvad hvis min STANG fanger en stor fisk,\n"
	.string "mens jeg er på WC? Jeg kan bare ikke gå…$"

Route106_Text_NedDefeated:
	.string "Jeg tabte, fordi jeg prøver at\n"
	.string "holde mig fra badeværelset…$"

Route106_Text_NedPostBattle:
	.string "Åh nej! Jeg har på fornemmelsen,\n"
	.string "at jeg fanger en stor fisk!\p$"

Route106_Text_DouglasIntro:
	.string "Hahahah! Jeg er en dårlig løber, men\n"
	.string "i vandet kan du ikke fange mig!$"

Route106_Text_DouglasDefeated:
	.string "Jeg giver op!$"

Route106_Text_DouglasPostBattle:
	.string "Jeg ville ikke tabe i en\n"
	.string "svømmekonkurrence…$"

Route106_Text_KylaIntro:
	.string "Havet er min baghave. Jeg tager det\n"
	.string "ikke roligt, fordi du er et barn!$"

Route106_Text_KylaDefeated:
	.string "Har du taget det lidt let med mig\n"
	.string "tilfældigvis?\p$"

Route106_Text_KylaPostBattle:
    .string "Driver med bølgerne…\n"
    .string "Det er skønt! Vil du prøve det?$"

Route107_Text_DarrinIntro:
	.string "Gaaab…\p"
	.string "Jeg må være faldet i søvn, mens\n"
	.string "jeg drev rundt på bølgerne.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, jeg tabte…\n"
	.string "Jeg tror, jeg vil tage en lur…$"

Route107_Text_DarrinPostBattle:
	.string "At flyde og blive vugget af\n"
	.string "bølgerne - det er som at sove\n"
	.string "i en blød, behagelig seng.$"

Route107_Text_TonyIntro:
	.string "Havet er som min baghave.\n"
	.string "Lad os kæmpe!$"

Route107_Text_TonyDefeated:
    .string "Jeg tabte på min hjemmebane…\n"
    .string "Jeg er i chok!$"

Route107_Text_TonyPostBattle:
	.string "Jeg svømmer i havene med et\n"
	.string "hjerte fuld af drømme…\p"
	.string "Det er en sang!\n"
	.string "Nå, jeg svømmer lidt mere.$"

Route107_Text_TonyRegister:
	.string "Du har chokeret mig til benet!\n"
	.string "Nå, så du ikke glemmer mig…$"

Route107_Text_TonyRematchIntro:
    .string "Svømmer i det store, vide hav,\n"
    .string "min POKéMON er blevet stærkere!$"

Route107_Text_TonyRematchDefeated:
	.string "Sikke en overraskelse!\p"
	.string "Mine POKéMON er blevet stærkere,\n"
	.string "men jeg forblev svag som en TRÆNER!$"

Route107_Text_TonyRematchPostBattle:
	.string "Det, du lærer i kamp, gør dig\n"
	.string "til en stærkere TRÆNER.\l"
	.string "Bølgerne har lært mig det.$"

Route107_Text_DeniseIntro:
	.string "Kender du en lille by kaldet\n"
	.string "ALDERSUND?\p$"

Route107_Text_DeniseDefeated:
	.string "Jeg hader dette!$"

Route107_Text_DenisePostBattle:
    .string "En mærkelig sætning bliver virkelig\n"
    .string "populær i DEWFORD HALL.$"

Route107_Text_BethIntro:
	.string "Vil du kæmpe mod mig?\n"
	.string "Selvfølgelig, jeg vil med dig!$"

Route107_Text_BethDefeated:
	.string "Jeg var ikke god nok til dig.$"

Route107_Text_BethPostBattle:
	.string "Jeg tror, du bliver ved med at\n"
	.string "blive bedre. Jeg vil også give det en chance!$"

Route107_Text_LisaIntro:
	.string "LISA: Vi udfordrer dig som søster\n"
	.string "og bror!$"

Route107_Text_LisaDefeated:
	.string "LISA: Fedt!\n"
	.string "Du er i en anden klasse af seje.$"

Route107_Text_LisaPostBattle:
	.string "LISA: Har du nogen venner, som\n"
	.string "ville tage til stranden med dig?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Hvis du vil kæmpe med os,\n"
	.string "skal du have flere POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: Vi kæmper altid med POKéMON,\n"
	.string "min søster og jeg.\p"
	.string "Jeg taber altid, men vi kan slå\n"
	.string "jer 2 mod 2!$"

Route107_Text_RayDefeated:
	.string "RAY: Ej, du er på et højere niveau\nend os!\n\p$"

Route107_Text_RayPostBattle:
	.string "RAY: Min søster gav mig min POKéMON.\n"
	.string "Jeg opfostrerede den, og nu er den min\l"
	.string "vigtige partner!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Hvis du vil kæmpe mod os,\n"
	.string "så tag nogle flere POKéMON med dig!$"

Route107_Text_CamronIntro:
	.string "Jeg er midt i en triatlon,\n"
	.string "men jeg er slet ikke træt!$"

Route107_Text_CamronDefeated:
	.string "Det udmattede mig…$"

Route107_Text_CamronPostBattle:
	.string "Jeg har stadig svømning og\n"
	.string "løb tilbage at lave efter dette.\p"
	.string "Mon jeg kommer til at være okay?$"

Route108_Text_JeromeIntro:
	.string "Min drøm er at svømme i verdens syv\n"
	.string "have!$"

Route108_Text_JeromeDefeated:
	.string "Jeg vil ikke kunne svømme de syv have\n"
	.string "på denne måde…$"

Route108_Text_JeromePostBattle:
	.string "At lege med marine POKéMON er en af\n"
	.string "glæderne ved at svømme!$"

Route108_Text_MatthewIntro:
	.string "Hej med dig! Skal du også ud til\n"
	.string "det FORLADTE SKIB?$"

Route108_Text_MatthewDefeated:
	.string "Jeg synker!\n"
	.string "Blup… Blup…$"

Route108_Text_MatthewPostBattle:
	.string "Nogle mennesker går endda ind i det\n"
	.string "FORLADTE SKIB.$"

Route108_Text_TaraIntro:
	.string "Min løgnagtige kæreste sagde, at jeg\n"
	.string "ser fantastisk ud i en bikini…$"

Route108_Text_TaraDefeated:
	.string "Åh, buhuhu!$"

Route108_Text_TaraPostBattle:
	.string "Selvom det er en løgn, elsker jeg at få at vide\n"
	.string "Jeg ser fantastisk ud…\l"
	.string "Vi piger er så komplekse…$" 

Route108_Text_MissyIntro:
	.string "Jeg elsker havet!\n"
	.string "Jeg glemmer alle mine bekymringer, når jeg svømmer!$"

Route108_Text_MissyDefeated:
	.string "Når jeg taber en kamp, bliver jeg helt\n"
	.string "stresset!$"

Route108_Text_MissyPostBattle:
	.string "Arbejd din stress af ved at svømme!\n"
	.string "Det er så sundt!$"

Route108_Text_CoryIntro:
	.string "Jeg elsker VAND-type POKéMON.\n"
	.string "Jeg elsker også andre POKéMON!$"

Route108_Text_CoryDefeated:
	.string "Ihh! Jeg tabte!\n"
	.string "Ihh! Ihh!$"

Route108_Text_CoryPostBattle:
	.string "At råbe er godt for mig!\n"
	.string "Det løfter mig!$"

Route108_Text_CoryRegister:
	.string "Jeg elsker seje TRÆNERE, også!\n"
	.string "Registrer mig i din POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Vind eller tab, jeg elsker at kæmpe til søs!$"

Route108_Text_CoryRematchDefeated:
	.string "Ååh nej! Jeg tabte igen!\n"
	.string "Ååh! Ååh!$"

Route108_Text_CoryRematchPostBattle:
	.string "Hvis du står over for en udford-\n"
	.string "ring, så prøv at råbe til havet!$"

Route108_Text_CarolinaIntro:
	.string "Jeg er virkelig stolt af mine POKéMON.\n"
	.string "Vi vil vise dig en lynhurtig kamp!$"

Route108_Text_CarolinaDefeated:
	.string "Det var slet ikke sødt.$"

Route108_Text_CarolinaPostBattle:
	.string "Siden jeg er på havet som dette, ville jeg\n"
	.string "ikke have noget imod at iføre mig en lyserød, \n"
    .string "flæsekantet bade dragt…$"

Route109_Text_DavidIntro:
	.string "Hiyah! Se på mine veltrænede mavemuskler!\n"
	.string "Det her er hvad man kalder “cut”!$"

Route109_Text_DavidDefeated:
	.string "Åh nej!\n"
	.string "Tabt!$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "Mine udhuggede mavemuskler har intet\n"
	.string "at gøre med POKéMON kampe!$"

Route109_Text_AliceIntro:
	.string "Er du ordentligt beskyttet mod\n"
	.string "solen?\p$"

Route109_Text_AliceDefeated:
	.string "Auts, av, av!$"

Route109_Text_AlicePostBattle:
	.string "Kinder er de mest tilbøjelige til at brænde!$"

Route109_Text_HueyIntro:
	.string "Jeg har kastet anker i havne overalt\n"
	.string "i verden, men SLATEPORT er den bedste.$"

Route109_Text_HueyDefeated:
	.string "Du er den bedste!$"

Route109_Text_HueyPostBattle:
	.string "I den bedste havn var den bedste\p" 
	.string "TRÆNER…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"
	.string "Kamp? Med mig?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh…\n"
	.string "Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "Jeg er normalt stærkere end dette!\n"
	.string "Jeg har bare søsyge som en hund!\p"
	.string "Jeg er en SØMAND, men…$"

Route109_Text_RickyIntro:
	.string "Jeg er tørstig… Jeg kunne godt bruge en SODAVAND\n"
	.string "på STRANDHUSET…$"

Route109_Text_RickyDefeated:
	.string "Øv…$"


Route109_Text_RickyPostBattle:
	.string "Jeg er ved at blive sulten… Min\n"
	.string "indsprøjtningsflåde ligner en kæmpe\n"
	.string "donut…$"


Route109_Text_RickyRegister:
	.string "Skal vi have endnu et spil sammen,\n"
	.string "når jeg ikke er så tørstig?$"

Route109_Text_RickyRematchIntro:
	.string "Jeg er sulten, men jeg har masser af\n"
	.string "energi til en kamp!$"

Route109_Text_RickyRematchDefeated:
	.string "Jeg tabte…\n"
	.string "Det er fordi jeg er sulten…$"

Route109_Text_RickyRematchPostBattle:
	.string "Når du spiser på stranden, virker\n"
	.string "alt til at smage lidt bedre.$"

Route109_Text_LolaIntro:
	.string "Ser et strandparasol ikke ud som\n"
	.string "en kæmpe blomst?\p$"

Route109_Text_LolaDefeated:
	.string "Mor!$"

Route109_Text_LolaPostBattle:
	.string "Hvis du ser på stranden fra himlen,\n"
	.string "ser det ud som en stor blomsterhave!$" 

Route109_Text_LolaRegister:
	.string "Mig?\n"
	.string "Jeg er her hver dag!$"

Route109_Text_LolaRematchIntro:
	.string "Jeg taber ikke til dig igen!\n"
	.string "Derfor har jeg min badering!$"

Route109_Text_LolaRematchDefeated:
	.string "Mor!$"

Route109_Text_LolaRematchPostBattle:
	.string "Hvis jeg har en badering, så stiger mig\n"
	.string "og min POKéMONs sødme helt op!$"

Route109_Text_AustinaIntro:
	.string "Jeg kan ikke svømme uden min badering,\n"
	.string "men jeg vil ikke tabe i POKéMON!$"  

Route109_Text_AustinaDefeated:
	.string "Tabte jeg, fordi jeg har en indre\n"
	.string "rør?$"

Route109_Text_AustinaPostBattle:
	.string "Min badering er et modeitem.\n"
	.string "Jeg kan ikke ses uden den.$"

Route109_Text_GwenIntro:
	.string "Hej, seje TRÆNER.\n"
	.string "Vil du kæmpe med mig?$"

Route109_Text_GwenDefeated:
	.string "Åh, du er stærk.$"

Route109_Text_GwenPostBattle:
	.string "Hvordan blev du så stærk?$"

Route109_Text_CarterIntro:
	.string "Wahahah! Denne fyr er ved at fange\n"
	.string "en kæmpe!$"

Route109_Text_CarterDefeated:
	.string "Denne fyr mistede lige et…$"

Route109_Text_CarterPostBattle:
	.string "Denne fyr tror, at du er en stor en.\n"
	.string "Nej, du er en stor-en-til-at-være!$"

Route109_Text_PaulIntro:
	.string "PAUL: Nå, det her er en stemningsødelægger.\p"
	.string "Jeg ville ønske, at du ikke forstyrrede\n"
	.string "vores dyrebare tid sammen.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Nå, jeg giver op.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Nå, fortæl ikke nogen, at\n"
	.string "vi er her.\n"
	.string "Dette er bare vores private tosomhed!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Vi er fuldstændig og dybt forelskede.\n"
	.string "Det er derfor, vi lader vores POKéMON kæmpe\n"
	.string "sammen.$"

Route109_Text_MelIntro:
	.string "MEL: Vi er bare så forelskede.\n"
	.string "Vores romantik opvarmer hele HOENN!$"

Route109_Text_MelDefeated:
    .string "MEL: Vi tabte, og det er min skyld!\n"
    .string "PAUL vil hade mig!$"

Route109_Text_MelPostBattle:
    .string "MEL: Øh, PAUL, er du sur på mig?\n"
    .string "Vær venlig ikke at være sur.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: Vi er, ligesom, dybt og sandt forelskede.\n"
	.string "Derfor kæmper vi med vores POKéMON\l"
	.string "sammen.$"

Route109_Text_ChandlerIntro:
	.string "Tadaah! Se?\n"
	.string "Min badering er rund!$"

Route109_Text_ChandlerDefeated:
	.string "Åh nej!\n"
	.string "Øv bøv!$"

Route109_Text_ChandlerPostBattle:
	.string "Efter at jeg viste dig mit runde\n"
	.string "indre rør, også…$"

Route109_Text_HaileyIntro:
	.string "Jeg kan ikke svømme, så jeg"
	.string "lader som om jeg svømmer.$"

Route109_Text_HaileyDefeated:
	.string "Jeg vidste det!\n"
	.string "Jeg troede ikke, vi kunne vinde.$"

Route109_Text_HaileyPostBattle:
	.string "Når jeg lærer at svømme, tror jeg,\n"
	.string "mine POKéMON vil blive stærkere.$"

Route109_Text_ElijahIntro:
	.string "For a guy as macho as me, this\n"
	.string "of POKéMON is the perfect match!$"

Route109_Text_ElijahDefeated:
	.string "Jeg er sej selv i nederlag, hey?$"

Route109_Text_ElijahPostBattle:
	.string "For a guy as macho as me, a port\n"
	.string "is the perfect setting!\p"
	.string "I guess I'll head for SLATEPORT.$"

Route110_Text_JacobIntro:
	.string "Whoa! Se dig for!$\n"
	.string "Jeg gætter på, at du ikke er vant til at CYKLE race.$"

Route110_Text_JacobDefeated:
	.string "Whoa!\n"
	.string "Mine bremser virkede ikke!$"

Route110_Text_JacobPostBattle:
	.string "Flade dæk og bremseproblemer kan\n"
	.string "forårsage alvorlige skader!\l"
	.string "Tjek din CYKEL for problemer!$"

Route110_Text_AnthonyIntro:
	.string "Hej, du!\n"
	.string "Kan du følge med i mit tempo?\p$"

Route110_Text_AnthonyDefeated:
	.string "Crash and burn!$"

Route110_Text_AnthonyPostBattle:
	.string "Hastighed alene vil ikke lade mig vinde i POKéMON.\n"
	.string "Jeg er nødt til at genoverveje dette…$"

Route110_Text_BenjaminIntro:
	.string "Frygt ikke, hvis DIN CYKEL kører hurtigt!$"

Route110_Text_BenjaminDefeated:
	.string "Jeg skal ikke få panik under\n"
	.string "POKéMON\n-kampe…$"

Route110_Text_BenjaminPostBattle:
	.string "Der er ingen grund til panik eller stress.\n"
	.string "Tag det roligt. Der er masser af tid.$"

Route110_Text_BenjaminRegister:
	.string "Jeg vil blive ved med at tøffe afsted uden at stresse.\n"
	.string "Hvis du er klar til det, så råb op.$"

Route110_Text_BenjaminRematchIntro:
	.string "Er du ikke lidt for hurtig?\n"
	.string "Tag det roligt og lad os kæmpe.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Jeg panikkede ikke, men jeg tabte stadig…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Der er ingen grund til panik eller stress.\n"
	.string "Tag det roligt. Der er masser af tid.$"

Route110_Text_AbigailIntro:
	.string "Triatlonet er hårdt i den ekstreme.\p"
	.string "Du skal gennemføre de tre begivenheder\n"
	.string "med svømning, cykling og løb.$"

Route110_Text_AbigailDefeated:
	.string "POKéMON battles are hard, too!$"

Route110_Text_AbigailPostBattle:
	.string "Jeg er udmattet, så jeg har brug for en pause.\n"
	.string "Det er vigtigt at få ordentlig hvile.$"

Route110_Text_AbigailRegister:
	.string "Du er sød, ved du det?\n"
	.string "Skal vi have en revanche på CYKLING VEJ?$"

Route110_Text_AbigailRematchIntro:
	.string "Er det ikke sjovt at kæmpe mens\n"
	.string "du cykler?\p$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow…\n"
	.string "Hvordan kunne du være så stærk?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Var du ude efter en rekord?\p"
	.string "Beklager, hvis jeg forsinkede dig!$"

Route110_Text_JasmineIntro:
	.string "Jeg har kørt uden at stoppe.\n"
	.string "Mine lår føles som sten!$"

Route110_Text_JasmineDefeated:
	.string "Jeg er bekymret for muskelkramper…$"

Route110_Text_JasminePostBattle:
	.string "Åh, har du nogle GYM BADGES?\n"
	.string "Ingen undskyldning for din styrke!$"

Route110_Text_EdwardIntro:
	.string "Jeg har forudset dine intentioner!\n"
	.string "Jeg kan simpelthen ikke tabe!$"

Route110_Text_EdwardDefeated:
	.string "Jeg mislykkedes i at forudsige min egen undergang!$"

Route110_Text_EdwardPostBattle:
    .string "Jeg ser din fremtid…\p"
    .string "Hmm…\n"
    .string "Jeg ser et skinnende lys…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"
	.string "Jeg vil forbløffe dig med mine undere!$"

Route110_Text_JaclynDefeated:
	.string "Jeg tabte vidunderligt!$"

Route110_Text_JaclynPostBattle:
	.string "Du formåede kun at vinde, fordi det \ner et mirakel! Ja, et mirakel!\l"
	.string "Tro ikke, at du kan vinde hver gang!$"

Route110_Text_EdwinIntro:
	.string "Må jeg se din POKéMON?\n"
	.string "Bare et kig, tak.$"

Route110_Text_EdwinDefeated:
	.string "Jeg ville gerne fuldføre\n"
	.string "min samling…$"

Route110_Text_EdwinPostBattle:
	.string "Når jeg ser en POKéMON, som jeg ikke kender,\n"
	.string "blusser min passion som samler op!$"

Route110_Text_EdwinRegister:
	.string "Jeg kan godt lide at samle MATCH CALL\n"
	.string "registreringer også…$"

Route110_Text_EdwinRematchIntro:
	.string "Hej, har du fanget nogle nye POKéMON?\p"
	.string "Må jeg se dine POKéMON?\n"
	.string "Bare et hurtigt kig, tak.$"

Route110_Text_EdwinRematchDefeated:
	.string "Dine POKéMON…\n"
	.string "Jeg misunder dig.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Åh, jeg længes efter at gøre alle sjældne POKéMON\n"
	.string "til mine!$"

Route110_Text_DaleIntro:
	.string "Hej!\n"
	.string "Du må ikke snige dig op bag mig på den måde!$"

Route110_Text_DaleDefeated:
	.string "Jeg tabte!\n"
	.string "Skidt!$"

Route110_Text_DalePostBattle:
	.string "At fiske handler om koncentration.\n"
	.string "Du skal fokusere på flåden.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha! Jeg ville gå hvor som helst for at vise\n"
	.string "mine dejlige POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Åh nej, dette går ikke.$"

Route110_Text_IsabelPostBattle:
	.string "I stedet for at kæmpe, burde jeg måske\n"
	.string "vise mine POKéMON frem i FANKLUBBEN.$"

Route110_Text_IsabelRegister:
	.string "Det var slet ikke tæt på, hvad jeg\n"
	.string "kan gøre for at vise mine POKéMON.\p"
	.string "Du vil være min fangete publikum\n"
	.string "så ofte som muligt!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! Jeg vil gerne vise mine\n"
	.string "POKéMON frem så tit du vil!$"

Route110_Text_IsabelRematchDefeated:
	.string "Åh, kære, dette går ikke. $"

Route110_Text_IsabelRematchPostBattle:
	.string "Jeg tror ikke, at jeg nogensinde\n"
	.string "ville kunne lade være med at vise\n"
	.string "mine POKéMON frem.\p"
	.string "Men jeg kan også godt lide\n"
	.string "at kæmpe!$"

Route110_Text_TimmyIntro:
	.string "Jeg fandt nogle seje POKéMON i græsset\n"
	.string "her omkring!$"

Route110_Text_TimmyDefeated:
    .string "At være sej er ikke nok til at vinde…$"

Route110_Text_TimmyPostBattle:
	.string "Det er svært at kæmpe med POKéMON,\n"
	.string "du lige har fanget.$"

Route110_Text_AlyssaIntro:
	.string "Jeg faldt af CYKLING ROAD…\p"
	.string "Jeg vil komme mig over min\n"
	.string "pinlighed ved at kæmpe med dig!$"

Route110_Text_AlyssaDefeated:
	.string "Ups!\n"
	.string "Jeg endte med at tabe!$"

Route110_Text_AlyssaPostBattle:
	.string "Falder… Taber…\n"
	.string "Det her er så ydmygende for mig!$"

Route110_Text_JosephIntro:
	.string "Okay! Fuldt fart fremad! Hvis du ikke\n"
	.string "kan være med, bliver du efterladt!$"

Route110_Text_JosephDefeated:
	.string "Du fik godt fat i rytmen…$"

Route110_Text_JosephPostBattle:
	.string "Det her kommer ikke til at slå mig ud!\n"
	.string "At tabe har gjort mig til en bedre mand!$"

Route110_Text_KalebIntro:
	.string "Når søde POKéMON hjælper hinanden…\n"
	.string "Kan du ikke se en mere nuttet syn!$"

Route110_Text_KalebDefeated:
	.string "Har du ingen medfølelse eller medlidenhed?$"

Route110_Text_KalebPostBattle:
	.string "Okay, okay, du gjorde dit bedste,\n"
	.string "mine skatte.$"

Route111_Text_DrewIntro:
	.string "Åh hej! De DER SOLBRILLER klær dig.\n"
	.string "Men jeg tror de ser bedre ud på mig.\p"
	.string "Lad os afgøre hvem de klæder bedst\n"
	.string "med en kamp!$"

Route111_Text_DrewDefeat:
	.string "Jeg kunne ikke se hvad der skete til\n"
	.string "siderne på grund af GO-BRILLERNE.$"

Route111_Text_DrewPostBattle:
	.string "GO-brillerne gør det muligt at\n"
	.string "komme igennem sandstorme.\l"
	.string "Det gør mig glad!$"

Route111_Text_HeidiIntro:
	.string "Jeg holder picnic i ørkenen.\p"
	.string "Der er altid en TRÆNER her,\n"
	.string "så jeg kan også nyde en kamp!$"

Route111_Text_HeidiDefeat:
	.string "Åh nej! Du er ond!$"

Route111_Text_HeidiPostBattle:
	.string "Når du kæmper i en sandstorm,\n"
	.string "så pas på din POKéMON's HP.\p"
	.string "Den kan besvime, hvis du ikke\n"
	.string "holder øje med den!$"

Route111_Text_BeauIntro:
	.string "At have disse GO-GOGGLES på gør mig\n"
	.string "føle mig som en superhelt.\l"
	.string "Lige nu kan ingen slå mig!$"

Route111_Text_BeauDefeat:
	.string "Jeg kan ikke vinde alene på vilje…$"

Route111_Text_BeauPostBattle:
	.string "En dag vil jeg blive en rigtig helt.\n"
	.string "Jeg vil arbejde hårdere for at gøre mig\l"
	.string "og mine POKéMON stærkere.$"

Route111_Text_BeckyIntro:
	.string "Jeg har hørt, at der er fossiler at\n"
	.string "finde i ørkenen. Hvor mon de er?$"

Route111_Text_BeckyDefeat:
	.string "Jeg var ikke god nok…$"

Route111_Text_BeckyPostBattle:
	.string "Hvis de kan finde fossiler i \ndesertet, må det have været et \nhav før.$"

Route111_Text_DustyIntro:
	.string "I tredive år har jeg ledt efter\n"
	.string "gamle ruiner!\l"
	.string "Er jeg klar til en udfordring?$"

Route111_Text_DustyDefeat:
	.string "Mens jeg har ledt efter ruiner,\n"
	.string "har jeg ikke ledt efter stærke POKéMON.$"

Route111_Text_DustyPostBattle:
	.string "I tredive år har jeg ledt efter\n"
	.string "gamle ruiner!\p"
	.string "Nej, vent, var det fyrre år?\n"
	.string "Hvad var det nu?$"

Route111_Text_DustyRegister:
	.string "Jeg har ikke ledt efter nogen\n"
	.string "seje POKéMON.\p" 
	.string "Men af en eller anden grund kan jeg\n"
	.string "godt lide POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "I tredive år har jeg ledt efter\n"
	.string "gamle ruiner!\p"
	.string "Vent, var det fyrre år?\n"
	.string "Nå, skal jeg udfordres?$"

Route111_Text_DustyRematchDefeat:
    .string "Jeg har fundet ingen ruiner, og\n"
    .string "heller ingen stærke POKéMON…$"

Route111_Text_DustyPostRematch:
	.string "I tredive år har jeg ledt efter\n"
	.string "gamle ruiner!\p"
	.string "Nej, vent, var det fyrre år,\n"
	.string "jeg har ledt?\p"
	.string "Hm… Det kunne endda være halvtreds…\n"
	.string "Hvor længe har jeg holdt på?$"

Route111_Text_TravisIntro:
	.string "Jeg sprudler af energi!\n"
	.string "Og min POKéMON er også fuld af gejst!$"

Route111_Text_TravisDefeat:
	.string "Min POKéMON har mistet sin gnist…$"

Route111_Text_TravisPostBattle:
	.string "Når jeg ser en TRÆNER med masser af energi,\n"
	.string "kan jeg ikke lade være med at kigge.$"

Route111_Text_IreneIntro:
    .string "Jeg ved ikke, hvor du er på vej hen,\n"
    .string "men vil du gerne kæmpe?$"

Route111_Text_IreneDefeat:
	.string "Åh, du er afskyeligt god!$"

Route111_Text_IrenePostBattle:
	.string "Jeg tænker på, at jeg burde tage\n"
	.string "til MT. CHIMNEY, men udsigten\l"
	.string "her er også meget flot.$"

Route111_Text_DaisukeIntro:
	.string "For at træne mig selv, udfordrer jeg\n"
	.string "alle jeg møder!$"

Route111_Text_DaisukeDefeat:
	.string "Onkel! Jeg giver op!$"

Route111_Text_DaisukePostBattle:
	.string "Alt jeg kan gøre, er at blive ved\n"
	.string "med at træne, indtil jeg kan besejre\n"
	.string "stærke TRÆNERE som dig.\p$"

Route111_Text_WiltonIntro:
    .string "Vis mig, hvor meget du har styrket\ndine POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "Jeg kan se, du har gjort dem\n"
	.string "betydeligt stærkere.$"

Route111_Text_WiltonPostBattle:
    .string "POKéMON og TRÆNERE lærer meget\n"
    .string "gennem at kæmpe.\p"
    .string "Det vigtigste er aldrig at give op\n"
    .string "selvom du taber.$"

Route111_Text_WiltonRegister:
	.string "Der er meget at lære fra\n"
	.string "din træningsstil.\p"
	.string "Jeg beder om en revanche, hvis det\n"
	.string "passer dig.$"

Route111_Text_WiltonRematchIntro:
	.string "Vi træner her for at hæve vores\n"
	.string "spil til næste niveau.\n"
	.string "Bliv og træn med os!$"

Route111_Text_WiltonRematchDefeat:
	.string "Åh, du er habil!$"

Route111_Text_WiltonPostRematch:
	.string "Da du er så stærk, bør du\n"
	.string "sigte efter POKéMON LIGAEN.$"

Route111_Text_BrookeIntro:
	.string "Åh, dine POKéMON ser ud som\n"
	.string "alvorlige skuespillere.\l"
	.string "Jeg er nødt til at bede om en kamp.$"  

Route111_Text_BrookeDefeat:
	.string "De så ikke bare stærke ud,\n"
	.string "de er stærke!$"

Route111_Text_BrookePostBattle:
	.string "Jeg troede, at jeg opdrættede mine \nPOKéMON omhyggeligt, men nej, der er \nstadig meget at gøre.$"

Route111_Text_BrookeRegister:
	.string "Jeg ville ønske, jeg kunne blive venner\n"
	.string "med flere stærke mennesker som dig!$"

Route111_Text_BrookeRematchIntro:
	.string "Du kan gøre POKéMON stærkere eller\n"
	.string "svagere afhængigt af de angreb,\n"
	.string "du lærer dem.\p"
	.string "Hvilke typer af angreb kender dine\n"
	.string "POKéMON?$"

Route111_Text_BrookeRematchDefeat:
	.string "Du har lært dem gode træk!$"

Route111_Text_BrookePostRematch:
	.string "Måske skulle jeg have stoppet min\n"
	.string "POKéMON fra at udvikle sig, indtil\n"
	.string "de lærte bedre angreb…$"

Route111_Text_CeliaIntro:
	.string "Jeg burde ikke være kommet til et\n"
	.string "sted som dette for en picnic!$"

Route111_Text_CeliaDefeat:
	.string "Åh nej!\n"
	.string "Jeg skulle virkelig ikke være kommet!$"

Route111_Text_CeliaPostBattle:
	.string "I en sandstorm som denne kan jeg ikke\n"
	.string "engang med mine GÅPÅ-DIG-briller\n"
	.string "finde et sted til en picnic…$"

Route111_Text_BryanIntro:
	.string "Hvor sej er du?\n"
	.string "Vi skal afsløre den hemmelighed!$"

Route111_Text_BryanDefeat:
	.string "Åh! Din styrke!\n"
	.string "Den er indhyllet i mystik!$"

Route111_Text_BryanPostBattle:
	.string "Denne ørken gemmer på mysterier\n"
	.string "i dens skiftende sand!$"

Route111_Text_BrandenIntro:
	.string "Jeg giver dig lidt af min sandwich\n"
	.string "hvis du taber.$"

Route111_Text_BrandenDefeat:
	.string "Tch! Jeg troede en sandwich ville\n"
	.string "være nok som bestikkelse…$"

Route111_Text_BrandenPostBattle:
	.string "Min SANDSHREW elsker at spise\n"
	.string "mine sandwiches.$"

Route111_Text_TyronIntro:
	.string "Dette er min yndlingstype af POKéMON!$"

Route111_Text_TyronDefeat:
	.string "Vent!\n"
	.string "Fik du et godt kig på mine POKéMON?\p$"

Route111_Text_TyronPostBattle:
    .string "Når man har en kamp, får jeg en kick ud\n"
    .string "af at vise mine POKéMON.\p"
    .string "Jeg satser på, at alle føler det sådan,\n"
    .string "når de går ind i en kamp!$"

Route111_Text_CelinaIntro:
	.string "Vis mig, hvordan jeg kan få lidt spænding\n"
	.string "ind i mit liv.$"

Route111_Text_CelinaDefeat:
	.string "Åh… Min…\n"
	.string "Det var for meget spænding.$"

Route111_Text_CelinaPostBattle:
	.string "Mit hjerte hamrer stadig.\n"
	.string "Du er en fantastisk TRÆNER.$"

Route111_Text_HaydenIntro:
	.string "Når du er lige så sultet som jeg er,\n"
	.string "er der ingen plads til medlidenhed!$"

Route111_Text_HaydenDefeat:
	.string "Åh nej…\p$"

Route111_Text_HaydenPostBattle:
	.string "Min mave knurrer!\n"
	.string "Måske kan jeg grille nogle BÆR…$"

Route111_Text_BiancaIntro:
	.string "Kom du fra MAUVILLE?\n"
	.string "Så burde du være fuld af energi!$"

Route111_Text_BiancaDefeat:
	.string "Åh la la!\n"
	.string "Det' en masse at tage!$"

Route111_Text_BiancaPostBattle:
	.string "Denne vej her…\n"
	.string "Du har stadig en god bid$."

Route112_Text_BriceIntro:
	.string "Hahahaha!\n"
	.string "Hvad siger du til en kamp?\p"
	.string "Dig og mig!\p"
	.string "Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "Jeg tabte!\n"
	.string "Hahahaha!$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha! Noget fløj op i min næse!\n"
	.string "Hahahaha-apsju!$"

Route112_Text_TrentIntro:
	.string "Mine ben er solide fra at hamre op\n"
	.string "og ned af bjergene.\p"
	.string "De vil ikke bukke let,\n"
	.string "ven!$"

Route112_Text_TrentDefeat:
	.string "Av! Mine ben kramper!$"

Route112_Text_TrentPostBattle:
	.string "Prøv vandring, og jeg mener virkelig\n"
	.string "at hamre løs på disse bjergstier\n"
	.string "med en tung rygsæk, der vejer\n"
	.string "dusinvis af pund.\p"
	.string "Det, min ven, vil få din krop i\n"
	.string "seriøs form.$"

Route112_Text_TrentRegister:
	.string "Av, mine ben er blevet krampagtige.\n"
	.string "Kan du hente nogle bandager fra\l"
	.string "min rygsæk?\p"
	.string "Nej, det er min POKéNAV!\n"
	.string "Nå, fint, jeg vil nok registrere dig.$"

Route112_Text_TrentRematchIntro:
	.string "Jeg har holdt mig i form ved at vandre.\n"
	.string "Kraft, det har jeg i massevis!$"

Route112_Text_TrentRematchDefeat:
	.string "Jeg blev overhalet i styrke!\p$"

Route112_Text_TrentRematchPostBattle:
	.string "Jeg hører, at der er nogle virkelig seje\n"
	.string "TRÆNERE på toppen af MT. CHIMNEY.\p"
	.string "Jeg har tænkt mig at komme derop og\n"
	.string "udfordre dem!$"

Route112_Text_LarryIntro:
	.string "Jeg er stærk.\n"
	.string "Jeg vil ikke græde, hvis jeg taber.$"

Route112_Text_LarryDefeat:
	.string "Waaaah!$"

Route112_Text_LarryPostBattle:
    .string "Jeg græder ikke, fordi jeg savner min mor!\n"
    .string "Hulke…\p$"

Route112_Text_CarolIntro:
	.string "Når du er ude at picnicke, så må\n"
	.string "du bare synge løs!\l"
	.string "Kom nu, syng med mig!$"

Route112_Text_CarolDefeat:
	.string "Åh, du er så stærk!$"

Route112_Text_CarolPostBattle:
	.string "Det betyder ikke noget, om du er god\n"
	.string "eller dårlig til at synge eller POKéMON.\p"
	.string "Hvis du har det sjovt, vinder du!$"

Route112_Text_BryantIntro:
	.string "Jeg fangede varme POKéMON på FYREDE STI!\n"
	.string "Tag et kig!$"

Route112_Text_BryantDefeat:
	.string "For en bumpet tur det var!$"

Route112_Text_BryantPostBattle:
	.string "Jeg kan lide den måde, du kæmper på.\n"
	.string "Der er en vis elegance i det.$"

Route112_Text_ShaylaIntro:
	.string "Åh, er du ikke en sød TRÆNER!\n"
	.string "Kom nu, jeg har brug for en romantisk duel!\l"
	.string "Jeg er rimelig god til det!$"

Route112_Text_ShaylaDefeat:
	.string "Hvor er du stærk!\n"
	.string "Du har virkelig overrasket mig!$"

Route112_Text_ShaylaPostBattle:
	.string "Er du optaget lige nu?\n"
	.string "Jeg tænkte på, om vi måske kan have\l"
	.string "en omkamp lige nu…\l"
	.string "Men det er okay, hvis du er optaget.$"

Route113_Text_JaylenIntro:
	.string "Kan du gætte hvorfor det er så\n"
	.string "fedt her omkring?$"

Route113_Text_JaylenDefeat:
	.string "Peeuuw!\n"
	.string "Det stinker!$"

Route113_Text_JaylenPostBattle:
	.string "Vulkanasken blokerer solen,\n"
	.string "så det bliver ikke så varmt.\p"
	.string "Det er godt for mig - jeg kan ikke lide varme!$"

Route113_Text_DillonIntro:
	.string "Vulkanens udbrud er bevis på, at\n"
	.string "jorden er i live.$"

Route113_Text_DillonDefeat:
	.string "Du er virkelig stærk!\p$"

Route113_Text_DillonPostBattle:
	.string "Av! Øv! Jeg kan ikke se!\n"
	.string "Jeg har fået aske i mine øjenvipper!\p"
	.string "Forstår du? Aske og øjenvipper?\p"
	.string "Nå, det var dårligt, undskyld…$"

Route113_Text_MadelineIntro:
	.string "Jeg bruger denne parasol til at skærme\n"
	.string "mig mod den beskidte, ulækre vulkanaske\l"
	.string "fra min kære NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "Puha, puha…\n"
	.string "Jeg er udmattet…$"

Route113_Text_MadelinePostBattle:
	.string "Du er meget god til dette.\n"
	.string "Jeg må sige, jeg er imponeret!$"

Route113_Text_MadelineRegister:
	.string "Her, kravl under min parasol.\n" 
	.string "Lad mig registrere dig i min POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Hej, har det ikke været et stykke tid?\n"
	.string "Må jeg invitere dig til kamp?\p$"

Route113_Text_MadelineRematchDefeat:
	.string "Åh, hvor super!\p$"

Route113_Text_MadelinePostRematch:
	.string "Du er forbløffende god til dette.\n"
	.string "Jeg må sige, jeg er imponeret!$"

Route113_Text_LaoIntro:
	.string "Fra asken springer jeg ud! Hiyah!\n"
	.string "Jeg udfordrer dig!$"

Route113_Text_LaoDefeat:
    .string "Med ære indrømmer jeg nederlag!$"

Route113_Text_LaoPostBattle:
	.string "Jeg skal forfine kunsten at skjule mig.\n"
	.string "Jeg siger farvel.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Oplev den gamle ninja-\n"
	.string "teknik til POKéNAV-registrering!$" 

Route113_Text_LaoRematchIntro:
	.string "Fra ud af asken springer jeg! Hiyah!\n"
	.string "Jeg udfordrer dig!$"

Route113_Text_LaoRematchDefeat:
	.string "Med ære erkender jeg mit nederlag!$"

Route113_Text_LaoPostRematch:
	.string "Min fejlfri skjul blev afsløret\n"
	.string "af mine umodne kampfærdigheder…\p"
	.string "Jeg siger farvel.$"

Route113_Text_LungIntro:
	.string "Tak fordi du fandt mig!\n"
	.string "Men vi skal stadig kæmpe!$"

Route113_Text_LungDefeat:
	.string "Jeg vil bruge min ninjutsu på dig…\n"
	.string "“VULKANISK ASKE VIRVELKAPSEL”!\p"
	.string "…Hvad?\n"
	.string "Er det allerede slut?$"

Route113_Text_LungPostBattle:
	.string "Ved du hvad der er nederen ved at gemme sig?\n"
	.string "Det er ensomt, hvis ingen kommer forbi.$"

Route113_Text_ToriIntro:
	.string "TORI: Vi samler begge to aske.\n"
	.string "Vi kæmper også med POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI: Vi tabte… Det er kedeligt, så\n"
	.string "jeg går for at få lidt flere aske.$"

Route113_Text_ToriPostBattle:
	.string "TORI: Hvor meget aske har vi?\n"
	.string "Forhåbentlig nok til en HVID FLØJTE.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: Vi vil kæmpe 2 mod 2.\n"
	.string "Hvis vi ikke gjorde det, ville vi tabe!$"

Route113_Text_TiaIntro:
    .string "TIA: Begge to samler vi aske.\n"
    .string "Vi kæmper også mod POKéMON.$"

Route113_Text_TiaDefeat:
	.string "TIA: Vi kunne ikke vinde… Det\n"
	.string "er kedeligt, så jeg henter lidt\n"
	.string "mere aske.$"

Route113_Text_TiaPostBattle:
	.string "TIA: Vi har en masse aske!\n"
	.string "Jeg tror, at det er nok til en\nHVID FLØJTE!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: Vi vil kæmpe 2 mod 2.\n"
	.string "Ellers vinder vi ikke!$"

Route113_Text_CobyIntro:
	.string "Pfft, med disse vinger kan jeg\n"
	.string "bare give dig et lille \n"
	.string "skub!$"

Route113_Text_CobyDefeat:
	.string "Hvad en… Hvad?$"

Route113_Text_CobyPostBattle:
	.string "Jeg ved ikke hvad jeg skal sige, når jeg\n"
	.string "bliver slået så let…$"

Route113_Text_SophieIntro:
    .string "Varmen her gør mig søvnig.\n"
    .string "Kæmp imod mig, så jeg kan holde mig vågen.$"

Route113_Text_SophieDefeat:
	.string "Dette er en drøm.\n"
	.string "Det er jeg sikker på…$"

Route113_Text_SophiePostBattle:
	.string "At tabe brænder mig op…\n"
	.string "Jeg vil bare sove lige her!\l"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Var du måske midt\n"
	.string "i at samle vulkansk aske?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "Vi blev slået rent.$"

Route113_Text_LawrencePostBattle:
	.string "Jeg burde gemme mig under asken også.$"

Route113_Text_WyattIntro:
	.string "V-Vil du kæmpe med mig?\n"
	.string "Selvom jeg lige har fanget min POKéMON?$"

Route113_Text_WyattDefeat:
	.string "Er I alle glade for at vinde?\n"
	.string "Selvom det kun er mig?$"

Route113_Text_WyattPostBattle:
	.string "Åh, så vil du pludselig sige et ord til\n"
	.string "taberen?\p"
	.string "Er du ikke bare den sejeste?\n"
	.string "Humph!$"

Route114_Text_LennyIntro:
	.string "Jodeladidejhuu!\p"
	.string "… …\p"
	.string "Du skulle råbe\n"
	.string "“jodeladidejhuu” da det ikke\l"
	.string "giver eko her!$"

Route114_Text_LennyDefeat:
	.string "Jodelajuhuu!$"

Route114_Text_LennyPostBattle:
	.string "Da jeg var en lille rapscallion, troede jeg, at der var nogen, der kopierede mig og råbte tilbage, “Jodelayhihoo.”$"

Route114_Text_LucasIntro:
	.string "Hvis du ikke er forberedt, skal du\n"
	.string "ikke være oppe i bjergene!$"

Route114_Text_LucasDefeat:
	.string "Bjergene er ubarmhjertige…$"

Route114_Text_LucasPostBattle:
	.string "Om vinteren bliver bjerge dødbringende\n"
	.string "med snestorme og laviner.$"

Route114_Text_ShaneIntro:
	.string "Camping er sjovt! Du kan fiske,\n"
	.string "riste skumfiduser og fortælle \n"
	.string "uhyggelige historier!\p"
	.string "Men det bedste af det hele er POKéMON\n"
	.string "kampe!$"

Route114_Text_ShaneDefeat:
	.string "Alt for stærk!$"

Route114_Text_ShanePostBattle:
	.string "Jeg synes, det er fantastisk, at jeg\n"
	.string "kan tage på telteventyr med mine POKéMON.$"

Route114_Text_NancyIntro:
	.string "Jeg skal have motion efter et måltid.\n"
	.string "Skal vi have en kamp?$"

Route114_Text_NancyDefeat:
	.string "Åh nej!$"

Route114_Text_NancyPostBattle:
	.string "Jeg havde lige et lækkert måltid.\n"
	.string "Jeg bliver søvnig…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Vil du kæmpe mod mine POKéMON?\p$"

Route114_Text_SteveDefeat:
	.string "M-Min POKéMON…$"

Route114_Text_StevePostBattle:
	.string "En stor krop, der er helt klumpet og hård,\n"
	.string "kæmpestore horn og farlige tænder…\p"
	.string "Ufufufufu…\n"
	.string "Jeg ønsker, jeg havde en POKéMON som den…$"

Route114_Text_SteveRegister:
	.string "Glem ikke hvad du har gjort imod mig!\n"
	.string "Jeg vil sørge for, at du ikke kan glemme det!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Kom så, kæmp mod mine POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "Jeg føler mig så heldig, at jeg får lov til at se dine\n"
	.string "POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Når jeg ser POKéMON kæmpe, bliver jeg\n"
	.string "helt forskrækket og rystet…$"

Route114_Text_BernieIntro:
	.string "Hvis du tænder et bål,\n"
	.string "sørg for at have vand ved hånden.$"

Route114_Text_BernieDefeat:
	.string "Tak for at slukke min ild!$"

Route114_Text_BerniePostBattle:
	.string "Man skal virkelig passe på med\n"
	.string "ild i en skov.\p"
	.string "Undervurdér aldrig kraften af\n"
	.string "ilden.$"

Route114_Text_BernieRegister:
	.string "Du sætter mit sind i brand.\n"
	.string "Lad os registrere hinanden!$"

Route114_Text_BernieRematchIntro:
	.string "Har du lært at have vand ved hånden\n"
	.string "til bål? $"

Route114_Text_BernieRematchDefeat:
	.string "Jeg fik sprøjtet ned,\n"
	.string "før jeg kunne antænde,\n"
	.string "tror jeg.$"

Route114_Text_BerniePostRematch:
	.string "Du skal virkelig passe på med\n"
	.string "ild i en skov.\p"
	.string "Undervurder aldrig kraften af\n"
	.string "ilden.$"

Route114_Text_ClaudeIntro:
	.string "Hvis vi var at fiske, ville du ikke\n"
	.string "have en chance imod mig.\l"
	.string "Så kom med dine POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "Hvis vi havde været til at fiske, ville jeg have vundet…$"

Route114_Text_ClaudePostBattle:
	.string "Jeg tror, jeg vil prøve lykken\n"
	.string "med at fange en stor fisk ved\n"
	.string "METEOR FALLS.\p"
	.string "Der må være noget godt derinde.\n"
	.string "Jeg kan bare mærke det.$"

Route114_Text_NolanIntro:
	.string "Jeg kan godt lide at fiske. Men jeg \n"
	.string "kan også godt lide at kæmpe!\p"
	.string "Hvis nogen udfordrer mig, er jeg \n"
	.string "klar, selv når jeg fisker.$"

Route114_Text_NolanDefeat:
	.string "Jeg kan godt lide at kæmpe, men det\n"
	.string "betyder ikke, at jeg er god til det…$"

Route114_Text_NolanPostBattle:
	.string "Denne gang gør jeg det!\p"
	.string "Jeg tænker altid det, så jeg kan\n"
	.string "ikke gå væk fra fiskeri eller POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Nå, selvfølgelig.\n"
	.string "Jeg er i humør til det.\l"
	.string "Jeg vil lære dig lidt om POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: Sikken en fantastisk kampstil!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Jeg underviste min junior IVY\n"
	.string "om POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Grin…\n"
	.string "Hvis du vil kæmpe med os, er bare én\n"
	.string "POKéMON ikke nok!$"

Route114_Text_IvyIntro:
	.string "IVY: Hvem lærte dig om POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: Sikke en fantastisk kampstil!$"

Route114_Text_IvyPostBattle:
	.string "IVY: Jeg begyndte at træne POKéMON\n"
	.string "fordi TYRA, min studerende mentor,\l"
	.string "lærte mig!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Har du kun én POKéMON?\n"
	.string "Det må være ensomt.$"

Route114_Text_KaiIntro:
	.string "Jeg har fanget en kæmpe fisk!\n"
	.string "En kæmpe fisk, jeg siger dig!$"

Route114_Text_KaiDefeat:
	.string "Hvad var det for noget?\n"
	.string "Tabte min i størrelse?$"

Route114_Text_KaiPostBattle:
	.string "Okay!\n"
	.string "Jeg vil bare fiske mig en større en!$"

Route114_Text_CharlotteIntro:
	.string "Mig!\n"
	.string "Jeg er ikke bare et pænt ansigt!$"

Route114_Text_CharlotteDefeat:
	.string "Det var overhovedet ikke sødt!$"

Route114_Text_CharlottePostBattle:
	.string "Jeg vil ikke have en POKéMON, der\n"
	.string "bare er sød.\p"
	.string "Jeg ELSKER søde, der har et par\n"
	.string "særegenheder!$"

Route114_Text_AngelinaIntro:
	.string "Har dine POKéMON udviklet sig\n"
	.string "meget?$"

Route114_Text_AngelinaDefeat:
	.string "Åh, jeg ser.\n"
	.string "Det er godt at vide.$"

Route114_Text_AngelinaPostBattle:
	.string "Nogle POKéMON ændrer sig så meget,\n"
	.string "når de udvikler sig, det er overraskende!$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "Du virker ret kompetent…\l"
	.string "Lad mig følge med dig!$"

Route115_Text_TimothyDefeat:
	.string "Du er meget stærkere end jeg\n"
	.string "havde forestillet mig!$"

Route115_Text_TimothyPostBattle:
	.string "Der findes ikke noget der hedder en født geni.\n"
	.string "Det hele afhænger af indsatsen!\l"
	.string "Det er hvad jeg tror…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Et tab så grundigt har været et\n"
	.string "fjernt minde.\p"
	.string "Hvis du tillader det, ønsker jeg en\n"
	.string "anden mulighed for at kæmpe.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Som altid taler din smidighed\n"
	.string "for dig selv.\l"
	.string "Kom, hold mig med selskab!$"

Route115_Text_TimothyRematchDefeat:
	.string "Stærk som altid!$"

Route115_Text_TimothyPostRematch:
	.string "Alt hvad der kræves, er anstrengelse!\p"
	.string "Jeg tabte, fordi jeg ikke har lagt nok\n"
	.string "anstrengelse!$"

Route115_Text_KoichiIntro:
	.string "Dig!\p"
	.string "Min MACHOP!\p"
	.string "Kræver en kamp!$"

Route115_Text_KoichiDefeat:
	.string "Av av av!$"

Route115_Text_KoichiPostBattle:
	.string "Min MACHOP-bande!\p"
	.string "Så længe de søger styrke, vil jeg\n"
	.string "vokse mig stærk med dem!$" 

Route115_Text_NobIntro:
	.string "Min største færdighed er at knuse mursten\n"
	.string "med min pande!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah!\n"
	.string "Mit hoved er smadret!$"

Route115_Text_NobPostBattle:
	.string "Jeg har undervist mine POKéMON i karate.\p"
	.string "Det ser ud til, at de vil blive meget bedre\n"
	.string "end mig. Jeg er spændt på det.$"

Route115_Text_NobRegister:
	.string "Du imponerer mig! Giv mig en ny kamp\n"
	.string "når jeg har trænet om!$"

Route115_Text_NobRematchIntro:
	.string "Efter at du slog mig, har vi trænet hårdt\n"
	.string "for at forbedre vores færdigheder.\l"
	.string "Kom nu, giv os en revanche!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah!\n"
	.string "Vi tabte igen!$"

Route115_Text_NobPostRematch:
    .string "Mine POKéMON vil blive stærkere!\n"
    .string "Jeg vil fordoble min træning!$"

Route115_Text_CyndyIntro:
	.string "Denne strand er mit hemmelige træningssted!\n"
	.string "Du skal ikke blande dig!$"

Route115_Text_CyndyDefeat:
	.string "Jeg har ikke trænet nok!$"

Route115_Text_CyndyPostBattle:
	.string "Sandet virker som en pude for at reducere\n"
	.string "stød og forhindre skader.\l"
	.string "Dette er det perfekte sted at træne.$"

Route115_Text_CyndyRegister:
	.string "Okay, fine, you're free to come here.\n"
	.string "In return, I'd like to battle you again.$"

Route115_Text_CyndyRematchIntro:
	.string "Okay, let's get this battle on!$"

Route115_Text_CyndyRematchDefeat:
	.string "Jeg kan kæmpe, men mine POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Selv når jeg taber, får jeg stadig lidt\n"
	.string "glæde ud af det.\l"
	.string "Det må være fordi, jeg elsker POKéMON.$"

Route115_Text_HectorIntro:
	.string "Jeg har en sjælden POKéMON!\n"
	.string "Vil du gerne se den?\p$"

Route115_Text_HectorDefeat:
	.string "Du…\n"
	.string "Du vil have min POKéMON, ikke sandt?$"

Route115_Text_HectorPostBattle:
	.string "Jeg har denne sjældne POKéMON.\n"
	.string "Det er nok til at tilfredsstille mig.$"

Route115_Text_KyraIntro:
	.string "Jeg vil kæmpe, mens jeg løber!\n"
	.string "Prøv at følge med mig!$"

Route115_Text_KyraDefeat:
	.string "Pust, pust…$"

Route115_Text_KyraPostBattle:
	.string "Jeg lavede den fejl at prøve at kæmpe\n"
	.string "mens jeg løb!\p"
	.string "Jeg burde tage en løbetur for at falde til ro…$"

Route115_Text_JaidenIntro:
	.string "Tag den!\n"
	.string "Ultra POKéMON ninja angreb!$"

Route115_Text_JaidenDefeat:
	.string "Åh nej!\n"
	.string "Vores strategi fejlede!$"

Route115_Text_JaidenPostBattle:
	.string "Men mine POKéMON var ultra,\n"
	.string "ikke sandt?$"

Route115_Text_HeleneIntro:
	.string "Mine POKéMON har styrke på\n"
	.string "sortbælte-niveau!$"

Route115_Text_HeleneDefeat:
	.string "Det her er alt for ydmygende!$"

Route115_Text_HelenePostBattle:
	.string "Jeg møder sjældent nogen, der er\n"
	.string "bedre end mig…\p"
	.string "Jeg forstår det nu!\n"
	.string "Du er en GYM LEADER, ikke sandt?$"

Route115_Text_AlixIntro:
	.string "Vores øjne mødtes!\n"
	.string "Der er ingen undslipning nu!$"

Route115_Text_AlixDefeat:
	.string "Av!\n"
	.string "Ikke dårligt!$"

Route115_Text_AlixPostBattle:
	.string "Nå, nå.\n"
	.string "Jeg tror jeg vil TELEPORTERE hjem.$"

Route115_Text_MarleneIntro:
	.string "Du har forstyrret min meditation…\n"
	.string "Du vil blive straffet for det.$"

Route115_Text_MarleneDefeat:
	.string "Du har ødelagt min koncentration!$"

Route115_Text_MarlenePostBattle:
	.string "Jeg var i meditationsform med mine POKéMON.\n"
	.string "Men dette sted er ikke særlig fredeligt…$"

Route116_Text_ClarkIntro:
	.string "Hvis tunnelen ikke går igennem, så\n"
	.string "skal jeg bare gå over toppen.$"

Route116_Text_ClarkDefeat:
	.string "Hov… Hov…\n"
	.string "At tabe gjorde mig træt…$"

Route116_Text_ClarkPostBattle:
	.string "Det er ingen big deal, hvis der ikke er nogen tunnel.\n"
	.string "For en VANDRER er bjerge veje!$"

Route116_Text_JoeyIntro:
	.string "Mine POKéMON regerer!\n"
	.string "Kom og se dem!$"

Route116_Text_JoeyDefeat:
	.string "Av! Et skrammel!\n"
	.string "Jeg skal sætte et plaster på!$"

Route116_Text_JoeyPostBattle:
	.string "Forbindinger er tegn på sejhed!\n"
	.string "Jeg har en mere!$"

Route116_Text_JoseIntro:
	.string "Mine BILLE POKéMON er seje!\n"
	.string "Lad os kæmpe!$"  

Route116_Text_JoseDefeat:
	.string "Jeg tabte!\n"
	.string "Jeg troede, jeg havde dig!$"

Route116_Text_JosePostBattle:
	.string "INSEKT POKéMON udvikler sig hurtigt.\n"
	.string "Så de bliver også hurtigt stærke.$"

Route116_Text_JaniceIntro:
	.string " Lad mig lære dig, hvor stærk min\n"
	.string " SØD POKéMON er!$"

Route116_Text_JaniceDefeat:
	.string "Du er et hak over mig…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON, der besidder sødme og\n"
	.string "styrke, det er ideelt, synes jeg.$"

Route116_Text_JerryIntro:
	.string "Vi lærer alle mulige ting på\n"
	.string "TRÆNERENS SKOLE.\p"
	.string "Jeg vil teste tingene i virkeligheden!$"

Route116_Text_JerryDefeat:
	.string "Jeg pjækkede i skolen…\n"
	.string "Det er derfor, jeg tabte.$"

Route116_Text_JerryPostBattle:
	.string "Jeg bliver nødt til at tage nogle kurser\n"
	.string "på TRÆNERENS SKOLE.\l"
	.string "Hvis ikke, bliver ROXANNE skuffet.$"

Route116_Text_JerryRegister1:
	.string "Jeg lærte på TRÆNERENS SKOLE\n"
	.string "at en POKéNAV kan registrere TRÆNERE.\p"
	.string "Jeg forstår ikke rigtigt, hvad det betyder,\n"
	.string "så kan jeg bare prøve det?$"

Route116_Text_JerryRegister2:
	.string "Jeg lærte på TRÆNER-SKOLEN\n"
	.string "at en POKéNAV kan registrere TRÆNERE.\p"
	.string "Jeg forstår ikke rigtigt hvad det betyder,\n"
	.string "så kan jeg bare prøve det?$"

Route116_Text_JerryRematchIntro:
	.string "Jeg har studeret seriøst på\n"
	.string "TRÆNERENS SKOLE.\l"
	.string "Jeg vil ikke tabe som sidste gang.$"

Route116_Text_JerryRematchDefeat:
	.string "Hvad?\n"
	.string "Jeg har læst flittigt.$"

Route116_Text_JerryPostRematch:
	.string "Jeg bliver nødt til at gøre nogle\n"
	.string "kurser om på TRÆNER-SKOLEN.\l"
	.string "Ellers bliver ROXANNE bestemt irriteret.$"

Route116_Text_KarenIntro:
	.string "Jeg studerer i skolen, og jeg studerer\n"
	.string "også på vejen hjem!$"

Route116_Text_KarenDefeat:
	.string "Jeg er i chok--jeg tabte?$"

Route116_Text_KarenPostBattle:
	.string "Åh nej, jeg bliver aldrig en elegant\n"
	.string "TRÆNER som ROXANNE på den måde!$"

Route116_Text_KarenRegister1:
	.string "Åh, wow! Er det ikke en POKéNAV?\n"
	.string "Jeg har også en! Vil du registrere mig?$"

Route116_Text_KarenRegister2:
	.string "Åh, wow! Er det ikke en POKéNAV?\n"
	.string "Jeg har også en! Registrér mig, venligst!$"

Route116_Text_KarenRematchIntro:
	.string "Jeg har læst utroligt meget, siden jeg så dig.\n"
	.string "Du skal se mine resultater!$"

Route116_Text_KarenRematchDefeat:
	.string "Jeg er i chok.\n"
	.string "Jeg tabte igen?$"

Route116_Text_KarenPostRematch:
	.string "Du slog ROXANNE?\n"
	.string "Jeg kan ikke slå dig endnu. Ikke endnu.$"

Route116_Text_SarahIntro:
	.string "Bare så du ved det, jeg er aldrig blevet\n"
	.string "slået af nogen i noget.$"

Route116_Text_SarahDefeat:
	.string "Åh, min gode.\n"
	.string "Det her er en ny oplevelse for mig.$"

Route116_Text_SarahPostBattle:
	.string "Mit liv i luksus giver mig alt, hvad\n"
	.string "jeg kunne ønske mig.\p"
	.string "Dog, når det kommer til POKéMON,\n"
	.string "har min rigdom ingen betydning.$"

Route116_Text_DawsonIntro:
	.string "Når du lægger dine øjne på min POKéMONs\n"
	.string "smukke pels, vil deres skønhed gøre dig\n"
	.string "magtesløs!$"

Route116_Text_DawsonDefeat:
	.string "Åh, lille skat, sig det ikke er sandt!$"

Route116_Text_DawsonPostBattle:
	.string "Åh nej, nej, nej!\n"
	.string "Du har rodet min POKéMONs pels til!\l"
	.string "Du har også ødelagt mit frisure!\l"
	.string "Jeg bliver nødt til at ringe til min stylist nu!$"

Route116_Text_DevanIntro:
	.string "Vi vil rocke dig hårdt!$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi!\n"
	.string "Overhovedet ingen konkurrence!$"

Route116_Text_DevanPostBattle:
	.string "Jeg burde prøve forskellige POKéMON-\ntyper, det er hvad jeg burde gøre.$"

Route116_Text_JohnsonIntro:
    .string "Det er en blindgyde heroppe.\n"
    .string "Jeg keder mig, så skal vi kæmpe?$"

Route116_Text_JohnsonDefeat:
	.string "Det var sjovt, selvom jeg tabte.$"

Route116_Text_JohnsonPostBattle:
	.string "Vil du blive her og hygge\n"
	.string "dig med mig?\p$"

Route117_Text_IsaacIntro:
	.string "Hør her, kunne jeg få dig til\n"
	.string "at kæmpe mod de POKéMON, jeg\n"
	.string "opdrætter?\p$"

Route117_Text_IsaacDefeat:
	.string "Du har opdraget din strålende…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON handler ikke kun om styrke.\p"
	.string "At finpudse en unik side af ens\n"
	.string "karakter er en anden måde at nyde\l"
	.string "POKéMON på.$"

Route117_Text_IsaacRegister:
	.string "Jeg vil fordoble min træning.\n"
	.string "Vil du kigge ind på os?$"

Route117_Text_IsaacRematchIntro:
	.string "De POKéMON, jeg har opdrættet,\n"
	.string "ser godt ud, ligesom tidligere.$"

Route117_Text_IsaacRematchDefeat:
	.string "Du ved, hvordan man opdrager dem ordentligt.\n"
	.string "Du har måske DAGPLEJE færdigheder…$"

Route117_Text_IsaacPostRematch:
	.string "Dine POKéMON vokser godt!\n"
	.string "Du burde tilmelde dem i KONKURRENCER.$"

Route117_Text_LydiaIntro:
	.string "Vil du ikke lade mig vurdere,\n"
	.string "om du har opdraget dine POKéMON rigtigt?$"

Route117_Text_LydiaDefeat:
	.string "Ja, de vokser ordentligt.$"

Route117_Text_LydiaPostBattle:
	.string "Prøv at opdrage POKéMON med\n"
	.string "mere opmærksomhed på deres personlighedstræk.$"

Route117_Text_LydiaRegister:
	.string "Jeg er glad for at have mødt en fantastisk TRÆNER som dig.\n"
	.string "Håber at se dig igen.$"

Route117_Text_LydiaRematchIntro:
	.string "Lad mig genoverveje om du har\n"
	.string "opdrættet dine POKéMON ordentligt.$"

Route117_Text_LydiaRematchDefeat:
	.string "De vokser beundringsværdigt.$"

Route117_Text_LydiaPostRematch:
	.string "POKéMON synes at kunne lide forskellige slags\n"
	.string "af {POKEBLOCK}S, afhængigt af deres natur.$"

Route117_Text_DylanIntro:
	.string "Jeg er midt i en triatlon, men,\n"
	.string "det er ligemeget, lad os kæmpe!$"

Route117_Text_DylanDefeat:
	.string "Jeg løb tør for energi!$"

Route117_Text_DylanPostBattle:
	.string "Jeg har måske ødelagt det…\p"
	.string "Jeg kunne være endt sidst under\n"
	.string "den kamp…$"

Route117_Text_DylanRegister:
	.string "POKéMON skal også være stærke, ikke?\n"
	.string "Jeg vil gerne have dig til at træne mig!$"

Route117_Text_DylanRematchIntro:
	.string "Jeg er midt i en triatlon,\n"
	.string "og jeg ligger trygt i front.\n"
	.string "Lad os gøre det til en hurtig kamp!$"

Route117_Text_DylanRematchDefeat:
	.string "Jeg løb tør for energi igen!$"

Route117_Text_DylanPostRematch:
	.string "Jeg var tops til at svømme og cykle,\n"
	.string "men jeg er ikke helt så selvsikker\l"
	.string "med POKéMON endnu.$"

Route117_Text_MariaIntro:
	.string "Jeg træner til triatlon med POKéMON,\n"
	.string "så jeg er ret sikker på min fart.$"

Route117_Text_MariaDefeat:
	.string "Jeg skal have lidt mere træning,\n"
	.string "tror jeg.$"

Route117_Text_MariaPostBattle:
	.string "Træning er meningsfuld kun hvis du\n"
	.string "holder fast i den regelmæssigt.\p"
	.string "Okay! Jeg vil genoptage min\n"
	.string "træning!\nI morgen!$"

Route117_Text_MariaRegister:
	.string "Du ser ud til at træne ordentligt…\n"
	.string "Hvis du vil, kan vi kæmpe senere!$"

Route117_Text_MariaRematchIntro:
	.string "Er du ved at holde dig ajour med din træning?\n"
	.string "Det er jeg helt sikkert!\l"
	.string "Lad mig vise dig beviset!$"

Route117_Text_MariaRematchDefeat:
	.string "Jeg er nødt til at få mere \ntræning,\n"
	.string "antager jeg.$"

Route117_Text_MariaPostRematch:
	.string "Jeg vil genoptage træningen i morgen.\n"
	.string " Lad os kæmpe igen en anden gang!$"

Route117_Text_DerekIntro:
	.string "Engang en INSEKT FANGER!\n"
	.string "Og nu en INSEKT FANATIKER!\p"
	.string "Men min kærlighed til POKéMON er stadig\n"
	.string "uforandret!$"

Route117_Text_DerekDefeat:
	.string "Min uduelighed forbliver\n"
	.string "uændret…$"

Route117_Text_DerekPostBattle:
	.string "Alt, hvad jeg gjorde, var at følge mit hjerte,\n"
	.string "og nu kalder de mig en INSEKTGALNING…\p"
	.string "Men jeg er stadig ekspert i INSEKT POKéMON,\n"
	.string "så det er kun naturligt, at de kalder mig\l"
	.string "en INSEKTGALNING.$"

Route117_Text_AnnaIntro:
	.string "ANNA: Jeg er sammen med min søde junior"
	.string "elevpartner. Jeg skal gøre det godt!$"

Route117_Text_AnnaDefeat:
    .string "ANNA: Jeg er sammen med min smukke\n"
    .string "juniorstuderende! Lad mig vinde!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Dine POKéMON har nogle gode\n"
	.string "kombinationer.\p"
	.string "Jeg vil sige, at du kun er nummer to\n"
	.string "i forhold til os!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: Vi kan ikke tage det her liggende! \n"
	.string "Kommer du tilbage, gør du ikke? \p$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: Hvis du vil kæmpe mod os,\n"
	.string "skal du have medbragt to POKéMON.$"

Route117_Text_MegIntro:
	.string "MEG: Jeg skal samarbejde med min super\n"
	.string "erfarne studentermakker og slå dig!$"

Route117_Text_MegDefeat:
	.string "MEG: Åh, nej!\n"
	.string "Undskyld, ANNA! Jeg skuffede dig…$"

Route117_Text_MegPostBattle:
	.string "MEG: Jeg trak ANNA ned…\n"
	.string "Hvis jeg ikke gjorde det, ville hun have vundet!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Har du kun en POKéMON?\n"
	.string "Så kan vi desværre ikke kæmpe med dig.\p"
	.string "Vi vil gerne have en 2-mod-2 kamp.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: Jeg kan ikke blive ved med at tabe\n"
	.string "foran min juniorpartner, vel?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: Jeg kunne ikke komme\n"
	.string "tilbage i rytmen.$"

Route117_Text_AnnaPostRematch:
    .string "ANNA: Dine POKéMON har nogle gode\n"
    .string "kombinationer.\p"
    .string "Jeg vil sige, du er kun nr. to efter os!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: Hvis du vil kæmpe mod os,\n"
	.string "skal du medbringe to POKéMON.$"

Route117_Text_MegRematchIntro:
	.string "MEG: Jeg vil danne makkerpar med min\n"
	.string "ældre partner og vinde denne gang!$" 

Route117_Text_MegRematchDefeat:
	.string "MEG: Alt for stærk!$"

Route117_Text_MegPostRematch:
	.string "MEG: Jeg kæmpede sammen med min\n"
	.string "ældre partner, men vi tabte…\p"
	.string "Det er så nedslående…$"

Route117_Text_MegRematchNotEnoughMons:
    .string "MEG: Har du kun én POKéMON?\n"
    .string "Så kan vi desværre ikke kæmpe mod dig.\p"
    .string "Vi vil gerne have en 2-mod-2 kamp.$"

Route117_Text_MelinaIntro:
    .string "Er det ikke dejligt? At kæmpe mens man\n"
    .string "kigger på smukke blomster?\p$"

Route117_Text_MelinaDefeat:
	.string "Oh, det er ret imponerende!$"

Route117_Text_MelinaPostBattle:
	.string "Det føles vidunderligt at løbe\n"
	.string "mens man kigger på blomster.$"

Route117_Text_BrandiIntro:
	.string " Lad mig demonstrere kraften\n"
	.string " gemt i en PSYCHIC POKéMON!$"

Route117_Text_BrandiDefeat:
	.string "Forbløffende!$"

Route117_Text_BrandiPostBattle:
	.string "PSYCHIC POKéMON er komplekse.\n"
	.string "Du burde prøve at fange nogle.$"

Route117_Text_AishaIntro:
	.string "Fokuser på at få sejren.\n"
	.string "Sådan kæmper jeg!$"

Route117_Text_AishaDefeat:
	.string "Jeg spilder ikke tid på at være\n"
	.string "vred over et nederlag--jeg vil\n"
    .string "hellere træne.$"

Route117_Text_AishaPostBattle:
	.string "Jeg tror, hvis du bekymrer dig om at\n"
	.string "tabe, er du mere tilbøjelig til at tabe.$"

Route118_Text_RoseIntro:
	.string "Duften af blomster har en magisk\n"
	.string "kraft. Den renser os krop og sjæl.$"

Route118_Text_RoseDefeat:
    .string "Åh, kære mig.\n"
    .string "Det ser ud til, at jeg har tabt.$"

Route118_Text_RosePostBattle:
	.string "Blomster, POKéMON…\n"
	.string "Jeg elsker alt, der dufter godt.\p"
	.string "Stinkende ting…\n"
	.string "Det springer jeg over.$"

Route118_Text_RoseRegister:
	.string "Snif… Den lugt--det er en POKéNAV!\n"
	.string "Vi skal registrere hinanden!$"

Route118_Text_RoseRematchIntro:
	.string "Var du tiltrukket heraf af den\n"
	.string "søde duft?$"

Route118_Text_RoseRematchDefeat:
	.string "Duftenes kraft…\n"
	.string "Det så ikke ud til at gøre meget.$"

Route118_Text_RosePostRematch:
	.string "Hvis du bruger en sød duft ordentligt,\n"
	.string "vil POKéMON blive tiltrukket af den.$"

Route118_Text_PerryIntro:
	.string "FUGLE POKéMON, der FLYVER elegant i\n"
	.string "himlen… De er de bedste!$"

Route118_Text_PerryDefeat:
	.string "Åh nej…\n"
	.string "Jeg crashede…$"

Route118_Text_PerryPostBattle:
	.string "Du har fantastiske POKéMON.\n" 
	.string "Jeg bliver nødt til at træne mine bedre.$"  

Route118_Text_ChesterIntro:
	.string "Tag flugt!\n"
	.string "Min FUGLPokémon!$"

Route118_Text_ChesterDefeat:
	.string "De tog flugten…$"

Route118_Text_ChesterPostBattle:
	.string "Hvis de blev stærkere, ville de kunne\n"
	.string "flyve mere frit…$"

Route118_Text_BarnyIntro:
	.string "Jeg er en FISKER, men også en TRÆNER.\n"
	.string "Jeg træner de POKéMON, jeg har fanget.$"

Route118_Text_BarnyDefeat:
	.string "Jeg troede, jeg klarede mig fint i min\n"
	.string "træning…$"

Route118_Text_BarnyPostBattle:
	.string "Jeg kunne ikke vinde ved bare at træne POKéMON\n"
	.string "mens jeg fiskede…\p"
	.string "Lavede jeg tingene halvhjertet?$"

Route118_Text_WadeIntro:
	.string "For FISKERE er udstyr nøglen.\p"
	.string "Men for TRÆNERE er de vigtigste\n"
	.string "ingredienser POKéMON og hjerte, selvfølgelig!$"

Route118_Text_WadeDefeat:
	.string "Jeg blev slået med hjertet?$"

Route118_Text_WadePostBattle:
	.string "Når man tænker over det, er fiskeri en kamp\n"
	.string "mellem en FISKER og en POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Lad min melodi ryste din sjæl!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "En elektrisk guitar behøver ikke\n"
	.string "altid at være larmende…\p"
	.string "Den kan spilles for at frembringe\n"
	.string "denne hjerteopvarmende melodi…$"

Route118_Text_DaltonRegister:
	.string "Når jeg komponerer bedre melodier,\n"
	.string "skal du komme og lytte, okay?$"

Route118_Text_DaltonRematchIntro:
	.string "En melodi fra mine POKéMON og mig…\n"
	.string "Lad os levere den til din sjæl.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
    .string "Når jeg spiller, skal mine følelser nå\n"
    .string "dig gennem min elektriske guitar…$"

Route118_Text_DeandreIntro:
	.string "Go, go, go!\n"
	.string "POKéMON 1, 2, and 3!$"

Route118_Text_DeandreDefeat:
	.string "Kom ind, POKéMON! Er du okay?\n"
	.string "POKéMON 1, 2 og 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Er det ikke sejt, at jeg har et POKéMON\n"
	.string "kamphold?\p"
	.string "Du kan kopiere mig--det gør mig ikke noget!$"

Route119_Text_BrentIntro:
	.string "Vi er MIMIC CIRCLE!\n"
	.string "Vi MIMIC'er hvad du gør!$"

Route119_Text_BrentDefeat:
	.string "Ups!\n"
	.string "Jeg tabte!$"

Route119_Text_BrentPostBattle:
	.string "Hvad er der så godt ved efterligning?\p"
	.string "Fufufu…\n"
	.string "Det vil du aldrig forstå…$"

Route119_Text_DonaldIntro:
	.string "Så mødes vi endelig!\n"
	.string "Mine INSEKT POKéMON vil holde dig med selskab!$"

Route119_Text_DonaldDefeat:
	.string "Jeg ville ønske, vi aldrig havde mødt hinanden…$"

Route119_Text_DonaldPostBattle:
	.string "Jeg vil gerne IMITERE dig lidt mere.\n"
	.string "Kan du skynde dig at flytte?\p$"

Route119_Text_TaylorIntro:
	.string "Hvis du går fremad, går vi fremad.\p"
	.string "Hvis du drejer til højre, drejer vi også…$"

Route119_Text_TaylorDefeat:
	.string "Men hvis du vinder, taber jeg…$"

Route119_Text_TaylorPostBattle:
	.string "Jeg kan ikke EFTERABE din sejr i kampen.\n"
	.string "Det er bare umuligt…\l"
	.string "Det brænder i mig…$"

Route119_Text_DougIntro:
	.string "Jeps, du har endelig fanget mig!\n"
	.string "Eller prøvede du at undgå mig?$"

Route119_Text_DougDefeat:
	.string "Hu-hej, det var en fantastisk kamp!$"

Route119_Text_DougPostBattle:
	.string "Vi er MIMIC CIRCLE!\n"
	.string "Jeg håber, du nød vores optræden.$"

Route119_Text_GregIntro:
	.string "Du ved ikke, hvem jeg er, gør du?\p"
	.string "Men jeg kender heller ikke dig.\n"
	.string "Så lad os kæmpe!$"

Route119_Text_GregDefeat:
	.string "Du er ret stærk!$"

Route119_Text_GregPostBattle:
	.string "Indtil du går et sted hen, vil vi\n"
	.string "fortsætte med at efterligne dine handlinger.$"

Route119_Text_KentIntro:
	.string "MIMIC CIRKLEN blev dannet af mennesker,\n"
	.string "som kan lide at efterligne.\p"
	.string "En kamp starter øjeblikket vi mødes!$"

Route119_Text_KentDefeat:
	.string "Jeg giver op!$"

Route119_Text_KentPostBattle:
	.string "Vil du ikke være med i vores MIMIC CIRCLE?\p$"

Route119_Text_JacksonIntro:
	.string "Who has the knowledge and\n"
	.string "the technique for survival?\p"
	.string "POKéMON RANGERS, that's who!$"

Route119_Text_JacksonDefeat:
	.string "Jeg havde ikke nok POKéMON\n"
	.string "viden…$"

Route119_Text_JacksonPostBattle:
	.string "For at bryde væk fra civilisationen og\n"
	.string "vække den vilde ånd indeni!\p"
	.string "Det er vores vision.$"

Route119_Text_JacksonRegister:
	.string "Jeg håber, du vil give mig en revan-\n"
	.string "che uden at gøre nar af min mang-\n"
	.string "lende viden.$"

Route119_Text_JacksonRematchIntro:
	.string "Jeg vil genfinde mit vilde\n"
	.string "åndedyr ved at være sammen med POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Du har været stærk!$"

Route119_Text_JacksonPostRematch:
	.string "Tro på dine POKéMON.\n"
	.string "Tro på dig selv.\p"
	.string "Vejen vil afsløre sig for dig.$"

Route119_Text_CatherineIntro:
	.string "Nå, ser man på det.\p"
	.string "For en eventyrer som dig,\n"
	.string "rejser du ualmindeligt let.$"

Route119_Text_CatherineDefeat:
	.string "Ulykker sker, når du ikke er\n"
	.string "forberedt!$"

Route119_Text_CatherinePostBattle:
	.string "Du rejser let, men du har alt, hvad\n"
	.string "du har brug for.\p"
	.string "Du er skarp mentalt\n"
	.string "og fysisk, også.$"

Route119_Text_CatherineRegister:
	.string "Har du en POKéNAV?\n"
	.string "Det er et must-have værktøj for enhver TRÆNER.\p"
	.string "Åh, du har en!\n"
	.string "Så lad os registrere hinanden, så!$"

Route119_Text_CatherineRematchIntro:
	.string "Hvordan går det med din rejse med POKéMON\n"
	.string "?\p$"

Route119_Text_CatherineRematchDefeat:
	.string "Jeg mangler stadig noget…$"

Route119_Text_CatherinePostRematch:
	.string "På samme måde som dig, som en\n"
	.string "TRÆNER, stoler på dine POKéMON,\n"
	.string "stoler dine POKéMON på dig.$"

Route119_Text_HughIntro:
	.string "Den enorme himmel rummer ubegrænset\n"
	.string "mulighed!\p"
	.string "Intet kan sammenlignes med den rene\n"
	.string "spænding ved at flyve!$"

Route119_Text_HughDefeat:
	.string "Nede og ude!$"

Route119_Text_HughPostBattle:
	.string "Mine FUGL POKéMON har gjort mine\n"
	.string "drømme om at flyve til virkelighed!$"

Route119_Text_PhilIntro:
	.string "Jeg vil vise dig mit sande potentiale\n"
	.string "og min FUGLE POKéMON!$"

Route119_Text_PhilDefeat:
	.string "Vi manglede potentiale…$"

Route119_Text_PhilPostBattle:
	.string "Siden jeg var en lille knægt, har jeg altid\n"
	.string "beundret FUGLE POKéMON…$"

Route119_Text_YasuIntro:
	.string "At lure i skyggerne og leve i\n"
	.string "mørket… Det er min skæbne.\p"
	.string "Jeg dukker op for at udfordre dig!$"

Route119_Text_YasuDefeat:
	.string "Jeg giver op!$"

Route119_Text_YasuPostBattle:
	.string "Dem, der er besejret i kamp, trækker sig\n"
	.string "stille tilbage ind i skyggerne.\l"
	.string "Det er også skæbnen…$"

Route119_Text_TakashiIntro:
	.string "Hvis du ikke er på vagt,\n"
	.string "venter der lidt smerte på dig!$"

Route119_Text_TakashiDefeat:
	.string "Du er overraskende god!$"

Route119_Text_TakashiPostBattle:
	.string "Mit overraskelsesangreb endte\n"
	.string "i fiasko…$"

Route119_Text_HideoIntro:
	.string "For at skjule et træ, brug en skov!$"

Route119_Text_HideoDefeat:
	.string "Jeg bøjer mig for din overlegenhed.$"

Route119_Text_HideoPostBattle:
	.string "For at skjule et træ, brug en skov!\n"
	.string "For at skjule en POKéMON, brug en POKéMON!\p"
	.string "Der er ingen dyb, skjult betydning\n"
	.string "i det.$" 

Route119_Text_ChrisIntro:
	.string "Du talte til mig…\n"
	.string "Så du vil udfordre mig!\p"
	.string "Selvfølgelig! Jeg vil prøve de POKéMON, jeg har fanget\n"
	.string "mens jeg surfede!$"

Route119_Text_ChrisDefeat:
	.string "Jeg har ikke en anelse om, hvad der\n"
	.string "skal til for at vinde.$"

Route119_Text_ChrisPostBattle:
	.string "Tag på en SURF på min POKéMON…\p"
	.string "Og fisk derefter fra dens ryg…\p"
	.string "Det er et ubeskriveligt luksuriøst øjeblik!$"

Route119_Text_FabianIntro:
	.string "Slå mig med en powerakkord!\n"
	.string "Sejren er min!\l"
	.string "Det er vores tid til at skinne, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "Du viste mig, hvem der er chefen!\n"
	.string "Vi bliver nødt til at tage tabet, oh nej!$"

Route119_Text_FabianPostBattle:
	.string "Slå mig med endnu et power-akord!\n"
	.string "Lad mig være i fred!\l"
	.string "Din sejr skal du sone!$"

Route119_Text_DaytonIntro:
	.string "Hohoho!\n"
	.string "Jeg kan godt lide børne-TRÆNERE!\l"
	.string "Lad os få en god kamp!$"

Route119_Text_DaytonDefeat:
	.string "Du er ret fantastisk!\n"
	.string "Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho!\n"
	.string "Jeg vil prøve at efterligne energien fra unge\l"
	.string "TRÆNERE som dig!$"

Route119_Text_RachelIntro:
	.string "Uanset hvor jeg er og hvornår det er,\n"
	.string "har jeg altid min parasol i hånden.$"

Route119_Text_RachelDefeat:
	.string "Åh, men…\n"
	.string "Det er ikke fair.$"

Route119_Text_RachelPostBattle:
	.string "Du spørger om min parasol er tung?\n"
	.string "Din RYGSÆK er fyldt med mere skrammel\l"
	.string "end jeg nogensinde bærer rundt på.$"

Route120_Text_ColinIntro:
	.string "Har du nogen angreb, der kan ramme\n"
	.string "en flyvende POKéMON?\p$"

Route120_Text_ColinDefeat:
	.string "Du fløj over mig!$"

Route120_Text_ColinPostBattle:
	.string "Flyv-funktionen er praktisk,\n"
	.string "synes du ikke?\p"
	.string "Når POKéMON-en flyver,\n"
	.string "kan næsten ingen angreb ramme den.$"  

Route120_Text_RobertIntro:
	.string "Mine POKéMON er stærk!\n"
	.string "Hvad med din?$"

Route120_Text_RobertDefeat:
	.string "Dine POKéMON var stærkere…$"

Route120_Text_RobertPostBattle:
	.string "En POKéMON, der vokser støt, er en\n"
	.string "du kan regne med.$"

Route120_Text_RobertRegister:
	.string "Du kan regnes med at blive bedre.\n"
	.string "Jeg vil gerne registrere dig i min POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "En POKéMON der vokser støt, er en\n"
	.string "du kan regne med.$"

Route120_Text_RobertRematchDefeat:
	.string "Dine POKéMON er virkelig stærke.$"

Route120_Text_RobertPostRematch:
	.string "Mine POKéMON bliver stærkere.\n"
	.string "Jeg bliver nødt til at blive stærkere også.$"

Route120_Text_LorenzoIntro:
	.string "Jeg vil tjekke dine POKéMON og se om\n"
	.string "de er klar til udendørslivet.$"

Route120_Text_LorenzoDefeat:
	.string "Med POKéMON så stærke, er du\n"
	.string "slet ikke i fare for at få brug for redning!$"

Route120_Text_LorenzoPostBattle:
	.string "At rejse hvor dit hjerte ønsker\n"
	.string "med POKéMON…\l"
	.string "Det er glæden ved at være en TRÆNER.$"

Route120_Text_JennaIntro:
	.string "Hvordan står det til med din fysisk\n"
	.string "fitness?\n"
	.string "Hvis du ikke er i form, kan du få det\n"
	.string "svært i kritiske situationer.$"

Route120_Text_JennaDefeat:
	.string "Jeg er helt i form, men…$"

Route120_Text_JennaPostBattle:
	.string "Fitness træning er en del af min rutine.\n"
	.string "Jeg løber altid med mine POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle?$"

Route120_Text_JeffreyDefeat:
	.string "Tabte den…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…$"  

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Har du en POKéNAV…?\p$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle again?$"

Route120_Text_JeffreyRematchDefeat:
	.string "Jeg tabte igen…$"


Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Jeg vil prøve hårdere…\l"
	.string "For min dyrebare INSEKT POKéMON…$"

Route120_Text_JenniferIntro:
	.string "POKéMON har mange specielle evner.\n"
	.string "Hvis du vil blive en topklasse\n"
	.string "TRÆNER, så lær om dem.$"

Route120_Text_JenniferDefeat:
	.string "Du tænker tydeligvis.$"

Route120_Text_JenniferPostBattle:
	.string "De specielle evner hos POKéMON\n"
	.string "vil ændre kampstil.$"

Route120_Text_ChipIntro:
	.string "Hvem mon du er?\p"
	.string "Er du måske på jagt efter gamle\n"
	.string "ruiner, som rygtet siger muligvis\l"
	.string "eksisterer ifølge legenden?$"

Route120_Text_ChipDefeat:
	.string "Hvad et pinligt tilbageslag…$"

Route120_Text_ChipPostBattle:
	.string "Den kæmpestore sten… Jeg vil gerne\n"
	.string "tro, at den faktisk gemmer på gamle\l"
	.string "ruiner. Men jeg kan ikke se nogen indgang.$"

Route120_Text_ClarissaIntro:
	.string "Hvorfor bærer jeg denne parasol?\p"
	.string "Jeg vil fortælle dig det, hvis du kan vinde imod mig.$"

Route120_Text_ClarissaDefeat:
	.string "En parasol kan ikke beskytte mod POKéMON\n"
	.string "angreb…$"

Route120_Text_ClarissaPostBattle:
	.string "Jeg tror ikke stærkt sollys er godt\n"
	.string "for mine POKéMON.\n"
	.string "Så jeg beskytter dem med min parasol.$"

Route120_Text_AngelicaIntro:
	.string "Mig, POKéMON, og min paraply…\p"
	.string "Hvis en af dem mangler,\n"
	.string "vil skønhedens billede blive ødelagt.$"

Route120_Text_AngelicaDefeat:
	.string "Du har fuldstændig ødelagt min skønhed…$"

Route120_Text_AngelicaPostBattle:
	.string "En parasol ville slet ikke klæde dig.\p"
	.string "Ja, noget som dette ville kun\n"
	.string "være i vejen for dig.$"

Route120_Text_KeigoIntro:
	.string "Jeg vil adoptere bevægelserne fra POKéMON\n"
	.string "og skabe nye ninja-teknikker.$"

Route120_Text_KeigoDefeat:
	.string "Oprettelsen af nye ninja teknikker\n"
	.string "er blot en fjern drøm…$"

Route120_Text_KeigoPostBattle:
	.string "Måske skulle jeg blive lærling under\n"
	.string "en ninja sensei.$"

Route120_Text_RileyIntro:
	.string "Vi ninja gemmer os under vores\n"
	.string "camouflagekapper.\l"
	.string "Jeg vedder på, at du ikke vidste, hvor jeg var!$"

Route120_Text_RileyDefeat:
	.string "Jeg tabte!\n"
	.string "Jeg burde kamuflere min skam!$"

Route120_Text_RileyPostBattle:
	.string "Vores kamuflagekapper er alle\n"
	.string "håndlavede.$"

Route120_Text_CallieIntro:
	.string "Hvis du ikke er opmærksom, \n"
	.string "kan du komme til skade!$"

Route120_Text_CallieDefeat:
	.string "Av!\n"
	.string "Det var mig, der blev såret.$"

Route120_Text_CalliePostBattle:
	.string "Jeg spekulerer… Skal jeg udvikle min POKéMON?\n"
	.string "De er søde, som de er, dog.$"

Route120_Text_LeonelIntro:
	.string "Dine POKéMON i teamet…\n"
	.string "Har du forskellige typer?$"

Route120_Text_LeonelDefeat:
	.string "Jeg har set din politik i aktion!$"

Route120_Text_LeonelPostBattle:
	.string "Jeg synes, det er sejt, du er så stærk\n"
	.string "og kæmper med din favorit POKéMON.$"

Route121_Text_VanessaIntro:
	.string "Vil du lege med mine skønne og\n"
	.string "smukke POKéMON? \p$"

Route121_Text_VanessaDefeat:
	.string "Det var ikke det, jeg mente!$"

Route121_Text_VanessaPostBattle:
	.string "Jeg skal til en KONKURRENCE i LILYCOVE.\p"
	.string "Mine POKéMON burde ikke have nogen\n"
	.string "problemer med at feje MESTERKLASSEN.$"

Route121_Text_WalterIntro:
	.string "Med mine POKéMON er jeg rejst\n"
	.string "til verdens fire hjørner.\p"
	.string "Man kunne sige, at jeg har lidt\n"
	.string "selvtillid i mine evner.$"

Route121_Text_WalterDefeat:
	.string "Åh, godt spillet.$"

Route121_Text_WalterPostBattle:
	.string "Jeg vil gerne cirkulere\n\nglobus endnu en gang med min POKéMON.$"

Route121_Text_WalterRegister:
	.string "Din POKéMON-færdighed er bemærkelsesværdig.\n"
	.string "Lad mig registrere dig som et minde.$"

Route121_Text_WalterRematchIntro:
	.string "Med mine POKéMON har jeg rejst\n"
	.string "til verdens fire hjørner.\p"
	.string "Man kunne sige, jeg er ret sikker\n"
	.string "på mine evner.$"

Route121_Text_WalterRematchDefeat:
	.string "Åh, godt spillet.$"

Route121_Text_WalterPostRematch:
	.string "Dine POKéMON og dig…\p"
	.string "Jeres kunnen sammen vil blive\n"
	.string "betraget som stærkt, selv i udlandet.$"

Route121_Text_TammyIntro:
	.string "Der er kræfter ud over vores\n"
	.string "forståelse i verden…$"

Route121_Text_TammyDefeat:
	.string "Jeg har tabt…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "Der er en mystisk kraft på\n"
	.string "spil der…$"

Route121_Text_KateIntro:
	.string "KATE: Sammen er vi frygtløse!\n"
	.string "Vi vil vise, hvor seje vi er!$"

Route121_Text_KateDefeat:
	.string "KATE: Jeg ødelagde det foran min\n"
	.string "juniorstudiepartner…$"

Route121_Text_KatePostBattle:
	.string "KATE: Når nogen stoler på mig,\n"
	.string "får jeg lyst til at se sej ud\n"
	.string "foran dem…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: Hvis du kun har én POKéMON,\n"
	.string "kan vi ikke kæmpe imod dig.\p"
	.string "Det ville være mobning.$"

Route121_Text_JoyIntro:
	.string "JOY: Sammen er vi frygtløse!\n"
	.string "Vi vil vise, hvor seje vi er!$"

Route121_Text_JoyDefeat:
	.string "JOY: Undskyld mig, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, jeg bliver nødt til at træne med KATE,\n"
	.string "min ældre studiepartner, igen.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: Du skal have mindst to POKéMON\n"
	.string "hvis du vil udfordre os!$"

Route121_Text_JessicaIntro:
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "Åh, hvordan tør du!\n"
	.string "Tag det ikke så alvorligt!$"

Route121_Text_JessicaPostBattle:
	.string "Måske tager jeg ud og fanger flere \n"
	.string "POKéMON i SAFARIEN.$"

Route121_Text_JessicaRegister:
	.string "Jeg tog det roligt med dig denne gang!\n"
	.string "Det bliver ikke på samme måde næste gang!$"

Route121_Text_JessicaRematchIntro:
    .string "Mine kære POKéMON er vokset!\n"
    .string "Tag et godt kig!$"

Route121_Text_JessicaRematchDefeat:
	.string "Åh, hvordan tør du!\n"
	.string "Du vil stadig ikke tage det roligt!$"

Route121_Text_JessicaPostRematch:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_CristinIntro:
	.string "Jeg har denne rutine.\n"
	.string "Besejr fem TRÆNERE om dagen.\l"
	.string "Gæt hvad? Du er nummer fem!$"

Route121_Text_CristinDefeat:
	.string "Nej!\n"
	.string "Du er grusom!$"

Route121_Text_CristinPostBattle:
	.string "Jeg havde ikke regnet med at tabe så let…\n"
	.string "Jeg vinder næste gang!$"

Route121_Text_CristinRegister:
	.string "Det var total ydmygelse!\n"
	.string "Jeg vil ikke glemme dig…\l"
	.string "Aflever din POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "Jeg har denne nye rutine.\n"
	.string "Besejr ti TRÆNERE om dagen.\l"
	.string "Gæt hvad? Du er nummer ti!$"

Route121_Text_CristinRematchDefeat:
	.string "Vent! Det er ulækkert!\n"
	.string "Jeg kræver en revanchepulje!$"

Route121_Text_CristinPostRematch:
	.string "En modstander jeg bare ikke kan slå…\n"
	.string "Snøft…\l"
	.string "Jeg kan ikke tro, at dette sker…$"

Route121_Text_CaleIntro:
	.string "Kan du ikke se, at jeg har alt dette\n"
	.string "grej med mig?\p"
	.string "På trods af det insisterer du stadig\n"
	.string "på, at vi skal kæmpe?$"

Route121_Text_CaleDefeat:
	.string "Selvfølgelig tabte jeg!\n"
	.string "Jeg holder ting i begge hænder!$"

Route121_Text_CalePostBattle:
	.string "Jeg har købt alt for meget\n"
	.string "ting hos LILYCOVE DEPT. STORE.\p"
	.string "Det er oppe ad vejen herfra.\n"
	.string "Jeg ønsker, jeg havde en RYGSÆK som din.$"

Route121_Text_MylesIntro:
	.string "Der er intet, jeg elsker mere end\n"
	.string "at kigge på andres POKéMON!$"

Route121_Text_MylesDefeat:
	.string "Super awesome!$"

Route121_Text_MylesPostBattle:
	.string "De er fantastiske, dine POKéMON!\n"
	.string "Hvordan opdrætter du dem?$"

Route121_Text_PatIntro:
	.string "Jeg vil have alle til at se de POKéMON,\n"
	.string "jeg har opfostret!$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Fantastisk!$"

Route121_Text_PatPostBattle:
	.string "Jeg opdrætter alle POKéMON med den samme\n"
	.string "kærlighed og omsorg - jeg vælger ingen favoritter.$"

Route121_Text_MarcelIntro:
	.string "Mine POKéMON har aldrig smagt nederlag!\n"
	.string "På deres næste sejr, vil jeg tilmelde dem\l"
	.string "i KONKURRENCER.$"

Route121_Text_MarcelDefeat:
	.string "Åh nej, hvad skete der lige her?$"

Route121_Text_MarcelPostBattle:
	.string "Jeg må nok træne min bande lidt\nmere, før vi deltager i en KONKURRENCE.$"

Route123_Text_WendyIntro:
	.string "Vil du finde ud af, hvor stærk du er?\n"
	.string "Jeg vil være testen!$"

Route123_Text_WendyDefeat:
	.string "Du bestod med flyvende farver!$"

Route123_Text_WendyPostBattle:
	.string "For at kunne slå mig…\n"
	.string "Din styrke er fantastisk!$"

Route123_Text_BraxtonIntro:
	.string "Du ser ud til at have en stor samling\n"
	.string "af GYM BADGES.\p"
	.string " Lad mig se, om du rent faktisk er værdig\n"
	.string "til disse BADGES!$"  

Route123_Text_BraxtonDefeat:
	.string "Åh, du er helt klart værdig!$"

Route123_Text_BraxtonPostBattle:
	.string "Du gjorde dine MÆRKER stolte i den\n"
	.string "duel!$"

Route123_Text_VioletIntro:
	.string "De siger, at gode tider er fyldt\n"
	.string "med gode dufte.$"

Route123_Text_VioletDefeat:
	.string "Åh…\n"
	.string "Jeg kan lugte den bitre duft af elendighed…$"

Route123_Text_VioletPostBattle:
	.string "BÆRETS mesteres have er fyldt\n"
	.string "med opmuntrende dufte.$"

Route123_Text_CameronIntro:
    .string "At være en psykisk er om viljestyrke.\p"
    .string "Jeg har villet mig til ikke at tabe til nogen.\n"
    .string "Det gør mig stærk!$"

Route123_Text_CameronDefeat:
	.string "Jeg føler mig ked af det…$"

Route123_Text_CameronPostBattle:
	.string "At være psykisk handler om viljestyrke.\n"
	.string "Jeg troede ikke, jeg ville tabe til dig…$"

Route123_Text_CameronRegister:
	.string "Jeg mærker det!\n"
	.string "Du og jeg skal kæmpe igen!\l"
	.string "Jeg kan ikke sige om jeg vil vinde, dog…\p"
	.string "Lad os se din POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Jeg har overbevist mig selv om, at\n"
	.string "jeg ikke vil tabe mere. Det gør mig stærk!$"

Route123_Text_CameronRematchDefeat:
	.string "Jeg føler mig trist…$"

Route123_Text_CameronPostRematch:
	.string "Jeg burde træne ved MT. PYRE…\n"
	.string "Jeg vil aldrig slå dig på denne måde…$"

Route123_Text_JackiIntro:
    .string "Vær ikke for glad, hvis din POKéMON\n"
    .string "udvikler psykiske evner.\p"
    .string "Du skal forfine de evner for at\n"
    .string "gøre dem virkelig nyttige.$"

Route123_Text_JackiDefeat:
	.string "Overvældet!$"

Route123_Text_JackiPostBattle:
	.string "Vi har alle psykiske evner.\n"
	.string "Vi har bare glemt, hvordan vi skal bruge dem.$"

Route123_Text_JackiRegister:
	.string "Jeg vil gerne stille op mod dig igen.\n"
	.string "Er det okay med dig?\p$"

Route123_Text_JackiRematchIntro:
	.string "Har du vækket de psykiske kræfter\n"
	.string "inden i dig?$"

Route123_Text_JackiRematchDefeat:
	.string "Forbløffende!$"

Route123_Text_JackiPostRematch:
	.string "Din kraft med POKéMON…\n"
	.string "Det kunne også være en psykisk kraft.$"

Route123_Text_MiuIntro:
	.string "MIU: Hej, TRÆNER. Jeg håber din\n"
	.string "POKéMON ikke græder, når de taber.$"

Route123_Text_MiuDefeat:
	.string "MIU: Øh-øj, vi tabte.$"

Route123_Text_MiuPostBattle:
    .string "MIU: TRÆNER, dine POKéMON er\n"
    .string "stærke, fordi I er venner.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: Det er ikke sjovt at kæmpe, hvis du\n"
	.string "ikke har to POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay!\n"
	.string "Vi slår TRÆNERENS POKéMON!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Ups, vi tabte.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Hvorfor er du så stærk?\n"
	.string "Vi har aldrig tabt før.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: Det er ikke sjovt at kæmpe, hvis du\n"
	.string "ikke har to POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Vil din POKéMON sove?\p$"

Route123_Text_KindraDefeat:
	.string "Sprudlende af vitalitet…$"

Route123_Text_KindraPostBattle:
	.string "MOUNT PYRE…\n"
	.string "Hvor POKéMON's ånder hviler…\p"
	.string "Der må være en kraft, der\n"
	.string "beroliger ånder…$"

Route123_Text_FernandoIntro:
	.string "Jeg slukker lyset mens\n"
	.string "jeg river igennem denne melodi!$"

Route123_Text_FernandoDefeat:
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_FernandoPostBattle:
	.string "Du er som en klippe.\n"
	.string "Jeg kunne godt tænke mig at skrive en sang om dig.$"

Route123_Text_FernandoRegister:
	.string "Næste gang, lyt til\n"
	.string "hele melodien, ik'?$"

Route123_Text_FernandoRematchIntro:
	.string "I dag er dagen, hvor jeg vil gøre det!\n"
	.string "Jeg slukker lyset, før jeg er færdig\l"
	.string "med at synge min sang!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "Jeg troede, du ville være så\n"
	.string "forhekset af min melodi, at du$"


Route123_Text_DavisIntro:
    .string "Det her er min seje INSEKT POKéMON!\n"
    .string "Min storebror købte den til mig.$" 

Route123_Text_DavisDefeat:
	.string "Iiiih!\n"
	.string "Du store skurk!$"

Route123_Text_DavisPostBattle:
	.string "Sig ikke til min bror, at jeg tabte.\n"
	.string "Du er nødt til at holde det hemmeligt!$"

Route123_Text_JazmynIntro:
    .string "Min selvtillid vil få et boost ved\n"
    .string "at slå en tydeligt stærk person!\p$"

Route123_Text_JazmynDefeat:
	.string "Der røg min selvtillid…$"

Route123_Text_JazmynPostBattle:
	.string "Man siger, at man ikke kan bedømme\n"
	.string "en person ud fra deres udseende.\p"
	.string "Men ofte lyver udseendet ikke…$"

Route123_Text_FrederickIntro:
	.string "Hej, barn!\n"
	.string "Har du lidt tid til overs?$"

Route123_Text_FrederickDefeat:
	.string "Åh, et mægtigt dygtigt barn!\n"
	.string " Lad mig bidrage til din lommepenge.$"

Route123_Text_FrederickPostBattle:
	.string "Bidrage til din lommepenge?\n"
	.string "Var præmiepengene ikke nok?$"

Route123_Text_AlbertoIntro:
	.string "Jeg bliver nødt til at fortælle dig, FUGL\n"
	.string "POKéMON er min besættelse!\p"
	.string "Fugle er seje!\n"
	.string "De er de bedste!$"

Route123_Text_AlbertoDefeat:
	.string "Selv i nederlag er FUGLE POKéMON seje!$"

Route123_Text_AlbertoPostBattle:
	.string "Jeg samler BIRD POKéMON-fjer, der\n"
	.string "spredes under kampe.\p"
	.string "Jeg vil lave en hat med\n"
	.string "BIRD POKéMON-fjer.$"

Route123_Text_EdIntro:
	.string "Når der ikke er NOGEN TRÆNERE i nærheden,\n"
	.string "lader jeg mine POKéMON kæmpe mod hinanden.\l"
	.string "Jeg ser på dem.$"

Route123_Text_EdDefeat:
	.string "Jeg er lidt vild med din POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, Jeg snupper dine kamp-idéer!\n"
	.string "Jeg tror de vil gøre mig bedre.$"

Route123_Text_JonasIntro:
	.string "Jeg ligger på lur, og en TRÆNER\n"
	.string "er landet i mit fælde!$"

Route123_Text_JonasDefeat:
	.string "Hvis du ikke taber, hvordan skal jeg\n"
	.string "så have det sjovt med at spille ninja?$"

Route123_Text_JonasPostBattle:
	.string "Jeg vil overraske en svagere udseende\n"
	.string "TRÆNER næste gang.$"

Route123_Text_KayleyIntro:
	.string "Jeg har lige købt denne parasol.\n"
	.string "Min sødme burde være steget med en tredjedel!$"

Route123_Text_KayleyDefeat:
	.string "Du er bedre end mig med cirka\n"
	.string "fem gange!$"

Route123_Text_KayleyPostBattle:
	.string "At bruge accessories effektivt er\n"
	.string "hemmeligheden bag moden.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON,\n"
	.string "I can serve as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "Jeg har mistet mit fodfæste i kampen!$"

Route124_Text_SpencerPostBattle:
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_RolandIntro:
	.string "Hm! Du rider på en POKéMON\n"
	.string "i stedet for at svømme selv…\p"
	.string "Jeg er misundelig!$"

Route124_Text_RolandDefeat:
	.string "Åh!\n"
	.string "Jeg kan ikke…$"

Route124_Text_RolandPostBattle:
	.string "Jeg fryser…\n"
	.string "Jeg har været i vandet for længe…\p"
	.string "Jeg ville ønske, jeg kunne ride på en POKéMON som dig…$"

Route124_Text_JennyIntro:
	.string "Hvis du bare flyder i havet på denne\n"
	.string "måde, POKéMON kommer for at lege.$"

Route124_Text_JennyDefeat:
	.string "Åh, pokkers.\n"
	.string "Jeg har tabt.$"

Route124_Text_JennyPostBattle:
	.string "Mens jeg svømmede, lagde jeg mærke\n"
	.string "til, at nogle POKéMON angriber, og\n"
	.string "andre bare ser på.\pJeg gætter på,\n"
	.string "at POKéMON har deres egne\n"
	.string "personligheder.$"

Route124_Text_JennyRegister:
	.string "Det er kun på en impuls, men måske får jeg\n"
	.string "dig til at registrere mig i din POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Hvis du bare lige driver rundt på havet på denne måde,\n"
	.string "TRÆNERE udfordrer dig!$"

Route124_Text_JennyRematchDefeat:
	.string "Det er mærkeligt…\n"
	.string "Jeg tabte igen…$"

Route124_Text_JennyPostRematch:
	.string "Det her har ikke noget at gøre med noget,\n"
	.string "men måske besøger jeg TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "Jeg bliver lidt træt af at svømme…\n"
	.string "Hvad med en kamp?\p$"

Route124_Text_GraceDefeat:
	.string "Jeg havde ingen idé om, at du var\n"
	.string "så stærk!$"

Route124_Text_GracePostBattle:
	.string "Alt det arbejde, du har lagt i, må\n"
	.string "have gjort dig så stærk.$"

Route124_Text_ChadIntro:
	.string "Haha… Jeg dykker dybt under vandet\n"
	.string "for at gå dybt under cover.\l"
	.string "Det er her, jeg virkelig skinner!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n" 
	.string "Jeg synker…$"

Route124_Text_ChadPostBattle:
	.string "Jeg har det fra pålidelig kilde,\n"
	.string "at der er et DYKKEsted omkring\n"
	.string "her.\p"
	.string "Det giver mig lyst til at dykke\n"
	.string "dybt igen…$"

Route124_Text_LilaIntro:
	.string "LILA: Suk…\p"
	.string "Her er jeg i havet, men hvem er med mig?\n"
	.string "Min lillebror!\p"
	.string "Lad os kæmpe så jeg ikke behøver at\n"
	.string "fokusere på det!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! Det er din skyld, at vi tabte!\n"
	.string "Du får problemer senere!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Suk…\p"
	.string "Hvis det bare ikke var min lille\n"
	.string "bror ved siden af mig, men en sød kæreste…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: Du planlægger at udfordre os?\n"
	.string "Ikke medmindre du har to POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: Min store søster er sej til POKéMON!\p"
	.string "Græd ikke, når du taber!$"

Route124_Text_RoyDefeat:
	.string "ROY: Åh-åh…\n"
	.string "Min store søster vil skælde mig ud…$"

Route124_Text_RoyPostBattle:
	.string "ROY: Min store søster er virkelig\n"
	.string "skræmmende når hun bliver vred.\p"
	.string "Det er derfor, hun ikke har en\n"
	.string "kæreste.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Vil du kæmpe med os igen?\n"
	.string "Men tag det roligt næste gang, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Vil du kæmpe mod os?\n"
	.string "Tag to POKéMON med, så.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Suk…\p"
	.string "Her er jeg i havet, men hvem er med mig?\n"
	.string "Min lille bror!\p"
	.string "Åh, hej, det var længe siden. Lad os kæmpe\n"
	.string "så jeg ikke behøver tænke for meget på tingene!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "Det er din skyld, vi tabte igen!\p"
	.string "Vi har en træningssession senere!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Suk…\p"
	.string "Hvis jeg havde en sød kæreste, ville vi\n"
	.string "slå alle med skønne kombinationer…$"  

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: Planlægger du at kæmpe mod os?\n"
	.string "Ikke medmindre du har to POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: Hvis vi taber, får jeg ballade.\n"
	.string "Jeg vil gå fuldstændig amok!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "Min store søster vil skælde mig ud igen.$"

Route124_Text_RoyPostRematch:
	.string "ROY: Min store søster er virkelig "
	.string "skræmmende, når hun bliver vred.\p"
	.string "Hun kommer til at lade mig træne "
	.string "rigtig hårdt med POKéMON senere…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Vil du kæmpe mod os?\n"
	.string "Tag to POKéMON med så.$"

Route124_Text_DeclanIntro:
	.string "Her står jeg og svømmer helt alene\n"
	.string "på dette store, smukke hav.\p"
	.string "Der er ingen anden måde at sige\n"
	.string "det på.\n"
	.string "Det her er ynkeligt!$"

Route124_Text_DeclanDefeat:
	.string "Jeg føler mig blå.\n"
	.string "Blå som himlen…$" 

Route124_Text_DeclanPostBattle:
	.string "Jeg burde snakke med dame-SWIMMERS\n"
	.string "og invitere dem med på en lang svømmetur.$"

Route124_Text_IsabellaIntro:
	.string "Jeg taber ikke til nogen\n"
	.string "surftræner.$"

Route124_Text_IsabellaDefeat:
	.string "Jeg har kun sved i øjnene!\n"
	.string "Jeg græder ikke!$"

Route124_Text_IsabellaPostBattle:
	.string "Du kan finde smukke farvede styk-\n"
	.string "ker af ting her omkring.$"

Route125_Text_NolenIntro:
	.string "Jeg hørte dig nærme dig, så jeg \n"
	.string "blev hængende for dig!$"

Route125_Text_NolenDefeat:
	.string "Jeg giver op!$"

Route125_Text_NolenPostBattle:
	.string "Lyden rejser hurtigere i vand end\n"
	.string "gennem luft.$"

Route125_Text_StanIntro:
	.string "Hej, du dér!\n"
	.string "Tjek mine seje POKéMON!$"

Route125_Text_StanDefeat:
	.string "Jeg tabte…$"

Route125_Text_StanPostBattle:
	.string "Jeg blev blæst væk af HORSEAs charme,\n"
	.string "så begyndte jeg også at svømme.$"

Route125_Text_TanyaIntro:
	.string "Jeg er træt af at svømme.\n"
	.string "Er du klar til at kæmpe med mig?$"

Route125_Text_TanyaDefeat:
	.string "Du er for meget!$"

Route125_Text_TanyaPostBattle:
	.string "Puha…\n"
	.string "Hvilken vej er det til MOSSDEEP CITY?\p$"

Route125_Text_SharonIntro:
	.string "Hvordan vil du tage kampen op\n"
	.string "mod de VAND-type POKéMON, jeg opdrættede?$"

Route125_Text_SharonDefeat:
	.string "Tabte det…$"

Route125_Text_SharonPostBattle:
	.string "Din kraft… Du er the real deal.\n"
	.string "Jeg er imponeret!$"

Route125_Text_ErnestIntro:
	.string "Hej med dig! Jeg er en sej og stærk SØMAND.\n"
	.string "Jeg har sejlet på verdens have!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "Jeg kunne ikke vinde!$"

Route125_Text_ErnestPostBattle:
	.string "Tidevandet ebber og flyder inde i\n"
	.string "SKOVLHULEN.\p"
	.string "Forresten, der er cirka seks timer fra\n"
	.string "højvande til lavvande. Vidste du det?$"

Route125_Text_ErnestRegister:
	.string "Registrer mig i din POKéNAV,\n"
	.string "og jeg vil fortælle dig noget godt.$"

Route125_Text_ErnestRematchIntro:
	.string "Det er på høje tid, jeg får min hævn\n"
	.string "på dig! Kom nu, vi skal kæmpe!$"

Route125_Text_ErnestRematchDefeat:
	.string "Jeg kunne ikke vinde!\n"
	.string "Jeg kunne simpelthen ikke vinde!$"

Route125_Text_ErnestRematchPostBattle:
	.string "HULEHULEN…\p"
	.string "Der er steder, du kan og ikke kan\n"
	.string "komme til afhængigt af ebbe og\n"
	.string "flod.\p"
	.string "Forresten, det tager cirka seks\n"
	.string "timer fra højvande til lavvande.\n"
	.string "Husk det!$"

Route125_Text_KimIntro:
	.string "KIM: En sjov gammel mand bor i\n"
	.string "SHOAL CAVE. Nogen fortalte mig.\l"
	.string "Skal du også besøge ham?$"

Route125_Text_KimDefeat:
	.string "KIM: Jeg troede, at vi ville vinde.$"

Route125_Text_KimPostBattle:
	.string "KIM: En sjov gammel mand bor i\n"
	.string "SKALHULEHULE, gør han ikke?\p"
	.string "Lad os gå besøge ham, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: Nej, nej, nej! Du skal bruge to \n"
	.string "POKéMON, ellers dur det bare ikke!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, kan du fortælle mig, hvad vi leder efter herude?\p$"

Route125_Text_IrisDefeat:
	.string "IRIS: Åh, vi kom lidt tæt på.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, skal vi virkelig ind i\n"
	.string "SKJULECAVE?\n"
	.string "Vi bliver helt våde.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Åh, vi kunne aldrig, nogensinde\n"
	.string "gøre noget som en 2-mod-1 kamp.$"

Route125_Text_PresleyIntro:
	.string "Hvorfor ville en FUGLEOPDRÆTTER som mig\n"
	.string "komme ud til havet?$"

Route125_Text_PresleyDefeat:
    .string "Okay.\n"
    .string "Jeg vil fortælle dig hvorfor jeg er her.$"

Route125_Text_PresleyPostBattle:
	.string "Jeg lagde en besked i en flaske og\n"
	.string "sendte den ud til havs.\p"
	.string "Jeg er sikker på, at en PIGE\n"
	.string "SVOEMMER vil finde den!$"

Route125_Text_AuronIntro:
	.string "Hey! Var det dig, der smed skrald\n"
	.string "i havet?$"

Route125_Text_AuronDefeat:
    .string "Åh, du kastede ikke affald i\n"
    .string "havet.$"

Route125_Text_AuronPostBattle:
	.string "Jeg fandt en grim flaske der drev\n"
	.string "i bølgerne tidligere.\p"
	.string "Det gør mig vred, at nogen ville\n"
	.string "forurene havet!$"

Route126_Text_BarryIntro:
	.string "At svømme er en fuld kropstræning!\n"
	.string "Du bliver fit!$"

Route126_Text_BarryDefeat:
	.string "Jeg indrømmer det!\n"
	.string "Du vinder!$"

Route126_Text_BarryPostBattle:
	.string "Takket være min daglige svømmetur…\n"
	.string "Se! Nyd dette fysik!$"

Route126_Text_DeanIntro:
    .string "Denne høje hvide bjerg af sten\n"
    .string "er SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "Jeg blev slået?$"

Route126_Text_DeanPostBattle:
	.string "Jeg kan ikke finde indgangen til\n"
	.string "SOOTOPOLIS. Hvor mon den er?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "Jeg er en havfrue!$"

Route126_Text_NikkiDefeat:
	.string "Min fantasi sprang som en boble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "Du gav mig øretæver… Jeg vil"
	.string "gerne forsvinde i en bølge af fortvivlelse…$"

Route126_Text_BrendaIntro:
	.string "Hej, ven!\n"
	.string "Vil du kæmpe med mig?$"

Route126_Text_BrendaDefeat:
	.string "Åh, neeeej!$"

Route126_Text_BrendaPostBattle:
	.string "Jeg elsker at lege med POKéMON\n"
	.string "i havet på denne måde!$"

Route126_Text_PabloIntro:
	.string "Tjek lige denne veltrænede krop!\n"
	.string "Jeg er mere trimmet end en SORT BÆLTE!$"

Route126_Text_PabloDefeat:
	.string "Hovsa! For stærk!\n"
	.string "Ikke dårligt! Slet ikke dårligt!$"

Route126_Text_PabloPostBattle:
	.string "At tabe til dig stimulerede mine sanser!\n"
	.string "Jeg vil træne mig selv og POKéMON hårdere!$"

Route126_Text_PabloRegister:
	.string "Ja, du er slet ikke dårlig!\n"
	.string "Jeg vil gerne lære dig bedre at kende!$"

Route126_Text_PabloRematchIntro:
	.string "Tjek lige denne smukke krop!\n"
	.string "Jeg er mere spænstig end en SVØMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Hovsa! Virkelig for stærk!\n"
	.string "Ikke dårligt! Slet ikke dårligt!$"

Route126_Text_PabloPostRematch:
	.string "Jeg vil træne endnu hårdere!\n"
	.string "Du er en fantastisk motivationskilde!\l"
	.string "Du skal komme tilbage igen!$"

Route126_Text_LeonardoIntro:
	.string "Sidste år kunne jeg ikke engang svømme,\n"
	.string "men nu er jeg en rimelig SVØMMER.\p"
	.string "Jeg tror, jeg er i stand til alt nu.$"

Route126_Text_LeonardoDefeat:
	.string "Puha, at blive grådig gjorde\n"
	.string "ikke noget for mig.$"

Route126_Text_LeonardoPostBattle:
	.string "Hvis du øver dig på noget,\n"
	.string "vil du blive bedre til det.\p"
	.string "Du er ung -- vær ikke bange for at\n"
	.string "prøve alle mulige ting!$"

Route126_Text_IsobelIntro:
	.string "Hvis saltvand kommer op i din næse,\n"
	.string "føles det ikke forfærdeligt?$"

Route126_Text_IsobelDefeat:
	.string "Nå, for en kriger du er!\n"
	.string "Plask!$"

Route126_Text_IsobelPostBattle:
	.string "Åh, jeg kom til at synke noget vand!\n"
	.string "Det er bittert! Det er salt!!$"

Route126_Text_SiennaIntro:
	.string "Jeg kaster hele mit hjerte\n"
	.string "ind i det!$"

Route126_Text_SiennaDefeat:
	.string "Du havde mere hjerte!$"

Route126_Text_SiennaPostBattle:
	.string "Jeg skal lige køle ned nu…\n"
	.string "Tror, jeg tager en dyk.$"

Route127_Text_CamdenIntro:
	.string "Jeg kan se det i dit ansigt.\n"
	.string "Du vil udfordre mig.$"

Route127_Text_CamdenDefeat:
	.string "Åh nej, du vandt…$"

Route127_Text_CamdenPostBattle:
	.string "En velspillet kamp får mig til at\n"
	.string "føle mig opfrisket og rolig.$"

Route127_Text_DonnyIntro:
	.string "Har du en rival, som du bare\n"
	.string "hader at tabe imod?\p$"

Route127_Text_DonnyDefeat:
	.string "Åh nej!\n"
	.string "Jeg hader at tabe!$"

Route127_Text_DonnyPostBattle:
	.string "Hvis du har en rival, får du ikke\n"
	.string "følelsen af, at du bliver nødt til\n"
	.string "at blive bedre?$"

Route127_Text_JonahIntro:
	.string "Gennem fiskeri har jeg opnået en\n"
	.string "tilstand af rolig stilhed…\p"
	.string "Vær så venlig at give mig lov til at demonstrere…$"

Route127_Text_JonahDefeat:
	.string "Selvom jeg har tabt, er mit hjerte\n"
	.string "stadig roligt…$"

Route127_Text_JonahPostBattle:
	.string "Det betyder ikke noget, at jeg fanger ingenting.\n"
	.string "Linjen forbliver i vandet…$"

Route127_Text_HenryIntro:
	.string "Ups! Sig ikke at jeg fangede\n"
	.string "en SURFING POKéMON?$"

Route127_Text_HenryDefeat:
	.string "Jeg kan ikke følge med!$"

Route127_Text_HenryPostBattle:
	.string "Det ville være en håndfuld,\n"
	.string "hvis jeg fik fat i dine seje \n"
	.string "POKéMON!$"

Route127_Text_RogerIntro:
	.string "Nå, hej! Dette er en kamp\n"
	.string "mellem en POKéMON-fan og en lystfisker!$"

Route127_Text_RogerDefeat:
	.string "Nej! Mit snøre er helt viklet sammen!\n"
	.string "Festen er forbi!$"

Route127_Text_RogerPostBattle:
	.string "Min fiskestang laver en dans!\n"
	.string "Det roder tango! Hahaha, snor!$"

Route127_Text_AidanIntro:
	.string "FUGLE POKéMON har fremragende syn.\n"
	.string "De opdager bytte fra store højder.$"

Route127_Text_AidanDefeat:
	.string "Puha… Jeg giver op.$"

Route127_Text_AidanPostBattle:
	.string "Der er masser af dykkersteder i\n"
	.string "havet omkring her.\p"
	.string "Du kan se dem tydeligt fra himlen\n"
	.string "på grund af deres mørkere farve.$"

Route127_Text_KojiIntro:
    .string "Løb i dine bare fødder.\n"
    .string "Det vil gøre dine fodsåler seje!$"

Route127_Text_KojiDefeat:
	.string "Av av!\n"
	.string "Jeg fik en sten under en tånegl!$"

Route127_Text_KojiPostBattle:
	.string "At gå barfodet føles fantastisk.\n"
	.string "Men dine LØBESKO er også seje.$"

Route127_Text_KojiRegister:
	.string "Det her er hvad jeg gør ved folk, der slår mig!\n"
	.string "Jeg håber, vi kan gøre det igen.$"

Route127_Text_KojiRematchIntro:
	.string "Jeg løber stadig dagligt i mine bare fødder.\n"
	.string "Mine såler er seje!$"

Route127_Text_KojiRematchDefeat:
	.string "Av av!\n"
	.string "Småsten gravede sig\nind i mine svang!$"

Route127_Text_KojiPostRematch:
	.string "Vil du gå barfodet i et stykke tid?\n"
	.string "Så jeg kan prøve dine LØBESKO?$"

Route127_Text_AthenaIntro:
	.string "Vi burde have en langsom og metodisk\n"
	.string "kamp.$"

Route127_Text_AthenaDefeat:
	.string "Du gav mig ikke chancen for at\n"
	.string "lave strategi.\p$"

Route127_Text_AthenaPostBattle:
	.string "Når jeg er omgivet af det blå hav\n"
	.string "og himmel, føles det, som om tiden går langsommere.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY er stadig langt\n"
	.string "væk…$"

Route128_Text_IsaiahDefeat:
	.string "Min første sejr synes også at\n"
	.string "være langt væk…$"

Route128_Text_IsaiahPostBattle:
	.string "Hele mit liv har handlet om at tabe,\n"
	.string "men jeg vil aldrig give op!$"

Route128_Text_IsaiahRegister:
	.string "Jeg ved, jeg er ikke god nu, men jeg tror\n"
	.string "jeg kan vinde på et tidspunkt.\p"
	.string "Vil du registrere mig i din POKéNAV?$"

Route128_Text_IsaiahRematchIntro:
	.string "Jeg har det stadig godt. Jeg vil fortsætte\n"
	.string "med at svømme til EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Jeg har endnu ikke smagt min første sejr…$"

Route128_Text_IsaiahPostRematch:
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro:
	.string "Du skal svømme, cykle og løbe\n"
	.string "en maraton i en triatlon.\p"
	.string "Det er et hårdt løb, der består\n"
	.string "af tre begivenheder.$"

Route128_Text_KatelynDefeat:
	.string "En POKéMON-kamp er også hård…$"

Route128_Text_KatelynPostBattle:
	.string "Jeg skal cykle næste gang, men…\n"
	.string "Jeg er ved at give op…$"

Route128_Text_KatelynRegister:
	.string "Nå, så kan jeg lige så godt\n"
	.string "gøre det bedste ud af det. Jeg vil\n"
	.string "gerne have en revanche engang.$"

Route128_Text_KatelynRematchIntro:
	.string "En triathlon er lang. Men jeg gætter på,"
	.string " vejen til at blive POKéMON-MESTER\n"
	.string "er også lang og krævende.$"

Route128_Text_KatelynRematchDefeat:
	.string "En POKéMON-kamp er virkelig barsk\n"
	.string "og ubarmhjertig…$"

Route128_Text_KatelynPostRematch:
	.string "Du bør overveje seriøst at tage\n"
	.string "udfordringer på SEJRSVEJEN.$"

Route128_Text_AlexaIntro:
	.string "Vi har arbejdet så hårdt på at forberede\n"
	.string "os til en POKéMON LIGA udfordring…\p"
	.string "Vi kan ikke tabe nu!$"

Route128_Text_AlexaDefeat:
	.string "Åh!\n"
	.string "Hvordan kunne dette ske?!$"

Route128_Text_AlexaPostBattle:
	.string "Efter alt det, jeg har gjort for at komme hertil,\n"
	.string "vil jeg ikke give op efter ét tilbageslag.$"

Route128_Text_RubenIntro:
	.string "Der er ingen stærkere TRÆNER end mig!$"

Route128_Text_RubenDefeat:
	.string "Det kan ikke være rigtigt!$"

Route128_Text_RubenPostBattle:
	.string "Der er sandsynligvis ingen stærkere\n"
	.string "TRÆNER end dig!$"

Route128_Text_WayneIntro:
	.string "Jeg vil gerne besøge EVER GRANDE, så\n"
	.string "jeg fangede mig en POKéMON, der kan\l"
	.string "bruge TORDEN til at bestege vandfaldene.$"

Route128_Text_WayneDefeat:
	.string "Jeg er knust!$"

Route128_Text_WaynePostBattle:
	.string "Åh nej, hvor ærgerligt!\p"
	.string "Min POKéMON kender VANDFALD, men\n"
	.string "jeg har ikke SOOTOPOLIS GYM BADGE!$"

Route128_Text_HarrisonIntro:
	.string "Du ser meget sej ud.\n"
	.string "Mon jeg kan vinde?$"

Route128_Text_HarrisonDefeat:
	.string "Av!\n"
	.string "Jeg gætter på, det var umuligt at vinde.$"

Route128_Text_HarrisonPostBattle:
	.string "Der er seje TRÆNERE i massevis\n"
	.string "omkring EVER GRANDE.\p"
	.string "Tror du, jeg måske er ude\n"
	.string "af min liga?$"

Route128_Text_CarleeIntro:
	.string "Det virker som om sollyset er\n"
	.string "skarpere her.$"

Route128_Text_CarleeDefeat:
	.string "Jeg kunne ikke se så godt på grund\n"
	.string "af solens blænding.$"

Route128_Text_CarleePostBattle:
	.string "Jeg burde snart tage tilbage.\n"
	.string "Jeg skal huske at smøre mig ind i solcreme.$"

Route129_Text_ChaseIntro:
	.string "Det her er min første triatlon.\n"
	.string "Jeg er helt spændt og nervøs!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "Jeg formåede ikke at vinde!$"

Route129_Text_ChasePostBattle:
	.string "Hvis jeg er helt spændt op, kan jeg ikke\n"
	.string "give det hele.$"

Route129_Text_AllisonIntro:
	.string "Jeg er midt i en triatlon,\n"
	.string "men okay, hvorfor kæmper vi ikke?$"

Route129_Text_AllisonDefeat:
	.string "Jeg var sikker på, at jeg ville vinde!$"

Route129_Text_AllisonPostBattle:
	.string "Ved du, hvad der er det største ved\n"
	.string "triathlons?\p"
	.string "At teste grænserne for din egen\n"
	.string "styrke og udholdenhed imod\n"
	.string "Moder Natur!$"

Route129_Text_ReedIntro:
	.string "Sig hej, hej!\n"
	.string "Lad os komme igang!$"

Route129_Text_ReedDefeat:
	.string "Fedt, jeg er slået.\n"
	.string "Det var det, færdig!$"

Route129_Text_ReedPostBattle:
	.string "Der er ikke noget for en taber.\n"
	.string "Det er tid for mig at slå hjem.$"

Route129_Text_TishaIntro:
	.string "Hvad er det for en fart?\n"
	.string "Lad os tage det roligt og nemt.$"

Route129_Text_TishaDefeat:
	.string "Åh, nej.\n"
	.string "Jeg ville gerne slappe lidt af mere…$"

Route129_Text_TishaPostBattle:
	.string "Kender du ikke det med at lave fejl,\n"
	.string "når du har travlt?\p"
	.string "Derfor forsøger jeg at tage tingene\n"
	.string "langsomt.$"

Route129_Text_ClarenceIntro:
	.string "At surfe er ikke så let, som det ser ud til,\n"
	.string "er det ikke rigtigt?$"

Route129_Text_ClarenceDefeat:
	.string "At vinde er bestemt ikke nemt.$"

Route129_Text_ClarencePostBattle:
	.string "Du har dine øjne rettet mod POKéMON-\n"
	.string "LIGAEN? Hold fast i det!\p$"

Route130_Text_RodneyIntro:
	.string "Hvad en overraskelse! Jeg havde ikke forventet at\n"
	.string "se en TRÆNER ude på havet.\p"
	.string "Jeg tror, vi burde kæmpe!$"

Route130_Text_RodneyDefeat:
	.string "Denne knægts virkelig sej…$"

Route130_Text_RodneyPostBattle:
	.string "Dine øjne har den der look af en,\n"
	.string "der har oplevet hårde udfordringer\n"
	.string "og sejret. Det klæder dig godt!$"

Route130_Text_KatieIntro:
	.string "I det dybe blå hav,\n"
	.string "finder mit knuste blå hjerte\l"
	.string "trøst blandt bølgerne.$"

Route130_Text_KatieDefeat:
	.string "Som det store blå hav,\n"
	.string "strækker POKéMON-verdenen\n"
	.string "sig dybere end man tror.$"

Route130_Text_KatiePostBattle:
	.string "Verdens børn drømmer\n"
	.string "om en dag at blive\l"
	.string "POKéMON MESTER.$"

Route130_Text_SantiagoIntro:
	.string "Der er noget helt magisk ved at sejle\n"
	.string "ud på det åbne hav… Stille og roligt.$"

Route130_Text_SantiagoDefeat:
	.string "Jeg måtte være lidt mindre fredelig!$"

Route130_Text_SantiagoPostBattle:
	.string "At svømme og kæmpe på denne måde… \n"
	.string "Jeg er en glad fyr…$" 

Route131_Text_RichardIntro:
	.string "Havet vrimler med POKéMON.\n"
	.string "Det er ikke nemt at svømme, jeg siger dig.$"  

Route131_Text_RichardDefeat:
	.string "POKéMON opdrættet af TRÆNERE er\n"
	.string "rigtig seje…$"

Route131_Text_RichardPostBattle:
	.string "Puha… Puha…\n"
	.string "Jeg er flad…\p"
	.string "Det er let på vejen. Det er det at\n"
	.string "forlade stedet, der er svært.\p"
	.string "Mon jeg vil have energi tilbage til\n"
	.string "turen tilbage?$"

Route131_Text_HermanIntro:
	.string "Havet… Havet… Havet…\n"
	.string "Havet så langt som disse øjne kan nå!\l"
	.string "Jeg er træt af havet!$"

Route131_Text_HermanDefeat:
	.string "Buh!$"

Route131_Text_HermanPostBattle:
	.string "Ked af det, jeg er ved havet, men svømme må jeg.\p"
	.string "Jeg er født svømmer!\n"
	.string "Det er hvad jeg er.$"

Route131_Text_SusieIntro:
    .string "Hej, skat, vent lige!\n"
    .string "Vi burde kæmpe, du og jeg!$"

Route131_Text_SusieDefeat:
	.string "Du er sej på trods af den måde\n"
	.string "du ser ud på!$"

Route131_Text_SusiePostBattle:
    .string "Så du en fyr derovre, som\n"
    .string "klager over, at han keder sig af havet?\p"
    .string "Det er alt sammen snak.\n"
    .string "Han er håbløst forelsket i havet!$"

Route131_Text_KaraIntro:
	.string "Hvorfor elsker mænd badebukser så meget?\p"
	.string "De glor alle på mig!$"

Route131_Text_KaraDefeat:
	.string "Jeg er ude af min dybde!$"

Route131_Text_KaraPostBattle:
	.string "Måske er det ikke min badedragt, der\n"
	.string "får mænd til at kigge. Det må være min skønhed!$"

Route131_Text_ReliIntro:
	.string "RELI: Vi vil arbejde sammen som søskende\n"
	.string "for at udfordre dig!\p$"

Route131_Text_ReliDefeat:
	.string "RELI: Vi kunne ikke vinde, selvom vi\n"
	.string "arbejdede sammen…$"

Route131_Text_ReliPostBattle:
	.string "RELI: Folkene i PACIFIDLOG er\n"
	.string "sammen med havet og POKéMON fra\l"
	.string "den tid, de bliver født.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: Du har ikke to POKéMON?\n"
	.string "Så kan vi desværre ikke kæmpe.$"

Route131_Text_IanIntro:
	.string "IAN: Jeg gør mit bedste sammen med\n"
	.string "min søster!$"

Route131_Text_IanDefeat:
	.string "IAN: Jeg gjorde mit bedste med min søs,\n"
	.string "men vi kunne stadig ikke vinde…$"

Route131_Text_IanPostBattle:
	.string "IAN: Ved du, hvordan PACIFIDLOG\n"
	.string "er en flydende by?\p"
	.string "Så, hvor end der er havet,\n"
	.string "er det en del af PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Hvis du har to POKéMON,\n"
	.string "tager vi dig med på!$"

Route131_Text_TaliaIntro:
	.string "Hvis du kan slå mig, vil jeg give dig lidt\n"
	.string "fantastisk information!$"

Route131_Text_TaliaDefeat:
	.string "Nå?\n"
	.string "Tabte jeg?$"

Route131_Text_TaliaPostBattle:
	.string "Der er et mærkeligt sted i nærheden.\n"
	.string "Der er et kæmpe tårn der.\l"
	.string "Hvorfor går du ikke derhen og kigger?$"

Route131_Text_KevinIntro:
	.string "Folkene fra PACIFIDLOG er\n"
	.string "en fredelig flok.\p"
	.string "De bliver aldrig sure.\n"
	.string "Det gælder også for mig.$"

Route131_Text_KevinDefeat:
	.string "Ups!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Åh, vent.\n"
	.string "Jeg er ikke sur. Ærligt talt!\p"
	.string "Men hold nu op, du er stærk!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro:
	.string "Jeg plejede at få forkølelse hele tiden\n"
	.string "som barn, men jeg blev helt sund, da\n"
	.string "jeg begyndte at svømme.$"

Route132_Text_GilbertDefeat:
	.string "Jeg sukker efter mere kraft…$"

Route132_Text_GilbertPostBattle:
	.string "TRÆNERE rejser gennem markerne og\n"
	.string "bjergene, så de må også være i form.$"

Route132_Text_DanaIntro:
    .string "Jeg forsøger at undgå at svømme\n"
    .string "hvor strømmene er for stærke.$"

Route132_Text_DanaDefeat:
	.string "Åh nej, ikke mere!$"

Route132_Text_DanaPostBattle:
	.string "Hvis jeg bliver skyllet væk, mister jeg\n"
	.string "hele min fornemmelse af sted…$"

Route132_Text_RonaldIntro:
	.string "Vind eller tab, du vil aldrig vide før\n"
	.string "du prøver!$"

Route132_Text_RonaldDefeat:
	.string "Åh nej!\n"
	.string "Jeg sank i nederlag!$"

Route132_Text_RonaldPostBattle:
	.string "Jeg slås aldrig, når jeg ved, jeg vil vinde.\n"
	.string "Jeg kan lide at kæmpe på den nådesløse\n"
	.string "kant mellem sejr og nederlag!$"

Route132_Text_KiyoIntro:
	.string "Jeg tænker på POKéMON 24 timer om dagen.\n"
	.string "Hvordan tror du, du kan slå mig?$"

Route132_Text_KiyoDefeat:
	.string "Jeg taber.\n"
	.string "Jeg vil bøje mig for nederlaget.$"

Route132_Text_KiyoPostBattle:
	.string "Øv…\n"
	.string "Du er vild med POKéMON, ikke sandt?\p"
	.string "Du må jo tænke på POKéMON 24 timer\n"
	.string "i døgnet, ikke?$"

Route132_Text_MakaylaIntro:
	.string "Jeg er altid sammen med min mand,\n"
	.string "men jeg kan vinde selv uden ham.$"

Route132_Text_MakaylaDefeat:
	.string "Nå, jeg gættede nok, jeg var ikke god nok.$"

Route132_Text_MakaylaPostBattle:
	.string "Den unge mand derovre ligner præcis\n"
	.string "min mand, da han var ung.\p"
	.string "Han får mig til at rødme!$"

Route132_Text_JonathanIntro:
	.string "Nogen har set mig meget interesseret på.\n"
	.string "Var det dig?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "That's pretty strong, all right!$" 

Route132_Text_JonathanPostBattle:
	.string "Jeg kan ikke ryste denne følelse\n"
	.string "af, at nogen ser på mig.\p"
	.string "Jeg kan ikke koncentrere mig!$"

Route132_Text_PaxtonIntro:
	.string "Hvor mon min kone er taget hen?\n"
	.string "Jeg er altid sammen med hende.\l"
	.string "Mon jeg kan vinde på egen hånd?$"

Route132_Text_PaxtonDefeat:
	.string "Åh, jeg kan se, at jeg ikke kunne\n"
	.string "vinde på egen hånd alligevel.$"

Route132_Text_PaxtonPostBattle:
	.string "Min kone leder sikkert efter mig.\n"
	.string "Jeg må hellere finde hende med det samme.$"

Route132_Text_DarcyIntro:
	.string "Jeg kunne lide at træne her selv.\n"
	.string "Det er forfærdeligt, at alle disse mennesker kom!$"

Route132_Text_DarcyDefeat:
    .string "Okay! Jeg vil ikke klage over andre\n"
    .string "mennesker, der er her.$"

Route132_Text_DarcyPostBattle:
	.string "Jeg antager, at jeg kan gå sammen\n"
	.string "med den gamle mand og udfordre det\n"
	.string "andet hold.$"

Route133_Text_FranklinIntro:
	.string "Har strømmene også ført dig hertil?\n"
	.string "Det må have været skæbnebestemt.\l"
	.string "Lad os kæmpe!$"

Route133_Text_FranklinDefeat:
    .string "Stærk!\n"
    .string "Alt for stærk!$"

Route133_Text_FranklinPostBattle:
	.string "Det er bare min uheldige skæbne, at en\n"
	.string "sej TRÆNER som dig ville drive her til…\l"
	.string "Jeg må være forbandet…$"

Route133_Text_DebraIntro:
	.string "Jeg har ført et liv fyldt med kvaler og elendighed…\n"
	.string "Jeg er blevet skubbet væk, og dette er hvor\l"
	.string "jeg er drevet hen…$"

Route133_Text_DebraDefeat:
	.string "Endnu et nederlag…$"

Route133_Text_DebraPostBattle:
	.string "Et liv på drift…\n"
	.string "Det vil jeg ikke længere!$"

Route133_Text_LindaIntro:
	.string "Velkommen!\n"
	.string "Jeg har ventet på dig!$"

Route133_Text_LindaDefeat:
	.string "Nej! Vær sød!$"

Route133_Text_LindaPostBattle:
	.string "En stærk børnetræner…\n"
	.string "Det er så irriterende!$" 

Route133_Text_WarrenIntro:
	.string "Jeg vil gerne vinde ligesom alle andre, \n"
	.string "men jeg vil ikke opdrætte POKéMON som \n"
	.string "alle andre.$"

Route133_Text_WarrenDefeat:
	.string "Øv altså!\n"
	.string "Min måde er stadig for slap!$"

Route133_Text_WarrenPostBattle:
	.string "Det er meget sjovere at gøre tingene på den\n"
	.string "måde, jeg vil, end at være som alle andre.\l"
	.string "Jeg mener, det er åbenlyst!$"

Route133_Text_BeckIntro:
	.string "Jeg er kommet hele vejen ud her med min\n"
	.string "FUGLE POKéMON.$"

Route133_Text_BeckDefeat:
	.string "Du…\n"
	.string "Du er helt fantastisk cool!$"

Route133_Text_BeckPostBattle:
	.string "Jeg vil gerne tilbage til FORTREE,\n"
	.string "men jeg er også begyndt at kunne lide dette sted.$"

Route133_Text_MollieIntro:
	.string "Jeg må have kæmpet tusindvis\n"
	.string "af gange. Jeg har mistet tællingen.$"

Route133_Text_MollieDefeat:
	.string "Jeg har måske tabt tusind gange,\n"
	.string "men et nederlag gør stadig ondt.$"

Route133_Text_MolliePostBattle:
	.string "Bliv ved med det, unge menneske. Så kan\n"
	.string "du blive ligesom min mand og mig.$"

Route133_Text_ConorIntro:
	.string "Unge mennesker er alt for glade for at\n"
	.string "følge strømmen. De er uden retning.$"

Route133_Text_ConorDefeat:
	.string "Du har et fast formål.$"

Route133_Text_ConorPostBattle:
	.string "Lad ikke andre føre dig på afveje.\n"
	.string "Mist ikke retning, når du bliver ældre.$"

Route134_Text_JackIntro:
    .string "Selv de POKéMON, der kan svømme, bliver\n"
    .string "ført med af de hurtige strømme.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "Jeg tror POKéMON nyder de hurtigt\n"
	.string "flydende strømme omkring disse dele.$"

Route134_Text_LaurelIntro:
	.string "Mine LUVDISC leder efter et sjovt\n"
	.string "kamp. Vil du være med?$"

Route134_Text_LaurelDefeat:
	.string "Ups!\p$"

Route134_Text_LaurelPostBattle:
	.string "Der er en samler, der er ude\n"
	.string "efter SKALERNE fra LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okay, venner! Det er nok med hvilen,\n"
	.string "det er tid til en kamp!$"

Route134_Text_AlexDefeat:
	.string "Træt igen…$"

Route134_Text_AlexPostBattle:
	.string "Mine FUGL POKéMON bliver hurtigt trætte\n"
	.string "efter en lang flyvning…$"

Route134_Text_HitoshiIntro:
	.string "Du er en POKéMON TRÆNER.\n"
	.string "Ingen grund til ord. Vi kæmper nu.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "Det var mig, der udfordrede dig, og\n"
	.string "alligevel tabte jeg. Jeg er dybt\n"
	.string "skamfuld…$"

Route134_Text_AaronIntro:
	.string "Den vilde tide i dette område\n"
	.string "er med til at gøre os stærkere end\n"
	.string "nogensinde.$"

Route134_Text_AaronDefeat:
	.string "Jeg giver mig frivilligt.$"

Route134_Text_AaronPostBattle:
	.string "Vi vender tilbage til mere træning på\n"
	.string "METEOR FALLS.\p"
	.string "Hvis du har lyst, burde du også tage med.\n"
	.string "Det vil helt sikkert gøre dig stærkere!$"

Route134_Text_KelvinIntro:
	.string "V-Vores båd!\n"
	.string "Strømmen har båret den væk!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Stoooop! Stoooop!$"

Route134_Text_KelvinPostBattle:
    .string "Hvordan skal vi komme hjem, hvis vi\n"
    .string "ikke kan SURFE?\p"
    .string "Faktisk, jeg ved, at en besvimet\n"
    .string "POKéMON stadig kan SURFE, men det\n"
    .string "føles forkert.$"

Route134_Text_MarleyIntro:
	.string "Kan dine POKéMON undvige vores\n"
	.string "lynhurtige angreb?\p$"

Route134_Text_MarleyDefeat:
	.string "Jeg vidste aldrig, at sådan en teknik eksisterede!\n"
	.string "Du har besejret os helt.$"

Route134_Text_MarleyPostBattle:
	.string "Jeg har ikke mistet min passion for fart.\n"
	.string "Jeg vil forsøge hårdere.$"

Route134_Text_ReynaIntro:
	.string "Mine POKéMON kan ikke tages ned\n"
	.string "let!$"

Route134_Text_ReynaDefeat:
	.string "Du må da være skør!\n"
	.string "Forklar hvordan jeg tabte!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "Du vandt, helt sikkert!\p"
	.string "Jeg vil arbejde mig tilbage ved at tage\n"
	.string "udfordringer fra TRÆNERE, jeg møder!$"

Route134_Text_HudsonIntro:
	.string "Hør lige, har du set en anden\n"
	.string "SØMAND omkring her?$"

Route134_Text_HudsonDefeat:
	.string "Nå, det var noget!\p$"

Route134_Text_HudsonPostBattle:
	.string "Vores båd drev ud til havs.\p"
	.string "Min ven er en forsigtig fyr, så jeg\n"
	.string "er bekymret for ham.$"
