@ TRANSLATED

Route102_Text_CalvinIntro:
	.string "Hvis du har POKéMON med dig, så er du en\n"
	.string "officiel POKéMON TRÆNER! Du kan ikke\l"
	.string "sige nej til min udfordring!$"

Route102_Text_CalvinDefeated:
	.string "Åh nej, jeg tabte… Jeg burde have\n"
	.string "trænet mine mere…$"

Route102_Text_CalvinPostBattle:
	.string "Hør her, du. Hvis du er stærk, skulle du\n"
	.string "have fortalt mig det før!$"

Route102_Text_CalvinRegister:
	.string "Jeg har knoklet hårdt med dette siden\n"
	.string "jeg så dig sidst.\p"
	.string "Jeg vil gerne kæmpe mod dig igen, så kan\n"
	.string "du registrere mig i din POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "Jeg vil gerne kæmpe mod dig igen, så kan\n"
	.string "du registrere mig i din POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Siden jeg tabte til dig, har jeg\n"
	.string "desperat trænet mine POKéMON. Du kan\l"
	.string "ikke sige nej til min udfordring!$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, jeg tabte! Træner jeg helt\n"
	.string "forkert?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Hvis du vil blive stærkere, så vil jeg\n"
	.string "også blive stærkere.$"

Route102_Text_AllenIntro:
	.string "Er du lige blevet en TRÆNER? Vi er begge\n"
	.string "nybegyndere!$"

Route102_Text_AllenDefeated:
	.string "Jeg ringede til dig, fordi jeg tænkte, at\n"
	.string "jeg kunne slå dig…$"

Route102_Text_AllenPostBattle:
	.string "Jeg har ikke vundet en eneste gang\n"
	.string "endnu… Jeg håber, at jeg snart vinder…$"

Route102_Text_RickIntro:
	.string "Haha! Vores øjne mødtes! Jeg vil\n"
	.string "udfordre dig med min BUG POKéMON!$"

Route102_Text_RickDefeated:
	.string "Åh! Ned og ude!$"

Route102_Text_RickPostBattle:
	.string "Hvis du møder øjnene med en TRÆNER,\n"
	.string "skal du udfordre vedkommende! Det er en\l"
	.string "regel!$"

Route102_Text_TianaIntro:
	.string "Jeg vil blive ved med at vinde og stræbe\n"
	.string "efter at være den bedste TRÆNER.\p"
	.string "Hjælp mig med at udvikle min karriere!$"

Route102_Text_TianaDefeated:
	.string "Jeg endte med at fremme din karriere…$"

Route102_Text_TianaPostBattle:
	.string "For at blive ved med at vinde, ser jeg,\n"
	.string "at jeg er nødt til at fange flere\l"
	.string "POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Kan du mærke trækket fra vores\n"
	.string "sjæleberoligende duft?$"

Route103_Text_DaisyDefeated:
	.string "Du blev ikke narret af vores duft…$"

Route103_Text_DaisyPostBattle:
	.string "Aromaterapi er en form for mental\n"
	.string "helbredelse, der arbejder med dufte.$"

Route103_Text_AmyIntro:
	.string "AMY: Jeg er AMY. Og det her er min\n"
	.string "lillesøster LIV. Vi kæmper sammen!$"

Route103_Text_AmyDefeated:
	.string "AMY: Øh, vi tabte.$"

Route103_Text_AmyPostBattle:
	.string "AMY: Du skal tænke på alle slags ting,\n"
	.string "når du kæmper mod to TRÆNERE.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Ups, du har kun en POKéMON med dig.\n"
	.string "Du kan ikke kæmpe mod os på den måde.$"

Route103_Text_LivIntro:
	.string "LIV: Vi kæmper sammen som ét hold.$"

Route103_Text_LivDefeated:
	.string "LIV: Øv, vi tabte, storesøster…$"

Route103_Text_LivPostBattle:
	.string "LIV: Vi arbejder perfekt sammen, min\n"
	.string "storesøster og jeg…\p"
	.string "Men vi tabte stadig…$"

Route103_Text_AmyLivRegister:
	.string "LIV: Virkelig, vi er meget bedre… Det er\n"
	.string "sandt! Vi viser dig næste gang!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: Hvis du vil kæmpe mod os, skal du\n"
	.string "have to POKéMON med! Det er ikke fair\l"
	.string "hvis du ikke har!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: Jeg er AMY. Og dette er min\n"
	.string "lillesøster LIV. Vi kæmper sammen!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Åh, buhuhu! Vi kunne ikke vinde\n"
	.string "igen…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Du skal tænke på alle slags ting,\n"
	.string "når du kæmper mod to TRÆNERE.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Ups! Du har kun een POKéMON med\n"
	.string "dig. Du kan ikke kæmpe mod os på den\l"
	.string "måde.$"

Route103_Text_LivRematchIntro:
	.string "LIV: Vi kæmper sammen som ét hold.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Øv, vi tabte igen… Storesøster…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: Vi arbejder perfekt sammen, min\n"
	.string "store søster og jeg…\p"
	.string "Men hvorfor tabte vi igen?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: Hvis du vil kæmpe mod os, skal du\n"
	.string "have to POKéMON! Det er ikke fair, hvis\l"
	.string "du ikke har to!$"

Route103_Text_AndrewIntro:
	.string "Åh nej! Mit fiskegarn er helt snørklet!\n"
	.string "Jeg bliver frustreret og sur!\p"
	.string "Det er nok! Udfordr mig!$"

Route103_Text_AndrewDefeated:
	.string "Åh! Tabte den! Nu er jeg endnu mere\n"
	.string "irriteret!$"

Route103_Text_AndrewPostBattle:
	.string "Åh, jeg er stadig kogende rasende…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "Mine POKéMON er dejligt bedårende! Vær\n"
	.string "ikke genert--jeg vil vise dig!$"

Route103_Text_MiguelDefeated:
	.string "Åh, min gosh! Min kære POKéMON!$"

Route103_Text_MiguelPostBattle:
	.string "Min dejlige POKéMON ser skøn ud, selv\n"
	.string "når den er faldet om!$"

Route103_Text_MiguelRegister:
	.string "Jeg skal nok få dig til at kigge på mine\n"
	.string "skønne POKéMON igen!$"

Route103_Text_MiguelRematchIntro:
	.string "Hej, dig! Min dejligt bedårende POKéMON\n"
	.string "er blevet endnu mere kær!$"

Route103_Text_MiguelRematchDefeated:
	.string "Åh! Mine kære POKéMON!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Jo mere tid jeg tilbringer med det, jo\n"
	.string "mere bedårende bliver mit POKéMON.$"

Route103_Text_PeteIntro:
	.string "Den slags afstand… Du burde bare\n"
	.string "svømme det!$"

Route103_Text_PeteDefeated:
	.string "Åh, det er godt gået!$"

Route103_Text_PetePostBattle:
	.string "Åh, nu forstår jeg, hvor du kommer fra.\p"
	.string "Hvis jeg havde en POKéMON så pålidelig,\n"
	.string "ville jeg også ønske at SURFE på den!$"

Route103_Text_IsabelleIntro:
	.string "Se hvor du går! Vi kommer til at krasje!$"

Route103_Text_IsabelleDefeated:
	.string "Støn…$"

Route103_Text_IsabellePostBattle:
	.string "Jeg er en dårlig svømmer, så jeg øvede\n"
	.string "mig… Undskyld for næsten at støde ind i\l"
	.string "dig.$"

Route103_Text_RhettIntro:
	.string "Wow! Hvordan kom du ind på så lidt\n"
	.string "plads?$"

Route103_Text_RhettDefeated:
	.string "Whoa! Den knægt kan feste!$"

Route103_Text_RhettPostBattle:
	.string "Kan du lide trange rum som dette?$"

Route103_Text_MarcosIntro:
	.string "Trak min guitars jamren dig ind?$"

Route103_Text_MarcosDefeated:
	.string "Min enmandsforestilling er ødelagt…$"

Route103_Text_MarcosPostBattle:
	.string "Jeg spillede guitar, hvor der var få\n"
	.string "mennesker omkring, men en masse fans\l"
	.string "var samlet.\p"
	.string "Heh, måske skulle jeg blive\n"
	.string "professionel.$"

Route104_Text_GinaIntro:
	.string "GINA: Okay, lad os kæmpe med vores\n"
	.string "POKéMON!$"

Route104_Text_GinaDefeat:
	.string "GINA: Tab at tabe oprører mig!$"

Route104_Text_GinaPostBattle:
	.string "GINA: Du er stærk! Vi skal træne meget\n"
	.string "mere!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Åh? Kun én POKéMON? Så skal vi\n"
	.string "ikke kæmpe med dig.\p"
	.string "Hvis der kun er én POKéMON, vil den føle\n"
	.string "sig ensom. Det er ikke rart.$"

Route104_Text_MiaIntro:
	.string "MIA: Vi er tvillinger, så vi kæmper\n"
	.string "POKéMON sammen.$"

Route104_Text_MiaDefeat:
	.string "MIA: Vi kæmpede sammen, men vi begge\n"
	.string "tabte…$"

Route104_Text_MiaPostBattle:
	.string "MIA: Vi vil træne vores POKéMON  mere og\n"
	.string "være stærke som dig.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Vil du kæmpe med os?\p"
	.string "Det er et stort NEJ, hvis du ikke har to\n"
	.string "POKéMON med dig. Vi er for stærke for\l"
	.string "dig!$"

Route104_Text_IvanIntro:
	.string "Hvorfor holde det som en hemmelighed?\n"
	.string "Jeg er eksperten i VANDE POKéMON!\p"
	.string "Hva'? Kender du mig ikke?$"

Route104_Text_IvanDefeat:
	.string "Jeg troede faktisk, at jeg ikke var så\n"
	.string "dårlig, hvis jeg selv skal sige det, men\l"
	.string "jeg gætter ikke… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "Jeg kom for meget i fiske humøret. Jeg\n"
	.string "glemte at træne mine POKéMON…$"

Route104_Text_BillyIntro:
	.string "At efterlade fodspor i sandet er så\n"
	.string "sjovt!$"

Route104_Text_BillyDefeat:
	.string "Åh nej! Jeg har fået sand i mine\n"
	.string "løbesko! De er helt sandete!$"

Route104_Text_BillyPostBattle:
	.string "Jeg vil efterlade mine fodspor overalt i\n"
	.string "sandet, men de forsvinder hurtigt…$"

Route104_Text_HaleyIntro:
	.string "Skal jeg… Eller skal jeg ikke?\p"
	.string "Okay, helt sikkert, jeg vil kæmpe!$"

Route104_Text_HaleyDefeat:
	.string "Jeg burde ikke have kæmpet…$"

Route104_Text_HaleyPostBattle:
	.string "Hvis du står over for en beslutning og\n"
	.string "du lader en anden vælge for dig, vil du\l"
	.string "fortryde det, uanset hvordan tingene\l"
	.string "går.$"

Route104_Text_HaleyRegister1:
	.string "Du er stærk, men skal jeg registrere dig\n"
	.string "i min POKéNAV? Måske skal jeg ikke…\p"
	.string "Godt, selvfølgelig vil jeg registrere\n"
	.string "dig!$"

Route104_Text_HaleyRegister2:
	.string "Du er stærk, men skal jeg registrere dig\n"
	.string "i min POKéNAViser? Måske skulle jeg\l"
	.string "ikke…\p"
	.string "Okay, selvfølgelig, jeg vil registrere\n"
	.string "dig!$"

Route104_Text_HaleyRematchIntro:
	.string "Kom så, kæmp mod mig!$"

Route104_Text_HaleyRematchDefeat:
	.string "Åhh… Jeg troede, jeg kunne vinde…$"

Route104_Text_HaleyPostRematch:
	.string "Jeg besluttede mig for at kæmpe, så jeg\n"
	.string "kan acceptere dette nederlag med nåde.\p"
	.string "Jeg er stadig ked af at tabe!$"

Route104_Text_WinstonIntro:
	.string "Åh, selvfølgelig, jeg accepterer din\n"
	.string "udfordring. Jeg har masser af penge.$"

Route104_Text_WinstonDefeat:
	.string "Hvorfor kunne jeg ikke vinde?$"

Route104_Text_WinstonPostBattle:
	.string "Der er visse ting, penge ikke kan købe.\n"
	.string "Det er POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "Hm? Nåh, du har fået en POKéNAV.\p"
	.string "Jeg vil med glæde registrere dig. Jeg har\n"
	.string "trods alt masser af penge.$"

Route104_Text_WinstonRegister2:
	.string "Hm? Åh, du har fået en POKéNAV.\p"
	.string "Jeg vil med glæde registrere dig. Jeg har\n"
	.string "trods alt masser af penge.$"

Route104_Text_WinstonRematchIntro:
	.string "Efter jeg tabte til dig, lærte jeg en\n"
	.string "masse ting om POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "Jeg tabte igen? Hvorfor kunne jeg ikke\n"
	.string "vinde?$"

Route104_Text_WinstonPostRematch:
	.string "Jeg er fantastisk rig, men jeg kan ikke\n"
	.string "synes at vinde i POKéMON…\p"
	.string "Det er så dybt, POKéMONs verden…$"

Route104_Text_CindyIntro:
	.string "Vi må have været skæbnebestemt til at\n"
	.string "mødes. Må jeg bede dig om en kamp?$"

Route104_Text_CindyDefeat:
	.string "Åh nej!$"

Route104_Text_CindyPostBattle:
	.string "“Hej” er begyndelsen på “farvel.” Jeg\n"
	.string "håber, vi mødes igen.$"

Route104_Text_CindyRegister1:
	.string "Hej, vi mødes igen.\p"
	.string "Det virker som om, vi bliver trukket\n"
	.string "sammen. Lad os registrere hinanden i\l"
	.string "vores POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "Vi burde mindes, hvordan vi synes at\n"
	.string "blive draget mod hinanden.\p"
	.string "Lad os registrere hinanden i vores\n"
	.string "POKéMONAVis.$"

Route104_Text_CindyRematchIntro:
	.string "Hej, vi mødes igen. Må jeg bede om en\n"
	.string "kamp?$"

Route104_Text_CindyRematchDefeat:
	.string "Åh, nej… Jeg gjorde det bedste, jeg\n"
	.string "kunne…$"

Route104_Text_CindyPostRematch:
	.string "“Hej” er starten på “farvel.” Jeg håber\n"
	.string "vi mødes igen.$"

Route104_Text_DarianIntro:
	.string "Jeg har fanget en sej udseende\n"
	.string "POKéMON!\p"
	.string "Den har en magisk kvalitet ved sig! Den\n"
	.string "ser helt klart sej ud, ja det gør den!$"

Route104_Text_DarianDefeat:
	.string "Hvad i…$"

Route104_Text_DarianPostBattle:
	.string "Hey, MAGIKARP, du lever virkelig ikke op\n"
	.string "til dit navn, gør du?$"

Route105_Text_FosterIntro:
	.string "Der skulle være en mystisk sten omkring\n"
	.string "her. Ved du noget om det?$"

Route105_Text_FosterDefeated:
	.string "Jeg tænkte for meget på den sten, mens\n"
	.string "mine POKéMON forblev svage…$"

Route105_Text_FosterPostBattle:
	.string "Jeg kan tilbringe timer og timer med at\n"
	.string "stirre på en flot sten uden at blive$"

Route105_Text_LuisIntro:
	.string "Puha! Jeg var bekymret for, at et barn\n"
	.string "drukner, når jeg så dig.\p"
	.string "Du ser ud til at have det fint, så hvad\n"
	.string "siger du til en kamp?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "Hvis du drukner, er signalet at vinke\n"
	.string "med en arm mod stranden.$"

Route105_Text_DominikIntro:
	.string "At svømme i det dybe blå… Det føles\n"
	.string "fantastisk!$"

Route105_Text_DominikDefeated:
	.string "Jeg tabte… Nu føler jeg mig blå…$"

Route105_Text_DominikPostBattle:
	.string "Hvorfor er havet blåt?\p"
	.string "Det lærte jeg om på MUSEET i SLATEPORT,\n"
	.string "men jeg har glemt.$"

Route105_Text_BeverlyIntro:
	.string "Min krop føles lettere i vandet. Det er,\n"
	.string "som om jeg er blevet slankere!$"

Route105_Text_BeverlyDefeated:
	.string "Jeg svæver…$"

Route105_Text_PostBattle:
	.string "Din kropsvægt reduceres til kun en\n"
	.string "tiendedel i vandet.\p"
	.string "Det ville gøre mig… Ups! Jeg fortæller\n"
	.string "ikke min vægt!$"

Route105_Text_ImaniIntro:
	.string "Den blå, blå himmel… Den uendelige hav…\n"
	.string "Det er så fredeligt…$"

Route105_Text_ImaniDefeated:
	.string "Jeg tabte mens jeg slappede af!$"

Route105_Text_ImaniPostBattle:
	.string "Jeg vil gerne have at vide, at jeg er\n"
	.string "afslappende at være sammen med. Griner.$"

Route105_Text_AndresIntro:
	.string "Jeg er overbevist om, at havet gemmer\n"
	.string "hemmeligheder fra os.$"

Route105_Text_AndresDefeated:
	.string "Ja… Jeg er ikke god til at kæmpe…$"

Route105_Text_AndresPostBattle:
	.string "Jeg er sikker på, at der er mange\n"
	.string "hemmeligheder at opdage i verdens have.\p"
	.string "Jeg har tænkt mig at finde dem alle!$"

Route105_Text_AndresRegister:
	.string "Hov? Jeg er så svag, men du er villig til\n"
	.string "at registrere mig på din POKéNAV?$"

Route105_Text_AndresRematchIntro:
	.string "Jeg har fortalt dig, at jeg er svag… Er\n"
	.string "du sikker på, at du vil gøre dette?$"

Route105_Text_AndresRematchDefeated:
	.string "Ja… Jeg troede ikke, jeg kunne vinde.$"

Route105_Text_AndresRematchPostBattle:
	.string "Jeg er måske svag til kamp, men min\n"
	.string "trang til at udforske kan ikke slås.\p"
	.string "Jeg vil sejle alle have rundt om\n"
	.string "verdenen!$"

Route105_Text_JosueIntro:
	.string "Jeg er udmattet af at svømme. Jeg er\n"
	.string "bare ikke vant til det.\p"
	.string "Jeg har brug for en kamp for at få lidt\n"
	.string "variation!$"

Route105_Text_JosueDefeated:
	.string "Jeg tabte, fordi jeg kæmpede til søs.$"

Route105_Text_JosuePostBattle:
	.string "Yeah, for me, the sky is a much better\n"
	.string "match than the sea.$"

Route106_Text_ElliotIntro:
	.string "Hvad foretrækker du, fiskeri i havet\n"
	.string "eller en bæk? $"

Route106_Text_ElliotDefeated:
	.string "Som med dybhavsfiskeri, tabte jeg\n"
	.string "spektakulært!$"

Route106_Text_ElliotPostBattle:
	.string "At fiske er det bedste, uanset om det\n"
	.string "er i havet eller en å. Er du enig med mig,\l"
	.string "ikke?$"

Route106_Text_ElliotRegister:
	.string "At fiske er skønt, men at kæmpe er også\n"
	.string "sjovt. Hvis det er okay med dig, kan vi så\l"
	.string "mødes igen?$"

Route106_Text_ElliotRematchIntro:
	.string "Jeg har fanget en masse POKéMON ved at\n"
	.string "fiske. Jeg vil vise dig en imponerende\l"
	.string "kamp!$"

Route106_Text_ElliotRematchDefeated:
	.string "Jeg tabte igen spektakulært!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Uanset om man vinder eller taber,\n"
	.string "POKéMON er de bedste! Du er enig med mig,\l"
	.string "ikke sandt?$"

Route106_Text_NedIntro:
	.string "Hvad gør folk, hvis de skal på\p"
	.string "WC? Hvad hvis min STANG fanger en stor\n"
	.string "fisk, mens jeg er på WC? Jeg kan bare\l"
	.string "ikke gå…$"

Route106_Text_NedDefeated:
	.string "Jeg tabte, fordi jeg prøver at holde mig\n"
	.string "fra badeværelset…$"

Route106_Text_NedPostBattle:
	.string "Åh nej! Jeg har på fornemmelsen, at jeg\n"
	.string "fanger en stor fisk!$"

Route106_Text_DouglasIntro:
	.string "Hahahah! Jeg er en dårlig løber, men i\n"
	.string "vandet kan du ikke fange mig!$"

Route106_Text_DouglasDefeated:
	.string "Jeg giver op!$"

Route106_Text_DouglasPostBattle:
	.string "Jeg ville ikke tabe i en\n"
	.string "svømmekonkurrence…$"

Route106_Text_KylaIntro:
	.string "Havet er min baghave. Jeg tager det\n"
	.string "ikke roligt, fordi du er et barn!$"

Route106_Text_KylaDefeated:
	.string "Har du taget det lidt let med mig\n"
	.string "tilfældigvis?$"

Route106_Text_KylaPostBattle:
	.string "Driver med bølgerne… Det er skønt! Vil\n"
	.string "du prøve det?$"

Route107_Text_DarrinIntro:
	.string "Gaaab…\p"
	.string "Jeg må være faldet i søvn, mens jeg drev\n"
	.string "rundt på bølgerne.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, jeg tabte… Jeg tror, jeg vil tage\n"
	.string "en lur…$"

Route107_Text_DarrinPostBattle:
	.string "At flyde og blive vugget af bølgerne -\n"
	.string "det er som at sove i en blød, behagelig\l"
	.string "seng.$"

Route107_Text_TonyIntro:
	.string "Havet er som min baghave. Lad os kæmpe!$"

Route107_Text_TonyDefeated:
	.string "Jeg tabte på min hjemmebane… Jeg er i\n"
	.string "chok!$"

Route107_Text_TonyPostBattle:
	.string "Jeg svømmer i havene med et hjerte fuld\n"
	.string "af drømme…\p"
	.string "Det er en sang! Nå, jeg svømmer lidt\n"
	.string "mere.$"

Route107_Text_TonyRegister:
	.string "Du har chokeret mig til benet! Nå, så du\n"
	.string "ikke glemmer mig…$"

Route107_Text_TonyRematchIntro:
	.string "Svømmer i det store, vide hav, min\n"
	.string "POKéMON er blevet stærkere!$"

Route107_Text_TonyRematchDefeated:
	.string "Sikke en overraskelse!\p"
	.string "Mine POKéMON er blevet stærkere, men\n"
	.string "jeg forblev svag som en TRÆNER!$"

Route107_Text_TonyRematchPostBattle:
	.string "Det, du lærer i kamp, gør dig til en\n"
	.string "stærkere TRÆNER. Bølgerne har lært mig\l"
	.string "det.$"

Route107_Text_DeniseIntro:
	.string "Kender du en lille by kaldet ALDERSUND?$"

Route107_Text_DeniseDefeated:
	.string "Jeg hader dette!$"

Route107_Text_DenisePostBattle:
	.string "En mærkelig sætning bliver virkelig\n"
	.string "populær i DEWFORD HALL.$"

Route107_Text_BethIntro:
	.string "Vil du kæmpe mod mig? Selvfølgelig, jeg\n"
	.string "vil med dig!$"

Route107_Text_BethDefeated:
	.string "Jeg var ikke god nok til dig.$"

Route107_Text_BethPostBattle:
	.string "Jeg tror, du bliver ved med at blive\n"
	.string "bedre. Jeg vil også give det en chance!$"

Route107_Text_LisaIntro:
	.string "LISA: Vi udfordrer dig som søster og\n"
	.string "bror!$"

Route107_Text_LisaDefeated:
	.string "LISA: Fedt! Du er i en anden klasse af\n"
	.string "seje.$"

Route107_Text_LisaPostBattle:
	.string "LISA: Har du nogen venner, som ville\n"
	.string "tage til stranden med dig?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Hvis du vil kæmpe med os, skal du\n"
	.string "have flere POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: Vi kæmper altid med POKéMON, min\n"
	.string "søster og jeg.\p"
	.string "Jeg taber altid, men vi kan slå jer 2 mod\n"
	.string "2!$"

Route107_Text_RayDefeated:
	.string "RAY: Ej, du er på et højere niveauend\n"
	.string "os!$"

Route107_Text_RayPostBattle:
	.string "RAY: Min søster gav mig min POKéMON. Jeg\n"
	.string "opfostrerede den, og nu er den min\l"
	.string "vigtige partner!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Hvis du vil kæmpe mod os, så tag\n"
	.string "nogle flere POKéMON med dig!$"

Route107_Text_CamronIntro:
	.string "Jeg er midt i en triatlon, men jeg er slet\n"
	.string "ikke træt!$"

Route107_Text_CamronDefeated:
	.string "Det udmattede mig…$"

Route107_Text_CamronPostBattle:
	.string "Jeg har stadig svømning og løb tilbage\n"
	.string "at lave efter dette.\p"
	.string "Mon jeg kommer til at være okay?$"

Route108_Text_JeromeIntro:
	.string "Min drøm er at svømme i verdens syv\n"
	.string "have!$"

Route108_Text_JeromeDefeated:
	.string "Jeg vil ikke kunne svømme de syv have\n"
	.string "på denne måde…$"

Route108_Text_JeromePostBattle:
	.string "At lege med marine POKéMON er en af\n"
	.string "glæderne ved at svømme!$"

Route108_Text_MatthewIntro:
	.string "Hej med dig! Skal du også ud til det\n"
	.string "FORLADTE SKIB?$"

Route108_Text_MatthewDefeated:
	.string "Jeg synker! Blup… Blup…$"

Route108_Text_MatthewPostBattle:
	.string "Nogle mennesker går endda ind i det\n"
	.string "FORLADTE SKIB.$"

Route108_Text_TaraIntro:
	.string "Min løgnagtige kæreste sagde, at jeg\n"
	.string "ser fantastisk ud i en bikini…$"

Route108_Text_TaraDefeated:
	.string "Åh, buhuhu!$"

Route108_Text_TaraPostBattle:
	.string "Selvom det er en løgn, elsker jeg at få\n"
	.string "at vide Jeg ser fantastisk ud… Vi piger\l"
	.string "er så komplekse…$"

Route108_Text_MissyIntro:
	.string "Jeg elsker havet! Jeg glemmer alle mine\n"
	.string "bekymringer, når jeg svømmer!$"

Route108_Text_MissyDefeated:
	.string "Når jeg taber en kamp, bliver jeg helt\n"
	.string "stresset!$"

Route108_Text_MissyPostBattle:
	.string "Arbejd din stress af ved at svømme! Det\n"
	.string "er så sundt!$"

Route108_Text_CoryIntro:
	.string "Jeg elsker VAND-type POKéMON. Jeg\n"
	.string "elsker også andre POKéMON!$"

Route108_Text_CoryDefeated:
	.string "Ihh! Jeg tabte! Ihh! Ihh!$"

Route108_Text_CoryPostBattle:
	.string "At råbe er godt for mig! Det løfter mig!$"

Route108_Text_CoryRegister:
	.string "Jeg elsker seje TRÆNERE, også!\n"
	.string "Registrer mig i din POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Vind eller tab, jeg elsker at kæmpe til\n"
	.string "søs!$"

Route108_Text_CoryRematchDefeated:
	.string "Ååh nej! Jeg tabte igen! Ååh! Ååh!$"

Route108_Text_CoryRematchPostBattle:
	.string "Hvis du står over for en udford- ring,\n"
	.string "så prøv at råbe til havet!$"

Route108_Text_CarolinaIntro:
	.string "Jeg er virkelig stolt af mine POKéMON. Vi\n"
	.string "vil vise dig en lynhurtig kamp!$"

Route108_Text_CarolinaDefeated:
	.string "Det var slet ikke sødt.$"

Route108_Text_CarolinaPostBattle:
	.string "Siden jeg er på havet som dette, ville\n"
	.string "jeg ikke have noget imod at iføre mig en\l"
	.string "lyserød,  flæsekantet bade dragt…$"

Route109_Text_DavidIntro:
	.string "Hiyah! Se på mine veltrænede\n"
	.string "mavemuskler! Det her er hvad man kalder\l"
	.string "“cut”!$"

Route109_Text_DavidDefeated:
	.string "Åh nej! Tabt!$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "Mine udhuggede mavemuskler har intet\n"
	.string "at gøre med POKéMON kampe!$"

Route109_Text_AliceIntro:
	.string "Er du ordentligt beskyttet mod solen?$"

Route109_Text_AliceDefeated:
	.string "Auts, av, av!$"

Route109_Text_AlicePostBattle:
	.string "Kinder er de mest tilbøjelige til at\n"
	.string "brænde!$"

Route109_Text_HueyIntro:
	.string "Jeg har kastet anker i havne overalt i\n"
	.string "verden, men SLATEPORT er den bedste.$"

Route109_Text_HueyDefeated:
	.string "Du er den bedste!$"

Route109_Text_HueyPostBattle:
	.string "I den bedste havn var den bedste\p"
	.string "TRÆNER…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp… Kamp? Med mig?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh… Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "Jeg er normalt stærkere end dette! Jeg\n"
	.string "har bare søsyge som en hund!\p"
	.string "Jeg er en SØMAND, men…$"

Route109_Text_RickyIntro:
	.string "Jeg er tørstig… Jeg kunne godt bruge en\n"
	.string "SODAVAND på STRANDHUSET…$"

Route109_Text_RickyDefeated:
	.string "Øv…$"

Route109_Text_RickyPostBattle:
	.string "Jeg er ved at blive sulten… Min\n"
	.string "indsprøjtningsflåde ligner en kæmpe\l"
	.string "donut…$"

Route109_Text_RickyRegister:
	.string "Skal vi have endnu et spil sammen, når\n"
	.string "jeg ikke er så tørstig?$"

Route109_Text_RickyRematchIntro:
	.string "Jeg er sulten, men jeg har masser af\n"
	.string "energi til en kamp!$"

Route109_Text_RickyRematchDefeated:
	.string "Jeg tabte… Det er fordi jeg er sulten…$"

Route109_Text_RickyRematchPostBattle:
	.string "Når du spiser på stranden, virker alt til\n"
	.string "at smage lidt bedre.$"

Route109_Text_LolaIntro:
	.string "Ser et strandparasol ikke ud som en\n"
	.string "kæmpe blomst?$"

Route109_Text_LolaDefeated:
	.string "Mor!$"

Route109_Text_LolaPostBattle:
	.string "Hvis du ser på stranden fra himlen, ser\n"
	.string "det ud som en stor blomsterhave!$"

Route109_Text_LolaRegister:
	.string "Mig? Jeg er her hver dag!$"

Route109_Text_LolaRematchIntro:
	.string "Jeg taber ikke til dig igen! Derfor har\n"
	.string "jeg min badering!$"

Route109_Text_LolaRematchDefeated:
	.string "Mor!$"

Route109_Text_LolaRematchPostBattle:
	.string "Hvis jeg har en badering, så stiger mig\n"
	.string "og min POKéMONs sødme helt op!$"

Route109_Text_AustinaIntro:
	.string "Jeg kan ikke svømme uden min badering,\n"
	.string "men jeg vil ikke tabe i POKéMON!$"

Route109_Text_AustinaDefeated:
	.string "Tabte jeg, fordi jeg har en indre rør?$"

Route109_Text_AustinaPostBattle:
	.string "Min badering er et modeitem. Jeg kan\n"
	.string "ikke ses uden den.$"

Route109_Text_GwenIntro:
	.string "Hej, seje TRÆNER. Vil du kæmpe med mig?$"

Route109_Text_GwenDefeated:
	.string "Åh, du er stærk.$"

Route109_Text_GwenPostBattle:
	.string "Hvordan blev du så stærk?$"

Route109_Text_CarterIntro:
	.string "Wahahah! Denne fyr er ved at fange en\n"
	.string "kæmpe!$"

Route109_Text_CarterDefeated:
	.string "Denne fyr mistede lige et…$"

Route109_Text_CarterPostBattle:
	.string "Denne fyr tror, at du er en stor en. Nej,\n"
	.string "du er en stor-en-til-at-være!$"

Route109_Text_PaulIntro:
	.string "PAUL: Nå, det her er en\n"
	.string "stemningsødelægger.\p"
	.string "Jeg ville ønske, at du ikke forstyrrede\n"
	.string "vores dyrebare tid sammen.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Nå, jeg giver op.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Nå, fortæl ikke nogen, at vi er\n"
	.string "her. Dette er bare vores private\l"
	.string "tosomhed!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Vi er fuldstændig og dybt\n"
	.string "forelskede. Det er derfor, vi lader vores\l"
	.string "POKéMON kæmpe sammen.$"

Route109_Text_MelIntro:
	.string "MEL: Vi er bare så forelskede. Vores\n"
	.string "romantik opvarmer hele HOENN!$"

Route109_Text_MelDefeated:
	.string "MEL: Vi tabte, og det er min skyld! PAUL\n"
	.string "vil hade mig!$"

Route109_Text_MelPostBattle:
	.string "MEL: Øh, PAUL, er du sur på mig? Vær\n"
	.string "venlig ikke at være sur.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: Vi er, ligesom, dybt og sandt\n"
	.string "forelskede. Derfor kæmper vi med vores\l"
	.string "POKéMON sammen.$"

Route109_Text_ChandlerIntro:
	.string "Tadaah! Se? Min badering er rund!$"

Route109_Text_ChandlerDefeated:
	.string "Åh nej! Øv bøv!$"

Route109_Text_ChandlerPostBattle:
	.string "Efter at jeg viste dig mit runde indre\n"
	.string "rør, også…$"

Route109_Text_HaileyIntro:
	.string "Jeg kan ikke svømme, så jeg lader som om\n"
	.string "jeg svømmer.$"

Route109_Text_HaileyDefeated:
	.string "Jeg vidste det! Jeg troede ikke, vi\n"
	.string "kunne vinde.$"

Route109_Text_HaileyPostBattle:
	.string "Når jeg lærer at svømme, tror jeg, mine\n"
	.string "POKéMON vil blive stærkere.$"

Route109_Text_ElijahIntro:
	.string "For a guy as macho as me, this of\n"
	.string "POKéMON is the perfect match!$"

Route109_Text_ElijahDefeated:
	.string "Jeg er sej selv i nederlag, hey?$"

Route109_Text_ElijahPostBattle:
	.string "For a guy as macho as me, a port is the\n"
	.string "perfect setting!\p"
	.string "I guess I'll head for SLATEPORT.$"

Route110_Text_JacobIntro:
	.string "Whoa! Se dig for! Jeg gætter på, at du\n"
	.string "ikke er vant til at CYKLE race.$"

Route110_Text_JacobDefeated:
	.string "Whoa! Mine bremser virkede ikke!$"

Route110_Text_JacobPostBattle:
	.string "Flade dæk og bremseproblemer kan\n"
	.string "forårsage alvorlige skader! Tjek din\l"
	.string "CYKEL for problemer!$"

Route110_Text_AnthonyIntro:
	.string "Hej, du! Kan du følge med i mit tempo?$"

Route110_Text_AnthonyDefeated:
	.string "Crash and burn!$"

Route110_Text_AnthonyPostBattle:
	.string "Hastighed alene vil ikke lade mig vinde i\n"
	.string "POKéMON. Jeg er nødt til at genoverveje\l"
	.string "dette…$"

Route110_Text_BenjaminIntro:
	.string "Frygt ikke, hvis DIN CYKEL kører\n"
	.string "hurtigt!$"

Route110_Text_BenjaminDefeated:
	.string "Jeg skal ikke få panik under\n"
	.string "POKéMON-kampe…$"

Route110_Text_BenjaminPostBattle:
	.string "Der er ingen grund til panik eller\n"
	.string "stress. Tag det roligt. Der er masser af\l"
	.string "tid.$"

Route110_Text_BenjaminRegister:
	.string "Jeg vil blive ved med at tøffe afsted\n"
	.string "uden at stresse. Hvis du er klar til det,\l"
	.string "så råb op.$"

Route110_Text_BenjaminRematchIntro:
	.string "Er du ikke lidt for hurtig? Tag det\n"
	.string "roligt og lad os kæmpe.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Jeg panikkede ikke, men jeg tabte\n"
	.string "stadig…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Der er ingen grund til panik eller\n"
	.string "stress. Tag det roligt. Der er masser af\l"
	.string "tid.$"

Route110_Text_AbigailIntro:
	.string "Triatlonet er hårdt i den ekstreme.\p"
	.string "Du skal gennemføre de tre begivenheder\n"
	.string "med svømning, cykling og løb.$"

Route110_Text_AbigailDefeated:
	.string "POKéMON battles are hard, too!$"

Route110_Text_AbigailPostBattle:
	.string "Jeg er udmattet, så jeg har brug for en\n"
	.string "pause. Det er vigtigt at få ordentlig\l"
	.string "hvile.$"

Route110_Text_AbigailRegister:
	.string "Du er sød, ved du det? Skal vi have en\n"
	.string "revanche på CYKLING VEJ?$"

Route110_Text_AbigailRematchIntro:
	.string "Er det ikke sjovt at kæmpe mens du\n"
	.string "cykler?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow… Hvordan kunne du være så stærk?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Var du ude efter en rekord?\p"
	.string "Beklager, hvis jeg forsinkede dig!$"

Route110_Text_JasmineIntro:
	.string "Jeg har kørt uden at stoppe. Mine lår\n"
	.string "føles som sten!$"

Route110_Text_JasmineDefeated:
	.string "Jeg er bekymret for muskelkramper…$"

Route110_Text_JasminePostBattle:
	.string "Åh, har du nogle GYM BADGES? Ingen\n"
	.string "undskyldning for din styrke!$"

Route110_Text_EdwardIntro:
	.string "Jeg har forudset dine intentioner! Jeg\n"
	.string "kan simpelthen ikke tabe!$"

Route110_Text_EdwardDefeated:
	.string "Jeg mislykkedes i at forudsige min egen\n"
	.string "undergang!$"

Route110_Text_EdwardPostBattle:
	.string "Jeg ser din fremtid…\p"
	.string "Hmm… Jeg ser et skinnende lys…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha! Jeg vil forbløffe dig med\n"
	.string "mine undere!$"

Route110_Text_JaclynDefeated:
	.string "Jeg tabte vidunderligt!$"

Route110_Text_JaclynPostBattle:
	.string "Du formåede kun at vinde, fordi det er\n"
	.string "et mirakel! Ja, et mirakel! Tro ikke, at du\l"
	.string "kan vinde hver gang!$"

Route110_Text_EdwinIntro:
	.string "Må jeg se din POKéMON? Bare et kig, tak.$"

Route110_Text_EdwinDefeated:
	.string "Jeg ville gerne fuldføre min samling…$"

Route110_Text_EdwinPostBattle:
	.string "Når jeg ser en POKéMON, som jeg ikke\n"
	.string "kender, blusser min passion som samler\l"
	.string "op!$"

Route110_Text_EdwinRegister:
	.string "Jeg kan godt lide at samle MATCH CALL\n"
	.string "registreringer også…$"

Route110_Text_EdwinRematchIntro:
	.string "Hej, har du fanget nogle nye POKéMON?\p"
	.string "Må jeg se dine POKéMON? Bare et hurtigt\n"
	.string "kig, tak.$"

Route110_Text_EdwinRematchDefeated:
	.string "Dine POKéMON… Jeg misunder dig.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Åh, jeg længes efter at gøre alle\n"
	.string "sjældne POKéMON til mine!$"

Route110_Text_DaleIntro:
	.string "Hej! Du må ikke snige dig op bag mig på\n"
	.string "den måde!$"

Route110_Text_DaleDefeated:
	.string "Jeg tabte! Skidt!$"

Route110_Text_DalePostBattle:
	.string "At fiske handler om koncentration. Du\n"
	.string "skal fokusere på flåden.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha! Jeg ville gå hvor som helst for\n"
	.string "at vise mine dejlige POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Åh nej, dette går ikke.$"

Route110_Text_IsabelPostBattle:
	.string "I stedet for at kæmpe, burde jeg måske\n"
	.string "vise mine POKéMON frem i FANKLUBBEN.$"

Route110_Text_IsabelRegister:
	.string "Det var slet ikke tæt på, hvad jeg kan\n"
	.string "gøre for at vise mine POKéMON.\p"
	.string "Du vil være min fangete publikum så ofte\n"
	.string "som muligt!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! Jeg vil gerne vise mine\n"
	.string "POKéMON frem så tit du vil!$"

Route110_Text_IsabelRematchDefeated:
	.string "Åh, kære, dette går ikke. $"

Route110_Text_IsabelRematchPostBattle:
	.string "Jeg tror ikke, at jeg nogensinde ville\n"
	.string "kunne lade være med at vise mine\l"
	.string "POKéMON frem.\p"
	.string "Men jeg kan også godt lide at kæmpe!$"

Route110_Text_TimmyIntro:
	.string "Jeg fandt nogle seje POKéMON i græsset\n"
	.string "her omkring!$"

Route110_Text_TimmyDefeated:
	.string "At være sej er ikke nok til at vinde…$"

Route110_Text_TimmyPostBattle:
	.string "Det er svært at kæmpe med POKéMON, du\n"
	.string "lige har fanget.$"

Route110_Text_AlyssaIntro:
	.string "Jeg faldt af CYKLING ROAD…\p"
	.string "Jeg vil komme mig over min pinlighed ved\n"
	.string "at kæmpe med dig!$"

Route110_Text_AlyssaDefeated:
	.string "Ups! Jeg endte med at tabe!$"

Route110_Text_AlyssaPostBattle:
	.string "Falder… Taber… Det her er så ydmygende\n"
	.string "for mig!$"

Route110_Text_JosephIntro:
	.string "Okay! Fuldt fart fremad! Hvis du ikke\n"
	.string "kan være med, bliver du efterladt!$"

Route110_Text_JosephDefeated:
	.string "Du fik godt fat i rytmen…$"

Route110_Text_JosephPostBattle:
	.string "Det her kommer ikke til at slå mig ud! At\n"
	.string "tabe har gjort mig til en bedre mand!$"

Route110_Text_KalebIntro:
	.string "Når søde POKéMON hjælper hinanden… Kan\n"
	.string "du ikke se en mere nuttet syn!$"

Route110_Text_KalebDefeated:
	.string "Har du ingen medfølelse eller\n"
	.string "medlidenhed?$"

Route110_Text_KalebPostBattle:
	.string "Okay, okay, du gjorde dit bedste, mine\n"
	.string "skatte.$"

Route111_Text_DrewIntro:
	.string "Åh hej! De DER SOLBRILLER klær dig. Men\n"
	.string "jeg tror de ser bedre ud på mig.\p"
	.string "Lad os afgøre hvem de klæder bedst med\n"
	.string "en kamp!$"

Route111_Text_DrewDefeat:
	.string "Jeg kunne ikke se hvad der skete til\n"
	.string "siderne på grund af GO-BRILLERNE.$"

Route111_Text_DrewPostBattle:
	.string "GO-brillerne gør det muligt at komme\n"
	.string "igennem sandstorme. Det gør mig glad!$"

Route111_Text_HeidiIntro:
	.string "Jeg holder picnic i ørkenen.\p"
	.string "Der er altid en TRÆNER her, så jeg kan\n"
	.string "også nyde en kamp!$"

Route111_Text_HeidiDefeat:
	.string "Åh nej! Du er ond!$"

Route111_Text_HeidiPostBattle:
	.string "Når du kæmper i en sandstorm, så pas på\n"
	.string "din POKéMON's HP.\p"
	.string "Den kan besvime, hvis du ikke holder øje\n"
	.string "med den!$"

Route111_Text_BeauIntro:
	.string "At have disse GO-GOGGLES på gør mig\n"
	.string "føle mig som en superhelt. Lige nu kan\l"
	.string "ingen slå mig!$"

Route111_Text_BeauDefeat:
	.string "Jeg kan ikke vinde alene på vilje…$"

Route111_Text_BeauPostBattle:
	.string "En dag vil jeg blive en rigtig helt. Jeg\n"
	.string "vil arbejde hårdere for at gøre mig og\l"
	.string "mine POKéMON stærkere.$"

Route111_Text_BeckyIntro:
	.string "Jeg har hørt, at der er fossiler at finde\n"
	.string "i ørkenen. Hvor mon de er?$"

Route111_Text_BeckyDefeat:
	.string "Jeg var ikke god nok…$"

Route111_Text_BeckyPostBattle:
	.string "Hvis de kan finde fossiler i desertet,\n"
	.string "må det have været et hav før.$"

Route111_Text_DustyIntro:
	.string "I tredive år har jeg ledt efter gamle\n"
	.string "ruiner! Er jeg klar til en udfordring?$"

Route111_Text_DustyDefeat:
	.string "Mens jeg har ledt efter ruiner, har jeg\n"
	.string "ikke ledt efter stærke POKéMON.$"

Route111_Text_DustyPostBattle:
	.string "I tredive år har jeg ledt efter gamle\n"
	.string "ruiner!\p"
	.string "Nej, vent, var det fyrre år? Hvad var\n"
	.string "det nu?$"

Route111_Text_DustyRegister:
	.string "Jeg har ikke ledt efter nogen seje\n"
	.string "POKéMON.\p"
	.string "Men af en eller anden grund kan jeg\n"
	.string "godt lide POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "I tredive år har jeg ledt efter gamle\n"
	.string "ruiner!\p"
	.string "Vent, var det fyrre år? Nå, skal jeg\n"
	.string "udfordres?$"

Route111_Text_DustyRematchDefeat:
	.string "Jeg har fundet ingen ruiner, og heller\n"
	.string "ingen stærke POKéMON…$"

Route111_Text_DustyPostRematch:
	.string "I tredive år har jeg ledt efter gamle\n"
	.string "ruiner!\p"
	.string "Nej, vent, var det fyrre år, jeg har\n"
	.string "ledt?\p"
	.string "Hm… Det kunne endda være halvtreds…\n"
	.string "Hvor længe har jeg holdt på?$"

Route111_Text_TravisIntro:
	.string "Jeg sprudler af energi! Og min POKéMON\n"
	.string "er også fuld af gejst!$"

Route111_Text_TravisDefeat:
	.string "Min POKéMON har mistet sin gnist…$"

Route111_Text_TravisPostBattle:
	.string "Når jeg ser en TRÆNER med masser af\n"
	.string "energi, kan jeg ikke lade være med at\l"
	.string "kigge.$"

Route111_Text_IreneIntro:
	.string "Jeg ved ikke, hvor du er på vej hen, men\n"
	.string "vil du gerne kæmpe?$"

Route111_Text_IreneDefeat:
	.string "Åh, du er afskyeligt god!$"

Route111_Text_IrenePostBattle:
	.string "Jeg tænker på, at jeg burde tage til MT.\n"
	.string "CHIMNEY, men udsigten her er også meget\l"
	.string "flot.$"

Route111_Text_DaisukeIntro:
	.string "For at træne mig selv, udfordrer jeg alle\n"
	.string "jeg møder!$"

Route111_Text_DaisukeDefeat:
	.string "Onkel! Jeg giver op!$"

Route111_Text_DaisukePostBattle:
	.string "Alt jeg kan gøre, er at blive ved med at\n"
	.string "træne, indtil jeg kan besejre stærke\l"
	.string "TRÆNERE som dig.$"

Route111_Text_WiltonIntro:
	.string "Vis mig, hvor meget du har styrketdine\n"
	.string "POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "Jeg kan se, du har gjort dem betydeligt\n"
	.string "stærkere.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMON og TRÆNERE lærer meget gennem\n"
	.string "at kæmpe.\p"
	.string "Det vigtigste er aldrig at give op\n"
	.string "selvom du taber.$"

Route111_Text_WiltonRegister:
	.string "Der er meget at lære fra din\n"
	.string "træningsstil.\p"
	.string "Jeg beder om en revanche, hvis det\n"
	.string "passer dig.$"

Route111_Text_WiltonRematchIntro:
	.string "Vi træner her for at hæve vores spil til\n"
	.string "næste niveau. Bliv og træn med os!$"

Route111_Text_WiltonRematchDefeat:
	.string "Åh, du er habil!$"

Route111_Text_WiltonPostRematch:
	.string "Da du er så stærk, bør du sigte efter\n"
	.string "POKéMON LIGAEN.$"

Route111_Text_BrookeIntro:
	.string "Åh, dine POKéMON ser ud som alvorlige\n"
	.string "skuespillere. Jeg er nødt til at bede om\l"
	.string "en kamp.$"

Route111_Text_BrookeDefeat:
	.string "De så ikke bare stærke ud, de er stærke!$"

Route111_Text_BrookePostBattle:
	.string "Jeg troede, at jeg opdrættede mine\n"
	.string "POKéMON omhyggeligt, men nej, der er\l"
	.string "stadig meget at gøre.$"

Route111_Text_BrookeRegister:
	.string "Jeg ville ønske, jeg kunne blive venner\n"
	.string "med flere stærke mennesker som dig!$"

Route111_Text_BrookeRematchIntro:
	.string "Du kan gøre POKéMON stærkere eller\n"
	.string "svagere afhængigt af de angreb, du lærer\l"
	.string "dem.\p"
	.string "Hvilke typer af angreb kender dine\n"
	.string "POKéMON?$"

Route111_Text_BrookeRematchDefeat:
	.string "Du har lært dem gode træk!$"

Route111_Text_BrookePostRematch:
	.string "Måske skulle jeg have stoppet min\n"
	.string "POKéMON fra at udvikle sig, indtil de\l"
	.string "lærte bedre angreb…$"

Route111_Text_CeliaIntro:
	.string "Jeg burde ikke være kommet til et sted\n"
	.string "som dette for en picnic!$"

Route111_Text_CeliaDefeat:
	.string "Åh nej! Jeg skulle virkelig ikke være\n"
	.string "kommet!$"

Route111_Text_CeliaPostBattle:
	.string "I en sandstorm som denne kan jeg ikke\n"
	.string "engang med mine GÅPÅ-DIG-briller finde\l"
	.string "et sted til en picnic…$"

Route111_Text_BryanIntro:
	.string "Hvor sej er du? Vi skal afsløre den\n"
	.string "hemmelighed!$"

Route111_Text_BryanDefeat:
	.string "Åh! Din styrke! Den er indhyllet i\n"
	.string "mystik!$"

Route111_Text_BryanPostBattle:
	.string "Denne ørken gemmer på mysterier i dens\n"
	.string "skiftende sand!$"

Route111_Text_BrandenIntro:
	.string "Jeg giver dig lidt af min sandwich hvis\n"
	.string "du taber.$"

Route111_Text_BrandenDefeat:
	.string "Tch! Jeg troede en sandwich ville være\n"
	.string "nok som bestikkelse…$"

Route111_Text_BrandenPostBattle:
	.string "Min SANDSHREW elsker at spise mine\n"
	.string "sandwiches.$"

Route111_Text_TyronIntro:
	.string "Dette er min yndlingstype af POKéMON!$"

Route111_Text_TyronDefeat:
	.string "Vent! Fik du et godt kig på mine\n"
	.string "POKéMON?$"

Route111_Text_TyronPostBattle:
	.string "Når man har en kamp, får jeg en kick ud\n"
	.string "af at vise mine POKéMON.\p"
	.string "Jeg satser på, at alle føler det sådan,\n"
	.string "når de går ind i en kamp!$"

Route111_Text_CelinaIntro:
	.string "Vis mig, hvordan jeg kan få lidt\n"
	.string "spænding ind i mit liv.$"

Route111_Text_CelinaDefeat:
	.string "Åh… Min… Det var for meget spænding.$"

Route111_Text_CelinaPostBattle:
	.string "Mit hjerte hamrer stadig. Du er en\n"
	.string "fantastisk TRÆNER.$"

Route111_Text_HaydenIntro:
	.string "Når du er lige så sultet som jeg er, er\n"
	.string "der ingen plads til medlidenhed!$"

Route111_Text_HaydenDefeat:
	.string "Åh nej…$"

Route111_Text_HaydenPostBattle:
	.string "Min mave knurrer! Måske kan jeg grille\n"
	.string "nogle BÆR…$"

Route111_Text_BiancaIntro:
	.string "Kom du fra MAUVILLE? Så burde du være\n"
	.string "fuld af energi!$"

Route111_Text_BiancaDefeat:
	.string "Åh la la! Det' en masse at tage!$"

Route111_Text_BiancaPostBattle:
	.string "Denne vej her… Du har stadig en god bid.$"

Route112_Text_BriceIntro:
	.string "Hahahaha! Hvad siger du til en kamp?\p"
	.string "Dig og mig!\p"
	.string "Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "Jeg tabte! Hahahaha!$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha! Noget fløj op i min næse!\n"
	.string "Hahahaha-apsju!$"

Route112_Text_TrentIntro:
	.string "Mine ben er solide fra at hamre op og\n"
	.string "ned af bjergene.\p"
	.string "De vil ikke bukke let, ven!$"

Route112_Text_TrentDefeat:
	.string "Av! Mine ben kramper!$"

Route112_Text_TrentPostBattle:
	.string "Prøv vandring, og jeg mener virkelig at\n"
	.string "hamre løs på disse bjergstier med en\l"
	.string "tung rygsæk, der vejer dusinvis af pund.\p"
	.string "Det, min ven, vil få din krop i seriøs\n"
	.string "form.$"

Route112_Text_TrentRegister:
	.string "Av, mine ben er blevet krampagtige. Kan\n"
	.string "du hente nogle bandager fra min rygsæk?\p"
	.string "Nej, det er min POKéNAV! Nå, fint, jeg vil\n"
	.string "nok registrere dig.$"

Route112_Text_TrentRematchIntro:
	.string "Jeg har holdt mig i form ved at vandre.\n"
	.string "Kraft, det har jeg i massevis!$"

Route112_Text_TrentRematchDefeat:
	.string "Jeg blev overhalet i styrke!$"

Route112_Text_TrentRematchPostBattle:
	.string "Jeg hører, at der er nogle virkelig seje\n"
	.string "TRÆNERE på toppen af MT. CHIMNEY.\p"
	.string "Jeg har tænkt mig at komme derop og\n"
	.string "udfordre dem!$"

Route112_Text_LarryIntro:
	.string "Jeg er stærk. Jeg vil ikke græde, hvis\n"
	.string "jeg taber.$"

Route112_Text_LarryDefeat:
	.string "Waaaah!$"

Route112_Text_LarryPostBattle:
	.string "Jeg græder ikke, fordi jeg savner min\n"
	.string "mor! Hulke…$"

Route112_Text_CarolIntro:
	.string "Når du er ude at picnicke, så må du bare\n"
	.string "synge løs! Kom nu, syng med mig!$"

Route112_Text_CarolDefeat:
	.string "Åh, du er så stærk!$"

Route112_Text_CarolPostBattle:
	.string "Det betyder ikke noget, om du er god\n"
	.string "eller dårlig til at synge eller POKéMON.\p"
	.string "Hvis du har det sjovt, vinder du!$"

Route112_Text_BryantIntro:
	.string "Jeg fangede varme POKéMON på FYREDE\n"
	.string "STI! Tag et kig!$"

Route112_Text_BryantDefeat:
	.string "For en bumpet tur det var!$"

Route112_Text_BryantPostBattle:
	.string "Jeg kan lide den måde, du kæmper på. Der\n"
	.string "er en vis elegance i det.$"

Route112_Text_ShaylaIntro:
	.string "Åh, er du ikke en sød TRÆNER! Kom nu, jeg\n"
	.string "har brug for en romantisk duel! Jeg er\l"
	.string "rimelig god til det!$"

Route112_Text_ShaylaDefeat:
	.string "Hvor er du stærk! Du har virkelig\n"
	.string "overrasket mig!$"

Route112_Text_ShaylaPostBattle:
	.string "Er du optaget lige nu? Jeg tænkte på, om\n"
	.string "vi måske kan have en omkamp lige nu… Men\l"
	.string "det er okay, hvis du er optaget.$"

Route113_Text_JaylenIntro:
	.string "Kan du gætte hvorfor det er så fedt her\n"
	.string "omkring?$"

Route113_Text_JaylenDefeat:
	.string "Peeuuw! Det stinker!$"

Route113_Text_JaylenPostBattle:
	.string "Vulkanasken blokerer solen, så det\n"
	.string "bliver ikke så varmt.\p"
	.string "Det er godt for mig - jeg kan ikke lide\n"
	.string "varme!$"

Route113_Text_DillonIntro:
	.string "Vulkanens udbrud er bevis på, at jorden\n"
	.string "er i live.$"

Route113_Text_DillonDefeat:
	.string "Du er virkelig stærk!$"

Route113_Text_DillonPostBattle:
	.string "Av! Øv! Jeg kan ikke se! Jeg har fået\n"
	.string "aske i mine øjenvipper!\p"
	.string "Forstår du? Aske og øjenvipper?\p"
	.string "Nå, det var dårligt, undskyld…$"

Route113_Text_MadelineIntro:
	.string "Jeg bruger denne parasol til at skærme\n"
	.string "mig mod den beskidte, ulækre vulkanaske\l"
	.string "fra min kære NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "Puha, puha… Jeg er udmattet…$"

Route113_Text_MadelinePostBattle:
	.string "Du er meget god til dette. Jeg må sige,\n"
	.string "jeg er imponeret!$"

Route113_Text_MadelineRegister:
	.string "Her, kravl under min parasol. Lad mig\n"
	.string "registrere dig i min POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Hej, har det ikke været et stykke tid?\n"
	.string "Må jeg invitere dig til kamp?$"

Route113_Text_MadelineRematchDefeat:
	.string "Åh, hvor super!$"

Route113_Text_MadelinePostRematch:
	.string "Du er forbløffende god til dette. Jeg må\n"
	.string "sige, jeg er imponeret!$"

Route113_Text_LaoIntro:
	.string "Fra asken springer jeg ud! Hiyah! Jeg\n"
	.string "udfordrer dig!$"

Route113_Text_LaoDefeat:
	.string "Med ære indrømmer jeg nederlag!$"

Route113_Text_LaoPostBattle:
	.string "Jeg skal forfine kunsten at skjule mig.\n"
	.string "Jeg siger farvel.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Oplev den gamle ninja- teknik\n"
	.string "til POKéNAV-registrering!$"

Route113_Text_LaoRematchIntro:
	.string "Fra ud af asken springer jeg! Hiyah! Jeg\n"
	.string "udfordrer dig!$"

Route113_Text_LaoRematchDefeat:
	.string "Med ære erkender jeg mit nederlag!$"

Route113_Text_LaoPostRematch:
	.string "Min fejlfri skjul blev afsløret af mine\n"
	.string "umodne kampfærdigheder…\p"
	.string "Jeg siger farvel.$"

Route113_Text_LungIntro:
	.string "Tak fordi du fandt mig! Men vi skal\n"
	.string "stadig kæmpe!$"

Route113_Text_LungDefeat:
	.string "Jeg vil bruge min ninjutsu på dig…\n"
	.string "“VULKANISK ASKE VIRVELKAPSEL”!\p"
	.string "…Hvad? Er det allerede slut?$"

Route113_Text_LungPostBattle:
	.string "Ved du hvad der er nederen ved at gemme\n"
	.string "sig? Det er ensomt, hvis ingen kommer\l"
	.string "forbi.$"

Route113_Text_ToriIntro:
	.string "TORI: Vi samler begge to aske. Vi kæmper\n"
	.string "også med POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI: Vi tabte… Det er kedeligt, så jeg\n"
	.string "går for at få lidt flere aske.$"

Route113_Text_ToriPostBattle:
	.string "TORI: Hvor meget aske har vi?\n"
	.string "Forhåbentlig nok til en HVID FLØJTE.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: Vi vil kæmpe 2 mod 2. Hvis vi ikke\n"
	.string "gjorde det, ville vi tabe!$"

Route113_Text_TiaIntro:
	.string "TIA: Begge to samler vi aske. Vi kæmper\n"
	.string "også mod POKéMON.$"

Route113_Text_TiaDefeat:
	.string "TIA: Vi kunne ikke vinde… Det er\n"
	.string "kedeligt, så jeg henter lidt mere aske.$"

Route113_Text_TiaPostBattle:
	.string "TIA: Vi har en masse aske! Jeg tror, at\n"
	.string "det er nok til enHVID FLØJTE!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: Vi vil kæmpe 2 mod 2. Ellers vinder\n"
	.string "vi ikke!$"

Route113_Text_CobyIntro:
	.string "Pfft, med disse vinger kan jeg bare give\n"
	.string "dig et lille  skub!$"

Route113_Text_CobyDefeat:
	.string "Hvad en… Hvad?$"

Route113_Text_CobyPostBattle:
	.string "Jeg ved ikke hvad jeg skal sige, når jeg\n"
	.string "bliver slået så let…$"

Route113_Text_SophieIntro:
	.string "Varmen her gør mig søvnig. Kæmp imod mig,\n"
	.string "så jeg kan holde mig vågen.$"

Route113_Text_SophieDefeat:
	.string "Dette er en drøm. Det er jeg sikker på…$"

Route113_Text_SophiePostBattle:
	.string "At tabe brænder mig op… Jeg vil bare\n"
	.string "sove lige her! Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Var du måske midt i at samle vulkansk\n"
	.string "aske?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe. Vi blev slået rent.$"

Route113_Text_LawrencePostBattle:
	.string "Jeg burde gemme mig under asken også.$"

Route113_Text_WyattIntro:
	.string "V-Vil du kæmpe med mig? Selvom jeg lige\n"
	.string "har fanget min POKéMON?$"

Route113_Text_WyattDefeat:
	.string "Er I alle glade for at vinde? Selvom det\n"
	.string "kun er mig?$"

Route113_Text_WyattPostBattle:
	.string "Åh, så vil du pludselig sige et ord til\n"
	.string "taberen?\p"
	.string "Er du ikke bare den sejeste? Humph!$"

Route114_Text_LennyIntro:
	.string "Jodeladidejhuu!\p"
	.string "… …\p"
	.string "Du skulle råbe “jodeladidejhuu” da det\n"
	.string "ikke giver eko her!$"

Route114_Text_LennyDefeat:
	.string "Jodelajuhuu!$"

Route114_Text_LennyPostBattle:
	.string "Da jeg var en lille rapscallion, troede\n"
	.string "jeg, at der var nogen, der kopierede mig\l"
	.string "og råbte tilbage, “Jodelayhihoo.”$"

Route114_Text_LucasIntro:
	.string "Hvis du ikke er forberedt, skal du ikke\n"
	.string "være oppe i bjergene!$"

Route114_Text_LucasDefeat:
	.string "Bjergene er ubarmhjertige…$"

Route114_Text_LucasPostBattle:
	.string "Om vinteren bliver bjerge dødbringende\n"
	.string "med snestorme og laviner.$"

Route114_Text_ShaneIntro:
	.string "Camping er sjovt! Du kan fiske, riste\n"
	.string "skumfiduser og fortælle  uhyggelige\l"
	.string "historier!\p"
	.string "Men det bedste af det hele er POKéMON\n"
	.string "kampe!$"

Route114_Text_ShaneDefeat:
	.string "Alt for stærk!$"

Route114_Text_ShanePostBattle:
	.string "Jeg synes, det er fantastisk, at jeg\n"
	.string "kan tage på telteventyr med mine\l"
	.string "POKéMON.$"

Route114_Text_NancyIntro:
	.string "Jeg skal have motion efter et måltid.\n"
	.string "Skal vi have en kamp?$"

Route114_Text_NancyDefeat:
	.string "Åh nej!$"

Route114_Text_NancyPostBattle:
	.string "Jeg havde lige et lækkert måltid. Jeg\n"
	.string "bliver søvnig…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu… Vil du kæmpe mod mine\n"
	.string "POKéMON?$"

Route114_Text_SteveDefeat:
	.string "M-Min POKéMON…$"

Route114_Text_StevePostBattle:
	.string "En stor krop, der er helt klumpet og\n"
	.string "hård, kæmpestore horn og farlige\l"
	.string "tænder…\p"
	.string "Ufufufufu… Jeg ønsker, jeg havde en\n"
	.string "POKéMON som den…$"

Route114_Text_SteveRegister:
	.string "Glem ikke hvad du har gjort imod mig!\n"
	.string "Jeg vil sørge for, at du ikke kan glemme\l"
	.string "det!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu… Kom så, kæmp mod mine\n"
	.string "POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "Jeg føler mig så heldig, at jeg får lov\n"
	.string "til at se dine POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Når jeg ser POKéMON kæmpe, bliver jeg\n"
	.string "helt forskrækket og rystet…$"

Route114_Text_BernieIntro:
	.string "Hvis du tænder et bål, sørg for at have\n"
	.string "vand ved hånden.$"

Route114_Text_BernieDefeat:
	.string "Tak for at slukke min ild!$"

Route114_Text_BerniePostBattle:
	.string "Man skal virkelig passe på med ild i en\n"
	.string "skov.\p"
	.string "Undervurdér aldrig kraften af ilden.$"

Route114_Text_BernieRegister:
	.string "Du sætter mit sind i brand. Lad os\n"
	.string "registrere hinanden!$"

Route114_Text_BernieRematchIntro:
	.string "Har du lært at have vand ved hånden til\n"
	.string "bål? $"

Route114_Text_BernieRematchDefeat:
	.string "Jeg fik sprøjtet ned, før jeg kunne\n"
	.string "antænde, tror jeg.$"

Route114_Text_BerniePostRematch:
	.string "Du skal virkelig passe på med ild i en\n"
	.string "skov.\p"
	.string "Undervurder aldrig kraften af ilden.$"

Route114_Text_ClaudeIntro:
	.string "Hvis vi var at fiske, ville du ikke have\n"
	.string "en chance imod mig. Så kom med dine\l"
	.string "POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "Hvis vi havde været til at fiske, ville\n"
	.string "jeg have vundet…$"

Route114_Text_ClaudePostBattle:
	.string "Jeg tror, jeg vil prøve lykken med at\n"
	.string "fange en stor fisk ved METEOR FALLS.\p"
	.string "Der må være noget godt derinde. Jeg kan\n"
	.string "bare mærke det.$"

Route114_Text_NolanIntro:
	.string "Jeg kan godt lide at fiske. Men jeg  kan\n"
	.string "også godt lide at kæmpe!\p"
	.string "Hvis nogen udfordrer mig, er jeg  klar,\n"
	.string "selv når jeg fisker.$"

Route114_Text_NolanDefeat:
	.string "Jeg kan godt lide at kæmpe, men det\n"
	.string "betyder ikke, at jeg er god til det…$"

Route114_Text_NolanPostBattle:
	.string "Denne gang gør jeg det!\p"
	.string "Jeg tænker altid det, så jeg kan ikke gå\n"
	.string "væk fra fiskeri eller POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Nå, selvfølgelig. Jeg er i humør til\n"
	.string "det. Jeg vil lære dig lidt om POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: Sikken en fantastisk kampstil!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Jeg underviste min junior IVY om\n"
	.string "POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Grin… Hvis du vil kæmpe med os, er\n"
	.string "bare én POKéMON ikke nok!$"

Route114_Text_IvyIntro:
	.string "IVY: Hvem lærte dig om POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: Sikke en fantastisk kampstil!$"

Route114_Text_IvyPostBattle:
	.string "IVY: Jeg begyndte at træne POKéMON\n"
	.string "fordi TYRA, min studerende mentor, lærte\l"
	.string "mig!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Har du kun én POKéMON? Det må være\n"
	.string "ensomt.$"

Route114_Text_KaiIntro:
	.string "Jeg har fanget en kæmpe fisk! En kæmpe\n"
	.string "fisk, jeg siger dig!$"

Route114_Text_KaiDefeat:
	.string "Hvad var det for noget? Tabte min i\n"
	.string "størrelse?$"

Route114_Text_KaiPostBattle:
	.string "Okay! Jeg vil bare fiske mig en større\n"
	.string "en!$"

Route114_Text_CharlotteIntro:
	.string "Mig! Jeg er ikke bare et pænt ansigt!$"

Route114_Text_CharlotteDefeat:
	.string "Det var overhovedet ikke sødt!$"

Route114_Text_CharlottePostBattle:
	.string "Jeg vil ikke have en POKéMON, der bare\n"
	.string "er sød.\p"
	.string "Jeg ELSKER søde, der har et par\n"
	.string "særegenheder!$"

Route114_Text_AngelinaIntro:
	.string "Har dine POKéMON udviklet sig meget?$"

Route114_Text_AngelinaDefeat:
	.string "Åh, jeg ser. Det er godt at vide.$"

Route114_Text_AngelinaPostBattle:
	.string "Nogle POKéMON ændrer sig så meget, når\n"
	.string "de udvikler sig, det er overraskende!$"

Route115_Text_TimothyIntro:
	.string "Hm… Du virker ret kompetent… Lad mig\n"
	.string "følge med dig!$"

Route115_Text_TimothyDefeat:
	.string "Du er meget stærkere end jeg havde\n"
	.string "forestillet mig!$"

Route115_Text_TimothyPostBattle:
	.string "Der findes ikke noget der hedder en\n"
	.string "født geni. Det hele afhænger af\l"
	.string "indsatsen! Det er hvad jeg tror…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Et tab så grundigt har været et\n"
	.string "fjernt minde.\p"
	.string "Hvis du tillader det, ønsker jeg en\n"
	.string "anden mulighed for at kæmpe.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Som altid taler din smidighed for\n"
	.string "dig selv. Kom, hold mig med selskab!$"

Route115_Text_TimothyRematchDefeat:
	.string "Stærk som altid!$"

Route115_Text_TimothyPostRematch:
	.string "Alt hvad der kræves, er anstrengelse!\p"
	.string "Jeg tabte, fordi jeg ikke har lagt nok\n"
	.string "anstrengelse!$"

Route115_Text_KoichiIntro:
	.string "Dig!\p"
	.string "Min MACHOP!\p"
	.string "Kræver en kamp!$"

Route115_Text_KoichiDefeat:
	.string "Av av av!$"

Route115_Text_KoichiPostBattle:
	.string "Min MACHOP-bande!\p"
	.string "Så længe de søger styrke, vil jeg vokse\n"
	.string "mig stærk med dem!$"

Route115_Text_NobIntro:
	.string "Min største færdighed er at knuse\n"
	.string "mursten med min pande!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah! Mit hoved er smadret!$"

Route115_Text_NobPostBattle:
	.string "Jeg har undervist mine POKéMON i\n"
	.string "karate.\p"
	.string "Det ser ud til, at de vil blive meget\n"
	.string "bedre end mig. Jeg er spændt på det.$"

Route115_Text_NobRegister:
	.string "Du imponerer mig! Giv mig en ny kamp når\n"
	.string "jeg har trænet om!$"

Route115_Text_NobRematchIntro:
	.string "Efter at du slog mig, har vi trænet\n"
	.string "hårdt for at forbedre vores\l"
	.string "færdigheder. Kom nu, giv os en revanche!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah! Vi tabte igen!$"

Route115_Text_NobPostRematch:
	.string "Mine POKéMON vil blive stærkere! Jeg vil\n"
	.string "fordoble min træning!$"

Route115_Text_CyndyIntro:
	.string "Denne strand er mit hemmelige\n"
	.string "træningssted! Du skal ikke blande dig!$"

Route115_Text_CyndyDefeat:
	.string "Jeg har ikke trænet nok!$"

Route115_Text_CyndyPostBattle:
	.string "Sandet virker som en pude for at\n"
	.string "reducere stød og forhindre skader.\l"
	.string "Dette er det perfekte sted at træne.$"

Route115_Text_CyndyRegister:
	.string "Okay, fine, you're free to come here. In\n"
	.string "return, I'd like to battle you again.$"

Route115_Text_CyndyRematchIntro:
	.string "Okay, let's get this battle on!$"

Route115_Text_CyndyRematchDefeat:
	.string "Jeg kan kæmpe, men mine POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Selv når jeg taber, får jeg stadig lidt\n"
	.string "glæde ud af det. Det må være fordi, jeg\l"
	.string "elsker POKéMON.$"

Route115_Text_HectorIntro:
	.string "Jeg har en sjælden POKéMON! Vil du gerne\n"
	.string "se den?$"

Route115_Text_HectorDefeat:
	.string "Du… Du vil have min POKéMON, ikke sandt?$"

Route115_Text_HectorPostBattle:
	.string "Jeg har denne sjældne POKéMON. Det er\n"
	.string "nok til at tilfredsstille mig.$"

Route115_Text_KyraIntro:
	.string "Jeg vil kæmpe, mens jeg løber! Prøv at\n"
	.string "følge med mig!$"

Route115_Text_KyraDefeat:
	.string "Pust, pust…$"

Route115_Text_KyraPostBattle:
	.string "Jeg lavede den fejl at prøve at kæmpe\n"
	.string "mens jeg løb!\p"
	.string "Jeg burde tage en løbetur for at falde\n"
	.string "til ro…$"

Route115_Text_JaidenIntro:
	.string "Tag den! Ultra POKéMON ninja angreb!$"

Route115_Text_JaidenDefeat:
	.string "Åh nej! Vores strategi fejlede!$"

Route115_Text_JaidenPostBattle:
	.string "Men mine POKéMON var ultra, ikke sandt?$"

Route115_Text_HeleneIntro:
	.string "Mine POKéMON har styrke på\n"
	.string "sortbælte-niveau!$"

Route115_Text_HeleneDefeat:
	.string "Det her er alt for ydmygende!$"

Route115_Text_HelenePostBattle:
	.string "Jeg møder sjældent nogen, der er bedre\n"
	.string "end mig…\p"
	.string "Jeg forstår det nu! Du er en GYM LEADER,\n"
	.string "ikke sandt?$"

Route115_Text_AlixIntro:
	.string "Vores øjne mødtes! Der er ingen\n"
	.string "undslipning nu!$"

Route115_Text_AlixDefeat:
	.string "Av! Ikke dårligt!$"

Route115_Text_AlixPostBattle:
	.string "Nå, nå. Jeg tror jeg vil TELEPORTERE\n"
	.string "hjem.$"

Route115_Text_MarleneIntro:
	.string "Du har forstyrret min meditation… Du vil\n"
	.string "blive straffet for det.$"

Route115_Text_MarleneDefeat:
	.string "Du har ødelagt min koncentration!$"

Route115_Text_MarlenePostBattle:
	.string "Jeg var i meditationsform med mine\n"
	.string "POKéMON. Men dette sted er ikke særlig\l"
	.string "fredeligt…$"

Route116_Text_ClarkIntro:
	.string "Hvis tunnelen ikke går igennem, så skal\n"
	.string "jeg bare gå over toppen.$"

Route116_Text_ClarkDefeat:
	.string "Hov… Hov… At tabe gjorde mig træt…$"

Route116_Text_ClarkPostBattle:
	.string "Det er ingen big deal, hvis der ikke er\n"
	.string "nogen tunnel. For en VANDRER er bjerge\l"
	.string "veje!$"

Route116_Text_JoeyIntro:
	.string "Mine POKéMON regerer! Kom og se dem!$"

Route116_Text_JoeyDefeat:
	.string "Av! Et skrammel! Jeg skal sætte et\n"
	.string "plaster på!$"

Route116_Text_JoeyPostBattle:
	.string "Forbindinger er tegn på sejhed! Jeg har\n"
	.string "en mere!$"

Route116_Text_JoseIntro:
	.string "Mine BILLE POKéMON er seje! Lad os\n"
	.string "kæmpe!$"

Route116_Text_JoseDefeat:
	.string "Jeg tabte! Jeg troede, jeg havde dig!$"

Route116_Text_JosePostBattle:
	.string "INSEKT POKéMON udvikler sig hurtigt. Så\n"
	.string "de bliver også hurtigt stærke.$"

Route116_Text_JaniceIntro:
	.string " Lad mig lære dig, hvor stærk min  SØD\n"
	.string "POKéMON er!$"

Route116_Text_JaniceDefeat:
	.string "Du er et hak over mig…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON, der besidder sødme og styrke,\n"
	.string "det er ideelt, synes jeg.$"

Route116_Text_JerryIntro:
	.string "Vi lærer alle mulige ting på TRÆNERENS\n"
	.string "SKOLE.\p"
	.string "Jeg vil teste tingene i virkeligheden!$"

Route116_Text_JerryDefeat:
	.string "Jeg pjækkede i skolen… Det er derfor,\n"
	.string "jeg tabte.$"

Route116_Text_JerryPostBattle:
	.string "Jeg bliver nødt til at tage nogle kurser\n"
	.string "på TRÆNERENS SKOLE. Hvis ikke, bliver\l"
	.string "ROXANNE skuffet.$"

Route116_Text_JerryRegister1:
	.string "Jeg lærte på TRÆNERENS SKOLE at en\n"
	.string "POKéNAV kan registrere TRÆNERE.\p"
	.string "Jeg forstår ikke rigtigt, hvad det\n"
	.string "betyder, så kan jeg bare prøve det?$"

Route116_Text_JerryRegister2:
	.string "Jeg lærte på TRÆNER-SKOLEN at en\n"
	.string "POKéNAV kan registrere TRÆNERE.\p"
	.string "Jeg forstår ikke rigtigt hvad det\n"
	.string "betyder, så kan jeg bare prøve det?$"

Route116_Text_JerryRematchIntro:
	.string "Jeg har studeret seriøst på TRÆNERENS\n"
	.string "SKOLE. Jeg vil ikke tabe som sidste gang.$"

Route116_Text_JerryRematchDefeat:
	.string "Hvad? Jeg har læst flittigt.$"

Route116_Text_JerryPostRematch:
	.string "Jeg bliver nødt til at gøre nogle kurser\n"
	.string "om på TRÆNER-SKOLEN. Ellers bliver\l"
	.string "ROXANNE bestemt irriteret.$"

Route116_Text_KarenIntro:
	.string "Jeg studerer i skolen, og jeg studerer\n"
	.string "også på vejen hjem!$"

Route116_Text_KarenDefeat:
	.string "Jeg er i chok--jeg tabte?$"

Route116_Text_KarenPostBattle:
	.string "Åh nej, jeg bliver aldrig en elegant\n"
	.string "TRÆNER som ROXANNE på den måde!$"

Route116_Text_KarenRegister1:
	.string "Åh, wow! Er det ikke en POKéNAV? Jeg har\n"
	.string "også en! Vil du registrere mig?$"

Route116_Text_KarenRegister2:
	.string "Åh, wow! Er det ikke en POKéNAV? Jeg har\n"
	.string "også en! Registrér mig, venligst!$"

Route116_Text_KarenRematchIntro:
	.string "Jeg har læst utroligt meget, siden jeg\n"
	.string "så dig. Du skal se mine resultater!$"

Route116_Text_KarenRematchDefeat:
	.string "Jeg er i chok. Jeg tabte igen?$"

Route116_Text_KarenPostRematch:
	.string "Du slog ROXANNE? Jeg kan ikke slå dig\n"
	.string "endnu. Ikke endnu.$"

Route116_Text_SarahIntro:
	.string "Bare så du ved det, jeg er aldrig blevet\n"
	.string "slået af nogen i noget.$"

Route116_Text_SarahDefeat:
	.string "Åh, min gode. Det her er en ny oplevelse\n"
	.string "for mig.$"

Route116_Text_SarahPostBattle:
	.string "Mit liv i luksus giver mig alt, hvad jeg\n"
	.string "kunne ønske mig.\p"
	.string "Dog, når det kommer til POKéMON, har min\n"
	.string "rigdom ingen betydning.$"

Route116_Text_DawsonIntro:
	.string "Når du lægger dine øjne på min POKéMONs\n"
	.string "smukke pels, vil deres skønhed gøre dig\l"
	.string "magtesløs!$"

Route116_Text_DawsonDefeat:
	.string "Åh, lille skat, sig det ikke er sandt!$"

Route116_Text_DawsonPostBattle:
	.string "Åh nej, nej, nej! Du har rodet min\n"
	.string "POKéMONs pels til! Du har også ødelagt\l"
	.string "mit frisure! Jeg bliver nødt til at ringe\l"
	.string "til min stylist nu!$"

Route116_Text_DevanIntro:
	.string "Vi vil rocke dig hårdt!$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi! Overhovedet ingen konkurrence!$"

Route116_Text_DevanPostBattle:
	.string "Jeg burde prøve forskellige\n"
	.string "POKéMON-typer, det er hvad jeg burde\l"
	.string "gøre.$"

Route116_Text_JohnsonIntro:
	.string "Det er en blindgyde heroppe. Jeg keder\n"
	.string "mig, så skal vi kæmpe?$"

Route116_Text_JohnsonDefeat:
	.string "Det var sjovt, selvom jeg tabte.$"

Route116_Text_JohnsonPostBattle:
	.string "Vil du blive her og hygge dig med mig?$"

Route117_Text_IsaacIntro:
	.string "Hør her, kunne jeg få dig til at kæmpe\n"
	.string "mod de POKéMON, jeg opdrætter?$"

Route117_Text_IsaacDefeat:
	.string "Du har opdraget din strålende…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON handler ikke kun om styrke.\p"
	.string "At finpudse en unik side af ens\n"
	.string "karakter er en anden måde at nyde\l"
	.string "POKéMON på.$"

Route117_Text_IsaacRegister:
	.string "Jeg vil fordoble min træning. Vil du\n"
	.string "kigge ind på os?$"

Route117_Text_IsaacRematchIntro:
	.string "De POKéMON, jeg har opdrættet, ser godt\n"
	.string "ud, ligesom tidligere.$"

Route117_Text_IsaacRematchDefeat:
	.string "Du ved, hvordan man opdrager dem\n"
	.string "ordentligt. Du har måske DAGPLEJE\l"
	.string "færdigheder…$"

Route117_Text_IsaacPostRematch:
	.string "Dine POKéMON vokser godt! Du burde\n"
	.string "tilmelde dem i KONKURRENCER.$"

Route117_Text_LydiaIntro:
	.string "Vil du ikke lade mig vurdere, om du har\n"
	.string "opdraget dine POKéMON rigtigt?$"

Route117_Text_LydiaDefeat:
	.string "Ja, de vokser ordentligt.$"

Route117_Text_LydiaPostBattle:
	.string "Prøv at opdrage POKéMON med mere\n"
	.string "opmærksomhed på deres\l"
	.string "personlighedstræk.$"

Route117_Text_LydiaRegister:
	.string "Jeg er glad for at have mødt en\n"
	.string "fantastisk TRÆNER som dig. Håber at se\l"
	.string "dig igen.$"

Route117_Text_LydiaRematchIntro:
	.string "Lad mig genoverveje om du har\n"
	.string "opdrættet dine POKéMON ordentligt.$"

Route117_Text_LydiaRematchDefeat:
	.string "De vokser beundringsværdigt.$"

Route117_Text_LydiaPostRematch:
	.string "POKéMON synes at kunne lide forskellige\n"
	.string "slags af {POKEBLOCK}S, afhængigt af deres\l"
	.string "natur.$"

Route117_Text_DylanIntro:
	.string "Jeg er midt i en triatlon, men, det er\n"
	.string "ligemeget, lad os kæmpe!$"

Route117_Text_DylanDefeat:
	.string "Jeg løb tør for energi!$"

Route117_Text_DylanPostBattle:
	.string "Jeg har måske ødelagt det…\p"
	.string "Jeg kunne være endt sidst under den\n"
	.string "kamp…$"

Route117_Text_DylanRegister:
	.string "POKéMON skal også være stærke, ikke?\n"
	.string "Jeg vil gerne have dig til at træne mig!$"

Route117_Text_DylanRematchIntro:
	.string "Jeg er midt i en triatlon, og jeg ligger\n"
	.string "trygt i front. Lad os gøre det til en\l"
	.string "hurtig kamp!$"

Route117_Text_DylanRematchDefeat:
	.string "Jeg løb tør for energi igen!$"

Route117_Text_DylanPostRematch:
	.string "Jeg var tops til at svømme og cykle, men\n"
	.string "jeg er ikke helt så selvsikker med\l"
	.string "POKéMON endnu.$"

Route117_Text_MariaIntro:
	.string "Jeg træner til triatlon med POKéMON, så\n"
	.string "jeg er ret sikker på min fart.$"

Route117_Text_MariaDefeat:
	.string "Jeg skal have lidt mere træning, tror\n"
	.string "jeg.$"

Route117_Text_MariaPostBattle:
	.string "Træning er meningsfuld kun hvis du\n"
	.string "holder fast i den regelmæssigt.\p"
	.string "Okay! Jeg vil genoptage min træning!I\n"
	.string "morgen!$"

Route117_Text_MariaRegister:
	.string "Du ser ud til at træne ordentligt… Hvis\n"
	.string "du vil, kan vi kæmpe senere!$"

Route117_Text_MariaRematchIntro:
	.string "Er du ved at holde dig ajour med din\n"
	.string "træning? Det er jeg helt sikkert! Lad mig\l"
	.string "vise dig beviset!$"

Route117_Text_MariaRematchDefeat:
	.string "Jeg er nødt til at få mere træning,\n"
	.string "antager jeg.$"

Route117_Text_MariaPostRematch:
	.string "Jeg vil genoptage træningen i morgen. \n"
	.string "Lad os kæmpe igen en anden gang!$"

Route117_Text_DerekIntro:
	.string "Engang en INSEKT FANGER! Og nu en\n"
	.string "INSEKT FANATIKER!\p"
	.string "Men min kærlighed til POKéMON er stadig\n"
	.string "uforandret!$"

Route117_Text_DerekDefeat:
	.string "Min uduelighed forbliver uændret…$"

Route117_Text_DerekPostBattle:
	.string "Alt, hvad jeg gjorde, var at følge mit\n"
	.string "hjerte, og nu kalder de mig en\l"
	.string "INSEKTGALNING…\p"
	.string "Men jeg er stadig ekspert i INSEKT\n"
	.string "POKéMON, så det er kun naturligt, at de\l"
	.string "kalder mig en INSEKTGALNING.$"

Route117_Text_AnnaIntro:
	.string "ANNA: Jeg er sammen med min søde junior\n"
	.string "elevpartner. Jeg skal gøre det godt!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: Jeg er sammen med min smukke\n"
	.string "juniorstuderende! Lad mig vinde!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Dine POKéMON har nogle gode\n"
	.string "kombinationer.\p"
	.string "Jeg vil sige, at du kun er nummer to i\n"
	.string "forhold til os!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: Vi kan ikke tage det her liggende!\n"
	.string " Kommer du tilbage, gør du ikke? $"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: Hvis du vil kæmpe mod os, skal du\n"
	.string "have medbragt to POKéMON.$"

Route117_Text_MegIntro:
	.string "MEG: Jeg skal samarbejde med min super\n"
	.string "erfarne studentermakker og slå dig!$"

Route117_Text_MegDefeat:
	.string "MEG: Åh, nej! Undskyld, ANNA! Jeg\n"
	.string "skuffede dig…$"

Route117_Text_MegPostBattle:
	.string "MEG: Jeg trak ANNA ned… Hvis jeg ikke\n"
	.string "gjorde det, ville hun have vundet!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Har du kun en POKéMON? Så kan vi\n"
	.string "desværre ikke kæmpe med dig.\p"
	.string "Vi vil gerne have en 2-mod-2 kamp.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: Jeg kan ikke blive ved med at\n"
	.string "tabe foran min juniorpartner, vel?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: Jeg kunne ikke komme tilbage i\n"
	.string "rytmen.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Dine POKéMON har nogle gode\n"
	.string "kombinationer.\p"
	.string "Jeg vil sige, du er kun nr. to efter os!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: Hvis du vil kæmpe mod os, skal du\n"
	.string "medbringe to POKéMON.$"

Route117_Text_MegRematchIntro:
	.string "MEG: Jeg vil danne makkerpar med min\n"
	.string "ældre partner og vinde denne gang!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: Alt for stærk!$"

Route117_Text_MegPostRematch:
	.string "MEG: Jeg kæmpede sammen med min ældre\n"
	.string "partner, men vi tabte…\p"
	.string "Det er så nedslående…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Har du kun én POKéMON? Så kan vi\n"
	.string "desværre ikke kæmpe mod dig.\p"
	.string "Vi vil gerne have en 2-mod-2 kamp.$"

Route117_Text_MelinaIntro:
	.string "Er det ikke dejligt? At kæmpe mens man\n"
	.string "kigger på smukke blomster?$"

Route117_Text_MelinaDefeat:
	.string "Oh, det er ret imponerende!$"

Route117_Text_MelinaPostBattle:
	.string "Det føles vidunderligt at løbe mens man\n"
	.string "kigger på blomster.$"

Route117_Text_BrandiIntro:
	.string " Lad mig demonstrere kraften  gemt i en\n"
	.string "PSYCHIC POKéMON!$"

Route117_Text_BrandiDefeat:
	.string "Forbløffende!$"

Route117_Text_BrandiPostBattle:
	.string "PSYCHIC POKéMON er komplekse. Du burde\n"
	.string "prøve at fange nogle.$"

Route117_Text_AishaIntro:
	.string "Fokuser på at få sejren. Sådan kæmper\n"
	.string "jeg!$"

Route117_Text_AishaDefeat:
	.string "Jeg spilder ikke tid på at være vred\n"
	.string "over et nederlag--jeg vil hellere træne.$"

Route117_Text_AishaPostBattle:
	.string "Jeg tror, hvis du bekymrer dig om at\n"
	.string "tabe, er du mere tilbøjelig til at tabe.$"

Route118_Text_RoseIntro:
	.string "Duften af blomster har en magisk kraft.\n"
	.string "Den renser os krop og sjæl.$"

Route118_Text_RoseDefeat:
	.string "Åh, kære mig. Det ser ud til, at jeg har\n"
	.string "tabt.$"

Route118_Text_RosePostBattle:
	.string "Blomster, POKéMON… Jeg elsker alt, der\n"
	.string "dufter godt.\p"
	.string "Stinkende ting… Det springer jeg over.$"

Route118_Text_RoseRegister:
	.string "Snif… Den lugt--det er en POKéNAV! Vi\n"
	.string "skal registrere hinanden!$"

Route118_Text_RoseRematchIntro:
	.string "Var du tiltrukket heraf af den søde\n"
	.string "duft?$"

Route118_Text_RoseRematchDefeat:
	.string "Duftenes kraft… Det så ikke ud til at\n"
	.string "gøre meget.$"

Route118_Text_RosePostRematch:
	.string "Hvis du bruger en sød duft ordentligt,\n"
	.string "vil POKéMON blive tiltrukket af den.$"

Route118_Text_PerryIntro:
	.string "FUGLE POKéMON, der FLYVER elegant i\n"
	.string "himlen… De er de bedste!$"

Route118_Text_PerryDefeat:
	.string "Åh nej… Jeg crashede…$"

Route118_Text_PerryPostBattle:
	.string "Du har fantastiske POKéMON. Jeg bliver\n"
	.string "nødt til at træne mine bedre.$"

Route118_Text_ChesterIntro:
	.string "Tag flugt! Min FUGLPokémon!$"

Route118_Text_ChesterDefeat:
	.string "De tog flugten…$"

Route118_Text_ChesterPostBattle:
	.string "Hvis de blev stærkere, ville de kunne\n"
	.string "flyve mere frit…$"

Route118_Text_BarnyIntro:
	.string "Jeg er en FISKER, men også en TRÆNER.\n"
	.string "Jeg træner de POKéMON, jeg har fanget.$"

Route118_Text_BarnyDefeat:
	.string "Jeg troede, jeg klarede mig fint i min\n"
	.string "træning…$"

Route118_Text_BarnyPostBattle:
	.string "Jeg kunne ikke vinde ved bare at træne\n"
	.string "POKéMON mens jeg fiskede…\p"
	.string "Lavede jeg tingene halvhjertet?$"

Route118_Text_WadeIntro:
	.string "For FISKERE er udstyr nøglen.\p"
	.string "Men for TRÆNERE er de vigtigste\n"
	.string "ingredienser POKéMON og hjerte,\l"
	.string "selvfølgelig!$"

Route118_Text_WadeDefeat:
	.string "Jeg blev slået med hjertet?$"

Route118_Text_WadePostBattle:
	.string "Når man tænker over det, er fiskeri en\n"
	.string "kamp mellem en FISKER og en POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Lad min melodi ryste din sjæl!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "En elektrisk guitar behøver ikke altid\n"
	.string "at være larmende…\p"
	.string "Den kan spilles for at frembringe denne\n"
	.string "hjerteopvarmende melodi…$"

Route118_Text_DaltonRegister:
	.string "Når jeg komponerer bedre melodier, skal\n"
	.string "du komme og lytte, okay?$"

Route118_Text_DaltonRematchIntro:
	.string "En melodi fra mine POKéMON og mig… Lad\n"
	.string "os levere den til din sjæl.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Når jeg spiller, skal mine følelser nå dig\n"
	.string "gennem min elektriske guitar…$"

Route118_Text_DeandreIntro:
	.string "Go, go, go! POKéMON 1, 2, and 3!$"

Route118_Text_DeandreDefeat:
	.string "Kom ind, POKéMON! Er du okay? POKéMON 1,\n"
	.string "2 og 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Er det ikke sejt, at jeg har et POKéMON\n"
	.string "kamphold?\p"
	.string "Du kan kopiere mig--det gør mig ikke\n"
	.string "noget!$"

Route119_Text_BrentIntro:
	.string "Vi er MIMIC CIRCLE! Vi MIMIC'er hvad du\n"
	.string "gør!$"

Route119_Text_BrentDefeat:
	.string "Ups! Jeg tabte!$"

Route119_Text_BrentPostBattle:
	.string "Hvad er der så godt ved efterligning?\p"
	.string "Fufufu… Det vil du aldrig forstå…$"

Route119_Text_DonaldIntro:
	.string "Så mødes vi endelig! Mine INSEKT\n"
	.string "POKéMON vil holde dig med selskab!$"

Route119_Text_DonaldDefeat:
	.string "Jeg ville ønske, vi aldrig havde mødt\n"
	.string "hinanden…$"

Route119_Text_DonaldPostBattle:
	.string "Jeg vil gerne IMITERE dig lidt mere. Kan\n"
	.string "du skynde dig at flytte?$"

Route119_Text_TaylorIntro:
	.string "Hvis du går fremad, går vi fremad.\p"
	.string "Hvis du drejer til højre, drejer vi også…$"

Route119_Text_TaylorDefeat:
	.string "Men hvis du vinder, taber jeg…$"

Route119_Text_TaylorPostBattle:
	.string "Jeg kan ikke EFTERABE din sejr i kampen.\n"
	.string "Det er bare umuligt… Det brænder i mig…$"

Route119_Text_DougIntro:
	.string "Jeps, du har endelig fanget mig! Eller\n"
	.string "prøvede du at undgå mig?$"

Route119_Text_DougDefeat:
	.string "Hu-hej, det var en fantastisk kamp!$"

Route119_Text_DougPostBattle:
	.string "Vi er MIMIC CIRCLE! Jeg håber, du nød\n"
	.string "vores optræden.$"

Route119_Text_GregIntro:
	.string "Du ved ikke, hvem jeg er, gør du?\p"
	.string "Men jeg kender heller ikke dig. Så lad os\n"
	.string "kæmpe!$"

Route119_Text_GregDefeat:
	.string "Du er ret stærk!$"

Route119_Text_GregPostBattle:
	.string "Indtil du går et sted hen, vil vi\n"
	.string "fortsætte med at efterligne dine\l"
	.string "handlinger.$"

Route119_Text_KentIntro:
	.string "MIMIC CIRKLEN blev dannet af\n"
	.string "mennesker, som kan lide at efterligne.\p"
	.string "En kamp starter øjeblikket vi mødes!$"

Route119_Text_KentDefeat:
	.string "Jeg giver op!$"

Route119_Text_KentPostBattle:
	.string "Vil du ikke være med i vores MIMIC\n"
	.string "CIRCLE?$"

Route119_Text_JacksonIntro:
	.string "Who has the knowledge and the\n"
	.string "technique for survival?\p"
	.string "POKéMON RANGERS, that's who!$"

Route119_Text_JacksonDefeat:
	.string "Jeg havde ikke nok POKéMON viden…$"

Route119_Text_JacksonPostBattle:
	.string "For at bryde væk fra civilisationen og\n"
	.string "vække den vilde ånd indeni!\p"
	.string "Det er vores vision.$"

Route119_Text_JacksonRegister:
	.string "Jeg håber, du vil give mig en revan- che\n"
	.string "uden at gøre nar af min mang- lende\l"
	.string "viden.$"

Route119_Text_JacksonRematchIntro:
	.string "Jeg vil genfinde mit vilde åndedyr ved\n"
	.string "at være sammen med POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Du har været stærk!$"

Route119_Text_JacksonPostRematch:
	.string "Tro på dine POKéMON. Tro på dig selv.\p"
	.string "Vejen vil afsløre sig for dig.$"

Route119_Text_CatherineIntro:
	.string "Nå, ser man på det.\p"
	.string "For en eventyrer som dig, rejser du\n"
	.string "ualmindeligt let.$"

Route119_Text_CatherineDefeat:
	.string "Ulykker sker, når du ikke er forberedt!$"

Route119_Text_CatherinePostBattle:
	.string "Du rejser let, men du har alt, hvad du\n"
	.string "har brug for.\p"
	.string "Du er skarp mentalt og fysisk, også.$"

Route119_Text_CatherineRegister:
	.string "Har du en POKéNAV? Det er et must-have\n"
	.string "værktøj for enhver TRÆNER.\p"
	.string "Åh, du har en! Så lad os registrere\n"
	.string "hinanden, så!$"

Route119_Text_CatherineRematchIntro:
	.string "Hvordan går det med din rejse med\n"
	.string "POKéMON ?$"

Route119_Text_CatherineRematchDefeat:
	.string "Jeg mangler stadig noget…$"

Route119_Text_CatherinePostRematch:
	.string "På samme måde som dig, som en TRÆNER,\n"
	.string "stoler på dine POKéMON, stoler dine\l"
	.string "POKéMON på dig.$"

Route119_Text_HughIntro:
	.string "Den enorme himmel rummer ubegrænset\n"
	.string "mulighed!\p"
	.string "Intet kan sammenlignes med den rene\n"
	.string "spænding ved at flyve!$"

Route119_Text_HughDefeat:
	.string "Nede og ude!$"

Route119_Text_HughPostBattle:
	.string "Mine FUGL POKéMON har gjort mine drømme\n"
	.string "om at flyve til virkelighed!$"

Route119_Text_PhilIntro:
	.string "Jeg vil vise dig mit sande potentiale og\n"
	.string "min FUGLE POKéMON!$"

Route119_Text_PhilDefeat:
	.string "Vi manglede potentiale…$"

Route119_Text_PhilPostBattle:
	.string "Siden jeg var en lille knægt, har jeg\n"
	.string "altid beundret FUGLE POKéMON…$"

Route119_Text_YasuIntro:
	.string "At lure i skyggerne og leve i mørket…\n"
	.string "Det er min skæbne.\p"
	.string "Jeg dukker op for at udfordre dig!$"

Route119_Text_YasuDefeat:
	.string "Jeg giver op!$"

Route119_Text_YasuPostBattle:
	.string "Dem, der er besejret i kamp, trækker sig\n"
	.string "stille tilbage ind i skyggerne. Det er\l"
	.string "også skæbnen…$"

Route119_Text_TakashiIntro:
	.string "Hvis du ikke er på vagt, venter der lidt\n"
	.string "smerte på dig!$"

Route119_Text_TakashiDefeat:
	.string "Du er overraskende god!$"

Route119_Text_TakashiPostBattle:
	.string "Mit overraskelsesangreb endte i\n"
	.string "fiasko…$"

Route119_Text_HideoIntro:
	.string "For at skjule et træ, brug en skov!$"

Route119_Text_HideoDefeat:
	.string "Jeg bøjer mig for din overlegenhed.$"

Route119_Text_HideoPostBattle:
	.string "For at skjule et træ, brug en skov! For\n"
	.string "at skjule en POKéMON, brug en POKéMON!\p"
	.string "Der er ingen dyb, skjult betydning i det.$"

Route119_Text_ChrisIntro:
	.string "Du talte til mig… Så du vil udfordre mig!\p"
	.string "Selvfølgelig! Jeg vil prøve de POKéMON,\n"
	.string "jeg har fanget mens jeg surfede!$"

Route119_Text_ChrisDefeat:
	.string "Jeg har ikke en anelse om, hvad der skal\n"
	.string "til for at vinde.$"

Route119_Text_ChrisPostBattle:
	.string "Tag på en SURF på min POKéMON…\p"
	.string "Og fisk derefter fra dens ryg…\p"
	.string "Det er et ubeskriveligt luksuriøst\n"
	.string "øjeblik!$"

Route119_Text_FabianIntro:
	.string "Slå mig med en powerakkord! Sejren er\n"
	.string "min! Det er vores tid til at skinne, whoa,\l"
	.string "yeah!$"

Route119_Text_FabianDefeat:
	.string "Du viste mig, hvem der er chefen! Vi\n"
	.string "bliver nødt til at tage tabet, oh nej!$"

Route119_Text_FabianPostBattle:
	.string "Slå mig med endnu et power-akord! Lad\n"
	.string "mig være i fred! Din sejr skal du sone!$"

Route119_Text_DaytonIntro:
	.string "Hohoho! Jeg kan godt lide\n"
	.string "børne-TRÆNERE! Lad os få en god kamp!$"

Route119_Text_DaytonDefeat:
	.string "Du er ret fantastisk! Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho! Jeg vil prøve at efterligne\n"
	.string "energien fra unge TRÆNERE som dig!$"

Route119_Text_RachelIntro:
	.string "Uanset hvor jeg er og hvornår det er,\n"
	.string "har jeg altid min parasol i hånden.$"

Route119_Text_RachelDefeat:
	.string "Åh, men… Det er ikke fair.$"

Route119_Text_RachelPostBattle:
	.string "Du spørger om min parasol er tung? Din\n"
	.string "RYGSÆK er fyldt med mere skrammel end\l"
	.string "jeg nogensinde bærer rundt på.$"

Route120_Text_ColinIntro:
	.string "Har du nogen angreb, der kan ramme en\n"
	.string "flyvende POKéMON?$"

Route120_Text_ColinDefeat:
	.string "Du fløj over mig!$"

Route120_Text_ColinPostBattle:
	.string "Flyv-funktionen er praktisk, synes du\n"
	.string "ikke?\p"
	.string "Når POKéMON-en flyver, kan næsten\n"
	.string "ingen angreb ramme den.$"

Route120_Text_RobertIntro:
	.string "Mine POKéMON er stærk! Hvad med din?$"

Route120_Text_RobertDefeat:
	.string "Dine POKéMON var stærkere…$"

Route120_Text_RobertPostBattle:
	.string "En POKéMON, der vokser støt, er en du\n"
	.string "kan regne med.$"

Route120_Text_RobertRegister:
	.string "Du kan regnes med at blive bedre. Jeg\n"
	.string "vil gerne registrere dig i min POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "En POKéMON der vokser støt, er en du\n"
	.string "kan regne med.$"

Route120_Text_RobertRematchDefeat:
	.string "Dine POKéMON er virkelig stærke.$"

Route120_Text_RobertPostRematch:
	.string "Mine POKéMON bliver stærkere. Jeg bliver\n"
	.string "nødt til at blive stærkere også.$"

Route120_Text_LorenzoIntro:
	.string "Jeg vil tjekke dine POKéMON og se om de\n"
	.string "er klar til udendørslivet.$"

Route120_Text_LorenzoDefeat:
	.string "Med POKéMON så stærke, er du slet ikke i\n"
	.string "fare for at få brug for redning!$"

Route120_Text_LorenzoPostBattle:
	.string "At rejse hvor dit hjerte ønsker med\n"
	.string "POKéMON… Det er glæden ved at være en\l"
	.string "TRÆNER.$"

Route120_Text_JennaIntro:
	.string "Hvordan står det til med din fysisk\n"
	.string "fitness? Hvis du ikke er i form, kan du\l"
	.string "få det svært i kritiske situationer.$"

Route120_Text_JennaDefeat:
	.string "Jeg er helt i form, men…$"

Route120_Text_JennaPostBattle:
	.string "Fitness træning er en del af min rutine.\n"
	.string "Jeg løber altid med mine POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … … … … … … … … Want to battle?$"

Route120_Text_JeffreyDefeat:
	.string "Tabte den…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … … … … … … … … I'll try harder…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … … … … … … … … Har du en\n"
	.string "POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … … … … … … … … Want to battle\n"
	.string "again?$"

Route120_Text_JeffreyRematchDefeat:
	.string "Jeg tabte igen…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … … … … … … … … Jeg vil prøve\n"
	.string "hårdere… For min dyrebare INSEKT\l"
	.string "POKéMON…$"

Route120_Text_JenniferIntro:
	.string "POKéMON har mange specielle evner. Hvis\n"
	.string "du vil blive en topklasse TRÆNER, så lær\l"
	.string "om dem.$"

Route120_Text_JenniferDefeat:
	.string "Du tænker tydeligvis.$"

Route120_Text_JenniferPostBattle:
	.string "De specielle evner hos POKéMON vil\n"
	.string "ændre kampstil.$"

Route120_Text_ChipIntro:
	.string "Hvem mon du er?\p"
	.string "Er du måske på jagt efter gamle ruiner,\n"
	.string "som rygtet siger muligvis eksisterer\l"
	.string "ifølge legenden?$"

Route120_Text_ChipDefeat:
	.string "Hvad et pinligt tilbageslag…$"

Route120_Text_ChipPostBattle:
	.string "Den kæmpestore sten… Jeg vil gerne tro,\n"
	.string "at den faktisk gemmer på gamle ruiner.\l"
	.string "Men jeg kan ikke se nogen indgang.$"

Route120_Text_ClarissaIntro:
	.string "Hvorfor bærer jeg denne parasol?\p"
	.string "Jeg vil fortælle dig det, hvis du kan\n"
	.string "vinde imod mig.$"

Route120_Text_ClarissaDefeat:
	.string "En parasol kan ikke beskytte mod\n"
	.string "POKéMON angreb…$"

Route120_Text_ClarissaPostBattle:
	.string "Jeg tror ikke stærkt sollys er godt for\n"
	.string "mine POKéMON. Så jeg beskytter dem med\l"
	.string "min parasol.$"

Route120_Text_AngelicaIntro:
	.string "Mig, POKéMON, og min paraply…\p"
	.string "Hvis en af dem mangler, vil skønhedens\n"
	.string "billede blive ødelagt.$"

Route120_Text_AngelicaDefeat:
	.string "Du har fuldstændig ødelagt min\n"
	.string "skønhed…$"

Route120_Text_AngelicaPostBattle:
	.string "En parasol ville slet ikke klæde dig.\p"
	.string "Ja, noget som dette ville kun være i\n"
	.string "vejen for dig.$"

Route120_Text_KeigoIntro:
	.string "Jeg vil adoptere bevægelserne fra\n"
	.string "POKéMON og skabe nye ninja-teknikker.$"

Route120_Text_KeigoDefeat:
	.string "Oprettelsen af nye ninja teknikker er\n"
	.string "blot en fjern drøm…$"

Route120_Text_KeigoPostBattle:
	.string "Måske skulle jeg blive lærling under en\n"
	.string "ninja sensei.$"

Route120_Text_RileyIntro:
	.string "Vi ninja gemmer os under vores\n"
	.string "camouflagekapper. Jeg vedder på, at du\l"
	.string "ikke vidste, hvor jeg var!$"

Route120_Text_RileyDefeat:
	.string "Jeg tabte! Jeg burde kamuflere min\n"
	.string "skam!$"

Route120_Text_RileyPostBattle:
	.string "Vores kamuflagekapper er alle\n"
	.string "håndlavede.$"

Route120_Text_CallieIntro:
	.string "Hvis du ikke er opmærksom,  kan du komme\n"
	.string "til skade!$"

Route120_Text_CallieDefeat:
	.string "Av! Det var mig, der blev såret.$"

Route120_Text_CalliePostBattle:
	.string "Jeg spekulerer… Skal jeg udvikle min\n"
	.string "POKéMON? De er søde, som de er, dog.$"

Route120_Text_LeonelIntro:
	.string "Dine POKéMON i teamet… Har du\n"
	.string "forskellige typer?$"

Route120_Text_LeonelDefeat:
	.string "Jeg har set din politik i aktion!$"

Route120_Text_LeonelPostBattle:
	.string "Jeg synes, det er sejt, du er så stærk\n"
	.string "og kæmper med din favorit POKéMON.$"

Route121_Text_VanessaIntro:
	.string "Vil du lege med mine skønne og smukke\n"
	.string "POKéMON? $"

Route121_Text_VanessaDefeat:
	.string "Det var ikke det, jeg mente!$"

Route121_Text_VanessaPostBattle:
	.string "Jeg skal til en KONKURRENCE i LILYCOVE.\p"
	.string "Mine POKéMON burde ikke have nogen\n"
	.string "problemer med at feje MESTERKLASSEN.$"

Route121_Text_WalterIntro:
	.string "Med mine POKéMON er jeg rejst til\n"
	.string "verdens fire hjørner.\p"
	.string "Man kunne sige, at jeg har lidt\n"
	.string "selvtillid i mine evner.$"

Route121_Text_WalterDefeat:
	.string "Åh, godt spillet.$"

Route121_Text_WalterPostBattle:
	.string "Jeg vil gerne cirkulereglobus endnu en\n"
	.string "gang med min POKéMON.$"

Route121_Text_WalterRegister:
	.string "Din POKéMON-færdighed er\n"
	.string "bemærkelsesværdig. Lad mig registrere\l"
	.string "dig som et minde.$"

Route121_Text_WalterRematchIntro:
	.string "Med mine POKéMON har jeg rejst til\n"
	.string "verdens fire hjørner.\p"
	.string "Man kunne sige, jeg er ret sikker på\n"
	.string "mine evner.$"

Route121_Text_WalterRematchDefeat:
	.string "Åh, godt spillet.$"

Route121_Text_WalterPostRematch:
	.string "Dine POKéMON og dig…\p"
	.string "Jeres kunnen sammen vil blive betraget\n"
	.string "som stærkt, selv i udlandet.$"

Route121_Text_TammyIntro:
	.string "Der er kræfter ud over vores forståelse\n"
	.string "i verden…$"

Route121_Text_TammyDefeat:
	.string "Jeg har tabt…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE… Der er en mystisk kraft på\n"
	.string "spil der…$"

Route121_Text_KateIntro:
	.string "KATE: Sammen er vi frygtløse! Vi vil\n"
	.string "vise, hvor seje vi er!$"

Route121_Text_KateDefeat:
	.string "KATE: Jeg ødelagde det foran min\n"
	.string "juniorstudiepartner…$"

Route121_Text_KatePostBattle:
	.string "KATE: Når nogen stoler på mig, får jeg\n"
	.string "lyst til at se sej ud foran dem…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: Hvis du kun har én POKéMON, kan vi\n"
	.string "ikke kæmpe imod dig.\p"
	.string "Det ville være mobning.$"

Route121_Text_JoyIntro:
	.string "JOY: Sammen er vi frygtløse! Vi vil vise,\n"
	.string "hvor seje vi er!$"

Route121_Text_JoyDefeat:
	.string "JOY: Undskyld mig, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, jeg bliver nødt til at træne\n"
	.string "med KATE, min ældre studiepartner, igen.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: Du skal have mindst to POKéMON\n"
	.string "hvis du vil udfordre os!$"

Route121_Text_JessicaIntro:
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "Åh, hvordan tør du! Tag det ikke så\n"
	.string "alvorligt!$"

Route121_Text_JessicaPostBattle:
	.string "Måske tager jeg ud og fanger flere \n"
	.string "POKéMON i SAFARIEN.$"

Route121_Text_JessicaRegister:
	.string "Jeg tog det roligt med dig denne gang!\n"
	.string "Det bliver ikke på samme måde næste\l"
	.string "gang!$"

Route121_Text_JessicaRematchIntro:
	.string "Mine kære POKéMON er vokset! Tag et\n"
	.string "godt kig!$"

Route121_Text_JessicaRematchDefeat:
	.string "Åh, hvordan tør du! Du vil stadig ikke\n"
	.string "tage det roligt!$"

Route121_Text_JessicaPostRematch:
	.string "Maybe I'll go catch more POKéMON at the\n"
	.string "SAFARI.$"

Route121_Text_CristinIntro:
	.string "Jeg har denne rutine. Besejr fem\n"
	.string "TRÆNERE om dagen. Gæt hvad? Du er\l"
	.string "nummer fem!$"

Route121_Text_CristinDefeat:
	.string "Nej! Du er grusom!$"

Route121_Text_CristinPostBattle:
	.string "Jeg havde ikke regnet med at tabe så\n"
	.string "let… Jeg vinder næste gang!$"

Route121_Text_CristinRegister:
	.string "Det var total ydmygelse! Jeg vil ikke\n"
	.string "glemme dig… Aflever din POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "Jeg har denne nye rutine. Besejr ti\n"
	.string "TRÆNERE om dagen. Gæt hvad? Du er\l"
	.string "nummer ti!$"

Route121_Text_CristinRematchDefeat:
	.string "Vent! Det er ulækkert! Jeg kræver en\n"
	.string "revanchepulje!$"

Route121_Text_CristinPostRematch:
	.string "En modstander jeg bare ikke kan slå…\n"
	.string "Snøft… Jeg kan ikke tro, at dette sker…$"

Route121_Text_CaleIntro:
	.string "Kan du ikke se, at jeg har alt dette grej\n"
	.string "med mig?\p"
	.string "På trods af det insisterer du stadig på,\n"
	.string "at vi skal kæmpe?$"

Route121_Text_CaleDefeat:
	.string "Selvfølgelig tabte jeg! Jeg holder ting\n"
	.string "i begge hænder!$"

Route121_Text_CalePostBattle:
	.string "Jeg har købt alt for meget ting hos\n"
	.string "LILYCOVE DEPT. STORE.\p"
	.string "Det er oppe ad vejen herfra. Jeg ønsker,\n"
	.string "jeg havde en RYGSÆK som din.$"

Route121_Text_MylesIntro:
	.string "Der er intet, jeg elsker mere end at\n"
	.string "kigge på andres POKéMON!$"

Route121_Text_MylesDefeat:
	.string "Super awesome!$"

Route121_Text_MylesPostBattle:
	.string "De er fantastiske, dine POKéMON!\n"
	.string "Hvordan opdrætter du dem?$"

Route121_Text_PatIntro:
	.string "Jeg vil have alle til at se de POKéMON,\n"
	.string "jeg har opfostret!$"

Route121_Text_PatDefeat:
	.string "Wow! Fantastisk!$"

Route121_Text_PatPostBattle:
	.string "Jeg opdrætter alle POKéMON med den\n"
	.string "samme kærlighed og omsorg - jeg vælger\l"
	.string "ingen favoritter.$"

Route121_Text_MarcelIntro:
	.string "Mine POKéMON har aldrig smagt nederlag!\n"
	.string "På deres næste sejr, vil jeg tilmelde dem\l"
	.string "i KONKURRENCER.$"

Route121_Text_MarcelDefeat:
	.string "Åh nej, hvad skete der lige her?$"

Route121_Text_MarcelPostBattle:
	.string "Jeg må nok træne min bande lidtmere, før\n"
	.string "vi deltager i en KONKURRENCE.$"

Route123_Text_WendyIntro:
	.string "Vil du finde ud af, hvor stærk du er? Jeg\n"
	.string "vil være testen!$"

Route123_Text_WendyDefeat:
	.string "Du bestod med flyvende farver!$"

Route123_Text_WendyPostBattle:
	.string "For at kunne slå mig… Din styrke er\n"
	.string "fantastisk!$"

Route123_Text_BraxtonIntro:
	.string "Du ser ud til at have en stor samling af\n"
	.string "GYM BADGES.\p"
	.string " Lad mig se, om du rent faktisk er værdig\n"
	.string "til disse BADGES!$"

Route123_Text_BraxtonDefeat:
	.string "Åh, du er helt klart værdig!$"

Route123_Text_BraxtonPostBattle:
	.string "Du gjorde dine MÆRKER stolte i den duel!$"

Route123_Text_VioletIntro:
	.string "De siger, at gode tider er fyldt med\n"
	.string "gode dufte.$"

Route123_Text_VioletDefeat:
	.string "Åh… Jeg kan lugte den bitre duft af\n"
	.string "elendighed…$"

Route123_Text_VioletPostBattle:
	.string "BÆRETS mesteres have er fyldt med\n"
	.string "opmuntrende dufte.$"

Route123_Text_CameronIntro:
	.string "At være en psykisk er om viljestyrke.\p"
	.string "Jeg har villet mig til ikke at tabe til\n"
	.string "nogen. Det gør mig stærk!$"

Route123_Text_CameronDefeat:
	.string "Jeg føler mig ked af det…$"

Route123_Text_CameronPostBattle:
	.string "At være psykisk handler om viljestyrke.\n"
	.string "Jeg troede ikke, jeg ville tabe til dig…$"

Route123_Text_CameronRegister:
	.string "Jeg mærker det! Du og jeg skal kæmpe\n"
	.string "igen! Jeg kan ikke sige om jeg vil vinde,\l"
	.string "dog…\p"
	.string "Lad os se din POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Jeg har overbevist mig selv om, at jeg\n"
	.string "ikke vil tabe mere. Det gør mig stærk!$"

Route123_Text_CameronRematchDefeat:
	.string "Jeg føler mig trist…$"

Route123_Text_CameronPostRematch:
	.string "Jeg burde træne ved MT. PYRE… Jeg vil\n"
	.string "aldrig slå dig på denne måde…$"

Route123_Text_JackiIntro:
	.string "Vær ikke for glad, hvis din POKéMON\n"
	.string "udvikler psykiske evner.\p"
	.string "Du skal forfine de evner for at gøre dem\n"
	.string "virkelig nyttige.$"

Route123_Text_JackiDefeat:
	.string "Overvældet!$"

Route123_Text_JackiPostBattle:
	.string "Vi har alle psykiske evner. Vi har bare\n"
	.string "glemt, hvordan vi skal bruge dem.$"

Route123_Text_JackiRegister:
	.string "Jeg vil gerne stille op mod dig igen. Er\n"
	.string "det okay med dig?$"

Route123_Text_JackiRematchIntro:
	.string "Har du vækket de psykiske kræfter\n"
	.string "inden i dig?$"

Route123_Text_JackiRematchDefeat:
	.string "Forbløffende!$"

Route123_Text_JackiPostRematch:
	.string "Din kraft med POKéMON… Det kunne også\n"
	.string "være en psykisk kraft.$"

Route123_Text_MiuIntro:
	.string "MIU: Hej, TRÆNER. Jeg håber din POKéMON\n"
	.string "ikke græder, når de taber.$"

Route123_Text_MiuDefeat:
	.string "MIU: Øh-øj, vi tabte.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRÆNER, dine POKéMON er stærke,\n"
	.string "fordi I er venner.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: Det er ikke sjovt at kæmpe, hvis du\n"
	.string "ikke har to POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay! Vi slår TRÆNERENS POKéMON!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Ups, vi tabte.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Hvorfor er du så stærk? Vi har\n"
	.string "aldrig tabt før.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: Det er ikke sjovt at kæmpe, hvis\n"
	.string "du ikke har to POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE… Where the spirits of POKéMON\n"
	.string "sleep… Vil din POKéMON sove?$"

Route123_Text_KindraDefeat:
	.string "Sprudlende af vitalitet…$"

Route123_Text_KindraPostBattle:
	.string "MOUNT PYRE… Hvor POKéMON's ånder\n"
	.string "hviler…\p"
	.string "Der må være en kraft, der beroliger\n"
	.string "ånder…$"

Route123_Text_FernandoIntro:
	.string "Jeg slukker lyset mens jeg river\n"
	.string "igennem denne melodi!$"

Route123_Text_FernandoDefeat:
	.string "Hey, hold it! I was still playing the\n"
	.string "intro!$"

Route123_Text_FernandoPostBattle:
	.string "Du er som en klippe. Jeg kunne godt\n"
	.string "tænke mig at skrive en sang om dig.$"

Route123_Text_FernandoRegister:
	.string "Næste gang, lyt til hele melodien, ik'?$"

Route123_Text_FernandoRematchIntro:
	.string "I dag er dagen, hvor jeg vil gøre det!\n"
	.string "Jeg slukker lyset, før jeg er færdig med\l"
	.string "at synge min sang!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it! I haven't even hit the\n"
	.string "chorus!$"

Route123_Text_FernandoPostRematch:
	.string "Jeg troede, du ville være så forhekset\n"
	.string "af min melodi, at du$"

Route123_Text_DavisIntro:
	.string "Det her er min seje INSEKT POKéMON! Min\n"
	.string "storebror købte den til mig.$"

Route123_Text_DavisDefeat:
	.string "Iiiih! Du store skurk!$"

Route123_Text_DavisPostBattle:
	.string "Sig ikke til min bror, at jeg tabte. Du er\n"
	.string "nødt til at holde det hemmeligt!$"

Route123_Text_JazmynIntro:
	.string "Min selvtillid vil få et boost ved at slå\n"
	.string "en tydeligt stærk person!$"

Route123_Text_JazmynDefeat:
	.string "Der røg min selvtillid…$"

Route123_Text_JazmynPostBattle:
	.string "Man siger, at man ikke kan bedømme en\n"
	.string "person ud fra deres udseende.\p"
	.string "Men ofte lyver udseendet ikke…$"

Route123_Text_FrederickIntro:
	.string "Hej, barn! Har du lidt tid til overs?$"

Route123_Text_FrederickDefeat:
	.string "Åh, et mægtigt dygtigt barn!  Lad mig\n"
	.string "bidrage til din lommepenge.$"

Route123_Text_FrederickPostBattle:
	.string "Bidrage til din lommepenge? Var\n"
	.string "præmiepengene ikke nok?$"

Route123_Text_AlbertoIntro:
	.string "Jeg bliver nødt til at fortælle dig, FUGL\n"
	.string "POKéMON er min besættelse!\p"
	.string "Fugle er seje! De er de bedste!$"

Route123_Text_AlbertoDefeat:
	.string "Selv i nederlag er FUGLE POKéMON seje!$"

Route123_Text_AlbertoPostBattle:
	.string "Jeg samler BIRD POKéMON-fjer, der\n"
	.string "spredes under kampe.\p"
	.string "Jeg vil lave en hat med BIRD\n"
	.string "POKéMON-fjer.$"

Route123_Text_EdIntro:
	.string "Når der ikke er NOGEN TRÆNERE i\n"
	.string "nærheden, lader jeg mine POKéMON kæmpe\l"
	.string "mod hinanden. Jeg ser på dem.$"

Route123_Text_EdDefeat:
	.string "Jeg er lidt vild med din POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, Jeg snupper dine kamp-idéer! Jeg\n"
	.string "tror de vil gøre mig bedre.$"

Route123_Text_JonasIntro:
	.string "Jeg ligger på lur, og en TRÆNER er landet\n"
	.string "i mit fælde!$"

Route123_Text_JonasDefeat:
	.string "Hvis du ikke taber, hvordan skal jeg så\n"
	.string "have det sjovt med at spille ninja?$"

Route123_Text_JonasPostBattle:
	.string "Jeg vil overraske en svagere udseende\n"
	.string "TRÆNER næste gang.$"

Route123_Text_KayleyIntro:
	.string "Jeg har lige købt denne parasol. Min\n"
	.string "sødme burde være steget med en\l"
	.string "tredjedel!$"

Route123_Text_KayleyDefeat:
	.string "Du er bedre end mig med cirka fem gange!$"

Route123_Text_KayleyPostBattle:
	.string "At bruge accessories effektivt er\n"
	.string "hemmeligheden bag moden.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON, I can serve\n"
	.string "as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "Jeg har mistet mit fodfæste i kampen!$"

Route124_Text_SpencerPostBattle:
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer to\n"
	.string "the POKéNAV's MAP.$"

Route124_Text_RolandIntro:
	.string "Hm! Du rider på en POKéMON i stedet for\n"
	.string "at svømme selv…\p"
	.string "Jeg er misundelig!$"

Route124_Text_RolandDefeat:
	.string "Åh! Jeg kan ikke…$"

Route124_Text_RolandPostBattle:
	.string "Jeg fryser… Jeg har været i vandet for\n"
	.string "længe…\p"
	.string "Jeg ville ønske, jeg kunne ride på en\n"
	.string "POKéMON som dig…$"

Route124_Text_JennyIntro:
	.string "Hvis du bare flyder i havet på denne\n"
	.string "måde, POKéMON kommer for at lege.$"

Route124_Text_JennyDefeat:
	.string "Åh, pokkers. Jeg har tabt.$"

Route124_Text_JennyPostBattle:
	.string "Mens jeg svømmede, lagde jeg mærke til,\n"
	.string "at nogle POKéMON angriber, og andre bare\l"
	.string "ser på.Jeg gætter på, at POKéMON har\l"
	.string "deres egne personligheder.$"

Route124_Text_JennyRegister:
	.string "Det er kun på en impuls, men måske får\n"
	.string "jeg dig til at registrere mig i din\l"
	.string "POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Hvis du bare lige driver rundt på havet\n"
	.string "på denne måde, TRÆNERE udfordrer dig!$"

Route124_Text_JennyRematchDefeat:
	.string "Det er mærkeligt… Jeg tabte igen…$"

Route124_Text_JennyPostRematch:
	.string "Det her har ikke noget at gøre med\n"
	.string "noget, men måske besøger jeg TRICK\l"
	.string "HOUSE.$"

Route124_Text_GraceIntro:
	.string "Jeg bliver lidt træt af at svømme… Hvad\n"
	.string "med en kamp?$"

Route124_Text_GraceDefeat:
	.string "Jeg havde ingen idé om, at du var så\n"
	.string "stærk!$"

Route124_Text_GracePostBattle:
	.string "Alt det arbejde, du har lagt i, må have\n"
	.string "gjort dig så stærk.$"

Route124_Text_ChadIntro:
	.string "Haha… Jeg dykker dybt under vandet for\n"
	.string "at gå dybt under cover. Det er her, jeg\l"
	.string "virkelig skinner!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub… Jeg synker…$"

Route124_Text_ChadPostBattle:
	.string "Jeg har det fra pålidelig kilde, at der\n"
	.string "er et DYKKEsted omkring her.\p"
	.string "Det giver mig lyst til at dykke dybt\n"
	.string "igen…$"

Route124_Text_LilaIntro:
	.string "LILA: Suk…\p"
	.string "Her er jeg i havet, men hvem er med mig?\n"
	.string "Min lillebror!\p"
	.string "Lad os kæmpe så jeg ikke behøver at\n"
	.string "fokusere på det!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! Det er din skyld, at vi tabte!\n"
	.string "Du får problemer senere!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Suk…\p"
	.string "Hvis det bare ikke var min lille bror ved\n"
	.string "siden af mig, men en sød kæreste…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: Du planlægger at udfordre os?\n"
	.string "Ikke medmindre du har to POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: Min store søster er sej til\n"
	.string "POKéMON!\p"
	.string "Græd ikke, når du taber!$"

Route124_Text_RoyDefeat:
	.string "ROY: Åh-åh… Min store søster vil skælde\n"
	.string "mig ud…$"

Route124_Text_RoyPostBattle:
	.string "ROY: Min store søster er virkelig\n"
	.string "skræmmende når hun bliver vred.\p"
	.string "Det er derfor, hun ikke har en kæreste.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Vil du kæmpe med os igen? Men tag\n"
	.string "det roligt næste gang, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Vil du kæmpe mod os? Tag to\n"
	.string "POKéMON med, så.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Suk…\p"
	.string "Her er jeg i havet, men hvem er med mig?\n"
	.string "Min lille bror!\p"
	.string "Åh, hej, det var længe siden. Lad os\n"
	.string "kæmpe så jeg ikke behøver tænke for\l"
	.string "meget på tingene!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY! Det er din skyld, vi tabte\n"
	.string "igen!\p"
	.string "Vi har en træningssession senere!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Suk…\p"
	.string "Hvis jeg havde en sød kæreste, ville vi\n"
	.string "slå alle med skønne kombinationer…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: Planlægger du at kæmpe mod os?\n"
	.string "Ikke medmindre du har to POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: Hvis vi taber, får jeg ballade. Jeg\n"
	.string "vil gå fuldstændig amok!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh… Min store søster vil skælde\n"
	.string "mig ud igen.$"

Route124_Text_RoyPostRematch:
	.string "ROY: Min store søster er virkelig \n"
	.string "skræmmende, når hun bliver vred.\p"
	.string "Hun kommer til at lade mig træne  rigtig\n"
	.string "hårdt med POKéMON senere…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Vil du kæmpe mod os? Tag to\n"
	.string "POKéMON med så.$"

Route124_Text_DeclanIntro:
	.string "Her står jeg og svømmer helt alene på\n"
	.string "dette store, smukke hav.\p"
	.string "Der er ingen anden måde at sige det på.\n"
	.string "Det her er ynkeligt!$"

Route124_Text_DeclanDefeat:
	.string "Jeg føler mig blå. Blå som himlen…$"

Route124_Text_DeclanPostBattle:
	.string "Jeg burde snakke med dame-SWIMMERS og\n"
	.string "invitere dem med på en lang svømmetur.$"

Route124_Text_IsabellaIntro:
	.string "Jeg taber ikke til nogen surftræner.$"

Route124_Text_IsabellaDefeat:
	.string "Jeg har kun sved i øjnene! Jeg græder\n"
	.string "ikke!$"

Route124_Text_IsabellaPostBattle:
	.string "Du kan finde smukke farvede styk- ker\n"
	.string "af ting her omkring.$"

Route125_Text_NolenIntro:
	.string "Jeg hørte dig nærme dig, så jeg  blev\n"
	.string "hængende for dig!$"

Route125_Text_NolenDefeat:
	.string "Jeg giver op!$"

Route125_Text_NolenPostBattle:
	.string "Lyden rejser hurtigere i vand end\n"
	.string "gennem luft.$"

Route125_Text_StanIntro:
	.string "Hej, du dér! Tjek mine seje POKéMON!$"

Route125_Text_StanDefeat:
	.string "Jeg tabte…$"

Route125_Text_StanPostBattle:
	.string "Jeg blev blæst væk af HORSEAs charme,\n"
	.string "så begyndte jeg også at svømme.$"

Route125_Text_TanyaIntro:
	.string "Jeg er træt af at svømme. Er du klar til\n"
	.string "at kæmpe med mig?$"

Route125_Text_TanyaDefeat:
	.string "Du er for meget!$"

Route125_Text_TanyaPostBattle:
	.string "Puha… Hvilken vej er det til MOSSDEEP\n"
	.string "CITY?$"

Route125_Text_SharonIntro:
	.string "Hvordan vil du tage kampen op mod de\n"
	.string "VAND-type POKéMON, jeg opdrættede?$"

Route125_Text_SharonDefeat:
	.string "Tabte det…$"

Route125_Text_SharonPostBattle:
	.string "Din kraft… Du er the real deal. Jeg er\n"
	.string "imponeret!$"

Route125_Text_ErnestIntro:
	.string "Hej med dig! Jeg er en sej og stærk\n"
	.string "SØMAND. Jeg har sejlet på verdens have!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar! Jeg kunne ikke vinde!$"

Route125_Text_ErnestPostBattle:
	.string "Tidevandet ebber og flyder inde i\n"
	.string "SKOVLHULEN.\p"
	.string "Forresten, der er cirka seks timer fra\n"
	.string "højvande til lavvande. Vidste du det?$"

Route125_Text_ErnestRegister:
	.string "Registrer mig i din POKéNAV, og jeg vil\n"
	.string "fortælle dig noget godt.$"

Route125_Text_ErnestRematchIntro:
	.string "Det er på høje tid, jeg får min hævn på\n"
	.string "dig! Kom nu, vi skal kæmpe!$"

Route125_Text_ErnestRematchDefeat:
	.string "Jeg kunne ikke vinde! Jeg kunne\n"
	.string "simpelthen ikke vinde!$"

Route125_Text_ErnestRematchPostBattle:
	.string "HULEHULEN…\p"
	.string "Der er steder, du kan og ikke kan komme\n"
	.string "til afhængigt af ebbe og flod.\p"
	.string "Forresten, det tager cirka seks timer\n"
	.string "fra højvande til lavvande. Husk det!$"

Route125_Text_KimIntro:
	.string "KIM: En sjov gammel mand bor i SHOAL\n"
	.string "CAVE. Nogen fortalte mig. Skal du også\l"
	.string "besøge ham?$"

Route125_Text_KimDefeat:
	.string "KIM: Jeg troede, at vi ville vinde.$"

Route125_Text_KimPostBattle:
	.string "KIM: En sjov gammel mand bor i\n"
	.string "SKALHULEHULE, gør han ikke?\p"
	.string "Lad os gå besøge ham, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: Nej, nej, nej! Du skal bruge to \n"
	.string "POKéMON, ellers dur det bare ikke!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, kan du fortælle mig, hvad vi\n"
	.string "leder efter herude?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Åh, vi kom lidt tæt på.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, skal vi virkelig ind i\n"
	.string "SKJULECAVE? Vi bliver helt våde.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Åh, vi kunne aldrig, nogensinde\n"
	.string "gøre noget som en 2-mod-1 kamp.$"

Route125_Text_PresleyIntro:
	.string "Hvorfor ville en FUGLEOPDRÆTTER som\n"
	.string "mig komme ud til havet?$"

Route125_Text_PresleyDefeat:
	.string "Okay. Jeg vil fortælle dig hvorfor jeg er\n"
	.string "her.$"

Route125_Text_PresleyPostBattle:
	.string "Jeg lagde en besked i en flaske og\n"
	.string "sendte den ud til havs.\p"
	.string "Jeg er sikker på, at en PIGE SVOEMMER\n"
	.string "vil finde den!$"

Route125_Text_AuronIntro:
	.string "Hey! Var det dig, der smed skrald i\n"
	.string "havet?$"

Route125_Text_AuronDefeat:
	.string "Åh, du kastede ikke affald i havet.$"

Route125_Text_AuronPostBattle:
	.string "Jeg fandt en grim flaske der drev i\n"
	.string "bølgerne tidligere.\p"
	.string "Det gør mig vred, at nogen ville\n"
	.string "forurene havet!$"

Route126_Text_BarryIntro:
	.string "At svømme er en fuld kropstræning! Du\n"
	.string "bliver fit!$"

Route126_Text_BarryDefeat:
	.string "Jeg indrømmer det! Du vinder!$"

Route126_Text_BarryPostBattle:
	.string "Takket være min daglige svømmetur… Se!\n"
	.string "Nyd dette fysik!$"

Route126_Text_DeanIntro:
	.string "Denne høje hvide bjerg af sten er\n"
	.string "SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "Jeg blev slået?$"

Route126_Text_DeanPostBattle:
	.string "Jeg kan ikke finde indgangen til\n"
	.string "SOOTOPOLIS. Hvor mon den er?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu! Jeg er en havfrue!$"

Route126_Text_NikkiDefeat:
	.string "Min fantasi sprang som en boble! Blub,\n"
	.string "blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "Du gav mig øretæver… Jeg vil gerne\n"
	.string "forsvinde i en bølge af fortvivlelse…$"

Route126_Text_BrendaIntro:
	.string "Hej, ven! Vil du kæmpe med mig?$"

Route126_Text_BrendaDefeat:
	.string "Åh, neeeej!$"

Route126_Text_BrendaPostBattle:
	.string "Jeg elsker at lege med POKéMON i havet\n"
	.string "på denne måde!$"

Route126_Text_PabloIntro:
	.string "Tjek lige denne veltrænede krop! Jeg er\n"
	.string "mere trimmet end en SORT BÆLTE!$"

Route126_Text_PabloDefeat:
	.string "Hovsa! For stærk! Ikke dårligt! Slet\n"
	.string "ikke dårligt!$"

Route126_Text_PabloPostBattle:
	.string "At tabe til dig stimulerede mine sanser!\n"
	.string "Jeg vil træne mig selv og POKéMON\l"
	.string "hårdere!$"

Route126_Text_PabloRegister:
	.string "Ja, du er slet ikke dårlig! Jeg vil gerne\n"
	.string "lære dig bedre at kende!$"

Route126_Text_PabloRematchIntro:
	.string "Tjek lige denne smukke krop! Jeg er\n"
	.string "mere spænstig end en SVØMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Hovsa! Virkelig for stærk! Ikke dårligt!\n"
	.string "Slet ikke dårligt!$"

Route126_Text_PabloPostRematch:
	.string "Jeg vil træne endnu hårdere! Du er en\n"
	.string "fantastisk motivationskilde! Du skal\l"
	.string "komme tilbage igen!$"

Route126_Text_LeonardoIntro:
	.string "Sidste år kunne jeg ikke engang svømme,\n"
	.string "men nu er jeg en rimelig SVØMMER.\p"
	.string "Jeg tror, jeg er i stand til alt nu.$"

Route126_Text_LeonardoDefeat:
	.string "Puha, at blive grådig gjorde ikke noget\n"
	.string "for mig.$"

Route126_Text_LeonardoPostBattle:
	.string "Hvis du øver dig på noget, vil du blive\n"
	.string "bedre til det.\p"
	.string "Du er ung -- vær ikke bange for at prøve\n"
	.string "alle mulige ting!$"

Route126_Text_IsobelIntro:
	.string "Hvis saltvand kommer op i din næse,\n"
	.string "føles det ikke forfærdeligt?$"

Route126_Text_IsobelDefeat:
	.string "Nå, for en kriger du er! Plask!$"

Route126_Text_IsobelPostBattle:
	.string "Åh, jeg kom til at synke noget vand! Det\n"
	.string "er bittert! Det er salt!!$"

Route126_Text_SiennaIntro:
	.string "Jeg kaster hele mit hjerte ind i det!$"

Route126_Text_SiennaDefeat:
	.string "Du havde mere hjerte!$"

Route126_Text_SiennaPostBattle:
	.string "Jeg skal lige køle ned nu… Tror, jeg\n"
	.string "tager en dyk.$"

Route127_Text_CamdenIntro:
	.string "Jeg kan se det i dit ansigt. Du vil\n"
	.string "udfordre mig.$"

Route127_Text_CamdenDefeat:
	.string "Åh nej, du vandt…$"

Route127_Text_CamdenPostBattle:
	.string "En velspillet kamp får mig til at føle\n"
	.string "mig opfrisket og rolig.$"

Route127_Text_DonnyIntro:
	.string "Har du en rival, som du bare hader at\n"
	.string "tabe imod?$"

Route127_Text_DonnyDefeat:
	.string "Åh nej! Jeg hader at tabe!$"

Route127_Text_DonnyPostBattle:
	.string "Hvis du har en rival, får du ikke\n"
	.string "følelsen af, at du bliver nødt til at\l"
	.string "blive bedre?$"

Route127_Text_JonahIntro:
	.string "Gennem fiskeri har jeg opnået en\n"
	.string "tilstand af rolig stilhed…\p"
	.string "Vær så venlig at give mig lov til at\n"
	.string "demonstrere…$"

Route127_Text_JonahDefeat:
	.string "Selvom jeg har tabt, er mit hjerte\n"
	.string "stadig roligt…$"

Route127_Text_JonahPostBattle:
	.string "Det betyder ikke noget, at jeg fanger\n"
	.string "ingenting. Linjen forbliver i vandet…$"

Route127_Text_HenryIntro:
	.string "Ups! Sig ikke at jeg fangede en SURFING\n"
	.string "POKéMON?$"

Route127_Text_HenryDefeat:
	.string "Jeg kan ikke følge med!$"

Route127_Text_HenryPostBattle:
	.string "Det ville være en håndfuld, hvis jeg fik\n"
	.string "fat i dine seje  POKéMON!$"

Route127_Text_RogerIntro:
	.string "Nå, hej! Dette er en kamp mellem en\n"
	.string "POKéMON-fan og en lystfisker!$"

Route127_Text_RogerDefeat:
	.string "Nej! Mit snøre er helt viklet sammen!\n"
	.string "Festen er forbi!$"

Route127_Text_RogerPostBattle:
	.string "Min fiskestang laver en dans! Det roder\n"
	.string "tango! Hahaha, snor!$"

Route127_Text_AidanIntro:
	.string "FUGLE POKéMON har fremragende syn. De\n"
	.string "opdager bytte fra store højder.$"

Route127_Text_AidanDefeat:
	.string "Puha… Jeg giver op.$"

Route127_Text_AidanPostBattle:
	.string "Der er masser af dykkersteder i havet\n"
	.string "omkring her.\p"
	.string "Du kan se dem tydeligt fra himlen på\n"
	.string "grund af deres mørkere farve.$"

Route127_Text_KojiIntro:
	.string "Løb i dine bare fødder. Det vil gøre dine\n"
	.string "fodsåler seje!$"

Route127_Text_KojiDefeat:
	.string "Av av! Jeg fik en sten under en tånegl!$"

Route127_Text_KojiPostBattle:
	.string "At gå barfodet føles fantastisk. Men\n"
	.string "dine LØBESKO er også seje.$"

Route127_Text_KojiRegister:
	.string "Det her er hvad jeg gør ved folk, der\n"
	.string "slår mig! Jeg håber, vi kan gøre det igen.$"

Route127_Text_KojiRematchIntro:
	.string "Jeg løber stadig dagligt i mine bare\n"
	.string "fødder. Mine såler er seje!$"

Route127_Text_KojiRematchDefeat:
	.string "Av av! Småsten gravede sigind i mine\n"
	.string "svang!$"

Route127_Text_KojiPostRematch:
	.string "Vil du gå barfodet i et stykke tid? Så\n"
	.string "jeg kan prøve dine LØBESKO?$"

Route127_Text_AthenaIntro:
	.string "Vi burde have en langsom og metodisk\n"
	.string "kamp.$"

Route127_Text_AthenaDefeat:
	.string "Du gav mig ikke chancen for at lave\n"
	.string "strategi.$"

Route127_Text_AthenaPostBattle:
	.string "Når jeg er omgivet af det blå hav og\n"
	.string "himmel, føles det, som om tiden går\l"
	.string "langsommere.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY er stadig langt væk…$"

Route128_Text_IsaiahDefeat:
	.string "Min første sejr synes også at være\n"
	.string "langt væk…$"

Route128_Text_IsaiahPostBattle:
	.string "Hele mit liv har handlet om at tabe, men\n"
	.string "jeg vil aldrig give op!$"

Route128_Text_IsaiahRegister:
	.string "Jeg ved, jeg er ikke god nu, men jeg tror\n"
	.string "jeg kan vinde på et tidspunkt.\p"
	.string "Vil du registrere mig i din POKéNAV?$"

Route128_Text_IsaiahRematchIntro:
	.string "Jeg har det stadig godt. Jeg vil\n"
	.string "fortsætte med at svømme til EVER GRANDE\l"
	.string "CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Jeg har endnu ikke smagt min første\n"
	.string "sejr…$"

Route128_Text_IsaiahPostRematch:
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro:
	.string "Du skal svømme, cykle og løbe en\n"
	.string "maraton i en triatlon.\p"
	.string "Det er et hårdt løb, der består af tre\n"
	.string "begivenheder.$"

Route128_Text_KatelynDefeat:
	.string "En POKéMON-kamp er også hård…$"

Route128_Text_KatelynPostBattle:
	.string "Jeg skal cykle næste gang, men… Jeg er\n"
	.string "ved at give op…$"

Route128_Text_KatelynRegister:
	.string "Nå, så kan jeg lige så godt gøre det\n"
	.string "bedste ud af det. Jeg vil gerne have en\l"
	.string "revanche engang.$"

Route128_Text_KatelynRematchIntro:
	.string "En triathlon er lang. Men jeg gætter på, \n"
	.string "vejen til at blive POKéMON-MESTER er\l"
	.string "også lang og krævende.$"

Route128_Text_KatelynRematchDefeat:
	.string "En POKéMON-kamp er virkelig barsk og\n"
	.string "ubarmhjertig…$"

Route128_Text_KatelynPostRematch:
	.string "Du bør overveje seriøst at tage\n"
	.string "udfordringer på SEJRSVEJEN.$"

Route128_Text_AlexaIntro:
	.string "Vi har arbejdet så hårdt på at\n"
	.string "forberede os til en POKéMON LIGA\l"
	.string "udfordring…\p"
	.string "Vi kan ikke tabe nu!$"

Route128_Text_AlexaDefeat:
	.string "Åh! Hvordan kunne dette ske?!$"

Route128_Text_AlexaPostBattle:
	.string "Efter alt det, jeg har gjort for at\n"
	.string "komme hertil, vil jeg ikke give op efter\l"
	.string "ét tilbageslag.$"

Route128_Text_RubenIntro:
	.string "Der er ingen stærkere TRÆNER end mig!$"

Route128_Text_RubenDefeat:
	.string "Det kan ikke være rigtigt!$"

Route128_Text_RubenPostBattle:
	.string "Der er sandsynligvis ingen stærkere\n"
	.string "TRÆNER end dig!$"

Route128_Text_WayneIntro:
	.string "Jeg vil gerne besøge EVER GRANDE, så\n"
	.string "jeg fangede mig en POKéMON, der kan\l"
	.string "bruge TORDEN til at bestege\l"
	.string "vandfaldene.$"

Route128_Text_WayneDefeat:
	.string "Jeg er knust!$"

Route128_Text_WaynePostBattle:
	.string "Åh nej, hvor ærgerligt!\p"
	.string "Min POKéMON kender VANDFALD, men jeg\n"
	.string "har ikke SOOTOPOLIS GYM BADGE!$"

Route128_Text_HarrisonIntro:
	.string "Du ser meget sej ud. Mon jeg kan vinde?$"

Route128_Text_HarrisonDefeat:
	.string "Av! Jeg gætter på, det var umuligt at\n"
	.string "vinde.$"

Route128_Text_HarrisonPostBattle:
	.string "Der er seje TRÆNERE i massevis omkring\n"
	.string "EVER GRANDE.\p"
	.string "Tror du, jeg måske er ude af min liga?$"

Route128_Text_CarleeIntro:
	.string "Det virker som om sollyset er skarpere\n"
	.string "her.$"

Route128_Text_CarleeDefeat:
	.string "Jeg kunne ikke se så godt på grund af\n"
	.string "solens blænding.$"

Route128_Text_CarleePostBattle:
	.string "Jeg burde snart tage tilbage. Jeg skal\n"
	.string "huske at smøre mig ind i solcreme.$"

Route129_Text_ChaseIntro:
	.string "Det her er min første triatlon. Jeg er\n"
	.string "helt spændt og nervøs!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar! Jeg formåede ikke at vinde!$"

Route129_Text_ChasePostBattle:
	.string "Hvis jeg er helt spændt op, kan jeg ikke\n"
	.string "give det hele.$"

Route129_Text_AllisonIntro:
	.string "Jeg er midt i en triatlon, men okay,\n"
	.string "hvorfor kæmper vi ikke?$"

Route129_Text_AllisonDefeat:
	.string "Jeg var sikker på, at jeg ville vinde!$"

Route129_Text_AllisonPostBattle:
	.string "Ved du, hvad der er det største ved\n"
	.string "triathlons?\p"
	.string "At teste grænserne for din egen styrke\n"
	.string "og udholdenhed imod Moder Natur!$"

Route129_Text_ReedIntro:
	.string "Sig hej, hej! Lad os komme igang!$"

Route129_Text_ReedDefeat:
	.string "Fedt, jeg er slået. Det var det, færdig!$"

Route129_Text_ReedPostBattle:
	.string "Der er ikke noget for en taber. Det er\n"
	.string "tid for mig at slå hjem.$"

Route129_Text_TishaIntro:
	.string "Hvad er det for en fart? Lad os tage\n"
	.string "det roligt og nemt.$"

Route129_Text_TishaDefeat:
	.string "Åh, nej. Jeg ville gerne slappe lidt af\n"
	.string "mere…$"

Route129_Text_TishaPostBattle:
	.string "Kender du ikke det med at lave fejl, når\n"
	.string "du har travlt?\p"
	.string "Derfor forsøger jeg at tage tingene\n"
	.string "langsomt.$"

Route129_Text_ClarenceIntro:
	.string "At surfe er ikke så let, som det ser ud\n"
	.string "til, er det ikke rigtigt?$"

Route129_Text_ClarenceDefeat:
	.string "At vinde er bestemt ikke nemt.$"

Route129_Text_ClarencePostBattle:
	.string "Du har dine øjne rettet mod POKéMON-\n"
	.string "LIGAEN? Hold fast i det!$"

Route130_Text_RodneyIntro:
	.string "Hvad en overraskelse! Jeg havde ikke\n"
	.string "forventet at se en TRÆNER ude på havet.\p"
	.string "Jeg tror, vi burde kæmpe!$"

Route130_Text_RodneyDefeat:
	.string "Denne knægts virkelig sej…$"

Route130_Text_RodneyPostBattle:
	.string "Dine øjne har den der look af en, der har\n"
	.string "oplevet hårde udfordringer og sejret.\l"
	.string "Det klæder dig godt!$"

Route130_Text_KatieIntro:
	.string "I det dybe blå hav, finder mit knuste\n"
	.string "blå hjerte trøst blandt bølgerne.$"

Route130_Text_KatieDefeat:
	.string "Som det store blå hav, strækker\n"
	.string "POKéMON-verdenen sig dybere end man\l"
	.string "tror.$"

Route130_Text_KatiePostBattle:
	.string "Verdens børn drømmer om en dag at blive\n"
	.string "POKéMON MESTER.$"

Route130_Text_SantiagoIntro:
	.string "Der er noget helt magisk ved at sejle ud\n"
	.string "på det åbne hav… Stille og roligt.$"

Route130_Text_SantiagoDefeat:
	.string "Jeg måtte være lidt mindre fredelig!$"

Route130_Text_SantiagoPostBattle:
	.string "At svømme og kæmpe på denne måde…  Jeg\n"
	.string "er en glad fyr…$"

Route131_Text_RichardIntro:
	.string "Havet vrimler med POKéMON. Det er ikke\n"
	.string "nemt at svømme, jeg siger dig.$"

Route131_Text_RichardDefeat:
	.string "POKéMON opdrættet af TRÆNERE er rigtig\n"
	.string "seje…$"

Route131_Text_RichardPostBattle:
	.string "Puha… Puha… Jeg er flad…\p"
	.string "Det er let på vejen. Det er det at\n"
	.string "forlade stedet, der er svært.\p"
	.string "Mon jeg vil have energi tilbage til turen\n"
	.string "tilbage?$"

Route131_Text_HermanIntro:
	.string "Havet… Havet… Havet… Havet så langt\n"
	.string "som disse øjne kan nå! Jeg er træt af\l"
	.string "havet!$"

Route131_Text_HermanDefeat:
	.string "Buh!$"

Route131_Text_HermanPostBattle:
	.string "Ked af det, jeg er ved havet, men svømme\n"
	.string "må jeg.\p"
	.string "Jeg er født svømmer! Det er hvad jeg er.$"

Route131_Text_SusieIntro:
	.string "Hej, skat, vent lige! Vi burde kæmpe, du\n"
	.string "og jeg!$"

Route131_Text_SusieDefeat:
	.string "Du er sej på trods af den måde du ser ud\n"
	.string "på!$"

Route131_Text_SusiePostBattle:
	.string "Så du en fyr derovre, som klager over,\n"
	.string "at han keder sig af havet?\p"
	.string "Det er alt sammen snak. Han er håbløst\n"
	.string "forelsket i havet!$"

Route131_Text_KaraIntro:
	.string "Hvorfor elsker mænd badebukser så\n"
	.string "meget?\p"
	.string "De glor alle på mig!$"

Route131_Text_KaraDefeat:
	.string "Jeg er ude af min dybde!$"

Route131_Text_KaraPostBattle:
	.string "Måske er det ikke min badedragt, der får\n"
	.string "mænd til at kigge. Det må være min\l"
	.string "skønhed!$"

Route131_Text_ReliIntro:
	.string "RELI: Vi vil arbejde sammen som\n"
	.string "søskende for at udfordre dig!$"

Route131_Text_ReliDefeat:
	.string "RELI: Vi kunne ikke vinde, selvom vi\n"
	.string "arbejdede sammen…$"

Route131_Text_ReliPostBattle:
	.string "RELI: Folkene i PACIFIDLOG er sammen\n"
	.string "med havet og POKéMON fra den tid, de\l"
	.string "bliver født.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: Du har ikke to POKéMON? Så kan vi\n"
	.string "desværre ikke kæmpe.$"

Route131_Text_IanIntro:
	.string "IAN: Jeg gør mit bedste sammen med min\n"
	.string "søster!$"

Route131_Text_IanDefeat:
	.string "IAN: Jeg gjorde mit bedste med min søs,\n"
	.string "men vi kunne stadig ikke vinde…$"

Route131_Text_IanPostBattle:
	.string "IAN: Ved du, hvordan PACIFIDLOG er en\n"
	.string "flydende by?\p"
	.string "Så, hvor end der er havet, er det en del\n"
	.string "af PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Hvis du har to POKéMON, tager vi\n"
	.string "dig med på!$"

Route131_Text_TaliaIntro:
	.string "Hvis du kan slå mig, vil jeg give dig lidt\n"
	.string "fantastisk information!$"

Route131_Text_TaliaDefeat:
	.string "Nå? Tabte jeg?$"

Route131_Text_TaliaPostBattle:
	.string "Der er et mærkeligt sted i nærheden. Der\n"
	.string "er et kæmpe tårn der. Hvorfor går du ikke\l"
	.string "derhen og kigger?$"

Route131_Text_KevinIntro:
	.string "Folkene fra PACIFIDLOG er en fredelig\n"
	.string "flok.\p"
	.string "De bliver aldrig sure. Det gælder også\n"
	.string "for mig.$"

Route131_Text_KevinDefeat:
	.string "Ups!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Åh, vent. Jeg er ikke sur. Ærligt\n"
	.string "talt!\p"
	.string "Men hold nu op, du er stærk! Hahaha!$"

Route132_Text_GilbertIntro:
	.string "Jeg plejede at få forkølelse hele tiden\n"
	.string "som barn, men jeg blev helt sund, da jeg\l"
	.string "begyndte at svømme.$"

Route132_Text_GilbertDefeat:
	.string "Jeg sukker efter mere kraft…$"

Route132_Text_GilbertPostBattle:
	.string "TRÆNERE rejser gennem markerne og\n"
	.string "bjergene, så de må også være i form.$"

Route132_Text_DanaIntro:
	.string "Jeg forsøger at undgå at svømme hvor\n"
	.string "strømmene er for stærke.$"

Route132_Text_DanaDefeat:
	.string "Åh nej, ikke mere!$"

Route132_Text_DanaPostBattle:
	.string "Hvis jeg bliver skyllet væk, mister jeg\n"
	.string "hele min fornemmelse af sted…$"

Route132_Text_RonaldIntro:
	.string "Vind eller tab, du vil aldrig vide før du\n"
	.string "prøver!$"

Route132_Text_RonaldDefeat:
	.string "Åh nej! Jeg sank i nederlag!$"

Route132_Text_RonaldPostBattle:
	.string "Jeg slås aldrig, når jeg ved, jeg vil\n"
	.string "vinde. Jeg kan lide at kæmpe på den\l"
	.string "nådesløse kant mellem sejr og nederlag!$"

Route132_Text_KiyoIntro:
	.string "Jeg tænker på POKéMON 24 timer om\n"
	.string "dagen. Hvordan tror du, du kan slå mig?$"

Route132_Text_KiyoDefeat:
	.string "Jeg taber. Jeg vil bøje mig for\n"
	.string "nederlaget.$"

Route132_Text_KiyoPostBattle:
	.string "Øv… Du er vild med POKéMON, ikke sandt?\p"
	.string "Du må jo tænke på POKéMON 24 timer i\n"
	.string "døgnet, ikke?$"

Route132_Text_MakaylaIntro:
	.string "Jeg er altid sammen med min mand, men\n"
	.string "jeg kan vinde selv uden ham.$"

Route132_Text_MakaylaDefeat:
	.string "Nå, jeg gættede nok, jeg var ikke god\n"
	.string "nok.$"

Route132_Text_MakaylaPostBattle:
	.string "Den unge mand derovre ligner præcis min\n"
	.string "mand, da han var ung.\p"
	.string "Han får mig til at rødme!$"

Route132_Text_JonathanIntro:
	.string "Nogen har set mig meget interesseret\n"
	.string "på. Var det dig?$"

Route132_Text_JonathanDefeat:
	.string "Wow! That's pretty strong, all right!$"

Route132_Text_JonathanPostBattle:
	.string "Jeg kan ikke ryste denne følelse af, at\n"
	.string "nogen ser på mig.\p"
	.string "Jeg kan ikke koncentrere mig!$"

Route132_Text_PaxtonIntro:
	.string "Hvor mon min kone er taget hen? Jeg er\n"
	.string "altid sammen med hende. Mon jeg kan\l"
	.string "vinde på egen hånd?$"

Route132_Text_PaxtonDefeat:
	.string "Åh, jeg kan se, at jeg ikke kunne vinde\n"
	.string "på egen hånd alligevel.$"

Route132_Text_PaxtonPostBattle:
	.string "Min kone leder sikkert efter mig. Jeg må\n"
	.string "hellere finde hende med det samme.$"

Route132_Text_DarcyIntro:
	.string "Jeg kunne lide at træne her selv. Det er\n"
	.string "forfærdeligt, at alle disse mennesker\l"
	.string "kom!$"

Route132_Text_DarcyDefeat:
	.string "Okay! Jeg vil ikke klage over andre\n"
	.string "mennesker, der er her.$"

Route132_Text_DarcyPostBattle:
	.string "Jeg antager, at jeg kan gå sammen med\n"
	.string "den gamle mand og udfordre det andet\l"
	.string "hold.$"

Route133_Text_FranklinIntro:
	.string "Har strømmene også ført dig hertil? Det\n"
	.string "må have været skæbnebestemt. Lad os\l"
	.string "kæmpe!$"

Route133_Text_FranklinDefeat:
	.string "Stærk! Alt for stærk!$"

Route133_Text_FranklinPostBattle:
	.string "Det er bare min uheldige skæbne, at en\n"
	.string "sej TRÆNER som dig ville drive her til…\l"
	.string "Jeg må være forbandet…$"

Route133_Text_DebraIntro:
	.string "Jeg har ført et liv fyldt med kvaler og\n"
	.string "elendighed… Jeg er blevet skubbet væk,\l"
	.string "og dette er hvor jeg er drevet hen…$"

Route133_Text_DebraDefeat:
	.string "Endnu et nederlag…$"

Route133_Text_DebraPostBattle:
	.string "Et liv på drift… Det vil jeg ikke\n"
	.string "længere!$"

Route133_Text_LindaIntro:
	.string "Velkommen! Jeg har ventet på dig!$"

Route133_Text_LindaDefeat:
	.string "Nej! Vær sød!$"

Route133_Text_LindaPostBattle:
	.string "En stærk børnetræner… Det er så\n"
	.string "irriterende!$"

Route133_Text_WarrenIntro:
	.string "Jeg vil gerne vinde ligesom alle andre, \n"
	.string "men jeg vil ikke opdrætte POKéMON som \l"
	.string "alle andre.$"

Route133_Text_WarrenDefeat:
	.string "Øv altså! Min måde er stadig for slap!$"

Route133_Text_WarrenPostBattle:
	.string "Det er meget sjovere at gøre tingene på\n"
	.string "den måde, jeg vil, end at være som alle\l"
	.string "andre. Jeg mener, det er åbenlyst!$"

Route133_Text_BeckIntro:
	.string "Jeg er kommet hele vejen ud her med min\n"
	.string "FUGLE POKéMON.$"

Route133_Text_BeckDefeat:
	.string "Du… Du er helt fantastisk cool!$"

Route133_Text_BeckPostBattle:
	.string "Jeg vil gerne tilbage til FORTREE, men\n"
	.string "jeg er også begyndt at kunne lide dette\l"
	.string "sted.$"

Route133_Text_MollieIntro:
	.string "Jeg må have kæmpet tusindvis af gange.\n"
	.string "Jeg har mistet tællingen.$"

Route133_Text_MollieDefeat:
	.string "Jeg har måske tabt tusind gange, men et\n"
	.string "nederlag gør stadig ondt.$"

Route133_Text_MolliePostBattle:
	.string "Bliv ved med det, unge menneske. Så kan\n"
	.string "du blive ligesom min mand og mig.$"

Route133_Text_ConorIntro:
	.string "Unge mennesker er alt for glade for at\n"
	.string "følge strømmen. De er uden retning.$"

Route133_Text_ConorDefeat:
	.string "Du har et fast formål.$"

Route133_Text_ConorPostBattle:
	.string "Lad ikke andre føre dig på afveje. Mist\n"
	.string "ikke retning, når du bliver ældre.$"

Route134_Text_JackIntro:
	.string "Selv de POKéMON, der kan svømme, bliver\n"
	.string "ført med af de hurtige strømme.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "Jeg tror POKéMON nyder de hurtigt\n"
	.string "flydende strømme omkring disse dele.$"

Route134_Text_LaurelIntro:
	.string "Mine LUVDISC leder efter et sjovt kamp.\n"
	.string "Vil du være med?$"

Route134_Text_LaurelDefeat:
	.string "Ups!$"

Route134_Text_LaurelPostBattle:
	.string "Der er en samler, der er ude efter\n"
	.string "SKALERNE fra LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okay, venner! Det er nok med hvilen, det\n"
	.string "er tid til en kamp!$"

Route134_Text_AlexDefeat:
	.string "Træt igen…$"

Route134_Text_AlexPostBattle:
	.string "Mine FUGL POKéMON bliver hurtigt trætte\n"
	.string "efter en lang flyvning…$"

Route134_Text_HitoshiIntro:
	.string "Du er en POKéMON TRÆNER. Ingen grund\n"
	.string "til ord. Vi kæmper nu.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … … … … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "Det var mig, der udfordrede dig, og\n"
	.string "alligevel tabte jeg. Jeg er dybt\l"
	.string "skamfuld…$"

Route134_Text_AaronIntro:
	.string "Den vilde tide i dette område er med til\n"
	.string "at gøre os stærkere end nogensinde.$"

Route134_Text_AaronDefeat:
	.string "Jeg giver mig frivilligt.$"

Route134_Text_AaronPostBattle:
	.string "Vi vender tilbage til mere træning på\n"
	.string "METEOR FALLS.\p"
	.string "Hvis du har lyst, burde du også tage\n"
	.string "med. Det vil helt sikkert gøre dig\l"
	.string "stærkere!$"

Route134_Text_KelvinIntro:
	.string "V-Vores båd! Strømmen har båret den\n"
	.string "væk!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah! Stoooop! Stoooop!$"

Route134_Text_KelvinPostBattle:
	.string "Hvordan skal vi komme hjem, hvis vi ikke\n"
	.string "kan SURFE?\p"
	.string "Faktisk, jeg ved, at en besvimet\n"
	.string "POKéMON stadig kan SURFE, men det føles\l"
	.string "forkert.$"

Route134_Text_MarleyIntro:
	.string "Kan dine POKéMON undvige vores\n"
	.string "lynhurtige angreb?$"

Route134_Text_MarleyDefeat:
	.string "Jeg vidste aldrig, at sådan en teknik\n"
	.string "eksisterede! Du har besejret os helt.$"

Route134_Text_MarleyPostBattle:
	.string "Jeg har ikke mistet min passion for\n"
	.string "fart. Jeg vil forsøge hårdere.$"

Route134_Text_ReynaIntro:
	.string "Mine POKéMON kan ikke tages ned let!$"

Route134_Text_ReynaDefeat:
	.string "Du må da være skør! Forklar hvordan jeg\n"
	.string "tabte!$"

Route134_Text_ReynaPostBattle:
	.string "Haha! Du vandt, helt sikkert!\p"
	.string "Jeg vil arbejde mig tilbage ved at tage\n"
	.string "udfordringer fra TRÆNERE, jeg møder!$"

Route134_Text_HudsonIntro:
	.string "Hør lige, har du set en anden SØMAND\n"
	.string "omkring her?$"

Route134_Text_HudsonDefeat:
	.string "Nå, det var noget!$"

Route134_Text_HudsonPostBattle:
	.string "Vores båd drev ud til havs.\p"
	.string "Min ven er en forsigtig fyr, så jeg er\n"
	.string "bekymret for ham.$"



