LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Hej, halloj! Du var til en POKéMON\n"
	.string "KONKURRENCE, ikke sandt?\l"
	.string "Det kan jeg nemt se ud fra dine POKéMON.\p"
	.string "Jeg er reporter. Jeg arbejder på en historie\n"
	.string "om POKéMON-KONKURRENCER.\p"
	.string "Hvis du vil, vil du så være villig til at\n"
	.string "svare på nogle spørgsmål?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Åh, vil du det?\n"
	.string "Tak.\p"
	.string "Kort sagt, hvordan vil du beskrive\n"
	.string "DEN KONKURRENCE, du lige deltog i?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Åh, jeg forstår.\n"
	.string "Det er en meget oplysende kommentar.\p"
	.string "Du får en god fornemmelse af,\n"
	.string "hvordan KONKURRENCEN var.\p"
	.string "Jeg har et sidste spørgsmål.\p"
	.string "Når du hører ordet “{STR_VAR_2},”\n"
	.string "hvilket billede dukker op?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Jeg forstår!\p"
	.string "Sådan forestiller du dig konceptet\n"
	.string "“{STR_VAR_2}” altså. \p"
	.string "Tak!\n"
	.string "Du har givet mig nogle gode idéer.\p"
	.string "Jeg tror, jeg kan skrive en god historie\n"
	.string "om POKéMONKONKURRENCER nu.\p"
	.string "Måske, bare måske, kommer denne historie\n"
	.string "endda på fjernsyn.\l"
	.string "Jeg håber, du glæder dig til det!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Åh, det var ærgerligt...\p"
	.string "Hvis du nu skulle støde på en god historie,\n"
	.string "så del den gerne med mig.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Jeg glæder mig til din næste\n"
	.string "POKéMON-KONKURRENCE.$"

gTVBravoTrainerText00::
	.string "Jubi!\n"
	.string "Det er BRAVO TRAINER tid!\p"
	.string "I dag vil vi præsentere en POKéMON\n"
	.string "som tilhører {STR_VAR_1}.\p"
	.string "Denne POKéMON praler med en {STR_VAR_3}\n"
	.string "rangering i {STR_VAR_2} kategorien.$"

gTVBravoTrainerText01::
	.string "Præsenterer {STR_VAR_2},\n"
	.string "{STR_VAR_1}!\p"
	.string "Kælenavnet {STR_VAR_2}…\p"
	.string "Selv kælenavnet udstråler en attitude der\n"
	.string "proklamerer “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Nå, da TRÆNEREN {STR_VAR_1}\n"
	.string "meldte POKéMON til en KONKURRENCE,\l"
	.string "lykkedes det os at få nogle begejstrede\l"
	.string "citat fra den pålidelige partner.$"

gTVBravoTrainerText03::
	.string "Spurgt om KONKURRENCEN bagefter,\n"
	.string "{STR_VAR_1} svarede lykkeligt med et\l"
	.string "kæmpe smil, “{STR_VAR_2}!”\p"
	.string "Nå ja, {STR_VAR_1}'s POKéMON kom\n"
	.string "på plads {STR_VAR_3} i KONKURRENCEN.\p"
	.string "Den sætning passer perfekt til {STR_VAR_1}\n"
	.string "lige nu, vil jeg sige!$"

gTVBravoTrainerText04::
	.string "Spurgt om KONKURRENCEN bagefter,\n"
	.string "{STR_VAR_1} svarede med en smule\l"
	.string "bitterhed, “{STR_VAR_2}.”\p"
	.string "Nå, selvfølgelig, {STR_VAR_1}s POKéMON\n"
	.string "kom på plads nummer {STR_VAR_3} i\n"
	.string "KONKURRENCEN.\p"
	.string "{STR_VAR_1}s skuffelse skinner klart\n"
	.string "igennem, vil jeg sige!$"

gTVBravoTrainerText05::
	.string "Wouldn't you also like to know what\n"
	.string "{STR_VAR_1} imagines {STR_VAR_2} to be?\p"
	.string "You bet we did!\n"
	.string "So we asked, of course!\p"
	.string "The answer is all perfectly condensed:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "That's what the concept of {STR_VAR_2}\n"
	.string "represents to {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "Den sidste bevægelse {STR_VAR_2}\n"
	.string "brugt af {STR_VAR_1} handler\l"
	.string "hele vejen om “{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "Super godt gået, {STR_VAR_1}!\n"
	.string "Fantastisk, {STR_VAR_2}!\p"
	.string "Jeg håber, vi kan regne med at se\n"
	.string "{STR_VAR_1} nå endnu større højder!\p"
	.string "Det er alt den tid, vi har!\n"
	.string "Vi ses næste gang!$"

gTVBravoTrainerText08::
	.string "Præsenterer TRÆNERENS {STR_VAR_1}!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Hej! Er du TRÆNEREN, der lige har haft\n"
	.string "en kamp, ikke sandt?\p"
	.string "Jeg samler interviews med TRÆNERE\n"
	.string "overalt.\p"
	.string "Må jeg få nogle ord fra dig om dine\n"
	.string "indtryk af at kæmpe?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Vil du? Virkelig?\n"
	.string "Tak!\l"
	.string "Øh, så...\p"
	.string "Hvordan gik det i\n"
	.string "KAMPENS TÅRN i dag?\p"
	.string "Var du tilfreds med kampen?\n"
	.string "Eller er du utilfreds?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Åh...\n"
	.string "Undskyld vi forstyrrede dig.\p"
	.string "Vil du give os et interview næste\p"
	.string "gang du besøger KAMPTÅRNET.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Selvfølgelig!\p"
	.string "Det ufejlbarlige udtryk af tilfredshed\n"
	.string "på dit ansigt…\p"
	.string "Det er tydeligt, at du har haft en stor\n"
	.string "kamp.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Åh, jeg forstår... \p"
	.string "Det er virkelig svært at få en kamp til\n"
	.string "at forløbe præcis som planlagt.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Åh, må jeg stille endnu et spørgsmål?\p"
	.string "Hvis du skulle beskrive dine\n"
	.string "indtryk af denne kamp med\n"
	.string "én sætning, hvad ville det være?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Åh, det er helt vildt sejt!\p"
	.string "Det er en fantastisk linje!\n"
	.string "Jeg håber, at du klarer dig fantastisk næste gang også.\p"
	.string "Jeg håber at se dig igen!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Åh, jeg forstår... \p"
	.string "Men at være den stille type er\n"
	.string "også sejt, ikke sandt? \p"
	.string "Jeg håber, at du vil give mig\n"
	.string "muligheden for at dele dine tanker\n"
	.string "igen!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Jeg glæder mig til din\n"
	.string "næste kamp!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Ja!\n"
	.string "Det er BRAVO TRAINER tid!\p"
	.string "I dag skal vi profilere {STR_VAR_1},\n"
	.string "som tog BATTLE TOWER udfordringen!\p"
	.string "Til udfordringen brugte {STR_VAR_1}\n"
	.string "ét vildt {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Dette par satte en ny rekord med {STR_VAR_2} sejre\n"
	.string "i træk i {STR_VAR_1} konkurrence!\l"
	.string "Bravo, TRÆNER!$"

BravoTrainerBattleTower_Text_Lost::
	.string "De to endte endelig med at give op\n"
	.string "over for {STR_VAR_1} i kamp nummer {STR_VAR_2}.\l"
	.string "Godt forsøgt, TRÆNER!\p"
	.string "Men hey, det er bare uheldigt at løbe ind i\n"
	.string "{STR_VAR_1} så tidligt i udfordringen.\p"
	.string "Vi bad TRÆNEREN om indtryk\n"
	.string "af kampen med {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "Det seje twosome vandt det hele ved at slå\n"
	.string "{STR_VAR_1}'s {STR_VAR_2} grundigt.\l"
	.string "Bravo, TRÆNER!\p"
	.string "At slå endda {STR_VAR_1}…\n"
	.string "Det er ubegribeligt! Simpelthen fantastisk!\p"
	.string "Vi bad TRÆNEREN om indtryk\n"
	.string "af øjeblikket med herlighed.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Efter en række sejre gav de endelig\n"
	.string "efter for {STR_VAR_1}'s {STR_VAR_2},\l"
	.string "deres sidste forhindring.\p"
	.string "Godt forsøg, TRÆNER!\p"
	.string "Alligevel må man give credit.\n"
	.string "Man ser ikke mange berømte kombinationer\l"
	.string "som {STR_VAR_1} og {STR_VAR_2}.\p"
	.string "Vi spurgte TRÆNEREN om indtrykkene\n"
	.string "af at kæmpe mod det berømte par.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Det her er hvad TRÆNEREN sagde:\n"
	.string "“Jeg er tilfreds!”\p"
	.string "Er det ikke en forfriskende svar?\n"
	.string "Bravo, TRÆNER!\p"
	.string "Er det ikke bare fantastisk at kunne\n"
	.string "kæmpe til fuld tilfredshed?\p"
	.string "Jeg fandt ud præcist hvor tilfreds\n"
	.string "jeg blev, da jeg hørte TRÆNEREN sige dette:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Dette er hvad TRÆNEREN havde at sige:\n"
	.string "“Jeg er ikke tilfreds…”\p"
	.string "Vores TRÆNER var åbenlyst lidt nede\n"
	.string "da det blev sagt.\p"
	.string "Det er stadig ikke let at være i stand til\n"
	.string "at kæmpe med fuld tilfredshed, ikke sandt?\p"
	.string "Uanset hvad, fandt jeg ud af hvor utilfreds\n"
	.string "vores TRÆNER var da jeg hørte dette:$"

BravoTrainerBattleTower_Text_None1::
	.string "Ingen$"

BravoTrainerBattleTower_Text_None2::
	.string "Ingen$"

BravoTrainerBattleTower_Text_None3::
	.string "Ingen$"

BravoTrainerBattleTower_Text_None4::
	.string "Ingen$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$" 

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Er det ikke fantastisk?\p"
	.string "Det udtrykker virkelig {STR_VAR_2}s glæde,\n"
	.string "vil jeg sige.\p"
	.string "Den kamp mod {STR_VAR_3} i\n"
	.string "slutningen… Det var virkelig det man kalder\l"
	.string "“{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Nu er det da passende, ikke sandt?\p"
	.string "Den kamp med {STR_VAR_3} i\n"
	.string "slutningen… Man kan ikke beskrive det\n"
	.string "som andet end “{STR_VAR_1}”!\p"
	.string "{STR_VAR_2}'s skuffelse er helt\n"
	.string "tydelig, vil jeg sige!$"  

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Jeg håber, vi kan regne med at se\n"
	.string "{STR_VAR_1} nå endnu større højder!\p"
	.string "Det er alt den tid, vi har!\n"
	.string "Vi ses næste gang!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "Det er tydeligt, at du overøser kærlighed\n"
	.string "på din {STR_VAR_1}.\p"
	.string "Okay, den hedder {STR_VAR_2}.\p"
	.string "Kan jeg bede om en tjeneste?\p"
	.string "Jeg er en TV-reporter, og jeg laver\n"
	.string "en undersøgelse om POKéMON.\p"
	.string "Vil du være villig til at svare på et\n"
	.string "par simple spørgsmål for mig?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Fantastisk! Tak!\p"
	.string "Okay, her går det.\n"
	.string "Jeg har bare brug for hurtige svar, okay?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Da du først mødte {STR_VAR_1},\n"
	.string "hvad følte du?\p"
	.string "Hvordan vil du beskrive dine følelser\n"
	.string "på det tidspunkt?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Din {STR_VAR_1} bliver passet kærligt på.\p"
	.string "Hvis du skulle sammenligne det med\n"
	.string "noget, du godt kan lide, hvad ville det være?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Denne spørgsmål handler også om din\n"
	.string "elskede {STR_VAR_1}.\p"
	.string "Hvad var det ved {STR_VAR_1}, der\n"
	.string "tiltrak dig?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Okay, det giver mening.\p"
	.string "Det næste spørgsmål kan være lidt\n"
	.string "svært.\p"
	.string "Her kommer det…\p"
	.string "Hvad betyder POKéMON for dig?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
    .string "Jeg forstår!\p"
    .string "Hmhm…\p"
    .string "Okay!\n"
    .string "Tak for at hjælpe mig.\p"
    .string "Det var sjovt og oplysende\n"
    .string "at snakke med dig.\p"
    .string "Det er muligt, at vores interview\n"
    .string "ender på tv. Hold dig opdateret!\p"
    .string "Okay, det er det.\n"
    .string "Hej-hej!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Nå, okay…\p"
	.string "Nå, hvis du får lyst til at fortælle mig\n"
	.string "om POKéMON, så er jeg her!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Jeg nyder dette job--du lærer\n"
	.string "om POKéMON ved at lave interviews.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
    .string "Hej, du virker meget tæt på din\n"
    .string "{STR_VAR_1}.\p"
    .string "Gæt hvad?\n"
    .string "Jeg er en tv-reporter.\p"
    .string "Jeg rejser rundt og interviewer folk\n"
    .string "om POKéMON.\p"
    .string "Jeg tænkte på, om du ville fortælle\n"
    .string "mig lidt om din {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Wow, tak!\p"
	.string "Okay, så fortæl mig venligst\n"
	.string "alt, hvad du vil, om din {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Wow…\n"
	.string "Det er en spændende historie.\p"
	.string "Du er virkelig tætte med {STR_VAR_1},\n"
	.string "ikke sandt?\p"
	.string "Jeg har en fornemmelse af,\n"
	.string "at din historie vil blive en fed TV-\n"
	.string "fortælling.\p"
	.string "Jeg lover, at jeg vil gøre dette til\n"
	.string "et underholdende show.\l"
	.string "Hold øjnene åbne for det.\p"
	.string "Okay, det var alt.\n"
	.string "Hej-hej!$"

gTVFanClubOpinionsText00::
	.string "VI ER POKéMON-FANKLUBBEN!\p"
	.string "Vi er på luften!\p"
	.string "I dette program får vi jeres\n"
	.string "meninger, og jeg råber dem ud på jeres\n"
	.string "vegne!\l"
	.string "Er det ikke en fantastisk programidé?\p"
	.string "I dag bringer vi denne rapport fra\n"
	.string "vores reporter, som vi sendte ud til\n"
	.string "POKéMON-FANKLUBBEN.\p"
	.string "Så, hvem er dagens fremhævede\n"
	.string "POKéMON-fan?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Lad os høre, hvad {STR_VAR_1} har at\n"
	.string "sige om {STR_VAR_3} den {STR_VAR_2}.\p"
	.string "Og jeg vil råbe disse kærlighedsord\n"
	.string "højt på tv!\p"
	.string "Hoo-hah!\p"
	.string "Lad os råbe!$"

gTVFanClubOpinionsText01::
	.string "Vi spurgte {STR_VAR_1}, “Da du først\n"
	.string "så din {STR_VAR_2}, hvad tænkte du så\l"
	.string "første gang?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Yeahah! Det var da en kanon god\n"
	.string "udråb!\p"
	.string "Giver det ikke minder om de gode\l"
	.string "gamle dage?$"

gTVFanClubOpinionsText02::
	.string "Vi spurgte {STR_VAR_1}, “Hvis du skulle\n"
	.string "sammenligne din {STR_VAR_2} med noget,\l"
	.string "ville det være…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Whoah-oh, det er virkelig en original idé!\p"
	.string "Du kan virkelig fornemme TRÆNERENS\n"
	.string "intensitet af følelser for\l"
	.string "{STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Og lad os se...\n"
	.string "Hvad var det ved den {STR_VAR_2},\n"
	.string "som tiltrak {STR_VAR_1} så meget?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Wow! En så spektakulær erklæring!\p"
	.string "{STR_VAR_1}s kærlighed til\n"
	.string "{STR_VAR_2} skinner tydeligt igennem!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oh, there's still more.\n"
	.string "Let's check it out!\p"
	.string "Let me see, now…\p"
	.string "We asked {STR_VAR_1}, “What do POKéMON\n"
	.string "mean to you?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "That's the best shout I've had all day!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "It makes you want to shout it out loud\n"
	.string "again and again!\p"
	.string "Now that we've had a great shout, it's\n"
	.string "time to say good-bye until next time!\p"
	.string "So, let's all have one last shout!\n"
	.string "All together now…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "VI ER POKéMON FANKLUBBEN!\p"
	.string "Vi er på luften!\p"
	.string "I dag går vi i gang med\nPOKéMON UNDERSØGELSESKROGEN.\p"
	.string "Af alle de historier, der er vævet\n"
	.string "af POKéMON og TRÆNERE, hvilken\n"
	.string "overraskende ny drama vil fange\nv\nores opmærksomhed i dag?\p"
	.string "Lad mig se…\p"
	.string "Den her!\p"
	.string "Vi starter med det her brev!\p"
	.string "Det er et brev fra {STR_VAR_1} om en\n"
	.string "elsket {STR_VAR_2}.\p"
	.string "Lad os se, hvor lidenskabeligt vores\n"
	.string "forfatter kan udtrykke kærlighed til\n{STR_VAR_2}!\l"
	.string "Hmhm…$"

gTVFanClubText01::
	.string "Whoah!\n"
	.string "Hvilket fantastisk brev!$"

gTVFanClubText02::
	.string "Jeg elskede det, så her er det igen!$"

gTVFanClubText03::
	.string "Et fantastisk brev er værd at læse om\n"
	.string "og om igen!$"

gTVFanClubText04::
	.string "Det stykke “{STR_VAR_3},” det virkelig\n"
	.string "accentuerer den følelsesmæssige\n"
	.string "påvirkning!\p"
	.string "Det er et fantastisk brev, der har en\n"
	.string "dybfølt dybde!$"

gTVFanClubText05::
	.string "Især den der “{STR_VAR_3}”-del!\p"
	.string "Jeg elsker, hvordan “{STR_VAR_3}” bliver brugt!$"

gTVFanClubText06::
	.string "Forresten, og det er ikke vigtigt,\n"
	.string "men {STR_VAR_3} er en fantastisk udtalelse.\p"
	.string "Jeg har brugt {STR_VAR_3} meget\n"
	.string "i samtaler for nylig.$"

gTVFanClubText07::
	.string "Hvis jeg skulle give denne besked en karakter,\n"
	.string "ville jeg give den {STR_VAR_3} point.\p"
	.string "Næste gang forventer jeg en\n"
	.string "endnu bedre besked, {STR_VAR_1}!\p"
	.string "Åh ups, ser du lige på klokken?\n"
	.string "Tid til at sige farvel indtil næste gang!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Nå?\n"
	.string "Kan det være, at du godt kan lide POKéMON?\p"
	.string "Jeg er på opgave for TV-netværket.\p"
	.string "Jeg samler historier om POKéMON og\n"
	.string "TRÆNERE, der er sket for nylig.\p"
	.string "Hvis du har lyst, kunne du så ikke fortælle mig\n"
	.string "lidt om dig selv?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Jeg indsamler historier om POKéMON og\n"
	.string "TRÆNERE, der skete for nylig.\p"
	.string "Hvis det er i orden, kunne du så ikke\n"
	.string "fortælle mig noget om dig selv?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Åh, vil du det?\n"
	.string "Tak!\p"
	.string "Så fortæl mig venligst noget\n"
	.string "interessant, som du har oplevet\n"
	.string "for nylig med POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Åh, nu forstår jeg…\p"
	.string "Hvis du har en interessant historie\n"
	.string "at fortælle, så lad mig venligst vide.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Åh, sikke en opmuntrende historie!\p"
	.string "Jeg skal sørge for, at din historie\n"
	.string "bliver fortalt på tv.\p"
	.string "Det burde blive vist på et tidspunkt,\n"
	.string "så glæd dig til det.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmmm...\n"
	.string "Jeg har en god historie til et tv-program.\p"
	.string "Jeg bør nok skrive den ned i en fart!$"

gTVRecentHappeningsText00::
	.string "Hej, det er tid til SENESTE NYT.\p"
	.string "For POKéMON TRÆNERE,\n"
	.string "er hver dag som en eventyrbogshistorie.\p"
	.string "Hvad vi gerne vil, er at præsentere dig\n"
	.string "for nogle af disse POKéMON-historier.\p"
	.string "I dag bringer vi dig historien\n"
	.string "om TRÆNER {STR_VAR_1}.\p"
	.string "Hvad har {STR_VAR_1} oplevet for nylig?\n"
	.string "Lad os finde ud af det.\p"
	.string "Lad os se…$"

gTVRecentHappeningsText01::
	.string "Var det ikke oplysende?\p"
	.string "Historien giver dig en klar idé om, hvad\n"
	.string "{STR_VAR_1} har oplevet for nylig.\l"
	.string "Det er, som om vi var der som vidner!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Det\n"
	.string "giver fortællingen et strejf og dybde.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.”\n"
	.string "Det giver historien en følelse af sted.\l"
	.string "Det lader os forestille os historiens miljø.$"

gTVRecentHappeningsText04::
	.string "Afsnittet “{STR_VAR_3}”\n"
	.string "i historien er meget udtryksfuldt.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} har genfortalt en fantastisk\n"
	.string "historie om POKéMON.\p"
	.string "Og nu er {STR_VAR_1}s historie uudsletteligt\n"
	.string "indgraveret i din sjæl også.\p"
	.string "Det var alt for i dag.\n"
	.string "Tune venligst ind næste gang.$"

gTVMassOutbreakText00::
	.string "Hej!\n"
	.string "Det er tid til POKéMON-NYHEDERNE.\p"
	.string "Vi har netop fået ord om en meget\n"
	.string "sjælden begivenhed.\p"
	.string "Der er rapporter om et massivt\n"
	.string "udbrud af {STR_VAR_2} i nærheden af\l"
	.string "{STR_VAR_1}.\p"
	.string "{STR_VAR_2}, som du sandsynligvis\n"
	.string "er klar over, er kendt som en\n"
	.string "POKéMON, der er sjælden og svær at\n"
	.string "finde.\p"
	.string "Det lyder som en sjælden mulighed\n"
	.string "for at se det forbløffende udbrud af\l"
	.string "{STR_VAR_2} i det vilde.\p"
	.string "Det var nyhederne på POKéMON-\n"
	.string "NYHEDERNE.$"

gTV3CheersForPokeblocksText00::
	.string "MC: Vi håber, du er i godt humør,\n"
	.string "“3 HURRA FOR {POKEBLOCK}S” er her!\p"
	.string "I dag undersøger vi {POKEBLOCK}'en blandet\n"
	.string "af {STR_VAR_1} og venner.\p"
	.string "Uden yderligere forsinkelse, lad mig fodre\n"
	.string "min gourmet POKéMON GULPIN.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Og dommen er meget {STR_VAR_1}!\n"
	.string "GULPIN siger, det smager “{STR_VAR_2}”!\p"
	.string "Mange tak, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "{STR_VAR_1}s blendingevner\n"
	.string "lod noget tilbage at ønske.\p"
	.string "Hvis denne TRÆNER kunne blande\n"
	.string "bedre, ville {POKEBLOCK}'en være\n"
	.string "meget mere velsmagende.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Hmm… Det er for {STR_VAR_1}.\n"
	.string "GULPIN siger, at det smager “{STR_VAR_2}”! \p"
	.string "Det ser ud til, at {STR_VAR_3}'s fejl\n"
	.string "påvirker blandingens kvalitet...$"

gTV3CheersForPokeblocksText04::
	.string "Det er ærgerligt at {STR_VAR_1}'s\n"
	.string "ledende indsats gik til spilde.\p"
	.string "Lad os håbe at {STR_VAR_2} kan\n"
	.string "levere en bedre præstation næste gang!$"

gTV3CheersForPokeblocksText05::
	.string "Følg med næste gang!\n"
	.string "Vores slogan er “3 HURRA FOR {POKEBLOCK}S!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Hej med dig!\p"
	.string "Jeg er en stor fan af {STR_VAR_1}.\n"
	.string "Hvad er din mening om {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Jeg forstår, jeg forstår. Det er hvad\n"
	.string "du tænker om TRÆNEREN.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Har du helt glemt\n"
	.string "om {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Jeg er kæmpe fan af {STR_VAR_1}.\n"
	.string "Hvad er din mening om {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Hvor stærk vil du vurdere {STR_VAR_1}\n"
	.string "på en skala fra ét til hundrede?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Har du helt glemt\n"
	.string "om {STR_VAR_1}?\p$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Åh, jeg forstår!\n"
	.string "Du burde møde {STR_VAR_1} en dag.\l"
	.string "Jeg er sikker på, at du også vil blive fan!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Jeg forstår, jeg forstår.\p"
	.string "Tak!\n"
	.string "Det er meget nyttigt at vide.\p"
	.string "Jeg vil dele denne information med andre\n"
	.string "{STR_VAR_1} fans og diskutere det.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Der kommer til at være en TV-special om\n"
	.string "{STR_VAR_1} meget snart.\p"
	.string "Jeg håber, du fanger den!$"

gTVTrainerFanClubSpecialText00::
	.string "TRÆNER FAN KLUB\n"
	.string "{STR_VAR_1} SPECIAL!\p"
	.string "Dette er en speciel præsentation for\n"
	.string "fans af {STR_VAR_1} over hele HOENN!\p"
	.string "I dag stiller vi spørgsmålet, “Hvad\n"
	.string "tænker folk om {STR_VAR_1}?”\p"
	.string "Vi spurgte {STR_VAR_2} som\n"
	.string "TRÆNER repræsentant.\p"
	.string "Vi spurgte, “Hvordan vil du i et ord\n"
	.string "beskrive {STR_VAR_1}?”\p"
	.string "Svaret: “{STR_VAR_3}.”\p"
	.string "Godt klaret, {STR_VAR_2}!\n"
	.string "Hvilken skarp opfattelse!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "Det har en dejlig klang!\p"
	.string "{STR_VAR_2} gav også {STR_VAR_1}'s\n"
	.string "styrke en vurdering fra 0 til 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Resultatet var {STR_VAR_3} point!\n"
	.string "Det er virkelig en høj score!\p"
	.string "{STR_VAR_2} må tydeligvis finde\n"
	.string "{STR_VAR_1} meget højt.$"

gTVTrainerFanClubSpecialText02::
	.string "Scoret var {STR_VAR_3} point!\n"
	.string "Det er et ret godt resultat.\p"
	.string "{STR_VAR_2} må tage\n"
	.string "{STR_VAR_1} som en rival.$"

gTVTrainerFanClubSpecialText03::
	.string "Scoret var {STR_VAR_3} point!\n"
	.string "Det er et ret svagt score.\p"
	.string "{STR_VAR_2} må overveje\n"
	.string "{STR_VAR_1} som en simpel hjælper.$"

gTVTrainerFanClubSpecialText04::
	.string "Du fik {STR_VAR_3} point!\n"
	.string "Det var en forfærdelig score.\p"
	.string "{STR_VAR_2} må tage\n"
	.string "{STR_VAR_1} for at være en underordnet.$"

gTVTrainerFanClubSpecialText05::
	.string "Her har I det, venner!\p"
	.string "Jeg tror, vi alle har lært noget\n"
	.string "nyt om {STR_VAR_1}.\p"
	.string "Afslutningsvis vil jeg give jer\n"
	.string "{STR_VAR_2}s ord.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Og nu er tiden inde til…\n"
	.string "NAVNEVURDERINGSSHOWET!\p"
	.string "Jeg spår din POKéMONs skæbne ud fra\n"
	.string "det kaldenavn, du har givet den.\p"
	.string "Jeg har råd at give, og det er\n"
	.string "nyttige råd, jeg tilbyder.\p"
	.string "I dag vil jeg fortolke kaldenavnet\n"
	.string "{STR_VAR_3} tilhørende {STR_VAR_1}'s\n"
	.string "POKéMON {STR_VAR_2}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Dette kaldenavn er…$"

gTVNameRaterText01::
	.string "Et kaldenavn, der antyder talent på\n"
	.string "mange forskellige måder.\p"
	.string "Jeg opfordrer denne TRÆNER til at tage\n"
	.string "courage og påtage sig mange udfordringer.$"

gTVNameRaterText02::
	.string "Et kaldenavn, der passer perfekt til\n"
	.string "{STR_VAR_1}, TRÆNERENS navn.\p"
	.string "Det antyder, at I vil danne et godt\n"
	.string "partnerskab med præcis timing.$"

gTVNameRaterText03::
	.string "Et kaldenavn passende til en unik person\n"
	.string "af en POKéMON!\p"
	.string "Hvis opdrættet korrekt, vil denne POKéMONs\n"
	.string "unikke karakter trives overdrevet!$"

gTVNameRaterText04::
	.string "Et kælenavn, der vil nære omsorgen og\n"
	.string "den medfølende side af POKéMON.\p"
	.string "Hvis den opdrages ordentligt, vil denne\n"
	.string "POKéMON udvise ægte varme!$"

gTVNameRaterText05::
	.string "Et virkelig fint kaldenavn, der antyder\n"
	.string "storhed i vente.\p"
	.string "Jeg er nysgerrig på, hvad fremtiden\n"
	.string "har i vente for denne POKéMON.$" 

gTVNameRaterText06::
	.string "Et godt kaldenavn, der bør få\n"
	.string "POKéMON til at være rasende og glade!\p"
	.string "Den POKéMON bør forblive sund og\n"
	.string "robust i lang, lang tid.$"

gTVNameRaterText07::
	.string "Et godt kælenavn, der burde gøre\n"
	.string "POKéMON meget aktivt!\p"
	.string "Jeg burde tænke, at denne POKéMON vil\n"
	.string "være en stærk performer i kampe.$"

gTVNameRaterText08::
	.string "En tiltalende kaldenavn, som burde\n"
	.string "gøre POKéMON'en meget charmerende!\p"
	.string "Jeg tvivler ikke på, at denne POKéMON\n"
	.string "vil være ganske charmerende i POKéMON-\n"
	.string "konkurrencer.$"

gTVNameRaterText09::
	.string "Kaldenavnet {STR_VAR_1} har sin rod i\n"
	.string "bogstavet “{STR_VAR_3}.”\p"
	.string "Det bogstav støttes af det første bogstav\n"
	.string "“{STR_VAR_2},” hvilket giver det en solid følelse\l"
	.string "af tilstedeværelse som et kaldenavn.$"

gTVNameRaterText10::
	.string "Kælenavnet {STR_VAR_1} er meget\n"
	.string "smukt på en behagelig måde.\p"
	.string "Tilstedeværelsen af bogstaverne “{STR_VAR_2}” og\n"
	.string "“{STR_VAR_3}” - det er virkelig godt!$"

gTVNameRaterText11::
	.string "Kælenavnet {STR_VAR_1}--det har en\n"
	.string "sublim, strømmende fornemmelse til det.\p"
	.string "Overgangen fra det første bogstav “{STR_VAR_2}” til\n"
	.string "“{STR_VAR_3}” er specielt vidunderlig.$"

gTVNameRaterText12::
    .string "Lad os undersøge andre eksempler\n" 
    .string "på gode kælenavne, skal vi?$"

gTVNameRaterText13::
	.string "Prøv dette eksempel. Tag en del af\n"
	.string "TRÆNER-navnet {STR_VAR_1}, og afslut\l"
	.string "med det fine kælenavn {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "Kælenavnet {STR_VAR_2}{STR_VAR_3} ville også\n"
	.string "være ganske godt.$"

gTVNameRaterText15::
	.string "POKéMON'et artens navn\n"
	.string "til {STR_VAR_2} kan bruges som\n"
	.string "grundlag for kaldenavnet {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} ville også være en effektiv\n"
	.string "kaldenavn.$"

gTVNameRaterText17::
	.string "Det, du altid skal undgå, er at bruge\n"
	.string "et andet POKéMON-artsnavn.\p"
	.string "For eksempel, undgå at bruge navnet\n"
	.string "{STR_VAR_2} til at lave kælenavnet {STR_VAR_1}{STR_VAR_3}.\l"
	.string "Det er uacceptabelt.$"

gTVNameRaterText18::
	.string "Jeg må sige, at {STR_VAR_1} er\n"
	.string "et rigtig godt kælenavn.\p"
	.string "Jeg håber, at TRÆNEREN vil fortsætte\n"
	.string "med at behandle {STR_VAR_1} med kærlighed.\p"
	.string "Det var alt for dagens program.\n"
	.string "Må vi mødes igen.$"

gTVPokemonAnglerText00::
	.string "{STR_VAR_2} FISKER\p"
	.string "VÆRT: Hej! I dag får vi tips til\n"
	.string "fiskeri efter {STR_VAR_2}.\p"
	.string "EKSPERT, hvilke råd kan du give til\n"
	.string "at fange {STR_VAR_2}?\p"
	.string "EKSPERT: Hm? Fange {STR_VAR_2}?\n"
	.string "Nå, lad mig fortælle dig, vær tålmodig\n"
	.string "og vent. Det er det vigtigste.\p"
	.string "Ser du {STR_VAR_1} derovre?\n"
	.string "Den TRÆNER er et godt eksempel.\p"
	.string "Den TRÆNER har allerede haft\n"
	.string "{STR_VAR_3} POKéMON undslippe.\p"
	.string "Men der venter {STR_VAR_1}. Ingen opgivelse.\n"
	.string "Det er reglen for at fange {STR_VAR_2}.\p"
	.string "VÆRT: Jeg forstår…\p"
	.string "Åh! {STR_VAR_1} har endelig landet en\n"
	.string "undvigende {STR_VAR_2}!\p"
	.string "TRÆNEREN ser ud til at være tæt på\n"
	.string "at græde af ren glæde!\p"
	.string "Når jeg ser det lykkelige udtryk, får jeg\n"
	.string "lyst til at tage ud og fiske også!\p"
	.string "Seere, hvorfor ikke tage dette som et tegn på\n"
	.string "at prøve lidt {STR_VAR_2}-fiskeri?\p"
	.string "Indtil vores næste udsendelse, farvel og\n"
	.string "god fisketur til jer alle!$"

gTVPokemonAnglerText01::
	.string "{STR_VAR_2} FISKER\p"
	.string "VÆRT: Hej! I dag får vi tips til\n"
	.string "fiskeri efter {STR_VAR_2}.\p"
	.string "EKSPERT, hvilke råd kan du give til\n"
	.string "fangst af {STR_VAR_2}?\p"
	.string "EKSPERT: Hm? Fangst af {STR_VAR_2}?\n"
	.string "Nå, lad mig fortælle dig, brug din\n"
	.string "fiskeSTANG med iver!\p"
	.string "Ser du {STR_VAR_1} derovre?\n"
	.string "Ser du, hvordan STANGEN bliver brugt?\p"
	.string "Den TRÆNER har allerede fanget\n"
	.string "{STR_VAR_3} i træk.\p"
	.string "VÆRT: Det er utroligt!\n"
	.string "Det ligner en storm…\p"
	.string "Når man ser en teknik af det kaliber,\n"
	.string "får jeg også lyst til at tage ud og\n"
	.string "fiske. /nSeere, hvorfor ikke tage det\n"
	.string "som et tegn til at prøve lidt\n"
	.string "{STR_VAR_2}-fiskeri?\p"
	.string "Indtil vores næste udsendelse, farvel og\n"
	.string "god fisketur til jer alle!$"

gTVPokemonTodayFailedText00::
	.string "Hej!\p"
	.string "Det er tid til POKéMON I DAG!\p"
	.string "STORE SØSTER: Hej! Er alle skønne og\n"
	.string "glade i dag?\p"
	.string "I dag skal vi kigge på {STR_VAR_1}s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "STORE BROR: Ja! Det er det vi skal!$"

gTVPokemonTodayFailedText01::
	.string "Åh!\n"
	.string "Når vi taler om {STR_VAR_1}…\p"
	.string "STORE SØSTER, jeg så TRÆNEREN med\n"
	.string "mine egne øjne!\p"
	.string "STORE SØSTER: Hvad så du?\p"
	.string "STORE BROR: Jo, jeg var nødt til at tage\n"
	.string "en tur til {STR_VAR_2}.\p"
	.string "Det var der, jeg tilfældigvis stødte på\n"
	.string "{STR_VAR_1}, der forsøgte at fange\n"
	.string "POKéMON {STR_VAR_3}, men…$"

gTVPokemonTodayFailedText02::
	.string "POKéMONet formåede at undslippe!\p"
	.string "Det endte med at spilde dette\n"
	.string "ANTAL POKéBOLDE: {STR_VAR_2}!\p"
	.string "Du skulle have set udtrykket\n"
	.string "af frustration på {STR_VAR_1}s ansigt\l"
	.string "da POKéMONet løb væk!$"

gTVPokemonTodayFailedText03::
	.string "Men {STR_VAR_1} lavede en fejl og lod\n"
	.string "POKéMON falde i svime!\p"
	.string "Det endte med at spilde så mange\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "Du skulle have set udtrykket af\n"
	.string "forbløffet forfærdelse på {STR_VAR_1}s\n"
	.string "ansigt da POKéMON'en besvimede!$"

gTVPokemonTodayFailedText04::
	.string "STORE SØSTER: Hej du der!\n"
	.string "Det er ikke pænt!\p"
	.string "Man burde ikke grine af andres\n"
	.string "uheld!\p"
	.string "Åh, stakkels {STR_VAR_1}.\n"
	.string "Sikke en skam!\p"
	.string "STORE BROR: Det er sandt!\n"
	.string "Undskyld for at grine.$"

gTVPokemonTodayFailedText05::
	.string "STORE SØSTER: Bufufu…\p"
	.string "STORE BROR: Hej!\n"
	.string "Du grinede også!\p"
	.string "STORE SØSTER: Hva'?! \p"
	.string "Jeg grinede ikke!\n"
	.string "Ærligt, det gjorde jeg ikke!\p"
	.string "Åh, stakkels {STR_VAR_1}.\n"
	.string "Hvad en skam!\p"
	.string "STORE BROR: …$"

gTVPokemonTodayFailedText06::
	.string "STORE SØSTER: Nu er det nok fjoller!\n"
	.string "Lad os se på dagens POKéMON…\p"
	.string "Hvad?\n"
	.string "Vi har allerede løbet tør for tid?\p"
	.string "Åh!\n"
	.string "Vi kunne ikke profilere en POKéMON i dag!\p"
	.string "STORE BROR: Vi ses igen næste gang!\p"
	.string "STORE SØSTER: Hey, afslut ikke\n"
	.string "programmet uden mig!$"

gTVPokemonTodaySuccessfulText00::
	.string "Hej!\p"
	.string "Det er tid til POKéMON I DAG!\p"
	.string "STORE SØSTER: Hej! Er alle glade\n"
	.string "og friske i dag?\p"
	.string "I dag skal vi se på {STR_VAR_1}s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "STORE BROR: Ja! Det er hvad vi skal!\p$"

gTVPokemonTodaySuccessfulText01::
	.string "STORE SØSTER: {STR_VAR_1} gav kælenavnet\n"
	.string "{STR_VAR_3} til {STR_VAR_2}!\p"
	.string "Det lyder som om {STR_VAR_3} bliver\n"
	.string "godt passet og elsket!$"

gTVPokemonTodaySuccessfulText02::
	.string "STOREBROR: Træneren var nødt til at kaste\n"
	.string "så mange POKéBOLDE for at fange den: {STR_VAR_3}!\p"
	.string "Endelig tog det kun en enkelt {STR_VAR_2}\n"
	.string "at fange den!$"

gTVPokemonTodaySuccessfulText03::
	.string "STORE SIS: Hvis det var så let at fange,\n"
	.string "må det have været skæbnen, der bragte\n"
	.string "{STR_VAR_1} og {STR_VAR_2} sammen!$"

gTVPokemonTodaySuccessfulText04::
	.string "STORE SIS: Ej, hvor sejt!\p"
	.string "Men ved du hvad de siger, en POKéMON\n"
	.string "der kræver en stor indsats at fange,\l"
	.string "fortjener kærligheden fra sin TRÆNER!$"

gTVPokemonTodaySuccessfulText05::
	.string "STORE SØSTER: {STR_VAR_1}s {STR_VAR_2} er en\n"
	.string "mindeværdig POKéMON, fordi det krævede\n"
	.string "en uvurderlig MASTER BALL at fange!\p"
	.string "STORE BROR: Wow! Det er mega-fedt!\p"
	.string "STORE SØSTER: {STR_VAR_1} må virkelig have\n"
	.string "ønsket sig den {STR_VAR_2}, helt sikkert!$"

gTVPokemonTodaySuccessfulText06::
	.string "STOREBROR: Så at give kælenavnet\n"
	.string "{STR_VAR_3} til den {STR_VAR_2}…\p"
	.string "Du får virkelig en god idé om\n"
	.string "{STR_VAR_1}'s TRÆNER sans.\p"
	.string "STORESØSTER: Jeg er helt enig!$"

gTVPokemonTodaySuccessfulText07::
	.string "Hvis det var op til mig, ville jeg give\n"
	.string "det kælenavnet til noget som dette {STR_VAR_3}!\p"
	.string "STOREBROR: Wow! Det kunne være starten\n"
	.string "på noget nyt!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} den {STR_VAR_1}?\n"
	.string "Lyder det ikke perfekt?\p"
	.string "Bogstaverne og det hele--de\n"
	.string "lyder bare rigtige til POKéMON\l"
	.string "{STR_VAR_1}!\p"
	.string "STORE BRO: Ja, sandt nok!$"

gTVPokemonTodaySuccessfulText09::
	.string "Så vidt jeg ved, har ingen TRÆNER\n"
	.string "givet kælenavnet {STR_VAR_2} til deres\n"
	.string "{STR_VAR_1}!\p"
	.string "STOREBROR: Det viser bare, hvor\l"
	.string "god smag TRÆNEREN har i valg af\n"
	.string "kælenavne!$"

gTVPokemonTodaySuccessfulText10::
	.string "Næste gang jeg fanger en POKéMON,\n"
	.string "skal jeg kalde den {STR_VAR_2}.\p"
	.string "STOREBROR: Hvad? Mig også!\n"
	.string "Jeg vil også bruge kælenavnet {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "STORE SØSTER: Åh, nej!\n"
	.string "Se lige tiden!\p"
	.string "Nå, venner, det var alt for i dag.\n"
	.string "Vi ses igen næste gang!\p"
	.string "STORE BROR: Husk, det kunne være din\n"
	.string "POKéMON i rampelyset næste gang!$"

SmartShopper_Text_Intro::
	.string "Hej!\p"
	.string "Det er tid til DAGENS SMARTE INDKØBER.\p"
	.string "INTERVIEWER: Hvordan har I det, seere?\p"
	.string "I dag besøger vi en butik\n"
	.string "i {STR_VAR_2}.\p"
	.string "Lad os se, hvad de populære\n"
	.string "varer har været for nylig.$"

SmartShopper_Text_ClerkNormal::
    .string "Lad os interviewe ekspedienten for at\n"
    .string "få det hele at vide.\p"
    .string "Hej, hvordan går det med din forretning?\p"
    .string "EKSPEDIENT: Åh, vi klarer os fremragende.\p"
    .string "For nylig har {STR_VAR_2} været særligt\n"
    .string "populær.\p"
    .string "Ja, forleden købte en TRÆNER ved navn\n"
    .string "{STR_VAR_1} {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "INTERVIEWER: TRÆNEREN købte\n"
	.string "{STR_VAR_3} {STR_VAR_2}ER? Det er et scoop!\p" 
	.string "Hvis jeg må sige det, så må {STR_VAR_1}\n"
	.string "have fyldt op til en lang rejse\n" 
	.string "til fjerne egne.\p" 
	.string "Når man rejser, er {STR_VAR_2} vigtige!$"

SmartShopper_Text_RandomComment2::
	.string "INTERVIEWER: Når vi taler om emnet\n"
	.string "{STR_VAR_2}, købte jeg for nylig {STR_VAR_3}\l"
	.string "af dem.\p"
	.string "Efter alt, {STR_VAR_2} er en fantastisk vare!$"

SmartShopper_Text_RandomComment3::
	.string "INTERVIEWER: {STR_VAR_2} ?!\n"
	.string "Men {STR_VAR_3} af dem?! \p"
	.string "Jeg troede ikke, der ville være nogen,\n"
	.string "der købte så mange. \p"
	.string "Min gode gud, jeg har kun råd til en\n"
	.string "eller to ad gangen…$"

SmartShopper_Text_RandomComment4::
	.string "INTERVIEWER: En gang købte jeg\n"
	.string "en hel masse af emnet {STR_VAR_2}.\p"
	.string "Men det viste sig at være for mange.\n"
	.string "Jeg fortrød det... \p"
	.string "Siden da køber jeg kun nøjagtigt hvad\n"
	.string "jeg absolut har brug for... \p"
	.string "Ups!\p"
	.string "Der er ingen grund til at tale om mig!$"

SmartShopper_Text_SecondItem::
	.string "EKSPEDIENT: {STR_VAR_1} købte også varen\n"
	.string "{STR_VAR_2} i stort antal, og fik {STR_VAR_3}.\p"
	.string "INTERVIEWER: Åh, dét er smart.\n"
	.string "{STR_VAR_2} er også et meget godt valg.$"

SmartShopper_Text_ThirdItem::
	.string "EKSPEDIENT: Og TRÆNEREN købte også\n"
	.string "{STR_VAR_3} af varen {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "EKSPEDIENT: Og så var det under en stor udsalg.\n"
	.string "Det er smart at handle.$"

SmartShopper_Text_OutroNormal::
	.string "INTERVIEWER: Hmm… {STR_VAR_1} lyder som\n"
	.string "en ganske snedig tilbuds-jæger!\p"
	.string "I alt løb {STR_VAR_1}'s køb op i…\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "Det er da en fantastisk sum!\p"
	.string "Ups! Tiden er udløbet!\n"
	.string "Vi ses på vores næste udsendelse!$"

SmartShopper_Text_IsVIP::
	.string "EKSPEDIENT: {STR_VAR_1} er en VIP-kunde,\n"
	.string "ingen tvivl om det.$"

SmartShopper_Text_ClerkMax::
	.string "Lad os interviewe ekspedienten for at\n"
	.string "få det hele at vide.\p"
	.string "Hej, hvordan går det med din forretning?\p"
	.string "EKSPEDIENT: Åh, vi har en utrolig god\n"
	.string "omsætning. Det er næsten overvældende.\p"
	.string "For nylig købte en TRÆNER ved navn {STR_VAR_1}\n"
	.string "varen {STR_VAR_2} i stort antal.\p"
	.string "TRÆNEREN tømte næsten vores hele lager af {STR_VAR_2}.\p"
	.string "Jeg drømte aldrig om, at en kunde\n"
	.string "ville få brug for så mange {STR_VAR_2}.\l"
	.string "Det er bare uhørt!\p"
	.string "INTERVIEWER: Så det vil være omkring 100\n"
	.string "eller 200 solgte?\p"
	.string "EKSPEDIENT: Åh, langt mere end det!\p"
	.string "INTERVIEWER: Åh, du store tid!\n"
	.string "{STR_VAR_1} må være en særlig shopper!\p"
	.string "EKSPEDIENT: {STR_VAR_1} er en VIP-kunde,\n"
	.string "ingen tvivl om det.$"

SmartShopper_Text_OutroMax::
	.string "INTERVIEWER: Hmm…\n"
	.string "Det er fantastisk.\p"
	.string "Men hvorfor skulle TRÆNEREN have brug\n"
	.string "for så mange?\p"
	.string "… …\p"
	.string "Mysteriet tykner, men det er alt den\n"
	.string "tid, vi har i dag.\l"
	.string "Vi ses i vores næste udsendelse!\p"
	.string "{STR_VAR_1} er helt sikkert stadig en gåde…$"

gTVWorldOfMastersText00::
	.string "VERDENEN FOR MESTRE\p"
	.string "Hej, seere.\p"
	.string "Måske er du bekendt med en TRÆNER\n"
	.string "ved navn {STR_VAR_1}.\p"
	.string "{STR_VAR_1} er berømt som en mester i\n"
	.string "at fange POKéMON.\p"
	.string "{STR_VAR_1}s jagt på POKéMON afhænger\n"
	.string "fuldstændigt af en omhyggelig søgning\n"
	.string "til fods.\p"
	.string "På en mindeværdig dag gik TRÆNEREN\n"
	.string "{STR_VAR_2} skridt.\p"
	.string "Det samlede antal POKéMON fanget\n"
	.string "den dag nåede imponerende {STR_VAR_3}!$"


gTVWorldOfMastersText01::
	.string "Den fantastiske bedrift må have været\n"
	.string "mulig på grund af tilliden mellem\n"
	.string "TRÆNEREN og {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Mesteren fangede dagens sidste\n"
	.string "{STR_VAR_3} nær {STR_VAR_2}.\p"
	.string "Denne POKéMON nyder tilsyneladende\n"
	.string "en særlig status som en rekordindehaver.\p"
	.string "Dygtige TRÆNERE bør opfordres til\n"
	.string "at udfordre denne fine rekord.\p"
	.string "Det er alt for i dag.\n"
	.string "Venligst vend tilbage næste gang.$"

gTVTodaysRivalTrainerText00::
	.string "DAGENS RIVALTRÆNER!\p"
	.string "Hej, medtrænere af POKéMON!\n"
	.string "Hvordan har vi det alle sammen i dag?\p"
	.string "I dag, ligesom enhver anden dag,\n"
	.string "vil vi undersøge en af vores rivaler!$"

gTVTodaysRivalTrainerText07::
	.string "Dagens rivalTRÆNER er {STR_VAR_1},\n"
	.string "som er omkring {STR_VAR_3} lige nu.\p"
	.string "{STR_VAR_1} har indtil videre\n"
	.string "registreret {STR_VAR_2} POKéMON i POKéDEXen.$"

gTVTodaysRivalTrainerText08::
    .string "Dagens rivalTRÆNER er {STR_VAR_1},\n"
    .string "som er i en HEMMELIG BASE nu.\p"
    .string "{STR_VAR_1} har indtil videre registreret\n"
    .string "{STR_VAR_2} POKéMON i POKéDEXEN.$"

gTVTodaysRivalTrainerText09::
	.string "Dagens rival TRÆNER er {STR_VAR_1}.\p"
	.string "Indtil nu har {STR_VAR_1}\n"
	.string "registreret {STR_VAR_2} POKéMON i\n"
	.string "POKéDEXEN.$"

gTVTodaysRivalTrainerText10::
	.string "Dagens rival TRÆNER er {STR_VAR_1},\n"
	.string "som er på en færge nu.\p"
	.string "{STR_VAR_1} har indtil videre registreret\n"
	.string "{STR_VAR_2} POKéMON i POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Og hvor mange MÆRKER har vores rival\n"
	.string "nu? Tallet er {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Men vores rival har ikke fået\n"
	.string "en enkelt MÆRKE endnu!$"

gTVTodaysRivalTrainerText03::
	.string "Vores rival har endnu ikke fået en\n"
	.string "KAMPFRONTIER-symbol endnu.$"

gTVTodaysRivalTrainerText04::
	.string "Lad os se, hvor mange BATTLE FRONTIER-\n"
	.string "Symboler vores rival har.\p"
	.string "Guld Symboler: {STR_VAR_1}!\n"
	.string "Sølv Symboler: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Vores rival har samlet {STR_VAR_1}\n"
	.string "Kamp Point(s) ved BATTLE FRONTIER.$"

gTVTodaysRivalTrainerText06::
	.string "Så, hvordan målte du dig\n"
	.string "sammen med {STR_VAR_1}?\p"
	.string "Eventyret fortsætter!\p"
	.string "Kære TRÆNERE!\p"
	.string "Lad os alle blive ved med at\n"
	.string "bevæge os fremad og\n"
	.string "foran vores rivaler!$"

TrendWatcher_Text_Intro::
	.string "DEWFORD TRENDSÆTTER NETVÆRK!\p"
	.string "MC: Hvad så?\n"
	.string "Vi holder det ægte med de seneste\n"
	.string "trends og begivenheder i DEWFORD.\p"
	.string "Vores gæst i dag er denne gamle kat,\n"
	.string "der har gjort sig kendt som\n"
	.string "autoriteten inden for alt i DEWFORD.\p"
	.string "Gammel mand: Dejligt at være her.\p"
	.string "MC: Lad os komme til sagen,\n"
	.string "direkte på. Hvad siger du til,\n"
	.string "at der er gang i den hos de gode\n"
	.string "mennesker i DEWFORD?\p"
	.string "Gammel mand: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "MC: {STR_VAR_1} {STR_VAR_2},\n"
	.string "siger du?\p"
	.string "Gammel mand: Nej.\p"
	.string "{STR_VAR_1} {STR_VAR_2} blev\n"
	.string "aldrig populært overhovedet.\p"
	.string "Vil du høre om det?\p"
	.string "MC: Øh, nej. Det vi gerne vil vide er,\n"
	.string "hvad der er 'in' i øjeblikket...$"

TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Gamle mand: {STR_VAR_1} {STR_VAR_2}\n"
	.string "var det, som {STR_VAR_3} fra LITTLEROOT\n"
	.string "lærte mig at være trendy…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Old man: {STR_VAR_1} {STR_VAR_2}\n"
	.string "er hvad {STR_VAR_3} fra LITTLEROOT\n"
	.string "har lært mig, der er trendy…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Men det var fuldstændig håbløst.\p"
	.string "{STR_VAR_1} {STR_VAR_2} festival!\p"
	.string "{STR_VAR_1} {STR_VAR_2} konkurrence!\p"
	.string "Jeg prøvede at lære alle det bedste\n"
	.string "jeg kunne, men…\p"
	.string "Måske var {STR_VAR_1} delen bare\n"
	.string "ikke rigtig…\p"
	.string "MC: Øh, undskyld, kammerat, jeg skal\n"
	.string "vide, hvad der er 'ind' lige nu...$"

TrendWatcher_Text_MaleTellMeBigger::
	.string "Gammel mand: {STR_VAR_3}!\n"
	.string "Vær sød at fortælle mig noget større\l"
	.string "end det {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Gammel mand: {STR_VAR_3}!\n"
	.string "Fortæl mig venligst noget større end\l"
	.string "det {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: ...Øh... Så er den der,\n"
	.string "alle I trendy, tjekkede katte derude!\p"
	.string "{STR_VAR_1} {STR_VAR_2}...øh...\n"
	.string "Ikke blev hip eller skete i DEWFORD!\p"
	.string "Min tid er op. Fanger dig på flugt!\p"
	.string "Gammel mand: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
    .string "HOENN SKATTEUNDERSØGERE!\p"
    .string "Hej, venner!\n"
    .string "Har I scoret nogle hemmelige genstande for nylig?\p"
    .string "Som altid vil vi undersøge øjenvidneberetninger\n"
    .string "om hemmeligheder fra hele regionen!\p"
    .string "Lad os begynde med et brev.\n"
    .string "Det siger, “{STR_VAR_1} opdaget!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Wow, vi bør lige se denne besked\n"
	.string "nærmere! Lad mig læse den op.\p"
	.string "…Kære EFTERFORSKERE,\n"
	.string "Jeg håber, I har det godt.\p"
	.string "Jeg så for nylig {STR_VAR_2} et sted\n"
	.string "omkring {STR_VAR_3}.\p"
	.string "TRÆNEREN fandt genstanden\n"
	.string "{STR_VAR_1}. Det gjorde mig misundelig.\p"
	.string "…Nå, godt gået, {STR_VAR_2}!\p"
	.string "Seere, lad det motivere jer til at\n"
	.string "starte jeres SØGESTAVE og lede!\p"
	.string "Jeg venter spændt på spændende\n"
	.string "nyheder fra jer alle!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Wow, vi bør nok tjekke dette brev\n"
	.string "ud! Lad mig læse det højt til dig.\p"
	.string "…Kære EFTERFORSKERE,\n"
	.string "Jeg håber, at I har det godt.\p"
	.string "Jeg så for nylig {STR_VAR_2} på en færge.\p"
	.string "TRÆNEREN fandt genstanden\n"
	.string "{STR_VAR_1}. Det gjorde mig misundelig.\p"
	.string "…Godt klaret, {STR_VAR_2}!\p"
	.string "Seere, lad det motivere jer til at\n"
	.string "tænde jeres TINGFINDERE og lede!\p"
	.string "Jeg venter spændt på spændende\n"
	.string "nyheder fra jer alle!$"

gTVFindThatGamerText00::
	.string "FIND THAT GAMER!\p"
	.string "Hej allesammen gamere!\n"
	.string "Hvordan spinner din {STR_VAR_2}? \p"
	.string "Som altid vil vi rette vores opmærksomhed\n"
	.string "mod en sjælden TRÆNER\nsom har besøgt\n"
	.string "SPILLEHJØRNET!\p"
	.string "I dag er vores nr. 1 gamer…\n"
	.string "{STR_VAR_1}!$" 

gTVFindThatGamerText01::
	.string "{STR_VAR_1} spillede {STR_VAR_2}-spillet\n"
	.string "og vandt sjældne {STR_VAR_3} MØNTER.\p"
	.string "”Når {STR_VAR_1} kommer, skal vi\n"
	.string "sørge for, at vi har nok MØNTER.”\p"
	.string "Det er det, GAME CORNER kassererne\n"
	.string "mumler, når vores gamer spiller!\p"
	.string "Seere, det er bedst at holde øje med\n"
	.string "dine MØNTER som {STR_VAR_1}, hvis du\n"
	.string "besøger GAME CORNER og spiller\n"
	.string "{STR_VAR_2}-spillet.\p"
	.string "Dette er live fra GAME CORNER-\n"
	.string "hvor du kan mærke spændingen!\p"
	.string "Det var alt for i dag!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} spillede det {STR_VAR_2}\n"
	.string "spil og tabte {STR_VAR_3} MØNTER.\p"
	.string "“Når {STR_VAR_1} kommer, ser det ud\n"
	.string "til, at vores MØNT-salg stiger.”\p"
	.string "Det siger spilhjørnets ekspedienter,\n"
	.string "når vores gamer spiller!$"

gTVFindThatGamerText03::
	.string "Seerne, det er bedst at holde øje med dine\n"
	.string "MØNTER som {STR_VAR_1}, hvis du besøger\n"
	.string "SPILLEHJØRNET og spiller {STR_VAR_2}-spillet.\p"
	.string "Dette er live fra SPILLEHJØRNET--\n"
	.string "hvor du kan føle spændingen!\p"
	.string "Det var alt for i dag!$"

gTVBreakingNewsText00::
	.string "VIGTIGT NYHEDER TV!$"

gTVBreakingNewsText01::
	.string "Sjælden {STR_VAR_2} fanget af\n"
	.string "{STR_VAR_1}!\p"
	.string "Vi er live fra området omkring\n"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1} fangede med succes en\n"
	.string "sjælden {STR_VAR_2} tidligere her!$"

gTVBreakingNewsText02::
	.string "Da {STR_VAR_1} stødte på den sjældne\n"
	.string "{STR_VAR_2}, sendte TRÆNEREN\n"
	.string "POKéMON {STR_VAR_3} ud.$"

gTVBreakingNewsText03::
	.string "I kampen blev antallet af POKé\n"
	.string "BOLD kastet af TRÆNEREN {STR_VAR_1}.\p"
	.string "Til sidst blev den sjældne POKéMON\n"
	.string "fanget af {STR_VAR_2} brugt sidst.$"

gTVBreakingNewsText04::
	.string "I det øjeblik fyldtes {STR_VAR_2}\n"
	.string "med {STR_VAR_1}'s brøl af\l"
	.string "triumferende glæde.\p"
	.string "Jeg må indrømme, at jeg er lidt\n"
	.string "misundelig på {STR_VAR_1}. Jeg ville\p"
	.string "også elske at brøle.\p"
	.string "…Det afslutter liveoptagelsen fra\n"
	.string "den glade scene!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} mislykkes med at fange en sjælden\n"
	.string "{STR_VAR_2}!\p"
	.string "Vi er live fra nærheden af\n"
	.string "{STR_VAR_3}!\p"
	.string "Det var her, at {STR_VAR_1} mislykkedes\n"
	.string "med at fange en sjælden {STR_VAR_2}!$"

gTVBreakingNewsText06::
	.string "Da {STR_VAR_1} stødte på den sjældne\n"
	.string "{STR_VAR_2}, sendte TRÆNEREN\n"
	.string "POKéMON {STR_VAR_3} ud.$"

gTVBreakingNewsText07::
	.string "TRÆNEREN fik {STR_VAR_2}\n"
	.string "til at bruge trækket {STR_VAR_1}.\p"
	.string "Uden at ville det, fik TRÆNEREN\n"
	.string "den sjældne POKéMON til at besvime…$"

gTVBreakingNewsText12::
	.string "Dog, fik {STR_VAR_1} panik \n"
	.string "ved synet af den sjældne {STR_VAR_2}.\p"
	.string "Forvirret beordrede TRÆNEREN\n"
	.string "{STR_VAR_3} til angreb.\p"
	.string "Uden at ville det, lod TRÆNEREN\n"
	.string "den sjældne POKéMON blive svag.$"

gTVBreakingNewsText08::
	.string "I samme øjeblik genlød {STR_VAR_2}\n"
	.string "med {STR_VAR_1}s skrig af\l"
	.string "frustration...$"

gTVBreakingNewsText09::
	.string "Dog løb {STR_VAR_1}\n"
	.string "tør for POKé BOLDE.\p"
	.string "TRÆNEREN måtte afbryde\l"
	.string "kampen med den sjældne {STR_VAR_2}.\p"
	.string "I samme øjeblik fyldtes\l"
	.string "{STR_VAR_3} af {STR_VAR_1}'s\l"
	.string "skrig af frustration…$"

gTVBreakingNewsText10::
	.string "Dog flygtede {STR_VAR_2} uden\n"
	.string "advarsel.\p"
	.string "I samme øjeblik fyldtes\n"
	.string "{STR_VAR_3} af {STR_VAR_1}s skrig af\l"
	.string "frustration…$"

gTVBreakingNewsText11::
	.string "Jeg må sige, jeg føler med {STR_VAR_1}.\n"
	.string "Hvorfor, det får også mig til at \nskrige.\p"
	.string "...Det afslutter den live feed fra \ndet melankolske scene!$"

gTVSecretBaseVisitText00::
	.string "Hej, venner!\n"
	.string "Det er tid til\l"
	.string "et BESØG I DEN HEMMELIGE BASE.\p"
	.string "I dag besøger vi DEN HEMMELIGE BASE\n"
	.string "til {STR_VAR_1}.\p"
	.string "Hvordan har {STR_VAR_1} tilpasset\n"
	.string "DEN HEMMELIGE BASE?\p"
	.string "Det finder vi ud af!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Åh!\n"
	.string "Hvor vidunderligt!\p"
	.string "Denne {STR_VAR_2}...\n"
	.string "Det er ikke hvad man ville forvente at\l"
	.string "finde her!$"

gTVSecretBaseVisitText02::
	.string "Åh!\n"
	.string "Hvor bemærkelsesværdigt!\p"
	.string "Der er ikke et eneste stykke\n"
	.string "møbel eller interiør!\p"
	.string "Almindelige dødelige kunne\n"
	.string "ikke drømme om at efterligne\n"
	.string "denne dristige erklæring!\p"
	.string "Det er enkelt, men det\n"
	.string "svulmer, ja, svulmer af\n"
	.string "vildskab!\p"
	.string "Mit hat af for dig, {STR_VAR_1}.\n"
	.string "Det måtte være dig!$"

gTVSecretBaseVisitText03::
	.string "Åh! Jeg ser!\n"
	.string "Med fuldkommen klarhed ser jeg det!\p"
	.string "Det {STR_VAR_2} er her…\n"
	.string "Det sender en effektiv besked!$"

gTVSecretBaseVisitText04:: 
	.string "Åh! Jeg ser!\n"
	.string "Med fuldstændig klarhed ser jeg det!\p"
	.string "Dette rum er bevidst holdt tomt\n"
	.string "for indvendige genstande!\p"
	.string "Det sender en effektiv besked!$"

gTVSecretBaseVisitText05::
	.string "Wheeew!\p"
	.string "The pairing of the {STR_VAR_2}\n"
	.string "with the {STR_VAR_3}!\p"
	.string "It's a dream combination if there\n"
	.string "ever was one!$"

gTVSecretBaseVisitText06::
	.string "Huuuj!\p"
	.string "Placeringen af dette {STR_VAR_2}\n"
	.string "lige her…\p"
	.string "Det har en tilstedeværelse,\n"
	.string "som fylder hele DEN HEMMELIGE BASE!$"

gTVSecretBaseVisitText07::
	.string "Iiiihaa!\p"
	.string "Der er ikke noget her.\p"
	.string "Dette tomme rum har en effekt på\n"
	.string "hele DEN HEMMELIGE BASE.$"

gTVSecretBaseVisitText08::
	.string "Åh!\n"
	.string "Her kommer {STR_VAR_1}!\l"
	.string "Lad os udfordre TRÆNEREN!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Åh…\n"
	.string "Jeg må virkelig give {STR_VAR_1} en\n"
	.string "klap på skulderen.\p"
	.string "TRÆNERENS POKéMON var virkelig\n"
	.string "værdige til at bære CHAMPION-\n"
	.string "titlen.\p"
	.string "De gav rigelig bevis på {STR_VAR_1}s\n"
	.string "styrke som TRÆNER.\p"
	.string "At {STR_VAR_2} vidste angrebet\n"
	.string "{STR_VAR_3}…\p"
	.string "Det viser hvilken slags TRÆNER\n"
	.string "{STR_VAR_1} er.\p"
	.string "Det var helt sikkert en god\n"
	.string "lektion!$"

gTVSecretBaseVisitText10::
	.string "Åhøj!\n"
	.string "Skal vi ikke lige give {STR_VAR_1}\n"
	.string "en high five?\p"
	.string "TRÆNERENS POKéMON var\n"
	.string "monster svære!\p"
	.string "De beviste virkelig {STR_VAR_1}s\n"
	.string "udholdenhed som TRÆNER.\p"
	.string "At {STR_VAR_2} kendte angrebet\n"
	.string "{STR_VAR_3}…\p"
	.string "Det viser, hvilken slags TRÆNER\n"
	.string "{STR_VAR_1} er.\p"
	.string "Det var virkelig en lektion i sig selv!$"

gTVSecretBaseVisitText11::
	.string "Wiiii!\n"
	.string "Jeg må give {STR_VAR_1} en high five.\p"
	.string "TRÆNERENS POKÉMON blev tydeligvis\n"
	.string "opdrættet på en balanceret måde.\p"
	.string "De vidnede tydeligt om {STR_VAR_1}s\n"
	.string "omsorg som TRÆNER.\p"
	.string "At {STR_VAR_2} kendte angrebet\n"
	.string "{STR_VAR_3}…\p"
	.string "Det siger noget om, hvilken slags\n"
	.string "TRÆNER {STR_VAR_1} er.\p"
	.string "Det var helt sikkert en vigtig\n"
	.string "lektion!$"

gTVSecretBaseVisitText12::
	.string "Nå, nå!\n"
	.string "Jeg må give det til {STR_VAR_1}.\p"
	.string "TRÆNERENS POKéMON viste stor\n"
	.string "lokkende for fremtidig vækst.\p"
	.string "De repræsenterede {STR_VAR_1}s\n"
	.string "håb og drømme.\p"
	.string "At {STR_VAR_2} kendte angrebet\n"
	.string "{STR_VAR_3}…\p"
	.string "Viser, hvilken slags TRÆNER\n"
	.string "{STR_VAR_1} er.\p"
	.string "Det var helt sikkert en lektion!$"

gTVSecretBaseVisitText13::
	.string "Jeg må sige, for en fantastisk HEMMELIG BASE\n"
	.string "det var!\p"
	.string "Seere, hvis I får chancen,\n"
	.string "besøg endelig {STR_VAR_1}s HEMMELIGE BASE.\p"
	.string "Indtil næste gang, siger jeg farvel!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Det er spændende!\n"
	.string "Det er dramatisk!\p"
	.string "Det er POKéMON LOTTERIET\n"
	.string "VINDER FLASH RAPPORT!\p"
	.string "Hej! Vi kommer til dig live fra\n"
	.string "POKéMON LOTTERIET på\l"
	.string "stueetagen i LILYCOVE\l"
	.string "DEPARTMENT STORE!\p"
	.string "Som det altid sker, kom en anden\n"
	.string "heldig TRÆNER frem i dag!\p"
	.string "Den TRÆNERS navn er...\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} vandt {STR_VAR_2} præmien\n"
	.string "og tog {STR_VAR_3} med hjem!\p"
	.string "{STR_VAR_1}!\n"
	.string "Tillykke!\p"
	.string "Seere, bare se ikke med,\n"
	.string "vær en del af handlingen!\p"
	.string "Vi hos LILYCOVE DEPARTMENT\n"
	.string "STORE glæder os til dit næste besøg!\p"
	.string "Dette har været en live transmission fra\n"
	.string "LILYCOVE DEPARTMENT STORE,\l"
	.string "der tilbyder dig det bedste udvalg\l"
	.string "i hele HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "POKéMONKAMPSEMINAR!\p"
	.string "Vi undersøger kampe for at se,\n"
	.string "hvad vi kan lære af andre.\p"
	.string "Dagens case-studie er på {STR_VAR_1}s\n"
	.string "kamp.\p"
	.string "{STR_VAR_1}s {STR_VAR_2} kæmpede\n"
	.string "mod én {STR_VAR_3}...$"

gTVThePokemonBattleSeminarText01::
	.string "Og den brugte angrebet {STR_VAR_3}\n"
	.string "på {STR_VAR_2}...\p"
	.string "Hmm... {STR_VAR_1}!\n"
	.string "Det er det forkerte at gøre!$"

gTVThePokemonBattleSeminarText02::
	.string "Udover det dømte træk,\n"
	.string "kendte TRÆNERENS {STR_VAR_1} også$"

gTVThePokemonBattleSeminarText03::
	.string "bevægelserne {STR_VAR_1}, {STR_VAR_2},\n"
	.string "og {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "bevægelserne {STR_VAR_1} og\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "trækket {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Så, i denne situation, hvad burde\n"
	.string "TRÆNEREN have brugt?\p"
	.string "… … … … … …\n"
	.string "Atakken {STR_VAR_1}!\p"
	.string "Atakken {STR_VAR_1} ville have været\n"
	.string "absolut bedre end {STR_VAR_2}.\p"
	.string "Seere, jeg opfordrer jer til at lære\n"
	.string "af dette tilfælde og kæmpe med\n"
	.string "intelligens!\p"
	.string "Indtil næste gang, farvel!$"

gTVTrainerFanClubText00::
	.string "Alle sammen nu!\n"
	.string "TRÆNER FAN KLUB!\p"
	.string "MC: Hvordan går det alle sammen?\n"
	.string "I dag har vi samlet fansene af\n"
	.string "den hyper-populære TRÆNER {STR_VAR_1}!\p"
	.string "FANS: Wrooooooaaaaah!\p"
	.string "FANS: {STR_VAR_1}!\p"
	.string "MC: Alle sammen!\n"
	.string "Hvad synes I om {STR_VAR_1}?!$\n"

gTVTrainerFanClubText01::
	.string "FANS: Deres seje måde at kaste\n"
	.string "POKé BOLDE!$"

gTVTrainerFanClubText02::
	.string "FANS: Deres søde måde at løbe på!$"  

gTVTrainerFanClubText03::
	.string "FANS: Hvordan TRÆNEREN bliver sej, \n"
	.string "når det bliver svært!$"

gTVTrainerFanClubText04::
    .string "FANS: Trænerens viden om\n"
    .string "POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: TRÆNERENS venlighed overfor\n"
	.string "alle POKéMON!\n$"

gTVTrainerFanClubText06::
	.string "FANS: TRÆNERENS fantastiske\n"
	.string "cykelkørselsteknikker!$"

gTVTrainerFanClubText07::
	.string "FANS: TRÆNERENS imponerende\n"
	.string "stil med at købe ting!$"

gTVTrainerFanClubText08::
	.string "FANS: TRÆNERENS charmerende\n"
	.string "måde at give POKéMON kælenavne!$"  

gTVTrainerFanClubText09::
	.string "FANS: TRÆNERENS smarte måde at\n"
	.string "dekorerer en HEMMELIG BASE!\p$"

gTVTrainerFanClubText10::
	.string "FANS: TRÆNERENS modige måder at\n"
	.string "bruge TMs!$"

gTVTrainerFanClubText11::
	.string "MC: Som du lige har set, er {STR_VAR_1}\n"
	.string "en hottie! Så hot, at man ikke kan\n"
	.string "røre ved det, wow!\p"
	.string "Blandt {STR_VAR_1}s FANS\n"
	.string "er der en speciel slogan!\p"
	.string "MC: Når jeg siger {STR_VAR_1},\n"
	.string "siger I…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Præcis, når nogen siger,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Svar tilbage med, “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Det har en helt unik klang!\n"
	.string "Jeg kan godt forstå, hvorfor folk bliver\n"
	.string "FANS af {STR_VAR_1}!\p"
	.string "Okay, dig foran fjernsynet, kom med!\n"
	.string "Alle sammen nu!\p"
	.string "MC: Når jeg siger {STR_VAR_1},\n"
	.string "siger I…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Tak fordi I var med, alle I\n"
	.string "vilde FANS af {STR_VAR_1}!\l"
	.string "Det var showet! Vi ses!\p"
	.string "MC: Når jeg siger {STR_VAR_1},\n"
	.string "siger I…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "FIND DE SMÅ VENNER!\n"
	.string "POKéMON MED SLØJFER!\p"
	.string "Hej, mine søde seere!\p"
	.string "Jeg er sikker på, I er enige, men en POKéMON\n"
	.string "med SLØJFER er simpelthen guddommelig!\p"
	.string "I dag vil jeg dele med jer\n"
	.string "en dejlig POKéMON, jeg så, da jeg var ude\n"
	.string "at gå tur i byen.\p"
	.string "Dagens smukke POKéMON\n"
	.string "er {STR_VAR_1}s {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Antallet af BÅND, som\n"
	.string "{STR_VAR_2} har på, er {STR_VAR_3}.\p"
	.string "Det siger meget om, hvor meget\n"
	.string "{STR_VAR_1} beundrer POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} bærer nogle fantastiske\n"
	.string "{STR_VAR_3} RIBBONER!\p"
	.string "Det siger en hel del om {STR_VAR_1}s\n"
	.string "dedikation til POKéMON!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} bærer utrolige\n"
	.string "{STR_VAR_3} BÅND!\p"
	.string "Det viser dig {STR_VAR_1}s totale\n"
	.string "dedikation som en samler!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Lad os tage et nærmere kig på de mange\n"
	.string "SLØJFER, som {STR_VAR_2} bærer.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "MESTERBÅNDEN er særligt\n"
	.string "charmerende.\p"
	.string "{STR_VAR_2} modtog det, da han trådte\n"
	.string "ind i BERØMMELSENS HAL.\p"
	.string "Det fremkalder virkelig modet hos\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} og MESTERBÅNDEN!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Den FEDTE RIBBON er særlig\n"
	.string "sej.\p"
	.string "{STR_VAR_2} fik den for at vinde\n"
	.string "en FED KONKURRENCE.\p"
	.string "Den fremhæver virkelig {STR_VAR_2}s\n"
	.string "sejhed.\p"
	.string "{STR_VAR_2} og FEDTE RIBBON!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "SKØNHEDSBÅNDET er særligt\n"
	.string "tiltrækkende.\p"
	.string "{STR_VAR_2} modtog det for at vinde\n"
	.string "en SKØNHEDSKONKURRENCE.\p"
	.string "Det fremhæver virkelig skønheden\n"
	.string "hos {STR_VAR_2}.\p"
	.string "{STR_VAR_2} og SKØNHEDSBÅNDET!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "DET SØDE BÅND er især\n"
	.string "charmerende.\p"
	.string "{STR_VAR_2} fik det for at vinde\n"
	.string "en SØD KONKURRENCE.\p"
	.string "Det fremhæver virkelig sødheden\n"
	.string "hos {STR_VAR_2}.\p"
	.string "{STR_VAR_2} og DET SØDE BÅND!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Den SMART RIBBON er specielt\n"
	.string "lækker.\p"
	.string "{STR_VAR_2} modtog den for at vinde\n"
	.string "en SMART KONKURRENCE.\p"
	.string "Den fremhæver virkelig {STR_VAR_2}s\n"
	.string "klogskab.\p"
	.string "{STR_VAR_2} og den SMART RIBBON!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Den SEJE BÅND er især\n"
	.string "forrygende.\p"
	.string "{STR_VAR_2} fik det for at vinde\n"
	.string "en SEJ KONKURRENCE.\p"
	.string "Det fremhæver virkelig sejhed\n"
	.string "hos {STR_VAR_2}.\p"
	.string "{STR_VAR_2} og det SEJE BÅND!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Den VINDENDE SLØJFE er særligt\n"
	.string "charmerende.\p"
	.string "{STR_VAR_2} modtog den for sine\n"
	.string "bedrifter i KAMPENS TÅRN.\p"
	.string "Den fremhæver sandelig styrken\n"
	.string "hos {STR_VAR_2}.\p"
	.string "{STR_VAR_2} og den VINDENDE SLØJFE!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "SEJRSMASKEN er særligt fornem.\n"
	.string "Fletter du ikke de rigtige bånd?\p"
	.string "{STR_VAR_2} modtog den for sine\n"
	.string "bedrifter i KAMPENS TÅRN.\p"
	.string "Den fremhæver virkelig styrken hos\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} og SEJRSMASKEN!\n"
	.string "Den kombination er super effektiv!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Kunstnerbåndet er virkelig super\n"
	.string "flot.\p"
	.string "{STR_VAR_2} fik det, fordi han\n"
	.string "var model for en kunstner.\p"
	.string "Det fremhæver virkelig popstjernens\n"
	.string "charme hos {STR_VAR_2}.\p"
	.string "{STR_VAR_2} og Kunstnerbåndet!\n"
	.string "Den kombination er super effektiv!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Den Hårde Arbejder RIBBON er\n"
	.string "helt speciel smuk.\p"
	.string "{STR_VAR_2} modtog den for at være\n"
	.string "en særligt dedikeret arbejder.\p"
	.string "Den fremhæver virkelig {STR_VAR_2}s\n"
	.string "determinationskraft.\p"
	.string "{STR_VAR_2} og Den Hårde Arbejder\n"
	.string "RIBBON! Kombinationen er super\n"
	.string "effektiv!$"

TVSpotTheCuties_Text_Outro::
	.string "…Suk…\p"
	.string "SLØJFER og POKéMON…\n"
	.string "De passer så skønt sammen!\p"
	.string "Inden jeg svimler,\n"
	.string "siger jeg farvel til jer!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Hej!\n"
	.string "Det er tid til POKéMON-NYHEDER.\p"
	.string "Vi har nogle opmuntrende nyheder fra\n"
	.string "BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-sejr-stime rekord mens\l"
	.string "han var på KAMP TÅRNETS SINGLE\l"
	.string "KAMP RUM udfordring.\p"
	.string "Hip hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "Den TRÆNER {STR_VAR_1} satte en\n"
	.string "{STR_VAR_2}-sejr-stime rekord, mens han\n"
	.string "var på BATTLE TOWER's DOUBLE\l"
	.string "BATTLE ROOM udfordring.\p"
	.string "Sådan, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-vind-stime rekord mens\l"
	.string "han var på BATTLE TOWER's MULTI\l"
	.string "BATTLE ROOM udfordring.\p"
	.string "Skål for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "TRÆNEREN {STR_VAR_1} har sat en ny\n"
	.string "{STR_VAR_2}-vind-stime rekord mens\l"
	.string "han var på BATTLE TOWER's LINK\l"
	.string "MULTI BATTLE ROOM-udfordringen.\p"
	.string "Tillykke til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "Træneren {STR_VAR_1} har sat en ny\n"
	.string "{STR_VAR_2}-mesterskabsrekord\n"
	.string "i SINGLE BATTLE-turneringer i BATTLE\n"
	.string "DOME.\p"
	.string "Hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "Den TRÆNER {STR_VAR_1} satte en\n"
	.string "{STR_VAR_2}-mesterskabsrekord\l"
	.string "og konkurrerede i BATTLE DOME's\l"
	.string "DOUBLE BATTLE-turneringer.\p"
	.string "Hip hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "Den TRÆNER {STR_VAR_1} satte en\n"
	.string "{STR_VAR_2}-sejr-stime rekord mens\l"
	.string "han var på KAMPFABRIKENS Kamp\l"
	.string "Byt Enkelt udfordring.\p"
	.string "Sådan, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-vind-stime rekord\n"
	.string "mens de var på KAMPFABRIK-\l"
	.string "LENs Battle Swap Double udfordring.\p"
	.string "Her er til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "rekord ved at rydde {STR_VAR_2}\n"
	.string "lokaler under BATTLE PIKE's Battle\n"
	.string "Choice udfordring.\p"
	.string "Hip hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "Træneren {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-vinstime-rekord mens han\l"
	.string "kæmpede i KAMPARENAENS\l"
	.string "Set KO Turnering.\p"
	.string "Hip hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-sejr-stime mens ved\l"
	.string "BATTLE PALACE's ENESTE KAMP\l"
	.string "SAL udfordring.\p"
	.string "Her er til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "Den TRÆNER {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-vinstime-rekord mens han\l"
	.string "var på BATTLE PALACE's DOUBLE\l"
	.string "BATTLE HALL udfordring.\p"
	.string "Tillykke til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "rekord ved at rydde {STR_VAR_2} etager\n"
	.string "mens de var på BATTLE PYRAMIDENS\l"
	.string "Battle Quest-udfordring.\p"
	.string "Her er til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Og til de tre POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, og {STR_VAR_3}!\p"
	.string "Tillykke med jeres\n"
	.string "rekordbrydende præstation!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Og til de to POKéMON, {STR_VAR_1}\n"
	.string "og {STR_VAR_2}!\p"
	.string "Tillykke med jeres\n"
	.string "rekordbrydende præstation!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Og til de fire POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Og {STR_VAR_1}!\p"
	.string "Tillykke med din\n"
	.string "rekordbrydende præstation!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Lad os håbe på flere rekordsættende\n"
	.string "bedrifter fra {STR_VAR_1} og de loyale\l"
	.string "POKéMON!\p"
	.string "Det var nyhederne fra POKéMON NEWS!$"

gTVWhatsNo1InHoennTodayText00::
	.string "HVAD ER NR. 1 I HOENN I DAG?\n"
	.string "Ja, det er den tid igen!\p"
	.string "Hej, seere! Giver I jeres bedste\n"
	.string "i alt, hvad I laver?\p"
	.string "Lad os se på TRÆNEREN, der gjorde\n"
	.string "det allerbedst i dag!\p"
	.string "Dagens nr. 1 TRÆNER er ingen anden\n"
	.string "end {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "På én dag drejede {STR_VAR_1} SLOTS\n"
	.string "på SPILLEHALLEN {STR_VAR_2} gange.\p"
	.string "Mens hun spillede, kunne man høre\n"
	.string "{STR_VAR_1} mumle, “For mig bevæger\l"
	.string "hjulene sig ikke engang…”\l"
	.string "Er det ikke interessant?$"

gTVWhatsNo1InHoennTodayText02::
	.string "På én dag spillede {STR_VAR_1}.\n"
	.string "ROULETTE-spillet i spilleHJØRNET\n"
	.string "{STR_VAR_2} gange.\p"
	.string "Mens {STR_VAR_1} spillede, råbte\n"
	.string "vedkommende, ”Lad boldene bestemme!”\p"
	.string "TRÆNERENs øjne var fokuserede\n"
	.string "og ansigtet udviste koncentration.$"

gTVWhatsNo1InHoennTodayText03::
	.string "I løbet af én dag kæmpede {STR_VAR_1}\n"
	.string "mod vilde POKéMON {STR_VAR_2} gange!\p"
	.string "{STR_VAR_1}'s POKéMON ser ud til\n"
	.string "at være blevet utroligt stærkere.\p"
	.string "De ser ud til at være ivrige efter\n"
	.string "at kæmpe overalt, hele tiden og på\n"
	.string "alle måder!$"

gTVWhatsNo1InHoennTodayText04::
	.string "På bare én dag snurrede {STR_VAR_1}\n"
	.string "BÆRBLANDEREN {STR_VAR_2} gange!\p"
	.string "Mod slutningen virkede selv {STR_VAR_1}\n"
	.string "som om han blev svimmel.\p"
	.string "TRÆNEREN så ud til at vakle\n"
	.string "rundt som en SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "På bare een dag plantede {STR_VAR_1}\n"
	.string "{STR_VAR_2} BÆR!\p"
	.string "Som følge heraf blev {STR_VAR_1}s\ntøj beskidt med snavs.\p"
	.string "Hvor TRÆNEREN plantede, er der\nspiret utallige blomster frem.\p"
	.string "Blomsterne siges at berolige\nfolks følelser.$"

gTVWhatsNo1InHoennTodayText06::
    .string "På bare én dag plukkede {STR_VAR_1}\n"
    .string "{STR_VAR_2} BÆR!\p"
    .string "{STR_VAR_1}s TASKE blev så fyldt\n"
    .string "med BÆR, at TRÆNEREN havde svært\n"
    .string "ved at gå bagefter!$"

gTVWhatsNo1InHoennTodayText07::
	.string "På bare én dag fik {STR_VAR_1}\n"
	.string "{STR_VAR_2} Kamp Point!\p"
	.string "{STR_VAR_1} blev senere set kæmpe\n"
	.string "med valget mellem at ombytte\l"
	.string "Kamp Point for en fed ting eller\l"
	.string "en smart indretningsgenstand.\p"
	.string "TRENEREN blev angiveligt set grinende\n"
	.string "mens han vendte mulighederne.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Nå, er det ikke noget!\p"
	.string "{STR_VAR_1}!\n"
	.string "Du er dagens nr. 1 TRÆNER!\p"
	.string "Seere, lad jer inspirere af {STR_VAR_1}!\n"
	.string "Også du kan være nr. 1 hver dag!$"

TVSecretBaseSecrets_Text_Intro::
	.string "HEMLIG BASE HEMMELIGHEDER!\p"
	.string "Hvad laver TRÆNERE i hemmelighed\n"
	.string "i HEMMELIGE BASER?\p"
	.string "I dag undersøger vi {STR_VAR_1}s\n"
	.string "HEMMELIGE BASE.\p"
	.string "Åh? Ser ud til at {STR_VAR_2} er kommet\n"
	.string "på besøg.\p"
	.string "Lad os tage et kig!\p"
	.string "Hvad vil {STR_VAR_2} gøre?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Hvad vil {STR_VAR_2} gøre nu?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Og nu, hvad vil {STR_VAR_2} gøre?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Til sidst tog {STR_VAR_2} {STR_VAR_3}\n"
	.string "skridt i {STR_VAR_1}s HEMMELIGE BASE før\n"
	.string "han forlod.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "Det ser ud til, at {STR_VAR_1}s HEMMELIGE\n" 
	.string "BASE ikke fangede {STR_VAR_2}s interesse…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} ser ud til at have haft\n"
	.string "en god tid i {STR_VAR_1}s HEMMELIGE BASE.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} synes at være blevet\n"
	.string "en kæmpe fan af {STR_VAR_1}'s\l"
	.string "HEMSLIGE BASE.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Seerne kan måske have lyst til at besøge\n"
	.string "{STR_VAR_1} HEMMELIGE BASE også.\p"
	.string "Bliv hængende til næste gang, hvor vi\n"
	.string "besøger en anden HEMMELIG BASE! Tak fordi\n"
	.string "I fulgte med!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Besøgende er stoppet!\p"
	.string "Besøgende bevæger sig ikke!\p"
	.string "Var {STR_VAR_1}s HEMMELIGE BASE\n"
	.string "så uimponerende?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Besøgende er stoppet!\p"
	.string "Besøgende bevæger sig ikke!\p"
	.string "Er det træthed?\n"
	.string "Mon besøgende er blevet træt?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Besøgende satte sig på en stol!\n"
	.string "Besøgende er nu siddende!\p"
	.string "Se den glæde i øjnene!\p"
	.string "Den stol må være meget behagelig\n"
	.string "for at få den reaktion!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Besøgeren angreb en ballon!\p"
	.string "Den sprang!\n"
	.string "Åh, du godeste, den poppede!\p"
	.string "Besøgeren ser ud til at blive\n"
	.string "forskrækket af den pludselige støj!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Besøgende kom ind i et TELT!\p"
	.string "Besøgende løber rundt!\p"
	.string "Åh, åh, besøgende leger!\p"
	.string "Besøgende virker overrasket over\n"
	.string "størrelsen på TELTET!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Besøgende undersøger\n"
	.string "en potteplante!\p"
	.string "Besøgende har overraskende\n"
	.string "moden smag!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Besøgende undersøger\n"
	.string "et GULD SKJOLD!\p"
	.string "Besøgendes øjne lyser\n"
	.string "op af beundring!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Besøgende undersøger\n"
	.string "et SØLVSKJOLD!\p"
	.string "Besøgende ser ud til at være storøjede!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Besøgende undersøger\n"
	.string "en GLASORNAMENT!\p"
	.string "Åh nej!\p"
	.string "Besøgende rører ved den!\p"
	.string "Den bliver dækket af\n"
	.string "fingeraftryk…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Besøgende ser fjernsyn!\p"
	.string "Det ser ud til, at vi har en stor fan af TV!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Besøgende trådte på en MUDDBOLD!\p"
	.string "Besøgende ser begejstret ud!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Åh?\p"
	.string "Besøgende når ned i deres eget\n"
	.string "taske og roder rundt i den!\p"
	.string "Besøgende trak en\n"
	.string "{STR_VAR_2} frem!\p"
	.string "Se besøgende smile mens de\n"
	.string "holder {STR_VAR_2} op!\p"
	.string "Det er ligesom en TV-reklame!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "The visitor grabs a cushion and…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…begynder at slå løs på den!\p"
	.string "Er besøgende under meget stress?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…krammer den hårdt!\p"
	.string "Mon besøgende føler sig glad over\n"
	.string "noget?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Besøgeren chatter med\n"
	.string "{STR_VAR_1}!\p"
	.string "Det ser ud til, at de skal\n"
	.string "kæmpe!\p"
	.string "Og...\p"
	.string "Det er besøgeren!\n"
	.string "Besøgeren vandt en udekamp!\p"
	.string "Besøgeren laver\n"
	.string "en sejrsdans!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Besøgende snakker med\n"
	.string "{STR_VAR_1}!\p"
	.string "Det ser ud til, de skal\n"
	.string "kæmpe!\p"
	.string "Og…\p"
	.string "Det er {STR_VAR_1}!\n"
	.string "Besøgende har tabt!\p"
	.string "Besøgende ser nedslået!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Besøgende taler med\n"
	.string "{STR_VAR_1}!\p"
	.string "Det ser ud til, at de skal\n"
	.string "kæmpe!\p"
	.string "Og...\p"
	.string "Nej, besøgende har afvist!\p"
	.string "Der bliver ingen kamp alligevel!\p"
	.string "Fandt besøgende {STR_VAR_1}\n"
	.string "upassende?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Besøgende stirrer intenst\n"
	.string "på en plakat!\p"
	.string "Kan plakaten lide besøgende?\p"
	.string "...Men... Der er noget forstyrrende\n"
	.string "ved besøgendes blikke.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Besøgende trådte på en NOTE MAT!\p"
	.string "…Hmm…\n"
	.string "Besøgende komponerede en sjov melodi!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Besøgende snakker med\n"
	.string "{STR_VAR_1}!\p"
	.string "Det ser ud til, at de skal\n"
	.string "kæmpe mod hinanden!\p"
	.string "Og…\p"
	.string "Det ender uafgjort!\n"
	.string "Ingen vinder!\p"
	.string "Begge TRÆNERE virker meget\n"
	.string "skuffede!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Besøgende trådte på\n"
	.string "en SPIN MAT!\p"
	.string "Det ser ud til, at besøgende er svimmel!\p"
	.string "Besøgende vakler rundt!\n"
	.string "Pas på!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Besøgende rækker ud efter\n"
	.string "en SAND ORNAMENT!\p"
	.string "Åh!\p"
	.string "Den smuldrede!\n"
	.string "Den er faldet fra hinanden!\p"
	.string "Besøgende ser flov ud\n"
	.string "og skyldig!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Besøgende gnider en skrivebordet\n"
	.string "med deres finger!\p"
	.string "Åbenbart er besøgende ikke fan\n"
	.string "af støv!\p"
	.string "Besøgende er overraskende bekymret\n"
	.string "for renlighed!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Besøgende stirrer på en MURSTEN!\p"
	.string "Måske tænker besøgende på\n"
	.string "objektet på MURSTENEN.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Besøgeren går henover\n"
	.string "DET FASTE BRÆT.\p"
	.string "Besøgeren kigger nedad.\p"
	.string "Besøgeren virker overraskende\n"
	.string "tavst og forsigtigt!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Besøgende kigger opmærksomt\n"
	.string "på et HEGN!\p"
	.string "Mon en ny idé til en fælde er\n"
	.string "poppet op i besøgendes hoved?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Besøgende trådte på\n"
	.string "et GLITTERMÅTTE!\p"
	.string "Besøgende laver en række\n"
	.string "positioner!\p"
	.string "Besøgende ser ud til\n"
	.string "at drømme om at være en idol!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Besøgeren stirrer intenst\n"
	.string "på et DÆK!\p"
	.string "Mon besøgeren tænker på\n"
	.string "hvad for en bil, der bruger det?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Den besøgende kravlede op på et STAND!\p"
	.string "Den besøgende kigger ud over\n"
	.string "{STR_VAR_1} BASE fra højt oppe!\p"
	.string "Og…\p"
	.string "Lader et brøl løs!\n"
	.string "Den besøgende brøler!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Besøgende styrter\n"
	.string "hovedkulds ind i\n"
	.string "en NEDBRYDELIG DØR!\p"
	.string "Besøgende ler højlydt!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Besøgende taler med en DUKKE!\p"
	.string "…Det er lidt uhyggeligt…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Besøgende klatrer op ad stigen\n"
	.string "på en RUTSCHEBANE!\p"
	.string "Og…\p"
	.string "Besøgende rutsjer ned!\p"
	.string "Det ser ud til at besøgende har\n"
	.string "en festlig tid!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Besøgende klatrer op ad stigen\n"
	.string "på en RUTSCHEBANE!\p"
	.string "Og…\p"
	.string "Besøgende gik tilbage ned ad\n"
	.string "stigen!\p"
	.string "Mon besøgende pludselig fik kolde fødder?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Besøgeren trådte på\n"
	.string "en SPRINGMAT!\p"
	.string "Besøgeren sprang én gang!\p"
	.string "Sprang to gange!\p"
	.string "Og en vellykket landing!\p"
	.string "Besøgeren klapper!\n"
	.string "Hvilken solopræstation!$"

gTVSafariFanClubText00::
	.string "SAFARI FAN CLUB!\p"
	.string "REPORTER: I orden, venner!\n"
	.string "Kaster I SAFARI-BOLDE, hva'?\p"
	.string "I kan være helt sikker på, at jeg er her i SAFARI-\n"
	.string "ZONEN, fyldt med fantastiske POKéMON!\p"
	.string "Kom nu, lad os tage fat på det og snakke\n"
	.string "med denne gode person, SAFARI-GUIDEN!\p"
	.string "I orden, ven, hvordan ser de besøgende\n"
	.string "TRÆNERE ud?$"

gTVSafariFanClubText01::
	.string "VEJLEDNING: Alle virker meget\n"
	.string "engagerede.\p"
	.string "{STR_VAR_1} klarer sig især godt.\p"
	.string "Faktisk fangede {STR_VAR_1} før\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "Træneren er dygtig med {POKEBLOCK}S.\n"
	.string "Brugte {STR_VAR_2} den gang, tror jeg.$"

gTVSafariFanClubText03::
	.string "TRÆNEREN brugte ikke en eneste\n"
	.string "{POKEBLOCK}! Ikke en eneste!\p"
	.string "Det er en ekspert, hva'?$"

gTVSafariFanClubText04::
	.string "REPORTER: Er det rigtigt, så?\p"
	.string "Det lyder som om vores ven {STR_VAR_1}\n"
	.string "er en sej SAFARI-mester!\p"
	.string "GUIDE: Jeg håber TRÆNEREN kommer tilbage\n"
	.string "og viser os den fantastiske teknik.$"

gTVSafariFanClubText05::
	.string "VEJLEDNING: Ingen ser ud til\n"
	.string "at klare sig særlig godt.\p"
	.string "{STR_VAR_1} havde det særligt skidt.\p"
	.string "Hvad før var TRÆNEREN kun i\n"
	.string "stand til at fange {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "VEJLEDNING: Der er ingen, der\n"
	.string "synes at klare sig særlig godt.\p"
	.string "{STR_VAR_1} havde det især skidt.\p"
	.string "Ja, førhen fangede TRÆNEREN\n"
	.string "ingen POKéMON. Ikke en eneste!$"

gTVSafariFanClubText07::
	.string "TRÆNEREN bruger {POKEBLOCK}ER.\n"
	.string "Brugte {STR_VAR_2} den gang, tror jeg.\p"
	.string "Men, arh, jeg ville ønske, at TRÆNEREN\n"
	.string "blev lidt bedre til dette.$"

gTVSafariFanClubText08::
	.string "Jeg tror TRÆNEREN ville have bedre\n"
	.string "held med at bruge {POKEBLOCK}S, som\l"
	.string "slet ikke blev brugt den gang.$"

gTVSafariFanClubText09::
	.string "REPORTER: Er det rigtigt, så?\p"
	.string "Det lyder som om vores kammerat {STR_VAR_1}\n"
	.string "har brug for mere SAFARI krydderi.\p"
	.string "GUIDE: Jeg håber, at TRÆNEREN besøger\n"
	.string "igen og igen for at få styr på det.$"

gTVSafariFanClubText10::
	.string "REPORTER: Helt rigtigt, det er det!\n" 
	.string "At tackle udfordringer er vigtigt!\p" 
	.string "Seere, kom ned til SAFARIEN\n" 
	.string "og påtag jer udfordringen selv!\p" 
	.string "Indtil næste gang, hej-hej!$"

ContestLiveUpdates_Text_Intro::
	.string "“POKéMON KONKURRENCE LIVE OPDATERINGER!”\p"
	.string "MC: Tak fordi I deltager!\p"
	.string "Vi sender live fra det netop\n"
	.string "{STR_VAR_1} sted.\p"
	.string "Salen er stadig fyldt med et\n"
	.string "publikum, der ikke vil gå.\p"
	.string "Tilskuer: {STR_VAR_2}!\p"
	.string "Tilskuer: {STR_VAR_3}!\p"
	.string "MC: Som I lige har hørt, blev KONKURRENCEN\n"
	.string "vundet af POKéMON {STR_VAR_2}\l"
	.string "fra {STR_VAR_3}.\p"
	.string "Tilskuer: {STR_VAR_2}!\n"
	.string "Du er den bedste!\p"
	.string "Tilskuer: {STR_VAR_3}!\n"
	.string "Godt gået!\p"
	.string "MC: Lad os høre, hvad fansene har\n"
	.string "at sige om denne KONKURRENCE.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Tilskuer: {STR_VAR_2} var den bedste\n"
	.string "i både primær og sekundær bedømmelse!\p"
	.string "Den {STR_VAR_2} vil fortsat vinde!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Tilskuer: {STR_VAR_2} klarede\n"
	.string "sig ikke så godt i den første bedømmelse,\n"
	.string "men gjorde rent bord i den sekundære bedømmelse!\p"
	.string "Det var et mirakuløst comeback\n"
	.string "for den {STR_VAR_2}. Yippee!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Tilskuer: {STR_VAR_2} forblev\n"
	.string "konsekvent gennem både primær\n"
	.string "og sekundær bedømmelse.\p"
	.string "{STR_VAR_3} og {STR_VAR_2}, de er\n"
	.string "ingen almindelig kombination!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Tilskuer: Hvad angår at være {STR_VAR_1},\n"
	.string "det {STR_VAR_2} var enestående.\p"
	.string "Jeg håber, det laver bedre\n"
	.string "appel næste gang, dog.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Tilskuer: Da {STR_VAR_2} blev\n"
	.string "nervøs, kunne jeg ikke lade være med\n"
	.string "at råbe opmuntrende til.\p"
	.string "Jeg vil gerne sige dette til den\n"
	.string "{STR_VAR_2}, “Tillykke!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Tilskuer: Selv jeg blev\n"
	.string "overrasket af {STR_VAR_2}'s appel!\p"
	.string "{STR_VAR_2}, du var fantastisk!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Tilskuer: Dét {STR_VAR_2}s kombination\n"
	.string "var forbløffende!\p"
	.string "Den rystede mig helt!$"

ContestLiveUpdates_Text_ExcitingAppeal::
    .string "Tilskuer: Vinderens\n"
    .string "tiltrækningskraft fik mit hjerte til at køre løs!$"

ContestLiveUpdates_Text_WasCool::
	.string "Det var sejt!\n"
	.string "Du var sej!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Du var smuk!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Du var sød!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Du var smart!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Du var sej!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Tilskuer: Vinderens\n"
	.string "tiltrækningskraft har stadig min\n"
	.string "puls i vejret!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Du er det sidste ord inden for sejt!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Du er den smukkeste!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Du er simpelthen den sødeste!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Du er den klogeste blandt de kloge!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Du er den sejeste af de seje!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Tilskuer: Selv da {STR_VAR_2}\n"
	.string "tog en pause fra at appellere,\l"
	.string "kunne jeg ikke tage øjnene fra det.\p"
	.string "Jeg er fængslet af den {STR_VAR_2}.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Tilskuer: Da {STR_VAR_2} blev\n"
	.string "forskrækket af en anden POKéMONs tiltrækning,\l"
	.string "var jeg tæt på at græde.\p"
	.string "{STR_VAR_2}, du var sej!\n"
	.string "Godt klaret!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Tilskuer: Åh…\n"
	.string "Det {STR_VAR_2}'s {STR_VAR_3}!\l"
	.string "{STR_VAR_2}'s {STR_VAR_3}!\l"
	.string "{STR_VAR_2}'s {STR_VAR_3}!\l"
	.string "Hvordan kan det være så vidunderligt?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC: Nå, her har du det. Dette sted er\n"
	.string "fyldt med {STR_VAR_1}'s fans!\p"
	.string "Jeg bør også nævne, at en anden\n"
	.string "POKéMON, {STR_VAR_2}'s {STR_VAR_3}, \l"
	.string "fangede min opmærksomhed.\p"
	.string "{STR_VAR_2}'s {STR_VAR_3}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Det mislykkedes at lave en enkelt\n"
	.string "appel under den sekundære bedømmelse af\n"
	.string "nervøsitet.\p"
	.string "Næste gang vil jeg gerne se denne\n"
	.string "{STR_VAR_1} lave bare én appel.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Det kom sidst i begge primære\n"
	.string "og sekundære bedømmelser.\p"
	.string "Jeg håber, at {STR_VAR_1} vil træne denne\n"
	.string "{STR_VAR_2} og slette skammen fra\l"
	.string "denne utvivlsomt sidsteplads.$"  

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Den formåede ikke at udnytte\n"
	.string "publikums spænding og lave et\l"
	.string "passende appel.\p"
	.string "Vi håber, at {STR_VAR_1} vil lære,\n"
	.string "hvordan man mærker publikum og får dem\l"
	.string "op at ringe af spænding næste gang.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Mens du endte som nummer et i den\n"
	.string "primære bedømmelse, faldt dens\n"
	.string "appeller i den sekundære bedømmelse\n"
	.string "fladt.\p"
	.string "Den led et pinligt comeback-tab.\p"
	.string "Jeg er sikker på at {STR_VAR_1} studerer\n"
	.string "nu, hvordan de kan lave mere\n"
	.string "effektive appeller.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Publikum blev aldrig begejstret af dets\n"
	.string "appel under den sekundære bedømmelse.\p"
	.string "Vi håber, at det vil holde op med at\n"
	.string "bekymre sig om andre POKéMON og\n"
	.string "lære at henvende sig til publikummet mere.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Den tabte til {STR_VAR_1}s {STR_VAR_2}\n"
	.string "med kun en lille margin.\p"
	.string "Det må være hjerteskærende at\n"
	.string "komme så tæt på sejr for så at\n"
	.string "miste. \p"
	.string "Jeg ville ikke blive overrasket, hvis\n"
	.string "{STR_VAR_3} græd over dette udfald.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Det skuffede DOMMEREN ved at\n"
	.string "gentage de samme appeller.\p"
	.string "Det er en uforsonlig fejl i enhver\n"
	.string "KONKURRENCE, og POKéMONET betalte.\p"
	.string "{STR_VAR_1} burde føle sig skyldig\n"
	.string "over denne sørgelige optræden.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} gjorde en tappert forsøg,\n"
	.string "men...\p"
	.string "Alt var forgæves, afsluttede sidst.\p"
	.string "{STR_VAR_1} bør lære af dette nederlag\n"
	.string "og anvende den viden til noget godt.$"

ContestLiveUpdates_Text_Outro::
	.string "Jeg vil gerne afslutte dette program\n"
	.string "med vores sædvanlige afsked til\n"
	.string "vinderne.\p"
	.string "Denne gang er det {STR_VAR_1} og\n"
	.string "{STR_VAR_2}!\p"
	.string "Vært: Er alle klar?\n"
	.string "Alle sammen nu!\p"
	.string "Publikum: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Tillykke!\l"
	.string "Du er vinderen af KONKURRENCEN!$"

gTVPokemonBattleUpdateText00::
	.string "“POKéMON KAMP OPDATERING!”\p"
	.string "Hold øje med resultaterne fra\n"
	.string "POKéMON kampe, som de kommer ind!$"

gTVPokemonBattleUpdateText01::
	.string "TRÆNERNE {STR_VAR_1} og\n"
	.string "{STR_VAR_2} stod over for\l"
	.string "hinanden i en {STR_VAR_3}\n"
	.string "KAMP.\p"
	.string "Denne kamp endte med sejr til\n"
	.string "{STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "I kampen var {STR_VAR_1}s\n"
	.string "{STR_VAR_2} en formidabel kraft\n"
	.string "der brugte {STR_VAR_3}!$" 

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_1}'s {STR_VAR_2} havde en svag\n"
	.string "præstation, der virkelig gjorde ondt.$"

gTVPokemonBattleUpdateText04::
	.string "Tillykke med din sejr,\n"
	.string "{STR_VAR_1}!\p"
	.string "Og til den slagne {STR_VAR_2},\n"
	.string "håber vi på et bedre resultat næste gang!\p"
	.string "Dette afslutter denne episode af\n"
	.string "“POKéMON KAMP OPDATERING!”$"

gTVPokemonBattleUpdateText05::
	.string "Holdene til TRÆNERE {STR_VAR_1} og\n"
	.string "{STR_VAR_2} mødtes i en MULTI KAMP.\p"
	.string "Denne kamp endte med sejr til\n"
	.string "holdet fra {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "I kampen var {STR_VAR_2} på\n"
	.string "{STR_VAR_1}s hold en formidabel\l"
	.string "kraft ved brug af {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "Den svage præstation af {STR_VAR_3}\n"
	.string "på {STR_VAR_2}s hold gjorde virkelig ondt.\p"
	.string "Tillykke med dit holds\n"
	.string "sejr, {STR_VAR_1}!\p"
	.string "Hvad angår det besejrede {STR_VAR_2}s hold,\n"
	.string "håber vi på et bedre resultat næste gang!\p"
	.string "Dette afslutter denne episode af\n"
	.string "“POKéMON BATTLE UPDATE!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Åh! Vi har lige spottet en sej-\n"
	.string "udseende TRÆNER her af alle steder!\p"
	.string "Okay, rul kameraet!\n"
	.string "Lad os få denne interview.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Åh! Du er {PLAYER}! Hej!\n"
	.string "Husker du os fra sidste gang?\p"
	.string "Kan du vise os, hvor meget stærkere\n"
	.string "du er blevet? Okay, start interviewet!$"


GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: Mine øjne løb ikke!\n"
	.string "Jeg har fundet en forbløffende TRÆNER!$"

GabbyAndTy_Text_WhoAreYouInterview:
    .string "GABBY: Fantastisk! Fantastisk!\n"
    .string "Hvem er du?!\p"
    .string "Jeg vidste, vi var på noget vildt,\n"
    .string "da vi fik øje på dig!\p"
    .string "Åh, lad mig forklare. Vi rejser rundt\n"
    .string "overalt og interviewer alle slags\n"
    .string "TRÆNERE.\p"
    .string "Så, vil du give os lidt af din tid\n"
    .string "til et interview?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Husker du? Det er citatet, du gav\n"
	.string "os som det afgørende i kampen\n"
	.string "sidste gang. Jeg glemmer aldrig sådan noget!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "Sidste gang vi kæmpede, stampede du\n"
	.string "os, før vi kunne forberede os…\p"
	.string "Nå, hvad synes du?\n"
	.string "Vil du interviewes igen?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "Sidste gang vi kæmpede, kastede du\n"
	.string "ikke en POKé BALL mod os?\p"
	.string "Vi var helt målløse! Så fortalte vi\n"
	.string "det til alle, ja, alle sammen!\p"
	.string "Nå, hvad siger du så?\n"
	.string "Vil du have en interview runde til?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "Sidste gang vi kæmpede, narrede\p"
	.string "dine genstandsevner os snedigt.\n"
	.string "Nå, hvad synes du?\n"
	.string "Vil du interviewes igen?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "Sidste gang vi kæmpede, formåede vi\n"
	.string "at se respektable ud.\p"
	.string "Men hvad synes du?\n"
	.string "Vil du interviewes igen?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Nå, hvad synes du?\n"
	.string "Vil du interviewes igen?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Vil du?\n"
	.string "Tak!\p"
	.string "Okay, jeg har brug for dig til at\n"
	.string "beskrive dine følelser om vores kamp,\n"
	.string "men det skal være kort og sødt. Skyd løs!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, ja!\n"
	.string "Det er den perfekte afslutning!\p"
	.string "Jeg har en fornemmelse af, at det her\n"
	.string "vil blive en fantastisk tv-show.\p"
	.string "Der er en chance for, at de vil vise det\n"
	.string "på tv, så sørg for at kigge efter os!\p"
	.string "Okay!\n"
	.string "Vi vil se dig igen!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Åh…\p"
	.string "Okay, men give ikke op!\n"
	.string "Vi vil holde øje med dig!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
    .string "GABBY: Vi vil holde øje med dig!\n"
    .string "$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Er der en stærk\n"
	.string "TRÆNER et sted med mange POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Wow, du er noget!\p"
	.string "Du er blevet meget stærk--meget--\n"
	.string "siden vi sidst kæmpede.\p"
	.string "Vi havde ret angående dig, da vi\n"
	.string "opdagede dig som en sej TRÆNER.\p"
	.string "Så, hvad siger du?\n"
	.string "Er du villig til at give os et interview\l"
	.string "denne gang?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: Det var en intens kamp!\n"
	.string "Fik du det hele med på kameraet?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Hej, se lige her! En sej udseende\n"
	.string "TRÆNER her, af alle steder!\l"
	.string "Kameraet kører!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Hey, se lige her!\n"
	.string "Jeg husker dig!\p"
	.string "Jeg får denne kamp med det\n"
	.string "her kamera!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: Du er en naturtalent!\n"
	.string "Jeg har fået nogle fantastiske optagelser lige her!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Har du kun den ene POKéMON\n"
	.string "og det er det?\p"
	.string "Hvis du havde flere POKéMON, ville det\n"
	.string "give bedre optagelser, men...$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Ja, vi har virkelig spottet en sej TRÆNER.\n"
	.string "Det her er et kæmpe scoop for os!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Jep, jeg har det hele.\n"
	.string "Hele den kamp er på kameraet.$"

gTVInSearchOfTrainersText00::
	.string "PÅ JAGT EFTER TRÆNERE…\p"
	.string "GABBY: Hej! I dag besøger jeg et område\n"
	.string "i nærheden af {STR_VAR_1}.\p"
	.string "Vi prøver at spotte nogle nye talenter\n"
	.string "på området.\p"
	.string "I dag rettede vi vores linse mod\n"
	.string "TRÆNER {PLAYER}.\p"
	.string "Der er noget ved denne TRÆNER, der\n"
	.string "har vakt vores interesse.$"

gTVInSearchOfTrainersText01::
	.string "Vi har kæmpet mod {PLAYER} før, men vi\n"
	.string "kan bekræfte, at TRÆNEREN klart er\n"
	.string "blevet bedre siden sidst.\p"
	.string "Jeg vidste, at vi var på sporet af\n"
	.string "en særlig person, da vi opdagede\n"
	.string "dig, TRÆNER!$"

gTVInSearchOfTrainersText02::
	.string "Den bedste måde at afgøre, hvor\n"
	.string "stærk en TRÆNER er...\p"
	.string "Nå, den hurtigste måde er at kæmpe.\n"
	.string "Og så begyndte vores undersøgelse!\p"
	.string "… …\p"
	.string "Sådan endte vi i kamp mod {PLAYER}.\p"
	.string "I en dominerende præstation blev vi\n"
	.string "fladt ud, rullet sammen og smidt væk!\p"
	.string "{PLAYER} er nådesløst stærk...\p"
	.string "Her er vores indtryk efter at have\n"
	.string "kæmpet mod vores fremhævede TRÆNER.$"

gTVInSearchOfTrainersText03::
	.string "Kombinationen af {STR_VAR_1}\n"
	.string "og {STR_VAR_3} var guddommelig!\p"
	.string "Synet af dem--{STR_VAR_1} og {STR_VAR_3}--\n"
	.string "der støtter hinanden selv\n"
	.string "løst i kampens hede…\p"
	.string "Det var et vidunderligt syn at skue!\p"
	.string "{STR_VAR_2} var trænerens sidste\n"
	.string "træk i vores kamp.\p"
	.string "Trækket {STR_VAR_2} er {STR_VAR_1}\n"
	.string "og {STR_VAR_3}'s tegn på venskab!$"

gTVInSearchOfTrainersText04::
	.string "…Jeg mistede tilliden til mig selv\n"
	.string "som et resultat af vores møde.\p"
	.string "Vi blev slået inden vi kunne\n"
	.string "igangsætte et enkelt angreb.\l"
	.string "Åhhhh… Hulke…\p"
	.string "Ikke desto mindre er {PLAYER}s\n"
	.string "kampe værd at se.\p"
	.string "Jeg anbefaler selvsikre TRÆNERE\n"
	.string "at udfordre {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Der er kun een ting at sige.\n"
	.string "Vov ikke at kaste en POKé BALL under\l"
	.string "en TRÆNER duel!\p"
	.string "{PLAYER} er helt sikkert stærk, men har\n"
	.string "ingen anelse om de grundlæggende regler.\p"
	.string "Til vores TV-publikum har jeg en anmodning.\p"
	.string "Hvis du ser {PLAYER}, bedes du advare\n"
	.string "TRÆNEREN!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} er ferm til at læse\n"
	.string "modstanderens handlinger.\p"
	.string "Timing af genstandsbrug var\n"
	.string "bemærkelsesværdigt effektivt!$"

gTVInSearchOfTrainersText07::
	.string "Ærligt talt troede jeg, at jeg\n"
	.string "måske endda var ret god.\p"
	.string "Selvom vi endte med at tabe, havde vi\n"
	.string "en hårdt kæmpet kamp.\p"
	.string "Men hvis du kæmper med at slå mig,\n"
	.string "har du stadig et stykke vej at gå, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Efter vores kamp bad vi {PLAYER}\n"
	.string "om en kort opsummering.\p"
	.string "TRÆNEREN svarede, “{STR_VAR_1}.”\p"
	.string "{PLAYER}s POKéMON {STR_VAR_2} og\n"
	.string "{STR_VAR_3}…\l"
	.string "Og “{STR_VAR_1}”…\p"
	.string "Mmm! Det er dybt! Der er dyb\n"
	.string "betydning bag den kommentar!\p"
	.string "Det er ingen overraskelse - en god\n"
	.string "TRÆNER har gode ting at sige.\p"
	.string "Det er alt for i dag!\n"
	.string "Vi ses igen i vores næste udsendelse!$"

ContestLadyShow_Text_Intro::
	.string "“POKéMON KONKURRENCE LIVE OPDATERINGER!”\p"
	.string "MC: Undskyld, at vi afbryder den\n"
	.string "normale udsendelse, og tak fordi du er med!\p"
	.string "Vi bringer dette live fra\n"
	.string "stedet for netop afsluttede\l"
	.string "{STR_VAR_1}!\p"
	.string "Tilskuere: ?!!!!\p"
	.string "MC: Åh! Det ser ud til, at KONKURRENCENS\n"
	.string "deltagere er på vej hertil!\p"
	.string "Jeg vil forsøge at få en spontan\n"
	.string "interview til jer derhjemme!\p"
	.string "Tilskuere: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "MC: Undskyld!\n"
	.string "Tak fordi du deltager i vores live TV-show!\p"
	.string "Må jeg lykønske dig med din sejr?\p"
	.string "Hvad var den afgørende faktor i\p"
	.string "dagens fantastiske sejr?\p"
	.string "SKØNHED: Vi gav vores bedste i\p"
	.string "dag, min {STR_VAR_2} og jeg!\p"
	.string "Men jeg er sikker på, at vi ikke\p"
	.string "ville have klaret det, hvis det ikke var\p"
	.string "for al den hjælp, vi modtog op til KONKURRENCEN!\p"
	.string "MC: Har du en helt speciel person,\p"
	.string "som du gerne vil dele din glæde med?\l"
	.string "Lad os høre det live!\p"
	.string "SKØNHED: Hej derude!\p"
	.string "{STR_VAR_3}! Ser du med?\n"
	.string "Vi gjorde det!\l"
	.string "Tak!$"

ContestLadyShow_Text_Lost::
	.string "MC: Undskyld!\n"
	.string "Tak fordi du er med på live TV!\p"
	.string "Er du skuffet over den vending af\n"
	.string "begivenhederne? Har du nogen kommentarer?\p"
	.string "BEAUTY: Det er hjerteknusende…\n"
	.string "Min {STR_VAR_2} og jeg gjorde vores bedste…\p"
	.string "Men jeg føler, at jeg har skuffet alle,\n"
	.string "der har støttet os igennem dette.\p"
	.string "MC: Jeg hader at sige det, men POKéMONs\n"
	.string "farvning er lidt mangelfuld.\p"
	.string "BEAUTY: {STR_VAR_3}, undskyld…\n"
	.string "Jeg vil gøre det bedre næste gang, jeg\n"
	.string "sværger…\l"
	.string "…Snøft… Waaaaah!\p"
	.string "Tilskuere: Ser du det der?\n"
	.string "Den stakkels pige!\p"
	.string "MC: Øh… Øh-oh…\p"
	.string "Øh… Det er alt den tid, vi har i dag!\n"
	.string "Tak fordi I fulgte med!$"

ContestLadyShow_Text_LostBadly::
	.string "MC: Undskyld!\n"
	.string "Tak fordi du er med os på live TV!\p"
	.string "Hvordan gik din KONKURRENCEoptræden?\p"
	.string "SKØNHED: Ingenting gik godt...\n"
	.string "Af en eller anden grund kunne min {STR_VAR_2}\l"
	.string "ikke tiltrække nogen popularitet.\p"
	.string "MC: Jeg hader at sige det, men POKéMON'ens\n"
	.string "farvevalg er lidt manglende.\p"
	.string "SKØNHED: ......\n"
	.string "...Snøft... Buuuuh!\p"
	.string "Tilskuere: Ser du det der?\n"
	.string "Den stakkels pige!\p"
	.string "MC: Øh... Øh-oh...\p"
	.string "Øh... Det er alt, hvad vi har tid til i dag!\n"
	.string "Tak for at følge med!$"
