@ TRANSLATED

LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Hej, halloj! Du var til en POKéMON\n"
	.string "KONKURRENCE, ikke sandt? Det kan jeg\l"
	.string "nemt se ud fra dine POKéMON.\p"
	.string "Jeg er reporter. Jeg arbejder på en\n"
	.string "historie om POKéMON-KONKURRENCER.\p"
	.string "Hvis du vil, vil du så være villig til at\n"
	.string "svare på nogle spørgsmål?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Åh, vil du det? Tak.\p"
	.string "Kort sagt, hvordan vil du beskrive DEN\n"
	.string "KONKURRENCE, du lige deltog i?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Åh, jeg forstår. Det er en meget\n"
	.string "oplysende kommentar.\p"
	.string "Du får en god fornemmelse af, hvordan\n"
	.string "KONKURRENCEN var.\p"
	.string "Jeg har et sidste spørgsmål.\p"
	.string "Når du hører ordet “{STR_VAR_2},”\n"
	.string "hvilket billede dukker op?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Jeg forstår!\p"
	.string "Sådan forestiller du dig konceptet\n"
	.string "“{STR_VAR_2}” altså. \p"
	.string "Tak! Du har givet mig nogle gode idéer.\p"
	.string "Jeg tror, jeg kan skrive en god historie\n"
	.string "om POKéMONKONKURRENCER nu.\p"
	.string "Måske, bare måske, kommer denne\n"
	.string "historie endda på fjernsyn. Jeg håber,\l"
	.string "du glæder dig til det!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Åh, det var ærgerligt...\p"
	.string "Hvis du nu skulle støde på en god\n"
	.string "historie, så del den gerne med mig.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Jeg glæder mig til din næste\n"
	.string "POKéMON-KONKURRENCE.$"

gTVBravoTrainerText00::
	.string "Jubi! Det er BRAVO TRAINER tid!\p"
	.string "I dag vil vi præsentere en POKéMON som\n"
	.string "tilhører {STR_VAR_1}.\p"
	.string "Denne POKéMON praler med en\n"
	.string "{STR_VAR_3} rangering i\l"
	.string "{STR_VAR_2} kategorien.$"

gTVBravoTrainerText01::
	.string "Præsenterer {STR_VAR_2},\n"
	.string "{STR_VAR_1}!\p"
	.string "Kælenavnet {STR_VAR_2}…\p"
	.string "Selv kælenavnet udstråler en attitude\n"
	.string "der proklamerer “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Nå, da TRÆNEREN {STR_VAR_1} meldte\n"
	.string "POKéMON til en KONKURRENCE, lykkedes\l"
	.string "det os at få nogle begejstrede citat\l"
	.string "fra den pålidelige partner.$"

gTVBravoTrainerText03::
	.string "Spurgt om KONKURRENCEN bagefter,\n"
	.string "{STR_VAR_1} svarede lykkeligt med et\l"
	.string "kæmpe smil, “{STR_VAR_2}!”\p"
	.string "Nå ja, {STR_VAR_1}'s POKéMON kom på\n"
	.string "plads {STR_VAR_3} i KONKURRENCEN.\p"
	.string "Den sætning passer perfekt til\n"
	.string "{STR_VAR_1} lige nu, vil jeg sige!$"

gTVBravoTrainerText04::
	.string "Spurgt om KONKURRENCEN bagefter,\n"
	.string "{STR_VAR_1} svarede med en smule\l"
	.string "bitterhed, “{STR_VAR_2}.”\p"
	.string "Nå, selvfølgelig, {STR_VAR_1}s\n"
	.string "POKéMON kom på plads nummer\l"
	.string "{STR_VAR_3} i KONKURRENCEN.\p"
	.string "{STR_VAR_1}s skuffelse skinner\n"
	.string "klart igennem, vil jeg sige!$"

gTVBravoTrainerText05::
	.string "Wouldn't you also like to know what\n"
	.string "{STR_VAR_1} imagines {STR_VAR_2}\l"
	.string "to be?\p"
	.string "You bet we did! So we asked, of course!\p"
	.string "The answer is all perfectly condensed:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "That's what the concept of\n"
	.string "{STR_VAR_2} represents to\l"
	.string "{STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "Den sidste bevægelse {STR_VAR_2}\n"
	.string "brugt af {STR_VAR_1} handler hele\l"
	.string "vejen om “{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "Super godt gået, {STR_VAR_1}!\n"
	.string "Fantastisk, {STR_VAR_2}!\p"
	.string "Jeg håber, vi kan regne med at se\n"
	.string "{STR_VAR_1} nå endnu større højder!\p"
	.string "Det er alt den tid, vi har! Vi ses næste\n"
	.string "gang!$"

gTVBravoTrainerText08::
	.string "Præsenterer TRÆNERENS {STR_VAR_1}!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Hej! Er du TRÆNEREN, der lige har haft\n"
	.string "en kamp, ikke sandt?\p"
	.string "Jeg samler interviews med TRÆNERE\n"
	.string "overalt.\p"
	.string "Må jeg få nogle ord fra dig om dine\n"
	.string "indtryk af at kæmpe?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Vil du? Virkelig? Tak! Øh, så...\p"
	.string "Hvordan gik det i KAMPENS TÅRN i dag?\p"
	.string "Var du tilfreds med kampen? Eller er du\n"
	.string "utilfreds?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Åh... Undskyld vi forstyrrede dig.\p"
	.string "Vil du give os et interview næste\p"
	.string "gang du besøger KAMPTÅRNET.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Selvfølgelig!\p"
	.string "Det ufejlbarlige udtryk af tilfredshed\n"
	.string "på dit ansigt…\p"
	.string "Det er tydeligt, at du har haft en stor\n"
	.string "kamp.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Åh, jeg forstår... \p"
	.string "Det er virkelig svært at få en kamp til\n"
	.string "at forløbe præcis som planlagt.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Åh, må jeg stille endnu et spørgsmål?\p"
	.string "Hvis du skulle beskrive dine indtryk af\n"
	.string "denne kamp med én sætning, hvad ville\l"
	.string "det være?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Åh, det er helt vildt sejt!\p"
	.string "Det er en fantastisk linje! Jeg håber,\n"
	.string "at du klarer dig fantastisk næste gang\l"
	.string "også.\p"
	.string "Jeg håber at se dig igen!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Åh, jeg forstår... \p"
	.string "Men at være den stille type er også\n"
	.string "sejt, ikke sandt? \p"
	.string "Jeg håber, at du vil give mig muligheden\n"
	.string "for at dele dine tanker igen!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Jeg glæder mig til din næste kamp!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Ja! Det er BRAVO TRAINER tid!\p"
	.string "I dag skal vi profilere {STR_VAR_1},\n"
	.string "som tog BATTLE TOWER udfordringen!\p"
	.string "Til udfordringen brugte {STR_VAR_1}\n"
	.string "ét vildt {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Dette par satte en ny rekord med\n"
	.string "{STR_VAR_2} sejre i træk i\l"
	.string "{STR_VAR_1} konkurrence! Bravo,\l"
	.string "TRÆNER!$"

BravoTrainerBattleTower_Text_Lost::
	.string "De to endte endelig med at give op over\n"
	.string "for {STR_VAR_1} i kamp nummer\l"
	.string "{STR_VAR_2}. Godt forsøgt, TRÆNER!\p"
	.string "Men hey, det er bare uheldigt at løbe\n"
	.string "ind i {STR_VAR_1} så tidligt i\l"
	.string "udfordringen.\p"
	.string "Vi bad TRÆNEREN om indtryk af kampen\n"
	.string "med {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "Det seje twosome vandt det hele ved at\n"
	.string "slå {STR_VAR_1}'s {STR_VAR_2}\l"
	.string "grundigt. Bravo, TRÆNER!\p"
	.string "At slå endda {STR_VAR_1}… Det er\n"
	.string "ubegribeligt! Simpelthen fantastisk!\p"
	.string "Vi bad TRÆNEREN om indtryk af\n"
	.string "øjeblikket med herlighed.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Efter en række sejre gav de endelig\n"
	.string "efter for {STR_VAR_1}'s\l"
	.string "{STR_VAR_2}, deres sidste\l"
	.string "forhindring.\p"
	.string "Godt forsøg, TRÆNER!\p"
	.string "Alligevel må man give credit. Man ser\n"
	.string "ikke mange berømte kombinationer som\l"
	.string "{STR_VAR_1} og {STR_VAR_2}.\p"
	.string "Vi spurgte TRÆNEREN om indtrykkene af\n"
	.string "at kæmpe mod det berømte par.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Det her er hvad TRÆNEREN sagde: “Jeg\n"
	.string "er tilfreds!”\p"
	.string "Er det ikke en forfriskende svar?\n"
	.string "Bravo, TRÆNER!\p"
	.string "Er det ikke bare fantastisk at kunne\n"
	.string "kæmpe til fuld tilfredshed?\p"
	.string "Jeg fandt ud præcist hvor tilfreds jeg\n"
	.string "blev, da jeg hørte TRÆNEREN sige dette:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Dette er hvad TRÆNEREN havde at sige:\n"
	.string "“Jeg er ikke tilfreds…”\p"
	.string "Vores TRÆNER var åbenlyst lidt nede da\n"
	.string "det blev sagt.\p"
	.string "Det er stadig ikke let at være i stand\n"
	.string "til at kæmpe med fuld tilfredshed, ikke\l"
	.string "sandt?\p"
	.string "Uanset hvad, fandt jeg ud af hvor\n"
	.string "utilfreds vores TRÆNER var da jeg hørte\l"
	.string "dette:$"

BravoTrainerBattleTower_Text_None1::
	.string "Ingen$"

BravoTrainerBattleTower_Text_None2::
	.string "Ingen$"

BravoTrainerBattleTower_Text_None3::
	.string "Ingen$"

BravoTrainerBattleTower_Text_None4::
	.string "Ingen$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.” Er det ikke\n"
	.string "fantastisk?\p"
	.string "Det udtrykker virkelig {STR_VAR_2}s\n"
	.string "glæde, vil jeg sige.\p"
	.string "Den kamp mod {STR_VAR_3} i\n"
	.string "slutningen… Det var virkelig det man\l"
	.string "kalder “{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.” Nu er det da\n"
	.string "passende, ikke sandt?\p"
	.string "Den kamp med {STR_VAR_3} i\n"
	.string "slutningen… Man kan ikke beskrive det\l"
	.string "som andet end “{STR_VAR_1}”!\p"
	.string "{STR_VAR_2}'s skuffelse er helt\n"
	.string "tydelig, vil jeg sige!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}! Bravo,\n"
	.string "{STR_VAR_2}!\p"
	.string "Jeg håber, vi kan regne med at se\n"
	.string "{STR_VAR_1} nå endnu større højder!\p"
	.string "Det er alt den tid, vi har! Vi ses næste\n"
	.string "gang!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "Det er tydeligt, at du overøser\n"
	.string "kærlighed på din {STR_VAR_1}.\p"
	.string "Okay, den hedder {STR_VAR_2}.\p"
	.string "Kan jeg bede om en tjeneste?\p"
	.string "Jeg er en TV-reporter, og jeg laver en\n"
	.string "undersøgelse om POKéMON.\p"
	.string "Vil du være villig til at svare på et par\n"
	.string "simple spørgsmål for mig?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Fantastisk! Tak!\p"
	.string "Okay, her går det. Jeg har bare brug for\n"
	.string "hurtige svar, okay?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Da du først mødte {STR_VAR_1}, hvad\n"
	.string "følte du?\p"
	.string "Hvordan vil du beskrive dine følelser på\n"
	.string "det tidspunkt?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Din {STR_VAR_1} bliver passet\n"
	.string "kærligt på.\p"
	.string "Hvis du skulle sammenligne det med\n"
	.string "noget, du godt kan lide, hvad ville det\l"
	.string "være?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Denne spørgsmål handler også om din\n"
	.string "elskede {STR_VAR_1}.\p"
	.string "Hvad var det ved {STR_VAR_1}, der\n"
	.string "tiltrak dig?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Okay, det giver mening.\p"
	.string "Det næste spørgsmål kan være lidt\n"
	.string "svært.\p"
	.string "Her kommer det…\p"
	.string "Hvad betyder POKéMON for dig?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Jeg forstår!\p"
	.string "Hmhm…\p"
	.string "Okay! Tak for at hjælpe mig.\p"
	.string "Det var sjovt og oplysende at snakke\n"
	.string "med dig.\p"
	.string "Det er muligt, at vores interview ender\n"
	.string "på tv. Hold dig opdateret!\p"
	.string "Okay, det er det. Hej-hej!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Nå, okay…\p"
	.string "Nå, hvis du får lyst til at fortælle mig\n"
	.string "om POKéMON, så er jeg her!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Jeg nyder dette job--du lærer om\n"
	.string "POKéMON ved at lave interviews.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Hej, du virker meget tæt på din\n"
	.string "{STR_VAR_1}.\p"
	.string "Gæt hvad? Jeg er en tv-reporter.\p"
	.string "Jeg rejser rundt og interviewer folk om\n"
	.string "POKéMON.\p"
	.string "Jeg tænkte på, om du ville fortælle mig\n"
	.string "lidt om din {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Wow, tak!\p"
	.string "Okay, så fortæl mig venligst alt, hvad du\n"
	.string "vil, om din {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Wow… Det er en spændende historie.\p"
	.string "Du er virkelig tætte med\n"
	.string "{STR_VAR_1}, ikke sandt?\p"
	.string "Jeg har en fornemmelse af, at din\n"
	.string "historie vil blive en fed TV- fortælling.\p"
	.string "Jeg lover, at jeg vil gøre dette til et\n"
	.string "underholdende show. Hold øjnene åbne\l"
	.string "for det.\p"
	.string "Okay, det var alt. Hej-hej!$"

gTVFanClubOpinionsText00::
	.string "VI ER POKéMON-FANKLUBBEN!\p"
	.string "Vi er på luften!\p"
	.string "I dette program får vi jeres meninger,\n"
	.string "og jeg råber dem ud på jeres vegne! Er\l"
	.string "det ikke en fantastisk programidé?\p"
	.string "I dag bringer vi denne rapport fra\n"
	.string "vores reporter, som vi sendte ud til\l"
	.string "POKéMON-FANKLUBBEN.\p"
	.string "Så, hvem er dagens fremhævede\n"
	.string "POKéMON-fan?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Lad os høre, hvad {STR_VAR_1} har at\n"
	.string "sige om {STR_VAR_3} den\l"
	.string "{STR_VAR_2}.\p"
	.string "Og jeg vil råbe disse kærlighedsord højt\n"
	.string "på tv!\p"
	.string "Hoo-hah!\p"
	.string "Lad os råbe!$"

gTVFanClubOpinionsText01::
	.string "Vi spurgte {STR_VAR_1}, “Da du først\n"
	.string "så din {STR_VAR_2}, hvad tænkte du\l"
	.string "så første gang?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Yeahah! Det var da en kanon god udråb!\p"
	.string "Giver det ikke minder om de gode gamle\n"
	.string "dage?$"

gTVFanClubOpinionsText02::
	.string "Vi spurgte {STR_VAR_1}, “Hvis du\n"
	.string "skulle sammenligne din {STR_VAR_2}\l"
	.string "med noget, ville det være…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Whoah-oh, det er virkelig en original\n"
	.string "idé!\p"
	.string "Du kan virkelig fornemme TRÆNERENS\n"
	.string "intensitet af følelser for\l"
	.string "{STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Og lad os se... Hvad var det ved den\n"
	.string "{STR_VAR_2}, som tiltrak\l"
	.string "{STR_VAR_1} så meget?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Wow! En så spektakulær erklæring!\p"
	.string "{STR_VAR_1}s kærlighed til\n"
	.string "{STR_VAR_2} skinner tydeligt\l"
	.string "igennem!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oh, there's still more. Let's check\n"
	.string "it out!\p"
	.string "Let me see, now…\p"
	.string "We asked {STR_VAR_1}, “What do\n"
	.string "POKéMON mean to you?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "That's the best shout I've had all day!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "It makes you want to shout it out loud\n"
	.string "again and again!\p"
	.string "Now that we've had a great shout, it's\n"
	.string "time to say good-bye until next time!\p"
	.string "So, let's all have one last shout! All\n"
	.string "together now…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "VI ER POKéMON FANKLUBBEN!\p"
	.string "Vi er på luften!\p"
	.string "I dag går vi i gang medPOKéMON\n"
	.string "UNDERSØGELSESKROGEN.\p"
	.string "Af alle de historier, der er vævet af\n"
	.string "POKéMON og TRÆNERE, hvilken\l"
	.string "overraskende ny drama vil fangevores\l"
	.string "opmærksomhed i dag?\p"
	.string "Lad mig se…\p"
	.string "Den her!\p"
	.string "Vi starter med det her brev!\p"
	.string "Det er et brev fra {STR_VAR_1} om en\n"
	.string "elsket {STR_VAR_2}.\p"
	.string "Lad os se, hvor lidenskabeligt vores\n"
	.string "forfatter kan udtrykke kærlighed\l"
	.string "til{STR_VAR_2}! Hmhm…$"

gTVFanClubText01::
	.string "Whoah! Hvilket fantastisk brev!$"

gTVFanClubText02::
	.string "Jeg elskede det, så her er det igen!$"

gTVFanClubText03::
	.string "Et fantastisk brev er værd at læse om\n"
	.string "og om igen!$"

gTVFanClubText04::
	.string "Det stykke “{STR_VAR_3},” det\n"
	.string "virkelig accentuerer den\l"
	.string "følelsesmæssige påvirkning!\p"
	.string "Det er et fantastisk brev, der har en\n"
	.string "dybfølt dybde!$"

gTVFanClubText05::
	.string "Især den der “{STR_VAR_3}”-del!\p"
	.string "Jeg elsker, hvordan “{STR_VAR_3}”\n"
	.string "bliver brugt!$"

gTVFanClubText06::
	.string "Forresten, og det er ikke vigtigt, men\n"
	.string "{STR_VAR_3} er en fantastisk\l"
	.string "udtalelse.\p"
	.string "Jeg har brugt {STR_VAR_3} meget i\n"
	.string "samtaler for nylig.$"

gTVFanClubText07::
	.string "Hvis jeg skulle give denne besked en\n"
	.string "karakter, ville jeg give den\l"
	.string "{STR_VAR_3} point.\p"
	.string "Næste gang forventer jeg en endnu\n"
	.string "bedre besked, {STR_VAR_1}!\p"
	.string "Åh ups, ser du lige på klokken? Tid til\n"
	.string "at sige farvel indtil næste gang!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Nå? Kan det være, at du godt kan lide\n"
	.string "POKéMON?\p"
	.string "Jeg er på opgave for TV-netværket.\p"
	.string "Jeg samler historier om POKéMON og\n"
	.string "TRÆNERE, der er sket for nylig.\p"
	.string "Hvis du har lyst, kunne du så ikke\n"
	.string "fortælle mig lidt om dig selv?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Jeg indsamler historier om POKéMON og\n"
	.string "TRÆNERE, der skete for nylig.\p"
	.string "Hvis det er i orden, kunne du så ikke\n"
	.string "fortælle mig noget om dig selv?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Åh, vil du det? Tak!\p"
	.string "Så fortæl mig venligst noget\n"
	.string "interessant, som du har oplevet for\l"
	.string "nylig med POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Åh, nu forstår jeg…\p"
	.string "Hvis du har en interessant historie at\n"
	.string "fortælle, så lad mig venligst vide.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Åh, sikke en opmuntrende historie!\p"
	.string "Jeg skal sørge for, at din historie\n"
	.string "bliver fortalt på tv.\p"
	.string "Det burde blive vist på et tidspunkt, så\n"
	.string "glæd dig til det.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmmm... Jeg har en god historie til et\n"
	.string "tv-program.\p"
	.string "Jeg bør nok skrive den ned i en fart!$"

gTVRecentHappeningsText00::
	.string "Hej, det er tid til SENESTE NYT.\p"
	.string "For POKéMON TRÆNERE, er hver dag som en\n"
	.string "eventyrbogshistorie.\p"
	.string "Hvad vi gerne vil, er at præsentere dig\n"
	.string "for nogle af disse POKéMON-historier.\p"
	.string "I dag bringer vi dig historien om TRÆNER\n"
	.string "{STR_VAR_1}.\p"
	.string "Hvad har {STR_VAR_1} oplevet for\n"
	.string "nylig? Lad os finde ud af det.\p"
	.string "Lad os se…$"

gTVRecentHappeningsText01::
	.string "Var det ikke oplysende?\p"
	.string "Historien giver dig en klar idé om, hvad\n"
	.string "{STR_VAR_1} har oplevet for nylig.\l"
	.string "Det er, som om vi var der som vidner!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Det giver\n"
	.string "fortællingen et strejf og dybde.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.” Det giver historien\n"
	.string "en følelse af sted. Det lader os\l"
	.string "forestille os historiens miljø.$"

gTVRecentHappeningsText04::
	.string "Afsnittet “{STR_VAR_3}” i historien\n"
	.string "er meget udtryksfuldt.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} har genfortalt en\n"
	.string "fantastisk historie om POKéMON.\p"
	.string "Og nu er {STR_VAR_1}s historie\n"
	.string "uudsletteligt indgraveret i din sjæl\l"
	.string "også.\p"
	.string "Det var alt for i dag. Tune venligst ind\n"
	.string "næste gang.$"

gTVMassOutbreakText00::
	.string "Hej! Det er tid til POKéMON-NYHEDERNE.\p"
	.string "Vi har netop fået ord om en meget\n"
	.string "sjælden begivenhed.\p"
	.string "Der er rapporter om et massivt udbrud\n"
	.string "af {STR_VAR_2} i nærheden af\l"
	.string "{STR_VAR_1}.\p"
	.string "{STR_VAR_2}, som du sandsynligvis er\n"
	.string "klar over, er kendt som en POKéMON, der\l"
	.string "er sjælden og svær at finde.\p"
	.string "Det lyder som en sjælden mulighed for at\n"
	.string "se det forbløffende udbrud af\l"
	.string "{STR_VAR_2} i det vilde.\p"
	.string "Det var nyhederne på POKéMON-\n"
	.string "NYHEDERNE.$"

gTV3CheersForPokeblocksText00::
	.string "MC: Vi håber, du er i godt humør, “3\n"
	.string "HURRA FOR {POKEBLOCK}S” er her!\p"
	.string "I dag undersøger vi {POKEBLOCK}'en blandet\n"
	.string "af {STR_VAR_1} og venner.\p"
	.string "Uden yderligere forsinkelse, lad mig\n"
	.string "fodre min gourmet POKéMON GULPIN.\p"
	.string "… … … … … … … … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Og dommen er meget {STR_VAR_1}!\n"
	.string "GULPIN siger, det smager\l"
	.string "“{STR_VAR_2}”!\p"
	.string "Mange tak, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "{STR_VAR_1}s blendingevner lod\n"
	.string "noget tilbage at ønske.\p"
	.string "Hvis denne TRÆNER kunne blande bedre,\n"
	.string "ville {POKEBLOCK}'en være meget mere\l"
	.string "velsmagende.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Hmm… Det er for {STR_VAR_1}.\n"
	.string "GULPIN siger, at det smager\l"
	.string "“{STR_VAR_2}”! \p"
	.string "Det ser ud til, at {STR_VAR_3}'s fejl\n"
	.string "påvirker blandingens kvalitet...$"

gTV3CheersForPokeblocksText04::
	.string "Det er ærgerligt at {STR_VAR_1}'s\n"
	.string "ledende indsats gik til spilde.\p"
	.string "Lad os håbe at {STR_VAR_2} kan\n"
	.string "levere en bedre præstation næste gang!$"

gTV3CheersForPokeblocksText05::
	.string "Følg med næste gang! Vores slogan er “3\n"
	.string "HURRA FOR {POKEBLOCK}S!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Hej med dig!\p"
	.string "Jeg er en stor fan af {STR_VAR_1}.\n"
	.string "Hvad er din mening om {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Jeg forstår, jeg forstår. Det er hvad du\n"
	.string "tænker om TRÆNEREN.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Har du helt glemt om {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Jeg er kæmpe fan af {STR_VAR_1}.\n"
	.string "Hvad er din mening om {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Hvor stærk vil du vurdere\n"
	.string "{STR_VAR_1} på en skala fra ét til\l"
	.string "hundrede?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Har du helt glemt om {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Åh, jeg forstår! Du burde møde\n"
	.string "{STR_VAR_1} en dag. Jeg er sikker på,\l"
	.string "at du også vil blive fan!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Jeg forstår, jeg forstår.\p"
	.string "Tak! Det er meget nyttigt at vide.\p"
	.string "Jeg vil dele denne information med\n"
	.string "andre {STR_VAR_1} fans og diskutere\l"
	.string "det.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Der kommer til at være en TV-special om\n"
	.string "{STR_VAR_1} meget snart.\p"
	.string "Jeg håber, du fanger den!$"

gTVTrainerFanClubSpecialText00::
	.string "TRÆNER FAN KLUB {STR_VAR_1}\n"
	.string "SPECIAL!\p"
	.string "Dette er en speciel præsentation for\n"
	.string "fans af {STR_VAR_1} over hele HOENN!\p"
	.string "I dag stiller vi spørgsmålet, “Hvad\n"
	.string "tænker folk om {STR_VAR_1}?”\p"
	.string "Vi spurgte {STR_VAR_2} som TRÆNER\n"
	.string "repræsentant.\p"
	.string "Vi spurgte, “Hvordan vil du i et ord\n"
	.string "beskrive {STR_VAR_1}?”\p"
	.string "Svaret: “{STR_VAR_3}.”\p"
	.string "Godt klaret, {STR_VAR_2}! Hvilken\n"
	.string "skarp opfattelse!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.” Det\n"
	.string "har en dejlig klang!\p"
	.string "{STR_VAR_2} gav også\n"
	.string "{STR_VAR_1}'s styrke en vurdering\l"
	.string "fra 0 til 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Resultatet var {STR_VAR_3} point!\n"
	.string "Det er virkelig en høj score!\p"
	.string "{STR_VAR_2} må tydeligvis finde\n"
	.string "{STR_VAR_1} meget højt.$"

gTVTrainerFanClubSpecialText02::
	.string "Scoret var {STR_VAR_3} point! Det er\n"
	.string "et ret godt resultat.\p"
	.string "{STR_VAR_2} må tage {STR_VAR_1}\n"
	.string "som en rival.$"

gTVTrainerFanClubSpecialText03::
	.string "Scoret var {STR_VAR_3} point! Det er\n"
	.string "et ret svagt score.\p"
	.string "{STR_VAR_2} må overveje\n"
	.string "{STR_VAR_1} som en simpel hjælper.$"

gTVTrainerFanClubSpecialText04::
	.string "Du fik {STR_VAR_3} point! Det var en\n"
	.string "forfærdelig score.\p"
	.string "{STR_VAR_2} må tage {STR_VAR_1}\n"
	.string "for at være en underordnet.$"

gTVTrainerFanClubSpecialText05::
	.string "Her har I det, venner!\p"
	.string "Jeg tror, vi alle har lært noget nyt om\n"
	.string "{STR_VAR_1}.\p"
	.string "Afslutningsvis vil jeg give jer\n"
	.string "{STR_VAR_2}s ord.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Og nu er tiden inde til…\n"
	.string "NAVNEVURDERINGSSHOWET!\p"
	.string "Jeg spår din POKéMONs skæbne ud fra\n"
	.string "det kaldenavn, du har givet den.\p"
	.string "Jeg har råd at give, og det er nyttige\n"
	.string "råd, jeg tilbyder.\p"
	.string "I dag vil jeg fortolke kaldenavnet\n"
	.string "{STR_VAR_3} tilhørende\l"
	.string "{STR_VAR_1}'s POKéMON\l"
	.string "{STR_VAR_2}.\p"
	.string "Hmhm…\p"
	.string "Hmm… Dette kaldenavn er…$"

gTVNameRaterText01::
	.string "Et kaldenavn, der antyder talent på\n"
	.string "mange forskellige måder.\p"
	.string "Jeg opfordrer denne TRÆNER til at tage\n"
	.string "courage og påtage sig mange\l"
	.string "udfordringer.$"

gTVNameRaterText02::
	.string "Et kaldenavn, der passer perfekt til\n"
	.string "{STR_VAR_1}, TRÆNERENS navn.\p"
	.string "Det antyder, at I vil danne et godt\n"
	.string "partnerskab med præcis timing.$"

gTVNameRaterText03::
	.string "Et kaldenavn passende til en unik\n"
	.string "person af en POKéMON!\p"
	.string "Hvis opdrættet korrekt, vil denne\n"
	.string "POKéMONs unikke karakter trives\l"
	.string "overdrevet!$"

gTVNameRaterText04::
	.string "Et kælenavn, der vil nære omsorgen og\n"
	.string "den medfølende side af POKéMON.\p"
	.string "Hvis den opdrages ordentligt, vil denne\n"
	.string "POKéMON udvise ægte varme!$"

gTVNameRaterText05::
	.string "Et virkelig fint kaldenavn, der antyder\n"
	.string "storhed i vente.\p"
	.string "Jeg er nysgerrig på, hvad fremtiden har\n"
	.string "i vente for denne POKéMON.$"

gTVNameRaterText06::
	.string "Et godt kaldenavn, der bør få POKéMON\n"
	.string "til at være rasende og glade!\p"
	.string "Den POKéMON bør forblive sund og\n"
	.string "robust i lang, lang tid.$"

gTVNameRaterText07::
	.string "Et godt kælenavn, der burde gøre\n"
	.string "POKéMON meget aktivt!\p"
	.string "Jeg burde tænke, at denne POKéMON vil\n"
	.string "være en stærk performer i kampe.$"

gTVNameRaterText08::
	.string "En tiltalende kaldenavn, som burde gøre\n"
	.string "POKéMON'en meget charmerende!\p"
	.string "Jeg tvivler ikke på, at denne POKéMON\n"
	.string "vil være ganske charmerende i POKéMON-\l"
	.string "konkurrencer.$"

gTVNameRaterText09::
	.string "Kaldenavnet {STR_VAR_1} har sin rod\n"
	.string "i bogstavet “{STR_VAR_3}.”\p"
	.string "Det bogstav støttes af det første\n"
	.string "bogstav “{STR_VAR_2},” hvilket giver\l"
	.string "det en solid følelse af tilstedeværelse\l"
	.string "som et kaldenavn.$"

gTVNameRaterText10::
	.string "Kælenavnet {STR_VAR_1} er meget\n"
	.string "smukt på en behagelig måde.\p"
	.string "Tilstedeværelsen af bogstaverne\n"
	.string "“{STR_VAR_2}” og “{STR_VAR_3}” -\l"
	.string "det er virkelig godt!$"

gTVNameRaterText11::
	.string "Kælenavnet {STR_VAR_1}--det har en\n"
	.string "sublim, strømmende fornemmelse til det.\p"
	.string "Overgangen fra det første bogstav\n"
	.string "“{STR_VAR_2}” til “{STR_VAR_3}”\l"
	.string "er specielt vidunderlig.$"

gTVNameRaterText12::
	.string "Lad os undersøge andre eksempler på\n"
	.string "gode kælenavne, skal vi?$"

gTVNameRaterText13::
	.string "Prøv dette eksempel. Tag en del af\n"
	.string "TRÆNER-navnet {STR_VAR_1}, og\l"
	.string "afslut med det fine kælenavn\l"
	.string "{STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "Kælenavnet\n"
	.string "{STR_VAR_2}{STR_VAR_3} ville\l"
	.string "også være ganske godt.$"

gTVNameRaterText15::
	.string "POKéMON'et artens navn til\n"
	.string "{STR_VAR_2} kan bruges som grundlag\l"
	.string "for kaldenavnet\l"
	.string "{STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} ville\n"
	.string "også være en effektiv kaldenavn.$"

gTVNameRaterText17::
	.string "Det, du altid skal undgå, er at bruge et\n"
	.string "andet POKéMON-artsnavn.\p"
	.string "For eksempel, undgå at bruge navnet\n"
	.string "{STR_VAR_2} til at lave kælenavnet\l"
	.string "{STR_VAR_1}{STR_VAR_3}. Det er\l"
	.string "uacceptabelt.$"

gTVNameRaterText18::
	.string "Jeg må sige, at {STR_VAR_1} er et\n"
	.string "rigtig godt kælenavn.\p"
	.string "Jeg håber, at TRÆNEREN vil fortsætte\n"
	.string "med at behandle {STR_VAR_1} med\l"
	.string "kærlighed.\p"
	.string "Det var alt for dagens program. Må vi\n"
	.string "mødes igen.$"

gTVPokemonAnglerText00::
	.string "{STR_VAR_2} FISKER\p"
	.string "VÆRT: Hej! I dag får vi tips til fiskeri\n"
	.string "efter {STR_VAR_2}.\p"
	.string "EKSPERT, hvilke råd kan du give til at\n"
	.string "fange {STR_VAR_2}?\p"
	.string "EKSPERT: Hm? Fange {STR_VAR_2}? Nå,\n"
	.string "lad mig fortælle dig, vær tålmodig og\l"
	.string "vent. Det er det vigtigste.\p"
	.string "Ser du {STR_VAR_1} derovre? Den\n"
	.string "TRÆNER er et godt eksempel.\p"
	.string "Den TRÆNER har allerede haft\n"
	.string "{STR_VAR_3} POKéMON undslippe.\p"
	.string "Men der venter {STR_VAR_1}. Ingen\n"
	.string "opgivelse. Det er reglen for at fange\l"
	.string "{STR_VAR_2}.\p"
	.string "VÆRT: Jeg forstår…\p"
	.string "Åh! {STR_VAR_1} har endelig landet\n"
	.string "en undvigende {STR_VAR_2}!\p"
	.string "TRÆNEREN ser ud til at være tæt på at\n"
	.string "græde af ren glæde!\p"
	.string "Når jeg ser det lykkelige udtryk, får\n"
	.string "jeg lyst til at tage ud og fiske også!\p"
	.string "Seere, hvorfor ikke tage dette som et\n"
	.string "tegn på at prøve lidt\l"
	.string "{STR_VAR_2}-fiskeri?\p"
	.string "Indtil vores næste udsendelse, farvel\n"
	.string "og god fisketur til jer alle!$"

gTVPokemonAnglerText01::
	.string "{STR_VAR_2} FISKER\p"
	.string "VÆRT: Hej! I dag får vi tips til fiskeri\n"
	.string "efter {STR_VAR_2}.\p"
	.string "EKSPERT, hvilke råd kan du give til\n"
	.string "fangst af {STR_VAR_2}?\p"
	.string "EKSPERT: Hm? Fangst af\n"
	.string "{STR_VAR_2}? Nå, lad mig fortælle dig,\l"
	.string "brug din fiskeSTANG med iver!\p"
	.string "Ser du {STR_VAR_1} derovre? Ser du,\n"
	.string "hvordan STANGEN bliver brugt?\p"
	.string "Den TRÆNER har allerede fanget\n"
	.string "{STR_VAR_3} i træk.\p"
	.string "VÆRT: Det er utroligt! Det ligner en\n"
	.string "storm…\p"
	.string "Når man ser en teknik af det kaliber,\n"
	.string "får jeg også lyst til at tage ud og\l"
	.string "fiske. /nSeere, hvorfor ikke tage det\l"
	.string "som et tegn til at prøve lidt\l"
	.string "{STR_VAR_2}-fiskeri?\p"
	.string "Indtil vores næste udsendelse, farvel\n"
	.string "og god fisketur til jer alle!$"

gTVPokemonTodayFailedText00::
	.string "Hej!\p"
	.string "Det er tid til POKéMON I DAG!\p"
	.string "STORE SØSTER: Hej! Er alle skønne og\n"
	.string "glade i dag?\p"
	.string "I dag skal vi kigge på {STR_VAR_1}s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "STORE BROR: Ja! Det er det vi skal!$"

gTVPokemonTodayFailedText01::
	.string "Åh! Når vi taler om {STR_VAR_1}…\p"
	.string "STORE SØSTER, jeg så TRÆNEREN med mine\n"
	.string "egne øjne!\p"
	.string "STORE SØSTER: Hvad så du?\p"
	.string "STORE BROR: Jo, jeg var nødt til at tage\n"
	.string "en tur til {STR_VAR_2}.\p"
	.string "Det var der, jeg tilfældigvis stødte på\n"
	.string "{STR_VAR_1}, der forsøgte at fange\l"
	.string "POKéMON {STR_VAR_3}, men…$"

gTVPokemonTodayFailedText02::
	.string "POKéMONet formåede at undslippe!\p"
	.string "Det endte med at spilde dette ANTAL\n"
	.string "POKéBOLDE: {STR_VAR_2}!\p"
	.string "Du skulle have set udtrykket af\n"
	.string "frustration på {STR_VAR_1}s ansigt\l"
	.string "da POKéMONet løb væk!$"

gTVPokemonTodayFailedText03::
	.string "Men {STR_VAR_1} lavede en fejl og\n"
	.string "lod POKéMON falde i svime!\p"
	.string "Det endte med at spilde så mange POKé\n"
	.string "BALLS: {STR_VAR_2}!\p"
	.string "Du skulle have set udtrykket af\n"
	.string "forbløffet forfærdelse på\l"
	.string "{STR_VAR_1}s ansigt da POKéMON'en\l"
	.string "besvimede!$"

gTVPokemonTodayFailedText04::
	.string "STORE SØSTER: Hej du der! Det er ikke\n"
	.string "pænt!\p"
	.string "Man burde ikke grine af andres uheld!\p"
	.string "Åh, stakkels {STR_VAR_1}. Sikke en\n"
	.string "skam!\p"
	.string "STORE BROR: Det er sandt! Undskyld for\n"
	.string "at grine.$"

gTVPokemonTodayFailedText05::
	.string "STORE SØSTER: Bufufu…\p"
	.string "STORE BROR: Hej! Du grinede også!\p"
	.string "STORE SØSTER: Hva'?! \p"
	.string "Jeg grinede ikke! Ærligt, det gjorde jeg\n"
	.string "ikke!\p"
	.string "Åh, stakkels {STR_VAR_1}. Hvad en\n"
	.string "skam!\p"
	.string "STORE BROR: …$"

gTVPokemonTodayFailedText06::
	.string "STORE SØSTER: Nu er det nok fjoller!\n"
	.string "Lad os se på dagens POKéMON…\p"
	.string "Hvad? Vi har allerede løbet tør for tid?\p"
	.string "Åh! Vi kunne ikke profilere en POKéMON i\n"
	.string "dag!\p"
	.string "STORE BROR: Vi ses igen næste gang!\p"
	.string "STORE SØSTER: Hey, afslut ikke\n"
	.string "programmet uden mig!$"

gTVPokemonTodaySuccessfulText00::
	.string "Hej!\p"
	.string "Det er tid til POKéMON I DAG!\p"
	.string "STORE SØSTER: Hej! Er alle glade og\n"
	.string "friske i dag?\p"
	.string "I dag skal vi se på {STR_VAR_1}s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "STORE BROR: Ja! Det er hvad vi skal!$"

gTVPokemonTodaySuccessfulText01::
	.string "STORE SØSTER: {STR_VAR_1} gav\n"
	.string "kælenavnet {STR_VAR_3} til\l"
	.string "{STR_VAR_2}!\p"
	.string "Det lyder som om {STR_VAR_3} bliver\n"
	.string "godt passet og elsket!$"

gTVPokemonTodaySuccessfulText02::
	.string "STOREBROR: Træneren var nødt til at\n"
	.string "kaste så mange POKéBOLDE for at fange\l"
	.string "den: {STR_VAR_3}!\p"
	.string "Endelig tog det kun en enkelt\n"
	.string "{STR_VAR_2} at fange den!$"

gTVPokemonTodaySuccessfulText03::
	.string "STORE SIS: Hvis det var så let at fange,\n"
	.string "må det have været skæbnen, der bragte\l"
	.string "{STR_VAR_1} og {STR_VAR_2}\l"
	.string "sammen!$"

gTVPokemonTodaySuccessfulText04::
	.string "STORE SIS: Ej, hvor sejt!\p"
	.string "Men ved du hvad de siger, en POKéMON\n"
	.string "der kræver en stor indsats at fange,\l"
	.string "fortjener kærligheden fra sin TRÆNER!$"

gTVPokemonTodaySuccessfulText05::
	.string "STORE SØSTER: {STR_VAR_1}s\n"
	.string "{STR_VAR_2} er en mindeværdig\l"
	.string "POKéMON, fordi det krævede en\l"
	.string "uvurderlig MASTER BALL at fange!\p"
	.string "STORE BROR: Wow! Det er mega-fedt!\p"
	.string "STORE SØSTER: {STR_VAR_1} må\n"
	.string "virkelig have ønsket sig den\l"
	.string "{STR_VAR_2}, helt sikkert!$"

gTVPokemonTodaySuccessfulText06::
	.string "STOREBROR: Så at give kælenavnet\n"
	.string "{STR_VAR_3} til den {STR_VAR_2}…\p"
	.string "Du får virkelig en god idé om\n"
	.string "{STR_VAR_1}'s TRÆNER sans.\p"
	.string "STORESØSTER: Jeg er helt enig!$"

gTVPokemonTodaySuccessfulText07::
	.string "Hvis det var op til mig, ville jeg give\n"
	.string "det kælenavnet til noget som dette\l"
	.string "{STR_VAR_3}!\p"
	.string "STOREBROR: Wow! Det kunne være starten\n"
	.string "på noget nyt!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} den {STR_VAR_1}?\n"
	.string "Lyder det ikke perfekt?\p"
	.string "Bogstaverne og det hele--de lyder bare\n"
	.string "rigtige til POKéMON {STR_VAR_1}!\p"
	.string "STORE BRO: Ja, sandt nok!$"

gTVPokemonTodaySuccessfulText09::
	.string "Så vidt jeg ved, har ingen TRÆNER givet\n"
	.string "kælenavnet {STR_VAR_2} til deres\l"
	.string "{STR_VAR_1}!\p"
	.string "STOREBROR: Det viser bare, hvor god\n"
	.string "smag TRÆNEREN har i valg af kælenavne!$"

gTVPokemonTodaySuccessfulText10::
	.string "Næste gang jeg fanger en POKéMON, skal\n"
	.string "jeg kalde den {STR_VAR_2}.\p"
	.string "STOREBROR: Hvad? Mig også! Jeg vil også\n"
	.string "bruge kælenavnet {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "STORE SØSTER: Åh, nej! Se lige tiden!\p"
	.string "Nå, venner, det var alt for i dag. Vi ses\n"
	.string "igen næste gang!\p"
	.string "STORE BROR: Husk, det kunne være din\n"
	.string "POKéMON i rampelyset næste gang!$"

SmartShopper_Text_Intro::
	.string "Hej!\p"
	.string "Det er tid til DAGENS SMARTE INDKØBER.\p"
	.string "INTERVIEWER: Hvordan har I det, seere?\p"
	.string "I dag besøger vi en butik i\n"
	.string "{STR_VAR_2}.\p"
	.string "Lad os se, hvad de populære varer har\n"
	.string "været for nylig.$"

SmartShopper_Text_ClerkNormal::
	.string "Lad os interviewe ekspedienten for at\n"
	.string "få det hele at vide.\p"
	.string "Hej, hvordan går det med din\n"
	.string "forretning?\p"
	.string "EKSPEDIENT: Åh, vi klarer os\n"
	.string "fremragende.\p"
	.string "For nylig har {STR_VAR_2} været\n"
	.string "særligt populær.\p"
	.string "Ja, forleden købte en TRÆNER ved navn\n"
	.string "{STR_VAR_1} {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "INTERVIEWER: TRÆNEREN købte\n"
	.string "{STR_VAR_3} {STR_VAR_2}ER? Det\l"
	.string "er et scoop!\p"
	.string "Hvis jeg må sige det, så må\n"
	.string "{STR_VAR_1} have fyldt op til en lang\l"
	.string "rejse til fjerne egne.\p"
	.string "Når man rejser, er {STR_VAR_2}\n"
	.string "vigtige!$"

SmartShopper_Text_RandomComment2::
	.string "INTERVIEWER: Når vi taler om emnet\n"
	.string "{STR_VAR_2}, købte jeg for nylig\l"
	.string "{STR_VAR_3} af dem.\p"
	.string "Efter alt, {STR_VAR_2} er en\n"
	.string "fantastisk vare!$"

SmartShopper_Text_RandomComment3::
	.string "INTERVIEWER: {STR_VAR_2} ?! Men\n"
	.string "{STR_VAR_3} af dem?! \p"
	.string "Jeg troede ikke, der ville være nogen,\n"
	.string "der købte så mange. \p"
	.string "Min gode gud, jeg har kun råd til en eller\n"
	.string "to ad gangen…$"

SmartShopper_Text_RandomComment4::
	.string "INTERVIEWER: En gang købte jeg en hel\n"
	.string "masse af emnet {STR_VAR_2}.\p"
	.string "Men det viste sig at være for mange. Jeg\n"
	.string "fortrød det... \p"
	.string "Siden da køber jeg kun nøjagtigt hvad\n"
	.string "jeg absolut har brug for... \p"
	.string "Ups!\p"
	.string "Der er ingen grund til at tale om mig!$"

SmartShopper_Text_SecondItem::
	.string "EKSPEDIENT: {STR_VAR_1} købte også\n"
	.string "varen {STR_VAR_2} i stort antal, og\l"
	.string "fik {STR_VAR_3}.\p"
	.string "INTERVIEWER: Åh, dét er smart.\n"
	.string "{STR_VAR_2} er også et meget godt\l"
	.string "valg.$"

SmartShopper_Text_ThirdItem::
	.string "EKSPEDIENT: Og TRÆNEREN købte også\n"
	.string "{STR_VAR_3} af varen\l"
	.string "{STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "EKSPEDIENT: Og så var det under en\n"
	.string "stor udsalg. Det er smart at handle.$"

SmartShopper_Text_OutroNormal::
	.string "INTERVIEWER: Hmm… {STR_VAR_1}\n"
	.string "lyder som en ganske snedig\l"
	.string "tilbuds-jæger!\p"
	.string "I alt løb {STR_VAR_1}'s køb op i…\p"
	.string "¥{STR_VAR_2}?! Det er da en\n"
	.string "fantastisk sum!\p"
	.string "Ups! Tiden er udløbet! Vi ses på vores\n"
	.string "næste udsendelse!$"

SmartShopper_Text_IsVIP::
	.string "EKSPEDIENT: {STR_VAR_1} er en\n"
	.string "VIP-kunde, ingen tvivl om det.$"

SmartShopper_Text_ClerkMax::
	.string "Lad os interviewe ekspedienten for at\n"
	.string "få det hele at vide.\p"
	.string "Hej, hvordan går det med din\n"
	.string "forretning?\p"
	.string "EKSPEDIENT: Åh, vi har en utrolig god\n"
	.string "omsætning. Det er næsten overvældende.\p"
	.string "For nylig købte en TRÆNER ved navn\n"
	.string "{STR_VAR_1} varen {STR_VAR_2} i\l"
	.string "stort antal.\p"
	.string "TRÆNEREN tømte næsten vores hele lager\n"
	.string "af {STR_VAR_2}.\p"
	.string "Jeg drømte aldrig om, at en kunde ville\n"
	.string "få brug for så mange {STR_VAR_2}.\l"
	.string "Det er bare uhørt!\p"
	.string "INTERVIEWER: Så det vil være omkring\n"
	.string "100 eller 200 solgte?\p"
	.string "EKSPEDIENT: Åh, langt mere end det!\p"
	.string "INTERVIEWER: Åh, du store tid!\n"
	.string "{STR_VAR_1} må være en særlig\l"
	.string "shopper!\p"
	.string "EKSPEDIENT: {STR_VAR_1} er en\n"
	.string "VIP-kunde, ingen tvivl om det.$"

SmartShopper_Text_OutroMax::
	.string "INTERVIEWER: Hmm… Det er fantastisk.\p"
	.string "Men hvorfor skulle TRÆNEREN have brug\n"
	.string "for så mange?\p"
	.string "… …\p"
	.string "Mysteriet tykner, men det er alt den\n"
	.string "tid, vi har i dag. Vi ses i vores næste\l"
	.string "udsendelse!\p"
	.string "{STR_VAR_1} er helt sikkert stadig\n"
	.string "en gåde…$"

gTVWorldOfMastersText00::
	.string "VERDENEN FOR MESTRE\p"
	.string "Hej, seere.\p"
	.string "Måske er du bekendt med en TRÆNER ved\n"
	.string "navn {STR_VAR_1}.\p"
	.string "{STR_VAR_1} er berømt som en mester\n"
	.string "i at fange POKéMON.\p"
	.string "{STR_VAR_1}s jagt på POKéMON\n"
	.string "afhænger fuldstændigt af en omhyggelig\l"
	.string "søgning til fods.\p"
	.string "På en mindeværdig dag gik TRÆNEREN\n"
	.string "{STR_VAR_2} skridt.\p"
	.string "Det samlede antal POKéMON fanget den\n"
	.string "dag nåede imponerende {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Den fantastiske bedrift må have været\n"
	.string "mulig på grund af tilliden mellem\l"
	.string "TRÆNEREN og {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Mesteren fangede dagens sidste\n"
	.string "{STR_VAR_3} nær {STR_VAR_2}.\p"
	.string "Denne POKéMON nyder tilsyneladende en\n"
	.string "særlig status som en rekordindehaver.\p"
	.string "Dygtige TRÆNERE bør opfordres til at\n"
	.string "udfordre denne fine rekord.\p"
	.string "Det er alt for i dag. Venligst vend\n"
	.string "tilbage næste gang.$"

gTVTodaysRivalTrainerText00::
	.string "DAGENS RIVALTRÆNER!\p"
	.string "Hej, medtrænere af POKéMON! Hvordan\n"
	.string "har vi det alle sammen i dag?\p"
	.string "I dag, ligesom enhver anden dag, vil vi\n"
	.string "undersøge en af vores rivaler!$"

gTVTodaysRivalTrainerText07::
	.string "Dagens rivalTRÆNER er {STR_VAR_1},\n"
	.string "som er omkring {STR_VAR_3} lige nu.\p"
	.string "{STR_VAR_1} har indtil videre\n"
	.string "registreret {STR_VAR_2} POKéMON i\l"
	.string "POKéDEXen.$"

gTVTodaysRivalTrainerText08::
	.string "Dagens rivalTRÆNER er {STR_VAR_1},\n"
	.string "som er i en HEMMELIG BASE nu.\p"
	.string "{STR_VAR_1} har indtil videre\n"
	.string "registreret {STR_VAR_2} POKéMON i\l"
	.string "POKéDEXEN.$"

gTVTodaysRivalTrainerText09::
	.string "Dagens rival TRÆNER er {STR_VAR_1}.\p"
	.string "Indtil nu har {STR_VAR_1}\n"
	.string "registreret {STR_VAR_2} POKéMON i\l"
	.string "POKéDEXEN.$"

gTVTodaysRivalTrainerText10::
	.string "Dagens rival TRÆNER er {STR_VAR_1},\n"
	.string "som er på en færge nu.\p"
	.string "{STR_VAR_1} har indtil videre\n"
	.string "registreret {STR_VAR_2} POKéMON i\l"
	.string "POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Og hvor mange MÆRKER har vores rival\n"
	.string "nu? Tallet er {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Men vores rival har ikke fået en enkelt\n"
	.string "MÆRKE endnu!$"

gTVTodaysRivalTrainerText03::
	.string "Vores rival har endnu ikke fået en\n"
	.string "KAMPFRONTIER-symbol endnu.$"

gTVTodaysRivalTrainerText04::
	.string "Lad os se, hvor mange BATTLE FRONTIER-\n"
	.string "Symboler vores rival har.\p"
	.string "Guld Symboler: {STR_VAR_1}! Sølv\n"
	.string "Symboler: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Vores rival har samlet {STR_VAR_1}\n"
	.string "Kamp Point(s) ved BATTLE FRONTIER.$"

gTVTodaysRivalTrainerText06::
	.string "Så, hvordan målte du dig sammen med\n"
	.string "{STR_VAR_1}?\p"
	.string "Eventyret fortsætter!\p"
	.string "Kære TRÆNERE!\p"
	.string "Lad os alle blive ved med at bevæge os\n"
	.string "fremad og foran vores rivaler!$"

TrendWatcher_Text_Intro::
	.string "DEWFORD TRENDSÆTTER NETVÆRK!\p"
	.string "MC: Hvad så? Vi holder det ægte med de\n"
	.string "seneste trends og begivenheder i\l"
	.string "DEWFORD.\p"
	.string "Vores gæst i dag er denne gamle kat, der\n"
	.string "har gjort sig kendt som autoriteten\l"
	.string "inden for alt i DEWFORD.\p"
	.string "Gammel mand: Dejligt at være her.\p"
	.string "MC: Lad os komme til sagen, direkte på.\n"
	.string "Hvad siger du til, at der er gang i den\l"
	.string "hos de gode mennesker i DEWFORD?\p"
	.string "Gammel mand: {STR_VAR_1}\n"
	.string "{STR_VAR_2}.\p"
	.string "MC: {STR_VAR_1} {STR_VAR_2},\n"
	.string "siger du?\p"
	.string "Gammel mand: Nej.\p"
	.string "{STR_VAR_1} {STR_VAR_2} blev\n"
	.string "aldrig populært overhovedet.\p"
	.string "Vil du høre om det?\p"
	.string "MC: Øh, nej. Det vi gerne vil vide er,\n"
	.string "hvad der er 'in' i øjeblikket...$"

TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Gamle mand: {STR_VAR_1}\n"
	.string "{STR_VAR_2} var det, som\l"
	.string "{STR_VAR_3} fra LITTLEROOT lærte\l"
	.string "mig at være trendy…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Old man: {STR_VAR_1} {STR_VAR_2}\n"
	.string "er hvad {STR_VAR_3} fra LITTLEROOT\l"
	.string "har lært mig, der er trendy…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Men det var fuldstændig håbløst.\p"
	.string "{STR_VAR_1} {STR_VAR_2}\n"
	.string "festival!\p"
	.string "{STR_VAR_1} {STR_VAR_2}\n"
	.string "konkurrence!\p"
	.string "Jeg prøvede at lære alle det bedste jeg\n"
	.string "kunne, men…\p"
	.string "Måske var {STR_VAR_1} delen bare\n"
	.string "ikke rigtig…\p"
	.string "MC: Øh, undskyld, kammerat, jeg skal\n"
	.string "vide, hvad der er 'ind' lige nu...$"

TrendWatcher_Text_MaleTellMeBigger::
	.string "Gammel mand: {STR_VAR_3}! Vær sød at\n"
	.string "fortælle mig noget større end det\l"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Gammel mand: {STR_VAR_3}! Fortæl mig\n"
	.string "venligst noget større end det\l"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: ...Øh... Så er den der, alle I trendy,\n"
	.string "tjekkede katte derude!\p"
	.string "{STR_VAR_1} {STR_VAR_2}...øh...\n"
	.string "Ikke blev hip eller skete i DEWFORD!\p"
	.string "Min tid er op. Fanger dig på flugt!\p"
	.string "Gammel mand: {STR_VAR_1}\n"
	.string "{STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "HOENN SKATTEUNDERSØGERE!\p"
	.string "Hej, venner! Har I scoret nogle\n"
	.string "hemmelige genstande for nylig?\p"
	.string "Som altid vil vi undersøge\n"
	.string "øjenvidneberetninger om hemmeligheder\l"
	.string "fra hele regionen!\p"
	.string "Lad os begynde med et brev. Det siger,\n"
	.string "“{STR_VAR_1} opdaget!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Wow, vi bør lige se denne besked\n"
	.string "nærmere! Lad mig læse den op.\p"
	.string "…Kære EFTERFORSKERE, Jeg håber, I har\n"
	.string "det godt.\p"
	.string "Jeg så for nylig {STR_VAR_2} et sted\n"
	.string "omkring {STR_VAR_3}.\p"
	.string "TRÆNEREN fandt genstanden\n"
	.string "{STR_VAR_1}. Det gjorde mig\l"
	.string "misundelig.\p"
	.string "…Nå, godt gået, {STR_VAR_2}!\p"
	.string "Seere, lad det motivere jer til at\n"
	.string "starte jeres SØGESTAVE og lede!\p"
	.string "Jeg venter spændt på spændende\n"
	.string "nyheder fra jer alle!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Wow, vi bør nok tjekke dette brev ud!\n"
	.string "Lad mig læse det højt til dig.\p"
	.string "…Kære EFTERFORSKERE, Jeg håber, at I\n"
	.string "har det godt.\p"
	.string "Jeg så for nylig {STR_VAR_2} på en\n"
	.string "færge.\p"
	.string "TRÆNEREN fandt genstanden\n"
	.string "{STR_VAR_1}. Det gjorde mig\l"
	.string "misundelig.\p"
	.string "…Godt klaret, {STR_VAR_2}!\p"
	.string "Seere, lad det motivere jer til at tænde\n"
	.string "jeres TINGFINDERE og lede!\p"
	.string "Jeg venter spændt på spændende\n"
	.string "nyheder fra jer alle!$"

gTVFindThatGamerText00::
	.string "FIND THAT GAMER!\p"
	.string "Hej allesammen gamere! Hvordan spinner\n"
	.string "din {STR_VAR_2}? \p"
	.string "Som altid vil vi rette vores\n"
	.string "opmærksomhed mod en sjælden TRÆNERsom\l"
	.string "har besøgt SPILLEHJØRNET!\p"
	.string "I dag er vores nr. 1 gamer…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} spillede\n"
	.string "{STR_VAR_2}-spillet og vandt\l"
	.string "sjældne {STR_VAR_3} MØNTER.\p"
	.string "”Når {STR_VAR_1} kommer, skal vi\n"
	.string "sørge for, at vi har nok MØNTER.”\p"
	.string "Det er det, GAME CORNER kassererne\n"
	.string "mumler, når vores gamer spiller!\p"
	.string "Seere, det er bedst at holde øje med\n"
	.string "dine MØNTER som {STR_VAR_1}, hvis du\l"
	.string "besøger GAME CORNER og spiller\l"
	.string "{STR_VAR_2}-spillet.\p"
	.string "Dette er live fra GAME CORNER- hvor du\n"
	.string "kan mærke spændingen!\p"
	.string "Det var alt for i dag!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} spillede det\n"
	.string "{STR_VAR_2} spil og tabte\l"
	.string "{STR_VAR_3} MØNTER.\p"
	.string "“Når {STR_VAR_1} kommer, ser det ud\n"
	.string "til, at vores MØNT-salg stiger.”\p"
	.string "Det siger spilhjørnets ekspedienter,\n"
	.string "når vores gamer spiller!$"

gTVFindThatGamerText03::
	.string "Seerne, det er bedst at holde øje med\n"
	.string "dine MØNTER som {STR_VAR_1}, hvis du\l"
	.string "besøger SPILLEHJØRNET og spiller\l"
	.string "{STR_VAR_2}-spillet.\p"
	.string "Dette er live fra SPILLEHJØRNET-- hvor\n"
	.string "du kan føle spændingen!\p"
	.string "Det var alt for i dag!$"

gTVBreakingNewsText00::
	.string "VIGTIGT NYHEDER TV!$"

gTVBreakingNewsText01::
	.string "Sjælden {STR_VAR_2} fanget af\n"
	.string "{STR_VAR_1}!\p"
	.string "Vi er live fra området omkring\n"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1} fangede med succes en\n"
	.string "sjælden {STR_VAR_2} tidligere her!$"

gTVBreakingNewsText02::
	.string "Da {STR_VAR_1} stødte på den\n"
	.string "sjældne {STR_VAR_2}, sendte\l"
	.string "TRÆNEREN POKéMON {STR_VAR_3} ud.$"

gTVBreakingNewsText03::
	.string "I kampen blev antallet af POKé BOLD\n"
	.string "kastet af TRÆNEREN {STR_VAR_1}.\p"
	.string "Til sidst blev den sjældne POKéMON\n"
	.string "fanget af {STR_VAR_2} brugt sidst.$"

gTVBreakingNewsText04::
	.string "I det øjeblik fyldtes {STR_VAR_2}\n"
	.string "med {STR_VAR_1}'s brøl af\l"
	.string "triumferende glæde.\p"
	.string "Jeg må indrømme, at jeg er lidt\n"
	.string "misundelig på {STR_VAR_1}. Jeg ville\p"
	.string "også elske at brøle.\p"
	.string "…Det afslutter liveoptagelsen fra den\n"
	.string "glade scene!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} mislykkes med at fange\n"
	.string "en sjælden {STR_VAR_2}!\p"
	.string "Vi er live fra nærheden af\n"
	.string "{STR_VAR_3}!\p"
	.string "Det var her, at {STR_VAR_1}\n"
	.string "mislykkedes med at fange en sjælden\l"
	.string "{STR_VAR_2}!$"

gTVBreakingNewsText06::
	.string "Da {STR_VAR_1} stødte på den\n"
	.string "sjældne {STR_VAR_2}, sendte\l"
	.string "TRÆNEREN POKéMON {STR_VAR_3} ud.$"

gTVBreakingNewsText07::
	.string "TRÆNEREN fik {STR_VAR_2} til at\n"
	.string "bruge trækket {STR_VAR_1}.\p"
	.string "Uden at ville det, fik TRÆNEREN den\n"
	.string "sjældne POKéMON til at besvime…$"

gTVBreakingNewsText12::
	.string "Dog, fik {STR_VAR_1} panik  ved\n"
	.string "synet af den sjældne {STR_VAR_2}.\p"
	.string "Forvirret beordrede TRÆNEREN\n"
	.string "{STR_VAR_3} til angreb.\p"
	.string "Uden at ville det, lod TRÆNEREN den\n"
	.string "sjældne POKéMON blive svag.$"

gTVBreakingNewsText08::
	.string "I samme øjeblik genlød {STR_VAR_2}\n"
	.string "med {STR_VAR_1}s skrig af\l"
	.string "frustration...$"

gTVBreakingNewsText09::
	.string "Dog løb {STR_VAR_1} tør for POKé\n"
	.string "BOLDE.\p"
	.string "TRÆNEREN måtte afbryde kampen med den\n"
	.string "sjældne {STR_VAR_2}.\p"
	.string "I samme øjeblik fyldtes {STR_VAR_3}\n"
	.string "af {STR_VAR_1}'s skrig af\l"
	.string "frustration…$"

gTVBreakingNewsText10::
	.string "Dog flygtede {STR_VAR_2} uden\n"
	.string "advarsel.\p"
	.string "I samme øjeblik fyldtes {STR_VAR_3}\n"
	.string "af {STR_VAR_1}s skrig af\l"
	.string "frustration…$"

gTVBreakingNewsText11::
	.string "Jeg må sige, jeg føler med\n"
	.string "{STR_VAR_1}. Hvorfor, det får også\l"
	.string "mig til at skrige.\p"
	.string "...Det afslutter den live feed fra det\n"
	.string "melankolske scene!$"

gTVSecretBaseVisitText00::
	.string "Hej, venner! Det er tid til et BESØG I\n"
	.string "DEN HEMMELIGE BASE.\p"
	.string "I dag besøger vi DEN HEMMELIGE BASE til\n"
	.string "{STR_VAR_1}.\p"
	.string "Hvordan har {STR_VAR_1} tilpasset\n"
	.string "DEN HEMMELIGE BASE?\p"
	.string "Det finder vi ud af! … … … … … …$"

gTVSecretBaseVisitText01::
	.string "Åh! Hvor vidunderligt!\p"
	.string "Denne {STR_VAR_2}... Det er ikke\n"
	.string "hvad man ville forvente at finde her!$"

gTVSecretBaseVisitText02::
	.string "Åh! Hvor bemærkelsesværdigt!\p"
	.string "Der er ikke et eneste stykke møbel eller\n"
	.string "interiør!\p"
	.string "Almindelige dødelige kunne ikke drømme\n"
	.string "om at efterligne denne dristige\l"
	.string "erklæring!\p"
	.string "Det er enkelt, men det svulmer, ja,\n"
	.string "svulmer af vildskab!\p"
	.string "Mit hat af for dig, {STR_VAR_1}. Det\n"
	.string "måtte være dig!$"

gTVSecretBaseVisitText03::
	.string "Åh! Jeg ser! Med fuldkommen klarhed ser\n"
	.string "jeg det!\p"
	.string "Det {STR_VAR_2} er her… Det sender\n"
	.string "en effektiv besked!$"

gTVSecretBaseVisitText04:: 
	.string "Åh! Jeg ser!\n"
	.string "Med fuldstændig klarhed ser jeg det!\p"
	.string "Dette rum er bevidst holdt tomt\n"
	.string "for indvendige genstande!\p"
	.string "Det sender en effektiv besked!$"

gTVSecretBaseVisitText05::
	.string "Wheeew!\p"
	.string "The pairing of the {STR_VAR_2} with\n"
	.string "the {STR_VAR_3}!\p"
	.string "It's a dream combination if there ever\n"
	.string "was one!$"

gTVSecretBaseVisitText06::
	.string "Huuuj!\p"
	.string "Placeringen af dette {STR_VAR_2}\n"
	.string "lige her…\p"
	.string "Det har en tilstedeværelse, som fylder\n"
	.string "hele DEN HEMMELIGE BASE!$"

gTVSecretBaseVisitText07::
	.string "Iiiihaa!\p"
	.string "Der er ikke noget her.\p"
	.string "Dette tomme rum har en effekt på hele\n"
	.string "DEN HEMMELIGE BASE.$"

gTVSecretBaseVisitText08::
	.string "Åh! Her kommer {STR_VAR_1}! Lad os\n"
	.string "udfordre TRÆNEREN!\p"
	.string "… … … … … … … … … … … …$"

gTVSecretBaseVisitText09::
	.string "Åh… Jeg må virkelig give {STR_VAR_1}\n"
	.string "en klap på skulderen.\p"
	.string "TRÆNERENS POKéMON var virkelig værdige\n"
	.string "til at bære CHAMPION- titlen.\p"
	.string "De gav rigelig bevis på {STR_VAR_1}s\n"
	.string "styrke som TRÆNER.\p"
	.string "At {STR_VAR_2} vidste angrebet\n"
	.string "{STR_VAR_3}…\p"
	.string "Det viser hvilken slags TRÆNER\n"
	.string "{STR_VAR_1} er.\p"
	.string "Det var helt sikkert en god lektion!$"

gTVSecretBaseVisitText10::
	.string "Åhøj! Skal vi ikke lige give\n"
	.string "{STR_VAR_1} en high five?\p"
	.string "TRÆNERENS POKéMON var monster svære!\p"
	.string "De beviste virkelig {STR_VAR_1}s\n"
	.string "udholdenhed som TRÆNER.\p"
	.string "At {STR_VAR_2} kendte angrebet\n"
	.string "{STR_VAR_3}…\p"
	.string "Det viser, hvilken slags TRÆNER\n"
	.string "{STR_VAR_1} er.\p"
	.string "Det var virkelig en lektion i sig selv!$"

gTVSecretBaseVisitText11::
	.string "Wiiii! Jeg må give {STR_VAR_1} en\n"
	.string "high five.\p"
	.string "TRÆNERENS POKÉMON blev tydeligvis\n"
	.string "opdrættet på en balanceret måde.\p"
	.string "De vidnede tydeligt om {STR_VAR_1}s\n"
	.string "omsorg som TRÆNER.\p"
	.string "At {STR_VAR_2} kendte angrebet\n"
	.string "{STR_VAR_3}…\p"
	.string "Det siger noget om, hvilken slags\n"
	.string "TRÆNER {STR_VAR_1} er.\p"
	.string "Det var helt sikkert en vigtig lektion!$"

gTVSecretBaseVisitText12::
	.string "Nå, nå! Jeg må give det til\n"
	.string "{STR_VAR_1}.\p"
	.string "TRÆNERENS POKéMON viste stor lokkende\n"
	.string "for fremtidig vækst.\p"
	.string "De repræsenterede {STR_VAR_1}s håb\n"
	.string "og drømme.\p"
	.string "At {STR_VAR_2} kendte angrebet\n"
	.string "{STR_VAR_3}…\p"
	.string "Viser, hvilken slags TRÆNER\n"
	.string "{STR_VAR_1} er.\p"
	.string "Det var helt sikkert en lektion!$"

gTVSecretBaseVisitText13::
	.string "Jeg må sige, for en fantastisk HEMMELIG\n"
	.string "BASE det var!\p"
	.string "Seere, hvis I får chancen, besøg endelig\n"
	.string "{STR_VAR_1}s HEMMELIGE BASE.\p"
	.string "Indtil næste gang, siger jeg farvel!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Det er spændende! Det er dramatisk!\p"
	.string "Det er POKéMON LOTTERIET VINDER FLASH\n"
	.string "RAPPORT!\p"
	.string "Hej! Vi kommer til dig live fra POKéMON\n"
	.string "LOTTERIET på stueetagen i LILYCOVE\l"
	.string "DEPARTMENT STORE!\p"
	.string "Som det altid sker, kom en anden heldig\n"
	.string "TRÆNER frem i dag!\p"
	.string "Den TRÆNERS navn er... {STR_VAR_1}!\p"
	.string "{STR_VAR_1} vandt {STR_VAR_2}\n"
	.string "præmien og tog {STR_VAR_3} med hjem!\p"
	.string "{STR_VAR_1}! Tillykke!\p"
	.string "Seere, bare se ikke med, vær en del af\n"
	.string "handlingen!\p"
	.string "Vi hos LILYCOVE DEPARTMENT STORE\n"
	.string "glæder os til dit næste besøg!\p"
	.string "Dette har været en live transmission\n"
	.string "fra LILYCOVE DEPARTMENT STORE, der\l"
	.string "tilbyder dig det bedste udvalg i hele\l"
	.string "HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "POKéMONKAMPSEMINAR!\p"
	.string "Vi undersøger kampe for at se, hvad vi\n"
	.string "kan lære af andre.\p"
	.string "Dagens case-studie er på\n"
	.string "{STR_VAR_1}s kamp.\p"
	.string "{STR_VAR_1}s {STR_VAR_2}\n"
	.string "kæmpede mod én {STR_VAR_3}...$"

gTVThePokemonBattleSeminarText01::
	.string "Og den brugte angrebet {STR_VAR_3}\n"
	.string "på {STR_VAR_2}...\p"
	.string "Hmm... {STR_VAR_1}! Det er det\n"
	.string "forkerte at gøre!$"

gTVThePokemonBattleSeminarText02::
	.string "Udover det dømte træk, kendte\n"
	.string "TRÆNERENS {STR_VAR_1} også$"

gTVThePokemonBattleSeminarText03::
	.string "bevægelserne {STR_VAR_1},\n"
	.string "{STR_VAR_2}, og {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "bevægelserne {STR_VAR_1} og\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "trækket {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Så, i denne situation, hvad burde\n"
	.string "TRÆNEREN have brugt?\p"
	.string "… … … … … … Atakken {STR_VAR_1}!\p"
	.string "Atakken {STR_VAR_1} ville have\n"
	.string "været absolut bedre end {STR_VAR_2}.\p"
	.string "Seere, jeg opfordrer jer til at lære af\n"
	.string "dette tilfælde og kæmpe med intelligens!\p"
	.string "Indtil næste gang, farvel!$"

gTVTrainerFanClubText00::
	.string "Alle sammen nu! TRÆNER FAN KLUB!\p"
	.string "MC: Hvordan går det alle sammen? I dag\n"
	.string "har vi samlet fansene af den\l"
	.string "hyper-populære TRÆNER {STR_VAR_1}!\p"
	.string "FANS: Wrooooooaaaaah!\p"
	.string "FANS: {STR_VAR_1}!\p"
	.string "MC: Alle sammen! Hvad synes I om\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "FANS: Deres seje måde at kaste POKé\n"
	.string "BOLDE!$"

gTVTrainerFanClubText02::
	.string "FANS: Deres søde måde at løbe på!$"

gTVTrainerFanClubText03::
	.string "FANS: Hvordan TRÆNEREN bliver sej,  når\n"
	.string "det bliver svært!$"

gTVTrainerFanClubText04::
	.string "FANS: Trænerens viden om POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: TRÆNERENS venlighed overfor alle\n"
	.string "POKéMON!$"

gTVTrainerFanClubText06::
	.string "FANS: TRÆNERENS fantastiske\n"
	.string "cykelkørselsteknikker!$"

gTVTrainerFanClubText07::
	.string "FANS: TRÆNERENS imponerende stil med\n"
	.string "at købe ting!$"

gTVTrainerFanClubText08::
	.string "FANS: TRÆNERENS charmerende måde at\n"
	.string "give POKéMON kælenavne!$"

gTVTrainerFanClubText09::
	.string "FANS: TRÆNERENS smarte måde at\n"
	.string "dekorerer en HEMMELIG BASE!$"

gTVTrainerFanClubText10::
	.string "FANS: TRÆNERENS modige måder at bruge\n"
	.string "TMs!$"

gTVTrainerFanClubText11::
	.string "MC: Som du lige har set, er\n"
	.string "{STR_VAR_1} en hottie! Så hot, at man\l"
	.string "ikke kan røre ved det, wow!\p"
	.string "Blandt {STR_VAR_1}s FANS er der en\n"
	.string "speciel slogan!\p"
	.string "MC: Når jeg siger {STR_VAR_1}, siger\n"
	.string "I…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Præcis, når nogen siger,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Svar tilbage med, “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Det har en helt unik klang! Jeg kan godt\n"
	.string "forstå, hvorfor folk bliver FANS af\l"
	.string "{STR_VAR_1}!\p"
	.string "Okay, dig foran fjernsynet, kom med!\n"
	.string "Alle sammen nu!\p"
	.string "MC: Når jeg siger {STR_VAR_1}, siger\n"
	.string "I…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Tak fordi I var med, alle I vilde\n"
	.string "FANS af {STR_VAR_1}! Det var showet!\l"
	.string "Vi ses!\p"
	.string "MC: Når jeg siger {STR_VAR_1}, siger\n"
	.string "I…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "FIND DE SMÅ VENNER! POKéMON MED\n"
	.string "SLØJFER!\p"
	.string "Hej, mine søde seere!\p"
	.string "Jeg er sikker på, I er enige, men en\n"
	.string "POKéMON med SLØJFER er simpelthen\l"
	.string "guddommelig!\p"
	.string "I dag vil jeg dele med jer en dejlig\n"
	.string "POKéMON, jeg så, da jeg var ude at gå tur\l"
	.string "i byen.\p"
	.string "Dagens smukke POKéMON er\n"
	.string "{STR_VAR_1}s {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Antallet af BÅND, som {STR_VAR_2}\n"
	.string "har på, er {STR_VAR_3}.\p"
	.string "Det siger meget om, hvor meget\n"
	.string "{STR_VAR_1} beundrer POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} bærer nogle\n"
	.string "fantastiske {STR_VAR_3} RIBBONER!\p"
	.string "Det siger en hel del om {STR_VAR_1}s\n"
	.string "dedikation til POKéMON!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} bærer utrolige\n"
	.string "{STR_VAR_3} BÅND!\p"
	.string "Det viser dig {STR_VAR_1}s totale\n"
	.string "dedikation som en samler!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Lad os tage et nærmere kig på de mange\n"
	.string "SLØJFER, som {STR_VAR_2} bærer.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "MESTERBÅNDEN er særligt charmerende.\p"
	.string "{STR_VAR_2} modtog det, da han\n"
	.string "trådte ind i BERØMMELSENS HAL.\p"
	.string "Det fremkalder virkelig modet hos\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} og MESTERBÅNDEN!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Den FEDTE RIBBON er særlig sej.\p"
	.string "{STR_VAR_2} fik den for at vinde en\n"
	.string "FED KONKURRENCE.\p"
	.string "Den fremhæver virkelig {STR_VAR_2}s\n"
	.string "sejhed.\p"
	.string "{STR_VAR_2} og FEDTE RIBBON!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "SKØNHEDSBÅNDET er særligt\n"
	.string "tiltrækkende.\p"
	.string "{STR_VAR_2} modtog det for at vinde\n"
	.string "en SKØNHEDSKONKURRENCE.\p"
	.string "Det fremhæver virkelig skønheden hos\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} og SKØNHEDSBÅNDET!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "DET SØDE BÅND er især charmerende.\p"
	.string "{STR_VAR_2} fik det for at vinde en\n"
	.string "SØD KONKURRENCE.\p"
	.string "Det fremhæver virkelig sødheden hos\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} og DET SØDE BÅND!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Den SMART RIBBON er specielt lækker.\p"
	.string "{STR_VAR_2} modtog den for at vinde\n"
	.string "en SMART KONKURRENCE.\p"
	.string "Den fremhæver virkelig {STR_VAR_2}s\n"
	.string "klogskab.\p"
	.string "{STR_VAR_2} og den SMART RIBBON!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Den SEJE BÅND er især forrygende.\p"
	.string "{STR_VAR_2} fik det for at vinde en\n"
	.string "SEJ KONKURRENCE.\p"
	.string "Det fremhæver virkelig sejhed hos\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} og det SEJE BÅND!\n"
	.string "Kombinationen er super effektiv!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Den VINDENDE SLØJFE er særligt\n"
	.string "charmerende.\p"
	.string "{STR_VAR_2} modtog den for sine\n"
	.string "bedrifter i KAMPENS TÅRN.\p"
	.string "Den fremhæver sandelig styrken hos\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} og den VINDENDE\n"
	.string "SLØJFE! Kombinationen er super\l"
	.string "effektiv!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "SEJRSMASKEN er særligt fornem. Fletter\n"
	.string "du ikke de rigtige bånd?\p"
	.string "{STR_VAR_2} modtog den for sine\n"
	.string "bedrifter i KAMPENS TÅRN.\p"
	.string "Den fremhæver virkelig styrken hos\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} og SEJRSMASKEN! Den\n"
	.string "kombination er super effektiv!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Kunstnerbåndet er virkelig super flot.\p"
	.string "{STR_VAR_2} fik det, fordi han var\n"
	.string "model for en kunstner.\p"
	.string "Det fremhæver virkelig popstjernens\n"
	.string "charme hos {STR_VAR_2}.\p"
	.string "{STR_VAR_2} og Kunstnerbåndet! Den\n"
	.string "kombination er super effektiv!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Den Hårde Arbejder RIBBON er helt\n"
	.string "speciel smuk.\p"
	.string "{STR_VAR_2} modtog den for at være\n"
	.string "en særligt dedikeret arbejder.\p"
	.string "Den fremhæver virkelig {STR_VAR_2}s\n"
	.string "determinationskraft.\p"
	.string "{STR_VAR_2} og Den Hårde Arbejder\n"
	.string "RIBBON! Kombinationen er super\l"
	.string "effektiv!$"

TVSpotTheCuties_Text_Outro::
	.string "…Suk…\p"
	.string "SLØJFER og POKéMON… De passer så\n"
	.string "skønt sammen!\p"
	.string "Inden jeg svimler, siger jeg farvel til\n"
	.string "jer!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Hej! Det er tid til POKéMON-NYHEDER.\p"
	.string "Vi har nogle opmuntrende nyheder fra\n"
	.string "BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-sejr-stime rekord mens\l"
	.string "han var på KAMP TÅRNETS SINGLE KAMP\l"
	.string "RUM udfordring.\p"
	.string "Hip hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "Den TRÆNER {STR_VAR_1} satte en\n"
	.string "{STR_VAR_2}-sejr-stime rekord, mens\l"
	.string "han var på BATTLE TOWER's DOUBLE\l"
	.string "BATTLE ROOM udfordring.\p"
	.string "Sådan, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-vind-stime rekord mens\l"
	.string "han var på BATTLE TOWER's MULTI BATTLE\l"
	.string "ROOM udfordring.\p"
	.string "Skål for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "TRÆNEREN {STR_VAR_1} har sat en ny\n"
	.string "{STR_VAR_2}-vind-stime rekord mens\l"
	.string "han var på BATTLE TOWER's LINK MULTI\l"
	.string "BATTLE ROOM-udfordringen.\p"
	.string "Tillykke til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "Træneren {STR_VAR_1} har sat en ny\n"
	.string "{STR_VAR_2}-mesterskabsrekord i\l"
	.string "SINGLE BATTLE-turneringer i BATTLE\l"
	.string "DOME.\p"
	.string "Hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "Den TRÆNER {STR_VAR_1} satte en\n"
	.string "{STR_VAR_2}-mesterskabsrekord og\l"
	.string "konkurrerede i BATTLE DOME's DOUBLE\l"
	.string "BATTLE-turneringer.\p"
	.string "Hip hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "Den TRÆNER {STR_VAR_1} satte en\n"
	.string "{STR_VAR_2}-sejr-stime rekord mens\l"
	.string "han var på KAMPFABRIKENS Kamp Byt\l"
	.string "Enkelt udfordring.\p"
	.string "Sådan, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-vind-stime rekord mens\l"
	.string "de var på KAMPFABRIK- LENs Battle Swap\l"
	.string "Double udfordring.\p"
	.string "Her er til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "rekord ved at rydde {STR_VAR_2}\l"
	.string "lokaler under BATTLE PIKE's Battle\l"
	.string "Choice udfordring.\p"
	.string "Hip hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "Træneren {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-vinstime-rekord mens\l"
	.string "han kæmpede i KAMPARENAENS Set KO\l"
	.string "Turnering.\p"
	.string "Hip hip hurra for {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-sejr-stime mens ved\l"
	.string "BATTLE PALACE's ENESTE KAMP SAL\l"
	.string "udfordring.\p"
	.string "Her er til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "Den TRÆNER {STR_VAR_1} satte en ny\n"
	.string "{STR_VAR_2}-vinstime-rekord mens\l"
	.string "han var på BATTLE PALACE's DOUBLE\l"
	.string "BATTLE HALL udfordring.\p"
	.string "Tillykke til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "TRÆNEREN {STR_VAR_1} satte en ny\n"
	.string "rekord ved at rydde {STR_VAR_2}\l"
	.string "etager mens de var på BATTLE\l"
	.string "PYRAMIDENS Battle Quest-udfordring.\p"
	.string "Her er til {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Og til de tre POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, og {STR_VAR_3}!\p"
	.string "Tillykke med jeres rekordbrydende\n"
	.string "præstation!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Og til de to POKéMON, {STR_VAR_1} og\n"
	.string "{STR_VAR_2}!\p"
	.string "Tillykke med jeres rekordbrydende\n"
	.string "præstation!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Og til de fire POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Og {STR_VAR_1}!\p"
	.string "Tillykke med din rekordbrydende\n"
	.string "præstation!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Lad os håbe på flere rekordsættende\n"
	.string "bedrifter fra {STR_VAR_1} og de\l"
	.string "loyale POKéMON!\p"
	.string "Det var nyhederne fra POKéMON NEWS!$"

gTVWhatsNo1InHoennTodayText00::
	.string "HVAD ER NR. 1 I HOENN I DAG? Ja, det er\n"
	.string "den tid igen!\p"
	.string "Hej, seere! Giver I jeres bedste i alt,\n"
	.string "hvad I laver?\p"
	.string "Lad os se på TRÆNEREN, der gjorde det\n"
	.string "allerbedst i dag!\p"
	.string "Dagens nr. 1 TRÆNER er ingen anden end\n"
	.string "{STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "På én dag drejede {STR_VAR_1} SLOTS\n"
	.string "på SPILLEHALLEN {STR_VAR_2} gange.\p"
	.string "Mens hun spillede, kunne man høre\n"
	.string "{STR_VAR_1} mumle, “For mig bevæger\l"
	.string "hjulene sig ikke engang…” Er det ikke\l"
	.string "interessant?$"

gTVWhatsNo1InHoennTodayText02::
	.string "På én dag spillede {STR_VAR_1}.\n"
	.string "ROULETTE-spillet i spilleHJØRNET\l"
	.string "{STR_VAR_2} gange.\p"
	.string "Mens {STR_VAR_1} spillede, råbte\n"
	.string "vedkommende, ”Lad boldene bestemme!”\p"
	.string "TRÆNERENs øjne var fokuserede og\n"
	.string "ansigtet udviste koncentration.$"

gTVWhatsNo1InHoennTodayText03::
	.string "I løbet af én dag kæmpede\n"
	.string "{STR_VAR_1} mod vilde POKéMON\l"
	.string "{STR_VAR_2} gange!\p"
	.string "{STR_VAR_1}'s POKéMON ser ud til at\n"
	.string "være blevet utroligt stærkere.\p"
	.string "De ser ud til at være ivrige efter at\n"
	.string "kæmpe overalt, hele tiden og på alle\l"
	.string "måder!$"

gTVWhatsNo1InHoennTodayText04::
	.string "På bare én dag snurrede {STR_VAR_1}\n"
	.string "BÆRBLANDEREN {STR_VAR_2} gange!\p"
	.string "Mod slutningen virkede selv\n"
	.string "{STR_VAR_1} som om han blev svimmel.\p"
	.string "TRÆNEREN så ud til at vakle rundt som\n"
	.string "en SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "På bare een dag plantede\n"
	.string "{STR_VAR_1} {STR_VAR_2} BÆR!\p"
	.string "Som følge heraf blev\n"
	.string "{STR_VAR_1}støj beskidt med snavs.\p"
	.string "Hvor TRÆNEREN plantede, er derspiret\n"
	.string "utallige blomster frem.\p"
	.string "Blomsterne siges at beroligefolks\n"
	.string "følelser.$"

gTVWhatsNo1InHoennTodayText06::
	.string "På bare én dag plukkede {STR_VAR_1}\n"
	.string "{STR_VAR_2} BÆR!\p"
	.string "{STR_VAR_1}s RYGSÆK blev så fyldt\n"
	.string "med BÆR, at TRÆNEREN havde svært ved at\l"
	.string "gå bagefter!$"

gTVWhatsNo1InHoennTodayText07::
	.string "På bare én dag fik {STR_VAR_1}\n"
	.string "{STR_VAR_2} Kamp Point!\p"
	.string "{STR_VAR_1} blev senere set kæmpe\n"
	.string "med valget mellem at ombytte Kamp Point\l"
	.string "for en fed ting eller en smart\l"
	.string "indretningsgenstand.\p"
	.string "TRENEREN blev angiveligt set grinende\n"
	.string "mens han vendte mulighederne.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Nå, er det ikke noget!\p"
	.string "{STR_VAR_1}! Du er dagens nr. 1\n"
	.string "TRÆNER!\p"
	.string "Seere, lad jer inspirere af\n"
	.string "{STR_VAR_1}! Også du kan være nr. 1\l"
	.string "hver dag!$"

TVSecretBaseSecrets_Text_Intro::
	.string "HEMLIG BASE HEMMELIGHEDER!\p"
	.string "Hvad laver TRÆNERE i hemmelighed i\n"
	.string "HEMMELIGE BASER?\p"
	.string "I dag undersøger vi {STR_VAR_1}s\n"
	.string "HEMMELIGE BASE.\p"
	.string "Åh? Ser ud til at {STR_VAR_2} er\n"
	.string "kommet på besøg.\p"
	.string "Lad os tage et kig!\p"
	.string "Hvad vil {STR_VAR_2} gøre?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Hvad vil {STR_VAR_2} gøre nu?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Og nu, hvad vil {STR_VAR_2} gøre?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Til sidst tog {STR_VAR_2}\n"
	.string "{STR_VAR_3} skridt i\l"
	.string "{STR_VAR_1}s HEMMELIGE BASE før han\l"
	.string "forlod.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "Det ser ud til, at {STR_VAR_1}s\n"
	.string "HEMMELIGE BASE ikke fangede\l"
	.string "{STR_VAR_2}s interesse…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} ser ud til at have haft\n"
	.string "en god tid i {STR_VAR_1}s HEMMELIGE\l"
	.string "BASE.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} synes at være blevet en\n"
	.string "kæmpe fan af {STR_VAR_1}'s HEMSLIGE\l"
	.string "BASE.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Seerne kan måske have lyst til at\n"
	.string "besøge {STR_VAR_1} HEMMELIGE BASE\l"
	.string "også.\p"
	.string "Bliv hængende til næste gang, hvor vi\n"
	.string "besøger en anden HEMMELIG BASE! Tak\l"
	.string "fordi I fulgte med!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Besøgende er stoppet!\p"
	.string "Besøgende bevæger sig ikke!\p"
	.string "Var {STR_VAR_1}s HEMMELIGE BASE så\n"
	.string "uimponerende?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Besøgende er stoppet!\p"
	.string "Besøgende bevæger sig ikke!\p"
	.string "Er det træthed? Mon besøgende er\n"
	.string "blevet træt?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Besøgende satte sig på en stol!\n"
	.string "Besøgende er nu siddende!\p"
	.string "Se den glæde i øjnene!\p"
	.string "Den stol må være meget behagelig for at\n"
	.string "få den reaktion!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Besøgeren angreb en ballon!\p"
	.string "Den sprang! Åh, du godeste, den\n"
	.string "poppede!\p"
	.string "Besøgeren ser ud til at blive\n"
	.string "forskrækket af den pludselige støj!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Besøgende kom ind i et TELT!\p"
	.string "Besøgende løber rundt!\p"
	.string "Åh, åh, besøgende leger!\p"
	.string "Besøgende virker overrasket over\n"
	.string "størrelsen på TELTET!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Besøgende undersøger en potteplante!\p"
	.string "Besøgende har overraskende moden\n"
	.string "smag!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Besøgende undersøger et GULD SKJOLD!\p"
	.string "Besøgendes øjne lyser op af beundring!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Besøgende undersøger et SØLVSKJOLD!\p"
	.string "Besøgende ser ud til at være storøjede!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Besøgende undersøger en\n"
	.string "GLASORNAMENT!\p"
	.string "Åh nej!\p"
	.string "Besøgende rører ved den!\p"
	.string "Den bliver dækket af fingeraftryk…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Besøgende ser fjernsyn!\p"
	.string "Det ser ud til, at vi har en stor fan af\n"
	.string "TV!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Besøgende trådte på en MUDDBOLD!\p"
	.string "Besøgende ser begejstret ud!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Åh?\p"
	.string "Besøgende når ned i deres egen taske\n"
	.string "og roder rundt i den!\p"
	.string "Besøgende trak en {STR_VAR_2} frem!\p"
	.string "Se besøgende smile mens de holder\n"
	.string "{STR_VAR_2} op!\p"
	.string "Det er ligesom en TV-reklame!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "The visitor grabs a cushion and…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…begynder at slå løs på den!\p"
	.string "Er besøgende under meget stress?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…krammer den hårdt!\p"
	.string "Mon besøgende føler sig glad over\n"
	.string "noget?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Besøgeren chatter med {STR_VAR_1}!\p"
	.string "Det ser ud til, at de skal kæmpe!\p"
	.string "Og...\p"
	.string "Det er besøgeren! Besøgeren vandt en\n"
	.string "udekamp!\p"
	.string "Besøgeren laver en sejrsdans!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Besøgende snakker med {STR_VAR_1}!\p"
	.string "Det ser ud til, de skal kæmpe!\p"
	.string "Og…\p"
	.string "Det er {STR_VAR_1}! Besøgende har\n"
	.string "tabt!\p"
	.string "Besøgende ser nedslået!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Besøgende taler med {STR_VAR_1}!\p"
	.string "Det ser ud til, at de skal kæmpe!\p"
	.string "Og...\p"
	.string "Nej, besøgende har afvist!\p"
	.string "Der bliver ingen kamp alligevel!\p"
	.string "Fandt besøgende {STR_VAR_1}\n"
	.string "upassende?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Besøgende stirrer intenst på en plakat!\p"
	.string "Kan plakaten lide besøgende?\p"
	.string "...Men... Der er noget forstyrrende ved\n"
	.string "besøgendes blikke.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Besøgende trådte på en NOTE MAT!\p"
	.string "…Hmm… Besøgende komponerede en sjov\n"
	.string "melodi!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Besøgende snakker med {STR_VAR_1}!\p"
	.string "Det ser ud til, at de skal kæmpe mod\n"
	.string "hinanden!\p"
	.string "Og…\p"
	.string "Det ender uafgjort! Ingen vinder!\p"
	.string "Begge TRÆNERE virker meget skuffede!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Besøgende trådte på en SPIN MAT!\p"
	.string "Det ser ud til, at besøgende er svimmel!\p"
	.string "Besøgende vakler rundt! Pas på!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Besøgende rækker ud efter en SAND\n"
	.string "ORNAMENT!\p"
	.string "Åh!\p"
	.string "Den smuldrede! Den er faldet fra\n"
	.string "hinanden!\p"
	.string "Besøgende ser flov ud og skyldig!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Besøgende gnider en skrivebordet med\n"
	.string "deres finger!\p"
	.string "Åbenbart er besøgende ikke fan af\n"
	.string "støv!\p"
	.string "Besøgende er overraskende bekymret\n"
	.string "for renlighed!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Besøgende stirrer på en MURSTEN!\p"
	.string "Måske tænker besøgende på objektet på\n"
	.string "MURSTENEN.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Besøgeren går henover DET FASTE BRÆT.\p"
	.string "Besøgeren kigger nedad.\p"
	.string "Besøgeren virker overraskende tavst\n"
	.string "og forsigtigt!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Besøgende kigger opmærksomt på et\n"
	.string "HEGN!\p"
	.string "Mon en ny idé til en fælde er poppet op i\n"
	.string "besøgendes hoved?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Besøgende trådte på et GLITTERMÅTTE!\p"
	.string "Besøgende laver en række positioner!\p"
	.string "Besøgende ser ud til at drømme om at\n"
	.string "være en idol!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Besøgeren stirrer intenst på et DÆK!\p"
	.string "Mon besøgeren tænker på hvad for en\n"
	.string "bil, der bruger det?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Den besøgende kravlede op på et STAND!\p"
	.string "Den besøgende kigger ud over\n"
	.string "{STR_VAR_1} BASE fra højt oppe!\p"
	.string "Og…\p"
	.string "Lader et brøl løs! Den besøgende brøler!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Besøgende styrter hovedkulds ind i en\n"
	.string "NEDBRYDELIG DØR!\p"
	.string "Besøgende ler højlydt!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Besøgende taler med en DUKKE!\p"
	.string "…Det er lidt uhyggeligt…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Besøgende klatrer op ad stigen på en\n"
	.string "RUTSCHEBANE!\p"
	.string "Og…\p"
	.string "Besøgende rutsjer ned!\p"
	.string "Det ser ud til at besøgende har en\n"
	.string "festlig tid!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Besøgende klatrer op ad stigen på en\n"
	.string "RUTSCHEBANE!\p"
	.string "Og…\p"
	.string "Besøgende gik tilbage ned ad stigen!\p"
	.string "Mon besøgende pludselig fik kolde\n"
	.string "fødder?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Besøgeren trådte på en SPRINGMAT!\p"
	.string "Besøgeren sprang én gang!\p"
	.string "Sprang to gange!\p"
	.string "Og en vellykket landing!\p"
	.string "Besøgeren klapper! Hvilken\n"
	.string "solopræstation!$"

gTVSafariFanClubText00::
	.string "SAFARI FAN CLUB!\p"
	.string "REPORTER: I orden, venner! Kaster I\n"
	.string "SAFARI-BOLDE, hva'?\p"
	.string "I kan være helt sikker på, at jeg er her i\n"
	.string "SAFARI- ZONEN, fyldt med fantastiske\l"
	.string "POKéMON!\p"
	.string "Kom nu, lad os tage fat på det og snakke\n"
	.string "med denne gode person, SAFARI-GUIDEN!\p"
	.string "I orden, ven, hvordan ser de besøgende\n"
	.string "TRÆNERE ud?$"

gTVSafariFanClubText01::
	.string "VEJLEDNING: Alle virker meget\n"
	.string "engagerede.\p"
	.string "{STR_VAR_1} klarer sig især godt.\p"
	.string "Faktisk fangede {STR_VAR_1} før\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "Træneren er dygtig med {POKEBLOCK}S. Brugte\n"
	.string "{STR_VAR_2} den gang, tror jeg.$"

gTVSafariFanClubText03::
	.string "TRÆNEREN brugte ikke en eneste {POKEBLOCK}!\n"
	.string "Ikke en eneste!\p"
	.string "Det er en ekspert, hva'?$"

gTVSafariFanClubText04::
	.string "REPORTER: Er det rigtigt, så?\p"
	.string "Det lyder som om vores ven\n"
	.string "{STR_VAR_1} er en sej\l"
	.string "SAFARI-mester!\p"
	.string "GUIDE: Jeg håber TRÆNEREN kommer\n"
	.string "tilbage og viser os den fantastiske\l"
	.string "teknik.$"

gTVSafariFanClubText05::
	.string "VEJLEDNING: Ingen ser ud til at klare\n"
	.string "sig særlig godt.\p"
	.string "{STR_VAR_1} havde det særligt skidt.\p"
	.string "Hvad før var TRÆNEREN kun i stand til at\n"
	.string "fange {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "VEJLEDNING: Der er ingen, der synes at\n"
	.string "klare sig særlig godt.\p"
	.string "{STR_VAR_1} havde det især skidt.\p"
	.string "Ja, førhen fangede TRÆNEREN ingen\n"
	.string "POKéMON. Ikke en eneste!$"

gTVSafariFanClubText07::
	.string "TRÆNEREN bruger {POKEBLOCK}ER. Brugte\n"
	.string "{STR_VAR_2} den gang, tror jeg.\p"
	.string "Men, arh, jeg ville ønske, at TRÆNEREN\n"
	.string "blev lidt bedre til dette.$"

gTVSafariFanClubText08::
	.string "Jeg tror TRÆNEREN ville have bedre held\n"
	.string "med at bruge {POKEBLOCK}S, som slet ikke blev\l"
	.string "brugt den gang.$"

gTVSafariFanClubText09::
	.string "REPORTER: Er det rigtigt, så?\p"
	.string "Det lyder som om vores kammerat\n"
	.string "{STR_VAR_1} har brug for mere SAFARI\l"
	.string "krydderi.\p"
	.string "GUIDE: Jeg håber, at TRÆNEREN besøger\n"
	.string "igen og igen for at få styr på det.$"

gTVSafariFanClubText10::
	.string "REPORTER: Helt rigtigt, det er det! At\n"
	.string "tackle udfordringer er vigtigt!\p"
	.string "Seere, kom ned til SAFARIEN og påtag\n"
	.string "jer udfordringen selv!\p"
	.string "Indtil næste gang, hej-hej!$"

ContestLiveUpdates_Text_Intro::
	.string "“POKéMON KONKURRENCE LIVE\n"
	.string "OPDATERINGER!”\p"
	.string "MC: Tak fordi I deltager!\p"
	.string "Vi sender live fra det netop\n"
	.string "{STR_VAR_1} sted.\p"
	.string "Salen er stadig fyldt med et publikum,\n"
	.string "der ikke vil gå.\p"
	.string "Tilskuer: {STR_VAR_2}!\p"
	.string "Tilskuer: {STR_VAR_3}!\p"
	.string "MC: Som I lige har hørt, blev\n"
	.string "KONKURRENCEN vundet af POKéMON\l"
	.string "{STR_VAR_2} fra {STR_VAR_3}.\p"
	.string "Tilskuer: {STR_VAR_2}! Du er den\n"
	.string "bedste!\p"
	.string "Tilskuer: {STR_VAR_3}! Godt gået!\p"
	.string "MC: Lad os høre, hvad fansene har at\n"
	.string "sige om denne KONKURRENCE.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Tilskuer: {STR_VAR_2} var den\n"
	.string "bedste i både primær og sekundær\l"
	.string "bedømmelse!\p"
	.string "Den {STR_VAR_2} vil fortsat vinde!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Tilskuer: {STR_VAR_2} klarede sig\n"
	.string "ikke så godt i den første bedømmelse,\l"
	.string "men gjorde rent bord i den sekundære\l"
	.string "bedømmelse!\p"
	.string "Det var et mirakuløst comeback for den\n"
	.string "{STR_VAR_2}. Yippee!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Tilskuer: {STR_VAR_2} forblev\n"
	.string "konsekvent gennem både primær og\l"
	.string "sekundær bedømmelse.\p"
	.string "{STR_VAR_3} og {STR_VAR_2}, de\n"
	.string "er ingen almindelig kombination!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Tilskuer: Hvad angår at være\n"
	.string "{STR_VAR_1}, det {STR_VAR_2} var\l"
	.string "enestående.\p"
	.string "Jeg håber, det laver bedre appel næste\n"
	.string "gang, dog.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Tilskuer: Da {STR_VAR_2} blev\n"
	.string "nervøs, kunne jeg ikke lade være med at\l"
	.string "råbe opmuntrende til.\p"
	.string "Jeg vil gerne sige dette til den\n"
	.string "{STR_VAR_2}, “Tillykke!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Tilskuer: Selv jeg blev overrasket af\n"
	.string "{STR_VAR_2}'s appel!\p"
	.string "{STR_VAR_2}, du var fantastisk!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Tilskuer: Dét {STR_VAR_2}s\n"
	.string "kombination var forbløffende!\p"
	.string "Den rystede mig helt!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Tilskuer: Vinderens tiltrækningskraft\n"
	.string "fik mit hjerte til at køre løs!$"

ContestLiveUpdates_Text_WasCool::
	.string "Det var sejt! Du var sej!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}! Du var smuk!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}! Du var sød!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}! Du var smart!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}! Du var sej!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Tilskuer: Vinderens tiltrækningskraft\n"
	.string "har stadig min puls i vejret!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}! Du er det sidste ord\n"
	.string "inden for sejt!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}! Du er den smukkeste!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}! Du er simpelthen den\n"
	.string "sødeste!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}! Du er den klogeste\n"
	.string "blandt de kloge!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}! Du er den sejeste af de\n"
	.string "seje!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Tilskuer: Selv da {STR_VAR_2} tog en\n"
	.string "pause fra at appellere, kunne jeg ikke\l"
	.string "tage øjnene fra det.\p"
	.string "Jeg er fængslet af den {STR_VAR_2}.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Tilskuer: Da {STR_VAR_2} blev\n"
	.string "forskrækket af en anden POKéMONs\l"
	.string "tiltrækning, var jeg tæt på at græde.\p"
	.string "{STR_VAR_2}, du var sej! Godt\n"
	.string "klaret!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Tilskuer: Åh… Det {STR_VAR_2}'s\n"
	.string "{STR_VAR_3}! {STR_VAR_2}'s\l"
	.string "{STR_VAR_3}! {STR_VAR_2}'s\l"
	.string "{STR_VAR_3}! Hvordan kan det være så\l"
	.string "vidunderligt?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC: Nå, her har du det. Dette sted er\n"
	.string "fyldt med {STR_VAR_1}'s fans!\p"
	.string "Jeg bør også nævne, at en anden\n"
	.string "POKéMON, {STR_VAR_2}'s\l"
	.string "{STR_VAR_3},  fangede min\l"
	.string "opmærksomhed.\p"
	.string "{STR_VAR_2}'s {STR_VAR_3}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Det mislykkedes at lave en enkelt appel\n"
	.string "under den sekundære bedømmelse af\l"
	.string "nervøsitet.\p"
	.string "Næste gang vil jeg gerne se denne\n"
	.string "{STR_VAR_1} lave bare én appel.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Det kom sidst i begge primære og\n"
	.string "sekundære bedømmelser.\p"
	.string "Jeg håber, at {STR_VAR_1} vil træne\n"
	.string "denne {STR_VAR_2} og slette skammen\l"
	.string "fra denne utvivlsomt sidsteplads.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Den formåede ikke at udnytte publikums\n"
	.string "spænding og lave et passende appel.\p"
	.string "Vi håber, at {STR_VAR_1} vil lære,\n"
	.string "hvordan man mærker publikum og får dem\l"
	.string "op at ringe af spænding næste gang.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Mens du endte som nummer et i den\n"
	.string "primære bedømmelse, faldt dens appeller\l"
	.string "i den sekundære bedømmelse fladt.\p"
	.string "Den led et pinligt comeback-tab.\p"
	.string "Jeg er sikker på at {STR_VAR_1}\n"
	.string "studerer nu, hvordan de kan lave mere\l"
	.string "effektive appeller.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Publikum blev aldrig begejstret af dets\n"
	.string "appel under den sekundære bedømmelse.\p"
	.string "Vi håber, at det vil holde op med at\n"
	.string "bekymre sig om andre POKéMON og lære at\l"
	.string "henvende sig til publikummet mere.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Den tabte til {STR_VAR_1}s\n"
	.string "{STR_VAR_2} med kun en lille margin.\p"
	.string "Det må være hjerteskærende at komme så\n"
	.string "tæt på sejr for så at miste. \p"
	.string "Jeg ville ikke blive overrasket, hvis\n"
	.string "{STR_VAR_3} græd over dette udfald.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Det skuffede DOMMEREN ved at gentage\n"
	.string "de samme appeller.\p"
	.string "Det er en uforsonlig fejl i enhver\n"
	.string "KONKURRENCE, og POKéMONET betalte.\p"
	.string "{STR_VAR_1} burde føle sig skyldig\n"
	.string "over denne sørgelige optræden.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} gjorde en tappert\n"
	.string "forsøg, men...\p"
	.string "Alt var forgæves, afsluttede sidst.\p"
	.string "{STR_VAR_1} bør lære af dette\n"
	.string "nederlag og anvende den viden til noget\l"
	.string "godt.$"

ContestLiveUpdates_Text_Outro::
	.string "Jeg vil gerne afslutte dette program\n"
	.string "med vores sædvanlige afsked til\l"
	.string "vinderne.\p"
	.string "Denne gang er det {STR_VAR_1} og\n"
	.string "{STR_VAR_2}!\p"
	.string "Vært: Er alle klar? Alle sammen nu!\p"
	.string "Publikum: {STR_VAR_1}!\n"
	.string "{STR_VAR_2}! Tillykke! Du er vinderen\l"
	.string "af KONKURRENCEN!$"

gTVPokemonBattleUpdateText00::
	.string "“POKéMON KAMP OPDATERING!”\p"
	.string "Hold øje med resultaterne fra POKéMON\n"
	.string "kampe, som de kommer ind!$"

gTVPokemonBattleUpdateText01::
	.string "TRÆNERNE {STR_VAR_1} og\n"
	.string "{STR_VAR_2} stod over for hinanden i\l"
	.string "en {STR_VAR_3} KAMP.\p"
	.string "Denne kamp endte med sejr til\n"
	.string "{STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "I kampen var {STR_VAR_1}s\n"
	.string "{STR_VAR_2} en formidabel kraft der\l"
	.string "brugte {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_1}'s {STR_VAR_2} havde\n"
	.string "en svag præstation, der virkelig gjorde\l"
	.string "ondt.$"

gTVPokemonBattleUpdateText04::
	.string "Tillykke med din sejr, {STR_VAR_1}!\p"
	.string "Og til den slagne {STR_VAR_2}, håber\n"
	.string "vi på et bedre resultat næste gang!\p"
	.string "Dette afslutter denne episode af\n"
	.string "“POKéMON KAMP OPDATERING!”$"

gTVPokemonBattleUpdateText05::
	.string "Holdene til TRÆNERE {STR_VAR_1} og\n"
	.string "{STR_VAR_2} mødtes i en MULTI KAMP.\p"
	.string "Denne kamp endte med sejr til holdet\n"
	.string "fra {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "I kampen var {STR_VAR_2} på\n"
	.string "{STR_VAR_1}s hold en formidabel\l"
	.string "kraft ved brug af {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "Den svage præstation af\n"
	.string "{STR_VAR_3} på {STR_VAR_2}s hold\l"
	.string "gjorde virkelig ondt.\p"
	.string "Tillykke med dit holds sejr,\n"
	.string "{STR_VAR_1}!\p"
	.string "Hvad angår det besejrede\n"
	.string "{STR_VAR_2}s hold, håber vi på et\l"
	.string "bedre resultat næste gang!\p"
	.string "Dette afslutter denne episode af\n"
	.string "“POKéMON BATTLE UPDATE!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Åh! Vi har lige spottet en sej-\n"
	.string "udseende TRÆNER her af alle steder!\p"
	.string "Okay, rul kameraet! Lad os få denne\n"
	.string "interview.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Åh! Du er {PLAYER}! Hej! Husker\n"
	.string "du os fra sidste gang?\p"
	.string "Kan du vise os, hvor meget stærkere du\n"
	.string "er blevet? Okay, start interviewet!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: Mine øjne løb ikke! Jeg har\n"
	.string "fundet en forbløffende TRÆNER!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Fantastisk! Fantastisk! Hvem er\n"
	.string "du?!\p"
	.string "Jeg vidste, vi var på noget vildt, da vi\n"
	.string "fik øje på dig!\p"
	.string "Åh, lad mig forklare. Vi rejser rundt\n"
	.string "overalt og interviewer alle slags\l"
	.string "TRÆNERE.\p"
	.string "Så, vil du give os lidt af din tid til et\n"
	.string "interview?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Husker du? Det er citatet, du gav os\n"
	.string "som det afgørende i kampen sidste gang.\l"
	.string "Jeg glemmer aldrig sådan noget!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "Sidste gang vi kæmpede, stampede du os,\n"
	.string "før vi kunne forberede os…\p"
	.string "Nå, hvad synes du? Vil du interviewes\n"
	.string "igen?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "Sidste gang vi kæmpede, kastede du ikke\n"
	.string "en POKé BALL mod os?\p"
	.string "Vi var helt målløse! Så fortalte vi det\n"
	.string "til alle, ja, alle sammen!\p"
	.string "Nå, hvad siger du så? Vil du have en\n"
	.string "interview runde til?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "Sidste gang vi kæmpede, narrede\p"
	.string "dine genstandsevner os snedigt. Nå,\n"
	.string "hvad synes du? Vil du interviewes igen?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "Sidste gang vi kæmpede, formåede vi at\n"
	.string "se respektable ud.\p"
	.string "Men hvad synes du? Vil du interviewes\n"
	.string "igen?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Nå, hvad synes du? Vil du interviewes\n"
	.string "igen?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Vil du? Tak!\p"
	.string "Okay, jeg har brug for dig til at\n"
	.string "beskrive dine følelser om vores kamp,\l"
	.string "men det skal være kort og sødt. Skyd løs!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, ja! Det er den perfekte\n"
	.string "afslutning!\p"
	.string "Jeg har en fornemmelse af, at det her\n"
	.string "vil blive en fantastisk tv-show.\p"
	.string "Der er en chance for, at de vil vise det\n"
	.string "på tv, så sørg for at kigge efter os!\p"
	.string "Okay! Vi vil se dig igen!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Åh…\p"
	.string "Okay, men give ikke op! Vi vil holde øje\n"
	.string "med dig!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: Vi vil holde øje med dig! $"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Er der en stærk TRÆNER et sted\n"
	.string "med mange POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Wow, du er noget!\p"
	.string "Du er blevet meget stærk--meget--\n"
	.string "siden vi sidst kæmpede.\p"
	.string "Vi havde ret angående dig, da vi\n"
	.string "opdagede dig som en sej TRÆNER.\p"
	.string "Så, hvad siger du? Er du villig til at\n"
	.string "give os et interview denne gang?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: Det var en intens kamp! Fik du\n"
	.string "det hele med på kameraet?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Hej, se lige her! En sej udseende\n"
	.string "TRÆNER her, af alle steder! Kameraet\l"
	.string "kører!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Hey, se lige her! Jeg husker dig!\p"
	.string "Jeg får denne kamp med det her kamera!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: Du er en naturtalent! Jeg har fået\n"
	.string "nogle fantastiske optagelser lige her!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Har du kun den ene POKéMON og det\n"
	.string "er det?\p"
	.string "Hvis du havde flere POKéMON, ville det\n"
	.string "give bedre optagelser, men...$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Ja, vi har virkelig spottet en sej\n"
	.string "TRÆNER. Det her er et kæmpe scoop for\l"
	.string "os!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Jep, jeg har det hele. Hele den kamp\n"
	.string "er på kameraet.$"

gTVInSearchOfTrainersText00::
	.string "PÅ JAGT EFTER TRÆNERE…\p"
	.string "GABBY: Hej! I dag besøger jeg et område\n"
	.string "i nærheden af {STR_VAR_1}.\p"
	.string "Vi prøver at spotte nogle nye talenter\n"
	.string "på området.\p"
	.string "I dag rettede vi vores linse mod TRÆNER\n"
	.string "{PLAYER}.\p"
	.string "Der er noget ved denne TRÆNER, der har\n"
	.string "vakt vores interesse.$"

gTVInSearchOfTrainersText01::
	.string "Vi har kæmpet mod {PLAYER} før, men vi\n"
	.string "kan bekræfte, at TRÆNEREN klart er\l"
	.string "blevet bedre siden sidst.\p"
	.string "Jeg vidste, at vi var på sporet af en\n"
	.string "særlig person, da vi opdagede dig,\l"
	.string "TRÆNER!$"

gTVInSearchOfTrainersText02::
	.string "Den bedste måde at afgøre, hvor stærk\n"
	.string "en TRÆNER er...\p"
	.string "Nå, den hurtigste måde er at kæmpe. Og\n"
	.string "så begyndte vores undersøgelse!\p"
	.string "… …\p"
	.string "Sådan endte vi i kamp mod {PLAYER}.\p"
	.string "I en dominerende præstation blev vi\n"
	.string "fladt ud, rullet sammen og smidt væk!\p"
	.string "{PLAYER} er nådesløst stærk...\p"
	.string "Her er vores indtryk efter at have\n"
	.string "kæmpet mod vores fremhævede TRÆNER.$"

gTVInSearchOfTrainersText03::
	.string "Kombinationen af {STR_VAR_1} og\n"
	.string "{STR_VAR_3} var guddommelig!\p"
	.string "Synet af dem--{STR_VAR_1} og\n"
	.string "{STR_VAR_3}-- der støtter hinanden\l"
	.string "selv løst i kampens hede…\p"
	.string "Det var et vidunderligt syn at skue!\p"
	.string "{STR_VAR_2} var trænerens sidste\n"
	.string "træk i vores kamp.\p"
	.string "Trækket {STR_VAR_2} er\n"
	.string "{STR_VAR_1} og {STR_VAR_3}'s\l"
	.string "tegn på venskab!$"

gTVInSearchOfTrainersText04::
	.string "…Jeg mistede tilliden til mig selv som et\n"
	.string "resultat af vores møde.\p"
	.string "Vi blev slået inden vi kunne igangsætte\n"
	.string "et enkelt angreb. Åhhhh… Hulke…\p"
	.string "Ikke desto mindre er {PLAYER}s kampe\n"
	.string "værd at se.\p"
	.string "Jeg anbefaler selvsikre TRÆNERE at\n"
	.string "udfordre {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Der er kun een ting at sige. Vov ikke at\n"
	.string "kaste en POKé BALL under en TRÆNER\l"
	.string "duel!\p"
	.string "{PLAYER} er helt sikkert stærk, men\n"
	.string "har ingen anelse om de grundlæggende\l"
	.string "regler.\p"
	.string "Til vores TV-publikum har jeg en\n"
	.string "anmodning.\p"
	.string "Hvis du ser {PLAYER}, bedes du advare\n"
	.string "TRÆNEREN!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} er ferm til at læse\n"
	.string "modstanderens handlinger.\p"
	.string "Timing af genstandsbrug var\n"
	.string "bemærkelsesværdigt effektivt!$"

gTVInSearchOfTrainersText07::
	.string "Ærligt talt troede jeg, at jeg måske\n"
	.string "endda var ret god.\p"
	.string "Selvom vi endte med at tabe, havde vi en\n"
	.string "hårdt kæmpet kamp.\p"
	.string "Men hvis du kæmper med at slå mig, har du\n"
	.string "stadig et stykke vej at gå, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Efter vores kamp bad vi {PLAYER} om\n"
	.string "en kort opsummering.\p"
	.string "TRÆNEREN svarede, “{STR_VAR_1}.”\p"
	.string "{PLAYER}s POKéMON {STR_VAR_2} og\n"
	.string "{STR_VAR_3}… Og “{STR_VAR_1}”…\p"
	.string "Mmm! Det er dybt! Der er dyb betydning\n"
	.string "bag den kommentar!\p"
	.string "Det er ingen overraskelse - en god\n"
	.string "TRÆNER har gode ting at sige.\p"
	.string "Det er alt for i dag! Vi ses igen i vores\n"
	.string "næste udsendelse!$"

ContestLadyShow_Text_Intro::
	.string "“POKéMON KONKURRENCE LIVE\n"
	.string "OPDATERINGER!”\p"
	.string "MC: Undskyld, at vi afbryder den\n"
	.string "normale udsendelse, og tak fordi du er\l"
	.string "med!\p"
	.string "Vi bringer dette live fra stedet for\n"
	.string "netop afsluttede {STR_VAR_1}!\p"
	.string "Tilskuere: ?!!!!\p"
	.string "MC: Åh! Det ser ud til, at KONKURRENCENS\n"
	.string "deltagere er på vej hertil!\p"
	.string "Jeg vil forsøge at få en spontan\n"
	.string "interview til jer derhjemme!\p"
	.string "Tilskuere: ?!!!! ?!!!!$"

ContestLadyShow_Text_Won::
	.string "MC: Undskyld! Tak fordi du deltager i\n"
	.string "vores live TV-show!\p"
	.string "Må jeg lykønske dig med din sejr?\p"
	.string "Hvad var den afgørende faktor i\p"
	.string "dagens fantastiske sejr?\p"
	.string "SKØNHED: Vi gav vores bedste i\p"
	.string "dag, min {STR_VAR_2} og jeg!\p"
	.string "Men jeg er sikker på, at vi ikke\p"
	.string "ville have klaret det, hvis det ikke var\p"
	.string "for al den hjælp, vi modtog op til\n"
	.string "KONKURRENCEN!\p"
	.string "MC: Har du en helt speciel person,\p"
	.string "som du gerne vil dele din glæde med? Lad\n"
	.string "os høre det live!\p"
	.string "SKØNHED: Hej derude!\p"
	.string "{STR_VAR_3}! Ser du med? Vi gjorde\n"
	.string "det! Tak!$"

ContestLadyShow_Text_Lost::
	.string "MC: Undskyld! Tak fordi du er med på\n"
	.string "live TV!\p"
	.string "Er du skuffet over den vending af\n"
	.string "begivenhederne? Har du nogen\l"
	.string "kommentarer?\p"
	.string "BEAUTY: Det er hjerteknusende… Min\n"
	.string "{STR_VAR_2} og jeg gjorde vores\l"
	.string "bedste…\p"
	.string "Men jeg føler, at jeg har skuffet alle,\n"
	.string "der har støttet os igennem dette.\p"
	.string "MC: Jeg hader at sige det, men POKéMONs\n"
	.string "farvning er lidt mangelfuld.\p"
	.string "BEAUTY: {STR_VAR_3}, undskyld… Jeg\n"
	.string "vil gøre det bedre næste gang, jeg\l"
	.string "sværger… …Snøft… Waaaaah!\p"
	.string "Tilskuere: Ser du det der? Den stakkels\n"
	.string "pige!\p"
	.string "MC: Øh… Øh-oh…\p"
	.string "Øh… Det er alt den tid, vi har i dag! Tak\n"
	.string "fordi I fulgte med!$"

ContestLadyShow_Text_LostBadly::
	.string "MC: Undskyld! Tak fordi du er med os på\n"
	.string "live TV!\p"
	.string "Hvordan gik din KONKURRENCEoptræden?\p"
	.string "SKØNHED: Ingenting gik godt... Af en\n"
	.string "eller anden grund kunne min\l"
	.string "{STR_VAR_2} ikke tiltrække nogen\l"
	.string "popularitet.\p"
	.string "MC: Jeg hader at sige det, men\n"
	.string "POKéMON'ens farvevalg er lidt\l"
	.string "manglende.\p"
	.string "SKØNHED: ...... ...Snøft... Buuuuh!\p"
	.string "Tilskuere: Ser du det der? Den stakkels\n"
	.string "pige!\p"
	.string "MC: Øh... Øh-oh...\p"
	.string "Øh... Det er alt, hvad vi har tid til i dag!\n"
	.string "Tak for at følge med!$"



