@ TRANSLATED

VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Langt væk, dybt inde i EVER GRANDE\n"
	.string "CITY, ligger POKéMON LIGAEN.\p"
	.string "TRÆNERNE, der samles der, er alle\n"
	.string "skræmmende veltrænede.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "I POKéMON LIGAEN, tror jeg, at reglerne\n"
	.string "siger, at du skal kæmpe mod DE FIRE\l"
	.string "SUPER TRÆNERE i træk.\p"
	.string "Hvis du taber til en af dem, skal du\n"
	.string "starte din udfordring forfra fra den\l"
	.string "første.$"



