@ TRANSLATED

SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "En undersøisk vulkan erupterede og\n"
	.string "tvang sig op fra dybet.\p"
	.string "Dens krater steg op fra havet og\n"
	.string "fyldtes med regnvand.\p"
	.string "Sådan opstod SOOTOPOLIS BY.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "Hulen, der forbinder SOOTOPOLIS og\n"
	.string "omverdenen…\p"
	.string "Det virker som om hulen blev lavet\n"
	.string "for at holde noget inde.\p"
	.string "Eller bilder jeg mig bare noget ind?$"



