@ TRANSLATED

PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "NORMAN blev vores bys nye\n"
	.string "GÅRDLÆRER.\p"
	.string "Jeg tror, han kaldte sin familie hertil\n"
	.string "fra et fjernt sted.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "Jeg kæmpede mod NORMAN en gang, men,\n"
	.string "puha, han var alt for stærk.\p"
	.string "Hvordan skal jeg sige det?\p"
	.string "Jeg fik bare fornemmelsen af,\n"
	.string "at han lever for POKéMON.$"



