@ TRANSLATED

OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Når en POKéMON-kamp starter, den\n"
	.string "til venstre på listen kommer ud først.\p"
	.string "Så når du får flere POKéMON i din\n"
	.string "gruppe, så prøv at skifte rundt på\n"
	.string "rækkefølgen af dine POKéMON.\p"
	.string "Det kunne give dig en fordel.$"



