@ TRANSLATED

OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Når en POKéMON-kamp starter, den til\n"
	.string "venstre på listen kommer ud først.\p"
	.string "Så når du får flere POKéMON i din gruppe, så\n"
	.string "prøv at skifte rundt på rækkefølgen af dine\l"
	.string "POKéMON.\p"
	.string "Det kunne give dig en fordel.$"



