@ TRANSLATED

@ Note: local IDs shared with scripts.inc for LilycoveCity_ContestLobby
.set LOCALID_MAN, 3
.set LOCALID_BOY, 9
.set LOCALID_TWIN, 10
.set LOCALID_POKEFAN_F, 15
.set LOCALID_EXPERT_M, 16
.set LOCALID_GIRL, 17

.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks:
	.string "Orkede du at lave nogle {POKEBLOCK} med\n"
	.string "denne gamle rotte?$"

BerryBlender_Text_Excellent:
	.string "Fremragende!$"

BerryBlender_Text_MadeOldTimerSad:
	.string "Åh… Du har gjort denne gamle sjæl ked af\n"
	.string "det…$"

BerryBlender_Text_KnowHowToMakePokeblocks:
	.string "Ved du, hvordan man laver en {POKEBLOCK}?$"

BerryBlender_Text_LetsBerryBlender:
	.string "Lad os komme i gang så!\p"
	.string "Lad os BÆRBLANDE!$"

BerryBlender_Text_ExplainBerryBlending:
	.string "Okay, lidt forklaring, så.\p"
	.string "Åh, du behøver ikke at bekymredig, det\n"
	.string "er ganske simpelt.\p"
	.string "Når BLENDERENS pil kommer tildin markør,\n"
	.string "så tryk bare på A-Knappen.\p"
	.string "Det er alt, hvad du behøver atgøre. Du\n"
	.string "vil se, hvor let det er, nårdu prøver.$"

BerryBlender_Text_DontHaveAnyBerries:
	.string "Åh? Du har ikke nogen BÆR?\p"
	.string "Hvis du ikke har nogen BÆR, kan du ikke\n"
	.string "lave nogen {POKEBLOCK}S.$"

BerryBlender_Text_CanHaveOneOfMyBerries:
	.string "Nå, det går jo slet ikke, gør det?\p"
	.string "Hvis du ikke har noget imod rester, kan\n"
	.string "du få en af mine BÆR.\p"
	.string "På den måde kan vi lave nogle {POKEBLOCK}S\n"
	.string "sammen ved hjælp af BÆRBLANDEREN.$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:
	.string "Hvis jeg havde nogle BÆR til overs, ville\n"
	.string "jeg med glæde give dig en…\p"
	.string "Men jeg har desværre ingen atoverskud i\n"
	.string "dag. Vi bliver nødt til at gøre det\l"
	.string "enanden gang.$"

BerryBlender_Text_PokeblockCaseIsFull:
	.string "Men din {POKEBLOCK} BEHOLDER er fuld.\p"
	.string "Du burde bruge nogle {POKEBLOCK}S inden du\n"
	.string "kommer tilbage til mig.$"

BerryBlender_Text_DontHavePokeblockCase:
	.string "Men du har ikke et {POKEBLOCK} ETUI.\p"
	.string "Du burde få et {POKEBLOCK} ETUI og så komme\n"
	.string "og besøge mig.$"

BerryBlender_Text_LetsGetBlendingAlready:
	.string "Lad os komme i gang med at blande\n"
	.string "allerede!$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:
	.string "Jeg undrer mig over, hvilken slags\n"
	.string "{POKEBLOCK} jeg får? Det er så spændende!$"

BerryBlender_Text_WantToBlendPokeblocksWithUs:
	.string "Hej med dig! Vil du blande nogle {POKEBLOCK}S\n"
	.string "med os?$"

BerryBlender_Text_Okay:
	.string "Okay!$"

BerryBlender_Text_ThatsTooBad:
	.string "Det er ærgerligt…\p"
	.string "Men vi vil altid være her, når du får lyst\n"
	.string "til at blande!$"

BerryBlender_Text_KnowHowToMakePokeblocks2:
	.string "Selvfølgelig ved du, hvordan man\n"
	.string "blander {POKEBLOCK}S, ikke?$"

BerryBlender_Text_LetsBerryBlender2:
	.string "Lad os komme i gang så!\p"
	.string "Lad os BÆRBLANDE!$"

BerryBlender_Text_ExplainBerryBlending2:
	.string "Okay! Lad mig forklare det til dig!\p"
	.string "Når BLENDERENS pil stopper ved dit\n"
	.string "markør, skal du bare trykke på\l"
	.string "A-knappen.\p"
	.string "Det er alt, hvad der skal til. Ret let,\n"
	.string "ikke også?$"

BerryBlender_Text_DontHaveAnyBerries2:
	.string "Åh, men vent lige et øjeblik her… Du har\n"
	.string "ingen BÆR.\p"
	.string "Du kan ikke lave nogen {POKEBLOCK}S uden\n"
	.string "BÆR…\p"
	.string "Vi vil altid være her, når du får fat i\n"
	.string "nogle BÆR til at blande.$"

BerryBlender_Text_PokeblockCaseIsFull2:
	.string "Åh, men vent lige et øjeblik her… Din\n"
	.string "{POKEBLOCK} SAG er fuld.\p"
	.string "Du burde bruge nogle {POKEBLOCK}S og kom så\n"
	.string "tilbage.$"

BerryBlender_Text_DontHavePokeblockCase2:
	.string "Åh, men vent lige et øjeblik her… Du har\n"
	.string "ikke en {POKEBLOCK}-BEHOLDER.\p"
	.string "Du burde skaffe dig en\n"
	.string "{POKEBLOCK}-BEHOLDER og så komme tilbage.$"

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup:
	.string "Hej, hallojs! Havde du lyst til at lave\n"
	.string "nogle {POKEBLOCK}S sammen med vores gruppe?$"

BerryBlender_Text_OhDear:
	.string "Åh, kære!$"

BerryBlender_Text_LeftUsInShock:
	.string "Åh, du godeste... \p"
	.string "Du har chokeret os!$"

BerryBlender_Text_KnowHowToMakePokeblocks3:
	.string "Selvfølgelig ved du, hvordan man laver\n"
	.string "{POKEBLOCK}S, ikke?$"

BerryBlender_Text_LetsBerryBlender3:
	.string "Okay, kære! Lad os komme i gang!\p"
	.string "Lad os BÆRBLANDE!$"

BerryBlender_Text_ExplainBerryBlending3:
	.string "Åh, kære!\p"
	.string "Så vil jeg forklare det pænt til dig.\p"
	.string "Når BLENDERENS pil drejer sig hen til\n"
	.string "din markør, tryk på A-knappen.\p"
	.string "Det er alt, hvad der kræves. Er det ikke\n"
	.string "simpelt?$"

BerryBlender_Text_DontHaveAnyBerries3:
	.string "Du har ikke nogen BÆR, gør du?\p"
	.string "Hvis du ikke har nogen BÆR, kan du ikke\n"
	.string "lave nogen {POKEBLOCK}S.\p"
	.string "Vi vil altid lave {POKEBLOCK}S her, så lad os\n"
	.string "lave nogle sammen, når du får et BÆR\l"
	.string "eller to.$"

BerryBlender_Text_PokeblockCaseIsFull3:
	.string "Din {POKEBLOCK}-BEHOLDER er fuld, ser det ud\n"
	.string "til.\p"
	.string "Du burde bruge nogle {POKEBLOCK}S og så\n"
	.string "komme tilbage.$"

BerryBlender_Text_DontHavePokeblockCase3:
	.string "Du har ikke fået en {POKEBLOCK} KASSE endnu,\n"
	.string "ser det ud til.\p"
	.string "Du skal have en {POKEBLOCK} KASSE før du\n"
	.string "kommer tilbage.$"

BerryBlender_Text_SetNewBlenderRecord:
	.string "Okay! I dag bliver dagen, hvor jeg\n"
	.string "sætter en ny BLENDER hastighedsrekord!$"

BerryBlender_Text_LookGoodAtBlendingJoinUs:
	.string "Åh, kære! Du ser ud til at være god til at\n"
	.string "blande.\p"
	.string "Vil du være med hos os?$"

BerryBlender_Text_MakeDeliciousPokeblocks:
	.string "Jeg vil lave lækre {POKEBLOCK}S og gøre mine\n"
	.string "POKéMON sødere.$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
	.string "{POKEBLOCK}S vil blive lavet med dine venner \n"
	.string "af BÆR i BÆRBLANDEREN.\p"
	.string "Er det okay at gemme spillet før at\n"
	.string "forbinde med dine venner?$"

BerryBlender_Text_SearchingForFriends:
	.string "Søger efter dine venner… … …\n"
	.string "B-knappen: Annullér$"

BerryBlender_Text_Player1Arrived:
	.string "{STR_VAR_1} ankom.$"

BerryBlender_Text_Player1And2Arrived:
.string "{STR_VAR_1} og {STR_VAR_2} er ankommet.$"

BerryBlender_Text_AllPlayersArrived:
	.string "{STR_VAR_1}, {STR_VAR_2} og\n"
	.string "{STR_VAR_3} ankom.$"

BerryBlender_Text_NoBerriesLink:
	.string "Du har ingen BÆR. BÆRBLÆNDEREN kan ikke\n"
	.string "bruges.$"

BerryBlender_Text_PokeblockCaseIsFullLink:
	.string "Din {POKEBLOCK} SAG er fuld. BÆRBLANDEREN\n"
	.string "kan ikke bruges.$"

BerryBlender_Text_DontHavePokeblockCaseLink:
	.string "Du har ikke en {POKEBLOCK} TASKE.\n"
	.string "BÆRBLANDEREN kan ikke bruges.$"

BerryBlender_Text_LoveMakingPokeblocks:
	.string "Jeg elsker at lave {POKEBLOCK}S.\p"
	.string "Jeg har altid nogle BÆR med mig.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:
	.string "Hvis du har lyst, kan vi lave lidt\n"
	.string "{POKEBLOCK}S sammen ved at bruge BERRY\l"
	.string "BLENDEREN.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:
	.string "Nå? Du har ingen BÆR?\p"
	.string "Det kan vi ikke have.\p"
	.string "Hvis du ikke har noget imod rester, kan\n"
	.string "du få en af mine BÆR.$"

BerryBlender_Text_UseItToMakePokeblocksTogether:
	.string "Vi vil bruge det til at lave {POKEBLOCK}\n"
	.string "sammen i BERRY BLENDER'en.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
	.string "Åh? Du har ingen BÆR?\p"
	.string "Hvis jeg havde nogle til overs, ville jeg\n"
	.string "med glæde give dig en…\p"
	.string "Men jeg har ikke nogen at undvære i dag.\n"
	.string "Undskyld for det.$"

BerryBlender_EventScript_BerryBlender1::
	lockall
	goto_if_unset FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_EXPERT_M, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1:
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry:
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1:
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1:
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending:
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2::
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_MAN, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2:
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2:
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2:
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender2
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3::
	lockall
	setvar VAR_0x8008, LOCALID_POKEFAN_F
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_BOY, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3:
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3:
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3:
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender3
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent:
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries:
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_BlendWithBlendMaster
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster:
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	call_if_eq VAR_RESULT, NO, BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending:
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase:
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull:
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man::
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF::
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin::
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM::
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry:
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_ExpertMPlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries:
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry:
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace:
	walk_in_place_faster_right
	step_end

BerryBlender_EventScript_BerryBlenderLink::
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderSaveGame
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame:
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryDoLinkBlender
	goto_if_eq VAR_RESULT, NO, BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries:
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender:
	call Common_EventScript_SaveGame
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	waitstate
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_SpawnLinkPartners
	goto_if_eq VAR_RESULT, LINKUP_SOMEONE_NOT_READY, BerryBlender_EventScript_CloseLinkNotReady
	goto_if_eq VAR_RESULT, LINKUP_DIFF_SELECTIONS, BerryBlender_EventScript_CloseLinkDifferentSelections
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_CloseLink
	goto_if_eq VAR_RESULT, LINKUP_CONNECTION_ERROR, BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink:
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink:
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink:
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending:
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
	fadescreen FADE_TO_BLACK
	removeobject 240 @ Unclear where these local IDs come from,
	removeobject 239 @ but presumably they'd be the 4 link players
	removeobject 238
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender:
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady:
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections:
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink:
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError:
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners:
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived:
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader:
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader:
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, FALSE
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup:
	call BerryBlender_EventScript_TryBecomeLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup:
	call BerryBlender_EventScript_TryJoinLinkGroup
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader:
	special TryBecomeLinkLeader
	waitstate
	return

BerryBlender_EventScript_TryJoinLinkGroup:
	special TryJoinLinkGroup
	waitstate
	return

BerryBlender_EventScript_LinkLeaderDecided:
	goto BerryBlender_EventScript_SpawnLinkPartners
	end



