@ TRANSLATED

OldaleTown_House2_MapScripts::
	.byte 0

OldaleTown_House2_EventScript_Woman::
	msgbox OldaleTown_House2_Text_PokemonLevelUp, MSGBOX_NPC
	end

OldaleTown_House2_EventScript_Man::
	msgbox OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon, MSGBOX_NPC
	end

OldaleTown_House2_Text_PokemonLevelUp:
	.string "Når POKéMON kæmper, vil de med tiden\n"
	.string "niveauop og blive stærkere.$"

OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon:
	.string "Hvis dine POKéMON bliver stærkere, kan du\n"
	.string "komme længere væk herfra.$"



