@ TRANSLATED

OldaleTown_House2_MapScripts::
	.byte 0

OldaleTown_House2_EventScript_Woman::
	msgbox OldaleTown_House2_Text_PokemonLevelUp, MSGBOX_NPC
	end

OldaleTown_House2_EventScript_Man::
	msgbox OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon, MSGBOX_NPC
	end

OldaleTown_House2_Text_PokemonLevelUp:
	.string "Når POKéMON kæmper, vil de\n"
	.string "med tiden niveauop og blive stærkere.$"

OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon:
	.string "Hvis dine POKéMON bliver\n"
	.string "stærkere, kan du komme længere\n"
	.string "væk herfra.$"



