@ TRANSLATED

PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "At rejse er vidunderligt!\p"
	.string "Da jeg var ung, strejfede jeg\n"
	.string "havene og bjergene!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Suk…\p"
	.string "Jeg ville ønske, jeg kunne tage på et\n"
	.string "eventyr med nogle POKéMON…\p"
	.string "Kravle gennem fugtigt græs…\n"
	.string "Bestige stejle bjerge…\p"
	.string "Krydse det brusende hav…\n"
	.string "Vandre rundt i mørke huler…\p"
	.string "Og nogle gange endda få lidt\n"
	.string "hjemve…\p"
	.string "Det må være fantastisk at rejse!$"



