@ TRANSLATED

AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper::
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring:
	.string "Det her er det perfekte sted at gå på opdagelse!\n"
	.string "Det er spændende her!\p"
	.string "Jeg er sikker på, at der er fantastiske skatte\n"
	.string "om bord.$"



