@ TRANSLATED

FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "Mens vi taler om POKéDEXER, kom jeg i\n"
	.string "tanke om noget.\p"
	.string "Jeg mødte denne TRÆNER, STEVEN, da jeg\n"
	.string "ledte efter sjældne sten.\p"
	.string "Huha, han havde nogle fantastiske\n"
	.string "POKéMON med sig.\p"
	.string "De var ikke bare sjældne, de var trænet\n"
	.string "til skræmmende ekstremer!\p"
	.string "Han er måske endda stærkere end\n"
	.string "GYMLEDREN i denne by…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "Hvad er det for noget, du har der?\p"
	.string "… … … … … …\p"
	.string "Åh, det hedder en POKéDEX? Det er\n"
	.string "virkelig fedt!$"



