@ TRANSLATED

SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "At designe et stort skib er mere\n"
	.string "som at lave en stor bygning end at\n"
	.string "sætte et transportmiddel sammen.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "Synes du ikke, det er mærkeligt, at\n"
	.string "et skib lavet af tungt jern flyder?\p"
	.string "Det flyder på grund af en princip\n"
	.string "kaldet opdrift.$"



