@ TRANSLATED

LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Den største gåde på denne planet er at\n"
	.string "finde i havets dybder.\p"
	.string "Det siges i hvert fald af nogen…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Der er en dyb undersøisk kløft mellem\n"
	.string "MOSSDEEP og SOOTOPOLIS.\p"
	.string "Det var i hvert fald det, nogen fortalte\n"
	.string "mig.$"



